### DISCUSSION TITLE
servicemonitors configured but nothing shows as up

### DISCUSSION THREAD

**Discussion by ndarilek** [prometheus-operator/prometheus-operator#4081] [Q&A]
I'm trying to monitor several apps, but though they show up in my targets list, I see 0/0 up for each one.

I'm prototyping this setup in a Minikube cluster. I'll include my configs below, but I start from bundle.yaml, then apply configs mostly from the getting started guide. I see tips in the troubleshooting guide for addressing 403 errors from the scraper, but I see no 403 anywhere so don't know if that is my issue, and I'm not sure whether those conditions apply to a stock Minikube cluster.

I'm fairly new to Prometheus, and reached for this operator because I'm strapped for time/experience and figure this setup probably gets more right than I could. I've followed the troubleshooting docs, and it does appear that my apps are in the generated configuration.

Insight welcome. I hate to just shotgun a bunch of possible solutions without any idea what is failing, and I can't find any hints as to what it might be.

Anyhow, here are my configs. Again, I start with bundle.yaml from the repo:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      scope: backend
  replicas: 1
  externalUrl: http://localhost:8080/prometheus
  resources:
    requests:
      memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: main
---
﻿apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /prometheus(/|$)(.*)
        backend:
          serviceName: prometheus
          servicePort: web
```

And a sample manifest, complete with monitoring. /metrics works and returns values:

```
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - targetPort: http-api
      port: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: gcr.io/jit-access-dev/auth
          resources:
            limits:
              cpu: 1
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 50Mi
          env:
            - name: AUTH0_DOMAIN
              value: skrybe.auth0.com
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth-auth0-credentials
                  key: client_id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-auth0-credentials
                  key: client_secret
            - name: PGHOST
              value: postgres
            - name: PGDATABASE
              value: postgres
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          ports:
            - name: http-api
              containerPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth
  labels:
    scope: backend
spec:
  selector:
    app: auth
  endpoints:
  - port: http-api
    path: /metrics
```

And logs with `logLevel: debug`. I may have missed something here--I'm a screen reader user and combing logs with speech is a tedious affair, but I searched for "error" and "403" and came up blank:

```
level=info ts=2019-08-23T14:49:57.98908344Z caller=main.go:302 msg="Starting Prometheus" version="(version=2.7.1, branch=HEAD, revision=62e591f928ddf6b3468308b7ac1de1c63aa7fcf3)"
level=info ts=2019-08-23T14:49:57.989123378Z caller=main.go:303 build_context="(go=go1.11.5, user=root@f9f82868fc43, date=20190131-11:16:59)"
level=info ts=2019-08-23T14:49:57.989138536Z caller=main.go:304 host_details="(Linux 4.15.0 #1 SMP Fri Aug 2 16:17:56 PDT 2019 x86_64 prometheus-main-0 (none))"
level=info ts=2019-08-23T14:49:57.989151478Z caller=main.go:305 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-08-23T14:49:57.989162324Z caller=main.go:306 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-08-23T14:49:57.989607809Z caller=main.go:620 msg="Starting TSDB ..."
level=info ts=2019-08-23T14:49:57.989677888Z caller=web.go:416 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-08-23T14:49:57.993586513Z caller=main.go:635 msg="TSDB started"
level=info ts=2019-08-23T14:49:57.993636322Z caller=main.go:695 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-08-23T14:49:57.994234747Z caller=kubernetes.go:201 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=debug ts=2019-08-23T14:49:57.994775398Z caller=manager.go:217 component="discovery manager scrape" msg="Starting provider" provider=*kubernetes.SDConfig/0 subs="[default/auth/0 default/backend/0]"
level=info ts=2019-08-23T14:49:57.994821898Z caller=main.go:722 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-08-23T14:49:57.994830916Z caller=main.go:589 msg="Server is ready to receive web requests."
level=debug ts=2019-08-23T14:49:57.995042455Z caller=klog.go:53 component=k8s_client_runtime func=Verbose.Infof msg="Starting reflector *v1.Endpoints (10m0s) from /app/discovery/kubernetes/kubernetes.go:300"
level=debug ts=2019-08-23T14:49:57.995052215Z caller=klog.go:53 component=k8s_client_runtime func=Verbose.Infof msg="Listing and watching *v1.Endpoints from /app/discovery/kubernetes/kubernetes.go:300"
level=debug ts=2019-08-23T14:49:57.99518502Z caller=klog.go:53 component=k8s_client_runtime func=Verbose.Infof msg="Starting reflector *v1.Service (10m0s) from /app/discovery/kubernetes/kubernetes.go:301"
level=debug ts=2019-08-23T14:49:57.995207297Z caller=klog.go:53 component=k8s_client_runtime func=Verbose.Infof msg="Listing and watching *v1.Service from /app/discovery/kubernetes/kubernetes.go:301"
level=debug ts=2019-08-23T14:49:57.995306538Z caller=klog.go:53 component=k8s_client_runtime func=Verbose.Infof msg="Starting reflector *v1.Pod (10m0s) from /app/discovery/kubernetes/kubernetes.go:302"
level=debug ts=2019-08-23T14:49:57.995326771Z caller=klog.go:53 component=k8s_client_runtime func=Verbose.Infof msg="Listing and watching *v1.Pod from /app/discovery/kubernetes/kubernetes.go:302"
level=debug ts=2019-08-23T14:49:58.002685564Z caller=klog.go:70 component=k8s_client_runtime func=Infof msg="GET https://10.96.0.1:443/api/v1/namespaces/default/pods?limit=500&resourceVersion=0 200 OK in 7 milliseconds"
level=debug ts=2019-08-23T14:49:58.003053445Z caller=klog.go:70 component=k8s_client_runtime func=Infof msg="GET https://10.96.0.1:443/api/v1/namespaces/default/endpoints?limit=500&resourceVersion=0 200 OK in 7 milliseconds"
level=debug ts=2019-08-23T14:49:58.003051485Z caller=klog.go:70 component=k8s_client_runtime func=Infof msg="GET https://10.96.0.1:443/api/v1/namespaces/default/services?limit=500&resourceVersion=0 200 OK in 7 milliseconds"
level=debug ts=2019-08-23T14:49:58.00611834Z caller=klog.go:70 component=k8s_client_runtime func=Infof msg="GET https://10.96.0.1:443/api/v1/namespaces/default/endpoints?resourceVersion=3542&timeout=9m14s&timeoutSeconds=554&watch=true 200 OK in 1 milliseconds"
level=debug ts=2019-08-23T14:49:58.006604113Z caller=klog.go:70 component=k8s_client_runtime func=Infof msg="GET https://10.96.0.1:443/api/v1/namespaces/default/services?resourceVersion=2804&timeout=9m19s&timeoutSeconds=559&watch=true 200 OK in 0 milliseconds"
level=debug ts=2019-08-23T14:49:58.010117361Z caller=klog.go:70 component=k8s_client_runtime func=Infof msg="GET https://10.96.0.1:443/api/v1/namespaces/default/pods?resourceVersion=3539&timeout=8m16s&timeoutSeconds=496&watch=true 200 OK in 0 milliseconds"
level=debug ts=2019-08-23T14:49:58.095461671Z caller=klog.go:53 component=k8s_client_runtime func=Verbose.Infof msg="caches populated"
level=info ts=2019-08-23T14:50:02.145205709Z caller=main.go:695 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-08-23T14:50:02.145896962Z caller=kubernetes.go:201 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=debug ts=2019-08-23T14:50:02.146534335Z caller=manager.go:217 component="discovery manager scrape" msg="Starting provider" provider=*kubernetes.SDConfig/0 subs="[default/auth/0 default/backend/0]"
level=info ts=2019-08-23T14:50:02.146618907Z caller=main.go:722 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=debug ts=2019-08-23T14:50:02.146888046Z caller=klog.go:53 component=k8s_client_runtime func=Verbose.Infof msg="Starting reflector *v1.Service (10m0s) from /app/discovery/kubernetes/kubernetes.go:301"
level=debug ts=2019-08-23T14:50:02.14704179Z caller=klog.go:53 component=k8s_client_runtime func=Verbose.Infof msg="Listing and watching *v1.Service from /app/discovery/kubernetes/kubernetes.go:301"
level=debug ts=2019-08-23T14:50:02.146975455Z caller=klog.go:53 component=k8s_client_runtime func=Verbose.Infof msg="Starting reflector *v1.Endpoints (10m0s) from /app/discovery/kubernetes/kubernetes.go:300"
level=debug ts=2019-08-23T14:50:02.147173485Z caller=klog.go:53 component=k8s_client_runtime func=Verbose.Infof msg="Listing and watching *v1.Endpoints from /app/discovery/kubernetes/kubernetes.go:300"
level=debug ts=2019-08-23T14:50:02.147206941Z caller=klog.go:53 component=k8s_client_runtime func=Verbose.Infof msg="Starting reflector *v1.Pod (10m0s) from /app/discovery/kubernetes/kubernetes.go:302"
level=debug ts=2019-08-23T14:50:02.147258257Z caller=klog.go:53 component=k8s_client_runtime func=Verbose.Infof msg="Listing and watching *v1.Pod from /app/discovery/kubernetes/kubernetes.go:302"
level=debug ts=2019-08-23T14:50:02.148390995Z caller=klog.go:70 component=k8s_client_runtime func=Infof msg="GET https://10.96.0.1:443/api/v1/namespaces/default/endpoints?limit=500&resourceVersion=0 200 OK in 1 milliseconds"
level=debug ts=2019-08-23T14:50:02.148603964Z caller=klog.go:70 component=k8s_client_runtime func=Infof msg="GET https://10.96.0.1:443/api/v1/namespaces/default/services?limit=500&resourceVersion=0 200 OK in 1 milliseconds"
level=debug ts=2019-08-23T14:50:02.149365916Z caller=klog.go:70 component=k8s_client_runtime func=Infof msg="GET https://10.96.0.1:443/api/v1/namespaces/default/pods?limit=500&resourceVersion=0 200 OK in 2 milliseconds"
level=debug ts=2019-08-23T14:50:02.150326536Z caller=klog.go:70 component=k8s_client_runtime func=Infof msg="GET https://10.96.0.1:443/api/v1/namespaces/default/endpoints?resourceVersion=3549&timeout=7m41s&timeoutSeconds=461&watch=true 200 OK in 1 milliseconds"
level=debug ts=2019-08-23T14:50:02.150710377Z caller=klog.go:70 component=k8s_client_runtime func=Infof msg="GET https://10.96.0.1:443/api/v1/namespaces/default/services?resourceVersion=2804&timeout=7m0s&timeoutSeconds=420&watch=true 200 OK in 0 milliseconds"
level=debug ts=2019-08-23T14:50:02.152153706Z caller=klog.go:70 component=k8s_client_runtime func=Infof msg="GET https://10.96.0.1:443/api/v1/namespaces/default/pods?resourceVersion=3545&timeout=6m32s&timeoutSeconds=392&watch=true 200 OK in 0 milliseconds"
level=debug ts=2019-08-23T14:50:02.24690516Z caller=klog.go:53 component=k8s_client_runtime func=Verbose.Infof msg="caches populated"
```

**Comment by ndarilek** [comment]
For completeness' sake, here is the Prometheus configuration currently stored in the secret:

```
global:
  evaluation_interval: 30s
  scrape_interval: 30s
  external_labels:
    prometheus: default/main
    prometheus_replica: $(POD_NAME)
rule_files:
- /etc/prometheus/rules/prometheus-main-rulefiles-0/*.yaml
scrape_configs:
- job_name: default/auth/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - default
  metrics_path: /metrics
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: http-api
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Node;(.*)
    replacement: ${1}
    target_label: node
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Pod;(.*)
    replacement: ${1}
    target_label: pod
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - target_label: endpoint
    replacement: http-api
- job_name: default/backend/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - default
  metrics_path: /actuator/prometheus
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: http-api
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Node;(.*)
    replacement: ${1}
    target_label: node
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Pod;(.*)
    replacement: ${1}
    target_label: pod
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - target_label: endpoint
    replacement: http-api
alerting:
  alert_relabel_configs:
  - action: labeldrop
    regex: prometheus_replica
  alertmanagers: []
```

**Comment by RiRa12621** [comment]
The reason is that your labeling doesn’t match up.
Your serviceMonitor is being picked up but there’s nothing behind it to be scraped.
In your serviceMonitor you are selecting service labeled `app: auth` but your service doesn’t contain that label.

**Comment by ndarilek** [comment]
Got it, so here's what I have now:


```

---
apiVersion: v1
kind: Service
metadata:
   name: auth
   labels:
     app: auth
spec:
   type: ClusterIP
   selector:
     app: auth
   ports:
     - targetPort: http-api
       port: 80
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
   name: auth
   labels:
     scope: backend
spec:
   selector:
     matchLabels:
       app: auth
   endpoints:
   - port: http-api
     path: /metrics

```


Still shows 0/0 up. I tried both the above and this in my ServiceMonitor:


```

   selector:
     app: auth

```


Not sure if they're functionally identical.


Thanks for the help thus far.

**Comment by ndarilek** [comment]
Made more progress with this. I have 2 ServiceMonitors monitoring 2 services with 3 pods. Unfortunately, each target shows 1/3 up and 2/3 up, whereas they should show 1/1 up and 2/2 up. Each monitor is matching all monitored pods, rather than those for the specific service. Here are my services:

```
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: http-api
      targetPort: http-api
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http-api
      targetPort: http-api
      port: 80
```

And my ServiceMonitors:

```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth
  labels:
    scope: backend
spec:
  selector:
    app: auth
  endpoints:
  - port: http-api
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  labels:
    scope: backend
spec:
  selector:
    app: backend
  endpoints:
  - port: http-api
    path: /actuator/prometheus
```

Why is each monitor matching everything? Is it because of:

```
scope: backend
```

My thought was that this parameter matched ServiceMonitors to a given Prometheus instance, but am I misunderstanding? My thought is that the auth and backend pods are all collectively part of the app's backend, so I want this monitor monitoring everything, but distinguishing between the auth and backend *app* pods. Ideally I wouldn't mind one instance monitoring everything for now, then adding selectors if I need other instances for some reason, but it doesn't look like that is supported without this extra bit of ceremony.

Thanks for the help.
