### DISCUSSION TITLE
Why is it that my ServiceMonitor needs a `release` label to run properly?

### DISCUSSION THREAD

**Discussion by evanmosseri** [prometheus-operator/prometheus-operator#4311] [Q&A] [answered]
When I deploy this: 
```
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  labels:
    app: complaints-monitor
    release: prometheus # <---------
  name: complaints-monitor-svc-monitor
  namespace: default
spec:
  endpoints:
    - path: /metrics
      port: web
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: complaints-monitor
```

My service shows up under prometheus targets and runs correctly.

If I apply the following instead, the target disappears:

```
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  labels:
    app: complaints-monitor
  name: complaints-monitor-svc-monitor
  namespace: default
spec:
  endpoints:
    - path: /metrics
      port: web
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: complaints-monitor
```
