### DISCUSSION TITLE
Discovered Labels but Target Labels 'Dropped'

### DISCUSSION THREAD

**Discussion by jhoweaa** [prometheus-operator/prometheus-operator#4431] [Q&A]
I'm trying to configure a ServiceMonitor in my DockerDesktop Kubernetes environment. I've installed the 'kube-prometheus-stack' from this Helm chart - kube-prometheus-stack-21.0.0. I have a simple Micronaut application that I would like to monitor. The application publishes Prometheus metrics on the '/prometheus' endpoint. I have a service definition that looks like this:

```
apiVersion: v1
kind: Service
metadata:
  name: report-api
spec:
  selector:
    app: report-api
  type: LoadBalancer
  ports:
    - name: api
      protocol: TCP
      port: 8180
      targetPort: 8080
```

and my servicemonitor definition looks like this:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: report-api-servicemonitor
  labels:
    app: report-api
    release: kube-prometheus-stack-1638301520
spec:
  selector:
    matchLabels:
      app: report-api
  endpoints:
  - port: api
    path: /prometheus
    interval: 15s
```

If I go to the Prometheus UI page, I can see that my servicemonitor is being picked up and I have a long list of discovered labels, mostly __meta tags. The 'Target Labels' column just  says 'Dropped'. I'm trying to figure out what bit of configuration I'm missing which is preventing things from working. Any suggestions on places to look or things to try would be appreciated.

Thanks!
