### DISCUSSION TITLE
servicemonitor was configured, configs are loaded, but no targets are discovered

### DISCUSSION THREAD

**Discussion by LeoQuote** [prometheus-operator/prometheus-operator#4438] [Q&A] [answered]
svc:

```
Name:              dae-btd1-prometheus-beanstalkd-exporter
Namespace:         monitoring
Labels:            app.kubernetes.io/instance=dae-btd1
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/name=prometheus-beanstalkd-exporter
                   app.kubernetes.io/version=1.16.0
                   helm.sh/chart=prometheus-beanstalkd-exporter-0.1.0
Annotations:       meta.helm.sh/release-name: dae-btd1
                   meta.helm.sh/release-namespace: monitoring
Selector:          app.kubernetes.io/instance=dae-btd1,app.kubernetes.io/name=prometheus-beanstalkd-exporter
Type:              ClusterIP
IP:                172.23.185.108
Port:              http  9240/TCP
TargetPort:        http/TCP
Endpoints:         10.0.7.116:8080
Session Affinity:  None
Events:            <none>
```

servicemonitor:

```
Name:         dae-btd1-prometheus-beanstalkd-exporter
Namespace:    monitoring
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: dae-btd1
              meta.helm.sh/release-namespace: monitoring
API Version:  monitoring.coreos.com/v1
Kind:         ServiceMonitor
Spec:
  Endpoints:
    Target Port:  9240
  Job Label:      dae-btd1-prometheus-beanstalkd-exporter
  Namespace Selector:
    Match Names:
      monitoring
  Selector:
    Match Labels:
      app.kubernetes.io/instance:  dae-btd1
      app.kubernetes.io/name:      prometheus-beanstalkd-exporter
```

I can see the config in configuration:

```
- job_name: serviceMonitor/monitoring/dae-btd1-prometheus-beanstalkd-exporter/0
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: (.*)
    target_label: __tmp_prometheus_job_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
...
...
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    namespaces:
      names:
      - monitoring
```

but no targets were discovered...

What can I do to troubleshoot this? I've checked the svc , I can wget the service inside prometheus container. There's no network issue.
