### DISCUSSION TITLE
ImagePullBackOff when using private container registry

### DISCUSSION THREAD

**Discussion by ErniMJ** [prometheus-operator/prometheus-operator#4757] [Q&A] [answered]
I have updated bundle.yaml file with private container registry:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: 0.56.0
  name: prometheus-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: prometheus-operator
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/version: 0.56.0
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --prometheus-config-reloader=mytestacr1.io/prometheus-operator/prometheus-config-reloader:v0.56.0
        image: mytestacr1.io/prometheus-operator/prometheus-operator:v0.56.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
```

The problem is that pod prometheus-prometheus-0 status ends with ImagePullBackOff:
```sh
kubectl get pods --namespace default
NAME                                                 READY   STATUS             RESTARTS   AGE
grafana-56853467d64f8-a76sf                             1/1     Running            0          5h58m
prometheus-operator-58c69cf643-fbv29                 1/1     Running            0          3m7s
prometheus-prometheus-0                              1/2     ImagePullBackOff   0          73s
```

When I check pod:
```sh
kubectl get pod prometheus-prometheus-0 --namespace default
```
I see in output that prometheus image is still pulled from quay.io instead of my private container registry:
```yaml
spec:
  automountServiceAccountToken: true
  containers:
  - args:
    - --web.console.templates=/etc/prometheus/consoles
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --storage.tsdb.retention.time=24h
    - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
    - --storage.tsdb.path=/prometheus
    - --web.enable-lifecycle
    - --web.route-prefix=/
    - --web.config.file=/etc/prometheus/web_config/web-config.yaml
    image: quay.io/prometheus/prometheus
    imagePullPolicy: Always
```
```yaml
containerStatuses:
  - containerID: containerd://e583fd9de7822c8408822398b85e92162ed84843c88b8a474426aa8d1abf2235
    image: mytestacr1.io/prometheus-operator/prometheus-config-reloader:v0.56.0
    imageID: mytestacr1.io/prometheus-operator/prometheus-config-reloader@sha256:2ca7942fa5a7a567cv2f565ac5b2c1622a6c884019ad82bcc6f07a4454df012d58
    lastState: {}
    name: config-reloader
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-04-28T20:48:41Z"
  - image: quay.io/prometheus/prometheus
    imageID: ""
    lastState: {}
    name: prometheus
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "quay.io/prometheus/prometheus"
        reason: ImagePullBackOff
```

Not sure if this is a bug or I need to update it somewhere else.
