### DISCUSSION TITLE
Cannot add the external nodes as targets to prometheus-operator in kubernetes

### DISCUSSION THREAD

**Discussion by bharathpantala** [prometheus-operator/prometheus-operator#4770] [General]
Cannot add the external nodes as targets to prometheus-operator in kubernetes 

My prom release on k8s is : **prometheus-operator**

Followed the same https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/additional-scrape-config.md

Can someone give some doc to add external node-exporter as targets to prometheus-operator in kubernetes.

**Comment by slashpai** [comment]
May be there are better ways but I tested this way in local cluster and it works.  We will create the the service without selector and then define the endpoints separately. And then create servicemonitor. Treat this as example and tweak settings as per your need :)

1. Create service object for external node-exporter with selector

```yaml
kind: Service
apiVersion: v1
metadata:
 name: node-exporter-external
 labels:
    app: node-exporter-external
spec:
 type: ClusterIP
 ports:
 - name: metrics
   port: 9100
   targetPort: 9100
```

2. Create endpoint object separately

```yaml
kind: Endpoints
apiVersion: v1
metadata:
 name: node-exporter-external
subsets:
- addresses:
  - ip: <node external ip>
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
```

3. Create servicemonitor

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: node-exporter-external
  name: node-exporter-external
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: node-exporter-external
```

**Comment by ikozar** [comment]
The solution doesn't work in my case.
I want to add to prometheus additional node-exported from external host.
I found value "endpoints" in "charts/prometheus-node-exporter/values.yaml", but it also doesn't work

I was able to add an external node export after applying the following endpoint
```
apiVersion: v1
kind: Endpoints
metadata:
  name: my-prometeus-prometheus-node-exporter
  namespace: monitoring
  labels:
    app: prometheus-node-exporter
    heritage: Helm
    release: my-prometeus
    chart: prometheus-node-exporter-3.3.0
subsets:
  - addresses:
      - ip: <minikube node IP>
      - ip: <external IP>
    ports:
      - name: http-metrics
        port: 9100
        protocol: TCP
```
prometheus discovered external exporter and queried metrics
but, unfortunately, after some time the external IP was lost and getting metrics from external node was stopped

**Comment by xiu** [comment]
Since prometheus-operator 0.65, we have the `ScrapeConfig` CRD. With it, you currently can define targets via the `static_config`, `file_sd_config` and `http_sd_config` parameters. Here's an example with `static_config`:
```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: my-scrape-config
spec:
  staticConfigs:
  - targets:
    - "10.x.y.z:1234"
```

Documentation: https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1alpha1.ScrapeConfig
