### DISCUSSION TITLE
Alertmanager routes

### DISCUSSION THREAD

**Discussion by ngc4579** [prometheus-operator/prometheus-operator#5009] [Q&A]
Given this configuration (`AlertmanagerConfig`, excerpt):

```yaml
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    receiver: 'null'
    routes:
    - receiver: 'null'
      matchers:
      - name: severity
        value: info
        matchType: '='
    - receiver: 'slack'
      matchers:
      - name: severity
        value: (warning|critical)
        matchType: '=~'
  receivers:
  - name: 'null'
  - name: 'slack'
    slackConfigs:
    ...
```

I'd expect alerts with a `severity=info` label to enter the routing tree, match the first child route and be dropped (i.e. sent to the `null` receiver). Alerts with a (e.g.) `severity=warning` label should match the second child route and be sent to the configured `slack` receiver.

In fact, no alert is ever sent to the `slack` receiver. When inspecting the actual Alertmanager Status (i.e. the rendered config), it looks like this:

```yaml
route: # top level, rendered by operator?
  receiver: "null"
  group_by:
  - job
  continue: false
  routes: # route with children as configured above
  - receiver: some-null-receiver
    group_by:
    - job
    match:
      namespace: some-namespace
    continue: true
    routes: # child routes
    - receiver: some-null-receiver
      match:
        severity: info
      continue: false
    - receiver: some-slack-receiver
      match:
        severity: (warning|critical)
      continue: false
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    ...
```

Is the `matchType` even evaluated properly when rendering the Alertmanager config? Or am I overlooking something basic?
