### DISCUSSION TITLE
How to add header to ServiceMonitor endpoint?

### DISCUSSION THREAD

**Discussion by danhngo-lx** [prometheus-operator/prometheus-operator#5093] [General]
**What did you do?**
I need to add `Authorization` header to an endpoint of ServiceMonitor. However according to [the API ](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#authorization), only `Bearer` and `Basic` is supported, while I need something other than that. Specifically I need to add the following header value:
```
Authorization: Apikey my-api-key-token
```

**Did you expect to see some different?**
At the moment it looks like there's no way to configure the `Authorization` header value, or adding a custom header to an Endpoint. The doc even says `Authorization contains optional Authorization header configuration` however I could not find any information on how to add this optional header (or maybe it's not supposed to be configured directly).

**Environment**

* Prometheus Operator version:

    `v0.58.0`
    
    

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"clean", BuildDate:"2022-09-14T19:40:59Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"e18a4970ca206398e987600929fec300cb85d0ca", GitTreeState:"clean", BuildDate:"2022-09-16T05:13:38Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    Azure AKS

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: whatsapp-core-wa-1234
  namespace: whatsapp
  labels:
    app: whatsapp-api
    app.kubernetes.io/name: whatsapp-api
    app.kubernetes.io/instance: whatsapp-core-wa-1234
    helm.sh/chart: whatsapp-api-1.4.7
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v2.37.2"
    app.kubernetes.io/managed-by: Helm
spec:
  namespaceSelector:
    matchNames:
      - whatsapp
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - whatsapp-api
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - whatsapp-core-wa-1234
  endpoints:
    - port: http
      scheme: http
      path: /v1/stats/app
      params:
        format: prometheus
      interval: 30
      scrapeTimeout: 10
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
you want to look at https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.SafeAuthorization

Assuming that you've created a secret `mysecret` with a key `apitoken` containing the API key, your service monitor should look like this:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: whatsapp-core-wa-1234
  namespace: whatsapp
spec:
  namespaceSelector:
    matchNames:
      - whatsapp
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - whatsapp-api
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - whatsapp-core-wa-1234
  endpoints:
    - port: http
      scheme: http
      path: /v1/stats/app
      authorization:
        type: Apikey
        credentials:
          name: mysecret
          key: apitoken
```
