### DISCUSSION TITLE
PrometheusRule support default label

### DISCUSSION THREAD

**Discussion by yccharles** [prometheus-operator/prometheus-operator#5110] [Ideas]
# PrometheusRule support default label 
maybe we can define a default label in a group. that's mean all alert [AlertA, AlertB, Alertc]  will has the same label : [severity: warning]

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
  name: xxxxx
  namespace: monitoring
spec:
  groups:
  - name: goldpinger-alerts
    default_labels:
      severity: warning
    rules:
    - alert: AlertA
      expr:  a > 1
    - alert: AlertB
      expr:  b > 1
    - alert: AlertC
      expr:  c > 1

```
