### DISCUSSION TITLE
PrometheusOperator Istio fails to replace metric name

### DISCUSSION THREAD

**Discussion by roee-landesman** [prometheus-operator/prometheus-operator#5144] [General]
I'm attempting to do a basic metric relabeling where I replace the `__name__` by removing a prefix (specifically `workload:`). This is taken directly from the upstream istio documentation found [here](https://istio.io/latest/docs/ops/best-practices/observability/#optimizing-metrics-collection-with-recording-rules). However, I am able to create a new metric without the `workload` prefix, but am totally unable to either replace nor drop the existing `workload` metric in order to save space. This is further confirmed when looking at the TSDB status endpoint of my main prometheus. 

<img width="2531" alt="Screen Shot 2022-11-08 at 12 23 48 PM" src="https://user-images.githubusercontent.com/100310202/200667669-2fb991fb-834b-4020-a777-14b5608c29ac.png">

My ServiceMonitor configuration:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: istio-prometheus
  name: istio-federation
  namespace: prometheus-system
spec:
  endpoints:
  - interval: 30s
    scrapeTimeout: 30s
    params:
      'match[]':
      - '{__name__=~"workload:(.*)"}'
      - '{__name__=~"pilot(.*)"}'
    path: /federate
    targetPort: 9090
    honorLabels: true
    metricRelabelings:
    - sourceLabels: ["__name__"]
      regex: 'workload:(.*)'
      targetLabel: "__name__"
      action: replace
  namespaceSelector:
    matchNames:
    - istio-system
  selector:
    matchLabels:
      release: prometheus-istio
```

Any help or pointers in this case would be super appreciated!
