### DISCUSSION TITLE
How to attach constant lables for metrics

### DISCUSSION THREAD

**Discussion by caibirdme** [prometheus-operator/prometheus-operator#5161] [Q&A] [answered]
I want to add some constant labels for my metrics, something like:
```yaml
spec:
  - targetPort: 8899
    labels:
      - manage_by: helm
      - provider: gcp 
```
Just find relabel and metricRelabel in docs, I don't know how to achieve this

**Comment by simonpasquier** [comment, marked as answer]
you want metricRelabelings:

```
spec:
  endpoints:
    metricRelabelings:
    - targetLabel: managed_by
      replacement: helm
```
