### DISCUSSION TITLE
Edit main scrape configuration prometheus.env.yaml

### DISCUSSION THREAD

**Discussion by mgorzkow** [prometheus-operator/prometheus-operator#5276] [Q&A]
Hi, im new in Kubernetes. I have a problem with scrape config. How can i edit it? I want to delete some k8s metrics because i dont need to use them. Prometheus pods have such huge CPU and Memory usage and i want to optimaze it by deleting not used targets. 

When i try to edit file in pod i got error: prometheus.env.yaml: Read-only file system

I know that i can add and edit new added targets in aditional scrape but what about edit existing targets?

Or is there any way to optimize CPU and memory usage by prometheus?

**Comment by simonpasquier** [comment]
you should use the metricRelabelings field in your ServiceMonitor/PodMonitor. The following snippet drops all metrics named "foo" and "bar":

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-service-monitor
spec:
  endpoints:
  - [omitted]
    metricRelabelings:
    - action: drop
      regex: "(foo|bar)"
      sourceLabels:
      - __name__
```
