### DISCUSSION TITLE
Collect metrics of cronjobs

### DISCUSSION THREAD

**Discussion by mojixcoder** [prometheus-operator/prometheus-operator#5298] [Q&A] [answered]
Hey
I have a cronjob which runs once a day.
When my cron job finishes its process it waits for 1 minute so pod monitor can collect its metrics.

My problem is that pod monitor is not collecting any metrics so I cannot see them in Grafana.

I wanted to know can pod monitor collect metrics from cron job pods?

After my cron job starts it creates a pod and I can find the pod using this command: `oc get pods -l app=app_name`. But metrics are still not collected by pod monitor.

**Comment by simonpasquier** [comment, marked as answer]
Can you share the PodMonitor & CronJob definitions?

**Reply by mojixcoder** [reply]
Here is the job definition:
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dailymileage
  labels:
    app.kubernetes.io/name: dailymileage
    helm.sh/chart: dailymileage-0.1.0
    app.kubernetes.io/instance: dailymileage
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: "30 22 * * *"
  jobTemplate:
    metadata:
      name: dailymileage
    spec:
      template:
        metadata:
          annotations:
          labels:
            app.kubernetes.io/name: dailymileage
            app.kubernetes.io/instance: dailymileage
            app: dailymileage
        spec:
          restartPolicy: Never
          containers:
          - name: dailymileage
            image: "my_img"
            imagePullPolicy: IfNotPresent
            command: [
                "/bin/sh",
            ]
            
            args: [
                "-c",
                "/dailymileage",
            ]
```

And here is the podmonitor definition:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: my-ns
  name: dailymileage
  labels:
    app: dailymileage
spec:
  namespaceSelector:
    matchNames:
      -  my-ns
  selector:
    matchLabels:
      app: dailymileage
  podMetricsEndpoints:
    - targetPort: 2112
```
