### DISCUSSION TITLE
Does RemoteWrite supports writing PrometheusRules ?

### DISCUSSION THREAD

**Discussion by matthewygf** [prometheus-operator/prometheus-operator#5397] [Q&A] [answered]
For example, in the kube-prometheus-stack, I added a prometheusRule

```yaml
additionalPrometheusRulesMap:
  some-rule:
        groups:
        - name: cpu_mem_usage_active
          interval: 30s
          rules:
           - record: cpu_usage_active
```

In the remoteWriteSpec I write the following:
```yaml
- url: "http://someurl/write"
  writeRelabelConfigs:
  - sourceLabels: ["__name__"]
    regex: "(.*usage_active)"
    action: "keep"
```

Does the ```cpu_usage_active``` gets written to a remote url ?
