### DISCUSSION TITLE
Prometheus PodMonitor not showing any endpoint

### DISCUSSION THREAD

**Discussion by jonas-tm** [prometheus-operator/prometheus-operator#5430] [Q&A]
I am using `kube-prometheus-stack` helm chart to run Prometheus in my cluster.
I now wanted scrape metrics for a specific app via PodMonitor custom resource.

Prometheus picks the monitor up, but it is not showing any endpoint in prometheus UI (see picture).
I tested the _testapp_ metrics endpoint on the pod via port-forwarding and it works fine.
Am I missing any configuration?

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: testapp
  name: testapp
  labels:
    name: testapp
spec:
  namespaceSelector:
    matchNames:
      - testapp
  selector:
    matchLabels:
      app: testapp
  podMetricsEndpoints:
    - interval: 5s
      port: "8080"
      path: /metrics
```

![image](https://user-images.githubusercontent.com/95413009/226394715-80522e94-e0fb-40b7-ab04-0aecdda7c3f8.png)
