### DISCUSSION TITLE
How to add the probe when using the blackbox-exporter

### DISCUSSION THREAD

**Discussion by yuan-yueping** [prometheus-operator/prometheus-operator#5568] [Q&A]
I created a Probe object to detect the port through blackbox-exporter ,but the Operator did not discovery it. I think the Operator should be able to correctly discover Probe CRs.
There is no error log in Operator and Prometheus.
Except Probe, ServiceMonitor and PorMonitor CRs can be dicover normally
What should i do
![截屏2023-05-11 14 28 02](https://github.com/prometheus-operator/prometheus-operator/assets/58799869/e0205dfa-e497-4392-91ad-675b8abf5a10)
image: prometheus-operator:v0.44.1

probe yaml

![截屏2023-05-11 14 31 11](https://github.com/prometheus-operator/prometheus-operator/assets/58799869/e96b93a4-199c-4a4a-a2b5-8b625213d89b)

I have deployed blackbox_exporter
<img width="1024" alt="截屏2023-05-11 14 44 23" src="https://github.com/prometheus-operator/prometheus-operator/assets/58799869/1b9c806c-0151-4180-b463-a35521d12e7f">

**Comment by atsai1220** [comment]
You may need to add the correct labels to your `Probe` objects based on the labels configured for your `Prometheus` CRD object.

For example
``` yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: rancher-monitoring-prometheus
  namespace: cattle-monitoring-system
spec:
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: rancher-monitoring

```
