### DISCUSSION TITLE
How to push alert to Grafana Cloud alert manager with AlertManagerEndpoint

### DISCUSSION THREAD

**Discussion by winston0410** [prometheus-operator/prometheus-operator#5639] [Q&A]
I am trying to push alert defined within my cluster to Grafana cloud's alert manager. I am aware of this config:
https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.AlertmanagerEndpoints

I am able to pass most of the required config I get from Grafana Cloud into this section, but I have no idea how to specify the `url` for the endpoint.

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
spec:
  alerting:
    alertmanagers:
      - name: grafana-cloud-alert-manager
        namespace: prometheus
        apiVersion: v2
        port: 443
        scheme: https
        basicAuth:
          username:
            name: alert-manager-secret
            key: username
          password:
            name: alert-manager-secret
            key: password          
        timeout: 15
```

Assuming my endoint is `foo.grafana.com`, where can I pass that url?
