### DISCUSSION TITLE
Label drop

### DISCUSSION THREAD

**Discussion by brunooliveiramac** [prometheus-operator/prometheus-operator#5763] [General]
Hey all,

I have a fresh prometheus installed and I'm trying to drop the id label, but it's not totally working. I have some memory issues and wanted to reduce the consumption.

![image](https://github.com/prometheus-operator/prometheus-operator/assets/10716628/cb8b673e-5501-4e7e-a235-ebf43e1c4704)

I tried this way, but the id is still the highest. 

```
prometheus:
  serviceMonitor:
    relabelings:
      - regex: "id"
        action: "labeldrop"
```

**Comment by nicolastakashi** [comment]
Hey @brunooliveiramac 
Actually, you need to use metricRelabelings instead of relabeling.
We have some examples available [here](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/running-exporters.md) 😄

**Reply by brunooliveiramac** [reply]
Hi @nicolastakashi  :)

This is my current values.yaml

```
prometheus:
#  additionalArgs:
#    - name: "storage.tsdb.max-block-duration"
#      value: "15m"
#    - name: "storage.tsdb.min-block-duration"
#      value: "15m"
#    - name: "storage.tsdb.retention.size"
#      value: "800MB"
#    - name: "storage.tsdb.retention.time"
#      value: "5m"
#    - name: "storage.tsdb.retention"
#      value: "5m"
  serviceMonitor:
    metricRelabelings:
      - regex: "id"
        action: "labeldrop"
    relabelings:
      - regex: "id"
        action: "labeldrop"
  nodeAffinityPreset:
    type: "hard"
    key: "type"
    values:
      - monitoring
  tolerations:
    - key: "monitoring-node-pool"
      operator: "Exists"
  replicaCount: 1
  podMetadata:
    labels:
      sidecar.istio.io/inject: "false"
  resources:
    limits:
      cpu: "2"
      memory: "8Gi"
    requests:
      cpu: "1"
      memory: "4Gi"
  thanos:
    # create a Thanos sidecar container
    create: true
    # expose sidecar as a LoadBalancer
    service:
      type: LoadBalancer
      # Make the load balancer internal, so that it is only accessible on VPC
      annotations:
        networking.gke.io/load-balancer-type: "Internal"
    extraArgs:
    - --log.level=debug
  externalLabels:
    cluster: foo
  service:
    type: ClusterIP
  ruleSelector: {}
  retention: 1d
  # retention: #time to retain metrics
  # walCompression #Enable compression of the write-ahead log using Snappy
  # allow loki altertingrules to write into prometheus rules, for notificaiton purposes
  enableRemoteWriteReceiver: true


alertmanager:
  replicaCount: 2
  service:
    type: ClusterIP
  config:
    global:
      resolve_timeout: 5m
    route:
      #group_by: ['job']
      #group_wait: 30s
      #group_interval: 5m
      #repeat_interval: 12h
      #receiver: 'default-catchall-msteams' (TO-DO: define default notif template)
      receiver: 'critical-devops-msteams'
      routes:
      - match:
          severity: critical
        receiver: critical-devops-msteams
        routes:
        - match_re:
            team: .*(devops).*
          receiver: critical-devops-msteams
    receivers:
    - name: 'critical-devops-msteams'
      webhook_configs:
      - send_resolved: true
        url: 'http://prometheus-msteams.loki.svc.cluster.local:2000/lokinotif'
  nodeAffinityPreset:
    type: "hard"
    key: "type"
    values:
      - monitoring
  tolerations:
    - key: "monitoring-node-pool"
      operator: "Exists"

operator:
  service:
    type: ClusterIP
  serviceMonitor:
    relabelings:
      - regex: "id"
        action: "labeldrop"
    metricRelabelings:
      - regex: "id"
        action: "labeldrop"
  nodeAffinityPreset:
    type: "hard"
    key: "type"
    values:
      - monitoring
  tolerations:
    - key: "monitoring-node-pool"
      operator: "Exists"

kubeScheduler:
  serviceMonitor:
    relabelings:
    - regex: "id"
      action: "labeldrop"
    metricRelabelings:
    - regex: "id"
      action: "labeldrop"

kubeControllerManager:
  serviceMonitor:
    relabelings:
    - regex: "id"
      action: "labeldrop"
    metricRelabelings:
    - regex: "id"
      action: "labeldrop"

kubelet:
  serviceMonitor:
    relabelings:
    - regex: "id"
      action: "labeldrop"
    metricRelabelings:
    - regex: "id"
      action: "labeldrop"

kubeApiServer:
  serviceMonitor:
    relabelings:
    - regex: "id"
      action: "labeldrop"
    metricRelabelings:
    - regex: "id"
      action: "labeldrop"

coreDns:
  serviceMonitor:
    relabelings:
    - regex: "id"
      action: "labeldrop"
    metricRelabelings:
    - regex: "id"
      action: "labeldrop"

kubeProxy:
  serviceMonitor:
    relabelings:
    - regex: "id"
      action: "labeldrop"
    metricRelabelings:
    - regex: "id"
      action: "labeldrop"
```

And still didn't work.
The **id** is still the highest cardinality:
./promtool tsdb analyze prometheus/opt/bitnami/prometheus/data/

```
Block ID: 01H658YZ3B7QY21C7W7BD84NX3
Duration: 2h0m0s
Series: 1100302
Label names: 197
Postings (unique label pairs): 15998
Postings entries (total label pairs): 19884419

Label pairs most involved in churning:
194064 container=istio-proxy
189258 namespace=vikingcloud
185061 job=istio-system/envoy-stats-monitor
105086 destination_canonical_revision=latest
105062 source_canonical_revision=latest
104416 request_protocol=http
94400 destination_cluster=Kubernetes
94253 response_flags=-
92240 destination_workload_namespace=vikingcloud
92169 destination_service_namespace=vikingcloud
89168 source_cluster=Kubernetes
71640 job=kubelet
71640 service=prometheus-kube-prometheus-kubelet
71640 endpoint=https-metrics
69986 source_workload_namespace=vikingcloud
66449 response_code=200
53558 destination_version=unknown
53558 reporter=source
53558 connection_security_policy=unknown
51527 reporter=destination

Label names most involved in churning:
273498 __name__
273404 instance
273310 job
270016 namespace
261693 pod
217220 container
185061 pod_name
124387 le
105180 source_canonical_service
105180 source_workload_namespace
105180 destination_workload_namespace
105180 destination_canonical_service
105086 source_principal
105086 reporter
105086 request_protocol
105086 connection_security_policy
105086 destination_canonical_revision
105086 destination_service_namespace
105086 destination_cluster
105086 response_flags

Most common label pairs:
696144 namespace=vikingcloud
659955 container=istio-proxy
636201 job=istio-system/envoy-stats-monitor
416382 destination_canonical_revision=latest
414445 request_protocol=http
404976 source_canonical_revision=latest
380801 destination_cluster=Kubernetes
371622 destination_workload_namespace=vikingcloud
371324 destination_service_namespace=vikingcloud
369318 source_cluster=Kubernetes
353460 response_flags=-
347984 job=kubelet
347984 endpoint=https-metrics
347984 service=prometheus-kube-prometheus-kubelet
264920 source_workload_namespace=vikingcloud
241003 response_code=200
227176 reporter=destination
227176 source_version=unknown
211582 destination_principal=spiffe://cluster.local/ns/vikingcloud/sa/default
202138 namespace=kube-system

Label names with highest cumulative label value length:
419849 id
188501 name
47779 __name__
39056 uid
33001 pod
26153 uri
17296 instance
17187 pod_name
9889 interface
8136 image
7552 type
6749 resource
4027 destination_service
3218 resource_prefix
2708 crd
2292 node
2169 container
2051 source_workload
1730 destination_service_name
1687 kind

Highest cardinality labels:
4007 id
3052 name
1222 __name__
1095 pod
1090 uid
1007 instance
660 interface
522 pod_name
325 uri
294 resource
268 type
179 le
126 kind
118 resource_prefix
118 container
105 image
81 destination_service
80 crd
77 destination_service_name
75 source_workload

Highest cardinality metric names:
122600 istio_response_bytes_bucket
122600 istio_request_bytes_bucket
122600 istio_request_duration_milliseconds_bucket
21250 container_tasks_state
20274 container_blkio_device_usage_total
17000 container_memory_failures_total
16142 storage_operation_duration_seconds_bucket
12780 kubelet_runtime_operations_duration_seconds_bucket
11044 apiserver_request_duration_seconds_bucket
10420 envoy_server_initialization_time_ms_bucket
10420 envoy_cluster_manager_cds_update_duration_bucket
10420 envoy_cluster_upstream_cx_length_ms_bucket
10420 envoy_cluster_upstream_cx_connect_ms_bucket
10420 envoy_listener_manager_lds_update_duration_bucket
7784 container_network_transmit_bytes_total
7784 container_network_receive_packets_total
7784 container_network_transmit_packets_total
7784 container_network_transmit_packets_dropped_total
7784 container_network_transmit_errors_total
7784 container_network_receive_bytes_total
```

If you have any other suggestions, I would really appreciate :D
