### DISCUSSION TITLE
How to convert configuration files into Alertmanagerconfig objects

### DISCUSSION THREAD

**Discussion by Codecaver** [prometheus-operator/prometheus-operator#5949] [Q&A] [answered]
I used docker to deploy alertmanger in the past, and I used a manually managed configuration file. Recently I deployed prometheus-operator:v0.68.0 and alertmanager:v0.26.0, and I used the previous configuration file to set alertmanagerconfig. But I cannot receive any alert information from alertmanager.

`alertmanager.yml `：
```
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'webhook'
  routes:
  - match:
      repeat_interval: day
    group_interval: 5m
    repeat_interval: 24h
    receiver: 'webhook'
      
receivers:
- name: 'webhook'
  webhook_configs:
  - url: http://xxxx.xxxx.com/api/ops/WebHook/xxxxx
    send_resolved: true
    http_config:
      authorization:
        credentials: xxxxxxxxx
 
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance','test']
```

`Alertmanagerconfig:`
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    alertmanagerConfig: xxx
  name: feishu-webhook
  namespace: monitoring
spec:
  receivers:
  - name: webhook
    webhookConfigs:
    - httpConfig:
        authorization:
          credentials:
            key: credentials
            name: feishu-webhook-token
      sendResolved: true
      url: url: http://xxxx.xxxx.com/api/ops/WebHook/xxxxx
  route:
    groupBy:
    - alertname
    groupInterval: 5m
    groupWait: 30s
    receiver: webhook
    repeatInterval: 1h
    routes:
    - groupInterval: 5m
      matche:
        repeatInterval: day
      receiver: webhook
      repeatInterval: 24h
```

`alertmanager WebUI shows configuration like this:`
```
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
  webex_api_url: https://webexapis.com/v1/messages
route:
  receiver: "null"
  group_by:
  - namespace
  continue: false
  routes:
  - receiver: monitoring/feishu-webhook/webhook
    group_by:
    - alertname
    matchers:
    - namespace="monitoring"
    continue: true
    routes:
    - receiver: monitoring/feishu-webhook/webhook
      continue: false
      group_interval: 5m
      repeat_interval: 1d
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
  - receiver: "null"
    matchers:
    - alertname=~"InfoInhibitor|Watchdog"
    continue: false
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
inhibit_rules:
- source_matchers:
  - severity="critical"
  target_matchers:
  - severity=~"warning|info"
  equal:
  - namespace
  - alertname
- source_matchers:
  - severity="warning"
  target_matchers:
  - severity="info"
  equal:
  - namespace
  - alertname
- source_matchers:
  - alertname="InfoInhibitor"
  target_matchers:
  - severity="info"
  equal:
  - namespace
receivers:
- name: "null"
- name: monitoring/feishu-webhook/webhook
  webhook_configs:
  - send_resolved: true
    http_config:
      authorization:
        type: Bearer
        credentials: <secret>
      follow_redirects: true
      enable_http2: true
    url: <secret>
    url_file: ""
    max_alerts: 0
templates:
- /etc/alertmanager/config/*.tmpl
```
