### DISCUSSION TITLE
Is prometheus using too much memory ?

### DISCUSSION THREAD

**Discussion by hasanawad94** [prometheus-operator/prometheus-operator#6073] [Q&A]
The amount of samples that its ingesting per second is ~3111, got this number using this query `rate(prometheus_tsdb_head_samples_appended_total[5m]) `.
I've set global scrape interval to be 1 minute.
I have prometheus writing locally and to victoria metrics remote storage using this remote_write queue config:
```
remoteTimeout: 55s
queueConfig:
          capacity: 5000
          maxShards: 50
          maxSamplesPerSend: 500
```
In Kubernetes I see that with this config prometheus is using ~1.4GB of memory.
I plan to add more scrape jobs but I'm currently concerned if its using too much memory
