### DISCUSSION TITLE
How to debug ScrapeConfig creation

### DISCUSSION THREAD

**Discussion by LeoQuote** [prometheus-operator/prometheus-operator#6171] [Q&A] [answered]
I've created ScrapeConfig with 

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: vault
spec:
  httpSDConfigs:
  - url: https://my-sd/api/prometheus-service-discovery/?tags=vault&job=vault
  metricsPath: /v1/sys/metrics
```

but no targets nor config about it was found in prometheus config.

I assure that there's no prometheus reload failed found, and I saw log in prometheus operator 
```
level=info ts=2023-12-18T10:50:26.091561053Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prom-kube-prometheus-prometheus msg="sync prometheus"
```

and logs in prometheus pod

```
ts=2023-12-18T10:50:56.109Z caller=main.go:1267 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=178.264749ms db_storage=1.512µs remote_storage=122.98µs web_handler=471ns query_engine=812ns scrape=10.717142ms scrape_sd=5.545892ms notify=12.724µs notify_sd=350.486µs rules=136.849586ms tracing=7.895µs
```

but no config about it found in configuration

basic info:

```
prometheus-operator version: v0.70.0

prometheus version: v2.48.1

scrapeConfigSelector: {}
```
