### DISCUSSION TITLE
Podmonnitor frequently got removed.

### DISCUSSION THREAD

**Discussion by Magicloud** [prometheus-operator/prometheus-operator#6440] [Q&A]
I have kube-prometheus-stack and cloud-native Postgresql installed in KIND. Due to the `Prometheus` resource from the stack contains built-in `PodMonitorSelector`, I could not use the built-in pod monitor of cloud-native Postgresql. Following instructions [here](https://cloudnative-pg.io/documentation/1.22/monitoring/), I setup an individual one as following. It worked well, but I found that the `PodMonitor` resource frequently got removed. I could not figure out why.

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: jianai
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": jianai
  podMetricsEndpoints:
  - port: metrics
```
