### DISCUSSION TITLE
PodMonitor frequently got removed.

### DISCUSSION THREAD

**Discussion by Magicloud** [prometheus-operator/prometheus-operator#6441] [Q&A]
I have kube-prometheus-stack and cloud-native Postgresql installed in KIND. Due to the `Prometheus` resource from the stack contains built-in `PodMonitorSelector`, I could not use the built-in pod monitor of cloud-native Postgresql. Following instructions [here](https://cloudnative-pg.io/documentation/1.22/monitoring/), I setup an individual one as following. It worked well, but I found that after some time, the `PodMonitor` resource was just removed, even I recreated. I could not figure out why.

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: jianai
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": jianai
  podMetricsEndpoints:
  - port: metrics
```

**Comment by SuperCoolAlan** [comment]
I have a similar issue! I have deployed this manifest many times but it is removed after 15 minutes to 2 hours. I have not yet found logs denoting why it is being removed!

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: orc-pooler-rw
spec:
  selector:
    matchLabels:
      cnpg.io/poolerName: orc-pooler-rw
  podMetricsEndpoints:
  - port: metrics
```
