### DISCUSSION TITLE
External Labels not showing up on SNS Email Alerts (Alert Manager, AWS Managed Prometheus)

### DISCUSSION THREAD

**Discussion by thaophung137** [prometheus-operator/prometheus-operator#6746] [Q&A]
I am trying to add external labels to my scrape configs to display the env, region without manually adding them to the alert itself but it's showing empty.

```
groups:
- name: your-alert-group
  rules:
  - alert: PodsNotReady
    expr: kube_pod_status_ready{condition="true", pod_name=~"your-pod-name"} == 0
    for: 5m
    labels:
      env: dev <---------- DON'T WANT TO ADD THEM LIKE THIS
    annotations:
      summary: "Pods not ready: {{ $value }} in {{$externalLabels.env}}" <-------- Want to use it like this
      description: "The number of ready pods is less than expected."
``` 
I added the external label to my Prometheus scrape config like this:

```
groups:
global:
  external_labels:
    env: ${var.environment_name}  <------------
scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 15s
``` 

Also include it in my alert manager template similar to this:
```
template_files:
  default_template: |
    {{ define "sns.default.message" }}
    {{ - if .ExternalLabels.env }}
    {{ .externalLabels.env}}
    {{ - end }}
alertmanager_config: |
  global:
  templates:
    - 'default_template'
  route:
    receiver: default
  receivers:
    - name: 'default'
      sns_configs:
      - topic_arn: arn:aws:sns:us-east-2:accountid:My-Topic
        sigv4:
          region: us-east-2
        attributes:
          key: severity
          value: SEV2
``` 
I've verified that the variable rendered in terraform plan and I can query it on Grafana "Explore metrics". The "env" was is attached to every single metrics:
![image](https://github.com/prometheus-operator/prometheus-operator/assets/42352705/b6fb0ee5-ac02-4ae2-86a4-97681717a7cc)

However, this value is not showing up in my email or when the alert is firing... It's returning empty. I've tried changing the labels to .Labels.env and .CommonLabels.env but nothing is working. Has anyone encountered a similar issue?
