### DISCUSSION TITLE
relabelings issue

### DISCUSSION THREAD

**Discussion by mobidyc** [prometheus-operator/prometheus-operator#7342] [Q&A] [answered]
Hello,

I try to use the relabelings to add the **metrics_path** label during a job scrape.
So I extracted the values.yaml file to get the appropriate fields with:
```
helm show values oci://registry-1.docker.io/bitnamicharts/kube-prometheus > helm-kube-prometheus.yaml
```

then I configured the kubelet fields with:
```
kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    https: true
    interval: ""
    jobLabel: k8s-app
    resource: false
    resourcePath: "/metrics/resource/v1alpha1"
    resourceRelabelings: []
    resourceMetricRelabelings: []
    metricRelabelings: []
    relabelings:
      - source_labels: [__metrics_path__]
        target_label: metrics_path
    cAdvisor: true
    cAdvisorMetricRelabelings: []
    cAdvisorRelabelings:
      - source_labels: [__metrics_path__]
        target_label: metrics_path
```

and during the configuration upgrade  awarning appears:

```
$ helm upgrade kube-prometheus oci://registry-1.docker.io/bitnamicharts/kube-prometheus -f helm-kube-prometheus.yaml
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/mobidyc/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/mobidyc/.kube/config
Pulled: registry-1.docker.io/bitnamicharts/kube-prometheus:11.0.2
Digest: sha256:6fb528935e88cedb0304918b63192bb432d8c5b0ae3c9948a9a1afda402df2c4
W0215 15:24:55.917810 1514539 warnings.go:70] unknown field "spec.endpoints[0].relabelings[0].source_labels"
W0215 15:24:55.917826 1514539 warnings.go:70] unknown field "spec.endpoints[0].relabelings[0].target_label"
W0215 15:24:55.917829 1514539 warnings.go:70] unknown field "spec.endpoints[1].relabelings[0].source_labels"
W0215 15:24:55.917831 1514539 warnings.go:70] unknown field "spec.endpoints[1].relabelings[0].target_label"
Release "kube-prometheus" has been upgraded. Happy Helming!
```

And the relabels do not appear in the Prometheus configuration, what did I miss?

I'm junior in k8s, I hope to not ask something stupid.

**Comment by dosubot** [comment, marked as answer]
Hello @mobidyc! 👋 I'm here to help you with your Kubernetes and Prometheus configuration conundrum. I can assist you with bug fixes, answer your questions, and even guide you on becoming a contributor!


The warnings you're encountering indicate that the fields `source_labels` and `target_label` under `relabelings` are not recognized in the `spec.endpoints` section of your configuration. This suggests that the structure or location of your relabeling configuration might not be correct for the Helm chart you're using.

In the Prometheus Operator, relabeling configurations are typically defined within a `ServiceMonitor` resource. The correct syntax for defining relabelings in a `ServiceMonitor` is as follows:

```yaml
relabelings:
  - sourceLabels: [<source_label1>, <source_label2>, ...]
    separator: <separator>
    regex: <regex>
    targetLabel: <target_label>
    replacement: <replacement>
    action: <action>
```

Each relabeling rule should be placed under the `relabelings` field, and it includes properties such as `sourceLabels`, `separator`, `regex`, `targetLabel`, `replacement`, and `action` <sup>[[1]](https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml)</sup><sup>[[2]](https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml)</sup>.

Ensure that your relabeling configuration is placed correctly within the Helm chart's values file. It might be necessary to check the chart's documentation or values schema to confirm the correct placement and structure for relabeling configurations. If the chart does not support direct relabeling configurations in the way you're attempting, you may need to customize the `ServiceMonitor` or other related resources directly.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/aa147829-54d7-4432-8e99-480e1d1569be?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/aa147829-54d7-4432-8e99-480e1d1569be?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/aa147829-54d7-4432-8e99-480e1d1569be?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/aa147829-54d7-4432-8e99-480e1d1569be?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/aa147829-54d7-4432-8e99-480e1d1569be?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/aa147829-54d7-4432-8e99-480e1d1569be?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/aa147829-54d7-4432-8e99-480e1d1569be?feedback_type=other)</sup>
