### DISCUSSION TITLE
How to use HEADERS with `remote_write`

### DISCUSSION THREAD

**Discussion by ryayon** [prometheus-operator/prometheus-operator#7375] [Q&A] [answered]
Hello,

The Prometheus remote write endpoint, we have to send metrics to, requests a token authentication via headers.

I tried:
```
  prometheusSpec:
    remoteWrite:
      - url: https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/api/v1/push
        headers:
          'X-TOKEN': ${TOKEN_SECRET_KEY}
```

However, neither the `headers` parameter is available, nor a way to provide an env variable for `TOKEN_SECRET_KEY`.

Do you see a way to implement something like this ?

I can only see Basic-Auth for authentication.

**Comment by dosubot** [comment]
Hey @ryayon,

I'm here to help you with any coding bugs, questions, or becoming a contributor. Let me know how I can assist you!

[Dosu](https://dosu.dev)


The Prometheus Operator does support setting custom headers for the `remote_write` configuration. You can specify custom HTTP headers using the `headers` field, but it seems like you are trying to use an environment variable directly within the configuration, which is not supported in this way.

To achieve your goal, you can use Kubernetes Secrets to manage sensitive data like tokens. Here's a general approach:

1. **Create a Kubernetes Secret** to store your token:
   ```bash
   kubectl create secret generic my-token-secret --from-literal=token=<your-token-value>
   ```

2. **Reference the Secret in your Prometheus configuration**:
   You can use the `valueFrom` field to reference the secret in your configuration. Unfortunately, direct environment variable substitution in the `headers` field is not supported, so you need to manage this through Kubernetes Secrets.

3. **Example configuration**:
   ```yaml
   prometheusSpec:
     remoteWrite:
       - url: https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/api/v1/push
         headers:
           X-TOKEN: <your-token-value>
   ```

While the Prometheus Operator supports custom headers, it does not directly support environment variable substitution in the configuration. You need to manage sensitive data using Kubernetes Secrets and manually update the configuration with the secret values.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/ac5c8025-c3f3-498d-a9c2-c262cc91e7f8?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/ac5c8025-c3f3-498d-a9c2-c262cc91e7f8?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/ac5c8025-c3f3-498d-a9c2-c262cc91e7f8?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/ac5c8025-c3f3-498d-a9c2-c262cc91e7f8?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/ac5c8025-c3f3-498d-a9c2-c262cc91e7f8?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/ac5c8025-c3f3-498d-a9c2-c262cc91e7f8?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/ac5c8025-c3f3-498d-a9c2-c262cc91e7f8?feedback_type=other)</sup>

**Reply by ryayon** [reply]
Thank you @dosu for your really quick feedback.

Actually, this is pretty much what I did except I don't know where to put the `valueFrom`.
In the Specs of the `config-reloader` container ?

**Comment by ryayon** [comment, marked as answer]
Actually, replacing:
```
prometheusSpec:
  remoteWrite:
    - url: https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/api/v1/push
      headers:
        X-TOKEN: <your-token-value>
```
with
```
prometheusSpec:
  remoteWrite:
    - url: https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/api/v1/push
        authorization:
          type: Bearer
          credentials:
            name: <secret-name>
            key: <your-token-value>
```
works
