### ISSUE TITLE
Helm kube-prometheus for GCE ETCD endpoint

### ISSUE THREAD

**Issue by sebglon** [prometheus-operator/prometheus-operator#1005]
On latest version of kube-prometheus Chart, i have no metrics for etcd, kube-scheduler, kube-controller-manager.

After seeing this page: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/etcd/etcd-bootkube-gce.yaml write by @brancz , i have added the values like that:

```
exporter-kube-etcd:
  endpoints:
    - 10.142.0.2
  etcdPort: 2379
  scheme: https
```

But this not work. I have timeout.

How can i config or find the right endpoint?
