### ISSUE TITLE
Setting the `namespace` for `alertmanagers` to the current namespace in the `alertsmanager` of a Prometheus spec

### ISSUE THREAD

**Issue by bgagnon** [prometheus-operator/prometheus-operator#1078]
This is a feature request for a way to set `namespace` of Alertmanager endpoints based on the namespace of the Prometheus custom resource itself.

```yaml
  alerting:
    alertmanagers:
    - name: my-alertmanager
      namespace: "<THIS-NAMESPACE>"
      port: web
```

The [`endpoints` discovery role](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#endpoints) for `kubernetes_sd_config` supports an empty `namespaces` array, but this will match endpoints from _all_ namespaces, which is not desired:

```
# Optional namespace discovery. If omitted, all namespaces are used.
namespaces:
  names:
    [ - <string> ]
```

Using the "current" namespace is the expected behavior for normal Kubernetes selectors, but it is somewhat ambiguous here since we are trying to produce a Prometheus configuration, not an actual selector.
