### ISSUE TITLE
Prometheus uses only one of AlertmanagerEndpoints

### ISSUE THREAD

**Issue by tomplus** [prometheus-operator/prometheus-operator#1179]
**What did you do?**

I have defined the section `alertmanagers` with two AlertmanagerEndpoints:

```
spec:
  alerting:
    alertmanagers:
    - name: proxy-alert-manager-az1
      namespace: monitoring
      port: http
    - name: proxy-alert-manager-az2
      namespace: monitoring
      port: http
```

There are defined `endpoints`:
```
$ kubectl get endpoints -n monitoring
proxy-alert-manager-az1   172.31.91.222:80
proxy-alert-manager-az2   172.31.29.66:80
```

but Prometheus uses only the second address (`/status`):
```
Endpoint
--
http://172.31.29.66:80/api/v1/alerts
```

Prometheus has configuration:

```
alerting:
  alertmanagers:
  - kubernetes_sd_configs:
    - api_server: null
      role: endpoints
      namespaces:
        names:
        - monitoring
    scheme: http
    path_prefix: /
    timeout: 10s
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: proxy-alert-manager-az1
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: http
      replacement: $1
      action: keep
  - kubernetes_sd_configs:
    - api_server: null
      role: endpoints
      namespaces:
        names:
        - monitoring
    scheme: http
    path_prefix: /
    timeout: 10s
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: proxy-alert-manager-az2
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: http
      replacement: $1
      action: keep
```

**What did you expect to see?**

Prometheus uses two endpoints to send alerts.

**What did you see instead? Under which circumstances?**

Prometheus uses the only one address.

**Environment**

* Kubernetes version information: 1.8.3, 
* prometheus-operator: 0.17.0
* prometheus 2.2.1
