### ISSUE TITLE
RuleSelector Extending

### ISSUE THREAD

**Issue by Atoms** [prometheus-operator/prometheus-operator#1184]
**What did you do?**
Create cluster role to be able to watch/list/get configmaps

**What did you expect to see?**
Expectation is to select rules across all cluster not just namespace in which prometheus resides

**What did you see instead? Under which circumstances?**
Configmaps with labels are not detected in other namespaces

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"archive", BuildDate:"2018-02-07T07:49:13Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
    kubespray

* Manifests:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: app-metrics
  namespace: default
  labels:
    prometheus: app-metrics
spec:
  version: v2.2.0
  logLevel: debug
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      tier: frontend
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 2Gi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: 9093
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: app-metrics
```
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

```
