### ISSUE TITLE
kube-prometheus grafana Helm Chart Missing service.labels Override

### ISSUE THREAD

**Issue by mikeln** [prometheus-operator/prometheus-operator#1350]
**What did you do?**
Deploy kube-prometheus, with additional labels set for grafana, alertmanager, prometheus services.

**What did you expect to see?**
The labels present on the deployed services.

**What did you see instead? Under which circumstances?**
The labels were present on all services except grafana.

The grafana chart does not have a way to supply additional service.labels in the chart (similar to alertmanager.service.labels, and prometheus.service.labels  in those respective charts).

**Environment**

* Kubernetes version information:

```
        Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
     Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kraken aws cluster

* Manifests:

```
kube-prometheus --set=values.yaml

grafana:
   service:
      labels:
          custom: label

```

* Prometheus Operator Logs:

N/A

**Comment by mikeln** [comment]
to be more explicit:  here is alertmanager service.yaml
```
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    alertmanager: {{ .Release.Name }}
    app: {{ template "alertmanager.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
```

vs  grafana svc.yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
```

- note the missing section to allow extra user specified labels...
