### ISSUE TITLE
prometheusRules in values.yaml being ignored

### ISSUE THREAD

**Issue by transient1** [prometheus-operator/prometheus-operator#1355]
**What did you do?**
I'm trying to get a handle on Helm and Prometheus, so I'm experimenting and making small changes to see what Helm does. I edited prometheus/values.yaml by uncommenting out "prometheusRules" and added my own small block (which is actually just a block taken from the Prometheus website as an example of a rules file).

**What did you expect to see?**
I expected that when I ran `helm template prometheus -x templates/configmap.yaml` to test the config, I would see my custom contents in the configmap instead of the contents from prometheus.rules.yaml. My understanding of configmap.yaml is that if prometheusRules is not defined in values.yaml, it will use prometheus.rules.yaml instead. Since I defined prometheusRules, I expected that content to be in the configmap. 

**What did you see instead? Under which circumstances?**
If I remove the if/else portion of the block in the configmap, leaving a static declaration of Values.prometheusRules, this is the configmap output

```
# Source: prometheus/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "prometheus"
    chart: prometheus-0.0.17
    heritage: Tiller
    prometheus: RELEASE-NAME
    release: RELEASE-NAME
    role: alert-rules
  name: RELEASE-NAME-prometheus
data:
```

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kops

* Manifests:
values.yaml
```
# default rules are in templates/prometheus.rules.yaml
prometheusRules:
groups:
- name: example
  rules:
  - alert: HighErrorRate
    expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
    for: 10m
    labels:
      severity: page
    annotations:
      summary: High request latency
```
ConfigMap
```
data:
{{- .Values.prometheusRules }}
{{- $root := . }}
{{- range $key, $val := .Values.prometheusRules }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
```

* Prometheus Operator Logs:

Not relevant. (I don't think)

**Comment by transient1** [comment]
I tried using `helm install prometheus --dry-run --debug` instead, just in case there was something needed from Tiller to render that block. The computed values portion shows my specific config
```
COMPUTED VALUES:
alertingEndpoints: []
config:
  specifiedInValues: true
  value: {}
externalLabels: {}
externalUrl: ""
global:
  rbacEnable: true
groups:
- name: example
  rules:
  - alert: HighErrorRate
    annotations:
      summary: High request latency
    expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
    for: 10m
    labels:
      severity: page
```

But the rendered configmap has an empty data block
```
---
# Source: prometheus/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "prometheus"
    chart: prometheus-0.0.17
    heritage: Tiller
    prometheus: jolly-duck
    release: jolly-duck
    role: alert-rules
  name: jolly-duck-prometheus
data:
```

**Comment by aranair** [comment]
I think it needs a key. Try this:

```
prometheusRules: 
  test.rules: |-
    groups:
      - name: test.rules
         rules: 
         - alert: ...
...
```
