### ISSUE TITLE
Servicemonitor for kube-apiserver is discovered using wrong namespace

### ISSUE THREAD

**Issue by altoic** [prometheus-operator/prometheus-operator#1371]
**What did you do?**
I deployed operator with the kube-prometheus manifests. And I am changing the servicemonitors for my own cluster parameters. One of the servicemonitors that are not working as I expected is the apiserver. The configuration default matchNames: default and picks up my apiserver running in the kube-system namespace. The tags are also misaligned. 
**What did you expect to see?**
I did not expect the service discovery to actually pick up my API server since its configured to the wrong namespace and different tags. 

**What did you see instead? Under which circumstances?**
## My apiserver description:
```
k describe po/kube-apiserver -n kube-system
Name:         kube-apiserver
Namespace:    kube-system
Start Time:   Tue, 24 Apr 2018 15:02:06 -0400
Labels:       component=kube-apiserver
                   tier=control-plane
```

## my apiserver servicemonitor config

```
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serverName: kubernetes
  jobLabel: component
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
```

**Environment**
set up using the manifests from kube-prometheus 
* Kubernetes version information:

```
 1.10
```
* Kubernetes cluster kind: 
I actually don't know. another team handles the deployment :D 

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```
