### ISSUE TITLE
Kubelet service on wrong port

### ISSUE THREAD

**Issue by ashiddo11** [prometheus-operator/prometheus-operator#1400]
I'm using the prometheus operator chart with kubernetes 1.9.6
The kubelet service is listening on port 10250 however cadvisor on the nodes listens on 10255. Can we make the kubelet port a variable so that we can change it depending on the port we're using?

**Comment by brancz** [comment]
Actually the underlying endpoints object already genrates all 3 ports:

```
  ports:
  - name: http-metrics
    port: 10255
    protocol: TCP
  - name: cadvisor
    port: 4194
    protocol: TCP
  - name: https-metrics
    port: 10250
    protocol: TCP
```

It's a bug, that the Service doesn't have all three.

**Comment by ashiddo11** [comment]
It works if I change port from **https-metrics** to **http-metrics** even thought the service doesn't have all three ports

```apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  clusterName: ""
  labels:
    prometheus: main
  name: kubelet
  namespace: kube-system
spec:
  endpoints:
  - interval: 30s
    port: http-metrics
  jobLabel: kubelet
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kubelet
```

```
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kubelet
  name: kubelet
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: https-metrics
    port: 10250
    protocol: TCP
    targetPort: 10250
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
