### ISSUE TITLE
K8SApiserverDown alert always triggers due to querying on non-existent job name

### ISSUE THREAD

**Issue by ralphmcneal** [prometheus-operator/prometheus-operator#1418]
**What did you do?**
Installed version 0.0.17 of kube-prometheus via helm.

**What did you expect to see?**
Everything installed fine. I do, however, get the K8SApiserverDown alert even though the api is up.
When looking at my targets, I see the apiserver has a job name of "kubernetes". The alert queries for a job name of "apiserver". 

The alert in question is in `helm/exporter-kubernetes/templates/kubernetes.rules.yaml`

```
  - alert: K8SApiserverDown
    expr: absent(up{job="apiserver"} == 1)
    for: 20m
    labels:
      severity: critical
    annotations:
      description: No API servers are reachable or all have disappeared from service
        discovery
      summary: No API servers are reachable
```

When looking at the prometheus configuration file, I see you always use `__meta_kubernetes_service_name` as the job name. In my cluster, the service name is "kubernetes" not "apiserver". This naming mismatch causes the K8SApiserverDown alert to remain in a triggered state.

```
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
```

![apiserver_scrape_target](https://user-images.githubusercontent.com/11877976/40860259-61c49694-65aa-11e8-8f01-188085700249.png)

**Environment**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
 custom install via ansible.

Is this naming unique to my cluster or should the job name be changed in the exporter-kubernetes alerting rule?
