### ISSUE TITLE
Prometheus with nfs persistent storage

### ISSUE THREAD

**Issue by vinodhbasavani** [prometheus-operator/prometheus-operator#1454]
**What did you do?**
I created the following yml file to create prometheus with nfs persistent storage.
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-persistent-storage
  labels:
    app: prometheus-persistent-storage
spec:
  capacity:
    storage: 80Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: x.x.x.x
    path: /export/pool1/monitoring-prod/prometheus-persistent-storage

---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
spec:
  replicas: 2
  version: v2.2.0-rc.1
  externalUrl: https://prometheus.example.com
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  resources:
    requests:
      memory: 1Gi
  retention: 168h
  storage:
    volumeClaimTemplate:
      spec:
        selector:
          matchLabels:
            app: prometheus-persistent-storage
        resources:
          requests:
            storage: 40Gi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
```
**What did you expect to see?**
I would see creating two prometheus pod using the given nfs endpoint mounted to both pods
**What did you see instead? Under which circumstances?**
It is not using the claim template mentioned above and it is using the default claim only. It is trying to create the ebs volumes.
```
Name:          prometheus-k8s-db-prometheus-k8s-0
Namespace:     monitoring
StorageClass:  gp2
Status:        Pending
Volume:
Labels:        app=prometheus
               prometheus=k8s
Annotations:   volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/aws-ebs
Finalizers:    []
Capacity:
Access Modes:
```
**Environment**

* Kubernetes version information:
1.8.8.
	insert output of `kubectl version` here
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.8", GitCommit:"2f73858c9e6ede659d6828fe5a1862a48034a0fd", GitTreeState:"clean", BuildDate:"2018-02-09T21:23:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

 kops

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```
