### ISSUE TITLE
Add service annotations support (Enhancement proposal)

### ISSUE THREAD

**Issue by jalberto** [prometheus-operator/prometheus-operator#1547]
In non-operator helm prometheus there is a interesting defautl configuration that allows to scrape any service or endpoints with specific annotations:

```
annotations:
  prometheus.io/port: "80"
  prometheus.io/scrape: "true"
```

I think a default 'ServiceMonitor' with similar configuration can be very useful (in particular for migrations)

**Comment by brancz** [comment]
The reason this is not used here is because the Prometheus upstream team (which we are all part of) advises against it, as it is very limited in what it can do. In fact it's the very reason the `ServiceMonitor` object exists.

A few examples of things that are impossible with this approach:

* any targets with multiple ports
* any targets that don't all have the exact same authentication, http and TLS configuration
* selection is an all or nothing, not based on the well known label selection paradigm in Kubernetes

If you want to mimic a behavior close to this (although with labels rather than annotations, labels are better because they are actually indexed in Kubernetes), then you can create a `ServiceMonitor` that selects all `Service` objects with the label selector `prometheus.io/scrape: "true"`. This will either take all ports or the defined port on the `ServiceMonitor`.

Alternatively you can use the `additionalScrapeConfigs` to write your own relabeling rules to select `Service`s that way.

**Comment by jalberto** [comment]
@brancz thanks for the reasoning, it makes sense and is a fair point. As an addition I still think a basic predefined SM for this task can be useful in the case of simplest metrics (the ones that doesn't require multiple ports or any kind of customization).

**Comment by brancz** [comment]
Yeah I think it's reasonable to document a `ServiceMonitor` that works for a broad common case.

**Comment by HaveFun83** [comment]
It will be great if someone can document an example ServiceMonitor for this use case.

**Comment by sstarcher** [comment]
Certainly going forward ServiceMonitor is the preferred approach, but if I install a new service from say a helm chart that uses the old prometheus.io/scrape true it would be great if it just worked instead of the user having to do extra work on their end.  I was hoping going from the Prometheus helm chart to the Prometheus operator helm chart would require less work.

**Comment by sstarcher** [comment]
I tossed this into the helm values for the prometheus-operator helm chart.  Please notice the `node-exporter` at the bottom if you don't drop it, it will be scraped twice as it still has the old annotation also.  I have overridden the name so yours will be different.

```
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
        # Scrape config for service endpoints.
      #
      # The relabeling allows the actual service scrape endpoint to be configured
      # via the following annotations:
      #
      # * `prometheus.io/scrape`: Only scrape services that have a value of `true`
      # * `prometheus.io/scheme`: If the metrics endpoint is secured then you will need
      # to set this to `https` & most likely set the `tls_config` of the scrape config.
      # * `prometheus.io/path`: If the metrics path is not `/metrics` override this.
      # * `prometheus.io/port`: If the metrics are exposed on a different port to the
      # service then set this appropriately.
      - job_name: 'kubernetes-service-endpoints'

        kubernetes_sd_configs:
          - role: endpoints

        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            action: replace
            target_label: __scheme__
            regex: (https?)
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_name
          - source_labels: [__meta_kubernetes_service_name]
            action: drop
            regex: 'node-exporter'
```
