### ISSUE TITLE
Unable to update the alert rules 

### ISSUE THREAD

**Issue by bigbasket-minjar** [prometheus-operator/prometheus-operator#1595]
**What did you do?**
I have added a new alert rule using custom-values.yaml and after that when tried to update the alert expression, its not reflecting in the prometheus-kube-prometheus-rulefiles  config map.

custom-values.yaml  - old settings 

```
prometheus:
    # default rules are in templates/general.rules.yaml
    prometheusRules:
      test2a.rule.yaml: |-
        groups:
          - alert: httbinDeploymentMissing
            expr: kube_deployment_status_replicas{deployment="httpbin"} < 1
            for: 5m
            labels:
              severity: critical
            annotations:
              description: Prometheus could not find the Simple Deployment
              summary: Testing alerts.
```

custom-values.yaml  - new  settings 

```
prometheus:
    # default rules are in templates/general.rules.yaml
    prometheusRules:
      test2a.rule.yaml: |-
        groups:
          - alert: httbinDeploymentMissing
            expr: kube_deployment_status_replicas{deployment="httpbin"} < 2
            for: 5m
            labels:
              severity: critical
            annotations:
              description: Prometheus could not find the Simple Deployment
              summary: Testing alerts.

```
This is the command I tried to upgrade the chart
`helm upgrade kube-prometheus coreos/kube-prometheus -f custom-values.yaml`

**What did you expect to see?**
In Prometheus dasboard, alert rule should be updated with an expression as 
  expr: kube_deployment_status_replicas{deployment="httpbin"} < 2

**What did you see instead? Under which circumstances?**

**Environment**

* Kubernetes version information:

	insert output of `kubectl version` here

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
kops
	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by Blasterdick** [comment]
Same thing on `prometheus-operator` v0.22.0 (w/o helm). Changes to the configmap don't reflect to `prometheus-prometheus-server-rulefiles-0` configmap. 

Any change gets provisioned only if I delete an appropriate `prometheusrule`.

**Comment by brancz** [comment]
Starting with v0.21 the configmaps are created through prometheusrule objects so those are the objects you want to update when you want to change rules.

**Comment by Blasterdick** [comment]
Oh, so I have to get every `prometheusrule` to `yaml` and work with that resource. Copy that, thank you, @brancz , now everything seems to work as expected.

**Comment by vielktus** [comment]
Sorry, I still don't get how to change the rules using new this new CRD. Could you please show me how to do this ? Where should I edit in the Helm when I want to insert new rules ?

**Comment by brancz** [comment]
@vielktus could you first check which version of the Operator you are running? I believe the helm charts have not been updated yet to use versions that use that CRD.

**Comment by brancz** [comment]
hmm ok, so ideally the helm charts would just adopt the CRDs (they are community maintained and sometimes lag behind a little). Until then you can modify them by just running

```
kubectl -n <namespace> edit prometheusrule <rule-object-name>
```

And you can find rules in a namespace by

```
kubectl -n <namespace> get prometheusrule
```

**Comment by vielktus** [comment]
Thanks @brancz

**Comment by airwolfnh** [comment]
I had the same problem, then I updated to the latest version, rules are being updated now, but ServiceMonitors are not being picked as targets on prometheus, also,  adding grafana dashboards with json files to the grafana folder does not work either.

**Comment by hobbsh** [comment]
I use ansible to deploy alert rules and just delete the affected prometheusrules before reapplying as a workaround for now. Not great but better than missing rules.

**Comment by msafarisc** [comment]
@brancz I have a similar issue.
my PrometheusRule rule seems fine:
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: prometheus
    role: alert-rules
  name: prometheus-prometheus-rulefiles-0
  namespace: monitoring
spec:
  groups:
...
...
```

seems fine and I don't see any error on prometheus-operator but my `prometheus-prometheus-rulefiles-0` never gets updated and is always empty.  I can verify that with`kubectl -n monitoring get prometheusrule` that prometheusrule is there.

**Comment by msafarisc** [comment]
nvm. my `role` label was wrong.

**Comment by ArjonBu** [comment]
@msafarisc what is "role" supposed to be for?

**Comment by amartorelli** [comment]
I have a similar issue, like @msafarisc . The definition looks good, but doesn't show in Prometheus:
```
Name:         statuspager
Namespace:    monitoring
Labels:       app=statuspager
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"monitoring.coreos.com/v1","kind":"PrometheusRule","metadata":{"annotations":{},"labels":{"app":"statuspager"},"name":"statu...
API Version:  monitoring.coreos.com/v1
Kind:         PrometheusRule
Metadata:
  Creation Timestamp:  2019-07-24T15:43:21Z
  Generation:          1
  Resource Version:    125034781
  Self Link:           /apis/monitoring.coreos.com/v1/namespaces/monitoring/prometheusrules/statuspager
  UID:                 c3aa4dd4-ae29-11e9-8040-42010a840182
Spec:
  Groups:
    Name:  statuspager
    Rules:
      Alert:  DatasourceErrors
      Annotations:
        Description:  Statuspager cannot read from datasource
        Summary:      Datasource unreachable
      Expr:           rate(statuspager_datasource_request_errors_total[10m]) > 0
      For:            15m
      Labels:
        Severity:  warning
      Alert:       StatuspageErrors
      Annotations:
        Description:  Statuspager cannot post component updates to Statuspage
        Summary:      Statuspage unreachable
      Expr:           rate(statuspager_statuspage_request_errors_total[10m]) > 0
      For:            15m
      Labels:
        Severity:  warning
Events:            <none>
```

**Comment by saurabhshendye** [comment]
I am having similar issue as @msafarisc as well. I can see my prometheus rule with `kubectl get prometheusrule -n monitoring` but can't find the same in `prometheus-prometheus-rulefiles-0` config map

**Comment by shockfish** [comment]
First is check what is your Rule Selector, by:
1. Get current prometheus CRD (with default namespace is **monitoring**)
`kubectl describe prometheus $(kubectl get -n monitoring -o=name) -n monitoring`
2. Find Rule Selector, like:
```
Rule Selector:
    Match Labels:
      App:      prometheus-operator
      Release:  monitoring
```
3. In your PrometheusRule set labels as above:
```
...
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-operator
    release: monitoring
...
```
