### ISSUE TITLE
metricRelabelings in ServiceMonitor

### ISSUE THREAD

**Issue by fumanne** [prometheus-operator/prometheus-operator#1604]
I have some  k8S cluster (mon, foundation.....), every k8s cluster have installed prometheus, now the mon cluster is the Top cluster and it federate from other cluster metics, the mon cluster prometheus servicemonitor looks like this:
```
  serviceMonitors:
    - name: foundation-prometheus
    namespaceSelector:
      matchNames:
      - monitoring
    selector:
      matchLabels:
        cluster: foundation
    endpoints:
    - port: foundation-port
      honorLabels: true
      path: /federate
      params:
        'match[]':
         - '{__name__=~".+"}'
      metricRelabelings:
        - sourceLabels: [__meta_kubernetes_service_label_cluster]
          targetLabel: cluster
          regex: (.*)
          replacement: ${1}
          action: replace
```
and the prometheus web console look like this:
![11111](https://user-images.githubusercontent.com/5414434/42547133-2851ac7c-84f3-11e8-9a79-e64a23dbd516.png)

Then the prometheus configure like this:
```
- job_name: monitoring/foundation-prometheus/0
  honor_labels: true
  params:
    match[]:
    - '{__name__=~".+"}'
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /federate
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names:
      - monitoring
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_cluster]
    separator: ;
    regex: foundation
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: foundation-port
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: foundation-port
    action: replace
  metric_relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_cluster]
    separator: ;
    regex: (.*)
    target_label: cluster
    replacement: ${1}
    action: replace

```

 I want to add __meta_kubernetes_service_label_cluster this label into TargetLabels
But it did not work. also in every metrics there is no "cluster=xxxx" label.
why?

prometheus-operator version:  v0.18.0
prometheus version: v2.2.1

**Comment by brancz** [comment]
You can use the `targetLabels` field for this. See here: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#servicemonitorspec

**Comment by fumanne** [comment]
@brancz 
you mean config like this:
```
  - name: foundation-prometheus
    namespaceSelector:
      matchNames:
      - monitoring
    selector:
      matchLabels:
        cluster: foundation
    **targetLabels:
      - cluster**
    endpoints:
    - port: foundation-port
      honorLabels: true
      path: /federate
      params:
        'match[]':
         - '{__name__=~".+"}'
      metricRelabelings:
        - sourceLabels: [__meta_kubernetes_service_label_cluster]
          targetLabel: cluster
          regex: (.*)
          replacement: ${1}
          action: replace
```
now I add 
```
targetLabels: 
  - cluster
```
but it still not work.
