### ISSUE TITLE
Custom alert for pod memory utilisation 

### ISSUE THREAD

**Issue by Manu-Thankachan** [prometheus-operator/prometheus-operator#1702]
**What did you do?**
Created alert rules for pod memory utilisation 
**What did you expect to see?**
Show the alert for pod memory utilisation of my apps
**What did you see instead? Under which circumstances?**
Alerts are showing perfectly, But it do not contain the name of the pod so that difficult to understand which pod is having the issue . It is Just showing " [FIRING:35]  (POD_MEMORY_HIGH_UTILIZATION default/k8s warning). But when I look in to the "Alert" section I can see the fired rules with its pod name.

**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by manuprometheus** [comment]
My rule is as follows:
```
- alert: POD_MEMORY_HIGH_UTILIZATION
      annotations:
        description: "pod {{$labels.pod}} is using high memory"
        summary: "HIGH Memory USAGE WARNING for{{$labels.pod}}"
      expr: (sum(rate(container_memory_usage_bytes[5m]))by(pod_name)*100) >90
      for: 1m
      labels:
        severity: warning
```
