### ISSUE TITLE
Helm - PodAntiAffinity topology key not configurable

### ISSUE THREAD

**Issue by lli-hiya** [prometheus-operator/prometheus-operator#1715]
**What did you do?**
I'd like to spread replicas of Prometheus across availability-zones
**What did you expect to see?**
I expect I could configure that though PodAntiAffinity - `TopologyKey: failure-domain.beta.kubernetes.io/zone`
**What did you see instead? Under which circumstances?**

From `Prometheus.yaml` helm chart
```
{{- if eq .Values.podAntiAffinity "hard" }}
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app: {{ template "prometheus.name" . }}
            prometheus: {{ .Values.prometheusLabelValue | default .Release.Name | quote }}
{{- else if eq .Values.podAntiAffinity "soft" }}
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app: {{ template "prometheus.name" . }}
              prometheus: {{ .Values.prometheusLabelValue | default .Release.Name | quote }}
{{- end }}
```
The `topologyKey` has been hard-coded to `kubernetes.io/hostname`

I'd like to submit a PR to fix this issue.
