### ISSUE TITLE
Adding additional relabeling rules to alert_relabel_configs:

### ISSUE THREAD

**Issue by atyronesmith** [prometheus-operator/prometheus-operator#1805]
**What did you do?**
Added an additional AlertManager relable rule to remove a label
to suppress duplicate alerts.  

```
apiVersion:` monitoring.coreos.com/v1
kind: Prometheus
metadata:
  clusterName: ""
  creationTimestamp: 
  generation:
  labels:
    prometheus: prometheus-sa-telemetry
  name: blue
  namespace: sa-telemetry
spec:
  alerting:
    alert_relabel_configs:
    - regex: (.+)\d+
      source_labels: src_qdr
      target_label: src_qdr
```
**What did you expect to see?**
Expected to see the additional rule in the Prometheus config file.

**What did you see instead? Under which circumstances?**

```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    prometheus: sa-telemetry/blue
    prometheus_replica: prometheus-blue-0
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
  alertmanagers:
  - kubernetes_sd_configs:

```

Looking at the code at: [promcfg.go](https://github.com/coreos/prometheus-operator/blob/6a78d1e8f19a380661af8dec6c64c37ba03744e5/pkg/prometheus/promcfg.go#L194)

it seems like the alert_relabel_configs: section is hard coded.  Is this the case?
Is it possible to rewrite/remove AlertManager labels?

**Environment**
Linux

* Prometheus Operator version:
  image: 'quay.io/coreos/prometheus-operator:v0.23.0'

* Kubernetes version information:

kubernetes v1.9.1+a0ce1bc657
