### ISSUE TITLE
Need help in setup  of new Prometheus instance for ambassador api gateway

### ISSUE THREAD

**Issue by 2dev2** [prometheus-operator/prometheus-operator#1825]
**What did you do?**
we have working Prometheus operator with node-exporter, kubelet
But when i try to setup a new Prometheus instance  for monitoring of a ambassador api gateway(envoy) in different name space,(ambassador service  is generating a promethus metrics )  Prometheus is able to discover it, attached screen shots- 
![targets](https://user-images.githubusercontent.com/8681544/44625541-aca44480-a929-11e8-9a83-af51a31a71e1.png)

But in target its not showing, ( i am aware of that _meta label will be dropped by Prometheus) 

**What did you expect to see?**
In target ambassador service should show, so that we can be sure that prometheus is able to scrap the metric from services

**What did you see instead? Under which circumstances?**
I am not able to see any thing in targets, for this Prometheus instance

**Environment**

* Prometheus Operator version:

	Prometheus operator v0.23.1

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.2", GitCommit:"384b4eaa132ca9a295fcb3e5dfc74062b257e7df", GitTreeState:"clean", BuildDate:"2018-08-15T00:10:14Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
service generating the metrics
apiVersion: v1
kind: Service
metadata:
  name: ambassador-monitor
  labels:
    service: ambassador-monitor
spec:
  selector:
    service: ambassador
    tier: frontend
  type: ClusterIP
  clusterIP: None
  ports:
  - name: prometheus-metrics
    port: 9102
    targetPort: 9102
    protocol: TCP

service monitor for ambassador------------

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ambassador-monitor
  labels:
    ambassador: monitoring
    tier: frontend
spec:
  jobLabel: ambassador
  selector:
    matchLabels:
      tier: frontend
      service: ambassador-monitor
  endpoints:
  - port: prometheus-metrics
    interval: 10s
  namespaceSelector:
    matchNames:
    - default
  targetLabels:
    - ambassador

Prometheus instance yaml---
![targets label](https://user-images.githubusercontent.com/8681544/44625458-d9eff300-a927-11e8-8792-38991101eeec.png)

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-ambassador
  labels:
    prometheus: frontend
spec:
  serviceMonitors:
    matchLabels:
      tier: frontend
      service: ambassador-monitor
  resources:
    requests:
      memory: 200Mi e

```

* Prometheus Operator Logs:

```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    prometheus: monitoring/prometheus-ambassador
    prometheus_replica: prometheus-prometheus-ambassador-0
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
rule_files:
- /etc/prometheus/rules/prometheus-prometheus-ambassador-rulefiles-0/*.yaml
scrape_configs:
- job_name: monitoring/ambassador-monitor/0
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names:
      - default
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_service]
    separator: ;
    regex: ambassador-monitor
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_service_label_tier]
    separator: ;
    regex: frontend
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: prometheus-metrics
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_label_ambassador]
    separator: ;
    regex: (.+)
    target_label: ambassador
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_label_ambassador]
    separator: ;
    regex: (.+)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: prometheus-metrics
    action: replace
```
