### ISSUE TITLE
How can I add configuration in Prometheus.yml

### ISSUE THREAD

**Issue by subinmt** [prometheus-operator/prometheus-operator#1860]
**What did you do?**
I need to add some configuration for my kafka in prometheus yaml as follow:
___________
global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'kafka_pod_job'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: kafkametrics.*
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
___________

**What did you expect to see?**
Please let me know How can I add the above thing in this Prometheus setup.
**What did you see instead? Under which circumstances?**

**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by metalmatze** [comment]
You should be able to create a ServiceMonitor for your application to be monitored. The Prometheus Operator will pick up that ServiceMonitor and then generate its own Prometheus configuration based on that. This way you can extend your already existing Prometheus configuration.

**Comment by veerendra2** [comment]
Hi,
I have same issue that I want to add config to scrap external node metrics(node_exporter). I don't see any `endpoint` (URL) in existing service monitor yaml file. For example, kubelet service monitor below,
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kubelet
  name: kubelet
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 30s
    port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 30s
    path: /metrics/cadvisor
    port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kubelet

``` 
Where or how can I specify endpoint URL in service monitor. Can you suggest any temple config?

**Comment by brancz** [comment]
If your node-exporter is on the same nodes as the kubelet, you can duplicate the servicemonitor and rename it to node-exporter, and then in the `endpoints` you can specify `targetPort: <node-exporter-port>` to force the port to be that port.

If the node-exporters are actually completely external, you can use the `additionalScrapeConfigs` feature to have the Prometheus server load arbitrary Prometheus configuration.

**Comment by veerendra2** [comment]
@brancz Thanks. 
I'm sorry, not sure where to specify the option `additionalScrapeConfigs` in `ServiceMonitor`. Can you please provide any example or reference document

**Comment by subinmt** [comment]
@metalmatze Actually I am using a Kafka-zookeeper cluster using cluster operator and the metrics for Kafka and Zookpper are inbuilt. As per your update if I create a service monitor, Then I should add the metrics listening port in the application service also. But I am failing to do that in my kafka setup.

**Comment by robsonpeixoto** [comment]
Any ideia why it's not working?

`> cat secret.yml`
```
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-federation-extra
  namespace: monitoring-federation
data:
  federation.yaml: "LSBqb2JfbmFtZTogJ2ZlZGVyYXRlJwoKICBob25vcl9sYWJlbHM6IHRydWUKICBtZXRyaWNzX3BhdGg6ICcvZmVkZXJhdGUnCgogIHBhcmFtczoKICAgICdtYXRjaFtdJzoKICAgICAgLSAne19fbmFtZV9fPX4iLisifScKCiAgc3RhdGljX2NvbmZpZ3M6CiAgICAtIHRhcmdldHM6CiAgICAgIC0gJzE3Mi4zMS4wLjEwOjkwOTAnCiAgICAgIC0gJzE3Mi4zMS4wLjg6OTA5MCcKICAgICAgLSAnMTcyLjI5LjAuMTk1OjkwOTAnCiAgICAgIC0gJzE3Mi4zMC4wLjY6OTA5MCcKICAgICAgLSAnMTcyLjI5LjIuNzo5MDkwJw=="
```

`> cat prometheus.yml`
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: federation
  namespace: monitoring-federation
  labels:
    prometheus: federation
spec:
  retention: 360h
  replicas: 1
  version: v2.3.2
  additionalScrapeConfigs:
    name: prometheus-federation-extra
    key: federation.yaml
    optional: false
  resources:
    requests:
      memory: 8Gi
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: managed-premium
        resources:
          requests:
            storage: 500Gi
```
