### ISSUE TITLE
PrometheusRules reload failed

### ISSUE THREAD

**Issue by whypro** [prometheus-operator/prometheus-operator#1939]
**What did you do?**

1. apply a object of PrometheusRules.
2. wait for prometheus reload.

**What did you expect to see?**

The actual rules in prometheus web page reload successfully.

**What did you see instead? Under which circumstances?**

The actual rules in prometheus web page didn't reload.

reason:

The pod status and prometheus chart show that the container `rules-configmap-reloader` was OOMkilled again and again.

```
  - containerID: docker://227e4149ce21e90e88d5d59121d4cb3de4d495c3503b29213422a9fd8b3d1a3d
    image: configmap-reload:v0.2.2
    imageID: docker-pullable://configmap-reload@sha256:befec9f23d2a9da86a298d448cc9140f56a457362a7d9eecddba192db1ab489e
    lastState:
      terminated:
        containerID: docker://16d113166633ff2b538514d86b0633383f8b9133c6506816cbf14315625a8904
        exitCode: 137
        finishedAt: 2018-09-26T02:54:18Z
        reason: OOMKilled
        startedAt: 2018-09-26T01:56:44Z
    name: rules-configmap-reloader
    ready: true
    restartCount: 5
    state:
      running:
        startedAt: 2018-09-26T02:54:19Z
```

![image](https://user-images.githubusercontent.com/2081494/46054986-60dcf900-c17c-11e8-860c-b459d4832d50.png)

I think the default resource limits (cpu: 5m, memory: 10Mi) of configmap-reloader is not enough. When the container is killed and restarted, the watch action is broken and it can't receive any update event from filesystem. 

What about add the resource limits or make it configurable?

**Environment**

* Prometheus Operator version:

v0.23.1

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-9+f0689c2c048b79", GitCommit:"f0689c2c048b790f57d46f29bc49edfa0d51a8cd", GitTreeState:"clean", BuildDate:"2018-05-07T06:21:33Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

```
kubeadm
```

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```
