### ISSUE TITLE
prometheus helm chart does not allow specification of thanos section inside Prometheus resource

### ISSUE THREAD

**Issue by harshal-shah** [prometheus-operator/prometheus-operator#1965]
**What did you do?** Install kube-prometheus helm chart

**What did you expect to see?** A way to specify thanos section within Prometheus custom resource

**What did you see instead? Under which circumstances?**
There are flags and conditions to specify various labels, annotations etc but there is no way to add a thanos section to the prometheus spec.

**Environment** kubernetes 1.10.6 on AWS with kops 1.10.0

* Prometheus Operator version: 0.0.27

~~~
	docker-pullable://quay.io/coreos/prometheus-operator@sha256:56185c9a4553b452fe620aa0edd1622ef7b677c6c9752953a4bfa949133b75f4
~~~

* Kubernetes version information:

~~~
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
~~~
	
* Kubernetes cluster kind: 

	kops 1.10.0

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: prometheus
    chart: prometheus-0.0.50
    heritage: Tiller
    prometheus: kube-prometheus
    release: kube-prometheus
  name: kube-prometheus
  namespace: monitoring
spec:
  podMetadata:
    labels:
      thanos-peer: 'true'
    annotations:
      iam.amazonaws.com/role: 'SOME_ARN'
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: prometheus
              prometheus: kube-prometheus
          topologyKey: kubernetes.io/hostname
        weight: 100
  alerting:
    alertmanagers:
    - name: kube-prometheus-alertmanager
      namespace: monitoring
      port: http
  baseImage: quay.io/prometheus/prometheus
  externalUrl: http://prometheus.k8s.something.com/
  imagePullSecrets: []
  logLevel: info
  paused: false
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 10Gi
  retention: 240h
  routePrefix: /
  ruleNamespaceSelector:
    any: true
  ruleSelector:
    matchLabels:
      prometheus: kube-prometheus
  thanos:
    peers: thanos-peers.monitoring.svc:10900
    version: v0.1.0
    s3:
      bucket: SOME-S3-BUCKET
      endpoint: s3.eu-east-1.amazonaws.com
  serviceAccountName: kube-prometheus
  serviceMonitorNamespaceSelector:
    any: true
  serviceMonitorSelector:
    matchExpressions:
    - key: prometheus
      operator: In
      values:
      - kube-prometheus
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 400Gi
        storageClassName: default
  version: v2.2.1
```

* Prometheus Operator Logs:

```
NA
```
