### ISSUE TITLE
Alertmanager Config incompatible with Kustomize

### ISSUE THREAD

**Issue by lswith** [prometheus-operator/prometheus-operator#2003]
Alertmanager is configured by specifying a secret with the name:

```
alertmanager-<name>
```

Kustomize and Kubernetes are moving towards creating temporary secrets of the form:
```
alertmanager-<hash>
```
and updating these secrets when the md5sum of the file they reference has changed. 

It would be nice to be able to specify the alertmanager configuration file name in the alertmanager resource. Something like:

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
spec:
   alertmanagerConfig: <config-file-name>
 ```

This would allow kustomize and other tools to update both the Alertmanager resource and specify new versions of the alertmanager config.

**Comment by metalmatze** [comment]
What does a temporary secret in this case mean? 
If it is removed at some point in the life cycle of the Alertmanagers running, I'm not sure we can support this, as we might need to read the secret again.

**Comment by lswith** [comment]
Based on how kustomize is being used with their `SecretGenerator` and `ConfigMapGenerator`, they are waiting for this ticket: https://github.com/kubernetes-sigs/kustomize/issues/242 to finalize the idea of a Kubernetes Garbage Collector.

Within Kustomize, they create a new kubernetes secret each time the secret is updated. These secrets are just plain vanilla kubernetes secrets, but when the above ticket lands, any secrets not being referenced will be removed from the cluster to clean up the clutter.

**Comment by lswith** [comment]
Quoting the Kustomize Documentation:

> Changing the data held by a live configMap in a cluster is considered bad practice. Deployments have no means to know that the configMaps they refer to have changed, so such updates have no effect.
> The recommended way to change a deployment's configuration is to
> 1. create a new configMap with a new name,
> 2. patch the deployment, modifying the name value of the appropriate configMapKeyRef field.

> This latter change initiates rolling update to the pods in the deployment. The older configMap, when no longer referenced by any other resource, is eventually garbage collected.

**Comment by brancz** [comment]
Yes I remember this, and I think it's a good idea to allow customizing this. I've had it in mind for a while but never ended up implementing it. My suggestion would be to add a new field in the AlertmanagerSpec that holds a SecretKeySelector, that points at the wanted Alertmanager config. If empty it defaults to the current behavior, and if not we just take whatever the user provides, just like your suggestion.

@lswith would you like to create a PR for this?

**Comment by lswith** [comment]
Let me get caught up with the codebase and I should be able to get something out.

**Comment by AngusDavis** [comment]
With #2827 merged, we have alertmanager configs being created by kustomize with the following config (note that we're using kustomize bundled with kubectl 1.14; newer versions may differ slightly):

1. In kustomization.yaml:
```yaml
resources:
  - alertmanager.yaml
configurations:
  - kustomizeconfig/alertmanager.yaml
secretGenerator:
  - name: alertmanager-config
    files:
      - alertmanager.yaml=alertmanager-config.yaml
``` 
2. In kustomizeconfig/alertmanager.yaml:
```yaml
# This file is a minimal transformer config for kustomize to be able to
# transform the alertmanager.spec.configSecret elemenet:

nameReference:
  - kind: Secret
    fieldSpecs:
      - path: spec/configSecret
        kind: Alertmanager
```

3. In alertmanager.yaml (our Alertmanager resource for prom-operator):
```yaml
 
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
spec:
  replicas: 1
  configSecret: alertmanager-config
```
4. in alertmanager-config.yaml (demo configuration from the user guide):
```yaml
# Demo config that uses a non-existant web-hook.
# This file is intended to be changed to hook into other alerting systems
# but *something* is required to start the alertmanager server.
global:
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'webhook'
receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://alertmanager:30500/'
```

**Comment by brancz** [comment]
@AngusDavis do you want to contribute this to the kustomize setup in [kube-prometheus](https://github.com/coreos/kube-prometheus)?

**Comment by mr-karan** [comment]
@AngusDavis Thanks a lot for documenting this! I've been looking several ways to do this since few hours now :smile:

**Comment by nlamirault** [comment]
@lswith @brancz I've got a similar problem for Prometheus.
It works fine with @AngusDavis  kustomizeconfig setup for additonal scraping and thanos storage : 
with this file : 

```yaml
nameReference:
- kind: Secret
  fieldSpecs:
  - path: spec/thanos/objectStorageConfig/name
    kind: Prometheus
  - path: spec/additionalScrapeConfigs/name
    kind: Prometheus
  - path: spec/secrets
    kind: Prometheus
  - path: spec/volumes/secret/secretName
    kind: Prometheus
  - path: spec/volumesMounts/mountPath
    kind: Prometheus
  - path: spec/containers/env/value
    kind: Prometheus
```

But not for change secret name for GOOGLE_APPLICATION_CREDENTIALS.
Prometheus mount the service account file like that into the Prometheus pod : 

`/etc/prometheus/secrets/service-account-prometheus/-mt62kbtk4t`

```yaml
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  additionalScrapeConfigs:
    key: prometheus-compute.yaml
    name: prometheus-additional-scrape-configs-749cm7mf5h
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  containers:
  - env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/prometheus/secrets/service-account-prometheus
    name: prometheus
  logLevel: info
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 2000Mi
    requests:
      cpu: 200m
      memory: 1000Mi
  retention: 10d
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      k8s-app: prometheus
      prometheus: k8s
      role: alert-rules
  secrets:
  - service-account-prometheus-mt62kbtk4t
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  thanos:
    baseImage: quay.io/thanos/thanos
    objectStorageConfig:
      key: config.yaml
      name: thanos-storage-5c4mctth7m
    version: v0.10.1
  version: v2.15.2
  volumeMounts:
  - mountPath: /etc/prometheus/secrets/service-account-prometheus
    name: google-credentials
    readOnly: true
  volumes:
  - name: google-credentials
    secret:
      secretName: service-account-prometheus-mt62kbtk4t
```

Any idea how can i fix that ? (set GOOGLE_APPLICATION_CREDENTIALS to dynamic secret name).

**Comment by nlamirault** [comment]
Any news ?

**Comment by brancz** [comment]
We don't use kustomize, so we're not super incentivized to implement this, but we're very open to contributions from anyone who wants to contribute this! :)

**Comment by c0da** [comment]
You can disable the behavior of appending a suffix to your configmaps/secrets by using **generatorOptions**. Something like this:

```
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: alertmanager-main
    files:
      - config/alertmanager.yaml
    type: Opaque
```

I hope it helps!
