### ISSUE TITLE
ServiceMonitor picks up the wrong services

### ISSUE THREAD

**Issue by jungopro** [prometheus-operator/prometheus-operator#2075]
**What did you do?**

Created a serviceMonitor via the values.yaml in kube-prometheus chart:

```yaml
prometheus:
  serviceMonitors
    - name: "backbone-metrics"
      jobLabel: "backbone"
      selector:
        app: octopus
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: "http1"
          targetPort: "80"
          interval: 30s
          path: /octopus/api/v1/getMetrics
          scheme: http
```

**What did you expect to see?**

a single service with the label app=octopus picked up

**What did you see instead? Under which circumstances?**

4 services are picked up instead of 1
- all are in the **default** namespace
- all have and endpoint called **http1**
- 2 have port **80** for the **http1** endpoint, 2 have a different port (5601)
- _**only 1 service has the label app: octopus**_

**Environment**

* Prometheus Operator version:

	v0.20.0

* Kubernetes version information:

	1.9.0

* Kubernetes cluster kind: 

	kubespray on-premise
