### ISSUE TITLE
Cannot configure namespaces in `kubernetes_sd_config`

### ISSUE THREAD

**Issue by kminehart** [prometheus-operator/prometheus-operator#2224]
**What did you do?**

Created this Prometheus:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: prometheus
    environment: ${ENVIRONMENT}
    service: prometheus-remote
  name: prometheus-remote
  namespace: ${NAMESPACE}
spec:
  alerting:
    alertmanagers: []
  baseImage: "quay.io/prometheus/prometheus"
  externalUrl: http://prometheus-remote.monitoring:9090
  externalLabels:
    prom_environment: ${ENVIRONMENT}
  paused: false
  replicas: 1
  logLevel:  info
  resources:
    requests:
      memory: "3G"
      cpu: "250m"
    limits:
      memory: "4G"
      cpu: "500m"
  retention: "1h"
  routePrefix: "/"
  serviceAccountName: prometheus-remote
  serviceMonitorSelector:
    matchLabels:
      prometheus: remote
  serviceMonitorNamespaceSelector: {}
  remoteWrite:
  - url: ${WEAVEWORKS_URL}
    basicAuth:
      password:
        name: prometheus-weave-credentials
        key: password
  ruleSelector:
    matchLabels:
      prometheus: remote
  version: "v2.3.2"
  podMetadata:
    labels:
      app: prometheus
      environment: ${ENVIRONMENT}
      service: prometheus-remote
  affinity: {}
  additionalScrapeConfigs:
    name: prometheus-remote-configs
    key: config.yaml
  apiServerConfig:
    host: kubernetes.default:443
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serverName: kubernetes
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```
**What did you expect to see?**

`kubernetes_sd_config` should display:

```
  kubernetes_sd_configs:
  - api_server: kubernetes.default:443
    role: endpoints
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      server_name: kubernetes
      insecure_skip_verify: false
    # namespaces: <-- Should be omitted
```

According to the Prometheus docs:
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config

```
# Optional namespace discovery. If omitted, all namespaces are used.
namespaces:
  names:
    [ - <string> ]
```

**What did you see instead? Under which circumstances?**

```
  kubernetes_sd_configs:
  - api_server: kubernetes.default:443
    role: endpoints
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      server_name: kubernetes
      insecure_skip_verify: false
    namespaces:
      names:
      - monitoring
```

Where `monitoring` is the namespace that Prometheus is currently in.

**Environment**

* Prometheus Operator version:

	v0.23.2

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-27T01:14:37Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

kubeadm

---
Service discovery isn't very useful when it's limited to 1 namespace.

It's also pretty weird behavior to default to the current namespace whenever Prometheus defaults to all namespaces if omitted. It'd be nice if we used the namespaceSelector that is used elsewhere and defaulted to the current namespace that way. That would leave existing configs working with the same behavior.

I feel like this might already exist but I seriously could not find it.
