### ISSUE TITLE
Prometheus breaks: relabel configuration for replace action requires 'target_label' value

### ISSUE THREAD

**Issue by swaroopkundeti** [prometheus-operator/prometheus-operator#2503]
**What did you do?**
Deployed SNMP with prometheus operator by using additionalscrapeconfigs

**What did you expect to see?**
Prometheus in running state and see snmp targets under targets section.

**What did you see instead? Under which circumstances?**

```
$ ns get pods prometheus-k8s-0
NAME               READY   STATUS             RESTARTS   AGE
prometheus-k8s-0   2/3     CrashLoopBackOff   10         29m
```

**Environment**
development 

* Prometheus Operator version: 

	v0.25.0

* Kubernetes version information:

	v1.9.2+coreos.0

* Kubernetes cluster kind: 

	Kubespray 

* Manifests:

prometheus-prometheus.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  externalLabels:
    cluster: test-10
  nodeSelector:
    prometheus-node: "1"
  replicas: 1
  resources:
    requests:
      memory: 2Gi
  retention: 60d
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 10Gi
        selector:
          matchLabels:
            lvm-volume: database-prometheus
  version: v2.5.0
  additionalScrapeConfigs:
    name: snmp-endpoints
    key: endpoints.yaml
```

endpoints.yaml
```
- job_name: "snmp-exporter"
  scrape_timeout: 300s
  scrape_interval: 300s
  static_configs:
    - targets: [ 'cisco1.test8.com', 'cisco2.test8.com', 'cisco3.test8.com', 'cisco4.test8.com']
  metrics_path: /snmp
  params:
    module: [zec]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: snmp-exporter.monitoring.svc.cluster.local:9116
```

* Prometheus Operator Logs:

```
caller=main.go:625 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: relabel configuration for replace action requires 'target_label' value"
```

**Comment by metalmatze** [comment]
```
relabel configuration for replace action requires 'target_label' value"
```
Seems like your `endpoints.yaml` is incorrect.

**Comment by swaroopkundeti** [comment]
The same config was working earlier -- I started to notice this problem after my team upgraded prometheus operator. Could you point out what is wrong with endpoints.yaml?

**Comment by sesto** [comment]
It looks like I have the same issue Prometheus Operator v.0.29.0.
Here is a relevant piece of the `servicemonitor` configuration:
```
spec:
  endpoints:
  - interval: 60s
    metricRelabelings:
    - regex: ^(.*?):(.*?):(.*)
      replacement: ${1}_${2}_${3}
      source_labels:
      - __name__
      target_label: __name__
```
To me the configuration looks perfectly fine, however, the prometheus pod ends up in the `CrashLoopBackOff`
```
$ kubectl get pods
NAME                                                       READY     STATUS             RESTARTS   AGE
prometheus-prometheus-operator-prometheus-0                3/4       CrashLoopBackOff   23         1h
```
This is what I am getting in Prometheus logs:
```
level=error ts=2019-03-27T08:47:25.807206375Z caller=main.go:688 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: relabel configuration for replace action requires 'target_label' value"
```

**Comment by brancz** [comment]
The filelds are called `sourceLabels` and `targetLabel` to conform to kubernetes best practices.

**Comment by spikepanx** [comment]
@brancz is total right! To point this out, we had snake_case fields with underscore values. changing the snake_case fields to camelCase solves the issue without altering the (underscored) values.

`target_label: __foobar__ # does not work`
`targetLabel: __foobar__ # works!`

**Comment by sbussetti** [comment]
I ran into this issue as well, even though the documentation suggests that you use snake_case style.

**Comment by brancz** [comment]
Where does the documentation suggest this?

**Comment by sbussetti** [comment]
Okay honestly, this is user error.  On the endpoints config docs (https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint) it directs you to https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config and since the table is wider than the columns on github, the link to view the (correct) docs on the RelabelConfig spec are cut off, making them easy to miss.

**Comment by brancz** [comment]
Makes sense. Do you think it would help, if we put a phrase before linking to the upstream relabeling configuration that in order to comply to kubernetes API convention it is converted to camel case instead?

**Comment by sbussetti** [comment]
Sure, or if the hyperlink was linebroken to allow for a full view of the
table at that point, that’d work too.

~
Steve
c: 917.930.0612

On June 21, 2019 at 9:40:28 AM, Frederic Branczyk (notifications@github.com)
wrote:

Makes sense. Do you think it would help, if we put a phrase before linking
to the upstream relabeling configuration that in order to comply to
kubernetes API convention it is converted to camel case instead?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/coreos/prometheus-operator/issues/2503?email_source=notifications&email_token=AAG67ULYM5Y654ILAQIP3FLP3TK4ZA5CNFSM4HAPAT3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYIPX7A#issuecomment-504429564>,
or mute the thread

**Comment by velann21** [comment]
> The filelds are called `sourceLabels` and `targetLabel` to conform to kubernetes best practices.

Can you guys please add this in a doc, Because in prometheus docs it is source_labels, target_label

**Comment by brancz** [comment]
The API docs already say this. Where would you have expected this to be documented?

**Comment by sbussetti** [comment]
It's not that the documentation is missing, it's that your preformatted text blocks are overwide and cut off the super important note about parameter naming.  If you're on an OS/Browser with visual scrollbars disabled, it's very easy to miss that you need to scroll right in the examples, even when the rest of the page is at max width.

**Comment by brancz** [comment]
Agreed it's easy to miss in that scenario, do you have a suggestion how we could do better?

**Comment by Cho1409** [comment]
Hey @brancz what Operator version would you recommend to skip this issue? I'm trying from 0.38.1 up to v0.40.0 and I'm still getting that crash.

**Comment by simonpasquier** [comment]
Looking at this issue again I think that the operator should run more validation on relabelConfigs and metricRelabelConfigs. The following snippet will generate a bad configuration for Prometheus because a replace action needs to specify a target label:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
spec:
  endpoints:
  - port: web
    relabelings:
    - sourceLabels: [__address__]
  selector:
    matchLabels:
      app: example-app
```

Prometheus logs

```
level=error ts=2021-09-23T13:10:24.946Z caller=main.go:756 msg="Error reloading config" err="couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: relabel configuration for replace action requires 'target_label' value"
```
