### ISSUE TITLE
Unable the get the metrics of spring boot application in Prometheus Operator

### ISSUE THREAD

**Issue by spesala-infy** [prometheus-operator/prometheus-operator#2572]
*What did you do?**
We are using Prometheus Operator to monitor our k8s cluster as well as to monitor our non K8S VM nodes.Created the deployment object for the spring boot application in different name space, also created the service object for the pods deployed through deployment object in the same name space.created the ServiceMonitor object to monitor in different name space, but spring boot application metrics aren't pulling by prometheus.

**Did you expect to see some different?**
spring boot application metrics aren't pulling by prometheus

**Environment**
stage

* Prometheus Operator version: v2.5.0

* Manifests:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service_test
  name: service_test
  namespace: actuator
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  - name: mgmt
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: mgmts
    port: 8443
    protocol: TCP
    targetPort: 8081
  selector:
    app: test_app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: app1-actuator
  name: app1-actuator
  namespace: monitoring
spec:
  endpoints:
  - port: mgmt
    interval: 30s
    scheme: http
    path: /prometheus
  selector:
    matchLabels:
      app: service_test
  namespaceSelector:
    any: true
```
Can you please suggest if any issue with my service or ServiceMonitor?

**Comment by metalmatze** [comment]
The Service and ServiceMonitor looks good. 
Can you check that Prometheus has access to the `actuator` namespace. If not you should see it in the Prometheus Container logs.

**Comment by spesala-infy** [comment]
Hi Matthias ,Thanks for your quick response. Prometheus is not having access to actuator namespace. so created the role and role binding for the name space, once created able to pull the metrics from spring boot actuator app.

Can you please share the document or process to create additional dashboards for spring boot app?

**Comment by jtmkrueger** [comment]
@metalmatze and/or @spesala-infy can you point me to documentation/instruction for creating the role and role binding for a namespace? I'm not able to find where this is explained. All the examples I've found don't go into any detail about introducing additional namespaces.

**Comment by brancz** [comment]
Can you be more specific in how you've setup your Prometheus server. If you're using kube-prometheus then what you're looking for is https://github.com/coreos/kube-prometheus#adding-additional-namespaces-to-monitor

**Comment by jtmkrueger** [comment]
I'd tried that path @brancz and ended up using the helm chart instead.
What tripped me up was how the labels have to be set up on the service monitors, but I did get things going.
 I'm going to put together a PR for the documentation to try and clarify the things that tripped me up so that it's easier for others to get things up and running in the future.

**Comment by krishnakumar797** [comment]
Prometheus showing down status for SpringBoot /actuator/prometheus endpoint. Manifests as follows,

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator-das-service-monitor
  labels:
    app: prometheus-operator-das-service-monitor
    release: prometheus
spec:
  jobLabel: das-metrics
  selector:
    matchLabels:
       cmks.das/name: das-service
  endpoints:
  - interval: 15s
    path: /actuator/prometheus
    port: das-port
```
  we are getting 

http://10.1.1.131:8080/actuator/prometheus | down | endpoint="das-port"                                    instance="10.1.1.131:8080"                                    job="das-service"                                    namespace="default"                                    pod="cmks-das-deployment-64fcb69cb-8448z"                                    service="das-service" | 14.342s ago | 10s | Get http://10.1.1.131:8080/actuator/prometheus: context deadline exceeded
-- | -- | -- | -- | -- | --


But i was able to get the metrics data using the same url inside the k8s cluster from a shell demo pod. All my projects and Prometheus is running in the default namespace.
