### ISSUE TITLE
Custom CRDs API Group does not work

### ISSUE THREAD

**Issue by dbluxo** [prometheus-operator/prometheus-operator#2691]
**What happened?**

I have deployed the prometheus operator with the `--crd-apigroup=custom.monitoring.coreos.com` flag. But the operator still tries to list the default CRD API Group, e.g.: servicemonitors.**monitoring.coreos.com**

**Did you expect to see some different?**

I expect that the operator tries it only with the provided CRD API Group.

**How to reproduce it (as minimally and precisely as possible)**:
- deploy the custom named CRDs:
```
alertmanagers.custom.monitoring.coreos.com     29m
podmonitors.custom.monitoring.coreos.com       29m
prometheuses.custom.monitoring.coreos.com      29m
prometheusrules.custom.monitoring.coreos.com   29m
servicemonitors.custom.monitoring.coreos.com   29m
```
- setup the rigths (rolebindings etc.)
- deploy the prometheus operator with `--crd-apigroup=custom.monitoring.coreos.com` flag

**Environment**

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.31.1`
    

* Kubernetes version information:

    `v1.11`
    

* Kubernetes cluster kind:

    OpenShift 3.11

* Manifests:

```
    spec:
      containers:
        - name: prometheus-operator
          image: "quay.io/coreos/prometheus-operator:v0.31.1"
          imagePullPolicy: "IfNotPresent"
          args:
            - --logtostderr=true
            - --namespaces=test
            - --manage-crds=false
            - --crd-apigroup=custom.monitoring.coreos.com
            - --localhost=127.0.0.1
            - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.31.1
            - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
```
* Prometheus Operator Logs:

```
E0726 07:24:24.542693       1 reflector.go:126] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:443: Failed to list *v1.ServiceMonitor: servicemonitors.monitoring.coreos.com is forbidden: User "system:serviceaccount:test:prometheus-operator-serviceaccount" cannot list servicemonitors.monitoring.coreos.com in the namespace "test": no RBAC policy matched
E0726 07:24:24.543551       1 reflector.go:126] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:442: Failed to list *v1.Prometheus: prometheuses.monitoring.coreos.com is forbidden: User "system:serviceaccount:test:prometheus-operator-serviceaccount" cannot list prometheuses.monitoring.coreos.com in the namespace "test": no RBAC policy matched
E0726 07:24:24.544920       1 reflector.go:126] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:445: Failed to list *v1.PrometheusRule: prometheusrules.monitoring.coreos.com is forbidden: User "system:serviceaccount:test:prometheus-operator-serviceaccount" cannot list prometheusrules.monitoring.coreos.com in the namespace "test": no RBAC policy matched
E0726 07:24:24.545692       1 reflector.go:126] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:444: Failed to list *v1.PodMonitor: podmonitors.monitoring.coreos.com is forbidden: User "system:serviceaccount:test:prometheus-operator-serviceaccount" cannot list podmonitors.monitoring.coreos.com in the namespace "test": no RBAC policy matched
```

In my opinion the operator should try it only with the provided CRD API Group, right?

**Comment by RiRa12621** [comment]
This might need some improved documentation.
This only specifies the naming of the CRDs if `manage-crds` is set to true.

Here's the function for that https://github.com/coreos/prometheus-operator/blob/409ec7dc5dd6b88d33e67ba5d19ff1d6169e56b0/pkg/prometheus/operator.go#L1572

and that is only happening if `manage-crds` is set, as can be seen here https://github.com/coreos/prometheus-operator/blob/409ec7dc5dd6b88d33e67ba5d19ff1d6169e56b0/pkg/prometheus/operator.go#L426

**Comment by dbluxo** [comment]
But the new "re-named" CRDs have to be used in the further workflow? I didn't get it.

**Comment by dbluxo** [comment]
Ah okay, provided CRD API group name will be only used if 'manage-crds' is enabled.
Is there any chance that you could integrate this in the future? The specified API group name is therefore used when 'manage-crds' is disabled.

**Comment by RiRa12621** [comment]
That i cannot tell you, but I'd suggest closing this issue, as it's expected behavior currently.
You could then open a new issue of type feature request to facilitate any conversation around that.

/cc @brancz

**Comment by dbluxo** [comment]
But even if I enable `manage-crds` I'm getting this error:

- Manifest:
```
    spec:
      containers:
        - name: prometheus-operator
          image: "quay.io/coreos/prometheus-operator:v0.31.1"
          imagePullPolicy: "IfNotPresent"
          args:
            - --logtostderr=true
            - --manage-crds=true
            - --crd-apigroup=custom.monitoring.coreos.com
            - --localhost=127.0.0.1
            - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.31.1
            - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
```

- Prometheus Operator Logs:
```
ts=2019-07-26T12:57:15.41926104Z caller=main.go:181 msg="Starting Prometheus Operator version '0.31.1'."
ts=2019-07-26T12:57:15.51881708Z caller=main.go:97 msg="Staring insecure server on :8080"
level=info ts=2019-07-26T12:57:15.625250992Z caller=operator.go:213 component=alertmanageroperator msg="connection established" cluster-version=v1.11.0+d4cacc0
level=info ts=2019-07-26T12:57:15.814409916Z caller=operator.go:419 component=prometheusoperator msg="connection established" cluster-version=v1.11.0+d4cacc0
level=info ts=2019-07-26T12:57:16.118412522Z caller=operator.go:635 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2019-07-26T12:57:16.518595661Z caller=operator.go:1593 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2019-07-26T12:57:16.533712958Z caller=operator.go:1593 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2019-07-26T12:57:16.623015215Z caller=operator.go:1593 component=prometheusoperator msg="CRD updated" crd=PodMonitor
level=info ts=2019-07-26T12:57:16.638132696Z caller=operator.go:1593 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
ts=2019-07-26T12:57:19.120775942Z caller=main.go:292 msg="Unhandled error received. Exiting..." err="waiting for Alertmanager crd failed: timed out waiting for Custom Resource: failed to list CRD: alertmanagers.monitoring.coreos.com is forbidden: User \"system:serviceaccount:test:prometheus-operator-serviceaccount\" cannot list alertmanagers.monitoring.coreos.com at the cluster scope: no RBAC policy matched"
```

Why is the operator trying to list alertmanagers.monitoring.coreos.com and not alertmanagers.custom.monitoring.coreos.com?
