### ISSUE TITLE
Need help to convert prometheus conf to prometheus-operator

### ISSUE THREAD

**Issue by Nasthiem** [prometheus-operator/prometheus-operator#2694]
**What did you do?**

I need to access to metrics/cadvisor behind a proxy.

I have this prometheus configuration:
```
    global:
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
    scrape_configs: 
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090
    - job_name: kubernetes-nodes-cadvisor
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - replacement: metrics-proxy.kube-system.svc:8443
        target_label: __address__
      - regex: (.+)
        replacement: /$1/proxy/metrics/cadvisor
        source_labels:
        - __meta_kubernetes_node_name
        target_label: __metrics_path__
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: false
      scrape_interval: 10s
```

Can you help me to convert this prometheus configuration to prometheus-operator ?

**Did you expect to see some different?**

for the moment , i have this

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-jmx
  labels:
    k8s-apps: k8s-jmx
    prometheus: kube-prometheus
    component: jmx
    app: jmx
spec:
  jobLabel: kube-prometheus-k8s-jmx
  selector:
    matchLabels:
      k8s-app: exporter-jmx
  namespaceSelector:
      matchNames:
      - testns
      - kube-system
  endpoints:
  - port: https-metrics
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    scrapetimeout: 3s
    tlsConfig:
    - insecureSkipVerify: true
    metricRelabelings:
    - regex: __meta_kubernetes_node_label_(.+)
      action: labelmap
    - replacement: metrics-proxy.kube-system.svc:8443
      targetLabel: __address__
    - regex: (.+)
      replacement: /$1/proxy/metrics/cadvisor
      separator: ','
      sourceLabels:
      - __meta_kubernetes_node_name
      targetLabel: __metrics_path__
  - port: http-promjmx
    interval: 30s
    scrapetimeout: 3s
    metricRelabelings:
    - regex: (.*)-(cl[0-9]{2})-(.*)
      replacement: $0
      separator: ','
      sourceLabels:
      - pod
      targetLabel: instance
```

**Environment**

* Prometheus Operator version:

    `prometheus-operator-0.0.29`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
`
    

* Kubernetes cluster kind:

   Network policies are enabled.
