### ISSUE TITLE
Notify about unknown CRD fields on operator start

### ISSUE THREAD

**Issue by mightyguava** [prometheus-operator/prometheus-operator#2771]
**What happened?**

I added a set of `podTargetLabels: [cluster, component, keyspace, shard]` to a `ServiceMonitor`. They didn't show up in the `relabel_configs` in the prometheus config.

I checked the prometheus config page, and looked at the gzipped secret in k8s.

**Did you expect to see some different?**

I expected to see something like the below to appear in the generated prometheus config.

```
  - source_labels:
    - __meta_kubernetes_pod_label_cluster
    regex: (.*)
    target_label: cluster
    replacement: ${1}
  - source_labels:
    - __meta_kubernetes_pod_label_component
    regex: (.*)
    target_label: component
    replacement: ${1}
...
```

**How to reproduce it (as minimally and precisely as possible)**:

<details><summary>ServiceMonitor</summary>

```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: platform
  name: vitess
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: vitess
  endpoints:
    - port: web
      podTargetLabels: [cluster, component, keyspace, shard]
      relabelings:
        # The Vitess cluster references the name of the service
        - sourceLabels: [cluster]
          replacement: $1
          targetLabel: service
        # Component is vtctld, vtgate, vttablet, etc
        - sourceLabels: [component]
          targetLabel: job
        - sourceLabels: [__name__]
          replacement: vitess
          targetLabel: component
```

</details>

<details><summary>Generated config</summary>

```
- job_name: monitoring/vitess/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app
    regex: vitess
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: web
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Node;(.*)
    replacement: ${1}
    target_label: node
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Pod;(.*)
    replacement: ${1}
    target_label: pod
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - target_label: endpoint
    replacement: web
  - source_labels:
    - cluster
    target_label: service
    replacement: $1
  - source_labels:
    - component
    target_label: job
  - source_labels:
    - __name__
    target_label: component
    replacement: vitess
```

</details>

**Environment**

* Prometheus Operator version:

`quay.io/coreos/prometheus-operator:v0.33.0`

* Kubernetes version information:

```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-825e5d", GitCommit:"825e5de08cb05714f9b224cd6c47d9514df1d1a7", GitTreeState:"clean", BuildDate:"2019-08-18T03:58:32Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    AWS EKS 1.12

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

All looks good here

```
level=info ts=2019-09-19T15:43:48.802670503Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-09-19T15:44:09.674574604Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-09-19T15:44:09.889420285Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-09-19T15:46:12.138091821Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-09-19T15:46:12.307503303Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
```

**Anything else we need to know?**:
