### ISSUE TITLE
How can i use one exporter to monitor multiple external instances

### ISSUE THREAD

**Issue by jinyanroot** [prometheus-operator/prometheus-operator#2781]
**I want use one exporter to monitor multiple external instances of one application.**

For example:
An application named TEST is deployed outside of K8S and has three instances.
I write a TEST exportor,and want deploy it inside the K8S. 

****I'm do it like this as blow,but I think this method is too stupid.****
****Is there a better way?****

TEST-exporter-deployment.yaml
```
...
kind: Deployment
metadata:
  labels:
    app: test-exporter1
  name: test-exporter1
  namespace: monitoring
spec:
  ...
    spec:
      containers:
      - name: test-exporter1
...
---
...
kind: Deployment
metadata:
  labels:
    app: test-exporter2
  name: test-exporter2
  namespace: monitoring
spec:
  ...
    spec:
      containers:
      - name: test-exporter2
...
---
...
kind: Deployment
metadata:
  labels:
    app: test-exporter3
  name: test-exporter3
  namespace: monitoring
spec:
  ...
    spec:
      containers:
      - name: test-exporter3
...
```

TEST-exporter-service.yaml
```
kind: Service
metadata:
  labels:
    k8s-app: redis-exporter1
  name: redis-exporter1
  namespace: monitoring
spec:
  ...
  selector:
    app: redis-exporter1
...
---
kind: Service
metadata:
  labels:
    k8s-app: redis-exporter2
  name: redis-exporter2
  namespace: monitoring
spec:
  ...
  selector:
    app: redis-exporter2
...
---
kind: Service
metadata:
  labels:
    k8s-app: redis-exporter3
  name: redis-exporter3
  namespace: monitoring
spec:
  ...
  selector:
    app: redis-exporter3
...
```

TEST-exporter-serviceMonitor.yaml
```
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: redis-exporter1
  name: redis-exporter1
  namespace: monitoring
spec:
  ...
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: redis-exporter1
---
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: redis-exporter2
  name: redis-exporter2
  namespace: monitoring
spec:
  ...
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: redis-exporter2
---
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: redis-exporter3
  name: redis-exporter3
  namespace: monitoring
spec:
  ...
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: redis-exporter3
```
