### ISSUE TITLE
Providing multiple urls in blackbox exporter serviceMonitor

### ISSUE THREAD

**Issue by harshavardhanc** [prometheus-operator/prometheus-operator#2821]
I'm trying to deploy blackbox exporter to monitor some endpoints with serviceMonitor. I'm using existing helm chart to deploy blackbox exporter stable/prometheus-blackbox-exporter.
I have enabled serviceMonitor in values.yaml and provided module and url.

It is working fine with one url, but I want monitor multiple endpoint. Is it possible provide multiple endpoints in the url section in serviceMonitor?

This is my custom values.yaml file.

```
restartPolicy: Always

podDisruptionBudget:
  maxUnavailable: 0

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate

image:
  repository: prom/blackbox-exporter
  tag: v0.15.1
  pullPolicy: IfNotPresent

  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistrKeySecretName

## User to run blackbox-exporter container as
runAsUser: 1000
readOnlyRootFilesystem: true
runAsNonRoot: true

nodeSelector: {}
tolerations: []
affinity: {}

secretConfig: false
config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2"]
        no_follow_redirects: false
        preferred_ip_protocol: "ip4"

resources: {}
  # limits:
  #   memory: 300Mi
  # requests:
  #   memory: 50Mi

priorityClassName: ""

service:
  annotations: {}
  type: ClusterIP
  port: 9115

## An Ingress resource can provide name-based virtual hosting and TLS
## termination among other things for CouchDB deployments which are accessed
## from outside the Kubernetes cluster.
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  hosts: []
     # - chart-example.local
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls: []
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

podAnnotations: {}

extraArgs: []
#  --history.limit=1000

replicas: 1
## Monitors ConfigMap changes and POSTs to a URL
## Ref: https://github.com/jimmidyson/configmap-reload
##
configmapReload:
  ## configmap-reload container name
  ##
  name: configmap-reload

  ## User to run configmap-reload container as
  ##
  runAsUser: 65534
  runAsNonRoot: true

  ## configmap-reload container image
  ##
  image:
    repository: jimmidyson/configmap-reload
    tag: v0.2.2
    pullPolicy: IfNotPresent

  ## configmap-reload resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}

serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  ## https://github.com/coreos/prometheus-operator
  ##
  enabled: true
  labels: { release: monitoring }
  interval: 30s
  scrapeTimeout: 30s
  module: http_2xx
  # The URL that blackbox will scrape
  **url: http://10.0.0.11:9090/health**
  # Optional human readable URL that will appear in Prometheus / AlertManager
  urlHumanReadable:  # www.changemeoriwillfail.com

```

Is it possible provide multiple endpoints in the url section in serviceMonitor or Is there any other way that I can achieve it.

**Comment by brancz** [comment]
We want to introduce a first class experience with Blackbox probing, it’s tracked here: #2680.

**Comment by harshavardhanc** [comment]
@brancz Any idea how I can add multiple url's using serviceMonitor for now.

**Comment by brancz** [comment]
Best is to use the additionalScrapeConfigs feature and just write plain Prometheus config yourself for it.

**Comment by harshavardhanc** [comment]
@brancz Thanks for the suggestion, we already tried with additionalScrapeConfigsExternal feature it is working fine. But we just wanted to go with serviceMonitor.

**Comment by brancz** [comment]
For now I don't have a better suggestion, sorry.

**Comment by samsja** [comment]
I have the same issue, I figure out that I can create other serviceMonitor with the same structure than the one create by the helm deployments of the black-box exporter by only changing the url.

```shell

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 1
  labels:
    app.kubernetes.io/instance: prometheus-blackbox-exporter
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: prometheus-blackbox-exporter
    chart: prometheus-operator-6.18.0
    release: prometheus-operator
  name: prometheus-blackbox-exporter-other
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    metricRelabelings:
    - sourceLabels:
      - __address__
      targetLabel: __param_target
    - sourceLabels:
      - __param_target
      targetLabel: instance
    - replacement: https://your_url
      targetLabel: target
    params:
      module:
      - http_2xx
      target:
      - https://your_url
    path: /probe
    port: http
    scheme: http
    scrapeTimeout: 30s
  jobLabel: prometheus-blackbox-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-blackbox-exporter
      app.kubernetes.io/name: prometheus-blackbox-exporter
```

It work and I can have multiple url that are scrape.

**Comment by harshavardhanc** [comment]
@samsja Thanks, this will help us.

**Comment by zmailloux** [comment]
> I have the same issue, I figure out that I can create other serviceMonitor with the same structure than the one create by the helm deployments of the black-box exporter by only changing the url.
> 
> ```shell
> apiVersion: monitoring.coreos.com/v1
> kind: ServiceMonitor
> metadata:
>   generation: 1
>   labels:
>     app.kubernetes.io/instance: prometheus-blackbox-exporter
>     app.kubernetes.io/managed-by: Tiller
>     app.kubernetes.io/name: prometheus-blackbox-exporter
>     chart: prometheus-operator-6.18.0
>     release: prometheus-operator
>   name: prometheus-blackbox-exporter-other
>   namespace: monitoring
> spec:
>   endpoints:
>   - interval: 30s
>     metricRelabelings:
>     - sourceLabels:
>       - __address__
>       targetLabel: __param_target
>     - sourceLabels:
>       - __param_target
>       targetLabel: instance
>     - replacement: https://your_url
>       targetLabel: target
>     params:
>       module:
>       - http_2xx
>       target:
>       - https://your_url
>     path: /probe
>     port: http
>     scheme: http
>     scrapeTimeout: 30s
>   jobLabel: prometheus-blackbox-exporter
>   namespaceSelector:
>     matchNames:
>     - monitoring
>   selector:
>     matchLabels:
>       app.kubernetes.io/instance: prometheus-blackbox-exporter
>       app.kubernetes.io/name: prometheus-blackbox-exporter
> ```
> 
> It work and I can have multiple url that are scrape.

@samsja When you say you were able to get multiple URLs to scrape, do you mean only by creating additional servicemonitor rules? I'm trying to create servicemonitor rules with multiple endpoints and haven't been able to do so.

**Comment by samsja** [comment]
Yep exactly, the only way I found is to create one Service Monitor (based on the template of the helm chart) for each url I want to monitor. It worked even though it is not ideal. Let me now if you found a solution to have multiple endpoints in one service monitor.

**Comment by gecube** [comment]
the same

**Comment by raghu-de** [comment]
Any further leads to knowing if this has been resolved when using values.yaml for BlackBox exporter?

**Comment by brancz** [comment]
I have no idea about the helm chart (we don't use nor maintain it), but blackbox probes are now a first class feature in prometheus operator. See the [`Probe`](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#probe) API spec. Under static targets you can add as many urls as you want or have them be discovered via `Ingress` objects.

If you have any further questions, feel free to comment, but given the initial question, I feel this has been resolved with the first class Probe resource. Closing.

**Comment by Zeka13** [comment]
@brancz thx for this new feature, but it's hard to find a working example for blackbox ssl and this Probe from API

**Comment by paulfantom** [comment]
@Zeka13 examples of Probe usage:
- staticConfig - https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/manifests/prober/promDemoProbe.yaml
- ingress - https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/manifests/prober/ingressProbe.yaml

**Comment by Zeka13** [comment]
@paulfantom thx that's helped a lot

**Comment by rjshrjndrn** [comment]
If anybody is still looking for a solution, with old prom-operator version
- I've two endpoints,listening on port 4000
- I'm using black box exporter to monitor both
- Idea is to have an endpoint(because this is external apps, you can use service name if it's running in kube), and use that with the service monitor
```
---
kind: Service
apiVersion: v1
metadata:
  name: headerecho
  namespace: default
  labels:
    app: headerecho
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 4000
    name: metrics
---
kind: Endpoints
apiVersion: v1
metadata:
  name: headerecho
  namespace: default
subsets:
- addresses:
  - ip: 10.42.0.96
  - ip: 10.42.0.97
  ports:
  - name: metrics
    port: 4000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample
  namespace: default
  labels:
    app: headerecho
    release: prometheus
spec:
  endpoints:
  - 
    interval: 15s
    path: "/probe"
    port: metrics
    scheme: http
    scrapeTimeout: 10s
    relabelings:
      - sourceLabels: [__address__]
        targetLabel: __param_target
      - sourceLabels: [__param_target]
        targetLabel: instance
      - targetLabel: __address__
        replacement: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
    params:
      module:
        - tcp_connect
      target:
        - blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  jobLabel: headerecho-scrape
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
        app: headerecho
```
