### ISSUE TITLE
creating config failed: loading additional scrape configs from Secret failed

### ISSUE THREAD

**Issue by archmangler** [prometheus-operator/prometheus-operator#2858]
**What did you do?**

- I've created an additional scrape config from a secret in order to scrape kubelet_ metrics e.g "kubelet_volume_stats_inodes". 
- However I don't see the metrics appearing, and in the operator logs I see the messages that it cannot find the secret. even though the secret is clearly there in the namespace:

```
E1115 13:39:17.341385       1 operator.go:956] Sync "monitoring/k8s" failed: creating config failed: loading additional scrape configs from Secret failed: secret additional-scrape-configs could not be found
```

- secret in namespace:

```
[prometheus]$ kubectl get secrets -n monitoring
NAME                              TYPE                                  DATA   AGE
additional-scrape-configs         Opaque                                1      15m
default-token-v57zx               kubernetes.io/service-account-token   3      3d20h
kube-state-metrics-token-5fsh7    kubernetes.io/service-account-token   3      3d12h
node-exporter-token-wxnkm         kubernetes.io/service-account-token   3      3d12h
prometheus-adapter-token-qmlbr    kubernetes.io/service-account-token   3      3d12h
prometheus-k8s                    Opaque                                1      3d12h
prometheus-k8s-token-hn67d        kubernetes.io/service-account-token   3      3d12h
prometheus-operator-token-8ncq6   kubernetes.io/service-account-token   3      3d12h
pushgateway-token-bfrn6           kubernetes.io/service-account-token   3      3d5h

.
.
.
[prometheus]$ kubectl get pods -n monitoring
NAME                                   READY   STATUS    RESTARTS   AGE
kube-state-metrics-549767c89b-g929c    3/3     Running   0          5h59m
node-exporter-4pp5k                    2/2     Running   0          5h58m
node-exporter-clsm6                    2/2     Running   0          5h59m
prometheus-adapter-84666954d9-85pgn    1/1     Running   0          6h1m
prometheus-k8s-0                       3/3     Running   1          24m
prometheus-k8s-1                       3/3     Running   1          77m
prometheus-operator-6cf78d69bb-gf7mb   1/1     Running   0          35m
pushgateway-f74b4cd59-z2lr2            1/1     Running   0          5h58m
```

- My scrape config:

```
---
- job_name: 'monitoring/service-endpoints'
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
      action: replace
      target_label: __scheme__
      regex: (https?)

# Scrape config for node (i.e. kubelet) /metrics (e.g. 'kubelet_'). Explore
# metrics from a node by scraping kubelet (127.0.0.1:10250/metrics).
- job_name: 'kubelet'
  scheme: http
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/$1/proxy/metrics
```

- My secret as output from the namespace:

```
apiVersion: v1
data:
  additionalScrapeConfigs.yaml: LS0tCi0gam9iX25hbWU6ICdtb25pdG9yaW5nL3NlcnZpY2UtZW5kcG9pbnRzJwogIHNjaGVtZTogaHR0cAogIGt1YmVybmV0ZXNfc2RfY29uZmlnczoKICAtIHJvbGU6IGVuZHBvaW50cwogIHJlbGFiZWxfY29uZmlnczoKICAgIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX3NlcnZpY2VfYW5ub3RhdGlvbl9wcm9tZXRoZXVzX2lvX3NjcmFwZV0KICAgICAgYWN0aW9uOiBrZWVwCiAgICAgIHJlZ2V4OiB0cnVlCiAgICAtIHNvdXJjZV9sYWJlbHM6IFtfX21ldGFfa3ViZXJuZXRlc19zZXJ2aWNlX2Fubm90YXRpb25fcHJvbWV0aGV1c19pb19wYXRoXQogICAgICBhY3Rpb246IHJlcGxhY2UKICAgICAgdGFyZ2V0X2xhYmVsOiBfX21ldHJpY3NfcGF0aF9fCiAgICAgIHJlZ2V4OiAoLispCiAgICAtIHNvdXJjZV9sYWJlbHM6IFtfX2FkZHJlc3NfXywgX19tZXRhX2t1YmVybmV0ZXNfc2VydmljZV9hbm5vdGF0aW9uX3Byb21ldGhldXNfaW9fcG9ydF0KICAgICAgYWN0aW9uOiByZXBsYWNlCiAgICAgIHJlZ2V4OiAoW146XSspKD86OlxkKyk/OyhcZCspCiAgICAgIHJlcGxhY2VtZW50OiAkMTokMgogICAgICB0YXJnZXRfbGFiZWw6IF9fYWRkcmVzc19fCiAgICAtIHNvdXJjZV9sYWJlbHM6IFtfX21ldGFfa3ViZXJuZXRlc19zZXJ2aWNlX2Fubm90YXRpb25fcHJvbWV0aGV1c19pb19zY2hlbWVdCiAgICAgIGFjdGlvbjogcmVwbGFjZQogICAgICB0YXJnZXRfbGFiZWw6IF9fc2NoZW1lX18KICAgICAgcmVnZXg6IChodHRwcz8pCgojIFNjcmFwZSBjb25maWcgZm9yIG5vZGUgKGkuZS4ga3ViZWxldCkgL21ldHJpY3MgKGUuZy4gJ2t1YmVsZXRfJykuIEV4cGxvcmUKIyBtZXRyaWNzIGZyb20gYSBub2RlIGJ5IHNjcmFwaW5nIGt1YmVsZXQgKDEyNy4wLjAuMToxMDI1MC9tZXRyaWNzKS4KLSBqb2JfbmFtZTogJ2t1YmVsZXQnCiAgc2NoZW1lOiBodHRwCiAga3ViZXJuZXRlc19zZF9jb25maWdzOgogIC0gcm9sZTogbm9kZQogIHJlbGFiZWxfY29uZmlnczoKICAgIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX25vZGVfbmFtZV0KICAgICAgcmVnZXg6ICguKykKICAgICAgdGFyZ2V0X2xhYmVsOiBfX21ldHJpY3NfcGF0aF9fCiAgICAgIHJlcGxhY2VtZW50OiAvYXBpL3YxL25vZGVzLyQxL3Byb3h5L21ldHJpY3MK
kind: Secret
metadata:
  creationTimestamp: "2019-11-15T13:39:17Z"
  name: additional-scrape-configs
  namespace: monitoring
  resourceVersion: "3677712"
  selfLink: /api/v1/namespaces/monitoring/secrets/additional-scrape-configs
  uid: 52205d0a-07ad-11ea-a552-0693108b726d
type: Opaque



```

- My monitoring namespace pods including prometheus:

```
[345401@asgprholpans001 prometheus]$ kubectl get pods -n monitoring
NAME                                   READY   STATUS    RESTARTS   AGE
kube-state-metrics-549767c89b-g929c    3/3     Running   0          5h57m
node-exporter-4pp5k                    2/2     Running   0          5h56m
node-exporter-clsm6                    2/2     Running   0          5h56m
prometheus-adapter-84666954d9-85pgn    1/1     Running   0          5h58m
prometheus-k8s-0                       3/3     Running   1          21m
prometheus-k8s-1                       3/3     Running   1          75m
prometheus-operator-6cf78d69bb-gf7mb   1/1     Running   0          32m
pushgateway-f74b4cd59-z2lr2            1/1     Running   0          5h55m
test                                   1/1     Running   0          3d20h


```

**Did you expect to see some different?**

- I expect to see the kubelet_* metrics available, and not messages in the operator logs about the missing secret config.

**Environment**

* Prometheus Operator version:

```
Name:                   prometheus-operator
Namespace:              monitoring
CreationTimestamp:      Tue, 12 Nov 2019 09:27:25 +0800
Labels:                 app.kubernetes.io/component=controller
                        app.kubernetes.io/name=prometheus-operator
                        app.kubernetes.io/version=v0.33.0
Annotations:            deployment.kubernetes.io/revision: 2
Selector:               app.kubernetes.io/component=controller,app.kubernetes.io/name=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/component=controller
                    app.kubernetes.io/name=prometheus-operator
                    app.kubernetes.io/version=v0.33.0
  Service Account:  prometheus-operator
  Containers:
   prometheus-operator:
    Image:      docker-release.PRIVATE:8443/coreos/prometheus-operator:v0.33.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --logtostderr=true
      --config-reloader-image=docker-release.PRIVATE:8443/coreos/configmap-reload:v0.0.1
      --prometheus-config-reloader=docker-release.PRIVATE:8443/coreos/prometheus-config-reloader:v0.33.0
    Limits:
      cpu:     200m
      memory:  200Mi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-6cf78d69bb (1/1 replicas created)
Events:          <none>

```

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
ts=2019-11-15T13:19:59.213487421Z caller=main.go:187 msg="Starting Prometheus Operator version '0.33.0'."
ts=2019-11-15T13:19:59.218233018Z caller=main.go:95 msg="Staring insecure server on :8080"
level=info ts=2019-11-15T13:19:59.313788854Z caller=operator.go:425 component=prometheusoperator msg="connection established" cluster-version=v1.14.6
level=info ts=2019-11-15T13:19:59.313928254Z caller=operator.go:222 component=alertmanageroperator msg="connection established" cluster-version=v1.14.6
level=info ts=2019-11-15T13:20:00.025141274Z caller=operator.go:644 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2019-11-15T13:20:00.040517863Z caller=operator.go:1599 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2019-11-15T13:20:00.111038016Z caller=operator.go:1599 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2019-11-15T13:20:00.131970302Z caller=operator.go:1599 component=prometheusoperator msg="CRD updated" crd=PodMonitor
level=info ts=2019-11-15T13:20:00.187991764Z caller=operator.go:1599 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2019-11-15T13:20:03.111451391Z caller=operator.go:238 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2019-11-15T13:20:03.311868456Z caller=operator.go:193 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2019-11-15T13:20:12.335384366Z caller=operator.go:441 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2019-11-15T13:20:13.211250175Z caller=operator.go:371 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2019-11-15T13:20:13.211531475Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-15T13:20:13.435207024Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-15T13:30:36.614207849Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-15T13:30:41.913997924Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-15T13:30:45.005005884Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-15T13:31:00.275099091Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
W1115 13:34:45.426845       1 reflector.go:302] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:452: watch of *v1.ConfigMap ended with: too old resource version: 3675909 (3676106)
level=info ts=2019-11-15T13:39:17.314466264Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
E1115 13:39:17.341385       1 operator.go:956] Sync "monitoring/k8s" failed: creating config failed: loading additional scrape configs from Secret failed: secret additional-scrape-configs could not be found
level=info ts=2019-11-15T13:39:17.410126402Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
E1115 13:39:17.432980       1 operator.go:956] Sync "monitoring/k8s" failed: creating config failed: loading additional scrape configs from Secret failed: secret additional-scrape-configs could not be found
level=info ts=2019-11-15T13:39:17.44322448Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
E1115 13:39:17.644090       1 operator.go:956] Sync "monitoring/k8s" failed: creating config failed: loading additional scrape configs from Secret failed: secret additional-scrape-configs could not be found
level=info ts=2019-11-15T13:39:17.664343637Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-15T13:39:17.82737423Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
W1115 13:48:49.445514       1 reflector.go:302] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:452: watch of *v1.ConfigMap ended with: too old resource version: 3677283 (3677433)

```

**Anything else we need to know?**:

**Comment by brancz** [comment]
Could you share your Prometheus object as well as double check whether the generated config might contain your additional scrape configs snippet? Do the Prometheus config reloaded logs say anything?

**Comment by archmangler** [comment]
Thanks for the response @brancz 

- my Prometheus object

https://gist.github.com/archmangler/46425e0581ff47f01c118f8df8b7bc46

- Check of the secrets config (base64 decoded), this looks valid but I'm not 100% sure this is the correct scrape config for kubelet.

```
[prometheus]$ cat additional-scrape-configs.yaml | base64 -d
---
- job_name: 'monitoring/service-endpoints'
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
      action: replace
      target_label: __scheme__
      regex: (https?)

#Scrape job to get kubelet metrics?
# Scrape config for node (i.e. kubelet) /metrics (e.g. 'kubelet_'). Explore
# metrics from a node by scraping kubelet (127.0.0.1:10250/metrics).
- job_name: 'kubelet'
  scheme: http
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/$1/proxy/metrics
```

- Logs following reload (delete) of the prometheus operator pod:


```
ts=2019-11-15T13:19:59.213487421Z caller=main.go:187 msg="Starting Prometheus Operator version '0.33.0'."
ts=2019-11-15T13:19:59.218233018Z caller=main.go:95 msg="Staring insecure server on :8080"
level=info ts=2019-11-15T13:19:59.313788854Z caller=operator.go:425 component=prometheusoperator msg="connection established" cluster-version=v1.14.6
level=info ts=2019-11-15T13:19:59.313928254Z caller=operator.go:222 component=alertmanageroperator msg="connection established" cluster-version=v1.14.6
level=info ts=2019-11-15T13:20:00.025141274Z caller=operator.go:644 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2019-11-15T13:20:00.040517863Z caller=operator.go:1599 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2019-11-15T13:20:00.111038016Z caller=operator.go:1599 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2019-11-15T13:20:00.131970302Z caller=operator.go:1599 component=prometheusoperator msg="CRD updated" crd=PodMonitor
level=info ts=2019-11-15T13:20:00.187991764Z caller=operator.go:1599 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2019-11-15T13:20:03.111451391Z caller=operator.go:238 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2019-11-15T13:20:03.311868456Z caller=operator.go:193 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2019-11-15T13:20:12.335384366Z caller=operator.go:441 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2019-11-15T13:20:13.211250175Z caller=operator.go:371 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2019-11-15T13:20:13.211531475Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-15T13:20:13.435207024Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-15T13:30:36.614207849Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-15T13:30:41.913997924Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-15T13:30:45.005005884Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-15T13:31:00.275099091Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-15T13:39:17.314466264Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
E1115 13:39:17.341385       1 operator.go:956] Sync "monitoring/k8s" failed: creating config failed: loading additional scrape configs from Secret failed: secret additional-scrape-configs could not be found
level=info ts=2019-11-15T13:39:17.410126402Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
E1115 13:39:17.432980       1 operator.go:956] Sync "monitoring/k8s" failed: creating config failed: loading additional scrape configs from Secret failed: secret additional-scrape-configs could not be found
level=info ts=2019-11-15T13:39:17.44322448Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
E1115 13:39:17.644090       1 operator.go:956] Sync "monitoring/k8s" failed: creating config failed: loading additional scrape configs from Secret failed: secret additional-scrape-configs could not be found
level=info ts=2019-11-15T13:39:17.664343637Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-15T13:39:17.82737423Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
```

- Logs from the prometheus pod:

```
[prometheus]$ kubectl logs prometheus-k8s-0 prometheus -n monitoring --follow
level=info ts=2019-11-17T04:01:57.995Z caller=main.go:329 msg="Starting Prometheus" version="(version=2.11.0, branch=HEAD, revision=4ef66003d9855ed2b7a41e987b33828ec36db34d)"
level=info ts=2019-11-17T04:01:57.995Z caller=main.go:330 build_context="(go=go1.12.7, user=root@0dc27cf95f36, date=20190709-09:54:35)"
level=info ts=2019-11-17T04:01:57.996Z caller=main.go:331 host_details="(Linux 4.15.0-1059-azure #64-Ubuntu SMP Fri Sep 13 17:02:44 UTC 2019 x86_64 prometheus-k8s-0 (none))"
level=info ts=2019-11-17T04:01:57.996Z caller=main.go:332 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-11-17T04:01:57.996Z caller=main.go:333 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-11-17T04:01:57.997Z caller=main.go:652 msg="Starting TSDB ..."
level=info ts=2019-11-17T04:01:57.997Z caller=web.go:448 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-11-17T04:01:58.003Z caller=main.go:667 fs_type=EXT4_SUPER_MAGIC
level=info ts=2019-11-17T04:01:58.003Z caller=main.go:668 msg="TSDB started"
level=info ts=2019-11-17T04:01:58.003Z caller=main.go:738 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-11-17T04:01:58.007Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-11-17T04:01:58.008Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-11-17T04:01:58.009Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-11-17T04:01:58.010Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-11-17T04:01:58.011Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-11-17T04:01:58.014Z caller=kubernetes.go:192 component="discovery manager notify" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-11-17T04:01:58.038Z caller=main.go:766 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-11-17T04:01:58.038Z caller=main.go:621 msg="Server is ready to receive web requests."
level=info ts=2019-11-17T04:01:59.517Z caller=main.go:738 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-11-17T04:01:59.521Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-11-17T04:01:59.523Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-11-17T04:01:59.524Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-11-17T04:01:59.525Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-11-17T04:01:59.526Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-11-17T04:01:59.527Z caller=kubernetes.go:192 component="discovery manager notify" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-11-17T04:01:59.558Z caller=main.go:766 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml

```
