### ISSUE TITLE
Promtheus pods volumes (pvc) name created by the Operator

### ISSUE THREAD

**Issue by clausa20** [prometheus-operator/prometheus-operator#2860]
Hello,

Promtheus pods volume name (pvc) created by the operator, it forcibly adds the word "prometheus" in the pvc name,
for example, having:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: telemetry
  namespace: mynamespace
  labels:
    prometheus: telemetry
spec:
  storage:
    volumeClaimTemplate:
      metadata:
        name: myvolumes
      spec:
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
....
```
Then the prometheus pvc name is:
myvolumes-**prometheus**-telemetry-0

I need to have the total control of the pvc name due to legacy dependencies,
is there any way to have a name without that "prometheus" word in the pvc name?
I would like to have the pvc name: **myvolumes-telemetry-0**

Thanks.
