### ISSUE TITLE
Promethues operator federation 

### ISSUE THREAD

**Issue by SofiaTa** [prometheus-operator/prometheus-operator#2877]
I've installed [Prometheus operator][1] `0.34` which works as expected on cluster **A**
Now I want to use the [federation][2] ,I mean collect metrics from other Prometheus which is located on other cluster **B**
But I miss the following

1. in the docs there is the following entry
```
  static_configs:
      - targets:
        - 'source-prometheus-1:9090'
        - 'source-prometheus-2:9090'
        - 'source-prometheus-3:9090'
```

What is the actually  **source** Prometheus of cluster B? should I create a service for it 

2. where in the values.yaml of the Prometheus operator I should add the config ? 

3. security - how it actually be able to collect data from cluster B without any security config ? 

  [1]: https://github.com/helm/charts/tree/master/stable/prometheus-operator
  [2]: https://prometheus.io/docs/prometheus/latest/federation/

I didn't find any useful example :(

**Comment by brancz** [comment]
1) You can use the `additionalScrapeConfigs` feature to add arbitrary Prometheus config to your setup.
2) We neither use nor maintain the helm charts, so unfortunately we can't help with that. I would suggest you to ask on the upstream helm charts repo.
3) The Prometheus object allows specifying additional `Secret`s to be mounted into Prometheus, which you can reference in the scrape config from 1).

**Comment by maxromanovsky** [comment]
@SofiaTa here's config that works for me (with the default `scheme: http`):
```yaml
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: federate-k3s-arm
        metrics_path: /federate
        scrape_interval: 1m
        scrape_timeout: 55s
        honor_labels: true
        params:
          'match[]':
            - '{cluster="kacaur-arm"}'
        static_configs:
          - targets:
              - "prometheus-arm.example.com"
```

Keep in mind to add label used in `match[]` to all the metrics in the prometheus you'd be scraping
