### ISSUE TITLE
Prometheus Operator failing with mTLS (Istio)

### ISSUE THREAD

**Issue by Callum1201** [prometheus-operator/prometheus-operator#2907]
We're running Prometheus-operator-8.3.2 and have istio installed with mTLS enabled. I have also enabled the following in Istio:
`rewriteapphttpprobe:true`
` readinessInitialDelaySeconds:10s`

When running the prometheus-oper-admission prior to helm installing this errors with
> Back-off restarting failed container
> Readiness probe failed: HTTP probe failed with statuscode: 503

I know this is being caused by the mTLS as if I install prometheus prior I do not get this issue. Has anyone else had a similar problem and worked around it?

**Comment by brancz** [comment]
Could you be more specific in which readiness probe is failing? Also please keep in mind that the helm charts are neither used nor maintained by the prometheus-operator maintainers, so while we'll try our best to help you it might be worth opening an issue with the upstream helm charts repo as well or instead as they know and understand the setup the helm charts provision better than we do (that said a lot is similar to the [kube-prometheus](https://github.com/coreos/kube-prometheus) setup we maintain so it's not unlikely that in this case the problem is the same).

**Comment by Callum1201** [comment]
Hey,

The error is from the prometheus-oper-admission pod. If I change the admission setting to false it all releases.

**Comment by brancz** [comment]
cc @vsliouniaev you probably understand the combination of helm + admission webhook best. Could you have a look?

**Comment by adamrbennett** [comment]
I recently ran into this as well, here are some anecdotes that apply to my circumstances (may not apply to yours):

The admission webhook pod should not get an Istio sidecar injected.

Set the Istio auto injection default policy to disabled, for example:
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    global:
      proxy:
        autoInject: disabled
```

This will not disable auto injection completely -- it will simply defer to pod annotations (namespace label is still required). See here: https://istio.io/docs/ops/configuration/mesh/injection-concepts/

Add the `istio-injection=enabled` label on the namespace (this is always required for automatic sidecar injection, see link above).

Add appropriate annotations to components that need a sidecar, for example (prometheus-operator helm chart values):
```
grafana:
  podAnnotations:
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
```

**Comment by infa-ddeore** [comment]
here is what I came up with to make all prom operator pods work with istio injection enabled and `STRICT` mtls `PeerAuthentication` set in the prom operator namespace

```
prometheusOperator:
  podAnnotations:
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  admissionWebhooks:
    patch:
      podAnnotations: 
        sidecar.istio.io/inject: "false"

grafana:
  podAnnotations:
    sidecar.istio.io/rewriteAppHTTPProbers: "true"

prometheus:
  prometheusSpec:
    podMetadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"

alertmanager:
  alertmanagerSpec:
    podMetadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"

kube-state-metrics:
  podAnnotations:
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
```
