### ISSUE TITLE
Target Labels are being dropped

### ISSUE THREAD

**Issue by omnipresent07** [prometheus-operator/prometheus-operator#2908]
**What did you do?**

have a pod running in default namespace that puts metrics on port `:9001/metrics`. Have prometheus running in default namespace and would like it to start scraping these metrics. 

Have this in the values.yaml
```
    additionalScrapeConfigs:
    - job_name: 'akka-hmda-platform'
      scrape_interval: 15s
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - default
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: keep   
        regex: hmda-platform
```

**Did you expect to see some different?**

I expected the metrics to be picked up in `/targets` but they are not. Going to service-discovery shows this:

<img width="1671" alt="Screen Shot 2019-12-11 at 11 48 31 AM" src="https://user-images.githubusercontent.com/44377678/70642318-fe4f0c00-1c0c-11ea-8854-5fa21f381622.png">

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

dc/os

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
