### ISSUE TITLE
Secrets don't get properly configured on thanos-sidecar container

### ISSUE THREAD

**Issue by streetmapp** [prometheus-operator/prometheus-operator#2968]
**What happened?**

When editing the prometheus CRD defining secrets that should be mounted to the containers. Notably the secret containing the GCP credentials in a JSON file. The volume was created for the `thanos-sidecar` container, but the VolumeMount was not. This results in an error where the thanos sidecar cannot configure the client for the Object Store component.

**Did you expect to see some different?**
Like with the prometheus container, would expect the whole secret component to function for the other containers. So the Volume definition for the secret as well as the VolumeMount for where on the resulting container this should be mounted.

**How to reproduce it (as minimally and precisely as possible)**:

Define a secret in the Prometheus definition that should be mounted and have a Thanos definition as well. The resulting stateful set will have this secret properly mounted as expected only for the `prometheus` container.

**Environment**

* Prometheus Operator version:

 quay.io/coreos/prometheus-operator:v0.33.0

* Kubernetes version information:

 ```
➜ kubectl version                                                                                                                                             
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+70132b0f13", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.7-gke.2", GitCommit:"96c91b15a936b36701e8704844bc356862440a21", GitTreeState:"clean", BuildDate:"2019-12-13T12:37:28Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

GKE cluster provisioned via Terraform

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  containers:
  - name: "thanos-sidecar"
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/prometheus/secrets/thanos-creds/credentials.json
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  podMonitorSelector: {}
  replicas: 2
  secrets:
  - thanos-creds
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  thanos:
    version: v0.5.0
    objectStorageConfig:
      key: thanos.yaml
      name: thanos-objstore-config
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  retention: 10m
  externalLabels:
    cluster: mycluster
  serviceMonitorSelector: {}
  version: v2.11.0
```

This [comment](https://github.com/coreos/prometheus-operator/pull/2445#issuecomment-542665021) also mentions the issue that I'm facing. I was able to resolve this in the interim by copying the `volumeMounts` lines for the secret that show up on the prometheus container. But this is not sustainable.
