### ISSUE TITLE
[alertmanager] One alertamanager for multiple Prometheus from different K8s clusters

### ISSUE THREAD

**Issue by GabrielPeral** [prometheus-operator/prometheus-operator#2990]
HI everyone,
I'm quite new with Prometheus Operator and me and my team are trying to centralize all metrics and alerts from different k8s clusters, so I was looking at the configuration, and I only find that in Prometheus it will look for the endpoint of a given service, but what if that service is not in the same cluster, for example,lets see this scenario:

- One k8s cluster designed as centralized operation cluster, this will have grafana,prometheus and alertmanager, from this alertmanager all the alerts will be configured and routing.

- several cluster in different regions, some of the in the same region than the first cluster, some of them in another region.

the idea is that all prometheus aims to the same alertamanger, so that way we can just modify from one point ( could be on HA).

The thing is that in the configuration of the prometheus CRD, it only ask for the following:
```
    alertingEndpoints: 
    - name: ""
      namespace: "monitoring"
      port: web
      scheme: http

```
Where name is the name for the service of the alertmanager service, right? the problem is that how to define if the alertmanager is not in the same cluster.

I don't know if here is the right place to ask this, so if it is not, please tell it to me.

P.S: the alertmanager endpoint is reachable from other k8s clusters through the IP:PORT

**Comment by brancz** [comment]
You can make use of raw prometheus config for discovering alertmanagers using the “additionalAlertManagerConfigs” feature.

**Comment by mr-karan** [comment]
I tried the configuration from the official helm chart [example](https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L1707 and got the following error on applying the manifest:

```
error: error validating "STDIN": error validating data: ValidationError(Prometheus.spec.additionalAlertManagerConfigs): invalid type for com.coreos.monitoring.v1.Prometheus.spec.additionalAlertManagerConfigs: got "array", expected "map"; if you choose to ignore these errors, turn validation off with --validate=false
```

Posting the config:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
spec:
  additionalAlertManagerConfigs:
  - consul_sd_configs:
    - server: consul.dev.test:8500
      scheme: http
      datacenter: dev
      tag_separator: ','
      services:
        - metrics-prometheus-alertmanager
```

Any pointers? @brancz

**Comment by simonpasquier** [comment]
@mr-karan from the [doc](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec):

> AdditionalAlertManagerConfigs allows specifying a key of a Secret containing additional Prometheus AlertManager configurations

You need to create a secret storing `- consul_sd_configs: ...` and reference it in the Prometheus resource.

**Comment by zgfh** [comment]
demo:
1. create secert:
```yaml
cat > alert-center-external-secert.yaml<<-EOF
apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alert-center-external
  namespace: monitoring
stringData:
  alert-config: |-
    - path_prefix: /
      scheme: https
      timeout: 10s
      api_version: v1
      static_configs:
        - targets: ['alert.daocloud.io:443']
      relabel_configs:
      - action: keep
        source_labels:
        - __meta_kubernetes_service_name
        regex: alert-center
      - action: keep
        source_labels:
        - __meta_kubernetes_endpoint_port_name
        regex: api
EOF
kubectl apply -f alert-center-external-secert.yaml
```
2. change crd:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  additionalAlertManagerConfigs:
    key: alert-config
    name: alert-center-external
  ...
```
