### ISSUE TITLE
How to get the original job tag?

### ISSUE THREAD

**Issue by fengyehong** [prometheus-operator/prometheus-operator#3033]
**What did you do?**

I create the following ServiceMonitor

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: test
  name: test
  namespace: default
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: metrics
    relabelings:
    - sourceLabels:
      - job
      targetLabel: prometheus_job_name
  namespaceSelector: {}
  selector:
    matchLabels:
      app: test
```

and get the following prometheus config:

```yaml
scrape_configs:
- job_name: default/test/0
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - default
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_app]
    separator: ;
    regex: test
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: metrics
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Node;(.*)
    target_label: node
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Pod;(.*)
    target_label: pod
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: metrics
    action: replace
  - source_labels: [job]
    separator: ;
    regex: (.*)
    target_label: prometheus_job_name
    replacement: $1
    action: replace
```

I need to get the original job_name as a tag `prometheus_job_name`, which should results to `default/test/0` here, but as the config show, relabelings defined in ServiceMonitor object are appended after built-in configs, so when the last relabeling executing, `job` has already been modified to `test`, I have no where to read `default/test/0`

My question: Is there any way the get the original `job` tag `default/test/0` ? 

or how can we change the order of relabelings? So I can read it before modified.

**Environment**

* Prometheus Operator version:

![爱奇艺20200220225027](https://user-images.githubusercontent.com/12654661/74947364-b2eb8200-5435-11ea-8118-d6df32908656.png)

* Kubernetes version information:

1.15.0
