### ISSUE TITLE
Prometheus not able to scrape metrics from different namespaces

### ISSUE THREAD

**Issue by vaishali-prophecy** [prometheus-operator/prometheus-operator#3086]
I have serviceMonitorSelector and serviceMonitorNamespaceSelector configured in values.yml for prometheus like below -

```
  prometheus-operator:
     prometheusSpec:
       serviceMonitorSelector:
         matchLabels:
           name: prophecy-operator
       serviceMonitorNamespaceSelector:
         matchLabels:
           prometheus: front-end-team
```
Namespace where servicemonitor is running has been labelled as-

 ```
apiVersion: v1
 kind: Namespace
 metadata:
   creationTimestamp: "2020-03-02T12:33:53Z"
   labels:
     prometheus: front-end-team
     tag: abcd
   name: visa
   resourceVersion: "2069386"
   selfLink: /api/v1/namespaces/visa
   uid: 139112ef-5c82-11ea-9e6e-42010a8001b3
 spec:
   finalizers:
   - kubernetes
 status:
   phase: Active
```
Still, in service discovery, the service monitor running in this namespace are not listed and hence metrics are not scraped.

**Comment by lilic** [comment]
How did you configure the `--deny-namespaces ` or/and `--namespaces` args of prometheus-operator?

**Comment by vaishali-prophecy** [comment]
I had set it up as - 
```
  prometheusOperator:
    enabled: true
    kubeletService:
      enabled: false
    serviceMonitor:
      selfMonitor: false
    tlsProxy:
      enabled: false
    admissionWebhooks:
      enabled: false
    namespaces:
      releaseNamespace: true
      additional:
        - kube-system
```
