### ISSUE TITLE
Prom Operator node exporter on picking up k8s worker nodes

### ISSUE THREAD

**Issue by jeffplesko** [prometheus-operator/prometheus-operator#3100]
I am having a problem with the nodeExporter picking up all 6 of my nodes, we have 3 master nodes which manager the control plane and etcd and 3 worker nodes which take alll the deployed pods.  Currently only the 3 worker nodes appear.  Checking the /target list and it only has the 3 worker nodes, no masters, no errors for the master nodes.

Prometheus Operator v6.7.3
Rancher Version: v2.2.8

```
## Deploy node exporter as a daemonset to all nodes
##
nodeExporter:
  enabled: true

  ## Use the value configured in prometheus-node-exporter.podLabels
  ##
  jobLabel: jobLabel

  serviceMonitor:
    ## Scrape interval. If not set, the Prometheus default scrape interval is used.
    ##
    interval: ""

    ## 	metric relabel configs to apply to samples before ingestion.
    ##
    metricRelabelings: []
    # - sourceLabels: [__name__]
    #   separator: ;
    #   regex: ^node_mountstats_nfs_(event|operations|transport)_.+
    #   replacement: $1
    #   action: drop

    ## 	relabel configs to apply to samples before ingestion.
    ##
    relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #  target_label: nodename
    #   replacement: $1
    #   action: replace

## Configuration for prometheus-node-exporter subchart
##
prometheus-node-exporter:
  podLabels:
    ## Add the 'node-exporter' label to be used by serviceMonitor to match standard common usage in rules and grafana dashboards
    ##
    jobLabel: node-exporter
  extraArgs:
    - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
    - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
```

**Comment by lilic** [comment]
What do you mean by subchart? This repo is only for prometheus-operator and we don't provide node-exporter. Do you have a problem with the ServiceMonitor itself?

**Comment by jeffplesko** [comment]
That is the ## comments expanding to header text...it ws just a comment from the prometheus-operater values.yaml

**Comment by brancz** [comment]
1) we don't use nor maintain the charts, we have no idea about its setup, it's entirely community maintained
2) do you actually see all nodes in `kubectl get nodes`? We can only discover what Kubernetes knows about.

**Comment by jeffplesko** [comment]
Thanks for your response.  I am somewhat new to prometheus/grafana and prometheus-operator so I appreciate any help or direction where to get help...

Yes, I can see all 6 nodes from a kubectl get nodes:

NAME         STATUS   ROLES               AGE   VERSION
10.8.1.10    Ready    controlplane,etcd   44d   v1.14.6
10.8.1.138   Ready    controlplane,etcd   44d   v1.14.6
10.8.1.148   Ready    worker              44d   v1.14.6
10.8.1.20    Ready    worker              44d   v1.14.6
10.8.1.74    Ready    controlplane,etcd   44d   v1.14.6
10.8.1.84    Ready    worker              44d   v1.14.6

but only the workers are showing up in prometheus in the targets list for nodes.  I do see it find the master nodes fine for things like etcd monitoring, just not for the node stats.  I appreciate any further info or direction you can offer as I learn to navigate the community.

**Comment by brancz** [comment]
There should be an endpoints object named `kubelet` in the `kube-system` namespace, do you see all 6 nodes there or only 3?

**Comment by jeffplesko** [comment]
Yes I see all 6 in kubelet:


Endpoint | State | Labels | Last Scrape | Scrape Duration | Error
-- | -- | -- | -- | -- | --
https://10.8.16.10:10250/metrics | UP | endpoint="https-metrics" instance="10.8.16.10:10250" job="kubelet" namespace="kube-system" node="10.8.16.10" service="monitoring-prometheus-oper-kubelet" | 29.696s ago | 13.85ms |  
https://10.8.16.138:10250/metrics | UP | endpoint="https-metrics" instance="10.8.16.138:10250" job="kubelet" namespace="kube-system" node="10.8.16.138" service="monitoring-prometheus-oper-kubelet" | 7.085s ago | 22.84ms |  
https://10.8.16.148:10250/metrics | UP | endpoint="https-metrics" instance="10.8.16.148:10250" job="kubelet" namespace="kube-system" node="10.8.16.148" service="monitoring-prometheus-oper-kubelet" | 18.9s ago | 49.12ms |  
https://10.8.16.20:10250/metrics | UP | endpoint="https-metrics" instance="10.8.16.20:10250" job="kubelet" namespace="kube-system" node="10.8.16.20" service="monitoring-prometheus-oper-kubelet" | 19.487s ago | 39.65ms |  
https://10.8.16.74:10250/metrics | UP | endpoint="https-metrics" instance="10.8.16.74:10250" job="kubelet" namespace="kube-system" node="10.8.16.74" service="monitoring-prometheus-oper-kubelet" | 20.763s ago | 10.91ms |  
https://10.8.16.84:10250/metrics | UP | endpoint="https-metrics" instance="10.8.16.84:10250" job="kubelet" namespace="kube-system" node="10.8.16.84" service="monitoring-prometheus-oper-kubelet" | 7.476s ago | 30.41ms |

**Comment by jeffplesko** [comment]
Any further ideas?  It appears like everything is seeing the nodes, yet its not reporting all of them.

**Comment by brancz** [comment]
I'm confused, the last snippet in the comment suggests that all 6 nodes are discovered and marked as `UP`.

**Comment by jeffplesko** [comment]
You would think, but that is only in kubelet.  If you look at the nodes themselves, only 3 of the 6 show.  So whats the issue?

**Comment by brancz** [comment]
I see now. Do you maybe have taints on your nodes that node-exporter might not be tolerating or a node selector that is not satisfied by the nodes?

**Comment by jeffplesko** [comment]
I am not seeing anything that should be blocking this.  Its all pretty generic.

**Comment by jeffplesko** [comment]
I found this PR by you that might be of interest here, but add this didn't seem to work.  Not sure If I am applying this correctly.

https://github.com/coreos/prometheus-operator/pull/610/files

**Comment by brancz** [comment]
An even more general toleration already exists: https://github.com/coreos/kube-prometheus/blob/8fdf1c772c3d02a68f11466b118dccab3eb6211c/manifests/node-exporter-daemonset.yaml#L82

Can you double check that your daemonset has this?

**Comment by paulfantom** [comment]
Closing as the issue appears to be answered. If you need additional clarification, please reopen it.

**Comment by Oliver-Sellwood** [comment]
For anyone running across this in the future...

I think the problem here was that the value of `nodeExporter.jobLabel` must match the value of `prometheus-node-exporter.jobLabel` 

i.e the config should be 

```
## Deploy node exporter as a daemonset to all nodes
##
nodeExporter:
  enabled: true

  ## Use the value configured in prometheus-node-exporter.podLabels
  ##
  jobLabel: node-exporter

  serviceMonitor:
    ## Scrape interval. If not set, the Prometheus default scrape interval is used.
    ##
    interval: ""

    ## 	metric relabel configs to apply to samples before ingestion.
    ##
    metricRelabelings: []
    # - sourceLabels: [__name__]
    #   separator: ;
    #   regex: ^node_mountstats_nfs_(event|operations|transport)_.+
    #   replacement: $1
    #   action: drop

    ## 	relabel configs to apply to samples before ingestion.
    ##
    relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #  target_label: nodename
    #   replacement: $1
    #   action: replace

## Configuration for prometheus-node-exporter subchart
##
prometheus-node-exporter:
  podLabels:
    ## Add the 'node-exporter' label to be used by serviceMonitor to match standard common usage in rules and grafana dashboards
    ##
    jobLabel: node-exporter
  extraArgs:
    - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
    - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
```

note: I had to delete and redeploy the release to get these changes to take effect
