### ISSUE TITLE
Horizontal scaling via sharding

### ISSUE THREAD

**Issue by jadencodes** [prometheus-operator/prometheus-operator#3130]
**What is missing?**
Horizontal Scaling via Sharding

**Why do we need it?**
Right now we are collecting approx. 2 Million series with 2 hour blocks and using thanos for long term storage and deduping at query time. Despite these small block sizes, the ram usage is around 11 gigs. We run in HA mode so multiple prometheus pods all have about the same ram usage.

As we scale out more metrics, it will become unfeasible to keep scaling vertically (currently they are on 32 gig boxes so we do have room).

**Environment**
Kubernetes 1.15.7
Thanos 0.10.1

* Prometheus Operator version: quay.io/coreos/prometheus-operator:v0.37.0

**Anything else we need to know?**:
I believe I know a way to fix implement this simply enough. We can add an option to the operator like so:

```yaml
sharding:
  enabled: true
  numShards: 2
  hashKey: __address__
```

In turn, this would add something like this to **each** of the jobs in the prometheus config:

> On prometheus-replica-0:

```yaml
- job_name: "foo"
  metrics_path: "/metrics"
  kubernetes_sd_config:
  - role: endpoints
  relabel_configs:
    - source_labels: [__address__]
      modulus:       2
      target_label:  __tmp_hash
      action:        hashmod
    - source_labels: [__tmp_hash]
      regex:         ^0$
      action:        keep
```

> On prometheus-replica-1:

```yaml
- job_name: "foo"
  metrics_path: "/metrics"
  kubernetes_sd_config:
  - role: endpoints
  relabel_configs:
    - source_labels: [__address__]
      modulus:       2
      target_label:  __tmp_hash
      action:        hashmod
    - source_labels: [__tmp_hash]
      regex:         ^1$
      action:        keep
```

HA would still be available by having more replicas than shards. In the above example that shards using modulus 2, `prometheus-replica-2` config would match `prometheus-replica-0` config.

Deduping would be done by thanos and/or alertmanager.

To merge results, federation can be enabled and then the master can scrape them and consolidate **OR** use a third party tool like thanos to do this for you.

I would be happy to implement this feature if this proposal is accepted.
