### ISSUE TITLE
Linter pass, but the created rule is invalid

### ISSUE THREAD

**Issue by omerlh** [prometheus-operator/prometheus-operator#3147]
**What happened?**
I'm using prometheus operator linter to check my rules before deploying them, and although the linter said the rules are valid, in fact the rule was invalid. Is this the expected behavior? I can see with promtool that the rule is invalid...

**Comment by brancz** [comment]
Do you have an example? Also can you double check that you actually have the validating webhook setup?

**Comment by omerlh** [comment]
```
- name: Scheduling
      rules:
        - record: utilizaion
          expr: 'sum(kube_pod_info[5m])) / sum(kube_node_status_capacity_pods)'
          labels:
            service: scheduling
        - record: saturation
          expr: 'sum(kube_pod_info[5m])) / sum(kube_node_status_capacity_pods)'
          labels:
            service: scheduling
```

This is just one example - the rule itself is invalid (the promql query is invalid), which is detected by promtool, but not by the operator linter. 

I'm not using the webhook - I'm running the linter on CI before merging PRs, and I was expecting it to fail if there is an invalid config.
