### ISSUE TITLE
How add list in servicemonitor params.target?

### ISSUE THREAD

**Issue by Minstrel56** [prometheus-operator/prometheus-operator#3166]
Hello, how can i add array of targets into spec.endpoints.params.target?
If i try to use somthing like this range function 
Values
```
servicemonitor:
  params:
    url:
      - examplehost1.local
      - examplehost2.local  
```
Chart
```
target:
  {{- range .Values.servicemonitor.params.url }}
    {{ . | toStrings }}
  {{- end }}
```

i get error 
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ServiceMonitor.spec.endpoints[0].params.target[0]): invalid type for com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints.params: got "array", expected "string"

But i can create or change worked one-target servicemonitor with hand and it will work

```
target:
  - examplehost1.local
  - examplehost2.local  
```
