### ISSUE TITLE
`path` in PodMetricsEndpoint from PodMonitor Spec is not picked up

### ISSUE THREAD

**Issue by ryandawsonuk** [prometheus-operator/prometheus-operator#3167]
Seems to [be in the CRD](https://github.com/coreos/prometheus-operator/blob/6225c4c5fb3ff91ad88f2528775a34c986804ed0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml#L125) but it's not exactly clear how to set it. 

The default seems to be `/metrics`. How would I change this to `/prometheus`? I'm guessing something like:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app
  podMetricsEndpoints:
  - port: web
    path: '/prometheus'
```
Not been able to get it to work as yet though.
