### ISSUE TITLE
--kubelet-service flag when deployed via OLM?

### ISSUE THREAD

**Issue by patoarvizu** [prometheus-operator/prometheus-operator#3180]
**What did you do?**

I'm deploying the operator through the OLM framework, via a `Subscription` object, but because the most recent `ClusterServiceVersion` ([0.37.0](https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/prometheus/0.37.0)) doesn't include the `--kubelet-service` flag, and as far as I can tell, there's no way to inject that via environment variables, there's no way to tell the operator to manage the kubelet `Endpoints`.

**Did you expect to see some different?**

To have a way to enable the functionality of the operator managing the kubelet `Endpoints` when I'm deploying the operator via an OLM `Subscription`.

Is there an alternative like a separate controller that dynamically creates the `Endpoints`?

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    quay.io/coreos/prometheus-operator:v0.37.0 (quay.io/coreos/prometheus-operator@sha256:ed3ec0597c2d5b7102a7f62c661a23d8e4b34d910693fc23fd40bfb1d9404dcf)

* Kubernetes version information:

    `kubectl version`
    Client: 1.13.11
    Server: 1.12.7

* Kubernetes cluster kind:

    Kops

* Manifests:

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus
  namespace: operators
spec:
  channel: beta
  name: prometheus
  source: operatorhubio-catalog
  sourceNamespace: olm
```

**Anything else we need to know?**:

OLM version 0.14.1
