### ISSUE TITLE
How can I expose grafana, prometheus and alert manager via ALB

### ISSUE THREAD

**Issue by vrathore18** [prometheus-operator/prometheus-operator#3192]
I saw a couple of example on how to expose grafana via ngnix. But I am looking for a way to expose grafana, prometheus and alert manager via ALB ingress

```
apiVersion: v1
kind: Service
metadata:
  name: qa-prometheus-operator-grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: qa-prometheus-operator
    app.kubernetes.io/name: grafana
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: qa-prometheus-operator
    app.kubernetes.io/name: grafana
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: "	arn:aws:acm:eu-west-1:428450571168:certificate/ec969c04-60f9-4654-a842-2f0c22e989d4"
    alb.ingress.kubernetes.io/inbound-cidrs: "0.0.0.0/0"
spec:
  rules:
    - host: grafana.qa.genieai.co
      http:
        paths:
          - path: /*
            backend:
              serviceName: qa-prometheus-operator-grafana
              servicePort: 80
```

But this is now working. any pointers? how to make it work for ALB?
