### ISSUE TITLE
Dropping metrics gathered using ServiceMonitor

### ISSUE THREAD

**Issue by sebarys** [prometheus-operator/prometheus-operator#3205]
Hi,

I'm using ServiceMonitor to scrape metrics from Istio. I would like to drop some of them and found that it is possible using `metric_relabel_configs`. 

My current ServiceMonitor yaml:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: http
    prometheus: kube-prometheus
  name: istio-monitor
  namespace: commontools
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-monitoring
    scheme: http
    scrapeTimeout: 30s
    tlsConfig:
      insecureSkipVerify: true
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: prometheus
    scheme: http
    scrapeTimeout: 30s
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - istio-system
  selector:
    matchExpressions:
    - key: istio
      operator: In
      values:
      - galley
      - mixer
```

Unfortunately I couldn't find how apply drop configuration to ServiceMonitor - is it possible somehow at the moment? Or can I provide global `metric_relabel_configs` to prometheus-operator `values.yaml` that will be applied to all scraped metrics?

Thanks in advance for any suggestion and help :)
