### ISSUE TITLE
Metric relabeling is removing all samples. How can I stop it?

### ISSUE THREAD

**Issue by zenbones** [prometheus-operator/prometheus-operator#3243]
Here's query for my custom metrics job...

```
up{endpoint="http", instance="172.17.0.12:9015", job="absolute-epicenter-worker", namespace="default", pod="absolute-epicenter-worker-d4bd57886-hpdmp", service="absolute-epicenter-worker"}
1
scrape_duration_seconds{endpoint="http", instance="172.17.0.12:9015", job="absolute-epicenter-worker", namespace="default", pod="absolute-epicenter-worker-d4bd57886-hpdmp", service="absolute-epicenter-worker"}
0.005390915
scrape_samples_scraped{endpoint="http", instance="172.17.0.12:9015", job="absolute-epicenter-worker", namespace="default", pod="absolute-epicenter-worker-d4bd57886-hpdmp", service="absolute-epicenter-worker"}
16
scrape_samples_post_metric_relabeling{endpoint="http", instance="172.17.0.12:9015", job="absolute-epicenter-worker", namespace="default", pod="absolute-epicenter-worker-d4bd57886-hpdmp", service="absolute-epicenter-worker"}
0
scrape_series_added{endpoint="http", instance="172.17.0.12:9015", job="absolute-epicenter-worker", namespace="default", pod="absolute-epicenter-worker-d4bd57886-hpdmp", service="absolute-epicenter-worker"}
0
count:up1{endpoint="http", job="absolute-epicenter-worker", namespace="default", service="absolute-epicenter-worker"}
1
```

Notice how I have no samples post relabeling? How can I tell why that's occurring, and how can I best stop it?

**Comment by brancz** [comment]
Can you share your ServiceMonitor/PodMonitor?

**Comment by zenbones** [comment]
This is the service monitor. I could fish out the version with the vars filled in, but this is a minikube install with everything in the 'default' namespace, so the values would not be terribly interesting. Both the app label and match label do match the app name, as  the app uses exactly same same variables for its name (and release, etc). Other than this I'm relying on the defaults for the prometheus-operator helm chart. Nothing changed. And the monitor works insofar as the number of samples shown for the scrape is correct.

```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "epicenter-worker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "epicenter-worker.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ include "epicenter-worker.fullname" . }}
      release: "{{ .Release.Name }}"
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: http
    interval: 120s
    path: /epicenter/rest/claxon/prometheus
```
