### ISSUE TITLE
relabelings vs metricRelabelings

### ISSUE THREAD

**Issue by delulu** [prometheus-operator/prometheus-operator#3246]
Hi there,

We can leverage `relabelings` or `metricRelabelings` to rename/drop a label, and it seems `relabelings` is applied on the `Scrape` behavior, and `metricRelabelings` is applied after the `Scrape` behavior and before the ingestion, right?

I would like to understand more about these two settings, so could share your own best practice, for example which one is more efficient and less cost?

Thanks!

**Comment by brancz** [comment]
You’re on the right track.

Relabelings refer to the labels that a target ends up having, this happens when Prometheus discovers your targets (so we often refer to this as “at discovery time”). Targets are scraped and all target labels are added to the metrics scraped from that target.

Metric relabeling is as you noted correctly done after the target’s labels have been added to the metrics that were just scraped, and right before they’re inserted into the time series database. We often refer to metric relabeling to be done “at scrape time”.

**Comment by delulu** [comment]
Since we can already use `Relabelings` to rename or drop labels, and `metricRelabelings` has the same configuration format as `Relabelings`. 

What's the purpose of `metricRelabelings`, is there anything that we have to do with `metricRelabelings`?

**Comment by brancz** [comment]
With metric relabeling you can for example rename labels at ingestion time, or drop entire metrics that are not useful to you for example or maybe harmful (in a cardinality explosion for example).

**Comment by ethernoy** [comment]
Hi, I have a question regarding these two fields too:

Let's say we have two Prometheus, namely A and B. B scape from /federate API of A using a hornorLabels=true service monitor. However, A and B both put a label "prometheus_replica" in its metric to indicate the Prometheus pod name and I wish to relabel A's "prometheus_replica" to something else in order to let B put its label on the scraped metric.

In this case, I wonder if it is a good practice to update service monitor as below to achieve my goal:

```
    relabelings:
    - sourceLabels: ["prometheus_replica"]
      regex: ".*"
      targetLabel: "another_prometheus_replica"
      action: replace
    metricRelabelings:
    - sourceLabels: ["prometheus_replica"]
      regex: ".*"
      action: drop
```

**Comment by delulu** [comment]
You can simply use the settings below to achieve it, and it is processing label rename and drop at the same time, which seems to be more efficient.
```
    metricRelabelings:
    - sourceLabels: ["prometheus_replica"]
      regex: (.*)
      targetLabel: "another_prometheus_replica"
      action: replace
    - regex: "prometheus_replica"
      action: labeldrop
```
