### ISSUE TITLE
[Proposal] AlertmanagerRule CRD

### ISSUE THREAD

**Issue by bigangryrobot** [prometheus-operator/prometheus-operator#3261]
**What is missing?**
Alertmanager is only configurable in one way, normally via deployment and creation of its secret. This means that the best alternative is to inject additional changes via jobs running in the cluster reading configuration files or firing up alert managers to support subsections of users as effective as possible. Neither of these solutions are finite in their approach or scale well.

**Why do we need it?**
This limitation of configuration means that operators must include all possibilities for routes and receivers is locked within it and hidden from users within the cluster. Exposing just part of the alertmanager config would vastly improve the usability of this tool and reduce the operational cost for adding new teams or alert pathways. I suggest the following

```
apiVersion: monitoring.coreos.com/v1
kind: AlertmanagerRule
metadata:
  name: <name>
  namespace: <namespace>
spec:
  routes: # One or more notification routes
    - <routes> # following prometheus standard route definition
  receivers: # A list of notification receivers.
    - name: <name> # The receiver name as defined in the <receiver> spec
      secretRef: <secret name> # kubernetes secret name as found within the namespace which contains one or more receiver config blocks as found in the <receiver> spec (eg <email_config>)
```
* The alertmanager defaults and general config blocks would be configured via the same process as it is now. These would only provide additional routes and receivers  
* The operator would discover AlertmanagerRule resources within the cluster and merge them with the defaults defined within the existing config
* All routes added would be non blocking, with continue forced to true. This can be not great, but there is no better work around to make sure someone does not clobber all down level alerts unless we can use multiple root routes instead (documentation is unclear and ive not tested multiple root routes)

**Environment**

* Prometheus Operator version: All

    `Insert image tag or Git SHA here`
    

**Anything else we need to know?**:
