### ISSUE TITLE
Hash locking the alertmanager config-reloader image

### ISSUE THREAD

**Issue by daurnimator** [prometheus-operator/prometheus-operator#3262]
I attempted to specify an image hash for the alertmanager

```yaml
  sha: 3d52ab7ef3a2e23e26a73cfd0ce13189e3796fb276b9af3e79664e4f743d8a1d
  containers:
    - name: config-reloader
      image: quay.io/coreos/configmap-reload@sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057
```

However it doesn't seem to do a strategic merge in the same way prometheus does:

```
Warning  FailedCreate      3m37s (x17 over 9m4s)  statefulset-controller  create Pod alertmanager-main-2 in StatefulSet alertmanager-main failed error: Pod "alertmanager-main-2" is invalid: spec.containers[2].name: Duplicate value: "config-reloader"
```

How can I specify the exact image checksum for the config-reloader container?

-----

Version: prometheus-operator:v0.34.0
