### ISSUE TITLE
ingress or clusterip

### ISSUE THREAD

**Issue by tirelibirefe** [prometheus-operator/prometheus-operator#3295]
I've read jsonnet stuff and there is no enough documentation about how to apply about jsonnet thing. I didn't understand anything. 

I've created clusterip service, it didn't work. Probably it doesn't work as there are 2 services use port 9090.

```
apiVersion: v1
kind: Service
metadata:
  name: prometheus-kafka
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
```
Is there another way to expose prometheus outside of kubernetes cluster?

**Comment by brancz** [comment]
`ClusterIP` type services do not expose an application to the outside of a cluster, that doesn't have anything to do with jsonnet. I would suggest that you start without jsonnet, and understand the concepts separately, and then dive into how to achieve this with jsonnet.

**Comment by tirelibirefe** [comment]
Sorry, my mention was missing.
I know clusterip, nodeport, service and ingress. I mean if there was a working clusterip ip, it would be easy to expose it outside of the cluster via custom ingress.
Do you guys all use only jsonnet to access prometheus from outside of kubernetes?

**Comment by tirelibirefe** [comment]
ok, let me explain the problem from the beginning.
My system is bare-metal vSphere Kubespray Kubernetes:
I prepared service and ingress manifests based on tutorial here:
[https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/exposing-prometheus-and-alertmanager.md](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/exposing-prometheus-and-alertmanager.md)

```
cat <<EOF | kubectl apply -f -
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring
  namespace: kafka
  annotations:
    ingress.kubernetes.io/rewrite-target: "/"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: ca-dev1
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  backend:
    serviceName: prometheus-kafka
    servicePort: 9090
  rules:
  - host: monitoring.dev1.kik.io
    http:
      paths:
      - backend:
          serviceName: prometheus-kafka
          servicePort: 9090
        path: /prometheus-kafka
  tls:
  - hosts:
    - monitoring.dev1.kik.io
    secretName: prometheus-tls-dev1
EOF

cat <<EOF | kubectl apply -n kafka -f -
apiVersion: v1
kind: Service
metadata:
  name: prometheus-kafka
spec:
  selector:
    app: prometheus
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9090
    targetPort: web
EOF

```

...and descriptions:

```
devadmin@vdi-mk2-ubn:~$ kubectl get svc -n kafka
NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                               AGE
kafka-beytepe-kafka-bootstrap    ClusterIP   10.233.53.108   <none>        9091/TCP,9092/TCP,9093/TCP,9404/TCP   15h
kafka-beytepe-kafka-brokers      ClusterIP   None            <none>        9091/TCP,9092/TCP,9093/TCP            15h
kafka-beytepe-kafka-exporter     ClusterIP   10.233.55.157   <none>        9404/TCP                              15h
kafka-beytepe-zookeeper-client   ClusterIP   10.233.14.254   <none>        9404/TCP,2181/TCP                     15h
kafka-beytepe-zookeeper-nodes    ClusterIP   None            <none>        2181/TCP,2888/TCP,3888/TCP            15h
prometheus-kafka                 ClusterIP   10.233.52.173   <none>        9090/TCP                              7m14s
prometheus-operated              ClusterIP   None            <none>        9090/TCP                              15h
devadmin@vdi-mk2-ubn:~$ kubectl describe svc prometheus-kafka -n kafka
Name:              prometheus-kafka
Namespace:         kafka
Labels:            <none>
Annotations:       Selector:  app=prometheus
Type:              ClusterIP
IP:                10.233.52.173
Port:              <unset>  9090/TCP
TargetPort:        web/TCP
Endpoints:         10.233.78.177:9090
Session Affinity:  None
Events:            <none>
devadmin@vdi-mk2-ubn:~$ kubectl get ingress -n kafka
NAME         CLASS    HOSTS                    ADDRESS          PORTS     AGE
monitoring   <none>   monitoring.dev1.kik.io   192.168.215.31   80, 443   11m
devadmin@vdi-mk2-ubn:~$ kubectl describe ingress monitoring -n kafka
Name:             monitoring
Namespace:        kafka
Address:          192.168.215.31
Default backend:  prometheus-kafka:9090 (10.233.78.177:9090)
TLS:
  prometheus-tls-dev1 terminates monitoring.dev1.kik.io
Rules:
  Host                    Path  Backends
  ----                    ----  --------
  monitoring.dev1.kik.io
                          /prometheus-kafka   prometheus-kafka:9090 (10.233.78.177:9090)
Annotations:              cert-manager.io/cluster-issuer: ca-dev1
                          ingress.kubernetes.io/rewrite-target: /
                          kubernetes.io/ingress.class: nginx
                          nginx.ingress.kubernetes.io/proxy-body-size: 0
Events:
  Type    Reason             Age    From                      Message
  ----    ------             ----   ----                      -------
  Normal  CreateCertificate  11m    cert-manager              Successfully created Certificate "prometheus-tls-dev1"
  Normal  CREATE             3m34s  nginx-ingress-controller  Ingress kafka/monitoring
  Normal  UPDATE             2m42s  nginx-ingress-controller  Ingress kafka/monitoring
devadmin@vdi-mk2-ubn:~$
```

...and my NGINX says 404.

`10.233.89.0 - - [25/Jun/2020:12:52:33 +0000] "GET /prometheus-kafka HTTP/2.0" 404 19 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0" 231 0.004 [kafka-prometheus-kafka-9090] [] 10.233.78.177:9090 19 0.004 404 703524123d772d4c4439becd6bca2276
`

What am I missing? Could you please advise?
