### ISSUE TITLE
set domain name as target

### ISSUE THREAD

**Issue by hedeesaa** [prometheus-operator/prometheus-operator#3366]
I want to define domain name url instead of IP address as target.
is there any way to do that?

**Comment by brancz** [comment]
Is this for scraping or synthetic probes that you want to ping?

**Comment by hedeesaa** [comment]
It's for scraping. until now I've always created a service and an endpoint like this:
```
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
spec:
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: test
  labels:
    app: test
subsets:
- addresses:
  - ip: "x.x.x.x" 
  ports:
    - name: metrics
      port: 9100
      protocol: TCP

```
for endpoint I always address the target by it's IP but now I need to address it by Domain name URL something like this: example.com:9100
Is there any way to do that? 
I've searched and I found [additionalScrapConfig](https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md) but I prefer not changing the Prometheus file
