### ISSUE TITLE
ServiceMonitor added but no targets discovered (0/0 up)

### ISSUE THREAD

**Issue by kam1sh** [prometheus-operator/prometheus-operator#3383]
Hi! Firstly, thank you for the Prometheus operator and the whole kube-prometheus stack. It's awesome that such work exists =)

I'm kinda new to k8s. and only recently I deployed kube-prometheus on our cluster. 

**What did you do?**

I have a few services in the default namespace, one of them is a Caddy web server with prometheus metrics plugin.
This morning I added **ServiceMonitor** for that service. After some time, it showed up in the Prometheus /targets page, but with no targets discovered (0/0 up).

**Did you expect to see some different?**

I expected to see something like 0/1 up, because I have one pod of that service that has metrics endpoint on 127.0.0.1 (instead of 0.0.0.0), which I'll configure later =)

**Environment**

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.38.1`
    

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    Cluster managed by service provider (CROC), that is something like AWS.

* Manifests:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: content-admin
  labels:
    app: content-admin
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: content-admin
```

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: content-admin
spec:
  selector:
    matchLabels:
      app: content-admin
  endpoints:
  - targetPort: 9180
    interval: 15s
```

* Prometheus Operator Logs:

There is no warning or error logs, only info messages about re-reading configuration:

Operator logs:
```
level=info ts=2020-08-04T09:16:50.016594107Z caller=operator.go:1094 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s    
level=info ts=2020-08-04T09:16:50.168647251Z caller=operator.go:1094 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s    
level=info ts=2020-08-04T09:17:25.905339202Z caller=operator.go:1094 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s    
level=info ts=2020-08-04T09:17:25.967938796Z caller=operator.go:1094 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s    
```

prometheus-k8s logs:
```
level=info ts=2020-08-04T09:20:32.391Z caller=main.go:734 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2020-08-04T09:20:32.414Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-08-04T09:20:32.414Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-08-04T09:20:32.415Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-08-04T09:20:32.416Z caller=kubernetes.go:190 component="discovery manager notify" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-08-04T09:20:32.437Z caller=main.go:762 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
```

**Anything else we need to know?**:

I was not sure about where to post this support ticket, because, of course, I deployed kube-prometheus, not just prometheus-operator, but I think this problem tied with operator... But if I'm wrong, I can, of course, easily re-post this ticket on kube-prometheus =)
