### ISSUE TITLE
PrometheusMissingRuleEvaluations Warning Fired

### ISSUE THREAD

**Issue by demisx** [prometheus-operator/prometheus-operator#3388]
Hello. I get this warning alert periodically fired in production cluster. It is very distracting and I can't find any info on how to resolve it.  The cluster appears to be working normally.

```
Alert: PrometheusMissingRuleEvaluations - warning
 Description:
 Graph: :chart_with_upwards_trend: Runbook: <|:spiral_note_pad:>
 Details:
  • alertname: PrometheusMissingRuleEvaluations
  • endpoint: web
  • instance: 100.110.251.127:9090
  • job: prometheus-operator-prometheus
  • namespace: monitoring
  • pod: prometheus-prometheus-operator-prometheus-0
  • prometheus: monitoring/prometheus-operator-prometheus
  • service: prometheus-operator-prometheus
  • severity: warning
```  

**Environment**

* Prometheus Operator version:

```
Name:                   prometheus-operator-grafana
Namespace:              monitoring
CreationTimestamp:      Wed, 25 Mar 2020 14:00:51 -0700
Labels:                 app.kubernetes.io/instance=prometheus-operator
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=grafana
                        app.kubernetes.io/version=7.0.3
                        helm.sh/chart=grafana-5.2.0
Annotations:            deployment.kubernetes.io/revision: 2
                        helm.fluxcd.io/antecedent: monitoring:helmrelease/prometheus-operator
Selector:               app.kubernetes.io/instance=prometheus-operator,app.kubernetes.io/name=grafana
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/instance=prometheus-operator
                    app.kubernetes.io/name=grafana
  Annotations:      checksum/config: a82d07ffdfe1e042c4b15a94b79ce5efcce7eaa925c54bbee6ac4afd96a3effc
                    checksum/dashboards-json-config: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
                    checksum/sc-dashboard-provider-config: 18c988985da8705efd7fd1a89565e24f3bccf68b0c163345e41320a10c00771e
                    checksum/secret: 7a09c62a876b6fe25ea327bee4ab069b329c11549a340880f2ebffc53c751547
  Service Account:  prometheus-operator-grafana
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

KOPS 1.16

* Manifests:

```yaml
# In prometheus-operator.k8s-helm-release.yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  annotations:
    fluxcd.io/automated: 'false'
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 8.15.6
  values:
    prometheusOperator:
      createCustomResource: false
      configReloaderCpu: 0
    grafana:
      adminPassword: admin
    # We use kubeDns at the moment
    coreDns:
      enabled: false
    kubeDns:
      enabled: true
      service:
        selector:
          k8s-app: kube-dns
    kubeControllerManager:
      enabled: true
      service:
        selector:
          k8s-app: kube-controller-manager
    # Until https://github.com/coreos/prometheus-operator/issues/1369
    kubeEtcd:
      enabled: false
      # enabled: true
      # service:
      #   selector:
      #     # component: null
      #     k8s-app: etcd-manager-main
    kubeScheduler:
      enabled: true
      service:
        selector:
          k8s-app: kube-scheduler
    kubelet:
      enabled: true
      serviceMonitor:
        https: false
    kubeProxy:
      enabled: true
      service:
        selector:
          k8s-app: kube-proxy
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ['job']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h
          receiver: 'slack'
          routes:
            - match:
                alertname: Watchdog
              receiver: 'null'
        # This inhibit rule is a hack from https://stackoverflow.com/a/54814033/2619188
        inhibit_rules:
          - target_match_re:
              alertname: '.+Overcommit'
            source_match:
              alertname: 'Watchdog'
            equal: ['prometheus']
        receivers:
          - name: 'null'
          - name: 'slack'
            slack_configs:
              # https://api.slack.com/apps/*****/incoming-webhooks?success=1
              - api_url: 'https://hooks.slack.com/services/******
                send_resolved: true
                channel: '#alerts-prod'
                title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
                text: |-
                  {{ range .Alerts }}
                    *Alert:* {{ .Labels.alertname }} - `{{ .Labels.severity }}`
                    *Description:* {{ .Annotations.message }}
                    *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook_url }}|:spiral_note_pad:>
                    *Details:*
                    {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                    {{ end }}
                  {{ end }}
```
