### ISSUE TITLE
Issue with cross-namespaced servicemonitor

### ISSUE THREAD

**Issue by yaroslavkasatikov** [prometheus-operator/prometheus-operator#3412]
Hello team,

Could you please assist me in this issue:

Scenario: 
I have blackbox-exporter in central namespace (let's call this ns - cluster-command-center) and have servicemonitor into another namespace (let's call it vault). This servicemonitor is generated by helm, because target is dynamic (we may have several ns with such servicemonitor - vault1, vault2, vault-n etc and targets for blackbox depends on service name). 

Here is my servicemonitor resource:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: blackbox-cluster-command-center
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: prometheus-blackbox-exporter
    helm.sh/chart: prometheus-blackbox-exporter-4.3.0
  name: blackbox-cluster-test
  namespace: vault
spec:
  endpoints:
  - interval: 60s
    metricRelabelings:
    - replacement: https://test:8200/v1/sys/health?standbyok=true
      targetLabel: instance
    - replacement: cluster-command-center
      targetLabel: target
    params:
      module:
      - http_2xx
      target:
      - https://test:8200/v1/sys/health?standbyok=true
    path: /probe
    port: http
    scheme: http
    scrapeTimeout: 60s
  jobLabel: blackbox-test
  namespaceSelector:
    matchNames:
    - cluster-command-center
  selector:
    matchLabels:
      app.kubernetes.io/instance: blackbox-cluster-command-center
      app.kubernetes.io/name: prometheus-blackbox-exporter

```

So I expect that prometheus will scrape blackbox-exporter in ns cluster-command-center, but it doen't work. When I opened prometheus config, I found this:

```
- job_name: vault/blackbox-cluster-test/0
  honor_labels: false
  honor_timestamps: false
  **kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - vault**
  scrape_interval: 60s
  scrape_timeout: 60s
  metrics_path: /probe
  params:
    module:
    - http_2xx
    target:
    - https://test:8200/v1/sys/health?standbyok=true
  scheme: http
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app_kubernetes_io_instance
    regex: blackbox-cluster-command-center
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app_kubernetes_io_name
    regex: prometheus-blackbox-exporter
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: http
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Node;(.*)
    replacement: ${1}
    target_label: node
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Pod;(.*)
    replacement: ${1}
    target_label: pod
  - source_labels:
    - __meta_kubernetes_namespace

    target_label: namespace
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - source_labels:
    - __meta_kubernetes_service_label_blackbox_test
    target_label: job
    regex: (.+)
    replacement: ${1}
  - target_label: endpoint
    replacement: http
  - target_label: namespace
    replacement: vault
  metric_relabel_configs:
  - target_label: instance
    replacement: https://test:8200/v1/sys/health?standbyok=true
  - target_label: target
    replacement: cluster-command-center

```

So, the endpoint in prometheus is vault:

```
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - vault
```

And certainly there is no my blackbox exporter in this ns.

What is wrong?

Many thanks!
Yaroslav
