### ISSUE TITLE
monitor prometheus thanos sidecar support

### ISSUE THREAD

**Issue by yxyx520** [prometheus-operator/prometheus-operator#3422]
**What happened?**
sidecar thanos listen to a pod address like:
```
/bin/thanos sidecar --prometheus.url=http://localhost:9090/ --tsdb.path=/prometheus --grpc-address=[10.149.96.166]:10901 --http-address=[10.149.96.166]:10902
```
netstat -anp
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.149.96.166:10901     0.0.0.0:*               LISTEN      1/thanos
tcp        0      0 10.149.96.166:10902     0.0.0.0:*               LISTEN      1/thanos
```
curl in container
```
/tmp/curl-7.30.0.ermine $ ./curl 0.0.0.0:10902/metrics
curl: (7) Failed connect to 0.0.0.0:10902; Connection refused
/tmp/curl-7.30.0.ermine $ ./curl 127.0.0.1:10902/metrics
curl: (7) Failed connect to 127.0.0.1:10902; Connection refused
/tmp/curl-7.30.0.ermine $ ./curl 10.149.96.166:10902/metrics
10# HELP go_gc_duration_seconds A summary of the GC invocation durations.    0
0# TYPE go_gc_duration_seconds summary
 go_gc_duration_seconds{quantile="0"} 2.2644e-05
3go_gc_duration_seconds{quantile="0.25"} 5.6873e-05
0go_gc_duration_seconds{quantile="0.5"} 8.735e-05
8go_gc_duration_seconds{quantile="0.75"} 0.003217515
0go_gc_duration_seconds{quantile="1"} 0.034533782
9go_gc_duration_seconds_sum 55.984698054
 go_gc_duration_seconds_count 16558
...
```
> only curl the pod ip can get metrics, and curl 127.0.0.1 and 0.0.0.0 can not get metrics
service
```
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  clusterIP: 172.21.4.145
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: store
    port: 10901
    protocol: TCP
    targetPort: 10901
  - name: metrics
    port: 10902
    protocol: TCP
    targetPort: 10902
  selector:
    prometheus: system
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```
> forward service and curl through service refuse to connect 

I think it should listen in 0.0.0.0 not pod ip , is that right?

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
