### ISSUE TITLE
Unable to add target (RabbitMQ)

### ISSUE THREAD

**Issue by PixelRobots** [prometheus-operator/prometheus-operator#3430]
**What did you do?**

Have existing RabbitMQ cluster running in k8s cluster with the Prometheus plugin enable and working. when using port forward I can see metrics.

**Did you expect to see some different?**

Expected to see the target in the ui and then be able to create a dashbaord.

**Environment**

Azure Kubernetes Service
K8s version 1.17.7

Prometheus operator in namespace called monitoring. rabbit in namespace called default

* Prometheus Operator version:

    `quay.io/coreos/kube-state-metrics:v1.9.7`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"5737fe2e0b8e92698351a853b0d07f9c39b96736", GitTreeState:"clean", BuildDate:"2020-06-24T19:54:11Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

   ARM template in Azure. (AKS)

* Manifests:

```
RabbitMQ service looks like

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '15692'
  labels:
    app: rabbitmq
    type: Service 
spec:
  ports:
  - port: 15672
    name: http
  - port: 5672
    name: amqp
  - port: 4369
    name: epmd
  - port: 25672
    name: rabbitmq-dist
  - name: metrics
    port: 15692
    targetPort: metrics
    protocol: TCP
  selector:
    app: rabbitmq
  type: NodePort

ServiceMonitor looks like

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-rabbitmq
  namespace: monitoring
  labels:
    app: rabbitmq-service-monitor
spec:
  endpoints:
  - port: metrics
    interval: 5s
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      # Target app service
      app: rabbitmq

```

* Prometheus Operator Logs:

```
Seems nothing is showing related to this.
```

**Anything else we need to know?**:

I am new to Prometheus
