### ISSUE TITLE
Credentials secret for basicAuth is not read/found

### ISSUE THREAD

**Issue by RickS-C137** [prometheus-operator/prometheus-operator#3437]
**What did you do?**
I deployed a Helm chart containing an application, secrets and a servicemonitor.

**Did you expect to see some different?**
The servicemonitor should be scraped, so the metrics are collected by Prometheus.
I don't understand why the Prometheus can't read the credentials secret. We've done it for another kind of deployment similar to this one and it's working. Do I miss something?

**Environment**
Kubernets: 1.11.6
Helm 2.16.10

* Prometheus Operator version:

    `chart version: 5.10.4`
    `app version: 0.29.0`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

    kops

* Prometheus Operator Logs:

```
Sync "monitoring/monitoring-prometheus-oper-prometheus" failed: creating config failed: could not generate basicAuth for servicemonitor haupia. unable to fetch username secret "haupia-credentials-secret": secrets "haupia-credentials-secret" not found
```

**Anything else we need to know?**:
Here's the definition of the credentials secret:
```
apiVersion: v1
data:
  solr.auth.password: <some_base64_string>
  solr.auth.username: <some_base64_string>
  user.admin.email: <some_base64_string>
  user.admin.password: <some_base64_string>
kind: Secret
metadata:
  labels:
    chart: haupia-2.0.96
    version: 2.0.96
  name: haupia-credentials-secret
  namespace: ecs-dev-haupia
type: Opaque
```
And the servicemonitor:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: prometheus
    release: monitoring
  name: haupia
  namespace: ecs-dev-haupia
spec:
  endpoints:
  - basicAuth:
      password:
        key: user.admin.password
        name: haupia-credentials-secret
      username:
        key: user.admin.email
        name: haupia-credentials-secret
    interval: 30s
    path: /actuator/prometheus
    port: http
    scheme: http
  namespaceSelector:
    matchNames:
    - ecs-dev-haupia
  selector:
    matchLabels:
      app: haupia
```
