### ISSUE TITLE
Support External Target Scraping via the Probe CRD.

### ISSUE THREAD

**Issue by Cellebyte** [prometheus-operator/prometheus-operator#3447]
**What is missing?**

Support the Probe of External Targets and introduce those in a K8s native way.
This is currently not possible because the Probe CRD heavily relies on modules and a service running in K8s.

![image](https://user-images.githubusercontent.com/16540824/91331187-be47ad80-e7ca-11ea-9174-288c4b65f460.png)

**Why do we need it?**

Better management of monitoring of external systems which don't have a kubelet and a container runtime installed.

```yaml
  - job_name: 'node_exporter_external_system'
    metrics_path: /metrics
    static_configs:
      - targets:
          - host1.example.com
        labels:
          hostType: elastic
      - targets:
          - host2.example.com
        labels:
          hostType: ceph
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        regex: "(.*)"
        replacement: "${1}:9100"

```

Also better management of federation of prometheuses from a differenct cluster.

```yaml
- job_name: 'prometheus-federation'
  scheme: https
  scrape_interval: 15s
  honor_labels: true
  metrics_path: /federate
  basic_auth:
    username: <username>
    password: <password>
  params:
    'match[]':
      - '{job=~"^(kubelet|apiserver|kubelet|node-exporter)$"}'
  tls_config:
    insecure_skip_verify: true
  static_configs:
  - targets:
    - 'prometheus-0.<baseFQDN>'
    - 'prometheus-1.<baseFQDN>'
```

**Environment**

* Prometheus Operator version:
    `v0.41.1`
