### ISSUE TITLE
Relabelling Prometheus operator default alert

### ISSUE THREAD

**Issue by KR411-prog** [prometheus-operator/prometheus-operator#3460]
I want to relabel Kubenodeunreachle alert so I can drop this alert as we dont need it and its only creating more noise in the alerts channel.I think I need to include this relabelling under additionalScrapeConfigs: in Prometheus config..The below config does not seem to work.It is still shown in alert page.
```

additionalScrapeConfigs:
  - job_name: kube-state-metrics
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: '(KubeNodeUnreachable)'
      action: drop

```

* Prometheus Operator chart version: 9.3.1

    `Insert image tag or Git SHA here`
    
quay.io/coreos/prometheus-operator:v0.38.1

* Kubernetes version information:

    `kubectl version` 1.15
    

* Kubernetes cluster kind: EKS

    insert how you created your cluster: kops, bootkube, etc.

**Comment by simonpasquier** [comment]
you want to use `additionalAlertRelabelConfigs` to drop alerts from being sent to Alertmanager. Note that the alerts will still show in the Prometheus Alerts page.

**Comment by KR411-prog** [comment]
oh..Thankyou..
Dropping alerts was just a poc that I tried..If I want to just relabel the default alerts,should I still use additionalAlertRelabelConfigs ? If yes,is there a example of it?I am not sure where to specify jobname in this configuration.

**Comment by KR411-prog** [comment]
I tried this in a values.yaml file for prometheus-operator helm chart deployment,
```
prometheus:
  prometheusSpec:
    additionalAlertRelabelConfigs:
    - job_name: kube-state-metrics
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: KubeNodeUnreachable
        action: drop
```
But I got below error,
couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: yaml: unmarshal errors:\n  line 893: field job_name not found in type relabel.plain\n  line 894: field metric_relabel_configs not found in type relabel.plain"

**Comment by simonpasquier** [comment]
Try this

```
prometheus:
  prometheusSpec:
    additionalAlertRelabelConfigs:
    - source_labels: [__name__]
      regex: KubeNodeUnreachable
      action: drop
```

**Comment by KR411-prog** [comment]
Thankyou ..I will try that..
If I want to do relabelling during metrics ingestion,how to do that? is it same?

**Comment by simonpasquier** [comment]
It would be `metricRelabelings` (see https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#endpoint).

**Comment by KR411-prog** [comment]
I thought additionalScrapConfig will help and thats why I raised this issue when I could not make it to work.
https://github.com/prometheus-operator/prometheus-operator/issues/3479

**Comment by KR411-prog** [comment]
I tried metricRelabelings but it didnt work,
```
kubeStateMetrics:
  serviceMonitor:
    metricRelabelings:
    - regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
      targetLabel: teamname
      replacement: "myteam"
      action: replace
```
I expected new label "teamname" to be added to kube-state-metrics scrapping. But it didnt work.

**Comment by simonpasquier** [comment]
The regex never matches because source labels are empty. Try this

```
kubeStateMetrics:
  serviceMonitor:
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
      targetLabel: teamname
      replacement: "myteam"
      action: replace
```

**Comment by KR411-prog** [comment]
@simonpasquier  ..I dont want to change the existing label name.I want to add a new label called teamname.Is sourceLabels still necessary?

**Comment by KR411-prog** [comment]
I made it working by adding below config,
```
kubeStateMetrics:
  serviceMonitor:
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
      targetLabel: teamname
      replacement: "myteam"
      action: replace
```

However I am trying to populate the pod's label into the teamname using below config..but its not working.
```
kubeStateMetrics:
  serviceMonitor:
    metricRelabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_teamname]
      regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
      targetLabel: teamname
      replacement: ${1}
      action: replace
```

I am not sure if we can directly refer to the pod's label "teamname" in the sourceLabels as "__meta_kubernetes_pod_label_teamname". Please suggest on this.
Also replacement: ${1} not working
