### ISSUE TITLE
Thanos sidecar failed to start if tls is enabled

### ISSUE THREAD

**Issue by benjaminhuo** [prometheus-operator/prometheus-operator#3464]
**What happened?**
I'm trying to enable thanos sidecar's --grpc-server-tls-* configs by ：
- create certs, key, ca files
- create a secret for these files:
```
kubectl -n monitoring create secret generic thanos-sidecar-tls --from-file=ca.crt=./cert/ca.crt --from-file=server.crt=./cert/server.crt --from-file=server.key=./cert/server.key 
```
- Modify prometheus crd like below:
```
  thanos:
    baseImage: quay.io/thanos/thanos
    version: v0.15.0-rc.1
    grpcServerTlsConfig:
      caFile: "/etc/prometheus/secrets/thanos-sidecar-tls/ca.cert"
      certFile: "/etc/prometheus/secrets/thanos-sidecar-tls/server.crt"
      keyFile: "/etc/prometheus/secrets/thanos-sidecar-tls/server.key"
  volumeMounts:
  - name: thanos
    mountPath: "/etc/prometheus/secrets/thanos-sidecar-tls"
    readOnly: true
  volumes:
  - name: thanos
    secret:
      secretName: thanos-sidecar-tls
```

**But thanos sidecar container keeps failing with errors like:**

![Snip20200903_7](https://user-images.githubusercontent.com/18525465/92111472-ee243000-ee1e-11ea-9ea2-d970fe1abfb7.png)

**The prometheus container has these cert files mounted while the thanos sidecar hasn't:**

![Snip20200903_6](https://user-images.githubusercontent.com/18525465/92111554-0ac06800-ee1f-11ea-9171-23c5cb4d0116.png)

**Did you expect to see something different?**
I'm wondering if the volume/volumemount should be added to ThanosSpec as well to let thanos sidecar could mount these cert file via a secret? 
Or there is another way to pass cert files to thanos sidecar?

**Comment by brancz** [comment]
cc @s-urbaniak

**Comment by damomurf** [comment]
I'm seeing this issue also.

Essentially at the moment, without baking TLS credentials into the Thanos container image, there's actually no way currently to use the Thanos sidecar with TLS at all, because there's no functioning way to supply it with external secrets containing those credentials.

**Comment by s-urbaniak** [comment]
@benjaminhuo you can patch the thanos sidecar in the `container` section of the `Prometheus` `spec`, example:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
...
spec:
  thanos:
    baseImage: quay.io/thanos/thanos
    version: v0.15.0-rc.1
    grpcServerTlsConfig:
      caFile: "/etc/tls/grpc/ca.cert"
      certFile: "/etc/tls/grpc/server.crt"
      keyFile: "/etc/tls/grpc/server.key"
  containers:
  - name: thanos-sidecar
    volumeMounts:
    - mountPath: /etc/tls/grpc
      name: thanos-sidecar-tls
```

**Comment by s-urbaniak** [comment]
side note: we have been discussing if exposing more and more fields makes sense in native fields of the spec (i.e. `spec.thanos`).

The consensus so far was that more "advanced" settings can always be injected by patching containers directly, as prometheus-operator has a merge strategy implemented where you can express your "deltas" in the `containers` section and the reconciliation logic will then merge them.

**Comment by benjaminhuo** [comment]
@s-urbaniak Thanks for the quick response. I agree that patching the thanos-sidecar container is a good way to fix advanced feature like this. The merge strategy is such a good move 👍

**Comment by Thilaknath** [comment]
@benjaminhuo  I am trying to enable thanos sidecar as part of the kube-prometheus helm chart? can you point me to an example on how to enable the same and configure it? As the new kube-prometheus chart has multiple thanos config split across `prometheus` and `prometheus-operator` section [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml).

**Comment by benjaminhuo** [comment]
> here

I think you can put the thanos config below at https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2134

```yaml
  thanos:
    baseImage: quay.io/thanos/thanos
    version: v0.15.0-rc.1
    grpcServerTlsConfig:
      caFile: "/etc/tls/grpc/ca.cert"
      certFile: "/etc/tls/grpc/server.crt"
      keyFile: "/etc/tls/grpc/server.key"
  containers:
  - name: thanos-sidecar
    volumeMounts:
    - mountPath: /etc/tls/grpc
      name: thanos-sidecar-tls
```
