### ISSUE TITLE
Setting severity levels for an alert

### ISSUE THREAD

**Issue by KR411-prog** [prometheus-operator/prometheus-operator#3467]
I want to set different severity levels based upon the alert.
For eg:
Currently all the alerts of KubePodCrashlooping is warning.
I want to set the severity level as Critical for pods in certain namespace.
Is it possible to do this in Alertmanager?
Or in Prometheus rules?
If Prometheus rules,then its already a default rule,should I create new Prometheus rule and override this one? Could you please help with an example of this?

    Prometheus Operator chart version: 9.3.1

    Insert image tag or Git SHA here

quay.io/coreos/prometheus-operator:v0.38.1

    Kubernetes version information:

    kubectl version 1.15

    Kubernetes cluster kind: EKS

    insert how you created your cluster: kops, bootkube, etc.

**Comment by brancz** [comment]
Yes if specific results should be of different severity you should just create a second rule that represents that. Alert names are not forced to be unique so you can even call it the same.

**Comment by KR411-prog** [comment]
Thankyou..will try that..

**Comment by KR411-prog** [comment]
@brancz  ..I created a new Prometheus rule for severity level critical.And it works.
Just want to check if this is correct way to clone Prometheus rules  for severity level update.
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    app: prometheus-operator
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-operator-9.3.1
    heritage: Helm
    release: prometheus-operator
  name: prometheus-operator-kubernetes-system-kubelet-test
  annotations:
    meta.helm.sh/release-name: prometheus-operator
    meta.helm.sh/release-namespace: monitoring
spec:
  groups:
  - name: kubernetes-apps
    rules:
    - alert: KubePodNotReady
      annotations:
          message: Pod {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.pod {{`}}`}} has been in a non-ready state for longer than 15 minutes.
      expr: |-
        sum by (namespace, pod) (
          max by(namespace, pod) (
            kube_pod_status_phase{job="kube-state-metrics", namespace="default", phase=~"Pending|Unknown"}
          ) * on(namespace, pod) group_left(owner_kind) topk by(namespace, pod) (
            1, max by(namespace, pod, owner_kind) (kube_pod_owner{owner_kind!="Job"})
          )
        ) > 0
      for: 15m
      labels:
        severity: critical
```

I kept the groups name and alert name as same.And changed the expr to include namespace which is critical.I have also changed metadata.name.

**Comment by KR411-prog** [comment]
Eventhough the above config works by sending Critical alert for example pods in default namespace,the same alert is also captured in the Warning alert which is the default Prometheus rule.
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/14121261/92290533-41eb5380-eec9-11ea-9121-ecc6743ab421.png">
How to avoid the alerts getting duplicated in both warning and critical Prometheus rules?

**Comment by brancz** [comment]
Typically you use Alertmanager inhibition rules for this purpose, where you ignore the lower severity level alert over the higher level one.

**Comment by KR411-prog** [comment]
ok..got it..Thankyou..

**Comment by KR411-prog** [comment]
I tried inhibiting the alerts  so same alert in critical can inhibit warning alert.
The below configs didnt work...Please suggest whats the issue with this config..

```
    inhibit_rules:
    - source_match:
        alertname: Inhibit
        severity: critical
      target_match:
        severity: warning
        alertname: KubePodNotReady
      equal: ['alertname', 'namespace', 'pod', 'prometheus']
```
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'namespace', 'pod','prometheus']

**Comment by coderanger** [comment]
I think we can close this, it's not related to the operator, just a general question about using Prom and AlertManager.

**Comment by KR411-prog** [comment]
Ok..I will close this..
And this config finally worked,
inhibit_rules:
```
 - source_match:
       severity: critical
       alertname: KubePodNotReady
   target_match:
       severity: warning
       alertname: KubePodNotReady
   equal: ['namespace', 'pod', 'prometheus']
```
