### ISSUE TITLE
Single Pod in Alertmanager and Prometheus keeps crashing

### ISSUE THREAD

**Issue by sathyendrasaran** [prometheus-operator/prometheus-operator#3469]
**What did you do?**
Installed helm chart from 
https://github.com/helm/charts/tree/master/stable/prometheus-operator

**Did you expect to see some different?**
All components running with stable installation
I can access the alertmanager and prometheus since 2/3 are available
but the installation is not stable which prevents me to proceed 

**Environment**
EKS k8sv1.16.13

* Prometheus Operator version:
prometheus-operator-9.3.1

*Out of 3 replicas -- 2 are working only one keeps crashing
![image](https://user-images.githubusercontent.com/16977700/92178490-b1513c80-ee10-11ea-8c25-ca7a9c385e69.png)

*Alertmanager logs
![image](https://user-images.githubusercontent.com/16977700/92178562-d180fb80-ee10-11ea-9efc-02364e51b0a7.png)

*Prometheus pods are not even starting
![image](https://user-images.githubusercontent.com/16977700/92178649-fc6b4f80-ee10-11ea-94c7-63a301e24777.png)

![image](https://user-images.githubusercontent.com/16977700/92178665-02613080-ee11-11ea-94b5-8bb1592765d7.png)

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind:
EKS

**Anything else we need to know?**:
I increased health check duration still the pods keep getting SIGTERM

**Comment by brancz** [comment]
Do you happen to have multiple Prometheus Operators running?

**Comment by sathyendrasaran** [comment]
No just a single operator
---------
the issue got resolved for me
I found that it was the liveness probe which was terminating the pods before it can even start
i overridden the probes threshold which takes longer for the pods to get ready but it is not crashing anymore
-----------
Not sure if this is the way to go
happy to hear any solution which is a proper fix
------------
Both for alertmanager and prometheus containers
```
      livenessProbe:
        initialDelaySeconds: 360
        failureThreshold: 100000
        timeoutSeconds: 1000
        periodSeconds: 360     
      readinessProbe:
        initialDelaySeconds: 360
        failureThreshold: 100000
        timeoutSeconds: 1000
        periodSeconds: 360 
```
