### ISSUE TITLE
Using prometheus operator with blackbox exporter

### ISSUE THREAD

**Issue by astrixj** [prometheus-operator/prometheus-operator#3471]
We are using prometheus operator which works as expected, We want now to add the blackbox exporter 

I've installed in the same namespace like Prometheus with https://github.com/helm/charts/tree/master/stable/prometheus-blackbox-exporter

Now I've update the config (values.yaml)and install the chart with the update new values like:

     helm upgrade --install bbe stable/prometheus-blackbox-exporter -f values.yaml -n po

*Took the defaults...*

```

  targets:
    - name: example                    # Human readable URL that will appear in Prometheus / AlertManager
      url: http://example.com/healthz  # The URL that blackbox will scrape
      labels: {}                       # List of labels for ServiceMonitor. Overrides value set in `defaults`
      interval: 60s                    # Scraping interval. Overrides value set in `defaults`
      scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
      module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`

```
https://github.com/helm/charts/blob/master/stable/prometheus-blackbox-exporter/values.yaml#L137

Now when entring prometheus UI I search for `example` metric and doesnt get anything, any idea what could be missing? 

I've configure the target to use `blackbox exporter` like following

https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L1872

    additionalScrapeConfigs:
      - job_name: 'blackbox'
        static_configs:
        - targets: ['localhost:9115']

The blackbox export service is mapped to port 9115.

However somehow I dont see it in the target of Prometheus, what am I doing wrong?
