### ISSUE TITLE
additionalScrapeConfigs not working

### ISSUE THREAD

**Issue by KR411-prog** [prometheus-operator/prometheus-operator#3474]
I am trying to add a new label called "teamname" to the metrics scraped on kube-state-metrics.So my objective is to add teamname as an additional label to  the metrics scraped at kube-state-metrics so in the PrometheusRule we can set the specific team name on the label.
So tried with the below config.But I dont see this new label being added to the kube-state-metrics in Prometheus Service Discovery page.Please let me know whats the correct method to do this.
Objective: is to add new label named "teamname" so based upon the metrics,the team name has to be set.

```
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: kube-state-metrics
      relabel_configs:
      - separator: ;
        regex: (.*)
        target_label: teamname
        replacement: "myteam"
        action: replace
```
