### ISSUE TITLE
Probe with same job name not merged in prom config

### ISSUE THREAD

**Issue by nerzhul** [prometheus-operator/prometheus-operator#3476]
**What happened?**
Hello, we are trying your new very nice probe support. It works fine except if we have 2 probes with the same job name. That generate an invalid prometheus configuration with 2 jobs with the same name:

```
level=error ts=2020-09-07T14:44:54.512Z caller=main.go:614 msg="Error reloading config" err="couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: found multiple scrape configs with job name \"kube-prometheus-probe\""
```

**Did you expect to see some different?**
We would prefer to have a single job with both probes merged across namespaces

**How to reproduce it (as minimally and precisely as possible)**:
Create 2 probes on 2 namespaces with name job => boom

**Environment**
Kubernetes 1.18.8 with Debian 10.5 and containerd 1.4.0

* Prometheus Operator version: 0.41.1

    `Insert image tag or Git SHA here`
    

* Kubernetes version information: 1.18.8

    `kubectl version`
    

* Kubernetes cluster kind: managed by our internal SRE team

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests: 

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

No specific log here

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

```
level=error ts=2020-09-07T14:44:54.512Z caller=main.go:614 msg="Error reloading config" err="couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: found multiple scrape configs with job name \"kube-prometheus-probe\""
```

**Anything else we need to know?**: N/A

**Comment by brancz** [comment]
I see yes, this is indeed a bug.

Here: https://github.com/prometheus-operator/prometheus-operator/blob/289ee029ef537c38090cb9a0249e7062a3173936/pkg/prometheus/promcfg.go#L638

We should instead of setting the `job_name` like that relabel the configured job name via relabel configs and generate a job name like we [do in PodMonitors for example](https://github.com/prometheus-operator/prometheus-operator/blob/289ee029ef537c38090cb9a0249e7062a3173936/pkg/prometheus/promcfg.go#L416).

**Comment by nerzhul** [comment]
@brancz sorry i don't have the time currently, but i'm available to test any packaged docker image fix

**Comment by lilic** [comment]
@nerzhul could you paste the manifests that caused the above issue, makes it easier for me test the fix, thanks!

**Comment by nerzhul** [comment]
Hello @lilic 
Here is our example usecase

First object
```
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus
    meta.helm.sh/release-namespace: prometheus-k8s
  labels:
    app.kubernetes.io/managed-by: Helm
    k8s-app: prometheus
  name: prometheus
  namespace: prometheus-k8s
spec:
  interval: 30s
  jobName: kube-prometheus-probe
  module: http_2xx
  prober:
    path: /probe
    url: blackbox_exporter.veepee.local
  targets:
    ingress:
      selector:
        matchLabels:
          k8s-app: prometheus
```

Second object:
```
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  annotations:
    meta.helm.sh/release-name: paas-deployment
    meta.helm.sh/release-namespace: veepee-cart
  labels:
    app.kubernetes.io/managed-by: Helm
    app.k8s.veepee.tech/name: cart
  name: ingress-probe
  namespace: cart
spec:
  interval: 30s
  jobName: kube-prometheus-probe
  module: http_2xx
  prober:
    path: /probe
    url: blackbox_exporter.veepee.local
  targets:
    ingress:
      selector:
        matchLabels:
          app.k8s.veepee.tech/name: cart
```
