### ISSUE TITLE
Error while launching alert manager in the cluster.

### ISSUE THREAD

**Issue by vperi1730** [prometheus-operator/prometheus-operator#3489]
**What did you do?**

I am trying to launch the alert manager with the following CR configuration. However, I was unable to as it is looking out for a secret which i am not sure about.

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version: 0.41.1

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
  apiVersion: monitoring.coreos.com/v1
  kind: Alertmanager
  metadata:
    name: prometheus-alertmanager
  spec:
    replicas: 3
    serviceAccountName: alertmanager-sa
    image: gcr.io/saaspoc-gtso-enterprise-gke/gkegtsoent/prometheus-operator/alert-manager:v0.21.0
    logLevel: debug
    resources:
      requests:
        memory: 2048Mi
```

* Prometheus Operator Logs:

```
Volumes:
  config-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alertmanager-prometheus-alertmanager
    Optional:    false
  alertmanager-prometheus-alertmanager-db:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  alertmanager-sa-token-ctqrl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alertmanager-sa-token-ctqrl
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                From                                                          Message
  ----     ------       ----               ----                                                          -------
  Normal   Scheduled    79s                default-scheduler                                             Successfully assigned brcm-prometheus1/alertmanager-prometheus-alertmanager-0 to gke-gtso-enter-gke-g-qa-testing-node--e12e2f7f-2dtx
  Warning  FailedMount  15s (x8 over 78s)  kubelet, gke-gtso-enter-gke-g-qa-testing-node--e12e2f7f-2dtx  MountVolume.SetUp failed for volume "config-volume" : secret "alertmanager-prometheus-alertmanager" not found
```

**Anything else we need to know?**: Which secret is this referring to and what is the importance of having it?Also, anything else am i missing to do a successful launch of this?

Need help to resolve this.
