### ISSUE TITLE
Additional Prometheus and Alertmanager Services are observed

### ISSUE THREAD

**Issue by vperi1730** [prometheus-operator/prometheus-operator#3492]
**What did you do?**
I have launched the Prometheus and Alertmanager services with the following CR configurations. However, additionally, i have noticed some default services which i am not sure from where they are getting created. 

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
apiVersion: v1
  kind: Service
  metadata:
    name: alertmanager-service
  spec:
    type: LoadBalancer
    ports:
    - name: web
      port: 9093
      protocol: TCP
      targetPort: web
    selector:
      alertmanager: prometheus-alertmanager


apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: prometheus
      prometheus: prometheus
    name: prometheus-service-ui
  spec:
    type: LoadBalancer
    ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
    selector:
      prometheus: prometheus
```

* Prometheus Operator Logs:

```
service/alertmanager-operated   ClusterIP      None            <none>        9093/TCP,9094/TCP,9094/UDP   89m
service/alertmanager-service    LoadBalancer   172.30.78.94    <pending>     9093:30696/TCP               84m
service/prometheus-operated     ClusterIP      None            <none>        9090/TCP                     89m
service/prometheus-operator     ClusterIP      None            <none>        8080/TCP                     89m
service/prometheus-service-ui   LoadBalancer   172.30.45.224   <pending>     9090:32483/TCP               89m

```

**Anything else we need to know?**:

Need help to know from where those 1, 3, and 5 services are coming from which are also running on the same ports as our custom services. Can we delete them or stop if not required from creation?

Need help.
