### ISSUE TITLE
Unknown error while launching the PrometheusRule inside a namespace

### ISSUE THREAD

**Issue by vperi1730** [prometheus-operator/prometheus-operator#3494]
**What did you do?**

Tried deploying the Prometheus rule CR on a defined namespace.

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version: 0.41.1

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: prometheus
    role: alert-rules
  name: prometheus-example-rules
  namespace: brcm-prometheus1
spec:
  groups:
  - name: general.rules
    rules:
    - alert: TargetDown-serviceprom
      annotations:
        description: '{{ $value }}% of {{ $labels.job }} targets are down.'
        summary: Targets are down
      expr: 100 * (count(up == 0) BY (job) / count(up) BY (job)) > 10
      for: 10m
      labels:
        severity: warning
    - alert: DeadMansSwitch-serviceprom
      annotations:
        description: This is a DeadMansSwitch meant to ensure that the entire Alerting
          pipeline is functional.
        summary: Alerting DeadMansSwitch
      expr: vector(1)
      labels:
        severity: none
```

* Prometheus Operator Logs:

```
Error from server (InternalError): error when creating "rules.yaml": Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://test-prometheus-operator-operator.pt1-kafka-operator-demo.svc:443/admission-prometheusrules/validate?timeout=30s: service "test-prometheus-operator-operator" not found

```

**Anything else we need to know?**: Need help on this to understand what is this issue related to webhook and what additional configurations are required for this?
