### ISSUE TITLE
Alertmanager Proxy URL

### ISSUE THREAD

**Issue by colinking** [prometheus-operator/prometheus-operator#3511]
**What is missing?**

To connect Prometheus with Alertmanager, you can specify a name/namespace/port: https://github.com/prometheus-operator/prometheus-operator/blob/156a5ec29cc90d76dbff8f3c8bf918c5e73080af/pkg/apis/monitoring/v1/types.go#L638-L647

However, that assumes that Alertmanager is running in the same k8s cluster as Prometheus. Prometheus [supports an optional proxy URL](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alertmanager_config) that can be used to point Prometheus at an Alertmanager running elsewhere. Ideally, Prometheus Operator would support an optional `ProxyURL` that, if specified, would be passed down to Prometheus:

```go
type AlertmanagerEndpoints struct {
	// ...

	// Optional URL that Prometheus will proxy Alertmanager API requests to.
	ProxyURL string `json:"proxyURL,omitempty"`

	// ...
}
```

**Why do we need it?**

We have a use-case where we want to run a multi-tenant Alertmanager in another k8s cluster that multiple k8s clusters would talk to.

**Environment**

* Prometheus Operator version: 0.42.0

**Anything else we need to know?**:

I'm more than happy to open a PR with this. Mainly raising here to see if y'all would be interested in this upstream. If this doesn't make sense as part of Prometheus Operator, then we can just maintain a fork with this feature that we'll use.

**Comment by colinking** [comment]
Closing this issue, since we identified we could accomplish this with `additionalAlertManagerConfigs` to inject a `static_config` target.

**Comment by Poweranimal** [comment]
Hi @colinking 
I'm facing the same issue.
How were you able to solve it?
[static_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config) seems to define scrape target, not alert manager endpoints.
Or am I missing something?

I tried to set the following [helm](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml) config without success:
```yaml
# ...
  additionalAlertManagerConfigs: [
      {
          static_configs: [
              {
                  targets: [
                      "1.2.3.4:9093"
                  ]
              }
          ]
      }
  ]
# ...
```

**Comment by Poweranimal** [comment]
Nvm, my example worked.
Additionally, I had set the `alertmanagers` to en ampty array:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-am-confg
data:
  additional-alertmanager-configs.yaml: LSBzdGF0aWNfY29uZmlnczoKICAtIHRhcmdldHM6CiAgICAtIGt1YmUtcHJvbWV0aGV1cy1zdGFjay1hbGVydG1hbmFnZXIucHJvbWV0aGV1czo5MDkzCg==
#- static_configs:
#  - targets:
#    - 1234:9093
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  additionalAlertManagerConfigs:
    key: additional-alertmanager-configs.yaml
    name: prometheus-am-confg
  alerting:
    alertmanagers: []
# ...
```
