### ISSUE TITLE
The Prometheus operator should discard invalid TLS configurations

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#3550]
**What happened?**

I created a service monitor with a `cert` field but no `keySecret`. The operator generated the new configuration but Prometheus failed to reload because it expects that both cert and key are [defined](https://github.com/prometheus/common/blob/317b7b125e8fddda956d0c9574e5f03f438ed5bc/config/http_config.go#L344-L354).

Prometheus logs:

```
level=info ts=2020-09-29T13:28:36.663Z caller=main.go:833 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=error ts=2020-09-29T13:28:38.116Z caller=manager.go:188 component="scrape manager" msg="error creating new scrape pool" err="error creating HTTP client: client cert file \"/etc/prometheus/certs/secret_default_tls-materials_cert\" specified without client key file" scrape_pool=default/example-app/0
```

Note that if the Prometheus container crashes, it will fail to start again.

Finally the issue isn't limited to the cert/key case described here. The same thing happens if one provides an invalid certificate, key or CA.

**Did you expect to see something different?**

The operator should have rejected the invalid TLS configuration.

**How to reproduce it (as minimally and precisely as possible)**:

See manifests below.

**Environment**

* Prometheus Operator version:

master

* Kubernetes version information:
N/A

* Kubernetes cluster kind:

N/A

* Manifests:

```
apiVersion: v1
data:
  cert: Zm9vYmFy
kind: Secret
metadata:
  name: tls-materials
type: Opaque
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
spec:
  endpoints:
  - port: web
    tlsConfig:
      cert:
        secret:
          key: cert
          name: tls-materials
  selector:
    matchLabels:
      app: example-app
```

* Prometheus Operator Logs:

N/A
