### ISSUE TITLE
Allow discovery of prometheus through a service using custom annotations

### ISSUE THREAD

**Issue by omegas27** [prometheus-operator/prometheus-operator#3555]
**What is missing?**
We currently cannot use a service monitor to monitor the prometheus instances created through prometheus operator using custom annotations like prometheus.io/scrape=true

**Why do we need it?**
We need this as we currently have a management cluster managing multiple tenant clusters. We have a prometheus for the management cluster and one for each tenant cluster and we would like to use a single service monitor to scrape the prometheus instances scraping the tenant clusters, however, as we currently cannot define annotations on the generated prometheus-operated service, we can only do so using a pod monitor which we would prefer not to use.

For more context, see https://github.com/prometheus-operator/prometheus-operator/pull/3513

**Comment by brancz** [comment]
You can select all services using the empty/all matcher `{}` and then use relabeling to select those services that have the annotation.

**Comment by omegas27** [comment]
We can but that requires an extra service monitor as we cannot set custom annotations (for example: `prometheus.io/scrape=true`) on the service generated by prometheus operator (the one with the annotation `prometheus-operated=true`). 
Being able to set annotations on the generated service would make scraping them a lot easier

**Comment by brancz** [comment]
Annotations aren't necessary for that, you can you normal relabeling rules for selecting the services you want to scrape.

**Comment by omegas27** [comment]
Yes, I would then keep only the services having the prometheus-operated annotations, but would being able to add annotations to this generated service be a better alternative?

**Comment by brancz** [comment]
You can select all services from all namespaces with a ServiceMonitor something like this and then only select services named 'prometheus-operated':

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-service-monitor
spec:
  selector: {}
  namespaceSelector:
    any: true
  ports:
  - port: metrics
  relabelings:
  - action: keep
    sourceLabels: ["__meta_kubernetes_service_name"]
    regex: prometheus-operated
```
