### ISSUE TITLE
create prometheus statefulset always terminating

### ISSUE THREAD

**Issue by johnnylei** [prometheus-operator/prometheus-operator#3561]
# prometheus operator: v0.40
# k8s: v.1.16.3
$ cat  prometheus.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  image: 10.223.150.20:5000/prom/prometheus:v2.16.0
  resources:
    requests:
      memory: 400Mi
```
$ kubectl get pods
```
...
prometheus-prometheus-0                0/3     Terminating   0          1s
...
```

the question is: why pods/prometheus-prometheus-0 awalys terminating?
