### ISSUE TITLE
Probe crd not populated to prometheus config

### ISSUE THREAD

**Issue by zetaab** [prometheus-operator/prometheus-operator#3575]
**What happened?**

I created following probe:
```
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: testing
  namespace: monitoring
spec:
  jobName: testing-3
  module: http_401
  prober:
    url: blackbox-prober
  targets:
    staticConfig:
      static:
      - https://google.com
```

**Did you expect to see something different?**: I do see that prometheus config is reloaded. However, I cannot see this probe available in prometheus configurations.

**How to reproduce it (as minimally and precisely as possible)**: 1) create that probe yaml 2) wait some time and check prometheus configuration

**Environment**

* Prometheus Operator version:

v0.41.1

* Kubernetes version information:

1.19.2

* Kubernetes cluster kind:

kops

* Prometheus CRD:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: prometheus
              operator: In
              values:
              - k8s
          namespaces:
          - monitoring
          topologyKey: kubernetes.io/hostname
        weight: 100
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  image: quay.io/prometheus/prometheus:v2.21.0
  nodeSelector:
    kubernetes.io/os: linux
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  replicas: 2
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 300m
      memory: 500Mi
  retention: 90d
  retentionSize: 8GB
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 16Gi
  version: v2.21.0
  walCompression: true
```
