### ISSUE TITLE
Not able to control  Readiness probe Liveness probe

### ISSUE THREAD

**Issue by gaurav-ackotech** [prometheus-operator/prometheus-operator#3587]
Warning  Unhealthy  23m (x404 over 98m)  kubelet, ip-10-0-xx-xx.ap-south-1.compute.internal  Readiness probe failed: HTTP probe failed with statuscode: 503
  Warning  Unhealthy  17m (x93 over 78m)   kubelet, ip-10-0-xx-xx.ap-south-1.compute.internal  Liveness probe failed: Get http://10.0.77.87:9090/-/healthy: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Note : container is restarting again and again and i can not control that as prometheus-operator is not providing to control Readiness probe Liveness probe.

**Comment by paulfantom** [comment]
It seems your prometheus instance is overloaded (WAL replay?).

We recently removed liveness probes in https://github.com/prometheus-operator/prometheus-operator/pull/3502. Next prometheus-operator version will include this and it should fix your issue.

You can read our discussion on why we removed it and why we don't want to make this configurable in https://github.com/prometheus-operator/prometheus-operator/issues/3391

**Comment by RangelReale** [comment]
I am having this same problem, but with the readinessProbe instead.
This happens over and over for more than 1 hour.
```
prometheus-kube-prometheus-stack-prometheus-0 (341)
Back-off restarting failed container
BackOff

prometheus-kube-prometheus-stack-prometheus-0 (1)
Readiness probe failed: Get http://10.100.2.11:9090/-/ready: read tcp 10.100.2.1:37014->10.100.2.11:9090: read: connection reset by peer
Unhealthy

prometheus-kube-prometheus-stack-prometheus-0 (35)
Readiness probe failed: HTTP probe failed with statuscode: 503
Unhealthy
```

**Comment by RangelReale** [comment]
I discovered in #3391 that it is possible to do this:

```
  prometheusSpec:
    # Set absurdly high thresholds as a workaround for not being able to disable these and not having enough time to WAL replay
    containers:
    - name: prometheus
      livenessProbe:
        failureThreshold: 1000
      readinessProbe:
        failureThreshold: 1000
```
This fixed my problem.

**Comment by sektorhybrid** [comment]
K8s: 1.16.x / prometheus-stack:14.0.1

The liveness probe is removed here https://github.com/prometheus-operator/prometheus-operator/pull/3502 and I was getting the following error
```
  Type     Reason            Age                   From                    Message
  ----     ------            ----                  ----                    -------
.......
  Warning  FailedCreate      51s (x17 over 6m19s)  statefulset-controller  create Pod prometheus-prometheus-stack-kube-prom-prometheus-0 in StatefulSet prometheus-prometheus-stack-kube-prom-prometheus failed error: Pod "prometheus-prometheus-stack-kube-prom-prometheus-0" is invalid: spec.containers[0].livenessProbe: Required value: must specify a handler type
```

I removed the liveness lines and it worked for me
```
prometheusSpec:
    # Set absurdly high thresholds as a workaround for not being able to disable these and not having enough time to WAL replay
    containers:
    - name: prometheus
      readinessProbe:
        failureThreshold: 1000
```

**Comment by ensonic** [comment]
Re probes, using 'InitialDelaySeconds: 600' would be much better that hammering the starting service with requests.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/.
Luckily the workaround above worked here too.

**Comment by navneet1075** [comment]
@ensonic right . setting a initialDelaySeconds is much better than rather than doing so many calls in the beginning.

**Comment by navneet1075** [comment]
the pods keeps on restarting with readiness probe failed errors . 

```
Normal   Pulled                  6s (x2 over 9s)   kubelet                  Successfully pulled image "quay.io/prometheus/prometheus:v2.27.1"
  Warning  Unhealthy               3s                kubelet                  Readiness probe failed: HTTP probe failed with statuscode: 503
```

**Comment by simonpasquier** [comment]
@sev3ryn a workaround would be to patch the default startupProbe definition generated by the operator like this:

```
spec:
    containers:
    - name: prometheus
      startupProbe:
        failureThreshold: 120 # periodSeconds is 15 so this would give (120 x 15s = 1800s) for the WAL replay to complete.
```

We should probably give more flexibility for users that have Prometheus servers with long WAL replay times.

```
spec:
  startupProbeTimeoutSeconds: 1800 # default: 60x15=900=15m
```

I don't feel that we need to provide full control on the configuration of probes though.

**Comment by sev3ryn** [comment]
@simonpasquier sorry if it is a stupid question, but how can I patch definition generated by operator?

when I do `kubectl edit pod mon-prometheus` to change the values of probes I get such error
```
# pods "prometheus-mon-prometheus-1" was not valid:
# * spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
#   core.PodSpec{
#       Volumes:        {{Name: "prometheus-mon-prometheus-db", VolumeSource: {PersistentVolumeClaim: &{ClaimName: "prometheus-mon-prometheus-db-prometheus-mon-prometheus-1"}}}, {Name: "config", VolumeSource: {Secret: &{SecretName: "prometheus-mon-prometheus", DefaultMode: &420}}}, {Name: "tls-assets", VolumeSource: {Projected: &{Sources: {{Secret: &{LocalObjectReference: {Name: "prometheus-mon-prometheus-tls-assets-0"}}}}, DefaultMode: &420}}}, {Name: "config-out", VolumeSource: {EmptyDir: &{}}}, ...},
#       InitContainers: {{Name: "init-config-reloader", Image: "quay.io/prometheus-operator/prometheus-config-reloader:v0.56.2", Command: {"/bin/prometheus-config-reloader"}, Args: {"--watch-interval=0", "--listen-address=:8080", "--config-file=/etc/prometheus/config/prometheus.yaml.gz", "--config-envsubst-file=/etc/prometheus/config_out/prometheus.env"..., ...}, ...}},
#       Containers: []core.Container{
#               {
#                       ... // 11 identical fields
#                       LivenessProbe:  &{Handler: {HTTPGet: &{Path: "/-/healthy", Port: {Type: 1, StrVal: "web"}, Scheme: "HTTP"}}, TimeoutSeconds: 3, PeriodSeconds: 5, SuccessThreshold: 1, ...},
#                       ReadinessProbe: &{Handler: {HTTPGet: &{Path: "/-/ready", Port: {Type: 1, StrVal: "web"}, Scheme: "HTTP"}}, TimeoutSeconds: 3, PeriodSeconds: 5, SuccessThreshold: 1, ...},
#                       StartupProbe: &core.Probe{
#                               ... // 3 identical fields
#                               PeriodSeconds:                 15,
#                               SuccessThreshold:              1,
# -                             FailureThreshold:              120,
# +                             FailureThreshold:              60,
#                               TerminationGracePeriodSeconds: nil,
#                       },
#                       Lifecycle:              nil,
#                       TerminationMessagePath: "/dev/termination-log",
#                       ... // 6 identical fields
#               },
#               {Name: "config-reloader", Image: "quay.io/prometheus-operator/prometheus-config-reloader:v0.56.2", Command: {"/bin/prometheus-config-reloader"}, Args: {"--listen-address=:8080", "--reload-url=http://127.0.0.1:9090/-/reload", "--config-file=/etc/prometheus/config/prometheus.yaml.gz", "--config-envsubst-file=/etc/prometheus/config_out/prometheus.env"..., ...}, ...},
#               {Name: "thanos-sidecar", Image: "quay.io/thanos/thanos@sha256:122cb4950b6f86444f1dce3c7835b714ecb"..., Args: {"sidecar", "--prometheus.url=http://127.0.0.1:9090/", "--grpc-address=:10901", "--http-address=:10902", ...}, Ports: {{Name: "http", ContainerPort: 10902, Protocol: "TCP"}, {Name: "grpc", ContainerPort: 10901, Protocol: "TCP"}}, ...},
#       },
#       EphemeralContainers: nil,
#       RestartPolicy:       "Always",
#       ... // 25 identical fields
#   }
```

**Comment by simonpasquier** [comment]
Sorry for being dense :) 
You should be editing the Prometheus object and not the pod.
E.g. `kubectl edit prometheus mon-prometheus` and add the following snippet under the `spec` field (more details in https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/strategic-merge-patch.md about strategic merge patch):

```
spec:
    ...
    replicas: 2
    # snippet to be added
    containers:
    - name: prometheus
      startupProbe:
        failureThreshold: 120 # periodSeconds is 15 so this would give (120 x 15s = 1800s) for the WAL replay
    # end of snippet
   ...
```

**Comment by ddmunhoz** [comment]
Sorry, but correct me if I'm wrong: There's no way increase the InitialDelaySeconds right ? I tried the failureThreshold, but it still gives me errors. I can definite patch the pod, but that would be less than ideal.

**Comment by simonpasquier** [comment]
@ddmunhoz it is possible to patch `initialDelaySeconds`

```
spec:
    ...
    replicas: 2
    # snippet to be added
    containers:
    - name: prometheus
      startupProbe:
        failureThreshold: 120 # periodSeconds is 15 so this would give (120 x 15s = 1800s) for the WAL replay
        initialDelaySeconds: 600 # 10 minutes before even checking the probe 
    # end of snippet
   ...

```

**Comment by julianandrews** [comment]
I'm also running into this issue.

Patching the Prometheus object fixes the issue, but we deploy our Prometheus Operator with ArgoCD and automatic syncing enabled so the fix requires manually disabling auto-sync, patching the config, waiting for successful deployment, and then re-enabling auto-sync. I think this is a fairly common setup.

Patching isn't really isn't a great solution since you need an engineer around who understands the problem to fix it any time it happens.

Given the number of people affected by this (and the fact that the patch everyone's using works), I think it's pretty clear that the WAL replay absolutely can, and often does, cause liveness check failures.

In #3391 @brancz suggested waiting until K8s 1.21 and then adding a `startupProbe`. That's not the actual request in this ticket, but I think that would fix the issue nicely. Is there any plan to do this now?

**Comment by simonpasquier** [comment]
> Patching the Prometheus object fixes the issue, but we deploy our Prometheus Operator with ArgoCD and automatic syncing enabled so the fix requires manually disabling auto-sync, patching the config, waiting for successful deployment, and then re-enabling auto-sync. I think this is a fairly common setup.

I suppose that you misunderstood my comment. I was talking about using strategic merge patch as documented [here](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/strategic-merge-patch.md). So the example would be

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: test
spec:
    ...
    replicas: 2
    # snippet to be added
    containers:
    - name: prometheus
      startupProbe:
        failureThreshold: 120 # periodSeconds is 15 so this would give (120 x 15s = 1800s) for the WAL replay
        initialDelaySeconds: 600 # 10 minutes before even checking the probe 
    # end of snippet
   ...
```

**Comment by hervenicol** [comment]
Related: https://github.com/prometheus-operator/prometheus-operator/issues/4730

**Comment by andrewhibbert** [comment]
> > Patching the Prometheus object fixes the issue, but we deploy our Prometheus Operator with ArgoCD and automatic syncing enabled so the fix requires manually disabling auto-sync, patching the config, waiting for successful deployment, and then re-enabling auto-sync. I think this is a fairly common setup.
> 
> I suppose that you misunderstood my comment. I was talking about using strategic merge patch as documented [here](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/strategic-merge-patch.md). So the example would be
> 
> ```
> apiVersion: monitoring.coreos.com/v1
> kind: Prometheus
> metadata:
>   name: test
> spec:
>     ...
>     replicas: 2
>     # snippet to be added
>     containers:
>     - name: prometheus
>       startupProbe:
>         failureThreshold: 120 # periodSeconds is 15 so this would give (120 x 15s = 1800s) for the WAL replay
>         initialDelaySeconds: 600 # 10 minutes before even checking the probe 
>     # end of snippet
>    ...
> ```

Is there a way to do this via the helm chart?

**Comment by hetii** [comment]
@andrewhibbert 
> Is there a way to do this via the helm chart?

For my usecase where I use rancher-monitoring  chart I did:
```
prometheus:
  prometheusSpec:
    containers: |
      - name: prometheus
        startupProbe:
          failureThreshold: 120 # periodSeconds is 15 so this would give (120 x 15s = 1800s) for the WAL replay
          initialDelaySeconds: 600 # 10 minutes before even checking the probe
```

then when you update your helm deployment you can check yaml from prometheus pod:

`kubectl -n cattle-monitoring-system get po prometheus-rancher-monitoring-prometheus-0 -o yaml`
![obraz](https://github.com/prometheus-operator/prometheus-operator/assets/3405461/b369dc36-e1c8-4b4a-9ace-36a441885cd1)

In my case I also needed to increase a memory limits as I get OOMKilled in wal bootstrap phase.
