### ISSUE TITLE
I want to get redis and tomcat metrics on prometheus

### ISSUE THREAD

**Issue by vdi-kakui** [prometheus-operator/prometheus-operator#3589]
environment
Prometheus Operator version: 0.39.0
Kubernetes version information: 1.16

I want to get metrics for redis and tomcat using prometheus-operator.
However, even if I set it to the following yaml, it does not work well.
Where should I fix it to monitor redis and tomcat metrics?

## REDIS

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  selector:
    matchLabels:
      redis-app: redis
  replicas: 2
  template:
    metadata:
      labels:
        redis-app: redis
    spec:
      containers:
      - name: redis
        image: redis:5-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /redis-data
          name: data
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        ports:
        - containerPort: 9121
        args:
          - -redis.scrape-uri=http://localhost:9121/metrics
      volumes:
      - configMap:
          name: redis-config
        name: config
      - emptyDir:
        name: data
---
kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
  - name: redis-exporter
    protocol: TCP
    port: 9121
    targetPort: 9121
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-servicemonitor
  namespace: monitoring
  labels:
    app: redis
    release: prometheus # serviceMonitorSelectorで確認したラベル
spec:
  endpoints:
  - port: redis-exporter
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: redis # Serviceのラベル
```
