### ISSUE TITLE
The --prometheus-default-base-image flag (and others) doesn't work

### ISSUE THREAD

**Issue by soleimaniamir** [prometheus-operator/prometheus-operator#3623]
Hello, I want to install Prometheus form a private registry, I have replaced two value  in `bundle.yaml`:
```
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --prometheus-config-reloader=registry.local:9050/quay.io/prometheus-operator/prometheus-config-reloader:v0.42.1
        image: registry.local:9050/quay.io/prometheus-operator/prometheus-operator:v0.42.1
```
but after deploying, Prometheus generate two docker image that I don't know how can I replace them with my private docker images, these are images name:

- quay.io/prometheus/prometheus
- jimmidyson/configmap-reload:v0.4.0
is that any way to deploy Prometheus with private repository images?
