### ISSUE TITLE
Additional Endpoints showing up when using Scrape Config with ec2_sd_configs

### ISSUE THREAD

**Issue by Finges** [prometheus-operator/prometheus-operator#3625]
Seeing some strange behavior with ScrapeConfigs. When using the `ec2_sd_configs` service discovery for my scrape config and setting a port. Something is setting an Endpoint with port 80 in addition to the Endpoint with the port I set. I would like to know why and what I can do to remove the additional port 80 configuration.

Below is the secret I've set for the scrape config:
```
k get secret additional-scrape-configs -o jsonpath="{['data']['prometheus-additional\.yaml']}" | base64 --decode                                                                                                  !1591
-   ec2_sd_configs:
    -   region: us-west-2
    -   port: 80
    job_name: tmna-app
    relabel_configs:
    -   action: keep
        regex: dev.*
        source_labels:
        - __meta_ec2_tag_Env
    -   action: keep
        regex: app.*
        source_labels:
        - __meta_ec2_tag_Role
-   ec2_sd_configs:
    -   region: us-west-2
    -   port: 8888
    job_name: tmna-ccrd
    relabel_configs:
    -   action: keep
        regex: dev.*
        source_labels:
        - __meta_ec2_tag_Env
    -   action: keep
        regex: app.*
        source_labels:
        - __meta_ec2_tag_Role
```

Below is the Scrape Config configuration that I get from the Prometheus UI, you can see an additional `endpoint` for each ec2_sd_config with port 80... that wasn't set in the secret above:
```
scrape_configs:
- job_name: tmna-app
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  ec2_sd_configs:
  - endpoint: ""
    region: us-west-2
    refresh_interval: 1m
    port: 80
    filters: []
  - endpoint: ""
    region: us-west-2
    refresh_interval: 1m
    port: 80
    filters: []
  relabel_configs:
  - source_labels: [__meta_ec2_tag_Env]
    separator: ;
    regex: dev.*
    replacement: $1
    action: keep
  - source_labels: [__meta_ec2_tag_Role]
    separator: ;
    regex: app.*
    replacement: $1
    action: keep
- job_name: tmna-ccrd
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  ec2_sd_configs:
  - endpoint: ""
    region: us-west-2
    refresh_interval: 1m
    port: 80
    filters: []
  - endpoint: ""
    region: us-west-2
    refresh_interval: 1m
    port: 8888
    filters: []
  relabel_configs:
  - source_labels: [__meta_ec2_tag_Env]
    separator: ;
    regex: dev.*
    replacement: $1
    action: keep
  - source_labels: [__meta_ec2_tag_Role]
    separator: ;
    regex: app.*
    replacement: $1
    action: keep
```
