### ISSUE TITLE
Failed to start  `prometheus-operator` with CephRBD dynamic provisioning

### ISSUE THREAD

**Issue by soleimaniamir** [prometheus-operator/prometheus-operator#3631]
Hello, I'm trying to run `prometheus-operator` in my Kubernetes cluster, But `prometheus` container failed to start. this is Prometheus console log:
```
level=info ts=2020-10-28T10:16:11.535Z caller=main.go:353 msg="Starting Prometheus" version="(version=2.22.0, branch=HEAD, revision=0a7fdd3b76960808c3a91d92267c3d815c1bc354)"
level=info ts=2020-10-28T10:16:11.535Z caller=main.go:358 build_context="(go=go1.15.3, user=root@6321101b2c50, date=20201015-12:29:59)"
level=info ts=2020-10-28T10:16:11.535Z caller=main.go:359 host_details="(Linux 4.14.35-1902.3.2.el7uek.x86_64 #2 SMP Tue Jul 30 03:59:02 GMT 2019 x86_64 prometheus-prometheus-0 (none))"
level=info ts=2020-10-28T10:16:11.536Z caller=main.go:360 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-10-28T10:16:11.536Z caller=main.go:361 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2020-10-28T10:16:11.537Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log
goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffe17672deb, 0xb, 0x14, 0x30867c0, 0xc000ec4b70, 0x30867c0)
	/app/promql/query_logger.go:117 +0x4cf
main.main()
	/app/cmd/prometheus/main.go:388 +0x536c 
```
I changed `securityContext` because when the value was `runAsUser: 65534`, I got `permission denied` error. This is my `securityContext`:
```
securityContext:
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
```
We use CephRBD to store data, so I added the storage to my Prometheus deploy file:
```
storage:
  volumeClaimTemplate:
    spec:
      storageClassName: rancher-rbd
      resources:
        requests:
          storage: 10Gi
```

**Comment by simonpasquier** [comment]
Have you tried setting `fsGroup` in the security context?

**Comment by amirsoleimanii** [comment]
@simonpasquier 
I changed my security context as you see below but the problem already exists.
```
securityContext:
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
  fsGroup: 2000
```

**Comment by soleimaniamir** [comment]
The problem was the permission of storage that solved with this `initContainers`:
```
  initContainers:
      - name: "init-datapath"
        image: debian:stable
        command: ["chown", "-R", "65534:65534", "/data"]
        command: ["/bin/chmod","-R","777","/data"]
        volumeMounts:
        - name: prometheus-prometheus-db
          mountPath: /data
          subPath: ""

  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: rancher-rbd
        name: prometheus-prometheus-db
        resources:
          requests:
            storage: 10Gi
```

I also rever my security context:
```
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
```
