### ISSUE TITLE
unable to load CA cert for remoteRead but working fine for remoteWrite

### ISSUE THREAD

**Issue by priteshkadavrean** [prometheus-operator/prometheus-operator#3635]
**What happened?**
When using remoteRead for prometheus then it is unable to load specified CA cert.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
spec:
  remoteRead:
  - readRecent: true
    remoteTimeout: 10s
    requiredMatchers:
      labelName: labelValue
    tlsConfig:
      ca:
        secret:
          key: <some name>.pem
          name: <some name>
      cert:
        secret:
          key: <some name>.pem
          name: <some name>
      insecureSkipVerify: true
      keySecret:
        key: <some name>.key
        name: <some name>
```

* Prometheus Operator version:
v0.42.1

* Prometheus Operator Logs:

```
level=info ts=2020-10-29T13:07:49.792Z caller=head.go:714 component=tsdb msg="WAL segment loaded" segment=12 maxSegment=12
level=info ts=2020-10-29T13:07:49.792Z caller=head.go:719 component=tsdb msg="WAL replay completed" checkpoint_replay_duration=62.083µs wal_replay_duration=4.544497156s total_replay_duration=4.544625111s
level=info ts=2020-10-29T13:07:49.885Z caller=main.go:732 fs_type=EXT4_SUPER_MAGIC
level=info ts=2020-10-29T13:07:49.885Z caller=main.go:735 msg="TSDB started"
level=info ts=2020-10-29T13:07:49.886Z caller=main.go:861 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=error ts=2020-10-29T13:07:49.886Z caller=main.go:881 msg="Failed to apply configuration" err="unable to load specified CA cert /etc/prometheus/certs/secret__metricsbeattls_domain.pem: open /etc/prometheus/certs/secret__metricsbeattls_domain.pem: no such file or directory"
level=info ts=2020-10-29T13:07:49.887Z caller=kubernetes.go:263 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2020-10-29T13:07:49.888Z caller=kubernetes.go:263 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2020-10-29T13:07:49.889Z caller=main.go:585 msg="Stopping scrape discovery manager..."
level=info ts=2020-10-29T13:07:49.889Z caller=main.go:599 msg="Stopping notify discovery manager..."
level=info ts=2020-10-29T13:07:49.889Z caller=main.go:621 msg="Stopping scrape manager..."
level=info ts=2020-10-29T13:07:49.889Z caller=main.go:595 msg="Notify discovery manager stopped"
level=info ts=2020-10-29T13:07:49.889Z caller=main.go:581 msg="Scrape discovery manager stopped"
level=error ts=2020-10-29T13:07:49.889Z caller=klog.go:96 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:426: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get \"https://10.100.0.1:443/api/v1/namespaces/istio-system/endpoints?limit=500&resourceVersion=0\": context canceled"
level=error ts=2020-10-29T13:07:49.889Z caller=klog.go:96 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:427: Failed to watch *v1.Service: failed to list *v1.Service: Get \"https://10.100.0.1:443/api/v1/namespaces/istio-system/services?limit=500&resourceVersion=0\": context canceled"
level=error ts=2020-10-29T13:07:49.889Z caller=klog.go:96 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:428: Failed to watch *v1.Pod: failed to list *v1.Pod: Get \"https://10.100.0.1:443/api/v1/namespaces/istio-system/pods?limit=500&resourceVersion=0\": context canceled"
level=info ts=2020-10-29T13:07:49.889Z caller=main.go:861 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2020-10-29T13:07:49.890Z caller=main.go:615 msg="Scrape manager stopped"
level=error ts=2020-10-29T13:07:49.890Z caller=main.go:881 msg="Failed to apply configuration" err="unable to load specified CA cert /etc/prometheus/certs/secret__metricsbeattls_domain.pem: open /etc/prometheus/certs/secret__metricsbeattls_domain.pem: no such file or directory"
level=info ts=2020-10-29T13:07:49.891Z caller=kubernetes.go:263 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2020-10-29T13:07:49.892Z caller=kubernetes.go:263 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=error ts=2020-10-29T13:07:49.894Z caller=main.go:646 msg="Error reloading config" err="one or more errors occurred while applying the new configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\")"
level=info ts=2020-10-29T13:07:49.895Z caller=manager.go:924 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-10-29T13:07:49.895Z caller=manager.go:934 component="rule manager" msg="Rule manager stopped"
level=info ts=2020-10-29T13:07:49.896Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."
level=info ts=2020-10-29T13:07:49.896Z caller=main.go:789 msg="Notifier manager stopped"
level=error ts=2020-10-29T13:07:49.896Z caller=main.go:798 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": one or more errors occurred while applying the new configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\")"
```

**Anything else we need to know?**:

The secret created has no data if using  remoteRead 
```
kubectl get secret
NAME                                                                         TYPE                                  DATA   AGE
prometheus-traefik-application10-tls-assets         Opaque                                0        82m
```

If using remoteWrite with same tls certs it is working fine 
example with remoteWrite 
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
spec:
  remoteWrite:
  - queueConfig:
      batchSendDeadline: 5s
      capacity: 499
      maxBackoff: 100ms
      maxSamplesPerSend: 100
      maxShards: 999
      minBackoff: 30ms
      minShards: 1
    remoteTimeout: 10s
    tlsConfig:
      ca:
        secret:
          key: <some name>.pem
          name: <some name>
      cert:
        secret:
          key: <some name>.pem
          name: <some name>
      insecureSkipVerify: true
      keySecret:
        key: <some name>.key
        name: <some name>
```

It may be  because the [AddTLSConfig](https://github.com/prometheus-operator/prometheus-operator/blob/v0.43.0/pkg/prometheus/operator.go#L1429) check is added for [RemoteWrite](https://github.com/prometheus-operator/prometheus-operator/blob/v0.43.0/pkg/prometheus/operator.go#L1425) and the same check is not added for [RemoteRead](https://github.com/prometheus-operator/prometheus-operator/blob/v0.43.0/pkg/prometheus/operator.go#L1419) section 
The AddTLSConfig  block should be present for both RemoteRead and RemoteWrite just like AddBasicAuth block.

Please consider this bug in next release. Thank you
