### ISSUE TITLE
Prometheus isn't discovering PodMonitors.

### ISSUE THREAD

**Issue by radinv** [prometheus-operator/prometheus-operator#3636]
**What did you do?**
I create Prometheus and PodMonitor for exporter in different namespace. I'l expecting see endpoint in targets.

* Prometheus Operator version:

    quay.io/coreos/prometheus-operator:v0.38.1
    

* Kubernetes version information:

Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

It is GKE 

* Manifests:

prometheus.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prom-elastic
  labels:
    app: prom-elastic
    release: prom-elastic
spec:
  replicas: 1
  portName: web
  serviceAccountName: prom-elastic
  serviceMonitorSelector:
    matchLabels:
      release: prom-elastic
  podMonitorSelector:
    matchLabels:
      release: prom-elastic
  additionalScrapeConfigs:
    name: config-prom-elastic
    key: config-prom-elastic.yaml
  retention: 7d
  ruleSelector:
    matchLabels:
      app: prometheus-operator
      release: prom-elastic
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 30Gi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
```
podmonitor.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: elastic-exporter
  namespace: monitoring
  labels:
    release: prom-elastic
spec:
  podMetricsEndpoints:
  - interval: 5s
    port: tcpmetric
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: elastic-exporter
```
exporter.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-exporter
spec:
  selector:
    matchLabels:
      app: elastic-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: elastic-exporter
    spec:
      containers:
        - name: elk-elasticsearch-exporter
          image: justwatch/elasticsearch_exporter:1.0.2
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
          ports:
           - containerPort: 9108
             name: tcpmetric
             protocol: TCP
          args: ["***"]
```

rbac.yaml
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prom-elastic
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prom-elastic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prom-elastic
subjects:
- kind: ServiceAccount
  name: prom-elastic
  namespace: prometheus
```

* Prometheus Operator Logs:
Not about problems with PodMonitor
```
E1030 08:59:02.635676       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.g
o:317: Failed to list *v1.ThanosRuler: the server could not find the requested resource (get thanosrulers.m
onitoring.coreos.com)
```

**Anything else we need to know?**:
I have identical configs for another Prometheus and PodMonitor instance, and it work correctly. 

How I can debug this?

**Comment by brancz** [comment]
cc @dgrisonnet

**Comment by dgrisonnet** [comment]
Hi @radinv, your problem seems to be coming from a namespace selector misconfiguration. You mentioned that your Prometheus instance and your PodMonitor are in different namespaces; however, in your Prometheus manifest, you don't set the `podMonitorNamespaceSelector` value. As per the [API documentation](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec), this means that Prometheus will only discover the PodMonitors present in its own namespace. To fix that, you could either specify the list of namespaces of your PodMonitors or an empty list to discover PodMonitors from all namespaces.

The problem reported in the logs doesn't seem to be related to this exact issue you have with PodMonitors. Could you check that the thanosrulers CRD exists in your cluster? It is normally created by the operator during startup, do you by any chance deleted it or run the operator with the `-manage-crds=false` flag?

**Comment by brpaz** [comment]
I am getting the same problem. The operator is not even detecting ServiceMonitors from helm charts like ingress-nginx, so I guess it´s not a problem of the ServiceMonitor definition per see, but some issue or missing configuration from the operator itself.

According to the logs, The Operator is looking into all namespaces, but it´s finding any Pod or Service monitor. Note that I am using the kube-prometheus helm chart to install the operator. I could open an issue there if you think it´s more appropriate

```
level=debug ts=2020-11-29T11:38:46.894696215Z caller=operator.go:1584 component=prometheusoperator msg="filtering namespaces to select ServiceMonitors from" namespaces=kube-public,local-path-storage,postgres,kube-node-lease,kube-system,ingress,monitoring,podinfo,cert-manager,default,flux-system namespace=monitoring prometheus=prometheus-operator-kube-p-prometheus
level=debug ts=2020-11-29T11:38:46.901466393Z caller=operator.go:1645 component=prometheusoperator msg="selected ServiceMonitors" servicemonitors=monitoring/prometheus-operator-kube-p-prometheus,monitoring/prometheus-operator-kube-p-kube-proxy,monitoring/prometheus-operator-kube-p-node-exporter,monitoring/prometheus-operator-kube-p-grafana,monitoring/prometheus-operator-kube-p-kubelet,monitoring/prometheus-operator-kube-p-operator,monitoring/prometheus-operator-kube-p-coredns,monitoring/prometheus-operator-kube-p-kube-state-metrics,monitoring/prometheus-operator-kube-p-apiserver,monitoring/prometheus-operator-kube-p-alertmanager namespace=monitoring prometheus=prometheus-operator-kube-p-prometheus
level=debug ts=2020-11-29T11:38:46.901651251Z caller=operator.go:1680 component=prometheusoperator msg="filtering namespaces to select PodMonitors from" namespaces=ingress,kube-public,local-path-storage,postgres,kube-node-lease,kube-system,flux-system,monitoring,podinfo,cert-manager,default namespace=monitoring prometheus=prometheus-operator-kube-p-prometheus
level=debug ts=2020-11-29T11:38:46.901725047Z caller=operator.go:1733 component=prometheusoperator msg="selected PodMonitors" podmonitors= namespace=monitoring prometheus=prometheus-operator-kube-p-prometheus
level=debug ts=2020-11-29T11:38:46.901821851Z caller=operator.go:1768 component=prometheusoperator msg="filtering namespaces to select Probes from" namespaces=flux-system,monitoring,podinfo,cert-manager,default,ingress,kube-public,local-path-storage,postgres,kube-node-lease,kube-system namespace=monitoring prometheus=prometheus-operator-kube-p-prometheus
level=debug ts=2020-11-29T11:38:46.901901881Z caller=operator.go:1780 component=prometheusoperator msg="selected Probes" probes= namespace=monitoring prometheus=prometheus-operator-kube-p-prometheus
```

One interesting thing, regarding the nginx-ingress service monitor. Their chart allows to specify the namespace where the monitor will be installed. I set it to the monitoring namespace and even so was not detected by Prometheus.

**Comment by muffl0n** [comment]
I'm also facing this issue and tried the following example:
nginx-deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
```
nginx-podmonitor.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx
spec:
  podMetricsEndpoints:
    - interval: 15s
      port: "9402"
  selector:
    matchLabels:
      app: nginx
```

I created both in the namespace "kube-prometheus-stack" where the prometheus-operator is running. The operator sees a change but does not pick up the PodMonitor I created
```
kube-prometheus-stack-operator-6d6c849c7c-vvtr2 kube-prometheus-stack level=debug ts=2021-03-11T11:14:43.310314962Z caller=operator.go:723 component=prometheusoperator msg="PodMonitor updated"
kube-prometheus-stack-operator-6d6c849c7c-vvtr2 kube-prometheus-stack level=debug ts=2021-03-11T11:14:43.44008134Z caller=operator.go:1726 component=prometheusoperator msg="filtering namespaces to select PodMonitors from" namespaces=goldpinger,default,kube-prometheus-stack,kube-external-secrets,kube-node-lease,kube-public,kube-system,cert-manager,configconnector-operator-system,cnrm-system,ingress-nginx namespace=kube-prometheus-stack prometheus=kube-prometheus-stack-prometheus
kube-prometheus-stack-operator-6d6c849c7c-vvtr2 kube-prometheus-stack level=debug ts=2021-03-11T11:14:43.440121573Z caller=operator.go:1779 component=prometheusoperator msg="selected PodMonitors" podmonitors= namespace=kube-prometheus-stack prometheus=kube-prometheus-stack-prometheus
```

I know that scraping port 9402 makes no sense in this example. But the PodMonitor should be selected and configured nonetheless.

Is there any possibility to debug this even further? 

I installed the stack via Helm chart "kube-prometheus-stack-14.0.1". 
Operator version is "quay.io/prometheus-operator/prometheus-operator:v0.46.0"

**Comment by muffl0n** [comment]
Nevermind! `probeSelectorNilUsesHelmValues` was set to true and so
```
  podMonitorSelector:
    matchLabels:
      release: {{ $.Release.Name | quote }}
```
was added, resulting in
```
   probeSelector:
     matchLabels:
       release: "kube-prometheus-stack"
```

So either setting `prometheus.prometheusSpec.probeSelectorNilUsesHelmValues` to false or defining an own   `prometheus.prometheusSpec.podMonitorSelector.matchLabels` like so
```
prometheus:
  prometheusSpec:
    podMonitorSelector:
      matchLabels:
        foo: bar
```
helps.

Other solution would be to add this label to the PodMonitor
```
  labels:
    release: kube-prometheus-stack
```
