### ISSUE TITLE
Alertmanager templates not being created in pods

### ISSUE THREAD

**Issue by PSjoe** [prometheus-operator/prometheus-operator#3650]
**What did you do?**
I've created a secret for AlertManager configs as follows

```
kubectl get secret/alertmanager-monitor2-kube-prometheus-s-alertmanager -o yaml
apiVersion: v1
data:
  alertmanager.yaml:  <alertmanger configs redacted>
  slack_templates.tmpl: e3sgZGVmaW5lICJzbGFjay5wdXJlc3Rha2UudGl0bGUiIH19W3t7IC5TdGF0dXMgfCB0b1VwcGVyIH19e3sgaWYgZXEgLlN0YXR1cyAiZmlyaW5nIiB9fTp7eyAuQWxlcnRzLkZpcmluZyB8IGxlbiB9fXt7IGVuZCB9fV0ge3sgLkdyb3VwTGFiZWxzLlZhbHVlcyB8IGpvaW4gIiAiICB9fXt7IGVuZCB9fQoKe3sgZGVmaW5lICJzbGFjay5wdXJlc3Rha2UudGV4dCIgfX0Ke3sgcmFuZ2UgLkFsZXJ0cyB9fQogICAgKkFsZXJ0Oioge3sgLkFubm90YXRpb25zLnN1bW1hcnkgfX0gLSBge3sgLkxhYmVscy5zZXZlcml0eSB9fWAKICAgICpEZXNjcmlwdGlvbjoqIHt7IC5Bbm5vdGF0aW9ucy5tZXNzYWdlIH19e3sgLkFubm90YXRpb25zLmRlc2NyaXB0aW9uIH19CiAgICAqRGV0YWlsczoqCiAgICAgIOKAoiAqUnVuYm9vazoqIHt7IC5Bbm5vdGF0aW9ucy5ydW5ib29rX3VybCB9fSB7eyAuQW5ub3RhdGlvbnMucnVuYm9vayB9fQogICAgICDigKIgKlN0YXJ0VGltZToqIGB7eyAuU3RhcnRzQXQgfX1gCiAgICB7eyByYW5nZSAuTGFiZWxzLlNvcnRlZFBhaXJzIH19ICDigKIgKnt7IC5OYW1lIH19OiogYHt7IC5WYWx1ZSB9fWAKICAgIHt7IGVuZCB9fQogIHt7IGVuZCB9fQp7eyBlbmQgfX0gIyBzbGFjay5wdXJlc3Rha2UudGV4dA==
kind: Secret
metadata:

```

**Did you expect to see some different?**
I expected to see a slack_templates.tmpl file in the same directory on the pod as `alertmanager.yaml` appears.  I can verify that any changes I make to `alertmanager.yaml` are showing up in the file in the pod and showing up in the AlertManger GUI.  To me, this confirms that it _is_ using this secret.

According to this, it should create the additional '.tmpl' files along with `alertmanager.yaml`: 

https://github.com/prometheus-operator/prometheus-operator/blob/release-0.43/Documentation/user-guides/alerting.md

**Environment**

* Prometheus Operator version:

```
Name:                   monitor2-kube-prometheus-s-operator
Namespace:              default
CreationTimestamp:      Wed, 04 Nov 2020 22:06:41 +0000
Labels:                 app=kube-prometheus-stack-operator
                        app.kubernetes.io/managed-by=Helm
                        chart=kube-prometheus-stack-11.0.0
                        heritage=Helm
                        prometheus=monitor2
                        release=monitor2
Annotations:            deployment.kubernetes.io/revision: 2
                        meta.helm.sh/release-name: monitor2
                        meta.helm.sh/release-namespace: default
Selector:               app=kube-prometheus-stack-operator,release=monitor2
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=kube-prometheus-stack-operator
                    chart=kube-prometheus-stack-11.0.0
                    heritage=Helm
                    prometheus=monitor2
                    release=monitor2
  Service Account:  monitor2-kube-prometheus-s-operator
  Containers:
   kube-prometheus-stack:
    Image:      quay.io/prometheus-operator/prometheus-operator:v0.43.0
    Port:       8443/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/monitor2-kube-prometheus-s-kubelet
      --logtostderr=true
      --localhost=127.0.0.1
      --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.43.0
      --config-reloader-cpu=100m
      --config-reloader-memory=25Mi
      --web.enable-tls=true
      --web.cert-file=cert/cert
      --web.key-file=cert/key
      --web.listen-address=:8443
    Environment:  <none>
    Mounts:
      /cert from tls-secret (ro)
  Volumes:
   tls-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  monitor2-kube-prometheus-s-admission
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   monitor2-kube-prometheus-s-operator-584c4c5888 (1/1 replicas created)
Events:          <none>
```

* Kubernetes version information:

` GitVersion:"v1.18.8-eks-7c9bda`

* Kubernetes cluster kind:

Using AWS EKS v 1.18

**Anything else we need to know?**:

This has been working with 0.42.0.

Not sure if it's related, but there are two alertmanager secrets:  
```
kubectl get secrets | grep alert
alertmanager-monitor2-kube-prometheus-s-alertmanager              Opaque                                2      17m
alertmanager-monitor2-kube-prometheus-s-alertmanager-generated    Opaque                                1      18m
alertmanager-monitor2-kube-prometheus-s-alertmanager-tls-assets   Opaque                                0      17h
monitor2-kube-prometheus-s-alertmanager-token-67mzc               kubernetes.io/service-account-token   3      17h
```

The one that ends in "-generated' has the correct `alertmanager.yaml` data in it, but _not_ the second `slack_templates.tmpl` data.
