### ISSUE TITLE
Add some sort of spell checking to the CI

### ISSUE THREAD

**Issue by invidian** [prometheus-operator/prometheus-operator#3654]
**Why do we need it?**

To make reviewers life easier and to keep code quality at high level, I suggest we add some automatic spell checking as part of CI process, to ensure less typos end up getting merged.

This has been discussed in #3653 

Sample implementation using Github Actions and codespell could look like:
```yaml
  codespell:
    runs-on: ubuntu-latest
    name: Codespell
    steps:
    - uses: actions/checkout@v2
    - name: codespell
      uses: codespell-project/actions-codespell@master
      with:
        skip: .git,*.png,main,./go.sum
        ignore_words_list: ba,dedup
        check_filenames: true
        check_hidden: true
```

_simonpasquier's edit: updated the link to the PR which was incorrect_
