### ISSUE TITLE
Multiple label matcher refused by admission webhook

### ISSUE THREAD

**Issue by lbesson-della** [prometheus-operator/prometheus-operator#3661]
**What did you do?**
Create a PrometheusRule with a multi label matcher expression, e.g. `http_requests_total{job="prometheus",group="canary"}`

The rule is refused by the admission webhook "prometheusrulemutate.monitoring.coreos.com" denied the request: Rules are not valid

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

v0.38.1

* Kubernetes version information:

   $ kubectl version                                                                                                                                                                                                                              
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/am
d64"}                                                                                                                                                                                                                                          
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/
amd64"}                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                               

* Kubernetes cluster kind:

    The cluster is managed via terraform, the prometheus oeprator is installed with helm

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: myservice.rules
  namespace: default
  labels:
    prometheus: kube-prometheus
spec:
  groups:
  - name: myservice-metric
    rules:
    - record: myservice_metric
      expr: rabbitmq_queue_messages{queue="myservice",job="prometheus-rabbitmq-exporter-0"}
      labels:
        namespace: default
        service: rabbitmq
```

* Prometheus Operator Logs:

I've found nothing relevant in the logs

* Anything else?

If I keep only one label, everything works fine
