### ISSUE TITLE
[alertmanagerconfig] routes field gets empty when applied to cluster

### ISSUE THREAD

**Issue by shibumi** [prometheus-operator/prometheus-operator#3688]
**What happened?**

When I apply the following configuration via helm the `routes:` field is suddenly empty on the cluster:

```yaml

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: foo
  labels:
    release: prometheus-stack
  namespace: foo
spec:
  receivers:
    - name: foo-msteams
      webhookConfigs:
        - url: "http://prometheus-msteams:2000/foo"
          sendResolved: true
  route:
    groupBy: [...]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: foo-msteams
    routes:
    - receiver: foo-msteams
      matchers:
      - name: customer
        value: foo
```

The applied version looks like this: `kubectl describe alertmanager`:
```
Name:         foo
Namespace:    foo
Labels:       app.kubernetes.io/managed-by=Helm
              release=prometheus-stack
Annotations:  meta.helm.sh/release-name: hfoo
              meta.helm.sh/release-namespace: foo
API Version:  monitoring.coreos.com/v1alpha1
Kind:         AlertmanagerConfig
Metadata:
  Creation Timestamp:  2020-11-17T13:52:03Z
  Generation:          3
  Resource Version:    94280348
  Self Link:           /apis/monitoring.coreos.com/v1alpha1/namespaces/hs-schraeder/alertmanagerconfigs/hs-schraeder
  UID:                 2f18718e-e0e8-4f24-a101-1ae4d619d1e0
Spec:
  Receivers:
    Name:  foo-msteams
    Webhook Configs:
      Send Resolved:  true
      URL:            http://prometheus-msteams:2000/foo
  Route:
    Group By:
      ...
    Group Interval:   5m
    Group Wait:       30s
    Receiver:         foo-msteams
    Repeat Interval:  12h
    Routes:
Events:  <none>
```

This leads to this error message here:
```
component=alertmanageroperator msg="skipping alertmanagerconfig" error="receiver \"\" not found" alertmanagerconfig=foo/foo namespace=monitoring alertmanager=prometheus-stack-kube-prom-alertmanager
```
**Did you expect to see something different?**

I expect that the routes section gets deployed, too.

**How to reproduce it (as minimally and precisely as possible)**:

Copy my YAML and remove the helm go templates...

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.43.`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-15T17:26:49Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

    insert how you created your cluster: Rancher
