### ISSUE TITLE
AlertmanagerConfig and  Alertmanager's alertmanager.yaml  not match！！！

### ISSUE THREAD

**Issue by GuobingLiu** [prometheus-operator/prometheus-operator#3699]
**What did you do?**
```
[root@master alerting]# cat alertmanager-config-example.yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'wechat-example'
  receivers:
  - name: 'wechat-example'
    weChatConfigs:
    - apiURL: 'http://wechatserver:8080/'
      corpID: 'wechat-corpid'
      apiSecret:
        name: 'wechat-config'
        key: 'apiSecret'

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: wechat-config
data:
  apiSecret: d2VjaGF0LXNlY3JldAo=

[root@master alerting]# cat alertmanager-selector-example.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: example
spec:
  replicas: 3
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: example
```
automate secret `alertmanager-example-generated` content：
```
alertmanager.yaml: cm91dGU6CiAgcmVjZWl2ZXI6ICJudWxsIgogIHJvdXRlczoKICAtIHJlY2VpdmVyOiBkZWZhdWx0LWNvbmZpZy1leGFtcGxlLXdlY2hhdC1leGFtcGxlCiAgICBncm91cF9ieToKICAgIC0gam9iCiAgICBtYXRjaDoKICAgICAgbmFtZXNwYWNlOiBkZWZhdWx0CiAgICBjb250aW51ZTogdHJ1ZQogICAgZ3JvdXBfd2FpdDogMzBzCiAgICBncm91cF9pbnRlcnZhbDogNW0KICAgIHJlcGVhdF9pbnRlcnZhbDogMTJoCnJlY2VpdmVyczoKLSBuYW1lOiAibnVsbCIKLSBuYW1lOiBkZWZhdWx0LWNvbmZpZy1leGFtcGxlLXdlY2hhdC1leGFtcGxlCnRlbXBsYXRlczogW10K
```
convert to text:
```
 echo -n 'cm91dGU6CiAgcmVjZWl2ZXI6ICJudWxsIgogIHJvdXRlczoKICAtIHJlY2VpdmVyOiBkZWZhdWx0LWNvbmZpZy1leGFtcGxlLXdlY2hhdC1leGFtcGxlCiAgICBncm91cF9ieToKICAgIC0gam9iCiAgICBtYXRjaDoKICAgICAgbmFtZXNwYWNlOiBkZWZhdWx0CiAgICBjb250aW51ZTogdHJ1ZQogICAgZ3JvdXBfd2FpdDogMzBzCiAgICBncm91cF9pbnRlcnZhbDogNW0KICAgIHJlcGVhdF9pbnRlcnZhbDogMTJoCnJlY2VpdmVyczoKLSBuYW1lOiAibnVsbCIKLSBuYW1lOiBkZWZhdWx0LWNvbmZpZy1leGFtcGxlLXdlY2hhdC1leGFtcGxlCnRlbXBsYXRlczogW10K'|base64 -d
route:
  receiver: "null"
  routes:
  - receiver: default-config-example-wechat-example
    group_by:
    - job
    match:
      namespace: default
    continue: true
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
receivers:
- name: "null"
- name: default-config-example-wechat-example
templates: []
```
I can't find default-config-example-wechat-example,  what does it  mean？ 

**Environment**

* Prometheus Operator version:
v0.43.2
* Kubernetes version information:
v18.3
* Kubernetes cluster kind:
kubeadm
