### ISSUE TITLE
`--dry-run=server` support in admission webhook

### ISSUE THREAD

**Issue by hmlkao** [prometheus-operator/prometheus-operator#3704]
**What is missing?**
Admission webhook doesn't support `--dry-run=server`

**Why do we need it?**
To check Prometheus rules over `--dry-run=server` to be sure that Prometheus rule syntax is correct before deployment.

* Prometheus Operator version:
    `quay.io/coreos/prometheus-operator:v0.38.1`
* Kubectl version:
    `v1.19.4`

**Issue example**
```
cat invalid-prom-rule.yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: main
    role: alert-rules
  name: invalid-rule-dev-rules
spec:
  groups:
  - interval: 60s
    name: dev
    rules:
    - alert: InvalidPrometheusRule
      annotations:
        summary: This is invalid test alert
      expr: prometheus_build_info{version~=".*"}
      for: 10m
      labels:
        severity: "3"
```

```
$ kubectl apply -f invalid-prom-rule.yaml --dry-run=server
Error from server (BadRequest): error when creating "invalid-prom-rule.yaml": admission webhook "prometheusrulemutate.monitoring.coreos.com" does not support dry run
```
