### ISSUE TITLE
prometheus and alertmanager's node-selector set by prometheus-operator

### ISSUE THREAD

**Issue by FarnazZ** [prometheus-operator/prometheus-operator#3708]
Is is possible to set `node-selector` of prometheus and alertmanager by the operator to make them to deploy on specific nodes without specify it in their own manifests?

**What did you do?**
I try to add below part to prometheus-operator:
```
prometheus:
        service:
          clusterIP: ""
          type: ClusterIP
          port: 9090
          targetPort: 9090
        prometheusSpec:
          nodeSelector:
            node-role.kubernetes.io/compute: "true"
      alertmanager:
        alertmanagerSpec:
          nodeSelector:
            node-role.kubernetes.io/compute: "true"  
```

**Did you expect to see some different?**

I expected to see that all resources start recreating and migrating to specified nodes and the `node-selector` added to their `StatefulSet`

**Environment**
* Openshift: 3.11
* Prometheus Operator version: v0.43.2

**Anything else we need to know?**:
I know you've mentioned that  v0.43.2 of the operator is not supported for OpenShift 3.11,  I changed the api version and  made a couple of changes in the `crds` and now it become compatible,
I want to check that I am making mistake or the reason am facing this issue is  the version that this option is not supported in our environment.

**Comment by paulfantom** [comment]
nodeSelector is Prometheus CRD and it is part of PrometheusSpec. More in https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec

**Comment by paulfantom** [comment]
Closing as the issue appears to be answered. If you need additional clarification, please reopen it.

**Comment by gomin1d** [comment]
Solution for statufulsets alertmanager-kube-prometheus-stack-alertmanager and prometheus-kube-prometheus-stack-prometheus: 

```
prometheus:
  prometheusSpec:
    nodeSelector:
      'kubernetes.io/hostname': 'host1.example.local'
alertmanager:
  alertmanagerSpec:
    nodeSelector:
      'kubernetes.io/hostname': 'host1.example.local'
```
