### ISSUE TITLE
How to integration with PushProx

### ISSUE THREAD

**Issue by Alanthur** [prometheus-operator/prometheus-operator#3709]
Hi,I use prometheus operator,but I do not know how to integration with pushProx?
How do I configure the prometheus operator to integration with pushProx?
Any help is appreciate

**Comment by paulfantom** [comment]
The integration with pushprox is done the same way as with other applications exposing a Service. After you deployed pushprox and created a Service for it, you need to add a ServiceMonitor which will be picked up by prometheus-operator to configure prometheus. More on the topic in https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md

**Comment by Alanthur** [comment]
@paulfantom But the ServiceMonitor is not have 'static_configs'.The pushprox needs 'static_configs' for presuming the FQDN of the client is "client".

**Comment by paulfantom** [comment]
In that case you can configure it with `additionalScrapeConfigs` in [PrometheusSpec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec)

**Comment by Alanthur** [comment]
@paulfantom But the 'additionalScrapeConfigs' needs 'job_name'. And the ServiceMonitor is not have 'job_name'.
So I configure prometheus-additional.yaml
`- job_name: kubesphere-monitoring-system/node-exporter/edge
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  proxy_url: http://10.233.56.173:8080/
  static_configs:
    - targets: ['pushprox-client-5947cc99bb-q7v97:9100']`
Then I update the secret.
But the prometheus can not read the proxy.
![QQ截图20201125112028](https://user-images.githubusercontent.com/9957813/100179213-7727a080-2f10-11eb-9881-24f2047c6a04.png)

**Comment by paulfantom** [comment]
As far as I can see without knowing your setup network topology everything is ok apart from your `targets`. Since `additionaScrapeConfigs` are including raw prometheus config, it doesn't know anything about k8s objects. For this reason, anything you put into `targets` needs to be reachable from prometheus pod. Is `pushprox-client-5947cc99bb-q7v97:9100` an address that is reachable from prometheus?

**Comment by Alanthur** [comment]
@paulfantom The targets is not reachable  from prometheus pod.But the proxy_url is reachable from prometheus pod.
My network topologies:
![20201126091320](https://user-images.githubusercontent.com/9957813/100296691-e01e1f80-2fc7-11eb-8dc0-9295dfda024a.png)
The prometheus can access proxy_url but not the targets.So if the prometheus would like to access targets, it has to access to proxy_url. I understand right?

**Comment by xichengliudui** [comment]
Has been fixed.
due to custom configuration

**Comment by xichengliudui** [comment]
/reopen
I'm sorry，wrong PR reply

**Comment by WLBF** [comment]
> @paulfantom The targets is not reachable from prometheus pod.But the proxy_url is reachable from prometheus pod. My network topologies: ![20201126091320](https://user-images.githubusercontent.com/9957813/100296691-e01e1f80-2fc7-11eb-8dc0-9295dfda024a.png) The prometheus can access proxy_url but not the targets.So if the prometheus would like to access targets, it has to access to proxy_url. Do I understand right?

yes you are right, I run pushprox-client as sidecar like:
```yaml
      containers:
        - name: pushprox
          image: prometheuscommunity/pushprox-linux-amd64:master
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - "/app/pushprox-client"
          args:
            - "--proxy-url=http://192.168.0.14:8080"
            - "--fqdn=$(MY_POD_IP)"
            - "--metrics-addr=':8080'"
            - "--log.level=debug"
```
and config `proxy_url` in service monitor, doc: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint. It works well.
