### ISSUE TITLE
any way to disable sync prometheus configuration?

### ISSUE THREAD

**Issue by dorsany** [prometheus-operator/prometheus-operator#3725]
**What did you do?**
I have changed some flags in the Prometheus  `statefuleset` resource, in my case: `kubectl -n monitoring edit statefulsets.apps prometheus-kube-prometheus-stack-prometheus` and after 2 seconds the `prometheus-operator` synced back to the original configuration as mentioned  in the `README.md`:
> The Prometheus operator automatically detects changes in the Kubernetes API server to any of the above objects, and ensures that matching deployments and configurations are kept in sync.

**Did you expect to see some different?**
There is any way to disable this sync? 

some advantages to support it :
- test some new `prometheus` flags from new versions
- change some values that hard coded, so we can test those new values before reporting about an issue (like change this flag`--storage.tsdb.max-block-duration=30m`)

**Environment**
bare metal

* Prometheus Operator version:
    `Insert image tag or Git SHA here`
    
chart version: version: 12.3.0
app version: 0.43.2

* Kubernetes version information:

    `kubectl version`
    
k8s 1.17
* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.
k3s
* Manifests:
from  helm chart

* Prometheus Operator Logs:

```
level=info ts=2020-12-06T10:59:30.572756799Z caller=operator.go:1145 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus-stack-prometheus
level=info ts=2020-12-06T10:59:30.744241351Z caller=operator.go:1145 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus-stack-prometheus
level=info ts=2020-12-06T10:59:30.817349659Z caller=operator.go:1145 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus-stack-prometheus
level=info ts=2020-12-06T10:59:30.854421614Z caller=operator.go:1145 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus-stack-prometheus
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
What you can do is override the containers as generated by the operator using the `spec.containers` field. See more in the [API docs](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec).

> Containers allows injecting additional containers or modifying operator generated containers. This can be used to allow adding an authentication proxy to a Prometheus pod or to change the behavior of an operator generated container. Containers described here modify an operator generated container if they share the same name and modifications are done via a strategic merge patch. The current container names are: prometheus, config-reloader, and thanos-sidecar. Overriding containers is entirely outside the scope of what the maintainers will support and by doing so, you accept that this behaviour may break at any time without notice.

**Comment by simonpasquier** [comment]
other than that you can scale down the operator to 0 and override the statefulset definition as you wish.

**Comment by dorsany** [comment]
> What you can do is override the containers as generated by the operator using the `spec.containers` field. See more in the [API docs](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec).
> 
> > Containers allows injecting additional containers or modifying operator generated containers. This can be used to allow adding an authentication proxy to a Prometheus pod or to change the behavior of an operator generated container. Containers described here modify an operator generated container if they share the same name and modifications are done via a strategic merge patch. The current container names are: prometheus, config-reloader, and thanos-sidecar. Overriding containers is entirely outside the scope of what the maintainers will support and by doing so, you accept that this behaviour may break at any time without notice.

Hi @simonpasquier , if I'll use `prometheus.prometheusSpec.containers` it will add additional container, but it won't change the `prometheus` container itself.
no way to override the `command` or `args` of the `prometheus` container?

> other than that you can scale down the operator to 0 and override the statefulset definition as you wish.

I actually want to avoid from that, since it will consider as a friction which I'll have to maintain to be identical to the original `prometheus` statefulset

**Comment by coderanger** [comment]
>  if I'll use prometheus.prometheusSpec.containers it will add additional container, but it won't change the prometheus container itself.

It will, it's a keyed array and the extra config is deep-merged with an understanding of that.

**Comment by dorsany** [comment]
work like a charm! 
thanks a lot @coderanger 

example:
```
prometheus:
  ...
  prometheusSpec:
    ...
    containers:
    - name: prometheus
      args:
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--config.file=/etc/prometheus/config_out/prometheus.env.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=60d"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.no-lockfile"
      - "--web.enable-admin-api"
      - "--web.external-url=http://foo.local/"
      - "--web.route-prefix=/"
      - "--storage.tsdb.min-block-duration=30m"
      - "--storage.tsdb.max-block-duration=30m"
```
