### ISSUE TITLE
AlertmanagerConfig - Opsgenie Responder

### ISSUE THREAD

**Issue by Whyeasy** [prometheus-operator/prometheus-operator#3726]
**What happened?**

Hi I'm switching towards the new AlertmanagerConfig CRD, but when I try to configure Opsgenie responders I get the following error: `OpsGenieConfig responder {   } has to have at least one of id, username or name specified"`.

I tried it with different values for responders:

```yaml
responders:
-  name: "{{ if .CommonLabels.responder }}{{ .CommonLabels.responder }}{{ else }}sre{{ end }}"
    type: team
```
and
``` yaml
responders:
-  name: sre
    type: team
```

Both with the same result.

**Did you expect to see something different?**

That the Opsgenie responder will be configured within Alertmanager.

**How to reproduce it (as minimally and precisely as possible)**:

Providing a `opsgenieConfigs.responders` object within the CRD.

**Environment**

* Prometheus Operator version:

    Release 0.44 deployed via kube-prometheus helm chart. CRDs are updated to the latest 0.44 release.

* Kubernetes version information:

    1.17

* Kubernetes cluster kind:

    GKE

* Prometheus Operator Logs:

Operator logs are fine, this the full Alertmanager line.
```
level=error ts=2020-12-07T15:35:55.895Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="OpsGenieConfig responder {   } has to have at least one of id, username or name specified"
```

**Comment by jaredstehler** [comment]
seeing the same; looks like the rendered config.yml looks like: 
```
    responders:
    - {}
    - name: ops
      type: team
```

**Comment by simonpasquier** [comment]
Can you share the generated Alertmanager config as well as the full AlertmanagerConfig definition? Something like `kubectl get secrets <generated secret> -o json | jq '.data["alertmanager.yaml"]' | base64 -d -`.

**Comment by Whyeasy** [comment]
AlertmanagerConfig:
```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
  labels:
    alertmanagerconfig: enabled
spec:
  route:
    receiver: opsgenie
    groupWait: 30s
    groupInterval: 15m
    repeatInterval: 15m
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            value: Watchdog
          - name: namespace
            value: kube-system|default
            regex: true
          - name: alertname
            value: KubeCPUOvercommit|PrometheusRuleFailures|KubeVersionMismatch
            regex: true
  receivers:
    - name: "null"
    - name: opsgenie
      opsgenieConfigs:
        - sendResolved: true
          apiKey:
            name: alertmanager-config
            key: KEY
          apiURL: https://api.eu.opsgenie.com/
          priority: '{{ range .Alerts }}{{ if not .Labels.responder }}P3{{ else if eq .Labels.severity "critical" }}P1{{ else if eq .Labels.severity "warning" }}P3{{ else }}P5{{ end }}{{ end }}'
          message: "{{ .CommonLabels.alertname }} ({{ .CommonLabels.cluster }}:{{ .CommonLabels.region }})"
          description: '{{ template "opsgenie.default.description" . }}'
          source: '{{ template "opsgenie.default.source" . }}'
          tags: "{{ .CommonLabels.app }},{{ .CommonLabels.cluster }},{{ .CommonLabels.namespace }},{{ .CommonLabels.region }}"
          responders:
            - type: "team"
              name: "sre"
```

generated Alertmanager configuration:

```yaml
ydHMgfX17eyBpZiBub3QgLkxhYmVscy5yZXNwb25kZXIgfX1QM3t7IGVsc2UgaWYgZXEgLkxhYmVscy5zZXZlcml0eSAiY3JpdGljYWwiIH19UDF7eyBlbHNlIGlmIGVxIC5MYWJlbHMuc2V2ZXJpdHkgIndhcm5pbmciIH19UDN7eyBlbHNlIH19UDV7eyBlbmQgfX17eyBlbmQgfX0nCnRlbXBsYXRlczogW10K | base64 -d      
global:
  resolve_timeout: 5m
route:
  receiver: "null"
  group_by:
  - job
  routes:
  - receiver: monitoring-alertmanager-opsgenie
    match:
      namespace: monitoring
    continue: true
    routes:
    - receiver: monitoring-alertmanager-null
      match:
        alertname: Watchdog
      match_re:
        alertname: KubeCPUOvercommit|PrometheusRuleFailures|KubeVersionMismatch
        namespace: kube-system|default
    group_wait: 30s
    group_interval: 15m
    repeat_interval: 15m
  - receiver: "null"
    match:
      alertname: Watchdog
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: "null"
- name: monitoring-alertmanager-null
- name: monitoring-alertmanager-opsgenie
  opsgenie_configs:
  - send_resolved: true
    api_key: ba58564d-5e11-43e5-ad40-abd8a57ee149
    api_url: https://api.eu.opsgenie.com/
    message: '{{ .CommonLabels.alertname }} ({{ .CommonLabels.cluster }}:{{ .CommonLabels.region }})'
    description: '{{ template "opsgenie.default.description" . }}'
    source: '{{ template "opsgenie.default.source" . }}'
    responders:
    - {}
    - name: sre
      type: team
    tags: '{{ .CommonLabels.app }},{{ .CommonLabels.cluster }},{{ .CommonLabels.namespace }},{{ .CommonLabels.region }}'
    priority: '{{ range .Alerts }}{{ if not .Labels.responder }}P3{{ else if eq .Labels.severity "critical" }}P1{{ else if eq .Labels.severity "warning" }}P3{{ else }}P5{{ end }}{{ end }}'
templates: []
```

Just as @jaredstehler mentioned, seems there is an empty `{ }` generated.
