### ISSUE TITLE
Why does alertmanagerconfigs automatically add a namespace matcher

### ISSUE THREAD

**Issue by snuggie12** [prometheus-operator/prometheus-operator#3733]
**What did you do?**
I created an `AlertmanagerConfig` and noticed it is adding a matcher for `namespace`. Is there some way to turn this off? What if there is no namespace label? What if the namespace is under a different label? What if I want it to be for all namespaces?

**Did you expect to see some different?**
I think I sort of understand why this exists, but curious if there's any way to turn this off.

**Environment**

* Prometheus Operator version:

    `v0.44.0`

* Kubernetes version information:

    `v1.16.15-gke.4300`

* Kubernetes cluster kind:

    gke using terraform

* Manifests:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: blackhole
  namespace: monitoring
spec:
  receivers:
  - name: blackhole
  route:
    matchers:
    - name: severity
      value: info
    receiver: blackhole
```

* Prometheus Operator Logs:

**Anything else we need to know?**:
```
# Config that is generated by CR:
  - receiver: monitoring-blackhole-blackhole
    match:
      namespace: monitoring
      severity: info
    continue: true
```
