### ISSUE TITLE
Sharing the /prometheus directory with a prometheus-operator sidecar

### ISSUE THREAD

**Issue by jamesla** [prometheus-operator/prometheus-operator#3735]
I am trying to deploy the prometheus operator with a sidecar that has the /prometheus volume mounted. I've been through the docs but struggling to see how to achieve this.

The closest I have got is the following however this gives me an error around the rest of the required volumes not being mounted.

```
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 100Gi
  containers:
  - name: stackdriver-sidecar
    image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.8.0
    imagePullPolicy: Always
    args:
    - --stackdriver.project-id={{.Values.project}}
    - --prometheus.wal-directory=/prometheus/wal
    - --stackdriver.kubernetes.location={{.Values.region}}
    - --stackdriver.kubernetes.cluster-name={{.Values.clusterName}}
    - --include=nginx_http_requests_total
    volumeMounts:
    - name: prometheus
      mountPath: /prometheus
  volumes:
  - name: prometheus
    persistentVolumeClaim:
      claimName: prometheus-prometheus-db-prometheus-prometheus-0
```

The error is

```
Unable to attach or mount volumes: unmounted volumes=[prometheus-prometheus-db], unattached volumes=[prometheus config-out tls-assets prometheus-prometheus-db prometheus-prometheus-rulefiles-0 prometheus-token-vxxkm config]: timed out waiting for the condition
```

So I considered creating each of these as `emptydir` volumes but it isn't possible to create the prometheus-token-xxxx name is dynamically generated. I feel like I am doing something wrong.

How can I deploy prometheus and expose it's /prometheus directory to it's sidecar using the prometheus operator?
