### ISSUE TITLE
Make AlertManagerConfig namespace label matching optional / configurable

### ISSUE THREAD

**Issue by bshifter** [prometheus-operator/prometheus-operator#3737]
It is a great thing that we have a validated alertmanager config with possible runtime reconfiguration. It’s much safer than the Helm chart values and easy to manage from 3rd parties.

However there are use-cases where the namespace restriction is not handy:

1. If an alert doesn't have a namespace label. There are already a couple of alerts (maybe from aggregated metrics) that have no namespace labels. In this case none of the alertmanager config will apply to them.
2. Global Kubernetes alerts, where namespace can be anything including future namespaces.
3. External alerts (outside of Kubernetes cluster) where namespace is not applicable at all.

Proposed solution
- Possible attribute to ignore namespace labels
- A singleton global configuration (maybe cluster scoped?)

We are happy to help with the implementation if we have a consensus about the issue.

**Comment by brancz** [comment]
> A singleton global configuration (maybe cluster scoped?)

We haven't done a great job at documenting this, but the secret where we previously configured the entire Alertmanager configuration, still works, and can be used to configure exactly this. I do think though that this is a sub-par experience. I would suggest that we embed an AlertmanagerConfig in the Alertmanager object, where no namespace enforcement is applied. What do you think?

**Comment by bshifter** [comment]
Thank you for the hint, let me take a closer look on the details!

**Comment by tarokkk** [comment]
An AlertmanagerConfig under the Alertmanager object seems reasonable. I really like that we don't have to use raw secret so the input is validated against the Alertmanager config schema ;) Thank you for the quick answer

**Comment by kragniz** [comment]
>I would suggest that we embed an AlertmanagerConfig in the Alertmanager object, where no namespace enforcement is applied. What do you think?

That would be great.

**Comment by buckner** [comment]
Having the choice to disable the namespace label matching would be immensely helpful.

Would embedding an AlertmanagerConfig in the Alertmanager object result in rolling the alertmanager pod(s) on change? An attribute that disables namespace label matching would allow me to deploy a single global AlertmanagerConfig and take advantage of the config-reloader sidecar.

**Comment by simonpasquier** [comment]
I agree that it's a valid request. The primary use case for AlertmanagerConfig was to offer self-service configuration of Alertmanager. That's why the initial implementation didn't change anything wrt the global Alertmanager configuration.

Instead of embedding, maybe we could have a reference to the `AlertmanagerConfig` resource in the same namespace? Especially since AlertmanagerConfig is v1alpha1.

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: example
spec:
  ...
  alertmanagerConfig: example
```

**Comment by shinebayar-g** [comment]
Having ability to disable namespace injection is really needed. Widely used [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus) alerts don't have any namespace labels for example.

**Comment by juris** [comment]
Yes, please! Blackbox probe metrics do not have namespace labels as well.

**Comment by hoffoo** [comment]
also summary for alerts do not have label either, for alert expressions such as sum() > 5 avg() and absent() dont work via this method either

**Comment by joshuasimon-taulia** [comment]
is there a workaround for this in the meantime? even hardcoding the namespace in the `matcher` doesn't work for me:
```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ include "thanos-operator.fullname" . }}-receivers
  labels:
    alertmanagerConfig: {{ include "thanos-operator.fullname" . }}
spec:
  route:
    receiver: victorops-test-prometheus
    matchers:
      - name: namespace
        value: integration
        regex: false
      - name: container
        value: yolo-prometheus-exporter
        regex: false
```
results in
```yaml
route:
  routes:
  - receiver: monitor-thanos-operator-receivers-victorops-test-prometheus
    match:
      container: yolo-prometheus-exporter
      namespace: monitor
    continue: true
```

child routes seem unaffected, but that's a super ugly workaround.

**Comment by eddycharly** [comment]
@joshuasimon-taulia why don't you create it in the `integration` namespace directly ?

**Comment by joshuasimon-taulia** [comment]
the above was intended to be deployed in my `thanos-operator` chart in the `monitor` namespace. i was reluctant to package a victorops receiver in each application chart and instead wanted to create 1 reusable victorops reciever to rule them all. this isn't currently possible since the respective receiver is only reference-able from within the `AlertmanagerConfig` CR object

**Comment by gmedders** [comment]
In our use case, we have many kubernetes clusters with their own prometheus instances. The namespaces are globally unique ids, and alerts are labeled with the namespace. Each of those prometheus instances sends the alerts to a common alertmanager instance.

Because the namespace labels on the alerts generated from the (remote) promtheus instances don't match the alertmanager namespace, the alerts aren't routed to the receiver due to the namespace mismatch. Unfortunately, most of those decisions aren't in my control so we're sort of stuck in this situation.

I know you all are trying to juggle a bunch of use cases. This is a great project though, and I'd love to be able to use it (e.g., through the flexibility that #3821 provides).

**Comment by freefood89** [comment]
I think there is a workaround for those who are stuck on this. I have a PodMonitor in namespace `monitoring`, monitoring a Pod in namespace `flux`, with a PrometheusRule in namespace `platform`:

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux
  namespace: platform
spec:
  groups:
  - name: flux.rules
    rules:
    - alert: FluxSyncError
      expr: delta(flux_daemon_sync_duration_seconds_count{success='true'}[6m]) < 1
      annotations:
        description: Usually means there are some problems with infrastructure or there are manifests parse error or there are manifests with duplicate ids.
      labels:
        severity: critical
        namespace: platform
 ...
```

I also have a PodMonitor in namespace `platform` monitoring a Pod in namespace `helmoperator` with PrometheusRule in namespace `platform`:

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: helmoperator
  namespace: platform
spec:
  groups:
  - name: helmoperator.rules
    rules:
    - alert: HelmOperatorLowThroughput
      expr: flux_helm_operator_release_queue_length_count > 0
      for: 30m
      labels:
        severity: warning
        namespace: platform
```

<img width="1166" alt="Screen Shot 2021-02-05 at 1 50 09 PM" src="https://user-images.githubusercontent.com/1236436/107100644-dedc5080-67c9-11eb-9dae-62887cb8df9f.png">

It's terrible but it works..

**Comment by simonpasquier** [comment]
@gmedders can you share how your central Alertmanager configuration looks like today? I would assume that you've got an alert routing tree based on some label identifying the originating cluster?

I'm all for making the feature useful for more people, just want to understand better the use cases :)

**Comment by bhvishal9** [comment]
This feature would also help us a lot, we have a situation where we have one namespace per application and we do not want to create `AlertManagerConfig` resource in each of those namespaces which are owned by different teams. Having it defined globally works perfect for us.

**Comment by gmedders** [comment]
> @gmedders can you share how your central Alertmanager configuration looks like today? I would assume that you've got an alert routing tree based on some label identifying the originating cluster?
> 
> I'm all for making the feature useful for more people, just want to understand better the use cases :)

Hey @simonpasquier sorry for the delayed response. Our config is similar to this
```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.alertmanager.replicas }}
  externalUrl: https://{{ .Values.alertmanager.hostname }}/alertmanager
  routePrefix: /alertmanager
  logLevel: debug
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: {{ .Release.Name }}
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ .Release.Name }}
  annotations:
    description: Config for alertmanager
  labels:
    alertmanagerConfig: {{ .Release.Name }}
spec:
  route:
    globalConfig: true # this is temporarily using https://github.com/prometheus-operator/prometheus-operator/pull/3821. Will update to whatever the recommended practice is 
    groupBy:
      - namespace # this is our globally unique id
    matchers:
      - name: handle
        regex: false
        value: "true"
    groupWait: 5s
    groupInterval: 5s
    repeatInterval: 15m
    receiver: handler
  receivers:
  - name: handler
    webhookConfigs:
    - url: 'https://handler'
      sendResolved: false
```
This has been working for our use case, but I'm definitely open to any options that satisfy our constraints (i.e., single alertmanager fed by many remote prometheus instances whose `namespace` label values are globally unique ids). Thanks so much!

**Comment by simonpasquier** [comment]
thanks @gmedders 

If I understand correctly, your Alertmanager routing tree is relatively simple and static. If it were possible to define the "global" `AlertmanagerConfig` in the `Alertmanager` resource as described [here](https://github.com/prometheus-operator/prometheus-operator/issues/3737#issuecomment-749570549), you would be able to accomplish the same thing?

**Comment by gmedders** [comment]
Hey @simonpasquier. Yes, our routing tree is definitely simple and more-or-less static (in the sense of: it may change over time and we'd want Alertmanager to reload the config at runtime, but that's it). So if we can accomplish the same thing via a global `Alertmanagerconfig` in the `Alertmanager`, that'd be great!

**Comment by eddycharly** [comment]
This would be quite usefull, in our use case, we want a catch-all route.

**Comment by eddycharly** [comment]
Maybe a `ClusterAlertmanagerConfig` CRD ?

**Comment by brancz** [comment]
Not sure where the other thread is right now, but there is another thread going on this topic, and the latest idea is to embed an AlertmanagerConfig object into the Alertmanager config that will never have enforcement applied exactly for this catch-all use case. If it turns out there is a large use case for having distributed non-enforced configs then we can look into that afterwards (my feeling is that this is probably unsafe to do as it can accidentally swallow notifications).

**Comment by mmerrill3** [comment]
wow, didn't expect to come across this behavior.  My main use case was for secrets as well, but we have alerts that trigger our monitoring vendor across "all" namsepaces, simply by having a label on the route.  I have hundreds of namespaces, and I don't want to have to make hundreds of alertManagerConfig CRDs.  Yeah, it would be nice to be able to disable the match against the object's namespace in the top level route.

**Comment by brancz** [comment]
Implementation is in progress to allow this https://github.com/prometheus-operator/prometheus-operator/pull/3821

**Comment by simonpasquier** [comment]
_Recap after discussing the topic on the [#prometheus-operator-dev](https://kubernetes.slack.com/archives/C01B03QCSMN/p1615539203010100) Slack channel with @brancz_ 
 
1. We should extend the `Alertmanager` spec so it can hold a reference (by name) to the root `AlertmanagerConfig` resource + fields for the global and template parameters. 

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: example
spec:
  ...
  alertmanagerConfig:
    name: example # name of the top-level AlertmanagerConfig in the same namespace
    global: {...} # hash of global settings
    templates: [...] # list of template paths
```

If defined, it would be used to generate the base Alertmanager config instead of the existing `configSecret` field. The operator wouldn't add any namespace matcher for the routes defined by this AlertmanagerConfig. It would also have to exclude the top-level AlertmanagerConfig when collecting the user-defined AlertmanagerConfig resources.
=> AFAICT it would solve most of the use cases: many asks are about leveraging secret references to avoid storing sensitive data into the main config secret, not so much about splitting the top-level Alertmanager config into N pieces.

2. A further improvement would be to add an `enforcedNamespaceLabel` flag to the `Alertmanager` CRD that enables/disables the namespace enforcement in the routing tree for user-defined `AlertmanagerConfig` resources as well as a way to exclude enforcement for some AlertmanagerConfig resources if namespace enforcement is enabled (this would be consistent with the `enforcedNamespaceLabel` and `prometheusRulesExcludedFromEnforce` fields from the Prometheus CRD). Whether namespaces are enforced or not, all first level routes would be set with `continue: true` to make sure that alerts are evaluated by all AlertmanagerConfigs.
