### ISSUE TITLE
How to hide my ServiceMonitor

### ISSUE THREAD

**Issue by juewu4072** [prometheus-operator/prometheus-operator#3738]
**What did you do?**
There is an old Prometheus operator, which is provided by another company and has the right to discover ServiceMonitor under all my namespaces.

There are some valuable indicators that are not allowed to be seen except the boss,
So I made a new prometheus-operator in kubernetes.
My question, how to hide my ServiceMonitor in the new namespace and be discovered by the old prometheus-operator?

I try to delete clusterrole

``` 
- apiGroups:
  - monitoring.coreos.com
 resources:
  - alertmanagers
  - alertmanagers/finalizers
  - prometheuses
  - prometheuses/finalizers
  - thanosrulers
  - thanosrulers/finalizers
  - servicemonitors
  - podmonitors
  - probes
  - prometheusrules
  verbs:
  - '*' 
```

it does't work .I am troubled
