### ISSUE TITLE
AlertmangerConfig doesn't validate when routes do not specify a receiver

### ISSUE THREAD

**Issue by jutley** [prometheus-operator/prometheus-operator#3748]
**What happened?**

When I applied an AlertmanagerConfig with nested routes, where non-leaf routes do not contain a receiver, this error appears in the logs.

```
level=warn ts=2020-12-17T17:51:06.668951195Z caller=operator.go:890 component=alertmanageroperator msg="skipping alertmanagerconfig" error="route[0]: receiver \"\" not found" alertmanagerconfig=prometheus/alertmanager-cluster namespace=prometheus alertmanager=alertmanager-cluster
```

For reference, here is a very simplified version of our real routing tree. Note that there are multiple intermediate routes that do not have a receiver, which is valid in vanilla Prometheus.

```
route:
  receiver: default
  routes:
    - matchers:
        - name: alert_owner
          value: '.+'
          regex: true
      routes:
        - matchers:
            - name: alert_owner
              value: 'platform'
          routes:
            - matchers:
                - name: severity
                  value: warning
              receiver: 'platform-warning'
            - matchers:
                - name: severity
                  value: critical
              receiver: 'platform-critical'
```

**Did you expect to see something different?**

I expected the configuration to successfully be validated. The API spec clearly states
> The field can be omitted only for nested routes otherwise it is mandatory.

**How to reproduce it (as minimally and precisely as possible)**:

From what I can tell, all that is necessary is to define a route without a receiver. This snippet of code seems to suggest this.

https://github.com/prometheus-operator/prometheus-operator/blob/v0.44.1/pkg/alertmanager/operator.go#L1236-L1238

**Environment**

* Prometheus Operator version:

quay.io/prometheus-operator/prometheus-operator:v0.44.1

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
