### ISSUE TITLE
configSecret in alertmanager-alertmanger.yaml is not taking alertmanager-main as a secrete with custom configs

### ISSUE THREAD

**Issue by navneet066** [prometheus-operator/prometheus-operator#3751]
**What happened?**

I am trying to put a custom alertmanager configuration. So I created below `alertmanager-secret.yaml` file. 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "24h"
      "smtp_from": "admin@blabla.com"
      "smtp_smarthost": "smtp.blabla.com:587"
      "smtp_auth_username": "admin@blabla.com"
      "smtp_auth_password": "************"
    "route":
      "group_by": "severity"
      "receiver": "Monitoring-DevOps"
      "group_wait": "30s"
      "group_interval": "5m"
      "repeat_interval": "24h"
      "routes":
      - "receiver": "Monitoring-DevOps"
        "match":
          "alertname": "highmem_slave"
          "team": "ITD"
    "receivers":
    - "name": "Monitoring-DevOps"
      "email_configs":
      - "to": "'someemail@blabla.com'"
        "headers":
          "subject": "'[{{ .Status | toUpper }}] | {{ .CommonLabels.environment}} | {{ .CommonLabels.alertname }} | {{ .CommonLabels.instance }}'"
        "send_resolved": "true"
type: Opaque
```

```bash
❯ kubectl get secret -n monitoring
NAME                              TYPE                                  DATA   AGE
additional-scrape-configs         Opaque                                1      40h
alertmanager-main                 Opaque                                1      70m
alertmanager-main-generated       Opaque                                1      71m
alertmanager-main-tls-assets      Opaque                                0      71m
alertmanager-main-token-x7zwj     kubernetes.io/service-account-token   3      41h

```

along with this, I modified the `alertmanager-alertmanager.yaml` to take the config as stated in this [doc](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/alerting.md):

below is the `alertmanager-alertmanager.yaml` where I have referenced `configSecret`

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  image: quay.io/prometheus/alertmanager:v0.21.0
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 3
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: example
  configSecret: alertmanager-main
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: v0.21.0

```

**Did you expect to see something different?**

Accoriding to the doc, when I will apply this configuration, it should take this as alertmanagr configuration, But it is taking values from secret called `alertmanager-main-generated`

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.44.1`
    

* Kubernetes version information:

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    Using Kubespray

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
