### ISSUE TITLE
E-mail alerting not working if configured through AlertmanagerConfig

### ISSUE THREAD

**Issue by TamasNeumer** [prometheus-operator/prometheus-operator#3756]
**What happened?**

I wanted to configure e-mail notification for the Alertmanager component using the new AlertmanagerConfig CRD. Our setup looks the following:

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    alertmanagerConfig: "example"
spec:
  route:
    groupBy: ["alertname"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: "default_channel"
    routes:
      - matchers:
          - name: namespace
            value: xxx-.*
            regex: true
        receiver: "xxx_email"
  receivers:
    - name: "xxx_email"
      emailConfigs:
        - to: "xxx@gmail.com"
          from: "xxxr@gmail.com"
          smarthost: "smtp.gmail.com:587"
          authUsername: "xxx@gmail.com"
          authPassword:
            name: gmail-auth
            key: password
          authIdentity: "xxx@gmail.com"
```

The AlertmanagerConfig was picked up correctly. The secret referrenced by `authPassword` was found. (No error-logs in prometheus-operator. I specifically tested this functionality of the operator - when I referenced an invalid secret I saw error logs...)

I was expecting to get e-mail notifications.

I tested the same configuration when feeding it as a k8s secret. In this case the password was hard-coded, but the rest of the configuration was the same. The e-mail functionality worked.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ["alertname"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: "default_channel" # Our default channel
      routes:
        - match_re:
            namespace: xxx-.*
          receiver: "xxx_email"
    receivers:
      - name: "xxx_email"
        email_configs:
          - to: xxx@gmail.com
            from: xxx@gmail.com
            smarthost: smtp.gmail.com:587
            auth_username: xxx@gmail.com
            auth_identity: xxx@gmail.com
            auth_password: xxx
            send_resolved: true
type: Opaque
```

**Did you expect to see something different?**

I expected the e-mail sending to work. Even when switching to debug log level I didn't see anything in the prometheus-operator or the alertmanager logs. 

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy the kube-prometheus stack
- Make sure that the CRD-based alertmanager configuration is enabled and the config is picked up
- Port-forward the alertmanager and send an alert to it. => Check if e-mail arrives

**Prometheus Operator version:** v0.44.1

**Kubernetes version information:**
- Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3"
- Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0"

**Kubernetes cluster kind:**
- Minikube
