### ISSUE TITLE
New Rules (kind: PrometheusRule) aren't discovered by the prometheus 

### ISSUE THREAD

**Issue by surensinghkhatana** [prometheus-operator/prometheus-operator#3767]
**What happened?**
 New rules of _kind: PrometheusRule_ aren't discovered by the prometheus server
 
**Did you expect to see something different?**
  Rules should be visible in the prometheus UI

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new PrometheusRule and deploy it in the same namespace as the operator
2.  Check if those are visible in the prometheus UI or not

**Environment**

* Prometheus Operator version:
  `quay.io/prometheus-operator/prometheus-operator:v0.44.0`

* Kubernetes version information:
 `Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.13", GitCommit:"4c00c3c459261e8ff3381c1070ddf798f0131956", GitTreeState:"clean", BuildDate:"2020-12-09T11:09:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
`

* Kubernetes cluster kind:
 microk8s

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
    role: server-rules
  name: server-up-time
  namespace: monitoring
spec:
  groups:
    - name: server-rules
      rules:
        - alert: server down
          annotations:
            description: server is down !
            summary:  test.
          expr: probe_success{job="monitoring/probe-server"} == 0
          for: 1m
          labels:
            severity: critical

```
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/managed-by: Helm
    chart: kube-prometheus-stack-12.8.1
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-prometheus
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: prometheus-kube-prometheus-alertmanager
      namespace: monitoring
      pathPrefix: /
      port: web
  enableAdminAPI: false
  externalUrl: http://prometheus-kube-prometheus-prometheus.monitoring:9090
  image: quay.io/prometheus/prometheus:v2.22.1
  listenLocal: false
  logFormat: logfmt
  logLevel: debug
  paused: false
  podMonitorSelector:
    matchLabels:
      release: prometheus
  portName: web
  probeSelector:
    matchLabels:
      release: prometheus
  replicas: 1
  retention: 10d
  routePrefix: /
  ruleSelector:
    matchLabels:
      app: kube-prometheus-stack
      release: prometheus
      role: server-rules
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-kube-prometheus-prometheus
  serviceMonitorSelector:
    matchLabels:
      release: prometheus
  version: v2.22.1

```

**Comment by surensinghkhatana** [comment]
Also, my rule is not available in the configMap `prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0` and as a consequence of that, it is not available inside the pod too.

Any idea what is needed for the `PrometheusRule` CR object to end up in the rulefiles configMap ?

**Comment by surensinghkhatana** [comment]
Noticed following error in the logs :
```
k -n monitoring logs -f prometheus-prometheus-kube-prometheus-prometheus-0 -c config-reloader                                                                                                                              ○ microk8s surendra.khatana@gluu 22:36:55
level=info ts=2021-01-01T20:36:11.733543254Z caller=main.go:147 msg="Starting prometheus-config-reloader" version="(version=0.44.0, branch=refs/tags/pkg/apis/monitoring/v0.44.0, revision=35c9101c332b9371172e1d6cc5a57c065f14eddf)"
level=info ts=2021-01-01T20:36:11.733594705Z caller=main.go:148 build_context="(go=go1.14.12, user=paulfantom, date=20201202-15:44:08)"
level=info ts=2021-01-01T20:36:11.733762722Z caller=main.go:182 msg="Starting web server for metrics" listen=:8080
**level=error ts=2021-01-01T20:36:11.812072421Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": dial tcp 127.0.0.1:9090: connect: connection refused"**
level=info ts=2021-01-01T20:36:16.898771813Z caller=reloader.go:347 msg="Reload triggered" cfg_in=/etc/prometheus/config/prometheus.yaml.gz cfg_out=/etc/prometheus/config_out/prometheus.env.yaml watched_dirs=/etc/prometheus/rules/prometheus-prometheus-kube-promethe
us-prometheus-rulefiles-0
level=info ts=2021-01-01T20:36:16.89883366Z caller=reloader.go:214 msg="started watching config file and directories for changes" cfg=/etc/prometheus/config/prometheus.yaml.gz out=/etc/prometheus/config_out/prometheus.env.yaml dirs=/etc/prometheus/rules/prometheus-
prometheus-kube-prometheus-prometheus-rulefiles-0

```

**Comment by surensinghkhatana** [comment]
Tried running it on a new EKS cluster, same issue

**Comment by simonpasquier** [comment]
:wave: I suspect that it's due of the `ruleSelector` definition:

```
  ruleSelector:
    matchLabels:
      app: kube-prometheus-stack
      release: prometheus
      role: server-rules
```

The `server-up-time` rule misses the `app` label.
