### ISSUE TITLE
Failed to create Prometheus service using Additional scraping Configuration

### ISSUE THREAD

**Issue by xichengliudui** [prometheus-operator/prometheus-operator#3775]
**What did you do?**
create Prometheus services
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: inst
  namespace: monitoring
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: example
  alerting:
    alertmanagers:
    - name: alertmanager-example
      namespace: monitoring
      port: web
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  resources:
    requests:
      memory: 400Mi
```

**Did you expect to see some different?**

before i add `additionalScrapeConfigs` can be used normally. but after i added `additionalScrapeConfigs` to apply yaml, i found that not only was pod not created but prometheus StatefulSet was not even created

i followed the documentation: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/additional-scrape-config.md

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    quay.io/prometheus-operator/prometheus-operator:v0.44.1

* Kubernetes version information:

    `kubectl version`
    Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:
kubeadm

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
i am deploying the Prometheus federation
