### ISSUE TITLE
ServiceMonitor namespace selection issue

### ISSUE THREAD

**Issue by you4su** [prometheus-operator/prometheus-operator#3777]
**What happened?**
Adding a new servicemonitor to monitor a custom app does not show up any targets.

**Did you expect to see something different?**
The prometheus UI should show up a new target for the app under `/targets`

**How to reproduce it (as minimally and precisely as possible)**:
Create a service monitor as below for an app exporting prometheus format metrics, and promethus instances through prometheus operator should be running. Below are the yamls I have used. I am using v0.44.1 version of the prometheus operator.

**Environment**
Linux
* Prometheus Operator version:
v0.34.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

    AWS EKS through Terraform

* Manifests:

app.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-app-deployment
  namespace: applications
spec:
  selector:
    matchLabels:
      app: rpc-app
  replicas: 1
  template:
    metadata:
      labels:
        app: rpc-app
    spec:
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsUser: 1000
      containers:
      - name: rpc-app-cont
        image: supergiantkir/prometheus-test-app
        ports:
        - name: web
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: rpc-app-service
  namespace: applications
  labels:
    app: rpc-app
spec:
  ports:
  - name: web
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: rpc-app
```
serviceMonitor.yaml

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rpc-app
  namespace: applications
  labels:
    type: custom-app
spec:
  endpoints:
  - interval: 15s
    port: web
  selector:
    matchLabels:
      app: rpc-app
```
prometheus.yaml

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    kubernetes.io/os: linux
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.11.0
```

* Prometheus Operator Logs:

```

Ideally the above prometheus object should select the servicemonitor I created in applications ns based on the values `serviceMonitorNamespaceSelector: {}`  and `serviceMonitorSelector: {}` and the `/targets` should show up un the prometheus UI but it is not showing up that target even through my lables and selectors seem to be good. One interesting point to not is that if I create the app(meaning deployment and service for the app) and the servicemonitor in the `monitoring` namespace, it works but the servicemonitor and the app are not picked up if created in `applications` namespace, please suggest.
