### ISSUE TITLE
Alertmanager doesn't apply the specified version.

### ISSUE THREAD

**Issue by atomerz** [prometheus-operator/prometheus-operator#3778]
**What happened?**
Specifying `Version` alongside `Image` in `AlertmanagerSpec` has no effect.

**Did you expect to see something different?**
As per documentation, I expected operator to concatenate `Image:Version` when creating the pods.

**How to reproduce it (as minimally and precisely as possible)**:
Apply the following using `kubectl`:
```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  namespace: default
spec:
  replicas: 1
  image: quay.io/prometheus/alertmanager
  version: v0.21.0
```
Use this command to get the image being used in pods:
```
kubectl -n workspace-sample get pod alertmanager-alertmanager-0 -o=jsonpath='{.spec.containers[].image}{"\n"}'
```
The output is:
```
quay.io/prometheus/alertmanager
```
Which uses the latest version.

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.43.2`

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

KinD cluster:
```
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
- role: worker
```

* Manifests:

```
```

* Prometheus Operator Logs:

```
```

**Anything else we need to know?**:
Oddly enough pods created for Prometheus instances apply the version correctly:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prmetheus
  namespace: default
spec:
  replicas: 1
  image: quay.io/prometheus/prometheus
  version: v0.21.0
```
Output of `kubectl -n workspace-sample get pod prometheus-prometheus-0 -o=jsonpath='{.spec.containers[].image}{"\n"}'`:
```
quay.io/prometheus/prometheus:v2.23.0
```
