### ISSUE TITLE
podmonitor scrape target address definition

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [prometheus-operator/prometheus-operator#3786]
**What did you do?**

I've deployed prom-op and some pod with a metrics endpoint, running on hostnetwork
the autogenerated address is the host IP + port

**Did you expect to see some different?**

not necessarily - here's my question: How does the podmonitor decide which address to use for scraping?

My use case / problem is that a pod deployed through another operator (meaning i don't have much control there) is offering metrics, and is running with `hostNetwork: true`,  but there is a firewall between the node it's running on and the node the prometheus is running on, which does not open for the targeted metrics port : /

So now I'm wondering how I might be able to tell the pod monitor to scrape through the pod IP address of the target pod, rather than the node's IP address, even though the target pod happens to run on the node's network.

**Environment**
self-hosted bare-metal k8s cluster + prom-op deployed through manifest files
* Prometheus Operator version:

    `v0.42.0`
    

**Podmonitor manifest**

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  annotations:
  labels:
    k8s-apps: http
  name: generic-pod-monitor
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchExpressions:
    - key: app
      operator: Exists
```

**Comment by paulfantom** [comment]
Relabelling is the way to go here. Possibly the following will work:

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  annotations:
  labels:
    k8s-apps: http
  name: generic-pod-monitor
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - port: metrics
    relabelings:
    - separator: ':'
      sourceLabels:
      - __meta_kubernetes_pod_ip
      - __meta_kubernetes_pod_container_port_number
      targetLabel: __address__
  selector:
    matchExpressions:
    - key: app
      operator: Exists
```

You can check by yourself what `sourceLabels` you need, by going to prometheus instance `/service-discovery` and investigating available discovered labels.
