### ISSUE TITLE
Alertmanager doesn't send alerts while using AlertManagerConfig custom resource

### ISSUE THREAD

**Issue by rjonala** [prometheus-operator/prometheus-operator#3796]
I am running kube-prometheus-stack-11.1.7. When I try to configure alerts using AlertmanagerConfig custom resource object, AlertManager doesn't send alerts to PagerDuty/Slack receiver. I can see alerts being fired in Prometheus/Alertmanager UI but not on PagerDuty/Slack. Here is my AlertmanagerConfig yaml,

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example-pagerduty
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: ['severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: pagerduty
  receivers:
  - name: pagerduty
    pagerdutyConfigs:
    - serviceKey: 
        name: pagerduty-config
        key: apiSecret
​
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pagerduty-config
data:
  apiSecret: <base64 encoded key>
```

Is anything wrong with my config? I don't find any working examples online for PD/Slack. Would be great if someone can provide a working example of AlertmanagerConfig custom resource object for PD and Slack. Thank you.

**Comment by grdryn** [comment]
Hi @rjonala, what does your complete config in alertmanager look like (so that we can see that it got generated properly). Also, does the namespace that this `AlertmanagerConfgi` is in match the namespace of the alerts that are firing (there's implicit namespace matching forced on the route)?

**Comment by rjonala** [comment]
Hi @grdryn Thanks for your response :)

> what does your complete config in alertmanager look like (so that we can see that it got generated properly)

Here is my alertmanager config from `/etc/alertmanager/config/alertmanager.yaml` inside alertmanager Pod.

```
global:
  resolve_timeout: 5m
route:
  receiver: "null"
  group_by:
  - job
  routes:
  - receiver: prometheus-config-example-slack
    group_by:
    - severity
    match:
      namespace: prometheus
    continue: true
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
  - receiver: prometheus-config-example-pagerduty-pagerduty
    group_by:
    - severity
    match:
      namespace: prometheus
    continue: true
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
  - receiver: "null"
    match:
      alertname: Watchdog
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: "null"
- name: prometheus-config-example-slack
- name: prometheus-config-example-pagerduty-pagerduty
templates: []
```
I don't see the **serviceKey** in the config file. Even if I pass **serviceKey** directly from alertmanagerConfig(without using kind:secret), I still don't see it in alertmanager config. Not sure what's the right way though.



> Also, does the namespace that this `AlertmanagerConfgi` is in match the namespace of the alerts that are firing (there's implicit namespace matching forced on the route)?

All the Custom resource objects(Prometheus, Prometheusrules, Alertmanager, AlertmanagerConfig) are running in the same namespace i.e Prometheus namespace.

I am stuck on this issue for a while now. Would really appreciate it if you can guide me through troubleshoot this issue.

**Comment by March-deng** [comment]
Hi @rjonala , it's possibly that your alert being fired did not contain label as "namespace"="prometheus", so it did't match the namespace in alertmanagerconfig.yaml. You can either add a label as "namespace"="prometheus" in your alert metric or prometheus rules.

Also, I'm quite wonder why prometheus-operator decide to add a default namespace matcher in alertmanagerconfig.yaml. @grdryn , It would be great if this can be controlled via a command line flag.

**Comment by simonpasquier** [comment]
@rjonala which operator version are you using? please share the operator's logs too.

@March-deng please see #3737

**Comment by eddycharly** [comment]
@simonpasquier the operator is mounting the secret `alertmanager-kube-prometheus-stack-alertmanager-generated` in the alertmanager pod but only the name of the receivers are kept from the static `alertmanager-kube-prometheus-stack-alertmanager` secret, the other receiver stanzas are not preserved.

for example, in the static secret i have:
```yaml
receivers:
- name: "null"
- name: slack
  slack_configs:
  - api_url: ...
```

and in the generated secret, only the name is kept:
```yaml
receivers:
- name: "null"
- name: slack
- name: core-test-test
```
