### ISSUE TITLE
Probe RelabelConfigs

### ISSUE THREAD

**Issue by EtienneBarbier** [prometheus-operator/prometheus-operator#3809]
**What did you do?**

I'm using prometheus-operator Probe to integrate ipmi-exporter to Prometheus.
https://github.com/soundcloud/ipmi_exporter

```
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  annotations:
    meta.helm.sh/release-name: ipmi-exporter-regionadmin
    meta.helm.sh/release-namespace: monitoring
spec:
  module: default
  interval: 5s
  prober:
    path: /ipmi
    scheme: http
    url: ipmi-exporter-regionadmin:9290
  targets:
    staticConfig:
      static:
      - 10.40.0.11
      - 10.40.0.12
      - 10.40.0.13
      - 10.40.0.14
```
The previous configuration works well, but all targets use the same module and by extension the same user/password to connect to the BMC.

**Did you expect to see some different?**

I want to assign a different module for each target. From the ipmi-exporter documentation we can do it by adding this custom relabeling entry. https://github.com/soundcloud/ipmi_exporter#remote-metrics (end of paragraph)

```
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_module
    replacement: ${1}
    action: replace
``` 

However, there is no field RelabelConfigs for Probe's StaticConfig. So i cannot apply the previous entry.
One more problem, i cannot filter my metrics (drop or keep).
Do you have any idea to solve theses problems ?
Thanks.
 
**Environment**

* Prometheus Operator version:

    `0.42.0`

* Kubernetes version information:

    `1.19.1`
