### ISSUE TITLE
How can i add ETCD cert to Prometheus

### ISSUE THREAD

**Issue by scila1996** [prometheus-operator/prometheus-operator#3815]
Hi ! I was deploy my Kubernetes with Master and ETCD same the node. ETCD configured with TLS Security and i was have cert of them.

1. I created namespace with name 'prom'
2. I added secret with name 'etcd-k8s-cert'

<pre>
kubectl -n prom create secret generic etcd-k8s-cert \
    --from-file=./cafiles/client.crt \
    --from-file=./cafiles/client.key \
    --from-file=./cafiles/ca.crt
</pre>

3. I configured kubeEtcd section in helm values.yaml with following

<pre>
kubeEtcd
  service:
    port: 2379
    targetPort: 2379
    selector:
      component: etcd
  serviceMonitor:
    scheme: https
    insecureSkipVerify: true
    # serverName: etcd-master1
    caFile: /etc/prometheus/secrets/etcd-k8s-cert/ca.crt
    certFile: /etc/prometheus/secrets/etcd-k8s-cert/client.crt
    keyFile: /etc/prometheus/secrets/etcd-k8s-cert/client.key
</pre>

4. I install Prom Operator but ETCD Dashboard have no data !

SO

How can i check secret was added and check ETCD Metrics log ?? How can i debug that or i missed any step ?

Thank !

**Comment by s-urbaniak** [comment]
A first good debugging point is to inspect what the "Targets" pane of Prometheus shows about those endpoints.

**Comment by scila1996** [comment]
Year. I was resolved . I missed a step. Must be add secrets with ETCD certs file to prometheus with config

<pre>
prometheus:
  prometheusSpec:
    # https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec

    secrets:
      - etcd-k8s-cert
</pre>

follow this tutorial

https://banzaicloud.com/docs/bank-vaults/mutating-webhook/howto-ct-prom/#prometheusspec

**Comment by yypastushenko** [comment]
In addition to first comment - how to deliver secret to the cluster.
If you want to act in IAC way or use GitOps approach you can make it like this:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-etcd-certs-to-secret-egress-to-apiserver
spec:
  egress:
  # if your apiserver is a pod - you can specify here the apiserver pod and namespace selector 
  - {}
  podSelector:
    matchLabels:
      app: etcd-certs-to-secret
  policyTypes:
  - Egress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-certs-to-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcd-certs-to-secret
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-certs-to-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-certs-to-secret
subjects:
- kind: ServiceAccount
  name: etcd-certs-to-secret
---
apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-certs-to-secret
spec:
  template:
    metadata:
      labels:
        app: etcd-certs-to-secret
    spec:
      serviceAccountName: etcd-certs-to-secret
      containers:
      - name: apply-secret
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        image: bitnami/kubectl:1.32.0
        command: ["/bin/sh", "-c"]
        args:
          - |
            if [ ! -f /etcd-certs/ca.crt ]; then
              echo "Error: Certificate authority file '/etcd-certs/ca.crt' is missing."
              exit 1
            fi

            if [ ! -f /etcd-certs/tls.crt ]; then
              echo "Error: Certificate file '/etcd-certs/tls.crt' is missing."
              exit 1
            fi

            if [ ! -f /etcd-certs/tls.key ]; then
              echo "Error: Key file '/etcd-certs/tls.key' is missing."
              exit 1
            fi

            kubectl apply -f - <<EOF
            apiVersion: v1
            kind: Secret
            metadata:
              name: etcd-certs
              annotations:
                created-by: job/etcd-certs-to-secret
            type: kubernetes.io/tls
            data:
              ca.crt: $(cat /etcd-certs/ca.crt | base64 -w 0)
              tls.crt: $(cat /etcd-certs/tls.crt | base64 -w 0)
              tls.key: $(cat /etcd-certs/tls.key | base64 -w 0)
            EOF
        volumeMounts:
        - name: ca-crt
          mountPath: /etcd-certs/ca.crt
          readOnly: true
        - name: tls-crt
          mountPath: /etcd-certs/tls.crt
          readOnly: true
        - name: tls-key
          mountPath: /etcd-certs/tls.key
          readOnly: true
      restartPolicy: Never
      tolerations:
      - key: "node-role.kubernetes.io/controlplane"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/etcd"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
      nodeSelector:
        node-role.kubernetes.io/controlplane: "true"
      volumes:
      - name: ca-crt
        hostPath:
          path: /etc/kubernetes/pki/etcd/ca.crt
          type: File
      - name: tls-crt
        hostPath:
          path: /etc/kubernetes/pki/etcd/server.crt
          type: File
      - name: tls-key
        hostPath:
          path: /etc/kubernetes/pki/etcd/server.key
          type: File
  backoffLimit: 4
```
