### ISSUE TITLE
Azure Kubernetes Service (AKS) Virtual Nodes (ACI) are included in the endpoint, causing target failures

### ISSUE THREAD

**Issue by MattJeanes** [prometheus-operator/prometheus-operator#3832]
**What happened?**
The prometheus-operator is creating an Endpoint for metrics scraping against a AKS Virtual Node.

**Did you expect to see something different?**
Metrics scraping does not work on virtual nodes 

**How to reproduce it (as minimally and precisely as possible)**:
- Install kube-prometheus-stack with the AKS virtual nodes feature enabled
- Under prometheus targets, it fails to contact the virtual node for metrics scraping 
- The `kube-prometheus-kubelet` endpoint resource in `kube-system` contains the virtual node when it should not

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.45.0`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"c7c4f6ce84bf8535a782b67465807651a4bd649b", GitTreeState:"clean", BuildDate:"2021-01-18T09:49:05Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

    Azure Kubernetes Service (AKS)

* Manifests:

N/A

* Prometheus Operator Logs:
N/A relevant

**Anything else we need to know?**:
I disabled the node-exporter from attempting deployment to the virtual node with these command line options on the helm install for kube-prometheus-stack:
```
"--set", "prometheus-node-exporter.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key=type", `
"--set", "prometheus-node-exporter.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].operator=NotIn", `
"--set", "prometheus-node-exporter.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values[0]=virtual-kubelet", `
"--set", "prometheus-node-exporter.nodeSelector.`"kubernetes\.io/os`"=linux", `
```

I found the code that gets the nodes to put in the endpoint is here, editing the endpoint manually to remove the virtual node works great but the operator quickly resets it: https://github.com/prometheus-operator/prometheus-operator/blob/v0.45.0/pkg/prometheus/operator.go#L605

**Comment by MattJeanes** [comment]
We're not using virtual nodes anymore but as far as I can tell this is still an issue

**Comment by MattJeanes** [comment]
Cannot confirm if this is still an issue as we no longer use virtual nodes so will give it the benefit of the doubt and assume it is now fixed.

**Comment by tomasfreund** [comment]
Hi, the issue is still present, I have the node-exporter disabled for the virtual nodes as well

**Comment by lokeshm89** [comment]
We are facing this issue in our team.

**Comment by tobimax** [comment]
It's still present on the latest version, in AKS I have to issue the following command for it to ignore the AKS Virtual Node. Even though the AKS Cluster is not enabled for Virtual Nodes.

Is there a way to do this in the values.yaml file?

```bash
helm upgrade --install -f /c/Development/data-admiral-iac-aks/k8s/prometheus/values.yaml prometheus prometheus-community/kube-prometheus-stack -n nelson-sys \
--set prometheus-node-exporter.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key="type" \
--set prometheus-node-exporter.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].operator="NotIn" \
--set prometheus-node-exporter.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values[0]="virtual-kubelet" \
```

**Comment by aravol** [comment]
Just encountered this on our team. Going by the above, moving this into a values.yaml ends up with  the following

```
prometheus-node-exporter:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: type
              operator: NotIn
                values:
                  - virtual-kubelet
```

Noting that the default values.yaml includes `prometheus-node-exporter` but not `affinity`

**Comment by nabladev** [comment]
@aravol That works! But there's an indentation issue: `values` is at the same level as `operator`, the right code is:
```
prometheus-node-exporter:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: type
              operator: NotIn
              values:
                - virtual-kubelet
```
