### ISSUE TITLE
AlertmanagerConfig not working for email and Slack

### ISSUE THREAD

**Issue by SaltedEggIndomee** [prometheus-operator/prometheus-operator#3845]
**What happened?**

- Alerts are not routed and handled by receivers (slackConfigs, emailConfigs). A.k.a I'm not receiving the emails or Slack notifications even after following the CRD specifications by the book.
- Prometheus UI and AlertManager UI are showing that alerts are firing correctly.
- No useful logs (info or error) to debug.
- Using blackbox-exporter manifests from the master branch. The alerts are received on Prometheus and AlertManager so I assume it's compatible with release-0.7.

**Did you expect to see some different?**
I expect at least one of the receivers in AlertmanagerConfig to work, or the error logs indicating the issue.

**How to reproduce it (as minimally and precisely as possible)**:
NOTE: I'm using as much default settings/CRD as I can.

1. Deploy all manifests based on official quickstart instructions, using branch release-0.7
```
kubectl create -f manifests/setup
kubectl create -f manifests/
```
2. Deploy a Probe, (certain info obscured)
```
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: probe-live-websites
  namespace: monitoring
  labels: 
    release: prometheus #
spec:
  jobName: probe-live-websites
  interval: 60s #
  scrapeTimeout: 10s #must be smaller than interval
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115 #
    scheme: http
    path: /probe
  targets:
    staticConfig:
      static:
      - http://mywebsites.domain.mydomain
      - https://mywebsites.domain.mydomain
```

3. Deploy PrometheusRule
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.21.0
    prometheus: k8s
    role: alert-rules
  name: prules-live-websites
  namespace: monitoring
spec:
  groups:
  - name: AllInstances
    rules:
      - alert: InstanceDown
        # Condition for alerting
        expr: probe_success == 0
        for: 1m
        # Annotation - additional informational labels to store more information
        annotations:
          title: 'Instance {{ $labels.instance }} down'
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
        # Labels - additional labels to be attached to the alert
        labels:
          severity: 'critical'
```

4. Deploy AlertmanagerConfig
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-my-new-config
  namespace: monitoring
  labels:
    alertmanagerConfig: "example"
spec:
  route:
    groupBy: ["job"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: "xxx_email"
  receivers:
    - name: "xxx_email"
      emailConfigs:
        - to: "myreceiver@domain.com"
          from: "mysender@domain.com"
          smarthost: "smtp.gmail.com:587"
          authUsername: "mysender@domain.com"
          authPassword:
            name: gmail-secret
            key: password
          authIdentity: "mysender@domain.com"
---
apiVersion: v1
kind: Secret
metadata: 
  name: gmail-secret
  namespace: monitoring
type: Opaque
stringData: 
  password: "xxxyyyzzz"
```

**Environment**
AWS

* Prometheus Operator version:
Using release-0.7 branch as suggested.

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
kubeadm

* Prometheus Operator Logs:
No errors at all.
```
level=info ts=2021-02-17T07:20:44.032253335Z caller=operator.go:661 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2021-02-17T07:25:44.0324413Z caller=operator.go:661 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2021-02-17T07:26:58.030576798Z caller=operator.go:1163 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2021-02-17T07:30:44.032608999Z caller=operator.go:661 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2021-02-17T07:35:44.034171503Z caller=operator.go:661 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
```

* Prometheus Logs:
Nothing much too.
```
level=warn ts=2021-02-17T07:05:11.468Z caller=klog.go:88 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:428: watch of *v1.Pod ended with: an error on the server (\"unable to decode an event from the watch stream: context canceled\") has prevented the request from succeeding"
level=warn ts=2021-02-17T07:05:11.472Z caller=klog.go:88 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:426: watch of *v1.Endpoints ended with: an error on the server (\"unable to decode an event from the watch stream: context canceled\") has prevented the request from succeeding"
level=info ts=2021-02-17T07:05:11.542Z caller=main.go:892 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=119.635629ms remote_storage=2.99µs web_handler=470ns query_engine=1.16µs scrape=23.584875ms scrape_sd=3.838088ms notify=16.77µs notify_sd=1.014772ms rules=80.694852ms
level=info ts=2021-02-17T07:06:33.377Z caller=main.go:861 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2021-02-17T07:06:33.410Z caller=kubernetes.go:263 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-02-17T07:06:33.411Z caller=kubernetes.go:263 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-02-17T07:06:33.412Z caller=kubernetes.go:263 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-02-17T07:06:33.414Z caller=kubernetes.go:263 component="discovery manager notify" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-02-17T07:06:33.500Z caller=main.go:892 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=122.804829ms remote_storage=2.71µs web_handler=590ns query_engine=1.12µs scrape=22.246289ms scrape_sd=3.459043ms notify=18.501µs notify_sd=1.025472ms rules=85.139468ms

```

**Anything else we need to know?**:
As you can see, the alerts are fired and received correctly in Prometheus and AlertManager. There are no obvious errors from the logs too.
![prometheus_fire](https://user-images.githubusercontent.com/49897566/108171725-e9d2a180-7136-11eb-9a46-00215494358d.PNG)
![alertmanager_fire](https://user-images.githubusercontent.com/49897566/108171833-0cfd5100-7137-11eb-8853-7d250989ca0b.PNG)
