### ISSUE TITLE
Manage PodDisruptionBudget objects for alertmanager and prometheus

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#3917]
**What is missing?**

It would be good to have PodDisruptionBudget objects for prometheus and alertmanager pods.

**Why do we need it?**

To ensure better deployment stability.

**Environment**

* Prometheus Operator version: all

**Anything else we need to know?**:

PDB objects were first created in kube-prometheus project in https://github.com/prometheus-operator/kube-prometheus/pull/1035 and improved in https://github.com/prometheus-operator/kube-prometheus/pull/1036. The consensus is that those objects should be managed by the operator due to the possibility of having sharding involved and because those need to be removed when the replica count is changed to 1.

**Comment by lilic** [comment]
Nice, that makes sense! I am guessing just having them be a field for Prometheus and Alertmanager Custom Resources? Can you maybe describe how the spec would look like and we can have someone contribute this, unless you wanted to do it?

**Comment by paulfantom** [comment]
I don't think there is a need for a new field. PDB should be configured when `spec.replicas` is greater than 1 and removed when it is 1 or Prometheus/Alertmanager resource was deleted. As for PDB itself, it is included in links from the issue description.

**Comment by coderanger** [comment]
Playing devils advocate, would there be value in disabling the creation if the user wanted to make a fancier one? I'm struggling to even think of a use case, would have to be something like `replicas: 4` and you want to allow 2 to restart at a time. Or maybe something fancier with the sharding system?

**Comment by lilic** [comment]
Yes exactly unsure about how this would work with the sharding mechanism, @brancz?

**Comment by paulfantom** [comment]
Friendly ping @brancz :)

**Comment by mhowell24** [comment]
@simonpasquier happy to take a stab at this if no-one else already is

**Comment by simonpasquier** [comment]
@mhowell24 please go ahead. On top of my head, there are a few items to clear up before starting the actual work:
* should it be a field in the CRD? how does one opt-out for PDB?
* how does it play with shards?
* how about anti-affinity rules too? though not directly related, they are required to eliminate/minimize service downtime.

**Comment by mhowell24** [comment]
> should it be a field in the CRD? how does one opt-out for PDB?

I think it should be a field on the CRD, most people will probably just want to set `maxUnavailable` to 1 but there might be other times people want to be more adventurous, so maybe we should expose both `maxUnavailable` and `minAvailable`. For opting out we could add an `enabled` flag for people that want to manage their own PDBs.

I think we could use something along the lines of this:

```YAML
podDisruptionBudget:
  enabled: true
  maxUnavailable: 1
``` 

> how does it play with shards?

We would need to create one PDB per shard since we care about the number of replicas getting disrupted per shard not the total number of disruptions across all shards. The PDB settings would be the same for all shards, I don't think it make sense to allow per shard settings. 

> how about anti-affinity rules too? though not directly related, they are required to eliminate/minimize service downtime.

Would it be best to use `topologySpreadConstaraints` if we are looking to spread the pods across failure domains? We could add soft constraints on well-known lables such as `kubernetes.io/hostname` and `topology.kubernetes.io/zone`, these would get added to all STS's that get created, but we would need to give people the ability to control these lables and the constraint settings, so maybe it's best to expose part/all of the `topologySpreadConstaraints` config in the CRD? Something along the lines of:

```YAML
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        operator.prometheus.io/shard: "0"
        prometheus: prom
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        operator.prometheus.io/shard: "0"
        prometheus: prom
```

**Comment by siegenthalerroger** [comment]
I can confirm that the shards part is correct, the per-shard disruption is relevant. Is there already a label for each shard that can be used to group the same shards together?

I can also vouch for the use of topologySpread over antiAffinity, it's more flexible and future proof from our usage.

**Comment by mhowell24** [comment]
> Is there already a label for each shard that can be used to group the same shards together?

yes, I beleive the operator already adds `operator.prometheus.io/shard` labels for sharded setups

**Comment by simonpasquier** [comment]
Thanks! All good input and it would be nice to capture it in a design doc under `Documentation/designs`.

>  maybe it's best to expose part/all of the topologySpreadConstaraints config in the CRD? 

This is already possible. I'm more thinking about a higher-level setting that would do the heavy lifting and configure `topologySpreadConstraints` with sane defaults. Thinking out loud:

```
spec:
  spreadStrategy:
    # type can be:
    # * "Hostname" -> spreading across hosts 
    # * "Zone" -> spreading across hosts + zones
    topology: Hostname
    whenUnsatisfiable: DoNotSchedule # or ScheduleAnyway
```

For people that have more complicated rules, they can still use `spec.topologySpreadConstaraints` directly. The operator could even try to merge it with the constraints generated from `spec.spreadStrategy`.
