### ISSUE TITLE
Istio-proxy sidecar in Prometheus with Prometheus operator

### ISSUE THREAD

**Issue by raz08** [prometheus-operator/prometheus-operator#3926]
I have setup where all the applications are part of Istio service mesh i.e. enabled MTLS with Istio. In this case Prometheus is failing to pull metrics from pod directly because istio proxy running in that pod enforcing client to use certificates and https. 

I tried with adding scheme https and passing certificates through servicemonitor. It is working fine.

But I'm looking for a solution where Prometheus also enabled with Istio mTLS ,for that we should have istio-proxy sidecar running as part of Promethues pod . 

Is this possible with Prometheus operator? Or is there any other possible solutions?

**Comment by simonpasquier** [comment]
Using the [`containers`](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) field of the Prometheus spec, you can inject any container you want to be deployed alongside the Prometheus container.

**Comment by raz08** [comment]
Ok , thanks simonpasquier.

I also tried adding annotation way.
But it is not injecting sidecar with annotations. 

`    annotations:
      sidecar.istio.io/inject: "true"
`
after this i described pod and checked but no sidecar injected. I have istio installed on my cluster.

**Comment by simonpasquier** [comment]
From #3922 and https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings, it seems that Istio doesn't play well with the Prometheus operator but I don't know much more.

**Comment by akhalyavka** [comment]
@raz08 `sidecar.istio.io/inject` annotation has no effect if sidecar injection is not enabled in the namespace. https://istio.io/latest/docs/ops/configuration/mesh/injection-concepts/

**Comment by raz08** [comment]
@simonpasquier I have tried the TLS settings as I mentioned query description and it works. Thank you for the link.

@akhalyavka I have added both namespace label and annotation . But I'm getting psp and security context issues . Trying to fix them. 
So It will work in this approach right? if I'm able to fix the psp issues. IF we have istio-proxy injected successfully will it be able to scrape metrics from mTLS enabled applications?

**Comment by akhalyavka** [comment]
@raz08 Injecting a sidecar is not enough because Istio cannot initiate mTLS on requests destined to pod IP. You're gonna need to use a trick from https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings
Be aware that this trick only works with `ServiceMonitor` - `PodMonitor` does not allow file references in TLS config.

**Comment by akhalyavka** [comment]
Sorry, I re-read your issue and saw that you already tried that. We tried omitting `traffic.sidecar.istio.io/includeInboundPorts: ""` annotation that disables inbound traffic interception and it worked fine, seemingly. 
At least we saw mTLS between grafana and prometheus and could expose prometheus with istio ingressgateway. I can't verify that everything works correctly though because we bailed on running prometheus inside the service mesh.

**Comment by raz08** [comment]
I was able to inject the istio-proxy sidecar and setup ingressgateway to reach Prometheus. 

But still scraping metrics from mTLS enabled applications is failing with 503.

Endpoint | State | Labels | Last Scrape | Scrape Duration | Error
-- | -- | -- | -- | -- | --
http://192.168.49.162:9090/metrics | DOWN |  | 1.265s ago | 2.705ms | server returned HTTP status 503 Service Unavailable

**Comment by raz08** [comment]
Now I'm getting different error.


Endpoint | State | Labels | Last Scrape | Scrape Duration | Error
-- | -- | -- | -- | -- | --
http://192.168.49.162:9090/metrics | DOWN |   | 1.265s ago | 2.705ms | GET "http://192.168.49.162:9090/metrics":EOF

**Comment by TamasNeumer** [comment]
> Now I'm getting different error.
> Endpoint 	State 	Labels 	Last Scrape 	Scrape Duration 	Error
> http://192.168.49.162:9090/metrics 	DOWN 	  	1.265s ago 	2.705ms 	GET "[http://192.168.49.162:9090/metrics":EOF](http://192.168.49.162:9090/metrics%22:EOF)

Any updates / success on this topic?

**Comment by snuggie12** [comment]
You're already looking at the same page I did to get mine working so I'm not sure what is currently wrong since you said scraping is working? Perhaps you're confusing what mTLS is? The setup is still using an official istio cert with mTLS, it's just that the traffic does not get routed through the sidecar.

`Probe` and `PodMonitor` as already mentioned does not work. There are a few issues open about that and hopefully they fix that at some point (btw, for `Probe` that means if you add istio to blackbox exporter you need to disable inbound traffic.)

Here is my working annotations on the prometheus pod:

```
    proxy.istio.io/config: |
      proxyMetadata:
        OUTPUT_CERTS: /etc/istio-output-certs
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/userVolume: '[{"name": "istio-certs", "emptyDir": {"medium":"Memory"}}]'
    sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]'
    traffic.sidecar.istio.io/includeOutboundIPRanges: ""
```

**Comment by cccsss01** [comment]
> 
@snuggie12
The istio documentation only has sidecar.istio.io/userVolumeMount:   listed.  Is their documentation incorrect?

**Comment by snuggie12** [comment]
@cccsss01 I'm not sure why, but it seemingly was removed between 1.8 and 1.9: https://istio.io/v1.8/docs/ops/integrations/prometheus/#tls-settings. I'm speculating, but the tone seems different to me where it later implies however you would make a volume is how you should make one.

That being said, I can confirm it's still a valid annotation (we currently run 1.16,) and is listed as such on the annotations page: https://istio.io/latest/docs/reference/config/annotations/

I've yet to try it myself, but all these problems presumably go away with ambient mesh. I believe it is GA in 1.18 which is due out very soon.

**Comment by cccsss01** [comment]
@snuggie12 Thank you greatly, I can get it working no problem with just prometheus, but converting those configs into prometheus-operator has failed so far. Next attempt is to use the annotations in the prometheus-operator instead of prometheusSpec. 
Likely something like this. https://github.com/prometheus-community/helm-charts/issues/145#issue-709681822

**Comment by snuggie12** [comment]
@cccsss01 I don't quite understand what you mean by `prometheusSpec`. Do you mean the normal prometheus server config file or the `Prometheus` object in the operator api?

It's a long story (unrelated to istio,) but we no longer use the helm chart to deploy the `Prometheus` object itself. That being said it worked prior to us migrating. Our current setup has the following annotations:
```
proxy.istio.io/config: |
  proxyMetadata:
    OUTPUT_CERTS: /etc/istio-output-certs
  sidecar.istio.io/inject: "true" # Mostly leftover from the fact this used to be "false". Some components like kube-state-metrics are still disabled.
  sidecar.istio.io/userVolume: '[{"name": "istio-certs", "emptyDir": {"medium":"Memory"}}]' # [sic] left the inconsistent spacing just in case, but obviously it should just be json
  sidecar.istio.io/userVolumeMount:  '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]'
  traffic.sidecar.istio.io/includeOutboundIPRanges: 10.17.32.0/19 # our Service CIDR. I think this was added when we enabled istio on blackbox-prober?
  traffic.sidecar.istio.io/includeOutboundPorts: "9115" # I think this is blackbox-exporter as well
```

Additionally, there's setup for alertmanager and the prometheus container's volume mount. Here's the actual `Prometheus` object's relevant parts:
```
spec:
  alerting:
    alertmanagers:
      - apiVersion: v2
        name: prometheus-stack-alertmanager
        namespace: monitoring
        pathPrefix: /
        port: http-web
        scheme: https
        tlsConfig:
          caFile: /etc/prom-certs/root-cert.pem
          certFile: /etc/prom-certs/cert-chain.pem
          insecureSkipVerify: true
          keyFile: /etc/prom-certs/key.pem
  volumeMounts:
    - mountPath: /etc/prom-certs/
       name: istio-certs
```

Aside from that:
- alertmanager excludes port 9094
- grafana is sort of a work in progress. It has istio enabled, but it's `Service` port is set to `grafana` and has a `PeerAuthentication` set to `PERMISSIVE`. I think the peer auth is actually cruft from before but it could be related to how we got websockets working for loki live tailing. Istio can't *automatically* handle two protocols using the same container port  so the port can't be http in the istio service catalog. However, just yesterday I got argocd-server to work (it has the same problem except instead of http and non-http tcp it's http and grpc,) using an `EnvoyFilter` which adds a 2nd inbound filter chain and cluster on the other protocol. Grafana will be the next thing I tackle so maybe this will get fixed soon.
- kube-state-metrics and nodeExporter have istio disabled. This isn't to say they will never work, it's just no one has cared enough to revisit them in the past 2 or 3 years since we enabled istio on the `Namespace`.

That's all I could find with a simple grep. If it still doesn't work let me know and I can try to look over all of the kustomize patches in place. There could be some command line arg or something I missed.

We don't merge our metrics btw. I think we had issues with double scrapings or something on certain metrics.
