### ISSUE TITLE
Delete grafana datasource through configuration (configmap)

### ISSUE THREAD

**Issue by jemag** [prometheus-operator/prometheus-operator#3929]
**What did you do?**

- Remove 2 datasources from Grafana datasource config map.
- Restart Grafana pod
- Check if the datasources got deleted within grafana
- Realize datasources are still there

**Did you expect to see some different?**

Datasources to be deleted

**Environment**

* Prometheus Operator version:

    quay.io/prometheus-operator/prometheus-operator:v0.43.2

* Kubernetes version information:

	  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"archive", BuildDate:"2021-01-13T22:07:54Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
	  Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-20T16:22:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

   AKS

* Manifests:
```yaml
apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://kube-prometheus-stack-prometheus:9090/
      access: proxy
      isDefault: true
    - access: proxy
      name: iwls-prometheus
      type: prometheus
      url: http://iwls-prometheus.iwls:9090/
kind: ConfigMap
```
* Datasources

![image](https://user-images.githubusercontent.com/7985687/112161368-756da100-8bc1-11eb-9434-5061b7179b5a.png)

## Questions

1- Is this the expected behavior?
2- If this is the expected behavior, how can we delete datasources through configuration?
