### ISSUE TITLE
Support role service for discovery in probe

### ISSUE THREAD

**Issue by sswieton** [prometheus-operator/prometheus-operator#3931]
**What is missing?**

Support of service role in Probe CRD.
Today, probe CDR supports only static and discovery via ingress. 

**Why do we need it?**

To supervise K8s services using blackbox exporter, and be able to dynamically discover Services.

This is the Job I'd like to build using Probe CR.

    job_name: 'blackbox'
    metrics_path: /probe
    params:
    module: [tcp_connect]
    kubernetes_sd_configs:
    - role: service
    namespaces:
    names:
    - my-namespace
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
    action: keep
    regex: true
    ...
    - source_labels: [__meta_kubernetes_service_label_domain]
    action: keep
    regex: myappli
    - source_labels: [__meta_kubernetes_namespace]
    target_label: address
    replacement: blackbox-exporter:9115 # Blackbox exporter.

**Environment**

* Prometheus Operator version:

Tag 0.46

    `Insert image tag or Git SHA here`
    

**Anything else we need to know?**:

**Comment by viperstars** [comment]
I tried to add this feature. When I started, I found the design of "ProbeTargets" is not abstract enough.

And I think the "ProbeTargets" should be like this:

```go
type ProbeTargets struct {
    StaticConfig *ProbeTargetStaticConfig `json:"staticConfig,omitempty"`
    DynamicConfig *ProbeTargetDynamicConfig `json:"dynamicConfig,omitempty"`
}

type ProbeTargetDynamicConfig struct {
    KubernetesSDRole string `json:"kubernetesSDRole,omitempty"`
    DynamicProbeTarget *DynamicProbeTarget `json:"dynamicProbeTarget,omitempty"`
}

type DynamicProbeTarget struct {
    Selector metav1.LabelSelector `json:"selector,omitempty"`
    NamespaceSelector NamespaceSelector `json:"namespaceSelector,omitempty"`
    RelabelConfigs []*RelabelConfig `json:"relabelingConfigs,omitempty"`
}
```

We can create the "Probe" like this,
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: blackbox-exporter
  name: test
  namespace: monitoring
spec:
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc:8080
  targets:
    dynamicConfig:
      kubernetesSDRole: "service" # or ingress or endpoint?
      dynamicProbeTarget: 
        namespaceSelector:
          any: true
        selector:
          matchLabels:
            probe: enabled
```

Of course we can add the "service" probe just like the "ingress".
```go
type ProbeTargets struct {
	StaticConfig *ProbeTargetStaticConfig `json:"staticConfig,omitempty"`
	Ingress *ProbeTargetIngress `json:"ingress,omitempty"`
	Service *ProbeTargetService `json:"service,omitempty"`
}
```
But it will be hard to config and maintain. 
User can configure both "Ingress" and "Service" in the "ProbeTargets". But the actual targets can be only from one source role.
If we want to add endpoint role support someday, it is not easy to expand.

**Comment by sswieton** [comment]
hi,
Thanks for your quick reply
The solution based on  ProbeTargetDynamicConfig and DynamicProbeTarget
would be really great

The supervision of service with blackbox exporter and a dynamic discovery
of Service is really an important feature for your solution.

Thanks a lot !
best regards
sylvie


Le mer. 24 mars 2021 à 17:47, viperstars ***@***.***> a
écrit :

**Comment by acondrat** [comment]
I was looking to achieve something similar and managed to get it working with `ScrapeConfig` and relabelings. I'll paste the resulting config in case anyone finds it useful. 

```
# Checks if the kubelet port 10255 is open.
# Uses a combination of ScrapeConfig, prometheus-blackbox-exporter and Prometheus Kubernetes Service Discovery.
#
# It discovers the targets using Kubernetes SD and then manipulates the labels in order to build
# scrape targets as per example bellow.
# "http://prometheus-blackbox-exporter.prometheus:9115/probe?module=tcp_port_closed&target=x.x.x.x:10255"
      
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: prometheus-blackbox-exporter-kubelet
  namespace: prometheus
spec:
  kubernetesSDConfigs:
  # The node role discovers one target per cluster node with the address defaulting to the Kubelet's secure port
    - role: Node
  metricsPath: /probe
  params:
    module:
    # Add "module=tcp_port_closed" as a request param
    - tcp_port_closed # this has to be declared in the blackbox exporter
  relabelings:
    # Takes the discovered address that looks like "${ip}:${port}" and turns it into "${ip}:10255" to target the custom port
    - sourceLabels:
        - __address__
      action: replace
      regex: ([^:]+):.*
      replacement: $1:10255
      targetLabel: __address__
    # Add "target=${ip}:10255" as a request param
    - sourceLabels:
        - __address__
      targetLabel: __param_target
    # Use the blackbox-exporter as the endpoint to scrape in Prometheus
    - targetLabel: __address__
      replacement:  prometheus-blackbox-exporter.prometheus:9115
    # Changes below are optional
    # Add port to the instance label
    - sourceLabels:
        - instance
      action: replace
      regex: (.+)
      replacement: $1:10255
      targetLabel: instance
    - action: replace
      replacement: tcp_port_closed
      targetLabel: module
    - sourceLabels:
        - target
      targetLabel: target
      replacement: kubelet
      action: replace    
```
