### ISSUE TITLE
Combined Alertmanager config does not include `match` statements in `AlertmanagerConfig` child routes

### ISSUE THREAD

**Issue by d-m** [prometheus-operator/prometheus-operator#3936]
**What happened?**

We allow teams to create and customize `AlertmanagerConfig` resources in their namespaces so that they can manage their own routing trees. One team attempted to route all `KubeJobFailed` alerts to null, by adding the following to their `AlertmanagerConfig` resource's spec:

```
route:
  ...
  routes:
  - match:
      alertname: KubeJobFailed
    receiver: "null"
  receivers:
  - name: "null"
  ... 
```

When this resource was combined into the Alertmanager config, the `match` section was dropped, resulting in all alerts being routed to the "null" receiver. The same thing happens when using `match_re` instead of `match`.

**Did you expect to see something different?**

I expected the `match` section to be preserved and have all alerts be forwarded to the team's default receiver, with the exception of `KubeJobFailed` alerts. This behavior was verified by checking the routing tree at https://prometheus.io/webtools/alerting/routing-tree-editor/.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `0.45.0`

* Kubernetes version information:

    ```
    Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
    ```

* Kubernetes cluster kind:

    kops

* Manifests:
`Prometheus` resource:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: alertmanager
      namespace: monitoring
      pathPrefix: /
      port: web
  enableAdminAPI: false
  enforcedNamespaceLabel: namespace
  externalUrl: http:/prometheus.monitoring:9090
  image: prometheus/prometheus:v2.24.0
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  portName: web
  probeNamespaceSelector: {}
  probeSelector: {}
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  shards: 1
  version: v2.24.0
```

`Alertmanager` resource:

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
spec:
  alertmanagerConfigNamespaceSelector: {}
  alertmanagerConfigSelector: {}
  externalUrl: http://alertmanager.monitoring:9093
  image: prometheus/alertmanager:v0.21.0
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  portName: web
  replicas: 3
  retention: 120h
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager
  version: v0.21.0
```

Default Alertmanager route:

```
route:
  receiver: default_receiver
  group_by:
  - alertname
  routes:
  - receiver: "null"
    match:
      alertname: Watchdog
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 15m
receivers:
- name: "null"
- name: default_receiver
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://default_receiver/webhook
    max_alerts: 0
```

`AlertmanagerConfig` resource in the `my-namespace` namespace:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: my-alertmanager-config
spec:
  route:
    groupBy: ["alertname"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 15m
    receiver: "webhook"
    routes:
      - match:
          alertname: KubeJobFailed
        receiver: "null"
  receivers:
    - name: "webhook"
      webhookConfigs:
        - url: http://my-webhook/webhook
    - name: "null"
```

Routes in the combined Alertmanager config:

```
route:
  receiver: default_receiver
  group_by:
  - alertname
  routes:
  - receiver: my-namespace-my-alertmanager-config-webhook
    group_by:
    - alertname
    match:
      namespace: my-namespace
    continue: true
    routes:
    - receiver: my-namespace-my-alertmanager-config-null
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 15m
  - receiver: "null"
    match:
      alertname: Watchdog
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 15m
receivers:
- name: "null"
- name: default_receiver
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://default_receiver/webhook
    max_alerts: 0
- name: my-namespace-my-alertmanager-config-null
- name: my-namespace-my-alertmanager-config-webhook
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://my-webhook/webhook
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by fherbert** [comment]
Your alermanagerconfig manifest has invalid route matching, according to the CRD definition
```
kubectl explain alertmanagerconfig.spec.route.matchers
KIND:     AlertmanagerConfig
VERSION:  monitoring.coreos.com/v1alpha1

RESOURCE: matchers <[]Object>

DESCRIPTION:
     List of matchers that the alert’s labels should match. For the first
     level route, the operator removes any existing equality and regexp matcher
     on the `namespace` label and adds a `namespace: <object namespace>`
     matcher.

     Matcher defines how to match on alert's labels.

FIELDS:
   name	<string> -required-
     Label to match.

   regex	<boolean>
     Whether to match on equality (false) or regular-expression (true).

   value	<string>
     Label value to match.
```
So your alertmanager config (route section) should look like:
```
route:
  groupBy: ["alertname"]
  groupWait: 30s
  groupInterval: 5m
  repeatInterval: 15m
  receiver: "webhook"
  routes:
    - matchers:
        name: alertname
        value: KubeJobFailed
        regex: false
      receiver: "null"
```
