### ISSUE TITLE
Cadvisor metrics scarping generates - HTTP server returned HTTP status 403 Forbidden

### ISSUE THREAD

**Issue by gr8Adakron** [prometheus-operator/prometheus-operator#3941]
Hey, I have deployed Prometheus operator and Integrated with Linekrd, KMS, Node exporter - they are working as desired. As I am trying to scrape directly the `/metric/cadvisor` endpoint it say `HTTP server returned HTTP status 403 Forbidden` in the Prometheus Dashboard > Status > Targets.

<img width="1440" alt="Screenshot 2021-03-27 at 3 52 01 PM" src="https://user-images.githubusercontent.com/16715364/112717771-b7297f00-8f14-11eb-8b82-9891cb628521.png">
 

These are my CAdvisor and Kubelet related scrape-confing:

```
    - job_name: kubernetes-cadvisor
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics/cadvisor
      scheme: https
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc.cluster.local:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

    - job_name: kubernetes-kubelet
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: https
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc.cluster.local:443
      - target_label: __metrics_path__
        source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        replacement: /api/v1/nodes/${1}/proxy/metrics

```

Version I am using: `quay.io/prometheus-operator/prometheus-operator:v0.46.0` . My Prometheus-main object config contains following:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus  #..> Expose #4 the Prometheus Admin API to External Port
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: testing-team
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: linkerd-additionalScrapeConfigs.yaml
  remoteWrite:
  - url: "https://metrics.idfystaging.com/vic1/api/v1/write"
  externalLabels:
    universe: andromeda-prometheus
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
```

## I can access the `/metrics/cadvisor` URL for specific Node via browser and can see the available metrics.

<img width="650" alt="Screenshot 2021-03-27 at 3 58 32 PM" src="https://user-images.githubusercontent.com/16715364/112717901-8d248c80-8f15-11eb-8437-7875a98cdb49.png">

Is there any thing missing? any help will be truly appreciated.
