### ISSUE TITLE
AlertmanagerConfig not getting picked up

### ISSUE THREAD

**Issue by shubhamc183** [prometheus-operator/prometheus-operator#3954]
My AlertmanagerConfig is not getting picked up by the Alertmanager. I have the CRD `monitoring.coreos.com.alertmanagerconfigs.yaml` version `0.46.0` applied in the cluster and I'm using `kube-prometheus-stack`.

Can someone guide me here?

**Environment**
K8s EKS 

* Prometheus Operator version:
```
Image:         quay.io/coreos/prometheus-operator:v0.40.0
Image ID:      docker-pullable://quay.io/coreos/prometheus-operator@sha256:a54e806fb27d2fb0251da4f3b2a3bb5320759af63a54a755788304775f2384a7
```

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
**Prometheus-operator logs:** No logs are reflected when the below manifest is added/deleted/edited.

* Manifests:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    alerts: "true"
    namespace: o11y # <-------------- kube-prometheus-stack is also installed in the same namespace "o11y"
spec:
  receivers:
  - name: prom-poc-alerts
    slackConfigs:
    - apiURL:
        key: prom-poc-alerts
      channel: '#prom-poc-alerts'
      sendResolved: true
      text: |-
        {{ range .Alerts }}{{ .Annotations.summary }}
        {{ .Annotations.description }}
        {{ .Annotations.message }}
        {{ end }}
  route:
    groupBy:
    - job
    groupInterval: 5m
    groupWait: 60s
    receiver: prom-poc-alerts
    repeatInterval: 10h
    routes:
    - match:
        namespace: o11y
      receiver: prom-poc-alerts
```

**Comment by fherbert** [comment]
Your alermanagerconfig manifest has invalid route matching, according to the CRD definition
```
kubectl explain alertmanagerconfig.spec.route.matchers
KIND:     AlertmanagerConfig
VERSION:  monitoring.coreos.com/v1alpha1

RESOURCE: matchers <[]Object>

DESCRIPTION:
     List of matchers that the alert’s labels should match. For the first
     level route, the operator removes any existing equality and regexp matcher
     on the `namespace` label and adds a `namespace: <object namespace>`
     matcher.

     Matcher defines how to match on alert's labels.

FIELDS:
   name	<string> -required-
     Label to match.

   regex	<boolean>
     Whether to match on equality (false) or regular-expression (true).

   value	<string>
     Label value to match.
```

So your alertmanager config (route section) should look like:
```
  route:
    groupBy:
    - job
    groupInterval: 5m
    groupWait: 60s
    receiver: prom-poc-alerts
    repeatInterval: 10h
    routes:
    - matchers:
       - name: namespace
         value: o11y
         regex: false
      receiver: prom-poc-alerts
```

**Comment by simonpasquier** [comment]
What's the definition of the corresponding `AlertmanagerConfig` resource (in particular `alertmanagerConfigSelector` and `alertmanagerConfigNamespaceSelector`)?

**Comment by talha0324** [comment]
I'm having same behaviour.
@fherbert  this doesn't fix it.

**Comment by PetzJohannes** [comment]
Would be awesome if someone can show us a working example.

At the moment I am stuck at this configuration:

```
  route:
    groupBy:
    - job
    groupInterval: 5m
    groupWait: 60s
    receiver: prom-poc-alerts
    repeatInterval: 10h
    matchers:
     - name: namespace
       value: o11y
       regex: false
    receiver: prom-poc-alerts
```

I don't know the update on which this changed. Before I was able to create a "match" over multiple namespaces. Now it looks like a AlertmanagerConfig is forced on one namespace.
https://github.com/prometheus-operator/prometheus-operator/blob/dab2194da371aee19ce251bcad34f8debb91ea9f/pkg/alertmanager/amcfg.go#L143

A couple of weeks ago I was able to do a global notification configuration like:
```
  route:
    groupBy:
    - job
    - alertname
    receiver: some-receiver
    routes:
    - match:
        department: it
      receiver: some-receiver
```

**Comment by njnygaard** [comment]
Any advice on this? I'm not able to configure my Slack integration without killing the operator and modifying the generated configuration by hand. If the operator is alive, it will continually overwrite modifications I make to the configuration. I know that I'm not supposed to make modifications to the config secret, but it was the only way I was able to get it to work once.

`alertmanager-prometheus-staging-kube-pr-alertmanager-generated`:
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: alertmanager-prometheus-staging-kube-pr-alertmanager-generated
  namespace: monitoring-prometheus
[...omitted]
```
Data:
```yaml
global:
  resolve_timeout: 5m
route:
  receiver: "null"
  group_by:
  - job
  routes:
  - receiver: "null"
    match:
      alertname: Watchdog
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: "null"
templates:
- /etc/alertmanager/config/*.tmpl
```

And here's the contents of the config I applied (pulled from k8s):
```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"monitoring.coreos.com/v1alpha1","kind":"AlertmanagerConfig","metadata":{"annotations":{},"labels":{"alertconfig":"slack-config"},"name":"slack-config","namespace":"monitoring-prometheus"},"spec":{"receivers":[{"name":"slack-notifications","slackConfigs":[{"apiURL":{"key":"slack-webhook-url"},"callbackId":"{{
      template \"slack.default.callbackid\" .
      }}","channel":"#notifications-staging","color":"{{ if eq .Status
      \"firing\" }}danger{{ else }}good{{ end }}","fallback":"{{ template
      \"slack.default.fallback\" . }}","footer":"{{ template
      \"slack.default.footer\" . }}","iconEmoji":"{{ template
      \"slack.default.iconemoji\" . }}","iconURL":"{{ template
      \"slack.default.iconurl\" . }}","linkNames":false,"pretext":"{{ template
      \"slack.default.pretext\" .
      }}","sendResolved":true,"shortFields":false,"text":"{{ template
      \"slack.default.text\" . }}","title":"{{ template \"slack.default.title\"
      . }}","titleLink":"{{ template \"slack.default.titlelink\" .
      }}","username":"Alertmanager!"}]}],"route":{"groupBy":["job"],"groupInterval":"5m","groupWait":"30s","receiver":"slack-notifications","repeatInterval":"12h"}}}
  creationTimestamp: '2021-08-31T20:16:20Z'
  generation: 1
  labels:
    alertconfig: slack-config
  managedFields:
    - apiVersion: monitoring.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:alertconfig': {}
        'f:spec':
          .: {}
          'f:receivers': {}
          'f:route':
            .: {}
            'f:groupBy': {}
            'f:groupInterval': {}
            'f:groupWait': {}
            'f:receiver': {}
            'f:repeatInterval': {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2021-08-31T20:16:20Z'
  name: slack-config
  namespace: monitoring-prometheus
  resourceVersion: '219228308'
  uid: 7d926aad-488e-4f41-a629-0c207ae8e985
spec:
  receivers:
    - name: slack-notifications
      slackConfigs:
        - apiURL:
            key: slack-webhook-url
          callbackId: '{{ template "slack.default.callbackid" . }}'
          channel: '#notifications-staging'
          color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
          fallback: '{{ template "slack.default.fallback" . }}'
          footer: '{{ template "slack.default.footer" . }}'
          iconEmoji: '{{ template "slack.default.iconemoji" . }}'
          iconURL: '{{ template "slack.default.iconurl" . }}'
          linkNames: false
          pretext: '{{ template "slack.default.pretext" . }}'
          sendResolved: true
          shortFields: false
          text: '{{ template "slack.default.text" . }}'
          title: '{{ template "slack.default.title" . }}'
          titleLink: '{{ template "slack.default.titlelink" . }}'
          username: Alertmanager!
  route:
    groupBy:
      - job
    groupInterval: 5m
    groupWait: 30s
    receiver: slack-notifications
    repeatInterval: 12h
```

And heres's the file that I applied to create that AlertManagerConfig:
```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-config
  namespace: monitoring-prometheus
  labels:
    alertconfig: slack-config
spec:
  route:
    groupBy: ["job"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: slack-notifications
  receivers:
    - name: slack-notifications
      slackConfigs:
        - sendResolved: true
          apiURL:
            key: slack-webhook-url
          channel: "#notifications-staging"
          username: "Alertmanager!"
          color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
          title: '{{ template "slack.default.title" . }}'
          titleLink: '{{ template "slack.default.titlelink" . }}'
          pretext: '{{ template "slack.default.pretext" . }}'
          text: '{{ template "slack.default.text" . }}'
          shortFields: false
          footer: '{{ template "slack.default.footer" . }}'
          fallback: '{{ template "slack.default.fallback" . }}'
          callbackId: '{{ template "slack.default.callbackid" . }}'
          iconEmoji: '{{ template "slack.default.iconemoji" . }}'
          iconURL: '{{ template "slack.default.iconurl" . }}'
          linkNames: false
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-webhook-url
  namespace: monitoring-prometheus
data:
  apiSecret: [redacted]
```

**Comment by talha0324** [comment]
@njnygaard can you post your Alertmanager CR too?

**Comment by njnygaard** [comment]
@talha0324 the Alertmanager CRD? I installed with the [Prometheus Community Kubernetes Helm Chart](https://github.com/prometheus-community/helm-charts). Did you still want that?

**Comment by talha0324** [comment]
So, the `prometheus-operator` creates an alertmanager config with the name of `alertmanager-xxxx-generated`
Now I'm assuming that you made no changes to the chart for alertmanager. So it's going to default config secret. What you need to do is.

1. Check if the `*-generated` secret is there with all your configs from `AlertmanagerConfig` CRD
2. Change the name of the secret picked by the chart for which you need to amend the chart or just give your config directly in the chart.
3. If you go with the changes to the chart, then you also need to deploy the config-reloader from the chart. By default it's disabled.

I guess by default prometheus-operator logs are info, you can set them to debug and see for logs.

BTW if you can just use the `Alertmanager` CRD to deploy it all it will be easy to configure.
it's all in here: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

**Comment by njnygaard** [comment]
Thanks for the response @talha0324 
I would like to target a Helm install procedure like the following:
```bash
    helm upgrade \
    -i \
    -f values-staging.yaml \
    prometheus-staging \
    prometheus-community/kube-prometheus-stack
```
With the values that I pulled from `helm show values prometheus-community/kube-prometheus-stack`.
Is it not possible to configure the `AlertmanagerConfig` from the values file at this time?

**Comment by talha0324** [comment]
Okay great so you used the `kube-prometheus-stack` 
All you have to do is look at these configs:
https://github.com/prometheus-community/helm-charts/blob/2a0d552bab9f9686008fbcdb9ad63c6382485f98/charts/kube-prometheus-stack/values.yaml#L424

To be specific you need to add the AlertmanagerConfig selector label.

**Comment by svetomir** [comment]
Hi, I am having the same issue with on K8s EKS. Helm Chart version: 19.2.2, appVersion: 0.50.0.

**Comment by talha0324** [comment]
@svetomir is the `AlertmanagerConfig` in the same namespace as the Alertmanager?

**Comment by svetomir** [comment]
> @svetomir is the `AlertmanagerConfig` in the same namespace as the Alertmanager?

Hey @talha0324 , thanks for replying, it is.

**Comment by talha0324** [comment]
Seems like it's picking and updating the alertmanagetConfig in the logs.
What is the name of the secret (config) for alertmanager that you are looking at?

**Comment by svetomir** [comment]
Yep, logs seem good, but it doesn't reflect in the alertmanager.

Secret name is: alertmanager-kube-prometheus-stack-alertmanager-generated
Also, /etc/alertmanager/config/alertmanager.yaml (the one being used) is unchanged.

**Comment by jjmengze** [comment]
> Would be awesome if someone can show us a working example.
> 
> At the moment I am stuck at this configuration:
> 
> ```
>   route:
>     groupBy:
>     - job
>     groupInterval: 5m
>     groupWait: 60s
>     receiver: prom-poc-alerts
>     repeatInterval: 10h
>     matchers:
>      - name: namespace
>        value: o11y
>        regex: false
>     receiver: prom-poc-alerts
> ```
> 
> I don't know the update on which this changed. Before I was able to create a "match" over multiple namespaces. Now it looks like a AlertmanagerConfig is forced on one namespace.
> 
> https://github.com/prometheus-operator/prometheus-operator/blob/dab2194da371aee19ce251bcad34f8debb91ea9f/pkg/alertmanager/amcfg.go#L143-L146
> 
> A couple of weeks ago I was able to do a global notification configuration like:
> 
> ```
>   route:
>     groupBy:
>     - job
>     - alertname
>     receiver: some-receiver
>     routes:
>     - match:
>         department: it
>       receiver: some-receiver
> ```

Hello @PetzJohannes I have the same question, I am stuck at the special namespace.

If if apply this alert config as folowing as below:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    slack: test
  name: slack-test-alertconfig
  namespace: myslack
spec:
  receivers:
  - name: slack-test
    slackConfigs:
    - apiURL:
        key: url
        name: slack-test-config
      channel: '#jason-prometheus-alert'
      sendResolved: true
      text: "test'
      title: "title"
  route:
    groupBy:
    - job
    groupInterval: 5s
    groupWait: 10s
    receiver: slack-test
    repeatInterval: 3s
```

the operator will create this alert configuration like the following as below.
```
  route:
    groupBy:
    - job
    groupInterval: 5s
    groupWait: 10s
    receiver: slack-test
    repeatInterval: 3s
    matchers:
     - name: namespace
       value: myslack
    receiver: slack-test
```

how did you escape this namespace

**Comment by tchellomello** [comment]
I'm hitting a similar issue. For example, my `AlertmanagerConfig` looks like:

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  namespace: observability
  name: toca-notifications
  labels:
    alertmanagerConfig: toca-notifications
spec:
  route:
    groupWait: 15s
    groupInterval: 15s
    repeatInterval: 15s
    receiver: slack-notifications
    routes:
      - matchers:
        - name: notify
          value: toca
        receiver: slack-notifications
  receivers:
    - name: slack-notifications
      slackConfigs:
        - sendResolved: true
          channel: '#notifications'
          apiURL:
            key: slack-api-url
            name: prometheus-toca-secrets
```

However, when rendered, the result YAML looks like this:

```yaml
/etc/alertmanager/config $ cat alertmanager.yaml 
route:
  receiver: "null"
  routes:
  - receiver: observability-toca-notifications-slack-notifications
    matchers:
    - namespace="observability"   <==== cannot escape this
    continue: true
    routes:
    - receiver: observability-toca-notifications-slack-notifications
      match:
        notify: toca
    group_wait: 15s
    group_interval: 15s
    repeat_interval: 15s
receivers:
- name: "null"
- name: observability-toca-notifications-slack-notifications
  slack_configs:
  - send_resolved: true
    api_url: xxxx
    channel: '#notifications'
templates: []
```

So I'm only able to receive a notification via Slack if the motivation has the label `namespace: observability`. For example, the first rule `BlackboxProbeFailed` I get via Slack but the next one I don't 

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blackbox-rules
  namespace: observability
  labels:
    managed-by: prometheus
spec:
  groups:
  - name: Blackbox
    rules:
      - alert: BlackboxProbeFailed
        expr: probe_success{instance!~"https://idrac-r610n.*"} == 0
        for: 5m
        labels:
          severity: error
          notify: toca
          namespace: observability
        annotations:
          summary: "Blackbox probe failed (instance {{ $labels.instance }})"
          description: "Probe failed\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: BlackboxProbeHttpFailure
        expr: probe_http_status_code{instance!~"https://idrac-r610n.*"} <= 199 OR probe_http_status_code{instance!~"https://idrac-r610n.*"} >= 400
        for: 5m
        labels:
          severity: error
          notify: toca
        annotations:
          summary: "Blackbox probe HTTP failure (instance {{ $labels.instance }})"
          description: "HTTP status code is not 200-399\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```

![image](https://user-images.githubusercontent.com/809840/152632095-82d52916-0294-492f-9371-fa546c3b0855.png)

**Comment by ostavnaas** [comment]
I believe that is the idea behind AlertmanagerConfig, that it's pr. namespace.

> By definition, the Alertmanager configuration only applies to alerts for which the `namespace` label is equal to the namespace of the AlertmanagerConfig resource

ref: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml#L41

**Comment by bigbugbean** [comment]
I'm hitting a similar issue, and I know why that is. Please the author to explain why doing this and what I should do if I want to match alerts for all namespaces of the entire K8S cluster?

**Comment by SlevinWasAlreadyTaken** [comment]
@bigbugbean you mean find a solution in this discussion: https://github.com/prometheus-operator/prometheus-operator/issues/3737

**Comment by StevenBarre** [comment]
This worked for me

```yaml
spec:
  route:
    groupBy:
    - severity
    - namespace
    groupInterval: 5m
    groupWait: 30s
    receiver: Everyone
    repeatInterval: 48h
    routes:
    - receiver: TechLeads
      repeatInterval: 1w
      matchers:
        - name: severity
          value: warning|info
          matchType: =~
```
