### ISSUE TITLE
Prometheus targets are not updated with current state of Kubernetes Endpoints

### ISSUE THREAD

**Issue by sharoncr1** [prometheus-operator/prometheus-operator#3965]
**What happened?**

I am trying to set-up a monitoring system for a SpringBoot service. I have setup a pod, service and a ServiceMonitor for this. I've configured Readiness probe on the health end point and ServiceMonitor against the metrics endpoint. When the application becomes unhealthy, kubernetes de-registers the that pod ip from endpoints of that service. But this is not being picked up by the Prometheus. Prometheus continues to scrape the metrics even when that endpoint doesn't exist against that service object. (Since pod-ip and path are still same and the pod is still running, target shows up). 

**Did you expect to see something different?**

I was expecting that Prometheus/Prometheus-operator has a mechanism to continuously refresh the list of endpoints to scrape from the configurations and continuously changing the list of targets. (So that I can set-up some alerts for up==0 and I can achieve both metrics scraping and alerting in one shot). 

**How to reproduce it (as minimally and precisely as possible)**:

Create a Kuberetes pod and Service. Let the pod run successfully and create ServiceMonitor for some metrics endpoint. Confirm you see the target after creating the ServiceMonitor on Prometheus. Make the pod un-ready. pod can be still running but not ready to accept traffic - this is only true for the sense of Kubernetes. Kuberenetes will detach the ip from list of endpoints. But that target will be still active in Kubernetes. 

**Environment**

Kubernetes cluster running on AWS

* Prometheus Operator version:

quay.io/coreos/prometheus-operator:v0.35.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

Created using KOPS

* Manifests:

Service monitor definition : 

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: prometheus
  name: myapp
  namespace: sharon
spec:
  endpoints:
  - interval: 20s
    path: /myapp/metrics
    port: http
  namespaceSelector:
    matchNames:
    - app-namespace
  selector:
    matchLabels:
      application: myapp
```
