### ISSUE TITLE
enabling external labels for Prometheus and alertmanager pods

### ISSUE THREAD

**Issue by munipravy** [prometheus-operator/prometheus-operator#3977]
For enabling pod level labeling in Prometheus we are using podMetada under spec as shown below:
```
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: prometheus 
spec:
  podMetadata:
      labels:
        app: monitor
```

But we are unable to see labels on prometheus pods. 
Please Kindly suggest us on this issue.

Env: GKE

prometheus operator version: prometheus-operator:v0.41.1
prometheus: prometheus:v2.20.1
