### ISSUE TITLE
Prometheus Agent Support

### ISSUE THREAD

**Issue by kakkoyun** [prometheus-operator/prometheus-operator#3989]
Prometheus soon is going to have a lightweight version as an agent. https://github.com/prometheus/prometheus/issues/8305
It would be awesome to support this in the promethues-operator. 

I've opened the issue to start the discussion and know what the maintainers think?

@prometheus-operator/kube-prometheus-reviewers

P.S: I'd be happy to work on this.

**Comment by simonpasquier** [comment]
+1 for me definitely. Because the agent won't have all capabilities of the Prometheus server (e.g. no rule evaluation,no alertmanager config, no API probably) and the plan is to have it as another binary, it might make sense to have another CRD for it. Obviously we need more details on what the agent will actually look like.

**Comment by brancz** [comment]
I think it might be a little early as the details haven't been fleshed/implemented out on Prometheus side even. It doesn't hurt to think about a high-level strategy of the CRD though.

I realize that this might be overloading things a bit, but this is sort of an opportunity for a new start, where we could re-think our mistakes from the existing Prometheus CRD/API. If you have time, I would very much welcome it if we could think about the ScrapeConfig CRD as the basis of all configuration, and PodMonitors/ServiceMonitors/Probes only compile down to the ScrapeConfig CRD and all the PrometheusAgent CRD does is pick up ScrapeConfig CRDs directly. Rough thoughts here: https://github.com/prometheus-operator/prometheus-operator/issues/2787

**Comment by ArthurSens** [comment]
This issue came up during the contributor office hours, so just backporting the discussion here:

It’s already possible to run the agent once it's released with the Prometheus CR so it's not like we have a huge urgency on this, but a dedicated CR for it would definitely help with validation and a better UX.

* The idea for the new Agent CR is to re-use everything we can from the Prometheus CR. 
* Creating a new Agent CR will not prevent people from using Prometheus CR with the agent configuration, and we should not block this from happening. The main reason is because avoiding maintaining extra logic for little benefit

**Comment by simonpasquier** [comment]
Now that we have a beta release of Prometheus with the agent feature flag ([v2.32.0-beta.0](https://github.com/prometheus/prometheus/releases/tag/v2.32.0-beta.0)), I gave it a try using the existing Prometheus CRD.

TL;DR: it's not working out of the box but it shouldn't be too hard to adjust a bit the operator to "support" the agent mode with the existing Prometheus CR. 

My CR looks like this:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/name: prometheus
    prometheus: agent
  name: agent
  namespace: openshift-monitoring
spec:
  image: quay.io/prometheus/prometheus:v2.32.0-beta.0
  containers:
  - name: prometheus
    args:
    - '--config.file=/etc/prometheus/config_out/prometheus.env.yaml'
    - '--storage.agent.path=/prometheus'
    - '--enable-feature=agent'
    - '--web.enable-lifecycle'
  - url: http://prometheus-receiver:9090/api/v1/write
    remoteTimeout: "5s"
  replicas: 1
```

The important bit is that the Prometheus arguments need to be overridden because the storage flags are different (TSDB path and retention in particular). I've used another Prometheux server with `--enable-feature=remote-write-receiver` as the remote write receiver.

The blocking issue right now is that the generated configuration isn't compatible with the agent mode because the operator generates the `rules` and `alerting` sections which isn't permitted for the agent. As a workaround, I've set the resource in paused mode, modified the generated secret manually to remove the 2 keys and it worked!
I think that it would be fine to tweak the generated Prometheus configuration so that `rules` and `alerting` fields aren't present when the custom resource has nil rule selectors and alerting spec.
