### ISSUE TITLE
Can't increase scrape timeout for pod monitor

### ISSUE THREAD

**Issue by pbnsilva** [prometheus-operator/prometheus-operator#3990]
I am trying to increase the scrape timeout of a pod monitor.

**What did you do?**
My PodMonitor:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: myapp-metrics-podmonitor
  namespace: monitoring
  labels:
    app: myapp-metrics-podmonitor
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: myapp
  podMetricsEndpoints:
  - port: metrics
    scrapeTimeout: 1m
    path: /metrics
  podTargetLabels:
  - app
  namespaceSelector:
    matchNames:
    - default
```
In the prometheus dashboard, my podmonitor targets appear with the error `context deadline exceeded` and scrape duration still at 10s.

Additionally, the value of `scrape_timeout` in the Prometheus configuration (`Status`->`Configuration`) for the corresponding `job_name` is also still set at `10s`.

**Did you expect to see some different?**
I would expect to see a higher scrape duration value, and even no error at all.

**Prometheus Operator version:**
`v0.46.0`

Thank you
