### ISSUE TITLE
How to add multiple ServiceMonitor to PrometheusOperator object

### ISSUE THREAD

**Issue by gr8Adakron** [prometheus-operator/prometheus-operator#3996]
**What did you do?**
I have configured prometheus operator with 2 service monitors:
My service monitors files

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-service-monitor
  labels:
    app: frontend
spec:
  namespaceSelector:
    matchNames:
    - abcd-efg
  selector:
    matchLabels:
      prometheus_operator_service_monitor: allow
  endpoints:
  - targetPort: 8877
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hijk-lmno
  labels:
    app: backend
spec:
  namespaceSelector:
    matchNames:
    - ambassador-log
  selector:
    matchLabels:
      prometheus_operator_service_monitor: allow
  endpoints:
  - targetPort: 80
```

Now I am refering the service monitor in the `prometheus-main-object` (Note: below YAML contain just issue-relevant field)

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus  
spec:
  serviceMonitorSelector:
    matchLabels:
      app: frontend
``` 

How do I add `app: backend` as well to the main object, I try doing like this:

```
spec:
  serviceMonitorSelector:
    matchLabels:
      app: frontend
      app: backend
```

But is didnt work as matchLabels works as `AND` operator.

Any help is appreaciated. THanks

**Comment by paulfantom** [comment]
> But this didnt work as matchLabels works as AND operator.

Yes, that is [how label matches work in kubernetes](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors).

Solution is to use another label in ServiceMonitors (we most commonly use `prometheus: <name_of_prometheus_resource>`). This way you have a label dedicated for this purpose and you have a clear notion of which prometheus is scraping this ServiceMonitor (there can be multiple prometheus servers governed by prometheus-operator).

**Comment by gr8Adakron** [comment]
Thanks for the response @paulfantom 
> there can be multiple prometheus servers governed by prometheus-operator

Let me know if I am wrong but this means creating two prometheus-main object with each concentrating on different service monitor. 

For example:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-frontend
spec:
  serviceMonitorSelector:
    matchLabels:
      app: frontend
...
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-backend
spec:
  serviceMonitorSelector:
    matchLabels:
      app: backend
...
```

**Comment by paulfantom** [comment]
No. Solution is to use different labels, adding another `Prometheus` object will spin up another set of prometheus servers (unless this is what you want).

Use one selector in Prometheus object, like:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-backend
spec:
  serviceMonitorSelector:
    matchLabels:
      prometheus: application-monitoring
...
```
and use `prometheus: application-monitoring` label in all ServiceMonitors which need to be handled by that prometheus.


Additionally, if you have only one Prometheus server and wish for this server to collect metrics from all ServiceMonitors in the cluster, then just use `{}` as `serviceMonitorSelector`. Like in https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/manifests/prometheus/prometheus.yaml#L64 (Feel free to poke around the repository to check a working configuration)
