### ISSUE TITLE
Prometheus did not discover correct label

### ISSUE THREAD

**Issue by sicparvismagnaX** [prometheus-operator/prometheus-operator#3998]
**What did you do?**
I have installed Prometheus with this repository using helm via youtube channel https://www.youtube.com/watch?v=QoDqxm7ybLc, Once I successfully installed Prometheus, I want to monitor the third party app which is nodeJS API. I have applied Servicemonitor as shown below 

```
apiVersion: v1
kind: Service
metadata:
  name: test-api
  namespace: core-infra
spec:
  ports:
    - name: iammetrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: digital-innov-gengchan-gateway
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-api-servicemonitor
  namespace: core-infra
  labels:
    app: test-api-servicemonitor
    release: prometheus
spec:
  selector:
    matchLabels:
      app: test-api
      Release: prometheus
  endpoints:
  - port: iammetrics
    interval: 15s
    path: /metrics
```

and here is my nodejs code

```js
`'use strict';

const express = require('express');

// Constants
const port = process.env.PORT;

// App
const client = require('prom-client');
const collectDefaultMetrics = client.collectDefaultMetrics;
// Probe every 5th second.
collectDefaultMetrics({ timeout: 5000 });

const counter = new client.Counter({
  name: 'node_request_operations_total',
  help: 'The total number of processed requests'
});

const histogram = new client.Histogram({
  name: 'node_request_duration_seconds',
  help: 'Histogram for the duration in seconds.',
  buckets: [1, 2, 5, 6, 10]
});

const app = express();
app.get('/', (req, res) => {

  //Simulate a sleep
  var start = new Date()
  var simulateTime = 1000

  setTimeout(function(argument) {
    // execution time simulated with setTimeout function
    var end = new Date() - start
    histogram.observe(end / 1000); //convert to seconds
  }, simulateTime)

  counter.inc();
  
  res.send('Hello world\n');
});


// Metrics endpoint
app.get('/metrics', async function(req,res,next){
  res.set('Content-Type', client.register.contentType)
  res.end(await client.register.metrics())
})

app.listen(port, async () => {
	console.log(`app listening at http://localhost:${port}`)
})
```

![Screen Shot 2564-04-22 at 15 39 09](https://user-images.githubusercontent.com/83002983/115683708-ec44b800-a380-11eb-9990-139273d8cf21.png)

**Did you expect to see some different?**
i expect prometheus to scrape metrics file

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by simonpasquier** [comment]
The label selector of the service monitor doesn't match with the `test-api` service. Your service definition should be:

```
apiVersion: v1
kind: Service
metadata:
  name: test-api
  namespace: core-infra
  labels:
      app: test-api
      Release: prometheus
spec:
  ...
```
