### ISSUE TITLE
AlertmanagerConfig Missing Global slack_api_url

### ISSUE THREAD

**Issue by Raynbag** [prometheus-operator/prometheus-operator#4006]
**What happened?**

alertmanager-generated secret created from alertmanagerconfig CRD is missing the global slack_api_url section causing an error in the alertmanager pod when trying to load the new config.

**Did you expect to see something different?**

Yeah, slack_api_url populated.

**How to reproduce it (as minimally and precisely as possible)**:

Create alertmanagerconfig CRD using the below config.

```
inhibitRules:
  - equal:
    - alertname
    - cluster
    - service
    sourceMatch:
    - name: severity
      regex: false
      value: critical
    targetMatch:
    - name: severity
      regex: false
      value: warning
  route:
    groupBy:
    - alertname
    - cluster
    - service
    groupInterval: 5m
    groupWait: 30s
    receiver: default-receiver
    repeatInterval: 1h
    routes:
    - match:
        alertname: DeadMansSwitch
      receiver: 'null'
    - match:
        alertname: Watchdog
      receiver: 'null'
    - match:
        alertname: DeploymentVerification
      receiver: default-notification
  receivers:
    - name: default-receiver
      slackConfigs:
      - apiURL:
          key: slack_webhook_url
          name: alertmanager
          optional: false
      - channel: '#stack-ops-eu'
        sendResolved: true
        text: "{{ range .Alerts }}\n   *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity\
          \ }}`\n  *Description:* {{ .Annotations.description }}\n  *Graph:* <{{ .GeneratorURL\
          \ }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>\n\
          \  *Details:*\n  {{ range .Labels.SortedPairs }} \u2022 *{{ .Name }}:* `{{ .Value\
          \ }}`\n  {{ end }}\n{{ end }}"
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing
          | len }}{{ end }}] Prometheus Event Notification'
        username: AlertManager Ops EU
    - name: default-notification
      slackConfigs:
      - apiURL:
          key: slack_webhook_url
          name: alertmanager
          optional: false
      - channel: '#stack-ops-eu'
        color: '#237CDC'
        sendResolved: false
        text: "{{ range .Alerts }}\n   *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity\
          \ }}`\n  *Description:* {{ .Annotations.description }}\n  *Graph:* <{{ .GeneratorURL\
          \ }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>\n\
          \  *Details:*\n  {{ range .Labels.SortedPairs }} \u2022 *{{ .Name }}:* `{{ .Value\
          \ }}`\n  {{ end }}\n{{ end }}"
        title: '[{{ .Status | toUpper }}] Deployment Generation Change'
        username: AlertManager Ops EU
    - name: 'null'
```

**Environment**

* Prometheus Operator version:

    `bfa18e877d76754870d9268dcfa652f35f0862cc3fe9cffbce239a3cf342b5f3`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-gke.1600", GitCommit:"4f6f69fd81ca8cb6962a2f7e1ed9c7880834cf71", GitTreeState:"clean", BuildDate:"2021-03-08T19:22:13Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

GKE deployed with ArgoCD.

**Anything else we need to know?**:

Logs from alertmanager pod:
```
{"caller":"coordinator.go:119","component":"configuration","file":"/etc/alertmanager/config/alertmanager.yaml","level":"info","msg":"Loading configuration file","ts":"2021-04-27T08:53:28.401Z"}
{"caller":"coordinator.go:124","component":"configuration","err":"no global Slack API URL set","file":"/etc/alertmanager/config/alertmanager.yaml","level":"error","msg":"Loading configuration file fa
iled","ts":"2021-04-27T08:53:28.401Z"}
```
Secret generated from operator:
```
global:
  resolve_timeout: 5m
route:
  receiver: "null"
  group_by:
  - job
  routes:
  - receiver: monitoring-alertmanager-config-inhouse-default-receiver
    group_by:
    - alertname
    - cluster
    - service
    match:
      namespace: monitoring
    continue: true
    routes:
    - receiver: monitoring-alertmanager-config-inhouse-null
    - receiver: monitoring-alertmanager-config-inhouse-null
    - receiver: monitoring-alertmanager-config-inhouse-default-notification
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
  - receiver: "null"
    match:
      alertname: Watchdog
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
inhibit_rules:
- target_match:
    namespace: monitoring
    severity: warning
  source_match:
    namespace: monitoring
    severity: critical
  equal:
  - alertname
  - cluster
  - service
receivers:
- name: "null"
- name: monitoring-alertmanager-config-inhouse-default-receiver
  slack_configs:
  - api_url: XXXXXXXXXXXXXXXXXXXXX
  - send_resolved: true
    channel: '#stack-ops-eu'
    username: AlertManager Ops EU
    title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing
      | len }}{{ end }}] Prometheus Event Notification'
    text: |-
      {{ range .Alerts }}
         *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
        *Description:* {{ .Annotations.description }}
        *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
        *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}
    icon_emoji: ':poop:'
- name: monitoring-alertmanager-config-inhouse-default-notification
  slack_configs:
  - api_url: XXXXXXXXXXXXXXXXXXXXX
  - send_resolved: false
    channel: '#stack-ops-eu'
    username: AlertManager Ops EU
    color: '#237CDC'
    title: '[{{ .Status | toUpper }}] Deployment Generation Change'
    text: |-
      {{ range .Alerts }}
         *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
        *Description:* {{ .Annotations.description }}
        *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
        *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}
- name: monitoring-alertmanager-config-inhouse-null
templates:
- /etc/alertmanager/config/*.tmpl
```

**Comment by simonpasquier** [comment]
Good catch! The field should be added here:
https://github.com/prometheus-operator/prometheus-operator/blob/981c6cdca48156442904bfae2c0da55245fcf673/pkg/alertmanager/types.go#L39-L65

Do you want to give it a try?

**Comment by Raynbag** [comment]
Hey,

Apologies, bank holiday weekend in the UK so been OOO.

I see there's a PR for this fix, thanks very much!

On your comment of giving it a try, apologies, how would I go about that exactly? @simonpasquier

**Comment by simonpasquier** [comment]
Oh now I see what happens for you @Raynbag. You've got a typo in your AlertmanagerConfig yaml

```yaml
  receivers:
    - name: default-receiver
      slackConfigs:
      - apiURL:
          key: slack_webhook_url
          name: alertmanager
          optional: false
# replace this line
#      - channel: '#stack-ops-eu'
# by
        channel: '#stack-ops-eu'
        sendResolved: true
        text: "{{ range .Alerts }}\n   *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity\
          \ }}`\n  *Description:* {{ .Annotations.description }}\n  *Graph:* <{{ .GeneratorURL\
          \ }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>\n\
          \  *Details:*\n  {{ range .Labels.SortedPairs }} \u2022 *{{ .Name }}:* `{{ .Value\
          \ }}`\n  {{ end }}\n{{ end }}"
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing
          | len }}{{ end }}] Prometheus Event Notification'
        username: AlertManager Ops EU
```
