### ISSUE TITLE
Cannot find active targets

### ISSUE THREAD

**Issue by juandspy** [prometheus-operator/prometheus-operator#4007]
**What did you do?**
I installed prometheus-community/kube-prometheus-stack and get all the metrics of my cluster but not the ones from a REST API I built in Golang.

**Did you expect to see some different?**
Yes. Inside Prometheus UI I see:

```
Service Discovery
serviceMonitor/develop/prometheus-kube-prometheus-alertmanager/0 (1 / 35 active targets)
serviceMonitor/develop/prometheus-kube-prometheus-apiserver/0 (1 / 1 active targets)
serviceMonitor/develop/prometheus-kube-prometheus-coredns/0 (1 / 13 active targets)
serviceMonitor/develop/prometheus-kube-prometheus-grafana/0 (1 / 35 active targets)
serviceMonitor/develop/prometheus-kube-prometheus-kube-controller-manager/0 (1 / 13 active targets)
serviceMonitor/develop/prometheus-kube-prometheus-kube-etcd/0 (1 / 13 active targets)
serviceMonitor/develop/prometheus-kube-prometheus-kube-proxy/0 (1 / 13 active targets)
serviceMonitor/develop/prometheus-kube-prometheus-kube-scheduler/0 (1 / 13 active targets)
serviceMonitor/develop/prometheus-kube-prometheus-kube-state-metrics/0 (1 / 35 active targets)
serviceMonitor/develop/prometheus-kube-prometheus-kubelet/0 (1 / 13 active targets)
serviceMonitor/develop/prometheus-kube-prometheus-kubelet/1 (1 / 13 active targets)
serviceMonitor/develop/prometheus-kube-prometheus-kubelet/2 (1 / 13 active targets)
serviceMonitor/develop/prometheus-kube-prometheus-node-exporter/0 (1 / 35 active targets)
serviceMonitor/develop/prometheus-kube-prometheus-operator/0 (1 / 35 active targets)
serviceMonitor/develop/prometheus-kube-prometheus-prometheus/0 (1 / 35 active targets)
serviceMonitor/develop/collector-metrics-servicemonitor/0 (0 / 35 active targets)
```

I don't know why the last one is 0/35 instead of 1/35. If Promtheus don't find the target I cannot monitor the API.

**Environment**

* Prometheus Operator version:
I can't find the prometheus-operator deployment, so here it is the prometheus-kube-prometheus-operator (sorry):

```
Name:                   prometheus-kube-prometheus-operator
Namespace:              develop
...
  Service Account:  prometheus-kube-prometheus-operator
  Containers:
   kube-prometheus-stack:
    Image:      quay.io/prometheus-operator/prometheus-operator:v0.47.0
    Port:       10250/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/prometheus-kube-prometheus-kubelet
      --localhost=127.0.0.1
      --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.47.0
      --config-reloader-cpu=100m
      --config-reloader-memory=50Mi
      --web.enable-tls=true
      --web.cert-file=/cert/cert
      --web.key-file=/cert/key
      --web.listen-address=:10250
      --web.tls-min-version=VersionTLS13
...
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

Minikube. These are the steps I followed:

```
minikube start
kubectl create namespace develop
kubectl apply -f collector.yml -n develop
# Install Prometheus
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add stable https://charts.helm.sh/stable
helm repo update
helm install prometheus prometheus-community/kube-prometheus-stack -n develop
kubectl get pods | grep prometheus  # -> This is the output:
        alertmanager-prometheus-kube-prometheus-alertmanager-0   2/2     Running   0          2m35s
        prometheus-grafana-bb6f77477-qhnzf                       2/2     Running   0          3m2s
        prometheus-kube-prometheus-operator-68d59d8d59-28pkj     1/1     Running   0          3m2s
        prometheus-kube-state-metrics-685b975bb7-8f924           1/1     Running   0          3m2s
        prometheus-prometheus-kube-prometheus-prometheus-0       2/2     Running   1          2m32s
        prometheus-prometheus-node-exporter-nswdn                1/1     Running   0          3m2s
kubectl expose service prometheus-grafana --type=NodePort --target-port=3000 --name=prometheus-grafana-np
kubectl expose service prometheus-kube-prometheus-prometheus --type=NodePort --target-port=9090 --name=prometheus-server-np
```
I have also deployed a Strimzi Kafka cluster, but it doesn't interfer with Prometheus.

* Manifests:

```
#collector.yml
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: collector-deployment
  labels:
    app: collector
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: juandspy/iok8s-collector:v0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        args: ["-kafkaAddress=cluster-01-kafka-bootstrap:9092"]
---
apiVersion: v1
kind: Service
metadata:
  name: collector-service
  labels:
    app: collector
spec:
  type: NodePort
  selector:
    app: collector
  ports:
    - name: https
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: collector-metrics-servicemonitor
  labels:
    app: collector
    release: prometheus
spec:
  selector:
    matchLabels:
      app: collector-service
  endpoints:
  - port: https
    interval: 15s
```

* Prometheus Operator Logs:

```
k logs prometheus-prometheus-kube-prometheus-prometheus-0 -c prometheus

level=info ts=2021-04-27T15:41:45.759Z caller=main.go:418 msg="Starting Prometheus" version="(version=2.26.0, branch=HEAD, revision=3cafc58827d1ebd1a67749f88be4218f0bab3d8d)"
level=info ts=2021-04-27T15:41:45.760Z caller=main.go:423 build_context="(go=go1.16.2, user=root@a67cafebe6d0, date=20210331-11:56:23)"
level=info ts=2021-04-27T15:41:45.760Z caller=main.go:424 host_details="(Linux 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 prometheus-prometheus-kube-prometheus-prometheus-0 (none))"
level=info ts=2021-04-27T15:41:45.760Z caller=main.go:425 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2021-04-27T15:41:45.760Z caller=main.go:426 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2021-04-27T15:41:45.808Z caller=web.go:540 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2021-04-27T15:41:45.811Z caller=main.go:795 msg="Starting TSDB ..."
level=info ts=2021-04-27T15:41:45.834Z caller=tls_config.go:191 component=web msg="TLS is disabled." http2=false
level=info ts=2021-04-27T15:41:45.837Z caller=head.go:696 component=tsdb msg="Replaying on-disk memory mappable chunks if any"
level=info ts=2021-04-27T15:41:45.837Z caller=head.go:710 component=tsdb msg="On-disk memory mappable chunks replay completed" duration=6.567µs
level=info ts=2021-04-27T15:41:45.837Z caller=head.go:716 component=tsdb msg="Replaying WAL, this may take a while"
level=info ts=2021-04-27T15:41:45.838Z caller=head.go:768 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
level=info ts=2021-04-27T15:41:45.838Z caller=head.go:773 component=tsdb msg="WAL replay completed" checkpoint_replay_duration=66.012µs wal_replay_duration=569.206µs total_replay_duration=678.301µs
level=info ts=2021-04-27T15:41:45.840Z caller=main.go:815 fs_type=EXT4_SUPER_MAGIC
level=info ts=2021-04-27T15:41:45.840Z caller=main.go:818 msg="TSDB started"
level=info ts=2021-04-27T15:41:45.840Z caller=main.go:944 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2021-04-27T15:41:45.851Z caller=kubernetes.go:266 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-04-27T15:41:45.852Z caller=kubernetes.go:266 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-04-27T15:41:45.853Z caller=kubernetes.go:266 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-04-27T15:41:45.854Z caller=kubernetes.go:266 component="discovery manager notify" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-04-27T15:41:46.217Z caller=main.go:975 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=376.623115ms remote_storage=2.215µs web_handler=536ns query_engine=1.068µs scrape=742.243µs scrape_sd=3.654958ms notify=34.895µs notify_sd=2.063348ms rules=360.215973ms
level=info ts=2021-04-27T15:41:46.217Z caller=main.go:767 msg="Server is ready to receive web requests."
level=info ts=2021-04-27T15:41:50.716Z caller=main.go:944 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2021-04-27T15:41:50.728Z caller=kubernetes.go:266 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-04-27T15:41:50.729Z caller=kubernetes.go:266 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-04-27T15:41:50.733Z caller=kubernetes.go:266 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-04-27T15:41:50.735Z caller=kubernetes.go:266 component="discovery manager notify" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-04-27T15:41:51.737Z caller=main.go:975 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=1.021779408s remote_storage=8.825µs web_handler=1.635µs query_engine=4.216µs scrape=204.682µs scrape_sd=7.117916ms notify=21.975µs notify_sd=1.298368ms rules=1.001650783s
level=warn ts=2021-04-27T17:50:54.699Z caller=scrape.go:1402 component="scrape manager" scrape_pool=serviceMonitor/develop/prometheus-kube-prometheus-kubelet/1 target=https://192.168.49.2:10250/metrics/cadvisor msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=174
level=info ts=2021-04-27T19:55:43.018Z caller=compact.go:507 component=tsdb msg="write block" mint=1619538116361 maxt=1619539200000 ulid=01F4AEDMD604MMMP02Z3311YVA duration=1.155737808s
level=info ts=2021-04-27T19:55:43.078Z caller=head.go:880 component=tsdb msg="Head GC completed" duration=44.329807ms
level=warn ts=2021-04-27T19:55:52.682Z caller=scrape.go:1402 component="scrape manager" scrape_pool=serviceMonitor/develop/prometheus-kube-prometheus-kubelet/1 target=https://192.168.49.2:10250/metrics/cadvisor msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=576
```

It says `TLS is disabled`. My app has exposed the /metrics endpoint with TLS. Could that be the problem?

**Anything else we need to know?**:
Here it is the Golang API I built: https://gitlab.com/iok8s/collector. All the steps I followed to build the cluster are at https://gitlab.com/iok8s/kubernetes-cluster. It is written in Spanish, but all the commands are there.

I read that this problem may be related to ports name inside the service, deployment and servicemonitor, but I'm pretty sure I filled everything correctly.

Thanks in advance.

**Comment by paulfantom** [comment]
You have an incorrect selector in ServiceMonitor. ServiceMonitor needs to match Service object using a kubernetes label selector.

This:
```
apiVersion: v1
kind: Service
metadata:
  name: collector-service
  labels:
    app: collector
```

Needs to be matched by `spec.selector` in:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
...
spec:
  selector:
    matchLabels:
      app: collector-service
```


Try changing your ServiceMonitor `spec.selector` to:
```
spec:
  selector:
    matchLabels:
      app: collector
```
