### ISSUE TITLE
AlertmanagerConfig not being recognized as expected

### ISSUE THREAD

**Issue by aa920502** [prometheus-operator/prometheus-operator#4024]
Hi team, I need some help identifying issue in my AlertManager Yaml file setup

Currently the alert rules are working, but AlertmanagerConfig is not properly read when I started Alertmanager service, I followed guide on https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/alerting.md but it's not helping with the issue 

Here is my current alertmanager.yaml file

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: example
spec:
  replicas: 2
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: example

---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: ['alertname']
    groupWait: 10s
    groupInterval: 10s
    repeatInterval: 1h
    receiver: 'email'
  receivers:
  - name: 'email'
    emailConfigs:
    - to: 'xxx@gmail.com'
      from: 'xxx@gmail.com'
      smarthost: 'email-xxx.usxxxxx-1.xxx.com:587'
      authUsername: 'xxx'
      authPassword:
        name: 'email-config'
        key: 'xxx/xxxx'
      authIdentity: 'xxx@gmail.com'
---

apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: alertmanager-svc
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 30903
      port: 9093
      protocol: TCP
      targetPort: web
  selector:
    alertmanager: example

```

<img width="1484" alt="Screen Shot 2021-05-06 at 4 36 16 PM" src="https://user-images.githubusercontent.com/7997068/117378027-70bb2e80-ae89-11eb-9c61-fa8e45174a7c.png">

From the screenshot you can see that receiver is null, also other configs are not showing up as well.

**Comment by simonpasquier** [comment]
Does the AlertmanagerConfig resource live in the same namespace as the Alertmanager resource? Can you share the prometheus operator logs?

**Comment by aa920502** [comment]
Thanks for the response! How do I define the name space for AlertmanagerConfig resource? In my prometheus yaml file, I have this under the spec of Prometheus resource to specify the alert manager service
```

  alerting:
    alertmanagers:
      - namespace: default
        name: alertmanager-svc
        port: web
```

And I also have alert rules defined in the Prometheus yaml file
```

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alert-rules
  namespace: default
  labels:
    role: alert-rules
spec:
  groups:
    - name: example
      rules:
        - alert: InstanceUp
          expr: up == 1
          for: 1m
          labels:
            alertname: "test alert"
            severity: "critical"
          annotations:
            summary: "service is up NOW"
            description: "service has been up for more than 1 minutes."

```


From this, should I just add `namespace: default`  in metadata field in AlertmanagerConfig?

**Comment by aa920502** [comment]
Update: I just added namespace: default in metadata field in AlertmanagerConfig, but it's still the same..

**Comment by talha0324** [comment]
Any update on this?

I'm using OpenShift version 4.7.1

**Comment by aa920502** [comment]
Still unresolved..  :(

**Comment by simonpasquier** [comment]
@aa920502 please run the operator with the debug log level and share the logs.

**Comment by talha0324** [comment]
[log.txt](https://github.com/prometheus-operator/prometheus-operator/files/6522383/log.txt)

These are the logs

**Comment by talha0324** [comment]
and these are my configurations
```
kind: Secret
apiVersion: v1
metadata:
  name: alertmanager-workload-config
  namespace: openshift-stakater-workload-monitoring
data:
  alertmanager.yaml: xxx

---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: workload-config
  namespace: openshift-stakater-workload-monitoring
  labels:
    alertmanagerConfig: test
spec:
  route:
    receiver: "null"
    groupBy:
    - job
    routes:
    - receiver: "null"
      groupBy:
      - alertname
      - severity
      continue: true
      routes:
      - receiver: "null"
        matchers:
        - name: alertname
          value: UsingDeprecatedAPIAppsV1Beta2
          regex: false
    - receiver: watchdog
      matchers:
      - name: alertname
        value: Watchdog
        regex: false
      repeatInterval: 5m
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
  receivers:
  - name: watchdog
    webhookConfigs:
    - sendResolved: true
      url: https://nosnch.in/f4b2677ac4
---

apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: workload
  namespace: openshift-stakater-workload-monitoring
  labels:
    alertmanager: workload
spec:
  nodeSelector:
    node-role.kubernetes.io/infra: ''
  serviceAccountName: alertmanager-workload
  secrets:
    - alertmanager-workload-tls
    - alertmanager-workload-proxy
    - alertmanager-kube-rbac-proxy
  listenLocal: true
  resources:
    requests:
      cpu: 4m
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: alertmanager
                  operator: In
                  values:
                    - workload
            namespaces:
              - openshift-stakater-workload-monitoring
            topologyKey: kubernetes.io/hostname
          weight: 100
  containers:
    - args:
        - '-provider=openshift'
        - '-https-address=:9095'
        - '-http-address='
              .
              .
              .
        - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
        - '-skip-auth-regex=^/metrics'
      env:
        - name: HTTP_PROXY
        - name: HTTPS_PROXY
        - name: NO_PROXY
      image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:d20a1b4fc47d832c6878abcdf404f34881baa4cd6da3f034c8c4a0fb0a80ee5c
      name: alertmanager-proxy
      ports:
        - containerPort: 9095
          name: web
      resources:
        requests:
          cpu: 1m
          memory: 20Mi
      terminationMessagePolicy: FallbackToLogsOnError
      volumeMounts:
        - mountPath: /etc/tls/private
          name: secret-alertmanager-workload-tls
        - mountPath: /etc/proxy/secrets
          name: secret-alertmanager-workload-proxy
        - mountPath: /etc/pki/ca-trust/extracted/pem/
          name: alertmanager-trusted-ca-bundle
          readOnly: true
    - args:
        - '--secure-listen-address=0.0.0.0:9092'
        - '--upstream=http://127.0.0.1:9096' 
                .
                .
                .
        - '--logtostderr=true'
        - '--v=10'
      image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:83618ed7f04eb61c8cbf3bed789f78f9a6101f95c3fae80fd445858f4f353d9b
      name: kube-rbac-proxy
      ports:
        - containerPort: 9092
          name: tenancy
      resources:
        requests:
          cpu: 1m
          memory: 20Mi
      terminationMessagePolicy: FallbackToLogsOnError
      volumeMounts:
        - mountPath: /etc/kube-rbac-proxy
          name: secret-alertmanager-kube-rbac-proxy
        - mountPath: /etc/tls/private
          name: secret-alertmanager-workload-tls
    - args:
        - '--insecure-listen-address=127.0.0.1:9096'
        - '--upstream=http://127.0.0.1:9093'
        - '--label=namespace'
      image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:30937a7b191c25aeb29ea1061176a3d4c060e4bf33fdae7365036ebbe53299fd
      name: prom-label-proxy
      resources:
        requests:
          cpu: 1m
          memory: 20Mi
      terminationMessagePolicy: FallbackToLogsOnError
    - name: config-reloader
      resources:
        requests:
          cpu: 1m
          memory: 10Mi
  volumeMounts:
    - mountPath: /etc/pki/ca-trust/extracted/pem/
      name: alertmanager-trusted-ca-bundle
      readOnly: true
  version: v0.21.0
  volumes:
    - configMap:
        items:
          - key: ca-bundle.crt
            path: tls-ca-bundle.pem
        name: alertmanager-trusted-ca-bundle
        optional: true
      name: alertmanager-trusted-ca-bundle
  image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:732f3e260bd4d6bc28519e0d0df2582f4bea0ae49458cad32a9dc59bd0804776
  replicas: 3
  configSecret: alertmanager-workload-config
  # alertmanagerConfigNamespaceSelector: openshift-stakater-workload-monitoring
  logLevel: debug
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: test
  priorityClassName: system-cluster-critical
```
