### ISSUE TITLE
Improvement wanted to use the "Probe" crd

### ISSUE THREAD

**Issue by guidoffm** [prometheus-operator/prometheus-operator#4026]
For the "Probe" CRD there is not enough documentation.

What I want to achieve:

I want to define a probe that queries the node exporter on a host. I found out that this yaml works:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: myhost.example.com
  namespace: monitoring
spec:
  targets:
    staticConfig:
      static:
        - myhost.example.com
  prober:
    url: myhost.example.com:9100
    path: /metrics
```

The Probe API in the current form makes sense for the blackbox exporter.
But for just to query the node exporter this spec is not clear, because:

- I do both need `targets` and `prober` at the moment.
- I have to specify `path` or it defaults to `probe`

An easier to use spec should allow to specify the hostname in just one place and maybe it should allow an array of hostnames there.
