### ISSUE TITLE
Prometheus operator validating webhook doesn't accept last_over_time function in rule expression

### ISSUE THREAD

**Issue by Sh1ftry** [prometheus-operator/prometheus-operator#4030]
**What happened?**
Trying to apply
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blackbox-exporter.records
spec:
  groups:
  - name: probe
    rules:
    - record: target_pod:probe_success:last_over_24h
      expr: last_over_time(probe_success[24h])
```
ends with an error
```
The  "prometheusrules" is invalid: : 1:45: group "probe", rule 1, "target_pod:probe_success:last_over_24h": could not parse expression: 1:1: parse error: unknown function with name "last_over_time"
```
Promtool says the rule is fine
```
❯ promtool check rules rules.yaml
Checking rules.yaml
  SUCCESS: 1 rules found
```

**How to reproduce it (as minimally and precisely as possible)**:
Run `kubectl apply -f manifest.yaml` with above manifest and expect an error.

**Environment**

* Prometheus Operator version: v0.47.0
* Prometheus version: v2.26.0
