### ISSUE TITLE
Prometheus operator v0.43.0 not updating rules

### ISSUE THREAD

**Issue by MonicaMagoniCom** [prometheus-operator/prometheus-operator#4032]
Hi, I'm using prometheus operator v0.43.0 together with prometheus 2.24.1. The problem I'm having is that if a change a rule (kind PrometheusRule), this is never reloaded. If I take back the operator to v0.40.0 everything works fine. This is my configuration:

```
- apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  #namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.43.0
        image: quay.io/prometheus-operator/prometheus-operator:v0.43.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator

In prometheus statefulset:
  - args:
        - --web.console.templates=/etc/prometheus/consoles
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
        - --storage.tsdb.path=/prometheus
        - --storage.tsdb.retention.time=168h
        - --web.enable-lifecycle
        - --storage.tsdb.no-lockfile
        - --web.enable-admin-api
        - --web.route-prefix=/
        image: quay.io/prometheus/prometheus:v2.24.1
   - args:
        - --log-format=logfmt
        - --reload-url=http://localhost:9090/-/reload
        - --config-file=/etc/prometheus/config/prometheus.yaml.gz
        - --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
        command:
        - /bin/prometheus-config-reloader
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: quay.io/prometheus-operator/prometheus-config-reloader:v0.43.0
```
