### ISSUE TITLE
Alertmanager fails with slack api key from secrets

### ISSUE THREAD

**Issue by agardiman** [prometheus-operator/prometheus-operator#4037]
**What happened?**
If I use a configuration like the following
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: watchdog-default
  namespace: monitoring
  labels:
    release: watchdog
spec:
  route:
    groupBy: ['job']
    groupWait: 1m
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'slack'
  receivers:
    - name: 'slack'
      slackConfigs:
        - channel: '#channel-name'
          apiURL:
            key: 'webhookURL'
            name: 'slack-webhook'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-webhook
  namespace: monitoring
data:
  webhookURL: "aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvUkVEQUNURUQK"
```
(the value of `webhookURL` is the based64 of the dummy webhook `https://hooks.slack.com/services/REDACTED`)
the config reloader uptakes the AlertmanagerConfig, and merges it with with the default configuration. 

But the alertmanager doesn't restart because it finds an extra \n character at the end of its `api_url` templated string.

The exact errors I'm getting are:
From alertmanager config-reloader sidecar
```
level=error ts=2021-05-18T18:02:57.300784983Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 500 Internal Server Error; have you set `--web.enable-lifecycle` Prometheus flag?"
```

From alertmanager
```
level=info ts=2021-05-18T18:02:37.305Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=error ts=2021-05-18T18:02:37.305Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="parse \"https://hooks.slack.com/services/REDACTED\\n\": net/url: invalid control character in URL"
```

If I cat the content of `/etc/alertmanager/config/`:
```
/ $ cat /etc/alertmanager/config/alertmanager.yaml
route:
  receiver: "null"
  routes:
  - receiver: monitoring-watchdog-default-slack
    group_by:
    - job
    match:
      namespace: monitoring
    continue: true
    group_wait: 1m
    group_interval: 5m
    repeat_interval: 12h
receivers:
- name: "null"
- name: monitoring-watchdog-default-slack
  slack_configs:
  - api_url: |
      https://hooks.slack.com/services/REDACTED
    channel: '#channel-name'
templates: []
```

The invalid control character complain from the alertmanager is related to 
```
  - api_url: |
      https://hooks.slack.com/services/REDACTED
```
As you can see there shouldn't be any new line character detected for api_url. I'm not sure if the issue is with that non-multiline string that is marshalled into a "|" syntax  by the prometheus operator or if it's the  alertmanager that is unmarshalling incorrectly.

**Did you expect to see something different?**
I expect the alertmanager and the prometheus operator to marshal/unmarshal the yaml  file in a way that the alertmanager reload its config correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Using exactly the previous configuration with a vanilla kube-prometheus-stack helm chart deployment.

**Environment**
Kube prometheus stack kube-prometheus-stack-15.4.4
alertmanager: 0.21.0
prometheus-config-reloader: 0.47.0

* Prometheus Operator version:
Image:      quay.io/prometheus-operator/prometheus-operator:v0.47.0

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:
EKS

**Comment by simonpasquier** [comment]
Indeed we should trim the trailing `\n`. Would you like to contribute the fix?

**Comment by barrowkwan** [comment]
Hi, I wonder if this is fixed?  I hit the same problem and I have checked my yaml is correct.  thanks

**Comment by simonpasquier** [comment]
Tthis is still open. Can you make sure that your secret's value doesn't have a trailing \n?

**Comment by Jammicus** [comment]
I'll pick this up

**Comment by jeunii** [comment]
Hello. Where can I find documentation on providing the slack url from a secret ? 

```
  receivers:
    - name: 'slack'
      slackConfigs:
        - channel: '#channel-name'
          apiURL:
            key: 'webhookURL'
            name: 'slack-webhook'
```

I am going through this https://prometheus.io/docs/alerting/latest/configuration/#slack_config but it says nothing about `apiURL`

**Comment by simonpasquier** [comment]
@jeunii you want to look at https://prometheus-operator.dev/docs/operator/api/

**Comment by jeunii** [comment]
@simonpasquier thanks. any idea why i would get the error

```
level=error ts=2022-08-11T14:05:45.690413192Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"monitoring/monitoring-kube-prometheus-alertmanager\" failed: provision alertmanager configuration: failed to initialize from secret: yaml: unmarshal errors:\n  line 13: field apiURL not found in type config.plain"
```

my config is

```
      receivers:
      - name: 'null'
      - name: slack-pe
        slack_configs:
          - apiURL:
              key: apiURL
              name: slack-config
            channel: "#pe-infra-alerts"
            title: '{{ template "alertmanager.slack.titletext" . }}'
            title_link: '{{ .ExternalURL }}{{ template "alertmanager.slack.titlelink" . }}'
            text: '{{ template "alertmanager.slack.text" . }}'
```

secret:

```
 k get secrets slack-config -o yaml
apiVersion: v1
data:
  apiURL: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDBKMTRQRDdFL0IwM1NWNUtCU1RYL0RtdHN1ZVVBTzhBYXM5U25MalZadGMwTw==
kind: Secret
metadata:
  creationTimestamp: "2022-08-11T14:11:26Z"
  name: slack-config
  namespace: monitoring
  resourceVersion: "202474"
  uid: f79801e8-d468-4bab-8082-286a5e0d4ecf
type: Opaque

echo "<REDACTED>" | base64 -D
https://hooks.slack.com/services/<REDACTED>

```
