### ISSUE TITLE
Question mark in service monitor endpoint path not working

### ISSUE THREAD

**Issue by aendi123** [prometheus-operator/prometheus-operator#4040]
**What happened?**

A Question mark in the endpoint path is displayed correctly under "Configuration" in the Prometheus Webinterface but the scrape target is not working, because the ? is replaced by %3.

My Service Monitor:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab
  namespace: monitoring
  labels:
    prom-monitored-service: "true"
spec:
  selector:
    matchLabels:
      prom-monitored-service: "true"
  namespaceSelector:
    matchNames:
      - "gitlab"
  endpoints:
  - port: http-webservice
    path: /-/metrics?token=censored-token
```

I also tried:

```
path: "/-/metrics?token=censored-token"
path: '/-/metrics?token=censored-token'
path: '/-/metrics\?token=censored-token
```
Displayed correctly in the configuration:
![image](https://user-images.githubusercontent.com/40163655/118870348-bbf02b00-b8e6-11eb-87cc-dc8f83ef06d0.png)

Target not working:
![image](https://user-images.githubusercontent.com/40163655/118870534-f1951400-b8e6-11eb-96cc-53ce6fba8b54.png)

**Did you expect to see something different?**
The question mark should be displayed and used correctly in the configuration and the target.

Or ist there another way for Prometheus to pass this token to the targets?

**How to reproduce it (as minimally and precisely as possible)**:
Create a ServiceMonitor with a question mark in the endpoint path.

**Environment**

* Prometheus Operator version:
0.47.0

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
RKE

**Comment by paulfantom** [comment]
Try using [`params`](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#endpoint) for passing parameters in URI.

This should work:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab
  namespace: monitoring
  labels:
    prom-monitored-service: "true"
spec:
  selector:
    matchLabels:
      prom-monitored-service: "true"
  namespaceSelector:
    matchNames:
      - "gitlab"
  endpoints:
  - port: http-webservice
    path: /-/metrics
    params:
      token: censored-token
```

You also shouldn't store sensitive information in plaintext, so consider using `bearerTokenSecret` for storing tokens. This way `params` shouldn't be needed at all. Like in:
```
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab
  namespace: monitoring
  labels:
    prom-monitored-service: "true"
spec:
  selector:
    matchLabels:
      prom-monitored-service: "true"
  namespaceSelector:
    matchNames:
      - "gitlab"
  endpoints:
  - port: http-webservice
    path: /-/metrics
    bearerTokenSecret: ref-to-secret
```
