### ISSUE TITLE
opening storage failed

### ISSUE THREAD

**Issue by vignesh-v-nutanix** [prometheus-operator/prometheus-operator#4047]
**What happened?**
prometheus stateful sets going in crashloopbackoff

**Did you expect to see something different?**
i expected to see it running

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.38.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 350Mi
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
```

**Environment**

* Prometheus Operator version: 0.38
* 
*

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information: v1.18.0

    `kubectl version`v1.21.0
    

* Kubernetes cluster kind: kops cluster

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.38.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 350Mi
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
```

* Prometheus Operator Logs:

```
level=info ts=2021-05-26T16:06:52.068690591Z caller=main.go:423 msg="Stopping scrape discovery manager..."
level=info ts=2021-05-26T16:06:52.06872007Z caller=main.go:437 msg="Stopping notify discovery manager..."
level=info ts=2021-05-26T16:06:52.068730821Z caller=main.go:459 msg="Stopping scrape manager..."
level=info ts=2021-05-26T16:06:52.068740333Z caller=main.go:433 msg="Notify discovery manager stopped"
level=info ts=2021-05-26T16:06:52.06877132Z caller=main.go:419 msg="Scrape discovery manager stopped"
level=info ts=2021-05-26T16:06:52.068786841Z caller=manager.go:638 component="rule manager" msg="Stopping rule manager..."
level=info ts=2021-05-26T16:06:52.068801564Z caller=manager.go:644 component="rule manager" msg="Rule manager stopped"
level=info ts=2021-05-26T16:06:52.068822477Z caller=notifier.go:512 component=notifier msg="Stopping notification manager..."
level=info ts=2021-05-26T16:06:52.068861676Z caller=main.go:608 msg="Notifier manager stopped"
level=info ts=2021-05-26T16:06:52.06888916Z caller=main.go:453 msg="Scrape manager stopped"
level=error ts=2021-05-26T16:06:52.068969675Z caller=main.go:617 err="opening storage failed: open /prometheus/wal/00000002: permission denied"
```

**Anything else we need to know?**:
