### ISSUE TITLE
prometheus-prometheus-0 Pod failed when StorageSpec defined as volumeClaimTemplate

### ISSUE THREAD

**Issue by rcarre** [prometheus-operator/prometheus-operator#4054]
operator:v0.47.1
k8s cluster : Rancher/openstack

I don't get any error when using default emptyDir setup for StorageSpec. As soon as I update the config with volumeClainTemplate, both pvc and pv are created but the prometheus-prometheus-0 ends up with error. However, no error in promethus-operator pod logs.
Thanks for your support

```
level=info ts=2021-05-31T15:07:29.002Z caller=main.go:426 msg="Starting Prometheus" version="(version=2.27.1, branch=HEAD, revision=db7f0bcec27bd8aeebad6b08ac849516efa9ae02)" 
level=info ts=2021-05-31T15:07:29.002Z caller=main.go:431 build_context="(go=go1.16.4, user=root@fd804fbd4f25, date=20210518-14:17:54)" 
level=info ts=2021-05-31T15:07:29.002Z caller=main.go:432 host_details="(Linux 4.15.0-139-generic #143-Ubuntu SMP Tue Mar 16 01:30:17 UTC 2021 x86_64 prometheus-prometheus-0 (none))" 
level=info ts=2021-05-31T15:07:29.002Z caller=main.go:433 fd_limits="(soft=1048576, hard=1048576)" 
level=info ts=2021-05-31T15:07:29.002Z caller=main.go:434 vm_limits="(soft=unlimited, hard=unlimited)" 
level=error ts=2021-05-31T15:07:29.003Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied" 
panic: Unable to create mmap-ed active query log 
 
goroutine 1 [running]: 
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7fff13b71de3, 0xb, 0x14, 0x3652100, 0xc00087fa40, 0x3652100) 
	/app/promql/query_logger.go:117 +0x4e8 
main.main() 
	/app/cmd/prometheus/main.go:462 +0x58b0 
```

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: strimzi
spec:
  replicas: 1
  serviceAccountName: prometheus-server
  podMonitorSelector:
    matchLabels:
      app: strimzi
  serviceMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 4Gi
  enableAdminAPI: false
  ruleSelector:
    matchLabels:
      role: alert-rules
      app: strimzi
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager
      port: alertmanager
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by paulfantom** [comment]
It looks like files inside PV are stored with different user and group permissions. Consider using `securityContext` to run prometheus with different user.

**Comment by rcarre** [comment]
Thanks @paulfantom for your reply.
All namespace created in my cluster come with a psp (Pod Security Policies) with restricted unlike the default namespace which come with a psps unrestricted. My Prometheus setup is fully hosted in the default namepace.
Not sure to fully understand what you mean by running Prometheus with different user ... I guess that this part is handled by the operator in the same way as with EmptyDir ?
Do you suggest to update the securityContext Field from 
https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec ?
Thanks&Regards. Richard

**Comment by simonpasquier** [comment]
> Do you suggest to update the securityContext Field from
https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec ?

yes you probably need to pass something other than the default security context so your Prometheus container gets a uid/gid with the correct permissions (maybe look at `fsGroup`).

**Comment by rcarre** [comment]
I am managing Pod Security Policy by the means of RBAC; in this context, I do not understand well which value I should update securityContext with.

Here is  the ls -l  /prometheus output from prometheus container when emtyDir is used instead of volumeClaim:
```
drwxr-xr-x    2 nobody   nobody        4096 Jun  2 06:46 chunks_head
-rw-r--r--    1 nobody   nobody       20001 Jun  2 06:53 queries.active
drwxr-xr-x    2 nobody   nobody        4096 Jun  2 06:46 wal

```
This would mean that I should force my Persistent Volume to be mounted as nobody:nobody (65534:65534) so that Prometheus container can write on it ... ? In my mind, a pod-level security context will  result in settings being applied to volumes when they are mounted, where applicable, namely to match the fsGroup specified within the security context.

As an example, here is the prometheus-server ClusterRole update with psp:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-server
  labels:
    app: strimzi
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
      - prometheus-server
```
