### ISSUE TITLE
Targets is ZERO on prometheus after create servicemonitor

### ISSUE THREAD

**Issue by XiamenGeek** [prometheus-operator/prometheus-operator#4061]
**What did you do?**
I have created a servicemonitor which try to scrape metrics, but it not work. It's 0 UP on Prometheus Targets page. 
Actually  I can access this k8s service metric endpoint through the match labels and namespace. And this k8s service is located on [default] namespace
**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:
v0.31.1
    
    

* Kubernetes version information:

v1.15.0
    

* Kubernetes cluster kind:

kubeadm

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - targetPort: 1234
    interval: 30s 
    path: /metrics
```

* Prometheus Operator Logs:

no any error or warning log

**Anything else we need to know?**:
