### ISSUE TITLE
ExternalLabels not coming in all the metric

### ISSUE THREAD

**Issue by gr8Adakron** [prometheus-operator/prometheus-operator#4064]
I have configured Kube-state-metric/cadvisor pipeline, sending data to Prometheus-operator with High Availability along with externalLabels to be added to each metric but somehow `externalLabel` showing for some metric while absent for other (especially metrics by Cadvisor)

* Prometheus operator version : 0.46
* Kubernetes: 1.18
* Scraping Cadvisor using scrape config 
```
- job_name: kubernetes-cadvisor
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics/cadvisor
  scheme: https
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc.cluster.local:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
  metric_relabel_configs:
  - source_labels: [__name__]
    regex: '(container|machine)_(cpu|memory|network|fs)_(.+)'
    action: keep
  - source_labels: [__name__]
    regex: 'container_memory_failures_total' # unneeded large metric
    action: drop
```

For example common metric showing `container_cpu_usage_seconds_total` where 1st has externalLabel (`universe`) while 2nd doesnt:

1st:
```json
container_cpu_usage_seconds_total {
 beta_kubernetes_io_arch="amd64",
 beta_kubernetes_io_instance_type="n1-highcpu-4",
 beta_kubernetes_io_os="linux",
 cloud_google_com_gke_boot_disk="pd-balanced",
 cloud_google_com_gke_container_runtime="containerd",
 cloud_google_com_gke_nodepool="n1-highcpu-4-pool-1",
 cloud_google_com_gke_os_distribution="cos",
 cloud_google_com_machine_family="n1",
 cluster="cluster",
 cpu="total",
 env="gateway-prod",
 failure_domain_beta_kubernetes_io_region="asia-south1",
 failure_domain_beta_kubernetes_io_zone="asia-south1-b",
 id="/kubepods/burstable/pod4b352417-67bd-4609-9b79-7e46b375dfa0",
 instance="gke-cluster-n1-highcpu-4-pool-1-fb1a7da5-m49h",
 job="kubernetes-cadvisor",
 kubernetes_io_arch="amd64",
 kubernetes_io_hostname="gke-cluster-n1-highcpu-4-pool-1-fb1a7da5-m49h",
 kubernetes_io_os="linux",
 namespace="gateway",
 node_kubernetes_io_instance_type="n1-highcpu-4",
 pod="portal-gateway-6cc8d54bf9-bjm9h",
 prometheus="prometheus/prometheus",
 prometheus_replica="prometheus-prometheus-0",
 sg="vm_v1_8428",
 topology_kubernetes_io_region="asia-south1",
 topology_kubernetes_io_zone="asia-south1-b",
 universe="milkyway"
}
```

2nd
```json
container_cpu_usage_seconds_total{
 beta_kubernetes_io_arch="amd64",
 beta_kubernetes_io_instance_type="n1-highcpu-4",
 beta_kubernetes_io_os="linux",
 cloud_google_com_gke_boot_disk="pd-balanced",
 cloud_google_com_gke_container_runtime="containerd",
 cloud_google_com_gke_nodepool="n1-highcpu-4-pool-1",
 cloud_google_com_gke_os_distribution="cos",
 cloud_google_com_machine_family="n1",
 cluster="cluster",
 container="ambassador",
 cpu="total",
 env="gateway-prod",
 failure_domain_beta_kubernetes_io_region="asia-south1",
 failure_domain_beta_kubernetes_io_zone="asia-south1-a",
 id="/kubepods/burstable/podd21312",
 image="docker.io/datawire/ambassador:1.13.4",
 instance="gke-cluster-n1-highcpu-4-pool-1-bc637d58-p0ru",
 job="kubernetes-cadvisor",
 kubernetes_io_arch="amd64",
 kubernetes_io_hostname="gke-cluster-n1-highcpu-4-pool-1-bc637d58-p0ru",
 kubernetes_io_os="linux",
 name="24919392",
 namespace="gateway",
 node_kubernetes_io_instance_type="n1-highcpu-4",
 pod="portal-gateway-6cc8d54bf9-jcdgp",
 prometheus="prometheus/prometheus",
 prometheus_replica="prometheus-prometheus-0",
 sg="vm_v1_8428",
 topology_kubernetes_io_region="asia-south1",
 topology_kubernetes_io_zone="asia-south1-a"
}
```

The only difference I see is the node-location.. any help will be appreciated. Thanks

**Comment by gr8Adakron** [comment]
@jfchevrette

**Comment by simonpasquier** [comment]
> sending data to Prometheus-operator with High Availability along with externalLabels to be added to each metric

I'm not sure to understand this. Do you use Prometheus remote write or federation? External labels are only added when Prometheus communicates with Alertmanager, federation and remote write endpoints.
Could you also share the generated config?

**Comment by gr8Adakron** [comment]
@simonpasquier 

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: prometheus
spec:
  additionalScrapeConfigs:
    key: sc-jobs.yaml
    name: sc-configmap
  enableAdminAPI: false
  externalLabels:
    cluster: milkyway-gpu-cluster
    universe: milkyway
  remoteWrite:
  - queueConfig:
      capacity: 5000
    url: https://<victoria-metric-VM>vic1/api/v1/write
  replicas: 1
  resources:
    requests:
      memory: 400Mi
  serviceAccountName: prometheus
  serviceMonitorSelector: {}
```

This is the Prometheus config with externalLabels `milkyway` and exporting it to Victoria Metric VM.
