### ISSUE TITLE
Option to turn off the default relabel_configs

### ISSUE THREAD

**Issue by qudongfang** [prometheus-operator/prometheus-operator#4065]
**What is missing?**

Option to turn off the default relabel_configs.

**Why do we need it?**

It ends with some useless extra labels with `kube-state-metrics`.

servicemonitor

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kube-prometheus-stack-kube-state-metrics
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 16.0.1
    chart: kube-prometheus-stack-16.0.1
    helm.toolkit.fluxcd.io/name: prometheus-stack
    helm.toolkit.fluxcd.io/namespace: monitoring
    heritage: Helm
    release: prometheus-stack
  name: prometheus-stack-kube-prom-kube-state-metrics
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    port: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-stack
      app.kubernetes.io/name: kube-state-metrics
```

the default `relabel_configs` will be 

```
relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: (.*)
    target_label: __tmp_prometheus_job_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_managed_by]
    separator: ;
    regex: prometheus-operator
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_service_label_k8s_app]
    separator: ;
    regex: kubelet
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: https-metrics
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Node;(.*)
    target_label: node
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Pod;(.*)
    target_label: pod
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: (.*)
    target_label: container
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_label_k8s_app]
    separator: ;
    regex: (.+)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: https-metrics
    action: replace
  - source_labels: [__metrics_path__]
    separator: ;
    regex: (.*)
    target_label: metrics_path
    replacement: $1
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 1
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: "0"
    replacement: $1
    action: keep
```

and the metrics look like

`kube_pod_labels{container="kube-state-metrics", endpoint="http", exported_namespace="flux-system", exported_pod="helm-controller-7b7fc87856-b5hp5", instance="10.160.34.178:8080", job="kube-state-metrics", namespace="monitoring", pod="prometheus-stack-kube-state-metrics-65f867bbc-9fvcs", service="prometheus-stack-kube-state-metrics"}`

`kube_service_labels{container="kube-state-metrics", endpoint="http", exported_namespace="default", exported_service="kubernetes", instance="10.160.34.178:8080", job="kube-state-metrics", namespace="monitoring", pod="prometheus-stack-kube-state-metrics-65f867bbc-9fvcs", service="prometheus-stack-kube-state-metrics"}`

I would be nice to have only the labels exported by the `kube-state-metrics`, even though we might be able to add more relabel_configs to remove them.

**Environment**

* Prometheus Operator version:

```
    Container ID:  docker://abe1902af11ad8f29dcb8c012302e272998c0b5f8bf793ed77885406df7aafbd
    Image:         quay.io/prometheus-operator/prometheus-operator:v0.47.1
    Image ID:      docker-pullable://quay.io/prometheus-operator/prometheus-operator@sha256:dd7b90c19e2bdce9db5832d9f4e51045b86972a1b1cf13f8e6fffcc505c93d7c
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
you can still drop the labels that you don't care with additional relabel_configs/metric_relabel_configs. I'm not sure that exposing a parameter to disable default relabel_configs make sense.

**Comment by paulfantom** [comment]
I agree with Simon, dropping labels with an established mechanism of using relabel_configs/metric_relabel_configs is IMHO better than introducing another parameter for this small feature.

**Comment by qudongfang** [comment]
Cool, thanks for your suggestions and I'll close this issue.

For anyone who might have the same issue as me.
```
        relabelings:
          - regex: (container|endpoint|namespace|pod|service)
            action: labeldrop
        metricRelabelings:
          - regex: instance
            action: labeldrop
```
