### ISSUE TITLE
Add .spec.prober.tlsConfig to Probe

### ISSUE THREAD

**Issue by snuggie12** [prometheus-operator/prometheus-operator#4121]
**What is missing?**
Looks like the new `.spec.tlsConfig` on a `Probe` is from the exporter to the targets. I would like to add a `tlsConfig` from prometheus to the bb-exporter similar to `ServiceMonitor` where you list files for your cert, key and ca. 

I'm thinking `.spec.prober` would be a good spot since `.spec.prober.scheme` is there and I think is the equivalent field as `ServiceMonitor`.

Here is an example from `ServiceMonitor` for what I'm looking for:
```
spec:
  endpoints:
  - path: /metrics
    port: http-service
    scheme: https
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      insecureSkipVerify: true
      keyFile: /etc/prom-certs/key.pem
```

**Why do we need it?**
We use istio and successfully scrape metrics by attaching a sidecar to the prometheus server which serves up the required certs (we do not route outbound traffic over istio though.) However, someone recently asked us to probe a target which has istio enabled. Once turning it on we got failed scrapes.

**Environment**

* Prometheus Operator version:

    `image: quay.io/prometheus-operator/prometheus-operator:v0.48.1`
    
    

**Anything else we need to know?**:
I see the `.spec.tlsConfig` is `Secret` or `ConfigMap` based. It's really important the `tlsConfig` I'm requesting is file based just like the `ServiceMonitor` for istio to work.

**Comment by simonpasquier** [comment]
see https://github.com/prometheus-operator/prometheus-operator/issues/3922#issuecomment-802899950 as for why Probe and PodMonitor don't support access to arbitrary files on the filesystem of the Prometheus container. Can you elaborate why using `Secret` and `ConfigMap` references doesn't work for you?

**Comment by snuggie12** [comment]
It's a performance/security feature of istio. The current SDS provisioning method doesn't work the same as described (there's no more `citadel` `DaemonSet`), but the downsides of making a `Secret` is listed in the first few paragraphs here: https://istio.io/v1.1/docs/tasks/security/auth-sds/.

None of this would be needed if normal traffic could flow through istio, but the OP in #3922 explains why prometheus has a special setup and doesn't just use automatic sidecar routing.

I guess one thing that is a bit unclear to me is that this isn't supported in just the operator? I don't see any github issues in the prometheus repo about not supporting files in the future.

Would it be more secure (and possible) to somehow setup a trusted tlsConfig setup? One annoyance is having to list out the same 5 or 6 lines over and over again in our `ServiceMonitors` anyways. Something like a `tlsConfigRef`?? That way we're not allowing end users to arbitrarily set up files, but using files is still permitted? I know that goes well beyond the scope of this issue, but I'm trying to make lemonade out of lemons.

```
# current servicemonitor repeated lines
    scheme: https
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      insecureSkipVerify: true
      keyFile: /etc/prom-certs/key.pem

# proposed fix where admins make the tlsConfig
  scheme: https
  tlsConfigRef:
    name: foo
    namespace: bar
```

**Comment by simonpasquier** [comment]
I think that we can improve the way TLS configuration is currently supported/exposed. We never allowed pod monitors (and probes) to read arbitrary files from the filesystem of the Prometheus container because it's very easy to leak sensitive information in case of (bearer) token and basic auth. I agree that it's a bit different for TLS client authentication because the client key is never issued to the monitored endpoint. Having said that, if we were to relax this limitation for TLS, the UX wouldn't be great anyway IMHO because you would still have a tight coupling between the Prometheus configuration and the monitoring resources (e.g. you have to know in advance where the TLS materials are mounted in the Prometheus pod).

What I would imagine instead:
* Prometheus can be configured with a list of TLS key/cert that can be used for client authentication (the TLS keys/certs are referenced by SecretKeySelector).
* Service/pod monitors and probes can specify that they expect Prometheus to use TLS client authentication + which identity (e.g. CommonName).
* The operator extracts CommonName from the TLS keys and selects the TLS key/cert matching with the requirements. Monitors for which no identity is found are ignored.

@s-urbaniak asking kindly for your feedback on this one with your authentication expert's hat :)

**Comment by snuggie12** [comment]
I think I followed most of that except for the `SecretKeySelector` part. Are you referencing a k8s resource or are files going to be possible? The istio sidecar can only output to a directory.

**Comment by simonpasquier** [comment]
@snuggie12 do you mean that the Istio sidecar would generate the TLS cert/key on disk and they would be accessible to the Prometheus container?
I think that we could support both `SecretKeySelector`s and files from the filesystem of the Prometheus container in that case.

**Comment by snuggie12** [comment]
> @snuggie12 do you mean that the Istio sidecar would generate the TLS cert/key on disk and they would be accessible to the Prometheus container?

@simonpasquier yeah, that's exactly how it works.

**Comment by caiobegotti** [comment]
If I got the issue behind this it's also blocking people from setting up a `Probe` to monitor ingress routes from something like Traefik, that exposes them via internal domains but depends on Traefik's custom cert files not being available in a `tlsConfig` of probes. Is this still something people are struggling with or it's just me?

**Comment by snuggie12** [comment]
@caiobegotti yeah, it's still a thing for `Probe` and `PodMonitor` resources.

I think some of this got negated by putting istio on the blackbox monitor pods and altering istio's instructions on the annotations to route through. prometheus now only routes traffic through istio if it is on the `Service`'s CIDR block which does an http scrape to the bb exporter which does an http probe to an internal service.

However, I believe we still have some occasional edge cases where this would very much be useful.

I believe there's also a possibility of not using the `Probe` at all and manually making the prometheus config the operator would have done since the functionality itself is there I think.

**Comment by pre** [comment]
Would be great to be able to read the mTLS Certificate from a file for `PodMonitor` like it's currently possible for `ServiceMonitor`.

The Istio mTLS with Prometheus instructions currently describe this file based approach, and it only works for `ServiceMonitor`. 

The `PodMonitor` can not currently read the Istio provided mTLS assets from a file, and they are not available as a Secret or a ConfigMap.

* ServiceMonitor tlsConfig with files: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#tlsconfig
* PodMonitor `tlsConfig` with ConfigMap/Secret (no support for files): https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#podmetricsendpointtlsconfig

Desired configuration for `PodMonitor` would be the same as for `ServiceMonitor`: 

```yaml
  endpoints:
  - port: https-metrics
    path: "/metrics"
    scheme: https
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      keyFile: /etc/prom-certs/key.pem
      insecureSkipVerify: true
 ```

**Comment by JoaoBraveCoding** [comment]
AFAIK this was intended with the introduction of SafeTLSConfig in https://github.com/prometheus-operator/prometheus-operator/pull/3370 see comment [here for an explanation](https://github.com/prometheus-operator/prometheus-operator/issues/3922#issuecomment-802899950) as to why. However, [Simon suggested an alternative](https://github.com/prometheus-operator/prometheus-operator/issues/4121#issuecomment-881436312) that might just work but we haven't had the time to implement it.

**Comment by pre** [comment]
State of today: With `STRICT` Istio mTLS, all Prometheus endpoints need to be excluded from mTLS. 

It's not a problem when the metrics can be served from a different port than the actual application server. However, one needs to ensure the metrics endpoint cannot be used to expose anything else than the intended metrics. Otherwise disabling mTLS for Prometheus may accidentally expose the whole application without mTLS. 

If both PodMonitor and ServiceMonitor supported the file based attributes (caFile, certFile, keyFile), then Prometheus presumably could work with mTLS. However, without file based support for PodMonitor, the only option seems to provide port level exclusion from mTLS to all Prometheus metrics endpoints. :/

**Comment by JoaoBraveCoding** [comment]
I see... this is tricky indeed. I'm not familiar with Istio but wouldn't be possible to change it to provide the mTLS files in Secret form? 🤔 Seems like a better change than allowing the file-based attributes in PodMonitor and Probe.

**Comment by snuggie12** [comment]
> I see... this is tricky indeed. I'm not familiar with Istio but wouldn't be possible to change it to provide the mTLS files in Secret form? 🤔 Seems like a better change than allowing the file-based attributes in PodMonitor and Probe.

@JoaoBraveCoding no, that's not how istio works. The same level of security the maintainers are looking for where certs are not stored on file systems is how `istio` _**normally**_ works. The certs are not on the filesystem of the sidecar container. However, we want to share this cert with the prometheus container and thus output it to a file and they share a volume mount. The irony is that the istio setup is more secure than how a `PodMonitor` or `Probe` works (there's not even a `Secret` which could be read by another workload potentially,) but due to a completely unrelated piece of data (a bearer token being stored as a file,) this is considered not secure.

Only solution I see (besides start discriminating between safe files to read on a file system and unsafe ones,) would be yet another sidecar which reads from the cert directory and creates a `Secret` which can be read from these two CRDs.

**Comment by simonpasquier** [comment]
I've sketched a potential solution in https://github.com/prometheus-operator/prometheus-operator/issues/4121#issuecomment-881436312 but unfortunately I've got no time to write down a design doc. If anybody wants to give it a try, I'm more than happy to provide help.

**Comment by EronWright** [comment]
@simonpasquier, I'm unsure whether selecting a certificate as you describe is practical, or how it would apply to client certificates.

May I propose an alternative solution? The idea is basically to provide a default TLS configuration in the `Prometheus` spec, to be applied to the scrapes.

*Option 1*
One variant is that the configuration is applied to all scrapes, or possibly all scrapes that don't supply a TLS configuration.   This approach would work for the Istio case, if all the scrape endpoints are mTLS-based.
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
spec:
  scrapeTlsConfig:
      caFile: "/etc/prom-certs/root-cert.pem"
      certFile: "/etc/prom-certs/cert-chain.pem"
      keyFile: "/etc/prom-certs/key.pem"
      insecureSkipVerify: true
```

Another option (which I prefer) would be to introduce a notion of  _scrape class_, akin to a Kubernetes _storage class_. Whether with a new resource or with a new section in `Prometheus`, define settings to be applied to all scrapes of a certain class. The `PodMonitor` would allow the user to select a class, and perhaps have a good default for simplicity.

```yaml
# define a scrape class for administrator-provided scrape settings
apiVersion: monitoring.coreos.com/v1
kind: ScrapeClass
metadata:
  name: istio
spec:
  tlsConfig:
      caFile: "/etc/prom-certs/root-cert.pem"
      certFile: "/etc/prom-certs/cert-chain.pem"
      keyFile: "/etc/prom-certs/key.pem"
      insecureSkipVerify: true
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
spec:
  # optional: set a default scrape class
  scrapeClass: istio
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
spec:
  podMetricsEndpoints:
    - port: http
      scrapeClass: istio
```

If it helps, I would be happy to submit a PR based on one of these options.
