### ISSUE TITLE
Alertmanager listen addr and peer addr family mismatch in Dual Stack cluster

### ISSUE THREAD

**Issue by Jean-Daniel** [prometheus-operator/prometheus-operator#4135]
**What happened?**

Prometheus operator chooses IPv6 as listen address for alert manager cluster, but `alertmanager-operated` host name resolve only to IPv4.

Despite the fact that the cluster (and the alert manager pod) are using IPv4 as primary family (first IP), prometheus controller still try to use IPv6 for cluster.listen-address.

```
kubectl describe pod alertmanager-main-0
…
Status:       Running
IP:           10.145.0.149
IPs:
  IP:           10.145.0.149
  IP:           fd00:abba:96fb::7a
…
```

Alert manager command line is:  

```
/bin/alertmanager --config.file=/etc/alertmanager/config/alertmanager.yaml --storage.path=/alertmanager --data.retention=120h --cluster.listen-address=[fd00:abba:96fb::7a]:9094 --web.listen-address=:9093 --web.route-prefix=/ --cluster.peer
=alertmanager-main-0.alertmanager-operated:9094 --cluster.peer=alertmanager-main-1.alertmanager-operated:9094 --cluster.peer=alertmanager-main-2.alertmanager-operated:9094 --cluster.reconnect-timeout=5m
```

This causes failure in alertmanager cluster creation as the membres fails to establish connection.

**Did you expect to see something different?**

The operator uses IPv4 (or IPv6) for every addresses. Or it listen on all addresses instead of forcing listen address on a single address.

**How to reproduce it (as minimally and precisely as possible)**:

This is a simple monitoring stack deployed using kube-prometheus on a dual-stack cluster running Kubernetes 1.21.

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.48.1`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

    Kubeadm cluster with dual stack feature flag enabled, and all nodes / kubelet have 2 IPs (1 IPv4 and 1 IPv6). 

Runtime:  CRI-O / crun.

CNI: Cilium 1.10

**Comment by Jean-Daniel** [comment]
After some check, it looks like this is more a Kubernetes bug than a prometheus operator bug:

`kubectl get -n monitoring pod/alertmanager-main-0 -o yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  …
spec:
  containers:
  - args:
    - --config.file=/etc/alertmanager/config/alertmanager.yaml
    - --storage.path=/alertmanager
    - --data.retention=120h
    - --cluster.listen-address=[$(POD_IP)]:9094
    - --web.listen-address=:9093
    - --web.route-prefix=/
    - --cluster.peer=alertmanager-main-0.alertmanager-operated:9094
    - --cluster.peer=alertmanager-main-1.alertmanager-operated:9094
    - --cluster.peer=alertmanager-main-2.alertmanager-operated:9094
    - --cluster.reconnect-timeout=5m
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
…
status:
  …
  podIP: 10.145.0.149
  podIPs:
  - ip: 10.145.0.149
  - ip: fd00:abba:96fb::7a
```

```
kubectl exec pod/alertmanager-main-0 -- printenv | grep POD_IP
POD_IP=fd00:abba:96fb::7a
```
