### ISSUE TITLE
Invalid alert labels in PrometheusRule rule blocks reloading of other valid rules

### ISSUE THREAD

**Issue by amuraru** [prometheus-operator/prometheus-operator#4181]
**What happened?**

Invalid alert labels in `PrometheusRule` rule blocks reloading of valid rules
I see this in prom logs:
```
level=error ts=2021-07-22T21:01:10.938Z caller=manager.go:956 component="rule manager" msg="loading groups failed" err="/etc/prometheus/rules/prometheus-prometheus-promoperator-prometheus-rulefiles-0/ns-team-prj-service.yaml: group \"API Metrics\", rule 1, \"memory usage\": invalid label name: app.kubernetes.io/part-of"
level=error ts=2021-07-22T21:01:10.938Z caller=main.go:977 msg="Failed to apply configuration" err="error loading rules, previous rule set restored"
```

This was generated apparently by a rogue alert defn where an invalid rule label was defined:
```yaml
 alert:API Metrics
          expr: >
           .....
          for: 10m
          labels:
            app.kubernetes.io/part-of: service
            env: prod
```

**Did you expect to see something different?**

I would expect the operator checks for alert rule definition validity and doesn't update the prom rules files if invalid rules are defined. This is especially useful in multi-tenant environments where PrometheusRules are defined by tenants of a central operator
