### ISSUE TITLE
Prometheus operator probes different target labels in one probe config

### ISSUE THREAD

**Issue by benbenai7786** [prometheus-operator/prometheus-operator#4186]
Hi guys, I am a little confused about prometheus operator probes config, here is the request:
I want to monitor serveral static ip by icmp, each ip has its own labels, but I found probe config only support target labels like the following:
```
spec:
  interval: 10s
  jobName: icmp
  module: icmp
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  scrapeTimeout: 3s
  targets:
    staticConfig:
      labels:
        labelone: test
        labeltwo: test2
      static:
      - 8.8.8.8
```
That means I have to create another job name when I want to monitor such as 9.9.9.9 with labelone: abc ....... I think each ip generating each job name for prometheus is a little unconvienent. Do you have any suggestions? My purpose is using one probe config for monitoring different ip with different labels such as:
```
static_configs:
  - targets: ['https://www.google.co.in/']
    labels:
      name: `GoogleIndia`
  - targets: ['https://www.google.co.uk/']
    labels:
      name: `GoogleUK`
  - targets: ['https://www.google.fr/']
    labels:
      name: `GoogleFrance`
```

**Comment by simonpasquier** [comment]
There might another way but you should be able to achieve this with `relabelingConfigs`:

```
spec:
  interval: 10s
  jobName: icmp
  module: icmp
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  scrapeTimeout: 3s
  targets:
    staticConfig:
  - targets:
    - 'https://www.google.co.in/'
    - 'https://www.google.co.uk/'
    - 'https://www.google.fr/'
  relabelingConfigs:
  - sourceLabels: [instance]
    regex: '.+google\.co\.in/'
    targetLabel: name
    replacement: GoogleIndia
  - sourceLabels: [instance]
    regex: '.+google\.co\.uk/'
    targetLabel: name
    replacement: GoogleUK
  - sourceLabels: [instance]
    regex: '.+google\.fr/'
    targetLabel: name
    replacement: GoogleFrance
```
