### ISSUE TITLE
Validating admission webhook incorrectly rejects valid thanos rule

### ISSUE THREAD

**Issue by amuraru** [prometheus-operator/prometheus-operator#4199]
**What happened?**

When validating admission webhook is enabled, a valid Thanos `PrometheusRule` defining `partial_response_strategy` field ([docs](https://github.com/thanos-io/thanos/blob/main/docs/components/rule.md#partial-response)) is rejected as invalid.

**Did you expect to see something different?**

Valid rule is accepted as valid by the admission webhook

**How to reproduce it (as minimally and precisely as possible)**:

Create a PrometheusRule with the following spec:

```yaml
spec:
  groups:
  - name: "test.rules"
    partial_response_strategy: "abort"
    rules:
      ...
```

Validation fails due to unknown `partial_response_strategy` field

**Environment**

* Prometheus Operator version:
`0.49`

* Kubernetes version information:
`1.21`

* Kubernetes cluster kind:
`kind`
