### ISSUE TITLE
Can I use probe to monitor a static target and get metrics?

### ISSUE THREAD

**Issue by amaothree** [prometheus-operator/prometheus-operator#4208]
**What I need to know?**

I found `probe` CRD may can help me to get a metrics from a static target. But there are no docs or example to help me to make a probe yaml. Can anyone help me with a probe example? the example ip could be 0.0.0.0:8080.

--Original Question--
Hej, developers. There is a **static** URL of a target that I want to monitor via the prometheus operator. For some reason, I don't know the label name of the service or namespace. How should I fill the serviceMonitor crd yaml?

**Environment**

* Prometheus Operator version:

    `v0.49.0`
    
    

* Kubernetes version information:

    `v1.22.0`
    

* Kubernetes cluster kind:

    `kubeadm init`

**Comment by amaothree** [comment]
Oh, I just learned I should use `Probe` CRD not serviceMonitor. I am not sure is it right. I will test it and will close the issue later if it works.

**Comment by amaothree** [comment]
Solved this: just set the prober same with the target. TBH, I can not understant why prober should be set same as target. but it is works.
```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: probe-sample
  namespace: monitoring

spec:
  interval: 5s
  jobName: probe-sample
  scrapeTimeout: 2s
  prober:
    url: example.com:8080
    scheme: http
  targets:
    staticConfig:
      static:
      - example.com:8080
```
