### ISSUE TITLE
No endpoint for custom target

### ISSUE THREAD

**Issue by ggordonhall** [prometheus-operator/prometheus-operator#4210]
Hi, I'm trying to configure Prometheus monitoring for an API. I can see that the target exists, but there is no endpoint.

![Screenshot 2021-08-12 at 15 32 02](https://user-images.githubusercontent.com/24595376/129215418-87fc9ed6-427d-4052-898d-2bacb5b32ed7.png)

I installed the Prometheus Operator Helm Chart and created a Prometheus object:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: prometheus
    prometheus: service-prometheus
  name: service-prometheus
  namespace: prometheus
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-prometheus-kube-prometheus-alertmanager
      namespace: prometheus
      port: web
  baseImage: quay.io/prometheus/prometheus
  logLevel: info
  paused: false
  replicas: 1
  retention: 2d
  routePrefix: /
  ruleSelector:
    matchLabels:
      prometheus: service-prometheus
      role: alert-rules
  serviceAccountName:  prometheus-prometheus-kube-prometheus-prometheus
  serviceMonitorSelector:
    matchExpressions:
    - key: serviceapp
      operator: Exists
```

My service monitor config is:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-search-api
  namespace: prometheus
  labels:
    app: monitoring-search-api
    serviceapp: monitoring-search-api
    release: prometheus
spec:
  selector:
    matchLabels:
      # Target app service
      app.kubernetes.io/instance: search-api
      app.kubernetes.io/name: search-api
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
```

The target service is:

```
Name:                     search-api
Namespace:                default
Labels:                   app.kubernetes.io/instance=search-api
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=search-api
                          app.kubernetes.io/version=1.16.0
                          helm.sh/chart=search-api-0.1.0
Annotations:              meta.helm.sh/release-name: search-api
                          meta.helm.sh/release-namespace: default
Selector:                 app.kubernetes.io/instance=search-api,app.kubernetes.io/name=search-api
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       ****
IPs:                      ****
LoadBalancer Ingress:     ****
Port:                     http  8080/TCP
TargetPort:               http/TCP
NodePort:                 http  ****/TCP
Endpoints:                ****:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

And the deployment:

```
Name:                   search-api
Namespace:              default
CreationTimestamp:      Thu, 05 Aug 2021 14:54:31 +0100
Labels:                 app.kubernetes.io/instance=search-api
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=search-api
                        app.kubernetes.io/version=1.16.0
                        helm.sh/chart=search-api-0.1.0
Annotations:            deployment.kubernetes.io/revision: 22
                        meta.helm.sh/release-name: search-api
                        meta.helm.sh/release-namespace: default
Selector:               app.kubernetes.io/instance=search-api,app.kubernetes.io/name=search-api
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/instance=search-api
                    app.kubernetes.io/name=search-api
  Service Account:  search-api
  Containers:
   search-api:
    Image:        ****
    Port:         8080/TCP
    Host Port:    0/TCP
    Liveness:     ****
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
```

Would be very grateful for any help/advice here!

Thanks

**Environment**
Amazon EKS

**Prometheus Operator image**
quay.io/prometheus-operator/prometheus-operator:v0.49.0

**Kubernetes version information**
    Kubernetes Client: v1.21.3
    Kubernetes Server: v1.21.2-eks-0389ca3
