### ISSUE TITLE
alertmanger Failed to resolve alertmanager-main-0.alertmanager-operated:9094

### ISSUE THREAD

**Issue by XzBuleSky** [prometheus-operator/prometheus-operator#4224]
**What happened?**
Hello! I encountered two problems with the AlertManager service.

**The first problem is the alertManager high availability error message.**
```
level=warn ts=2021-08-19T09:51:05.495Z caller=cluster.go:251 component=cluster msg="failed to join cluster" err="3 errors occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.254.0.2:53: no such host\n\t* Failed to resolve alertmanager-main-1.alertmanager-operated:9094: lookup alertmanager-main-1.alertmanager-operated on 10.254.0.2:53: no such host\n\t* Failed to resolve alertmanager-main-2.alertmanager-operated:9094: lookup alertmanager-main-2.alertmanager-operated on 10.254.0.2:53: no such host\n\n"
```
The log information shows that alertManager cannot be resolved to `alertmanager-main-0.alertmanager-operated` using coreDNS.
Here's my test result: `alertmanager-main-0.alertmanager-operated' can't connect properly, But `alertmanager-main-0.alertmanager-operated.monitoring.svc.cluster.local` connected properly

Should excuse me I how to modify the alertmanager configuration information, set to `alertmanager-main-0.alertmanager-operated.monitoring.svc.cluster.local` (`cluster. peer`)
```
$ ping alertmanager-main-2.alertmanager-operated -c 4
ping: alertmanager-main-0.alertmanager-operated: Name or service not known

$  ping alertmanager-main-0.alertmanager-operated.monitoring.svc.cluster.local -c 4
PING alertmanager-main-0.alertmanager-operated.monitoring.svc.cluster.local (172.30.167.8) 56(84) bytes of data.
64 bytes from 172-30-167-8.alertmanager-main.monitoring.svc.cluster.local (172.30.167.8): icmp_seq=1 ttl=63 time=0.251 ms
64 bytes from 172-30-167-8.alertmanager-main.monitoring.svc.cluster.local (172.30.167.8): icmp_seq=2 ttl=63 time=0.254 ms
64 bytes from 172-30-167-8.alertmanager-main.monitoring.svc.cluster.local (172.30.167.8): icmp_seq=3 ttl=63 time=0.313 ms
64 bytes from 172-30-167-8.alertmanager-main.monitoring.svc.cluster.local (172.30.167.8): icmp_seq=4 ttl=63 time=0.225 ms
```

**The second problem is that the alertmanager configuration is incorrect**
Why does the configuration not take effect
```
$ cat alertmanager-secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.22.2
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ["severity",'alertname']
      receiver: 'webhook1'
      routes:
      - match_re:
          severity: warning
        receiver: webhook2
    receivers:
    - name: webhook1
      ....
      ....
    - name: webhook2
      ...
      ...
```
```
$ kubectl exec -it alertmanager-main-0  -n monitoring   -- cat /etc/alertmanager/config/alertmanager.yaml
route:
  receiver: 'null'
receivers:
- name: 'null'
```

> alertmanager-alertmanager.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.22.2
  name: main
  namespace: monitoring
spec:
  image: quay.io/prometheus/alertmanager:v0.22.2
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.22.2
  replicas: 3
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 4m
      memory: 100Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: 0.22.2
```
>

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    
```
Image:      quay.io/prometheus-operator/prometheus-operator:v0.49.0
```
* Kubernetes version information:

    `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T13:00:45Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
