### ISSUE TITLE
No target appears in UI, but no errors either with certain service monitors

### ISSUE THREAD

**Issue by a-roberts** [prometheus-operator/prometheus-operator#4227]
**What did you do?**

Enabled user defined workload monitoring on OCP 4.8.2, created an additional ServiceMonitor, observed it never appears unless it's of a certain (non-working) configuration.

**Did you expect to see some different?**

I expected my ServiceMonitor to result in a target on the UI regardless of it working or not, as I have an existing, partially erroring, ServiceMonitor

**Environment**
OCP 4.8.2

* Prometheus Operator version:

```
    Image:      quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:e5543a44a6c1ca4938d90f7c3961424c840e861841679dd6f04c7c710aa9aaf8
```

I don't have a visible operator or ClusterServiceVersion, but if I get a terminal inside the Prometheus operator container I see:

```
/root/buildinfo/content_manifests/prometheus-operator-container-v4.8.0-202106291913.p0.git.9d679a1.assembly.stream.json
/root/buildinfo/Dockerfile-openshift-ose-prometheus-operator-v4.8.0-202106291913.p0.git.9d679a1.assembly.stream
```

* Kubernetes version information:

    `kubectl version`

```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+051ac4f", GitCommit:"051ac4f6786868fa0316800752e1905f31830383", GitTreeState:"clean", BuildDate:"2021-07-16T17:46:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

my client is 1.17.

* Kubernetes cluster kind:

It's a very large OpenShift one...all x86.

* Manifests:

Here's a non-working ServiceMonitor definition along with some comments/notes along the way I found helpful for myself after a weekend away...

```
#  oc port-forward -n openshift-user-workload-monitoring pod/prometheus-user-workload-0 9090 for debugging
# Kill operator pod - looks like if bad config it won't appear, but no errors
# oc delete pod -l app.kubernetes.io/name=prometheus-operator -n openshift-user-workload-monitoring
# Hint, access targets with: http://localhost:9090/targets
# Todo raise with community
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: adam-tm-service-monitor
  namespace: acme-iaf
spec:
  endpoints:
  #- port: prometheus # this always goes to 9249 which gives connection refused, but it does appear in the ui
  - targetPort: 9248 # with this, it never appears in the ui, hmm
    interval: 1s
  selector:
    matchLabels:
      app.kubernetes.io/component: ep
      component: taskmanager <-- I know these selectors are good
```

* Prometheus Operator Logs:

I have debug on and there are no errors or warnings at all, but it does not mention my service monitor by name either.

I can provide them in full if required.

**Anything else we need to know?**:

As per my comments in the ServiceMonitor, if I try to use a different port (let's say, by using the named port Prometheus, which i know I'm supposed to do), it doesn't appear. If I try to use port 9249, I get connection refused errors.

Here is the Service I am using, with lots of extra stuff omitted for brevity.

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flink
    app.kubernetes.io/component: ep
    component: taskmanager
  name: a-flink-taskmanager
  namespace: acme-iaf
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: rpc
    port: 6122
    protocol: TCP
    targetPort: rpc
  - name: data
    port: 6121
    protocol: TCP
    targetPort: data
  - name: query
    port: 50555
    protocol: TCP
    targetPort: query
  - name: prometheus
    port: 9249
    protocol: TCP
    targetPort: prometheus
  selector:
    app: flink
    app.kubernetes.io/component: ep
    component: taskmanager
    eventprocessing.automation.ibm.com/role: taskmanager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

If I exec into the container, and curl 127.0.0.1:9248, there are metrics here, indicating I've configured Flink to emit metrics correctly with Prometheus.

Any guidance would be very helpful, I have been through https://docs.openshift.com/container-platform/4.6/monitoring/troubleshooting-monitoring-issues.html and all of the monitoring steps from the beginning - the sample works perfectly fine, it's only when I try to create a ServiceMonitor of my own, that its target never appears, and that's really the root of my ask for help here (I'm not asking anyone to help with solving my problem, but more - helping me to understand what my problem is :smile).

![image](https://user-images.githubusercontent.com/12814972/130418678-59092df5-2c33-4086-a00f-868e5d38d0ae.png)

Here you can see that even when a target isn't correctly working (e.g. prometheus can't reach the endpoints), they're visible. But my ServiceMonitor never is, unless I change it. If I try the named "prometheus" port, instead of the (I get warned about this, deprecated use of targetPort), I see:

![image](https://user-images.githubusercontent.com/12814972/130420431-ff66d642-1ccf-4e8c-b216-0bc8a443f6ae.png)

I know some of the 
I'll exec in to a user defined workload pod and start curling this endpoint to debug that, it's interesting this does appear as a target though.

It would be helpful if there was a status in the CR indicating an error, or at least to have something in the logs pointing me in the right direction, but hopefully I can get some information here about why the target doesn't appear under certain conditions (which?) in the Prometheus UI. 

I am wondering if it's the part where the ServiceMonitor is added into the list of Prometheus ones, but I see no errors indicating that's the case. My ServiceMonitorSelector is simply: {} indicating any will be added AIAU.

Many thanks in advance

**Comment by fpetkovski** [comment]
Exposing troubleshooting information for ServiceMonitoring is definitely something which would be immensely beneficial. I believe there are already some issues for tracking such improvements.

Leaving that aside, from what I managed to understand, prometheus metrics are exposed on 9248 but prometheus is trying to scrape them from 9249. Can you check the name of the containerPort with name `prometheus` in the flink deployment? Is it set to 9248 or 9249?

**Comment by a-roberts** [comment]
> Exposing troubleshooting information for ServiceMonitoring is definitely something which would be immensely beneficial. I believe there are already some issues for tracking such improvements.
> 
> Leaving that aside, from what I managed to understand, prometheus metrics are exposed on 9248 but prometheus is trying to scrape them from 9249. Can you check the name of the containerPort with name `prometheus` in the flink deployment? Is it set to 9248 or 9249?

👍 that would be super helpful, so the metrics are definitely on 9248 in the container, but I believe something in my operator code was having it use 9249. So to make it super explicit, what I've done is add `prometheus-tm` as a named port instead, and had this use 9249,

This means my service now looks like this:

```
  ports:
  - name: rpc
    port: 6122
    protocol: TCP
    targetPort: rpc
  - name: data
    port: 6121
    protocol: TCP
    targetPort: data
  - name: query
    port: 50555
    protocol: TCP
    targetPort: query
  - name: prometheus-tm
    port: 9248
    protocol: TCP
    targetPort: prometheus-tm
```

and the servicemonitor like this:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: adam-tm-service-monitor
  namespace: acme-iaf
spec:
  endpoints:
  - port: prometheus-tm
    interval: 1s
  selector:
    matchLabels:
      app.kubernetes.io/component: ep
      component: taskmanager
```

If I then bounce the operator pod and port-forward a user workload pod again (my way of refreshing things)

![image](https://user-images.githubusercontent.com/12814972/130435524-9eaab58e-2e99-434e-9356-9266d0379b98.png)

everything works and I'm once again happy.

Note, to get this working, I actually had to remove our reconcileNetworkPolicy method. Basically in one of the operators I work on, we create a networkpolicy for managing what's allowed inbound/outbound and it wasn't quite right. I wonder if that caused my original problem (no target in the UI)...

**Comment by fpetkovski** [comment]
The no targets in the UI is caused by the following prometheus config chunk:
```
- action: keep
  source_labels:
  - __meta_kubernetes_pod_container_port_name
  regex: "9248"
```

Prometheus is looking for a container port with the name 9248. The target port in a service monitor refers to a container port name, not the port value.
