### ISSUE TITLE
Alertmanager SNS receiver not working

### ISSUE THREAD

**Issue by phin1x** [prometheus-operator/prometheus-operator#4236]
**What happened?**

We want to use the new SNS receiver from alertmanager 0.23.0, but the operator fails with an unmashal error. A quick look at the code showed that the sns receiver structs are missing.

A general question: why is the alert manager config rebuilt if the corresponding structures are exported in the alert manager module and there is already a dependency on the alert manager anyway?

**Did you expect to see something different?**

alertmanager config with sns receivers should work without errors.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy prometheus operator 0.50.0
2. Deploy alertmanager with sns receiver via the kube-prometheus-stack helm chart (config is stored in a secret)

**Environment**

* Prometheus Operator version:

    `0.50.0`
    
    

* Manifests:

```
...
receivers:
- name: 'null'
- name: 'cluster-admin'
   sns_configs:
   - send_resolved: True
     topic_arn: arn:aws:sns:eu-central-1:123456789:my-alert-topic
...
```

* Prometheus Operator Logs:

```
level=error ts=2021-08-30T11:17:30.620996291Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"monitoring/kube-prometheus-stack-alertmanager\" failed: provision alertmanager configuration: base config from Secret could not be parsed: yaml: unmarshal errors:\n  line 6: field sns_configs not found in type alertmanager.receiver\n  line 11: field sns_configs not found in type alertmanager.receiver"
```

**Anything else we need to know?**:

The operator and the alert manager is deployed via the kube prometheus stack helm chart
