### ISSUE TITLE
  Warning  Failed Error: failed to start container "prometheus": Error response from daemon: cannot join network of a non running container: 

### ISSUE THREAD

**Issue by lingfengChen03** [prometheus-operator/prometheus-operator#4254]
When I tried to use Promethus to monitor rook-ceph:
    1.  kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/v0.40.0/bundle.yaml
    2. kubectl apply -f service-monitor.yaml
    3. kubectl create -f prometheus.yaml
    4. kubectl create -f prometheus-service.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph
  labels:
    team: rook
spec:
  namespaceSelector:
    matchNames:
      - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: rook-ceph
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 5s
```

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: rook-ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.ceph.rook.io/aggregate-to-prometheus: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-rules
  labels:
    rbac.ceph.rook.io/aggregate-to-prometheus: "true"
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: rook-ceph
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: rook-prometheus
  namespace: rook-ceph
  labels:
    prometheus: rook-prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: rook
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: rook-prometheus
  resources:
    requests:
      memory: 400Mi
```

```
apiVersion: v1
kind: Service
metadata:
  name: rook-prometheus
  namespace: rook-ceph
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: rook-prometheus
```

But this is not normal：
```
$ kubectl get all -n rook-ceph | grep prometheus
pod/prometheus-rook-prometheus-0                              0/3     Terminating   0          8s
service/prometheus-operated        ClusterIP   None             <none>        9090/TCP            3d18h
service/rook-prometheus            NodePort    10.254.21.250    <none>        9090:30900/TCP      4d16h
statefulset.apps/prometheus-rook-prometheus   0/1     3d18h
```
When I went to check the pod：
```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  6s    default-scheduler  Successfully assigned rook-ceph/prometheus-rook-prometheus-0 to 10.90.230.19
  Normal   Pulling    5s    kubelet            Pulling image "quay.io/prometheus/prometheus"
  Normal   Pulled     2s    kubelet            Successfully pulled image "quay.io/prometheus/prometheus" in 3.177992286s
  Normal   Created    2s    kubelet            Created container prometheus
  Warning  Failed     1s    kubelet            Error: failed to start container "prometheus": Error response from daemon: cannot join network of a non running container: 7b82fbe08eb992b78d23f2d9ad6dc5671832d22b9aed5ff0bd16a6a868b6f62b
  Normal   Pulled     1s    kubelet            Container image "kubesphere/prometheus-config-reloader:v0.42.1" already present on machine
  Warning  Failed     1s    kubelet            Error: cannot find volume "config" to mount into container "prometheus-config-reloader"
  Normal   Pulled     1s    kubelet            Container image "jimmidyson/configmap-reload:v0.3.0" already present on machine
  Warning  Failed     1s    kubelet            Error: cannot find volume "prometheus-rook-prometheus-rulefiles-0" to mount into container "rules-configmap-reloader"
```

kubernetes version: v1.21.1
rook version: v1.5

prometheus log:
```
level=info ts=2021-09-04T10:46:44.200734971Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=rook-ceph/rook-prometheus
level=info ts=2021-09-04T10:46:44.309134577Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=rook-ceph/rook-prometheus
level=info ts=2021-09-04T10:46:44.400835149Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=rook-ceph/rook-prometheus
level=info ts=2021-09-04T10:46:44.591217035Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=rook-ceph/rook-prometheus
level=info ts=2021-09-04T10:46:44.882791032Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=rook-ceph/rook-prometheus
level=info ts=2021-09-04T10:46:44.930791764Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=rook-ceph/rook-prometheus
level=info ts=2021-09-04T10:46:45.082827373Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=rook-ceph/rook-prometheus
```
