### ISSUE TITLE
PodMonitor spec with explicit scrape interval result in two jobs

### ISSUE THREAD

**Issue by matrohon** [prometheus-operator/prometheus-operator#4264]
When I create a PodMonitor with an interval in the podMonitorEndpoints section, the operator creates two jobs, one with the endpoint="port-name" label which is scraped at the default period, and one without this label, which is scraped at the period I've asked.

If I remove the "interval" option, then only one job is created.

I've deployed the operator with the helm charts from kube-prometheus-stack.

* Prometheus Operator version:

chart=kube-prometheus-stack-18.0.2
kube-prometheus-stack:
    Image:      quay.io/prometheus-operator/prometheus-operator:v0.50.0
    Port:       10250/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/prometheus-stack-kube-prom-kubelet
      --localhost=127.0.0.1
      --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.50.0
      --config-reloader-cpu-request=100m
      --config-reloader-cpu-limit=100m
      --config-reloader-memory-request=50Mi
      --config-reloader-memory-limit=50Mi
      --thanos-default-base-image=quay.io/thanos/thanos:v0.17.2
      --web.enable-tls=true
      --web.cert-file=/cert/cert
      --web.key-file=/cert/key
      --web.listen-address=:10250
      --web.tls-min-version=VersionTLS1

* Kubernetes version information:

    `kubectl version`
    Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3+k3s1", GitCommit:"1d1f220fbee9cdeb5416b76b707dde8c231121f2", GitTreeState:"clean", BuildDate:"2021-07-22T20:52:14Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

* Manifests:

Here is the PodMonitor object I've created:

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: node-power-exporter
  namespace: kube-system
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      name: node-power-exporter
  podMetricsEndpoints:
    - port: metrics
    - interval: 2s
```

**Comment by matrohon** [comment]
thanks to @vsliouniaev how figured out where was my error. I was having a mistake in my spec, the correct one has only one entry in the podMetricsEndpoints slice: 

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: node-power-exporter
  namespace: kube-system
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      name: node-power-exporter
  podMetricsEndpoints:
    - port: metrics
      interval: 2s
```
