### ISSUE TITLE
Stop scraping metrics from a namespace in K8s

### ISSUE THREAD

**Issue by mouliveera** [prometheus-operator/prometheus-operator#4268]
**What did you do?**
tried using below values in proetheusSpec, but it didn't help
```
  prometheusSpec:
    serviceMonitorSelector:
    matchLabels:
      namespace: !test.*
```
**Did you expect to see some different?**

We use multiple namespace to test our features. We are using prometheus-operator to scrape metrics of our kubernetes environment irrespective of namespaces.

Observed service monitor `prometheus-kube-state-metrics` is taking care of that.

I am looking for a way, how can we stop scraping metrics from a test namespace.

**Environment**

* Prometheus Operator version:
prometheus-operator:v0.46.0
* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by fpetkovski** [comment]
Hi @mouliveera,

you could use matchExpression[1] instead of matchLabels and label the service monitors that you want to exclude.

[1] https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#LabelSelector

**Comment by mouliveera** [comment]
@fpetkovski I tried to ignore the namespace `test.*` from scraping. Ran helm upgrade 
```
   prometheusSpec:
     serviceMonitorSelector:
     matchExpression:
       namespace: "!test.*"
```

I still see some test namespace pod metrics in prometheus. Do I need any other values to skip the metrics scraping the test.* namespaces?

**Comment by fpetkovski** [comment]
This is not how the matchExpression works, it matches service monitor labels.
I suggest you try something like
```
  prometheusSpec:
     serviceMonitorSelector:
       matchExpression:
         key: <some-special-key>
         operator: NotIn
         values: 
         - <some-special-value>
```
and label the service monitors that you want to exclude with 
```
metadata:
...
  labels:
     <some-special-key>: <some-special-key>
```

**Comment by mouliveera** [comment]
@fpetkovski I agree, but the issue is not with `serviceMonitorSelector` options. 

I am looking for some help where we can skip/stop a namespace from Prometheus metrics scraping. Is there any available options we can set to stop metrics scraping?

**Comment by fpetkovski** [comment]
Ok now I understand. You could try using `--deny-namespaces` on the oeprator itself, but that is a global deny for all resources, not only for ServiceMonitors: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/operator.md

**Comment by fpetkovski** [comment]
And if you need an operator for kube-system as well, you can spin up a dedicated one with `--namespaces=kube-system`

**Comment by mouliveera** [comment]
Thanks for sharing the options[`deny-namespaces`]. Yes we dont want to scrape any metric from those test namespaces. I am trying it to test. 
```
helm template prometheus prometheus-community/kube-prometheus-stack --namespace monitoring -f values.yaml -f values/develop-values.yaml --kube-context develop  --deny-namespaces test.1,test.2
```

**Comment by simonpasquier** [comment]
you could use `serviceMonitorNamespaceSelector` to exclude a set of namespaces based on labels. For instance:

```
  serviceMonitorNamespaceSelector:                                                                                                                                                            
    matchExpressions:                                                                                                                                                                         
    - key: test-namespace
      operator: In                                                                                                                                                                         
      values:                                                                                                                                                                                 
      - "true"                                                                                                                                                                                
```

Otherwise the `--deny-namespaces` flag should work too.
