### ISSUE TITLE
Prometheus Operator - Service Monitor No Active Targets

### ISSUE THREAD

**Issue by rubenssoto** [prometheus-operator/prometheus-operator#4288]
Hello,

I deployed and java application on kubernetes and Im using jmx exporter to export metrics to prometheus. I created a service monitor but on prometheus service discovery shows no active target...could you help me?

Deployment:
```
 ports:
        - containerPort: 8443
        - name: metrics
          containerPort: 8090
        - containerPort: 8889
```

Service
```
kind: Service
apiVersion: v1
metadata:
  name:  presto-prometheus-metrics
  namespace: presto
spec:
  type: ClusterIP
  selector:
    app:  presto-coordinator-app
  ports:
    - name: metrics 
      port: 8090 
      targetPort: metrics
      protocol: TCP
```

Service Monitor

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: presto-coordinator-servicemonitor
  namespace: monitoring
  labels:
    app: presto-coordinator-servicemonitor
spec:
  selector:
    matchLabels:
      # Target app service
      app: presto-prometheus-metrics
  endpoints:
  - interval: 15s
    port: metrics
    path: /metrics
  namespaceSelector:
    matchNames:
    - presto
```

Could you help me?

Thank you
