### ISSUE TITLE
about  relabelingConfigs

### ISSUE THREAD

**Issue by yehaotong** [prometheus-operator/prometheus-operator#4297]
I want to use  relabelingConfigs in kind:Probe of monitoring.coreos.com/v1,
and my yaml is : 
```
                                 prober:
                                    url: "redis-exporter.monitoring.svc.cluster.local:9121"
                                    scheme: http
                                    path: /scrape
                                targets:
                                    staticConfig:
                                      static:
                                      - redis://xxx.staging:6379
                                    relabelingConfigs:
                                      - action: replace
                                        sourceLabels: 
                                        - instance
                                        targetLabel: instance
                                        regex: (.*)
                                        replacement: 'crs-xxxxxx'
```

But it did not work and have some error:unknown field "relabelingConfigs" in com.coreos.monitoring.v1.Probe.spec.targets,how can I use relabelingConfigs to replace metrics ?
