### ISSUE TITLE
Multiple tls_configs to forward alerts to different alertmanager instances

### ISSUE THREAD

**Issue by heyoheyo** [prometheus-operator/prometheus-operator#4302]
**What did you do?**

Hi, I am looking to have two alertmanagers for prometheus operator alerts - one living in k8s cluster and one outside k8s cluster. I successfully added two endpoints by adding `additionalAlertManagerConfigs` with `static_configs` and can see them in `$PROM_ENDPOINT/status` page. However, k8s Prometheus was set up differently (http and  a root `api/v2/alerts` endpoint), whereas non-k8s one is https and is located at `/alertmanager/api/v2/alerts`. As such, I added also an extra tls_config entry alongside `static_configs` in `additionalAlertManagerConfigs` secret to reflect this, but Prometheus is only using http and  a root `api/v2/alerts` for all alertmanagers. Is there a way to add tls information for both alertmanagers individually or is there any other way I can get this to work?

Thank you so much!

**Did you expect to see some different?**
I expected traffic to be forwarded to /alertmanager endpoint on non-k8s instance.

* Prometheus Operator version:
* 
```Version	2.30.2
Revision	b30db03f35651888e34ac101a06e25d27d15b476
Branch	HEAD
BuildUser	root@80d1e84a93dd
BuildDate	20211001-12:26:58
GoVersion	go1.17.1
```

**Comment by simonpasquier** [comment]
Can you share the Prometheus resource definition as well as the generated configuration?

**Comment by heyoheyo** [comment]
Hi sure!

Prometheus Resource definition:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    prometheus: prometheus
spec:
  externalUrl: https://<sensitive-k8s-hostname>
  replicas: 1
  enableAdminAPI: true
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager
      port: <port>
    additionalAlertManagerConfigs:
      name: additional
      key: additional.yaml
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      label: <label-sensitive>
  ruleSelector:
    matchLabels:
      <sensitive>
  imagePullSecrets:
    - name: xxxxx
  resources:
    limits:
      cpu: 150m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 150Mi
```


additional.yml:
```
  - tls_config:
      insecure_skip_verify: true
    follow_redirects: true
    scheme: https
    path_prefix: /non-kubernetes
    timeout: 10s
    api_version: v2
  - static_configs:
       - targets:
          - "<sensitive-non-k8s-hostname>"
```

Generated prometheus config:
```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    <sensitive>
alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    path_prefix: /
    timeout: 10s
    api_version: v2
    kubernetes_sd_configs:
    - role: endpoints
      kubeconfig_file: ""
      follow_redirects: true
      namespaces:
        names:
        - monitoring
  - follow_redirects: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
      - <sensitive-non-k8s-hostname>
  - tls_config:
      insecure_skip_verify: true
    follow_redirects: true
    scheme: https
    path_prefix: /non-kubernetes
    timeout: 10s
    api_version: v2
<rest of settings for scrapes and rules>


**What I see in UI (/status):**

```Endpoint
http://<kubernetes-endpoint>/api/v2/alerts
http://<sensitive-non-k8s-hostname>/api/v2/alerts - Missing /non-kubernetes and https
```

**Comment by simonpasquier** [comment]
I suspect that your additional Alertmanager config isn't correctly formatted

```
  - tls_config:
      insecure_skip_verify: true
    follow_redirects: true
    scheme: https
    path_prefix: /non-kubernetes
    timeout: 10s
    api_version: v2
# you had
# - static_configs:
    static_configs:
       - targets:
          - "<sensitive-non-k8s-hostname>"
```
