### ISSUE TITLE
ServiceMonitor not working

### ISSUE THREAD

**Issue by stoupance** [prometheus-operator/prometheus-operator#4317]
Hi,

I'm using `kube-prometheus` ontop of `Prometheus-operator` and I would like to monitor Redis, which is deployed by an operator too. Multiple Redis instances can/will be deployed into this cluster and into multiple namespaces. So I would like Prometheus to monitor all of them, without doing much configuration or having to tweak Prometheus configuration each time a new Redis instances is deployed. So my idea was to use a `ServiceMonitor` without specifying any namespace selector. 

For my test purposes, I have 2 Redis Cluster deployed, each into different namespaces: one in `default` and one into `preprod`. I created a `ServiceMonitor` and I'm facing multiple issues without succeeding my goals.

When I'm using this `ServiceMonitor` configuration below, Redis exporter doesn't appears into `/targets` Prometheus page. And no data is scraped. No logs from Prometheus container.

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-monitoring-cluster
  namespace: monitoring
  labels:
    redis-operator: "true"
    env: preprod
spec:
  endpoints:
  - port: redis-exporter
    interval: 30s
    scrapeTimeout: 10s
  selector:
    matchLabels:
      redis_setup_type: cluster
```

When I'm adding a `namespaceSelector`
```
  namespaceSelector:
    matchNames:
    - default
    - preprod
```
Redis exporter appears in `/targets` of Prometheus and data from Redis of `default` namespace is scraped correctly. But there is an issue to scrape data from `preprod` namespace.
```
level=error ts=2021-10-07T13:31:22.891Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/reflector.go:167: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list resource \"pods\" in API group \"\" in the namespace \"preprod\""
```

My Redis `service` has the matching label:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
    redis.opstreelabs.in: "true"
  labels:
    app: redis-cluster-leader
    redis_setup_type: cluster
    role: leader
  name: redis-cluster-leader
  namespace: default
[...]
```

I figured this is something related to Role, RoleBindings but can't work around or fix the issue. Also, I came to the conclusion without adding a `namespaceSelector`, Prometheus doesn't detect/add the Service Monitor and I can't figure why. 
So, what is the way to add a ServiceMonitor that will scrape Redis data from all namespaces? Is that using a ClusterRoleBindings (I thought this is already configured by `kube-prometheus`?

So, overall:
- It works for `default` namespace when I add the `namespaceSelector` 
- It doesn't work for any additional namespaces added in the `namespaceSelector`
- It doesn't work if I don't add any `namespaceSelector`

Any help will be greatly appreciated, thanks :)

**Comment by simonpasquier** [comment]
Have you checked https://prometheus-operator.dev/docs/operator/rbac/#prometheus-rbac? 
If the Prometheus instance should all namespaces then you need to create a `ClusterRoleBinding`. Otherwise if the Prometheus instance is limited to one or several namespaces, you can create a `RoleBinding` for each namespace.

**Comment by stoupance** [comment]
> Have you checked https://prometheus-operator.dev/docs/operator/rbac/#prometheus-rbac? If the Prometheus instance should all namespaces then you need to create a `ClusterRoleBinding`. Otherwise if the Prometheus instance is limited to one or several namespaces, you can create a `RoleBinding` for each namespace.

Yes I finally figured it you by creating a `ClusterRoleBinding` with the proper permissions. I one I had previously wasn't correct. Hence the error I had.

I still have an issue when I don't declare a `namespaceSelector` into my `serviceMonitor`, Prometheus reload correctly but this `serviceMonitor` does not appears on `/targets` page of Prometheus, and I don't really why. Nor how to fix it. Any clue where to look at?

**Comment by simonpasquier** [comment]
From https://prometheus-operator.dev/docs/operator/design/#servicemonitor, this should do the trick:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-monitoring-cluster
  namespace: monitoring
  labels:
    redis-operator: "true"
    env: preprod
spec:
  endpoints:
  - port: redis-exporter
    interval: 30s
    scrapeTimeout: 10s
  selector:
    matchLabels:
      redis_setup_type: cluster
  namespaceSelector:
    any: true
```
