### ISSUE TITLE
How to configure multiple receivers and routes using Alertmanagerconfig custom resource?

### ISSUE THREAD

**Issue by rjonala** [prometheus-operator/prometheus-operator#4318]
I want to setup alerts using Alertmanagerconfig custom resource. Does someone have example of alertmanagerconfig custom resource to configure multiple receivers and routes so that the alerts are routed to various teams accordingly? I have searched online to find examples but couldn't. It would be really great if someone can point me to examples.

**Comment by fpetkovski** [comment]
Hi @rjonala, have you looked at the example that we have here: https://github.com/prometheus-operator/prometheus-operator/blob/master/example/user-guides/alerting/alertmanager-config-example.yaml ?

**Comment by rjonala** [comment]
Hi @fpetkovski thanks for the response. Yes, I have looked at that example which only has a single receiver and a single route. 

I am looking for a config file with multiple receivers and route them to multiple routes based on labels. For ex, I am able to configure multiple receivers but I am not able to list down multiple receivers in **kind: AlertmanagerConfig** file. Here is what I have,

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    alertmanagerConfig: alerting
  name: alertmanagerconfig
  namespace: prometheus
spec:
  receivers:
  - name: team-devops
    opsgenieConfigs:
    - apiKey:
        key: apiKey
        name: devops-prometheus
      apiURL: https://api.opsgenie.com/
      sendResolved: true
      httpConfig: {}
  - name: team-dev
    opsgenieConfigs:
    - apiKey:
        key: apiKey
        name: dev
      apiURL: https://api.opsgenie.com/
      sendResolved: true
      httpConfig: {}
  route:
    receiver: team-devops
    matchers:
      - name: team
        value: devops


```
I am stuck at configuring multiple routes. For ex, if I want to route an alert with label **team: dev** to the receiver **team-dev**, how do I do that?
