### ISSUE TITLE
Prometheus discovers too many targets when using selectors with empty label values

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#4325]
**What happened?**

Deployed the example application from the Getting Started guide (https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md) but instead of matching services on `app: example-app`, I've modified the service monitor to match the service on an empty label value.

```yaml
kind: Service
apiVersion: v1
metadata:
  name: example-app
  labels:
    # MODIFIED
    example-app: ""
spec:
  selector:
    app: example-app
  ports:
  - name: web
    port: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      # MODIFIED
      example-app: ""
  endpoints:
  - port: web
```

Instead of only scraping the endpoints with the `example-app: ""` label, Prometheus scraped all endpoints from the namespace (e.g. including itself).

**Did you expect to see something different?**

I expected Prometheus to scrape only endpoints for which the `example-app` label was present.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Environment**

* Prometheus Operator version: master
* Kubernetes version information: N/A
* Kubernetes cluster kind: N/A
* Manifests: N/A
* Prometheus Operator Logs: N/A

**Anything else we need to know?**:

This is the configuration generated by the operator:

```yaml
- job_name: serviceMonitor/default/example-app/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - default
  relabel_configs:
  - source_labels:
    - job
    target_label: __tmp_prometheus_job_name
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_example_app
    regex: ""
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: web
```

The configuration doesn't distinguish between an empty label value and a missing label. The operator should leverage the `__meta_kubernetes_service_label_example_app_present` meta label to avoid this (requires Prometheus >= 2.9.0):

```yaml
- job_name: serviceMonitor/default/example-app/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - default
  relabel_configs:
  - source_labels:
    - job
    target_label: __tmp_prometheus_job_name
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_example_app
    - __meta_kubernetes_service_label_example_app_present
    regex: ";true"
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: web
```
