### ISSUE TITLE
Receiver not found

### ISSUE THREAD

**Issue by rmgpinto** [prometheus-operator/prometheus-operator#4330]
**What happened?**

I've used the helm chart (https://prometheus-community.github.io/helm-charts) to create the deployment.
I've edited the `values.yaml` file and added a "global" receiver called SRE.
The idea is to re-use the SRE receiver on multiple `AlertmanagerConfig` and avoid repeating the same email addresses on every namespace.

Now, on the `default` namespace I applied:

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sre
  namespace: default
spec:
  receivers:
    - name: sink
  route:
    groupBy: ["teams", "severity", "namespace"]
    receiver: sink
    routes:
      - receiver: SRE
        matchers:
          - name: teams
            value: "(.*)SRE(.*)"
            regex: true
---
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sre
  namespace: default
spec:
  groups:
    - name: Apps
      rules:
      - alert: Warning
        expr: vector(1)
        labels:
          teams: SRE appX
          severity: warning
          namespace: default
```

However, on the logs I see:

```
caller=operator.go:993 component=alertmanageroperator msg="skipping alertmanagerconfig" error="route[0]: receiver \"SRE\" not found" alertmanagerconfig=default/sre namespace=monitoring alertmanager=pks-alertmanager
```

**Did you expect to see something different?**
Is there a way to re-use receivers added on the global alertmanager config file?

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `v0.50.0`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

kops

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
