### ISSUE TITLE
long pvc:  prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0

### ISSUE THREAD

**Issue by jingslunt** [prometheus-operator/prometheus-operator#4343]
- Install
```
 helm install prometheus-operator  \
 --set rbacEnable=true \
 --set prometheusOperator.createCustomResource=false \
 -n=monitoring \
 stable/prometheus-operator
```
- set pvc
```
#kubectl edit prometheus  prometheus-operator-prometheus -n monitoring
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 50Gi
```
-  ERROR:
```
  Warning  FailedScheduling    3m58s  default-scheduler        0/6 nodes are available: 6 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling    3m58s  default-scheduler        0/6 nodes are available: 6 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled           3m51s  default-scheduler        Successfully assigned monitoring/prometheus-prometheus-operator-prometheus-0 to oc-master-01
  Warning  FailedAttachVolume  111s   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-39441d30-28b1-45e9-8f67-739210cfdbee" : attachdetachment timeout for volume pvc-39441d30-28b1-45e9-8f67-739210cfdbee
  Warning  FailedMount         108s   kubelet                  Unable to attach or mount volumes: unmounted volumes=[prometheus-prometheus-operator-prometheus-db], unattached volumes=[prometheus-prometheus-operator-prometheus-rulefiles-0 prometheus-operator-prometheus-token-ccpjp config config-out tls-assets prometheus-prometheus-operator-prometheus-db]: timed out waiting for the condition
