### ISSUE TITLE
Operator fails to spawn alertmanager due to parsing error when using authorization credentials from secret

### ISSUE THREAD

**Issue by kanor1306** [prometheus-operator/prometheus-operator#4345]
**What happened?**
Using the new `authorization` configuration ( See https://github.com/prometheus-operator/prometheus-operator/pull/4110 )  in the `http_config` section of a webhook receiver triggers a parsing error of the alertmanager configuration, preventing the alert manager from starting up. This happens when trying to use a secret to pass the credentials, like:
```
http_config:
  authorization:
    credentials:
      name: opsgenie
      key: apiKey
```

**Did you expect to see something different?**
The operator should be able to parse the configuration and startup alertmanager properly.

**How to reproduce it (as minimally and precisely as possible)**:
- In a cluster with a prometheus operator (and alert manager) running:
  - Change the alertmanager receiver configuration to the one in he manifests section
  - Delete the stateful set of the alert manager and let the operator recreate it. The alertmanager should not come up, and the operator should show the parsing error.
- In an empty cluster:
  - Configure the alertmanager as indicated in the manifest below. 
  - Start the prometheus operator. The alert manager should not come up and show the parsing error in the logs.

**Environment**

* Prometheus Operator version:

    `v0.51.2`
    
    

* Kubernetes version information:

    `Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

    AWS EKS

* Manifests:
The alertmanager.yml inside the secret to which the log error refers to:

```
global:
  var1: "redacted"
  resolve_timeout: 5m
receivers:
- name: heartbeat
  webhook_configs:
  - http_config:
      authorization:
        credentials:
          key: apiKey
          name: opsgenie
    send_resolved: true
    url: https://api.opsgenie.com/v2/heartbeats/myheartbeat/ping
- name: "null"
route:
  group_by:
  - alertname
  group_interval: 5m
  group_wait: 30s
  receiver: "null"
  repeat_interval: 4h
  routes:
  - match:
      alertname: Watchdog
    receiver: heartbeat
    repeat_interval: 60s
```

* Prometheus Operator Logs:

```
level=error ts=2021-10-25T10:27:32.253245641Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"monitoring/monitoring-kube-prometheus-alertmanager\" failed: provision alertmanager configuration: base config from Secret could not be parsed: yaml: unmarshal errors:
  line 10: cannot unmarshal !!map into config.plain"
```

**Anything else we need to know?**:
I am using the `kube-prometheus-stack` chart, version `19.2.2`, with the prometheus operator image tag overridden to use  `v0.51.2`, but as the error shows up in the prometheus operator, I assume is an issue with the operator itself (though I may be wrong...)
