### ISSUE TITLE
Why AlertManagerConfig CRD does not overwrite default Config

### ISSUE THREAD

**Issue by winshenting** [prometheus-operator/prometheus-operator#4354]
**What did you do?**
I installed prometheus by prometheus operator helm chart. In values yaml, I conifg as below. I leave route blank
```
  config:
    global:
      resolve_timeout: 5m
      smtp_from: XXX
      smtp_require_tls: XXX
      smtp_smarthost: XXX
```
Then I created one AlertManagerConfig CRD and applied it to the Prometheus.
However, It looks like as below. I want to know how I can remove receiver: "null". And Make sure that prometheus-engops-team-noc-notification is the top one as default receive and route

```
route:
  receiver: "null"
  group_by:
  - job
  routes:
  - receiver: prometheus-engops-team-noc-notification
    group_by:
    - alertname
    - team
    match:
      namespace: prometheus
    continue: true
    routes:
    - receiver: prometheus-engops-team-cloudplatform-notification
      match_re:
        team: (?i)(cloudplatform)
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 12h
  - receiver: "null"
    match:
      alertname: Watchdog
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
inhibit_rules:
- source_match:
    namespace: prometheus
    severity: (?!)(critical)
  target_match:
    namespace: prometheus
    severity: (?!)(warning)
  equal:
  - alertname
  - cluster
  - service
receivers:
- name: "null"
- name: prometheus-engops-team-noc-notification
  email_configs:
  - send_resolved: true
    to: xmnoc@XXXX.com
    from: prometheus_engops_qa@XXXX.com
    hello: localhost
    smarthost: MAIL01.XXXX.com:25
    headers:
      From: prometheus_engops_qa@XXXX.com
      Subject: '{{ template "email.default.subject" . }}'
      To: xmnoc@XXXX.com
    html: '{{ template "email.default.html" . }}'
    require_tls: true
  pagerduty_configs:
  - send_resolved: true
    http_config: {}
    service_key: <secret>
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{ template "pagerduty.default.description" .}}'
    details:
      firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
- name: prometheus-engops-team-cloudplatform-notification
  email_configs:
  - send_resolved: true
    to: dl-cloudoperations@XXXX.com
    from: prometheus_engops_qa@XXXX.com
    hello: localhost
    smarthost: MAIL01.XXXX.com:25
    headers:
      From: prometheus_engops_qa@XXXX.com
      Subject: '{{ template "email.default.subject" . }}'
      To: dl-cloudoperations@XXXX.com
    html: '{{ template "email.default.html" . }}'
    require_tls: true
  pagerduty_configs:
  - send_resolved: true
    http_config: {}
    service_key: <secret>
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{ template "pagerduty.default.description" .}}'
    details:
      firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
```
