### ISSUE TITLE
matchExpressions in relabel_configs have a bug (regex)

### ISSUE THREAD

**Issue by sgolod** [prometheus-operator/prometheus-operator#4391]
We must take a values for labels (in regex) in "()" to be compatible with RE2 rules. For example:

we have next selector in Pod/ServiceMonitor
```
selector:                       
matchExpressions:       
- key: app              
  operator: In          
  values:               
  - helm-controller     
  - source-controller   
  - kustomize-controller
```

old prom-operator (0.50.0):
```
  - source_labels: [__meta_kubernetes_pod_label_app]
    separator: ;
    regex: helm-controller|source-controller|kustomize-controller
    replacement: $1
    action: keep
```
new operator (0.52.0)
```
  - source_labels: [__meta_kubernetes_pod_label_app, __meta_kubernetes_pod_labelpresent_app]
    separator: ;
    regex: helm-controller|source-controller|kustomize-controller;true
    replacement: $1
    action: keep
```

This regex:
    **regex: helm-controller|source-controller|kustomize-controller;true**

is invalid. It must be:
    **regex: (helm-controller|source-controller|kustomize-controller);true**
