### ISSUE TITLE
Can't evaluate field name in type interface

### ISSUE THREAD

**Issue by wh1sssss** [prometheus-operator/prometheus-operator#4393]
Hello guys,

I try to resolve dependencies from kubecost and i need add some recording rules on my prometheus.

Chart name: stable/prometheus
Version: prometheus-operator-9.3.2

I use the follow configuration on "Values.yaml":

```
additionalPrometheusRules:
  groups:
    - name: CPU
      rules:
      - expr: sum(rate(container_cpu_usage_seconds_total{container_name!=""}[5m]))
        record: cluster:cpu_usage:rate5m
      - expr: rate(container_cpu_usage_seconds_total{container_name!=""}[5m])
        record: cluster:cpu_usage_nosum:rate5m
      - expr: avg(irate(container_cpu_usage_seconds_total{container_name!="POD", container_name!=""}[5m])) by (container_name,pod_name,namespace)
        record: kubecost_container_cpu_usage_irate
      - expr: sum(container_memory_working_set_bytes{container_name!="POD",container_name!=""}) by (container_name,pod_name,namespace)
        record: kubecost_container_memory_working_set_bytes
      - expr: sum(container_memory_working_set_bytes{container_name!="POD",container_name!=""})
        record: kubecost_cluster_memory_working_set_bytes
```

Error:

`Error: INSTALLATION FAILED: template: kube-prometheus-stack/templates/prometheus/additionalPrometheusRules.yaml:30:61: executing "kube-prometheus-stack/templates/prometheus/additionalPrometheusRules.yaml" at <.name>: can't evaluate field name in type interface {}`

Thanks all!!!!
