### ISSUE TITLE
AlertmanagerConfig with duplicate group_by labels generates an invalid configuration

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#4402]
The following AlertmanagerConfig definition would trigger an invalid configuration:

```yaml
kind: AlertmanagerConfig
metadata:
  name: config-example
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: ['job', 'job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'null'
  receivers:
  - name: 'null'
```

Alertmanager logs:

```
level=error ts=2021-11-15T15:42:06.617Z caller=coordinator.go:118 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="duplicated label \"job\" in group_by"
```

cc @PhilipGough

**Comment by simonpasquier** [comment]
There is also probably an issue with the following definition

```yaml
kind: AlertmanagerConfig
metadata:
  name: config-example
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: ['job', '...']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'null'
  receivers:
  - name: 'null'
```
