### ISSUE TITLE
Version 0.52.0 dropped the app label from the statefulset but is still in the service selector causing no endpoint in the service 

### ISSUE THREAD

**Issue by primeroz** [prometheus-operator/prometheus-operator#4408]
**What happened?**
I upgraded to 0.52.1 , in 0.52.0 the `app` label was dropped from the statefulset for prometheus and alertmanager but is still in the service selector causing no endpoint in the service 

I did delete the service forcing the operator to recreate it but it came back with the app label in the selector

```
  selector:
    app: prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
```

**Did you expect to see something different?**
I expected the app label to be removed from the selector 
**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:
0.52.1
* Kubernetes version information:
GitVersion:"v1.19.13-eks-8df270"
* Kubernetes cluster kind:
EKS
* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
