### ISSUE TITLE
Prometheus statefulset not ready

### ISSUE THREAD

**Issue by mosheavni** [prometheus-operator/prometheus-operator#4409]
**What happened?**
The statefulset created by Prometheus resource is never ready even though the pod is running and available (marked as 0/1),
This causes the service of prometheus to not have any available endpoints, rendering the prometheus pods unreachable.

```
→ k get sts
NAME                                              READY   AGE
alertmanager-kube-prometheus-stack-alertmanager   1/1     130m
prometheus-kube-prometheus-stack-prometheus       0/1     117m
→ k get ep
NAME                                             ENDPOINTS                                               AGE
alertmanager-operated                            10.21.31.163:9094,10.21.31.163:9094,10.21.31.163:9093   131m
kube-prometheus-stack-alertmanager               10.21.31.163:9093                                       131m
kube-prometheus-stack-grafana                    10.21.16.165:3000                                       131m
kube-prometheus-stack-kube-state-metrics         10.21.23.173:8080                                       131m
kube-prometheus-stack-operator                   10.21.21.101:10250                                      131m
kube-prometheus-stack-prometheus                                                                         131m
kube-prometheus-stack-prometheus-node-exporter   10.21.30.35:9100                                        131m
prometheus-operated                                                                                      118m
```

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:
Simple installation of the kube-prometheus-stack, no changes at all.

**Environment**

* Prometheus Operator version:
```
→ kdd -n monitoring kube-prometheus-stack-operator G -i image:
    Image:      quay.io/prometheus-operator/prometheus-operator:v0.52.0
```

* Kubernetes version information:
```
→ k version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

EKS cluster

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 20.0.1
    chart: kube-prometheus-stack-20.0.1
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-stack-prometheus
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: kube-prometheus-stack-alertmanager
      namespace: monitoring
      pathPrefix: /
      port: web
  enableAdminAPI: false
  externalUrl: http://prometheus.eu.company.com/
  image: quay.io/prometheus/prometheus:v2.28.1
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: kube-prometheus-stack
  portName: web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: kube-prometheus-stack
  replicas: 1
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      app: kube-prometheus-stack
      release: kube-prometheus-stack
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: kube-prometheus-stack-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: kube-prometheus-stack
  shards: 1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: gp2-persistent
  version: v2.28.1
```

* Prometheus Operator Logs:

```
→ kl kube-prometheus-stack-operator-5bdb448845-8ldhk | awk '{$2="";print}' | awk '!x[$0]++'

level=info  caller=main.go:261 msg="Starting Prometheus Operator" version="(version=0.52.0, branch=refs/tags/v0.52.0, revision=62bfc820e410e06443b01f7f48812790cb67c9ce)"
level=info  caller=main.go:262 build_context="(go=go1.17.2, user=Action-Run-ID-1421200009, date=20211104-12:21:39)"
level=info  caller=server.go:54 msg="enabling server side TLS"
level=info  caller=main.go:124 msg="Starting secure server on [::]:10250"
level=info  caller=operator.go:448 component=alertmanageroperator msg="connection established" cluster-version=v1.21.2-eks-06eac09
level=info  caller=operator.go:457 component=alertmanageroperator msg="CRD API endpoints ready"
level=info  caller=operator.go:309 component=thanosoperator msg="connection established" cluster-version=v1.21.2-eks-06eac09
level=info  caller=operator.go:318 component=thanosoperator msg="CRD API endpoints ready"
level=info  caller=operator.go:421 component=prometheusoperator msg="connection established" cluster-version=v1.21.2-eks-06eac09
level=info  caller=operator.go:430 component=prometheusoperator msg="CRD API endpoints ready"
level=error  caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1.Prometheus: failed to list *v1.Prometheus: the server could not find the requested resource (get prometheuses.monitoring.coreos.com)"
level=info  caller=operator.go:261 component=thanosoperator msg="successfully synced all caches"
level=info  caller=operator.go:280 component=alertmanageroperator msg="successfully synced all caches"
level=info  caller=operator.go:741 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=warn  caller=amcfg.go:1061 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver="null" msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="unsupported value type" match_re="unsupported value type"
level=warn  caller=operator.go:346 component=prometheusoperator informer=Prometheus msg="cache sync not yet completed"
level=info  caller=operator.go:351 component=prometheusoperator msg="successfully synced all caches"
level=info  caller=operator.go:1221 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"```

**Anything else we need to know?**:
