### ISSUE TITLE
Thanos Ruler remote write config

### ISSUE THREAD

**Issue by m-messiah** [prometheus-operator/prometheus-operator#4451]
**What is missing?**
Thanos introducing stateless Ruler https://thanos.io/tip/components/rule.md/#stateless-ruler-via-remote-write with possibility to send data from ruler somewhere else.  It would be nice to see it in https://prometheus-operator.dev/docs/operator/api/#thanosrulerspec

**Why do we need it?**
The only way to use stateless ruler now is to override containers, which is kinda tricky.

**Environment**

* Prometheus Operator version: https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.52.1
* Thanos version https://github.com/thanos-io/thanos/releases/tag/v0.24.0-rc.1 (prerelease)

**Comment by simonpasquier** [comment]
It looks sensible to me. Adding a `remoteWriteConfig *v1.SecretKeySelector` field would be consistent with the rest of the CRD.

**Comment by tatchiuleung** [comment]
Just came across here and find out the prometheus-operator doesn't support Thanos Ruler remote write. It would be great if we can do this without hacking the container args!

**Comment by zakariais** [comment]
We also need this, is this solved or still not implemented?

**Comment by m-messiah** [comment]
It is still not implemented as part of the ThanosRuler spec, but it could be solved with additionalArgs now:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ThanosRuler
metadata:
  name: thanos-ruler
spec:
  image: thanos/thanos:v0.30.0
  additionalArgs:
  - name: remote-write.config
    value: |-
      "remote_write":
      - "name": "receiver-0"
        "remote_timeout": "30s"
        "url": "http://thanos-receiver-0.thanos-receiver:8081/api/v1/receive"
   ...
```
