### ISSUE TITLE
JobLabel comment may cause misunderstanding

### ISSUE THREAD

**Issue by qixiaobo** [prometheus-operator/prometheus-operator#4470]
https://github.com/prometheus-operator/prometheus-operator/blob/9c0db5656f04e005de6a0413fd8eb8f11ec99757/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml#L492
>jobLabel:
>                description: "Chooses the label of the Kubernetes `Endpoints`. ItsMaksim Nabokikh, 7 months ago: • Bump golangci->lint and switch to the revive (…
>                 value will be used for the `job`-label's value of the created metrics.
>                  \n Default & fallback value: the name of the respective Kubernetes
>                 `Endpoint`."
>                type: string

It may leads us to add label to endpoints like below

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  name: xxx
  namespace: xxx
  labels:
    app: jenkins-master
    xxxlabel: xxx
subsets:
  - addresses:
      - ip: xxx
```
We should just point out this is service
