### ISSUE TITLE
scrape limited metrics using prometheus

### ISSUE THREAD

**Issue by saiharshitachava** [prometheus-operator/prometheus-operator#4480]
I want to scrape only very few metrics using prometehus like used pod memory and used pod cpu and limits and requests of a namespace

How do I change my configs to scrape only specific metrics

**Comment by slashpai** [comment]
You can use `metricRelabelings` to ingest only metrics you are interested in. Example below is to collect only metrics which starts with http. You should be able to do that similarly for metrics you are interested in by forming the regex correctly

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web
    metricRelabelings:
    - action: keep
      sourceLabels: [__name__]
      regex: (http_).*
```

Documentation: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
