### ISSUE TITLE
Invalid scrapeTimeout value specified causes failure during prometheus configuration reload and preventing changes from being applied

### ISSUE THREAD

**Issue by slashpai** [prometheus-operator/prometheus-operator#4485]
**What happened?**

Create a servicemonitor like below

``` yaml
{
    "apiVersion": "monitoring.coreos.com/v1",
    "kind": "ServiceMonitor",
    "metadata": {
        "name": "example-app",
        "namespace": "test"
    },
    "spec": {
        "endpoints": [
            {
                "interval": "60s",
                "port": "http",
                "scrapeTimeout": "120s"
            }
        ],
        "jobLabel": "app.kubernetes.io/name",
        "selector": {
            "matchLabels": {
                "app": "example-app"
            }
        }
    }
}
```

**Did you expect to see something different?**

Operator should validate scrapeTimeout value specified

**How to reproduce it (as minimally and precisely as possible)**:

Try creating servicemonitor like above example

**Environment**

* Prometheus Operator version:

`0.50` and above

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

log shows error message like below

```
level=error ts=2022-01-10T12:51:02.928Z caller=main.go:763 msg="Error reloading config" err="couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: scrape timeout greater than scrape interval for scrape config with job name \"serviceMonitor/test/example-app/0\"" reported and all future changes won't be applied because of this problem
```

**Anything else we need to know?**:
