### ISSUE TITLE
I just tried to do the similar thing here as mentioned above, I have service monitor pointed to a service.

### ISSUE THREAD

**Issue by manikandanramdevops** [prometheus-operator/prometheus-operator#4492]
I just tried to do the similar thing here as mentioned in this ticket #3246.

What I'm trying to make is, I just want to add a additional label like {env="dev"} to all the metrices coming from this service monitor, I dont know what I missed, 

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rpc-app
  labels:
    app.kubernetes.io/name: kubelet
    app.kubernetes.io/part-of: kube-prometheus
    app: dev
spec:
  selector:
    matchLabels:
      app: rpc-app
  endpoints:
 - port: web
    metricRelabelings:
    - sourceLabels: [__..?]
      targetLabel: dev
      action: replace

```

The metrices from the prometheus, I just wanted to add a label like env=dev for this metric coming from the service monitor.

![image](https://user-images.githubusercontent.com/85827977/148999752-22b2b942-1093-40f5-9299-719d4080e7c4.png)

_Originally posted by @manikandanramdevops in https://github.com/prometheus-operator/prometheus-operator/issues/3246#issuecomment-1010243389_

**Comment by simonpasquier** [comment]
Here is the snippet to hardcode a static label:

```
  endpoints:
 - port: web
   metricRelabelings:
   - replacement: dev
     targetLabel: env
     action: replace

```

**Comment by manikandanramdevops** [comment]
@simonpasquier No luck, Im unable to get the metrices in the prometheus eventhough I applied the snippet.

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rpc-app
  labels:
    app.kubernetes.io/name: kubelet
    app.kubernetes.io/part-of: kube-prometheus
    app: dev
spec:
  selector:
    matchLabels:
      app: rpc-app
  endpoints:
  - port: web
    metricRelabelings:
    - replacement: dev
      targetLabel: dev
      action: replace
```

![image](https://user-images.githubusercontent.com/85827977/149153779-c67703af-cf9b-455e-bd56-ddf85260e5d1.png)
