### ISSUE TITLE
Auto add labels to discovered rules

### ISSUE THREAD

**Issue by nvtkaszpir** [prometheus-operator/prometheus-operator#4495]
**What is missing?**
We use kube-prometheus-stack helm chart which has additionalRuleLabels which allows to add extra lables to the rules defined in the chart.

Yet looks like there is no way to auto add labels to other discovered rules.

**Why do we need it?**
We want to avoid duplication of the labels or avoid copying them across installations, so it would be nice so that enforce adding specific labels to prometheus rules discovered by operator.
This way we can deploy prometheus operator and tell it to add to all prometheus rules our custom labels. This would also avoid accidental (or not) label value changes by teams.

Example use case:
- add `cluster_provider: aws` to all prometheus rules.
- this way if someone creates  PrometheusRule with below fragment:
```yaml
    - alert: Example
      annotations:
        summary: Endpoint with zero addresses
        description:  Endpoint {{ $labels.endpoint }} with zero addresses
      expr: |
        sum(kube_endpoint_address_available{namespace="my-namsepace"}) by (endpoint) == 0
      for: 3m
      labels:
        severity: critical
```
then prometheus-operator would actually render it as below (see last lines)
```yaml
    - alert: Example
      annotations:
        summary: Endpoint with zero addresses
        description:  Endpoint {{ $labels.endpoint }} with zero addresses
      expr: |
        sum(kube_endpoint_address_available{namespace="my-namespace"}) by (endpoint) == 0
      for: 3m
      labels:
        severity: critical
        cluster_provider: aws
```

**Environment**
k8s 1.18...1.22

* Prometheus Operator version:
v0.53.1

**Anything else we need to know?**:

**Comment by fpetkovski** [comment]
I guess this can be both a global setting as a binary arg, and a field in the `PrometheusSpec`.

**Comment by nvtkaszpir** [comment]
I've managed to get what I need by setting proper prometheusSpec.externalLabels

**Comment by simonpasquier** [comment]
`prometheusSpec.externalLabels` is the right way to go IMHO since it applies also to remote write, federation, ...

**Comment by gberche-orange** [comment]
@simonpasquier 

My team has a similar use-case that would benefit from adding both labels and annotations to the rules loaded from the [PrometheusRule](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.PrometheusRule) resource

We'd like to reuse off-the-shelf alert definitions such as [host-and-hardware/node-exporter.yml](https://github.com/samber/awesome-prometheus-alerts/blob/master/dist/rules/host-and-hardware/node-exporter.yml#L214) from [https://github.com/samber/awesome-prometheus-alerts](samber/awesome-prometheus-alerts), see https://github.com/prometheus-operator/prometheus-operator/issues/5035

In order to refine the prometheus labels and annotations defined in the loaded prometheus rules, it would be quite convenient for the [PrometheusRuleSpec](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.PrometheusRuleSpec) to include new fields such as the followings:
* addititionalLabels (array of Object): for all rules loaded, complements or overrides any prometheus rule labels 
* addititionalAnnotations (array of Object) : for all rules loaded, complements or overrides any prometheus rule labels

**Comment by simonpasquier** [comment]
:wave: @gberche-orange, could you provide more details about your use case (e.g. maybe with 1 or 2 concrete examples)?

Since Kubernetes objects also carry labels & annotations, does it make sense to reference which need to be injected? For instance,

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: example
    team: infra
  annotations:
    escalation-number: "+123456"
  name: prometheus-example-rules
spec:
  injectLabels: [team]
  injectAnnotations: [escalation-number]
  groups:
  - name: ./example.rules
    rules:
    - alert: ExampleAlert

```

**Comment by gberche-orange** [comment]
thanks @simonpasquier 

> could you provide more details about your use case (e.g. maybe with 1 or 2 concrete examples)?

adding onto an existing off-the-shelf prometheus alert such as [host-and-hardware/node-exporter.yml](https://github.com/samber/awesome-prometheus-alerts/blob/master/dist/rules/host-and-hardware/node-exporter.yml#L214) 

1) a set of [prometheus alert rule label](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/)  such as the followings:
* `source: awesome-prometheus-alerts`: the source authoring for this alert
* `local-operators-adoption: alpha`: how much confidence/experience the current operation teams has on this alert

This is then used in the prometheus alert manager to group/filter out alerts from a new source, or of yet low confidence (despites their contributed `severity` level)


2) a set of prometheus alert rules annotations such as the followings:
* `source_url: https://github.com/samber/awesome-prometheus-alerts/blob/master/dist/rules/host-and-hardware/node-exporter.yml`: used by operators to access the git history of an alert definition, create issues, or PR for refinements


Thinking it through, my need is really related to make it easier to reuse existing off-the-shelf prometheus rules (also discussed in #5035) and adapt them to a specific local context. The above examples focused on labels and annotations which could typically be applied "in batch" on a set of rules. 

More fine grained adaptations will likely also be required for a specific given rule on the alert name, `exp`, or `for` attributes. For gitops practionners using kustomize, this would typically be supported by [JSon Patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesjson6902/) or [StrategicMerge Patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesstrategicmerge/)

> Since Kubernetes objects also carry labels & annotations, does it make sense to reference which need to be injected?

I don't yet have use cases where the K8S PrometheusRule CR labels/annotations and the desired deployed prometheus rule labels/annotations would relate. In other words, I don't yet see value in the indirection. Worse, it may sometimes require additional complexity to handle error cases such as missing labels/annotation being referenced as ilustrated in the example below, and may prevent to leverage prometheus specific input validation (json schema) on the label and annotation if they differ from K8S annotations/labels requirements.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: example
    team: infra
  annotations:
    escalation-number: "+123456"
  name: prometheus-example-rules
spec:
  injectLabels: [invalid-missing-label-referenced]
  injectAnnotations: [invalid-missing-annotation-referenced]
  groups:
  - name: ./example.rules
    rules:
    - alert: ExampleAlert
```

**Comment by simonpasquier** [comment]
Thanks for the detailed explanation, it helps a lot.

One use case with labels at least would be that you can easily leverage the same labels to include/exclude rules at the Prometheus level too. But I fail to find a compelling use case for annotations (except that it would be more visible when you look directly at the PrometheusRule resource and you don't have to repeat the information at 2 places).

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: example
spec:
  ruleSelector:
    matchExpressions:
    # exclude alpha rules
    - key: local-operators-adoption
      operator: NotIn
      values: ["alpha"] 
    - key: source
      operator: In
      values: ["awesome-prometheus-alerts"]
```

Anyway the ability to inject static labels/annotations make sense to me. Something like?

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-example-rules
spec:
  labels:
    source: awesome-prometheus-alerts
    local-operators-adoption: alpha
  annotations:
    source_url: https://github.com/samber/awesome-prometheus-alerts/blob/master/dist/rules/host-and-hardware/node-exporter.yml
  groups:
  - name: example.rules
    rules:
    - alert: ExampleAlert
      expr: vector(1)
    - alert: ...
```
