### ISSUE TITLE
Custom configs inside alertmanager for slack

### ISSUE THREAD

**Issue by manikandanramdevops** [prometheus-operator/prometheus-operator#4497]
I tried to add custom configs inside the alertmanager-secrets.yml for slack, But once I added new configs the alertmanger pod crashed.

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.23.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"
      "slack_api_url": "https://hooks.slack.com/services/****"
    "inhibit_rules":
    - "equal":
      - "namespace"
      - "alertname"
      "source_matchers":
      - "severity = critical"
      "target_matchers":
      - "severity =~ warning|info"
    - "equal":
      - "namespace"
      - "alertname"
      "source_matchers":
      - "severity = warning"
      "target_matchers":
      - "severity = critical"
    "receivers":
    - "name": "Default"
    - "name": "Watchdog"
    - "name": "slack"
      "slack_configs":
       - "channel": "#prom"               
       - "send_resolved": true
         "title": "'[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'"
         "text: >- {{ range .Alerts }}"
              "*Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`"
              "*Description:* {{ .Annotations.description }}"
              "*Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>"
              "*Details:*"
              "{{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`"
              "{{ end }}"
            "{{ end }}"
    "route":
      "group_by":
      - "namespace"
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "Default"
      "repeat_interval": "12h"
      "routes":
      - "matchers":
        - "alertname = Watchdog"
        "receiver": "Default"
      - "matchers":
        - "severity = critical"
        "receiver": "slack"
type: Opaque

```

Getting the below error in alertmanager

![image](https://user-images.githubusercontent.com/85827977/149515554-cd1025c9-7394-4629-b87d-62cbac4fffaf.png)

![image](https://user-images.githubusercontent.com/85827977/149515589-6c702e9b-4e2f-4f37-b99b-cd290f5aaa4e.png)

If I remove the below snippet, Every goes as expected, I'm not sure what syntax im missing here

```
 "title": "'[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'"
         "text: >- {{ range .Alerts }}"
              "*Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`"
              "*Description:* {{ .Annotations.description }}"
              "*Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>"
              "*Details:*"
              "{{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`"
              "{{ end }}"
            "{{ end }}"

```

**Comment by manikandanramdevops** [comment]
Similar issue #3751

**Comment by manikandanramdevops** [comment]
Similar issue #3751

**Comment by simonpasquier** [comment]
you've got a typo in your configuration

```
      "slack_configs":
       - "channel": "#prom"               
# wrong here:
#      - "send_resolved": true
# should be:
         "send_resolved": true
         "title": "'[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'"
         "text: >- {{ range .Alerts }}"
              *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
              "*Description:* {{ .Annotations.description }}"
              "*Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>"
              "*Details:*"
              "{{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`"
              "{{ end }}"
            "{{ end }}"
```

**Comment by manikandanramdevops** [comment]
@simonpasquier  Modified the send_resolved but still the same

![image](https://user-images.githubusercontent.com/85827977/149527018-3cf407d8-5c19-4e61-b1aa-5a4d98614640.png)

![image](https://user-images.githubusercontent.com/85827977/149527114-a8313f08-e258-4c11-bcc4-c2024aecad84.png)

**Comment by PhilipGough** [comment]
@manikandanramdevops - I think your YAML is invalid. Verified the following with amtool:

```yaml
"global":
  "resolve_timeout": "5m"
  "slack_api_url": "https://hooks.slack.com/services/****"
"inhibit_rules":
  - "equal":
      - "namespace"
      - "alertname"
    "source_matchers":
      - "severity = critical"
    "target_matchers":
      - "severity =~ warning|info"
  - "equal":
      - "namespace"
      - "alertname"
    "source_matchers":
      - "severity = warning"
    "target_matchers":
      - "severity = critical"
"receivers":
  - "name": "Default"
  - "name": "Watchdog"
  - "name": "slack"
    "slack_configs":
      - "channel": "#prom"
        "send_resolved": true
        "title": |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification
        text: >-
          {{ range .Alerts }}"
            "*Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`"
            "*Description:* {{ .Annotations.description }}"
            "*Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>"
            "*Details:*"
            "{{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`"
            "{{ end }}"
          "{{ end }}"
"route":
  "group_by":
    - "namespace"
  "group_interval": "5m"
  "group_wait": "30s"
  "receiver": "Default"
  "repeat_interval": "12h"
  "routes":
    - "matchers":
        - "alertname = Watchdog"
      "receiver": "Default"
    - "matchers":
        - "severity = critical"
      "receiver": "slack"
```
