### ISSUE TITLE
Service Account Token Volume Projection and PodMonitor

### ISSUE THREAD

**Issue by nabokihms** [prometheus-operator/prometheus-operator#4523]
**Why do we need it?**
We use Kubernetes service account tokens to fetch metrics protected by kube-rbac-proxy. With PodMonitor, it is possible to specify a secret with a token for authentication to access targets (as we can create a token secret with a predictable name, it worked for us).

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
secrets:
- name: prometheus-token
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-token
  annotations:
    kubernetes.io/service-account.name: test
type: kubernetes.io/service-account-token
```
These manifests still work, but there is a better solution.

Starting from the Kubernetes v1.21, the [`Service Account Token Projection`](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) feature is enabled by default. This feature allows us to use more secure renewable tokens mounted by kubelet directly to pods for authentication in Kubernetes API (token only exists on fs, there is no secret with the token). In addition, these tokens are more flexible, e.g., you can control the audience and issuer claims. So, as for newer Kubernetes versions, it is better to use a token from a filesystem than read it from a secret.

As claimed [here](https://github.com/simonpasquier/common/blob/33bc620f956eb70fbb8355e87df6a97891657ed5/config/http_config.go#L215-L216), Prometheus reads a token from the disc for every request. Thus it will automatically renew the projected token. For ServiceMonitors, specifying the `bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token` works, but this option is missing for PodMonitors.

I propose adding this option to PodMonitorSpec (I remember the long discussion about picking certificates from secrets, but the bearer token looks different as per the latest Kubernetes changes).

**Environment**
Kubernetes v1.21

* Prometheus Operator version:

v0.50.0

**Anything else we need to know?**:
