### ISSUE TITLE
Common labels override labels from podMetadata

### ISSUE THREAD

**Issue by brushmate** [prometheus-operator/prometheus-operator#4549]
**What happened?**

When we updated prometheus-operator from ~v0.2.4~ v0.43.2 to v0.53.1 we lost some metrics because one Prometheus instance was not able to do service discovery anymore. This happened because we have some network policies in place that select pods based on the `app.kubernetes.io/instance` label. We used to define this label in the Prometheus `podMetadata` section, but now the label is always the name of the Prometheus resource.

**Did you expect to see something different?**

I expected that the Prometheus pods have the same `app.kubernetes.io/instance` label that is defined in `podMetadata`.

**How to reproduce it (as minimally and precisely as possible)**:

Create a Prometheus:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/instance: owning-app
  name: prometheus
spec:
  podMetadata:
    labels:
      app.kubernetes.io/instance: owning-app
```

And expect a StatefulSet like this:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: owning-app
  name: prometheus-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: owning-app
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: owning-app
```

But get a StatefulSet like this:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: owning-app
  name: prometheus-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: prometheus
```

**Environment**

* Prometheus Operator version:

    `v0.53.1`

**Anything else we need to know?**:

I think this is due to #3841 where some common labels have been introduced. These common labels have a higher precedence than the labels from `podMetadata` and I think it should be the other way round, no?
