### ISSUE TITLE
Why can't I set my own subPath?

### ISSUE THREAD

**Issue by clintmod** [prometheus-operator/prometheus-operator#4560]
Why is it just:

https://github.com/prometheus-operator/prometheus-operator/blob/473a81e954579703d446e1476bfa5fd6c49e45b7/pkg/prometheus/statefulset.go#L973-L980

**Comment by fpetkovski** [comment]
A lot of mount paths are implementation details and not relevant for the user. Could you explain what you're trying to accomplish?

**Comment by clintmod** [comment]
On EKS we have one fsx filesystem that is mounted by containers on various nodes. This fsx file system is used by multiple deployments. I need to set the subpath for the `/prometheus` volumeMount to a different path per deployment.  Why is this hard coded to `prometheus-db` in the code above?

I'm currently working around this by patching the volumeMounts for the  prometheus sts.

**Comment by fpetkovski** [comment]
Could you mount a different directory into each prometheus instance?

**Comment by clintmod** [comment]
> Could you mount a different directory into each prometheus instance?

That's what I'm trying to do… that's what subPath is for and I tried to define it like:
```
prometheus:
  prometheusSpec:
    volumeMounts:
      - mountPath: /prometheus
        name: fsx-prometheus-claim
        subPath: global/prometheus-3
```
but the resulting output has two mountPaths pointing to `/prometheus`

```
        volumeMounts:
        - mountPath: /etc/prometheus/config_out
          name: config-out
          readOnly: true
        - mountPath: /etc/prometheus/certs
          name: tls-assets
          readOnly: true
        - mountPath: /prometheus
          name: fsx-prometheus-claim
          subPath: prometheus-db
        - mountPath: /prometheus
          name: fsx-prometheus-claim
          subPath: global/prometheus-3
        - mountPath: /etc/prometheus/rules/prometheus-prometheus-stack-kube-prom-prometheus-rulefiles-0
          name: prometheus-prometheus-stack-kube-prom-prometheus-rulefiles-0
        - mountPath: /etc/prometheus/web_config/web-config.yaml
          name: web-config
          readOnly: true
          subPath: web-config.yaml
```
