### ISSUE TITLE
too many non active targets

### ISSUE THREAD

**Issue by yelhouti** [prometheus-operator/prometheus-operator#4561]
**What did you do?**
I created a custom serviceMonitor:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  ...
  name: jhipster
  namespace: prometheus
spec:
  endpoints:
  - basicAuth:
     ...
    path: /management/prometheus
    port: http
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      prometheus-type: jhipster
```

I checked the the Prometheus dashboard and it says:
```
serviceMonitor/prometheus/jhipster/0 (1 / 247 active targets)
```

I feel like I am doing something wrong and maybe be wasting resources configuring and checking for info in the wrong places.

**Did you expect to see some different?**
I expect something like: 1/1 since I have only one service matching `prometheus-type: jhipster` for now.
