### ISSUE TITLE
[alertmanager]  AlertmanagerConfig CRD do not overwrite the alertmanager config

### ISSUE THREAD

**Issue by rhollins** [prometheus-operator/prometheus-operator#4569]
I'm trying to customize Alertmanager with custom config using AlertmanagerConfig CDR and following this instruction: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/alerting.md

I have alert manager in debug mode and can't see any event when the CRD AlertmanagerConfig is getting created also the alertmanager config stays the same.

The workaround is to replace secret `alertmanager-prometheus-kube-prometheus-alertmanager` `alertmanager.yaml` each time prometheus operator is deployed from Helm but I would rather use CRD as the preferred method.

Here is Alertmanager resource:

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
  generation: 2
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 30.2.0
    chart: kube-prometheus-stack-30.2.0
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-alertmanager
  namespace: monitoring
spec:
  alertmanagerConfigNamespaceSelector: {}
  alertmanagerConfigSelector:
    matchLabels:
      release: prometheus
  externalUrl: ...
  forceEnableClusterMode: true
  image: quay.io/prometheus/alertmanager:v0.23.0
  listenLocal: false
  logFormat: logfmt
  logLevel: debug
  paused: false
  portName: http-web
  replicas: 1
  retention: 120h
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-kube-prometheus-alertmanager
  version: v0.23.0
```

AlertmanagerConfig resource

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-alertmanager
  labels:
    release: prometheus
spec:
  route:
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'slack'
  receivers:
  - name: 'slack'
    slackConfigs:
    - sendResolved: true
      apiURL:
        name: slack-secret
        key: url
      channel: '#some-monitoring'
      title: 'some alert title'
      text: 'some description'
```

Changed Helm value for alertmanager:

```
    alertmanagerConfigSelector:
      matchLabels:
        release: prometheus
```

What's your helm version?
v3.7.2

What's your kubectl version?
v1.22.4

Which chart?
prometheus-kube-stack

What's the chart version?
30.2.0
