### ISSUE TITLE
alertmanagerconfig has matchType will error

### ISSUE THREAD

**Issue by woshihaoren** [prometheus-operator/prometheus-operator#4582]
**What happened?**
I use this chart kube-prometheus-stack-32.2.1 ,when alertmanagerconfig has matchType. output error like:
```
error validating data: ValidationError(AlertmanagerConfig.spec.route.matchers[1]): unknown field "matchType" in com.coreos.monitoring.v1alpha1.AlertmanagerConfig.spec.route.matchers; if you choose to ignore these errors, turn validation off with --validate=false
```
**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:
    0.54.0
    
    

* Kubernetes version information:

    1.20
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: biz-monitor
  namespace: prometheus
spec:
  route:
    receiver: query
    matchers:
      - name: alert_receiver
        value: query
      - name: site_name
        value: local
        matchType: "!="
    groupBy: [ "alertname" ]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 20m
  receivers:
    - name: 'query'
      webhookConfigs:
        - url: 'http://192.168.1.2'
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
