### ISSUE TITLE
update prometheus-k8s secret data prometheus.yaml.gz data reset

### ISSUE THREAD

**Issue by xichengliudui** [prometheus-operator/prometheus-operator#4588]
**What did you do?**
update secret prometheus-k8s data with k8s client-go, but after the update, data will restore the content before the update

**Did you expect to see some different?**
the `resources version` is updated every time

**Environment**
CentOS Linux release 7.6.1810 (Core)

* Prometheus Operator version:

```yaml
[root@master113-380517 ~]# kubectl -n monitoring describe deployment prometheus-operator
Name:                   prometheus-operator
Namespace:              monitoring
CreationTimestamp:      Wed, 16 Feb 2022 10:47:37 +0800
Labels:                 app.kubernetes.io/component=controller
                        app.kubernetes.io/name=prometheus-operator
                        app.kubernetes.io/version=v0.34.0
                        kubernetes.customized/cluster_component_prometheus=prometheus-operator
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app.kubernetes.io/component=controller,app.kubernetes.io/name=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 0 max surge
Pod Template:
  Labels:           app.kubernetes.io/component=controller
                    app.kubernetes.io/name=prometheus-operator
                    app.kubernetes.io/version=v0.34.0
  Service Account:  prometheus-operator
  Containers:
   prometheus-operator:
    Image:      deploy.bocloud.k8s:40443/coreos/prometheus-operator:v0.34.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --logtostderr=true
      --config-reloader-image=deploy.bocloud.k8s:40443/coreos/configmap-reload:v0.0.1
      --prometheus-config-reloader=deploy.bocloud.k8s:40443/coreos/prometheus-config-reloader:v0.34.0
      --manage-crds=false
      --labels=kubernetes.customized/cluster_component_prometheus=prometheus-k8s
    Limits:
      cpu:     200m
      memory:  200Mi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-6b68489f47 (1/1 replicas created)
Events:          <none>
```
* Kubernetes version information:

```yaml
[root@master113-380517 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Prometheus Operator Logs:
```
level=info ts=2022-02-22T04:32:34.668426323Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2022-02-22T04:32:34.896642585Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
```

**Anything else we need to know?**:

**Comment by xichengliudui** [comment]
How to disable Prometheus sync configuration

**Comment by simonpasquier** [comment]
If you want to override the resources generated by the operator, you need to set `spec.paused: true` in the resource definition.

**Comment by xichengliudui** [comment]
I found a new way to do this using `ServiceMonitor`
I have not used `ServiceMonitor` before，do you know how to configure the following two jobs using `ServiceMonitor`?
```yaml
- job_name: 'istiod'
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - istio-system
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    action: keep
    regex: istiod;http-monitoring
```
```yaml
- job_name: 'envoy-stats'
  metrics_path: /stats/prometheus
  kubernetes_sd_configs:
  - role: pod

  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    action: keep
    regex: '.*-envoy-prom'
```
