### ISSUE TITLE
Implement oauth2 using refresh_token

### ISSUE THREAD

**Issue by SindhuraGowri** [prometheus-operator/prometheus-operator#4589]
**What is missing?**

Oauth2 Implementation using refresh_token 

**Why do we need it?**

Enhancing support for oauth2 authentication. When the endpoint has oauth2 authentication using refresh_token grant type, then we need to fetch access_token from user provided refresh_token secret and then hit the endpoint url for scraping metrics.

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.47`
    
    

**Anything else we need to know?**:

Current implementation of oauth2 uses client_credentials (client_id and client_secret) https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/  but for oauth2 authentication using refresh_token requires (refresh_token secret) https://www.oauth.com/oauth2-servers/access-tokens/refreshing-access-tokens/.

**Comment by SindhuraGowri** [comment]
I am working on the above described enhancement, proposed design change is as below. Thinking to remove "required" properties section for oauth2 and introduce 2 new attributes grant_type and refresh_token.

```
version v1 schema:
  spec:
    endpoints:
       authorisation:
       basicAuth:
       oauth2:
           client_id:
           client_secret:
           token_url:
           scope:
           grant_type: (defaulting to client_credentials for backward compatibility)
           refresh_token:
       path:
       scrapeTimeout:
```

Below is the existing sample spec of endpoint of a resource.
```
version v1 schema:
  spec:
    endpoints:
       authorisation:
       basicAuth:
       oauth2:
           client_id:
           client_secret:
           token_url:
           scope:
       path:
       scrapeTimeout:
```
