### ISSUE TITLE
StaticTarget ServiceMonitor Is Not Updating Prometheus Configuration

### ISSUE THREAD

**Issue by xichengliudui** [prometheus-operator/prometheus-operator#4594]
**What happened?**

I configured static config according to these issues

https://github.com/prometheus-operator/prometheus-operator/pull/1100
https://github.com/prometheus-operator/prometheus-operator/issues/1207

use a serviceMonitor with a static target to monitor another cluster via the /federate endpoint.
No change to the prometheus config file, the new static config was not added.

**Did you expect to see something different?**
the prometheus.yaml config file should have been updated for the new static configs.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl get ServiceMonitor -n monitoring  prometheus-federate -oyaml
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: istio
  name: prometheus-federate
  namespace: monitoring
spec:
  endpoints:
  - honorTimestamps: true
    interval: 15s
    params:
      match[]:
      - '{job="pilot"}'
      - '{job="envoy-stats"}'
    path: /federate
    scheme: http
    scrapeTimeout: 10s
    staticTargets:
    - https://prometheus.mycluster
    - http://somethingelse.mycluster
    - withaport.mycluster:9090
  namesapceSelector:
    any: true
  selector:
    matchLabels:
      k8s-app: istio
```

**Environment**
CentOS Linux release 7.6.1810 (Core)

* Prometheus Operator version:
```yaml
Name:                   prometheus-operator
Namespace:              monitoring
CreationTimestamp:      Mon, 10 Jan 2022 13:10:40 +0800
Labels:                 app.kubernetes.io/component=controller
                        app.kubernetes.io/name=prometheus-operator
                        app.kubernetes.io/version=v0.34.0
                        kubernetes.customized/cluster_component_prometheus=prometheus-operator
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app.kubernetes.io/component=controller,app.kubernetes.io/name=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 0 max surge
Pod Template:
  Labels:           app.kubernetes.io/component=controller
                    app.kubernetes.io/name=prometheus-operator
                    app.kubernetes.io/version=v0.34.0
  Service Account:  prometheus-operator
  Containers:
   prometheus-operator:
    Image:      deploy.bocloud.k8s:40443/coreos/prometheus-operator:v0.34.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --logtostderr=true
      --config-reloader-image=deploy.bocloud.k8s:40443/coreos/configmap-reload:v0.0.1
      --prometheus-config-reloader=deploy.bocloud.k8s:40443/coreos/prometheus-config-reloader:v0.34.0
      --manage-crds=false
      --labels=kubernetes.customized/cluster_component_prometheus=prometheus-k8s
    Limits:
      cpu:     200m
      memory:  200Mi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-6b68489f47 (1/1 replicas created)
Events:          <none>
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Prometheus Operator Logs:

```
level=info ts=2022-02-24T07:22:50.524000911Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2022-02-24T07:22:50.7594505Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2022-02-24T07:24:49.253150514Z caller=operator.go:462 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2022-02-24T07:29:49.2533644Z caller=operator.go:462 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
```

**Comment by xichengliudui** [comment]
I notice that the StaticTarget field has been removed，how do I now configure static_config in ServiceMonitor

**Comment by slashpai** [comment]
AdditionalScrapeConfigs should help, check https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/additional-scrape-config.md

**Comment by xichengliudui** [comment]
Thank you, the use of static_config has upset me

**Comment by xichengliudui** [comment]
> AdditionalScrapeConfigs should help, check https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/additional-scrape-config.md

`error: error validating "sts.yaml": error validating data: ValidationError(StatefulSet.spec): unknown field "additionalScrapeConfigs" in io.k8s.api.apps.v1.StatefulSetSpec; if you choose to ignore these errors, turn validation off with --validate=false`

I can't use `additionalScrapeConfigs`. is that because of my operator version?
```yaml
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
```
