### ISSUE TITLE
Webhook documentation indicates that mutation and validation webhooks both reject invalid rule config 

### ISSUE THREAD

**Issue by wfindley** [prometheus-operator/prometheus-operator#4618]
**What happened?**
I read this documentation that indicates that both webhooks reject invalid rule config.

https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/webhook.md#deploying-the-admission-webhook
> Two variants of the admission webhook are available: a validating webhook and a mutating webhook. *Both reject invalid PrometheusRule resources.*
Emphasis mine.

I implemented only the mutation hook and was still able to send erroneous rules.

**Did you expect to see something different?**
I expected the mutation hook to reject rules that don't pass validation.

**Anything else we need to know?**:
This can be fixed with a document rewrite.

**Comment by PhilipGough** [comment]
Thanks for reporting that. Would you mind adding a copy of the erroneous rule that was accepted? I just want to verify it is a docs issue only as opposed to a bad rule being accepted.

**Comment by wfindley** [comment]
Here it is.  It is completely a docs issue.  When I installed the validating webhook it got rejected.
```
spec:
  groups:
  - name: watchdog.rules
    rules:
    - alert: Watchdog
      annotations:
        message: |
          foo
      expr: vectoooor(1)
      labels:
        severity: none
```
