### ISSUE TITLE
regex in relabelingConfigs not working

### ISSUE THREAD

**Issue by mikakatua** [prometheus-operator/prometheus-operator#4629]
**What happened?**
I have created a Probe for an Ingress object with a relabeling config:
```
      relabelingConfigs:
      - action: replace
        regex: ([^\(]+)
        replacement: ${1}
        sourceLabels: [ __param_target ]
        targetLabel: __param_target
```
The Ingress host/path is `http://monitoring.localnet/prometheus(/|$)(.*)` and this relabeling does not eliminate the regular expression `(/|$)(.*)` at the end of the target url. The relabeling config is ignored and the target url remains the same.

**Did you expect to see something different?**
I would expect that the regex `([^\(]+)` matches the url from the beginning to the first parenthesis:  `http://monitoring.localnet/prometheus`

**How to reproduce it (as minimally and precisely as possible)**:
In a cluster with the Nginx Ingress Controller installed, create an Ingress with a rewrite rule and the Probe resource like in the manifests below.

**Environment**

* Prometheus Operator version: 

    `quay.io/prometheus-operator/prometheus-operator:v0.54.1`
    
    

* Kubernetes version information: 

    `v1.23.4`
    

* Kubernetes cluster kind:

    kubespray

* Manifests:

```
# monitoring-ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: monitoring.localnet
    http:
      paths:
      - backend:
          service:
            name: kps-kube-prometheus-stack-prometheus
            port:
              number: 9090
        path: /prometheus(/|$)(.*)
        pathType: Prefix
---
# blackbox-ingress.yml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
    release: kps
  name: blackbox-ingress
  namespace: monitoring
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: pbe-prometheus-blackbox-exporter.monitoring:9115
  targets:
    ingress:
      namespaceSelector:
        any: true
      selector:
        matchLabels:
          probe: enabled
      relabelingConfigs:
      - action: replace
        regex: ([^\(]+)
        replacement: ${1}
        sourceLabels: [ __param_target ]
        targetLabel: __param_target
```

* Prometheus Operator Logs:

```
No errors found in the logs
```

**Anything else we need to know?**:
Changing the regexp in the relabel config to `(.+)\(.+\(.+` works

**Comment by mikakatua** [comment]
Playing a bit with the regex, I found a solution:
```
      relabelingConfigs:
      - action: replace
        regex: ([^\(]+)\(.+
        replacement: ${1}
        sourceLabels: [ __param_target ]
        targetLabel: __param_target
```
The difference is that this regex pattern matches the **whole string** with the target url, resulting in:
* Match 1: `http://monitoring.localnet/prometheus`
* Rest: `(/|$)(.*)`

The previous regex didn't work because  it had multiple matches. You can check it in https://regex101.com/
