### ISSUE TITLE
Cross namespace service/pod monitors failing

### ISSUE THREAD

**Issue by adyanth** [prometheus-operator/prometheus-operator#4655]
**What did you do?**
I installed the prometheus operator and set up `prometheus`, `servicemonitor` and `podmonitor`.
One of the cross namespace `servicemonitor`  for longhorn is working fine whereas another one for `cloudflared` is not.

**Did you expect to see some different?**
I expected both to work fine

**Environment**

* Prometheus Operator version:

    `v0.55.0`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

    k3sup

* Manifests:

```yaml
# working:
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn
  namespace: monitoring
  labels:
    name: longhorn
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
      - longhorn-system
  endpoints:
    - port: manager
---
# Non working
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudflared
  namespace: monitoring
  labels:
    name: cloudflared
spec:
  selector:
    matchLabels:
      cfargotunnel.com/app: cloudflared
  namespaceSelector:
    matchNames:
      - cloudflare-operator-system
  podMetricsEndpoints:
    - port: metrics
---
# Non working
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    name: kube-state-metrics
  name: kube-state-metrics
  namespace: monitoring
spec:
  endpoints:
    - port: http-metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kube-state-metrics
  namespaceSelector:
    matchNames:
      - kube-system
```

* Prometheus Operator Logs:
No relevant logs
```
ts=2022-03-17T21:13:01.424Z caller=head.go:493 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2022-03-17T21:13:01.425Z caller=head.go:536 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=5.316µs
ts=2022-03-17T21:13:01.425Z caller=head.go:542 level=info component=tsdb msg="Replaying WAL, this may take a while"
ts=2022-03-17T21:13:01.425Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=4
ts=2022-03-17T21:13:02.478Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=1 maxSegment=4
ts=2022-03-17T21:13:02.498Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=2 maxSegment=4
ts=2022-03-17T21:13:02.506Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=3 maxSegment=4
ts=2022-03-17T21:13:02.507Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=4 maxSegment=4
ts=2022-03-17T21:13:02.507Z caller=head.go:619 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=66.63µs wal_replay_duration=1.081700304s total_replay_duration=1.081831558s
ts=2022-03-17T21:13:02.509Z caller=main.go:958 level=info fs_type=EXT4_SUPER_MAGIC
ts=2022-03-17T21:13:02.509Z caller=main.go:961 level=info msg="TSDB started"
ts=2022-03-17T21:13:02.509Z caller=main.go:1142 level=info msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
ts=2022-03-17T21:13:02.512Z caller=kubernetes.go:313 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2022-03-17T21:13:02.518Z caller=kubernetes.go:313 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2022-03-17T21:13:02.520Z caller=kubernetes.go:313 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2022-03-17T21:13:02.520Z caller=main.go:1179 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=11.149703ms db_storage=601ns remote_storage=966ns web_handler=326ns query_engine=24.196µs scrape=1.046362ms scrape_sd=9.025099ms notify=1.484µs notify_sd=1.511µs rules=1.697µs tracing=3.547µs
ts=2022-03-17T21:13:02.520Z caller=main.go:910 level=info msg="Server is ready to receive web requests."
ts=2022-03-17T21:13:06.305Z caller=main.go:1142 level=info msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
ts=2022-03-17T21:13:06.306Z caller=kubernetes.go:313 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2022-03-17T21:13:06.307Z caller=kubernetes.go:313 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2022-03-17T21:13:06.308Z caller=kubernetes.go:313 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2022-03-17T21:13:06.308Z caller=main.go:1179 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=3.125282ms db_storage=924ns remote_storage=2.341µs web_handler=277ns query_engine=964ns scrape=55.201µs scrape_sd=2.125551ms notify=713ns notify_sd=1.07µs rules=1.479µs tracing=3.015µs
```

**Anything else we need to know?**:

Service/Pod monitors look correct to me:

```bash
❯ k -n cloudflare-operator-system get pods -l cfargotunnel.com/app=cloudflared -o jsonpath='{.items[*].spec.containers[*].ports[*].name}'
metrics
❯ k -n kube-system get pods -l app.kubernetes.io/component=exporter -l app.kubernetes.io/name=kube-state-metrics -o jsonpath='{.items[*].spec.containers[*].ports[*].name}'
http-metrics telemetry                                                                                                                           
❯ k -n longhorn-system get pods -l app=longhorn-manager -o jsonpath='{.items[*].spec.containers[*].ports[*].name}'
manager manager manager
```
<img width="569" alt="Screenshot 2022-03-18 at 2 54 43 AM" src="https://user-images.githubusercontent.com/33192449/158897604-bfcd1db5-4d23-4885-a7f3-043b6e1b07a4.png">

<img width="925" alt="Screenshot 2022-03-18 at 2 54 51 AM" src="https://user-images.githubusercontent.com/33192449/158897615-79e83aac-d93d-4729-b7ca-21f14b9516db.png">

**Comment by adyanth** [comment]
My bad for not RTFM. I had to add the below to the `Prometheus` and the `ServiceMonitor` and `PodMonitor`

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      monitor: prometheus
  podMonitorSelector:
    matchLabels:
      monitor: prometheus
...
```

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudflared
  labels:
    name: cloudflared
    monitor: prometheus
...
```

Can someone tell me how did it work for the 2 podMonitors and the 1 serviceMonitor without me adding anything? The documentation seems to say the following:

> serviceMonitorSelector       <Object>
     ServiceMonitors to be selected for target discovery. *Deprecated:* if
     neither this nor podMonitorSelector are specified, configuration is
     unmanaged.
