### ISSUE TITLE
thanos sidecar lost permission to work from v0.55.0 due to securityContext

### ISSUE THREAD

**Issue by dullest** [prometheus-operator/prometheus-operator#4664]
**What happened?**

thanos-sidecar cannot upload objects after upgrading to v0.55.0 from v0.54.1.
It seems thanos-sidecar needs some securityContext.capabilities.
I didn't check which capabilities are required but `securityContext.capabilities: {}` for thanos-sidecar can work.

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

Deploy prometheus with operator v0.55.0 with thanos and bucket config.

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  thanos:
    baseImage: quay.io/thanos/thanos
    version: v0.25.1
    objectStorageConfig:
      key: thanos-objstore-config.yaml
      name: thanos-objstore-config
```

**Environment**

* Prometheus Operator version:

    `v0.55.0`
    
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
`
    

* Kubernetes cluster kind:

   minikube

* Manifests:

Generated prometheus pod has `capabilities.drop: [ALL]` as expected of v0.55.0's behavior.

```
  - args:
    name: thanos-sidecar
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
```

* Prometheus Operator Logs:

prometheus pod's thanos-sidecar logs

```
level=info ts=2022-03-19T08:17:16.390597429Z caller=shipper.go:334 msg="upload new block" id=01FYGM0SXBS2J08J3QT847E078
level=warn ts=2022-03-19T08:17:16.393475738Z caller=sidecar.go:341 err="upload 01FYGM0SXBS2J08J3QT847E078: hard link block: hard link file chunks/000001: link /prometheus/01FYGM0SXBS2J08J3QT847E078/chunks/000001 /prometheus/thanos/upload/01FYGM0SXBS2J08J3QT847E078/chunks/000001: operation not permitted" uploaded=0
```

**Anything else we need to know?**:

I guess users can manage security context once #3993 is implemented.
But I don't know how we can override capabilities of thanos-sidecar containers with v0.55.0 because following containers settings for it is ignored.

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  thanos:
    baseImage: quay.io/thanos/thanos
    version: v0.25.1
    objectStorageConfig:
      key: thanos-objstore-config.yaml
      name: thanos-objstore-config
  containers:
  - args:
    name: thanos-sidecar
    securityContext:
      capabilities: {}
```

**Comment by dullest** [comment]
Checked thanos process capabilities with `quay.io/thanos/thanos:v0.25.1`

```sh
k exec -it prometheus-main-0 -c  thanos-sidecar -- cat /proc/1/status | grep Cap
CapInh: 00000000a80425fb
CapPrm: 00000000a80425fb
CapEff: 00000000a80425fb
CapBnd: 00000000a80425fb
CapAmb: 0000000000000000

capsh --decode=00000000a80425fb
0x00000000a80425fb=cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap
```

So I could upload with following `securityContext.capabilities`.

```
    securityContext:
      capabilities:
        add:
        - CHOWN
        - DAC_OVERRIDE
        - FOWNER
        - FSETID
        - KILL
        - SETGID
        - SETUID
        - SETPCAP
        - NET_BIND_SERVICE
        - NET_RAW
        - SYS_CHROOT
        - MKNOD
        - AUDIT_WRITE
        - SETFCAP
```

**Comment by dullest** [comment]
This can be fixed by adding runAsUser.

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  securityContext:
    runAsUser: 1001
~~~
```
