### ISSUE TITLE
Limiting targets with the same data

### ISSUE THREAD

**Issue by renebarbosafl** [prometheus-operator/prometheus-operator#4674]
**What did you do?**

We have a k8s running where every single pod exports basically the same data through Prometheus endpoints. We want to setup a serviceMonitor and we want to scrape only one pod/endpoint per time (or maybe the load balancer itself). We tried to set `targetLimit: 1` on serviceMonitor's spec and no one of our endpoints were scraped.

**Did you expect to see some different?**

Only one (of 4, for example) endpoint added as a target and scraped.

**Environment**

* Prometheus Operator version:

    `v0.54.1`
    
    

* Kubernetes version information:

    `1.21`
    

* Kubernetes cluster kind:

EKS

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: wa-stats-app
  namespace: monitoring
spec:
  endpoints:
  - authorization:
      credentials:
        key: apikey
        name: wa-metrics
      type: Apikey
    interval: 60s
    params:
      format:
      - prometheus
    path: /v1/stats/app
    port: web
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_label_webapp
      targetLabel: service
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - whatsapp
  selector:
    matchLabels:
      prometheus.io/scrape: "true"
```

* Prometheus Operator Logs:

Nothing relevant, tons of lines like these:
```
level=info ts=2022-03-23T00:55:59.672024266Z caller=operator.go:1221 component=prometheusoperator key=monitoring/prometheus-prometheus msg="sync prometheus"
level=info ts=2022-03-23T00:56:00.37965301Z caller=operator.go:741 component=alertmanageroperator key=monitoring/prometheus-alertmanager msg="sync alertmanager"
level=info ts=2022-03-23T00:56:00.403469787Z caller=operator.go:1221 component=prometheusoperator key=monitoring/prometheus-prometheus msg="sync prometheus"
level=info ts=2022-03-23T01:03:52.738269159Z caller=operator.go:1221 component=prometheusoperator key=monitoring/prometheus-prometheus msg="sync prometheus"
level=info ts=2022-03-23T01:03:53.461822456Z caller=operator.go:741 component=alertmanageroperator key=monitoring/prometheus-alertmanager msg="sync alertmanager"
level=info ts=2022-03-23T01:03:53.490693046Z caller=operator.go:1221 component=prometheusoperator key=monitoring/prometheus-prometheus msg="sync prometheus"
level=info ts=2022-03-23T01:09:16.299784606Z caller=operator.go:1221 component=prometheusoperator key=monitoring/prometheus-prometheus msg="sync prometheus"
level=info ts=2022-03-23T01:09:16.998127274Z caller=operator.go:741 component=alertmanageroperator key=monitoring/prometheus-alertmanager msg="sync alertmanager"
level=info ts=2022-03-23T01:09:17.0337916Z caller=operator.go:1221 component=prometheusoperator key=monitoring/prometheus-prometheus msg="sync prometheus"
```

**Anything else we need to know?**:

N/A
