### ISSUE TITLE
servicemonitor加入基本认证，Prometheus依然显示server returned HTTP status 401 Unauthorized

### ISSUE THREAD

**Issue by jhsswl** [prometheus-operator/prometheus-operator#4689]
监控外部主机，需要基本认证
host-servicemonitor.yaml 配置

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: node-jf
    prometheus: k8s
  name: node-jf
  namespace: monitoring
spec:
  endpoints:
    - interval: 120s
      port: http-9100
      scheme: http
      basicAuth:
        username:
          name: node-jf-secret
          key: user
        password:
          name: node-jf-secret
          key: password
  jobLabel: app
  namespaceSelector:
    matchNames:
      - monitoring
  selector: {}
```

==================
cat host-secret.yaml
```

apiVersion: v1
kind: Secret
metadata:
  name: node-jf-secret
  namespace: monitoring
data:
  user: amhz
  password: amhz
type: Opaque
```

=====================
cat host-endpoints.yaml
```
apiVersion: v1
kind: Endpoints
metadata:
  name: node-jf
  namespace: monitoring
subsets:
- addresses:
  - ip: 192.168.20.12     
  - ip: 192.168.20.13    
  - ip: 192.168.20.14     
  ports:
  - name: http-9100
    port: 9100
    protocol: TCP
```

=============
cat host-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-jf
  name: node-jf
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: http-9100
      port: 9100
      protocol: TCP
      targetPort: http-9100
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
======
外部机器node_exporter配置
cat node_exporter/config.yaml
```
basic_auth_users:
  jhs: $2y$12$qI7tS0YsG0rGecOtLcOBJeIPKjmhYj543sVebw8x31fudJxvXpMHq
```

node_exporter不用基础认证是可以获取到信息的，prometheus上还需要配置什么吗

![image](https://user-images.githubusercontent.com/35069629/160366540-cb3d6f70-3b43-4569-b145-f9e071163cae.png)

![image](https://user-images.githubusercontent.com/35069629/160366622-976cfa24-2e77-4d25-8b31-d6d0731ff84b.png)

![image](https://user-images.githubusercontent.com/35069629/160366920-e9c7a4b3-51e8-4916-8dc3-6a5d7477bce7.png)
