### ISSUE TITLE
[Question] Missing app=prometheus label on pod

### ISSUE THREAD

**Issue by AnthonyWC** [prometheus-operator/prometheus-operator#4696]
Somehow kubernetes operator pod is missing app=prometheus label on pod:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  image: quay.io/prometheus/prometheus:v2.34.0
```

```
kubectl get pod prometheus-prometheus-0 --show-labels                                                                              
NAME                      READY   STATUS    RESTARTS   AGE   LABELS
prometheus-prometheus-0   2/2     Running   0          29m   app.kubernetes.io/instance=prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,app.kubernetes.io/version=2.34.0,controller-revision-hash=prometheus-prometheus-5bbc56645,operator.prometheus.io/name=prometheus,operator.prometheus.io/shard=0,prometheus=prometheus,statefulset.kubernetes.io/pod-name=prometheus-prometheus-0
```

Endpoint and many other resources has dependency on that label; anyone know what could be causing this? 

p.s. If someone can change label to question
