### ISSUE TITLE
Prometheus not showing rules and alerts

### ISSUE THREAD

**Issue by daneearquero** [prometheus-operator/prometheus-operator#4707]
Hi, We are trying to create a prometheus rule and alert.We have applied it in our namespace and can see the configuration when we run `kubectl describe` but it is not showing in the prometheus site

Sample Rule :

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
labels:
release: prometheus
name: test-rule
namespace: test-namespace
spec:
groups:

name: test-rule
rules:
alert: InstanceDown
expr: ...
```

Sample Alert:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: test-alert
  namespace: test-namespace
  labels:
    release: prometheus
spec:
  route:
    groupBy: ['alertname','job']
    receiver: 'test-namespace'
    continue: true
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
  receivers:
  - name: 'test-namespace'
    slackConfigs:
    - channel: 
```

Are there any prerequisites needed? Did we miss anything
Thank you!
