### ISSUE TITLE
Custom config-reloader resource limits

### ISSUE THREAD

**Issue by ctml91** [prometheus-operator/prometheus-operator#4712]
I did do some searching and came across some older issues related to the topic of config-reloader resources but need some clarification. 

2364
3883

I am looking to see if there is a way to configure the init container resources (config-reloader) through the Prometheus CR (I could only find the spec for prometheus itself, and adding additional init containers). The defaults are too big for what I need, and I'd like to set them a bit lower to save on resources. I have installed prometheus via OLM, so ideally it would not be an argument to the operator controller as it's going to reconcile those changes but from what I gathered from the mentioned issues that was how it was implemented. If I am wrong, or there is documentation I missed that shows this process please let me know. Thanks in advance!

**Comment by ctml91** [comment]
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec

Sorry, found it :) For anyone else who comes across, you can override the `config-reloader` container spec.

```
  containers:
    - name: config-reloader
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 50Mi
```
