### ISSUE TITLE
opsgenie_configs field api_key_file not found in type config.plain

### ISSUE THREAD

**Issue by ihorhritskiv** [prometheus-operator/prometheus-operator#4714]
**What happened?**

**prometheus-operator** not able to sync **alertmanager** configuration

**Environment**

* Prometheus Operator version:

    `image: quay.io/prometheus-operator/prometheus-operator:v0.55.0`

* Alertmanager version:

    `image: quay.io/prometheus/alertmanager:v0.24.0`

* Alertmanager config:

```
        global:
          resolve_timeout: 5m
        route:
          group_by: ['job']
          group_wait: 10s
          group_interval: 5m
          repeat_interval: 3h
          receiver: 'opsgenie'
          routes:
          - matchers:
            - alertname = Watchdog
            receiver: 'null'
        receivers:
        - name: 'null'
        - name: 'opsgenie'
          opsgenie_configs:
          - send_resolved: true
            api_key_file: /mnt/secrets-store/opsgenie-api-key
```

* Prometheus Operator Logs:

```
{"caller":"klog.go:116","component":"k8s_client_runtime","func":"ErrorDepth","level":"error","msg":"Sync \"monitoring/prometheus-alertmanager\" failed: provision alertmanager configuration: base config from Secret could not be parsed: yaml: unmarshal errors:\n  line 11: field api_key_file not found in type config.plain","ts":"2022-04-13T06:52:45.390938478Z"}
```
