### ISSUE TITLE
Service Monitor No Active Targets - Target Labels are dropped

### ISSUE THREAD

**Issue by octopus20** [prometheus-operator/prometheus-operator#4724]
<!--

Feel free to ask questions in #prometheus-operator on Kubernetes Slack!

Note: This repository is about prometheus-operator itself, if you have questions about:
- helm installation, go to https://github.com/prometheus-community/helm-charts repository
- kube-prometheus setup, go to https://github.com/prometheus-operator/kube-prometheus

-->

**What did you do?**

Creating a ServiceMonitor to monitor Kubernetes service, the service and its ServiceMonitor are in other namespaces than Prometheus and it appears on Prometheus Service Discovery but showing 0/1 active targets and when expand the discovered service is has  "dropped" in the Target Label column. 



**Environment**


* Prometheus Operator version:
 `Prometheus Operator" version="(version=0.50.0, branch=master, revision=83fe36566)"`

* Kubernetes version information:

    `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"31c58a08fe4dd916f981cd61db406a61c4b789eb", GitTreeState:"clean", BuildDate:"2021-09-17T05:25:38Z", GoVersion:"go1.15.15 BoringCrypto", Compiler:"gc", `Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

   Oracle managed Kubernetes

* Manifests:

```
apiVersion: v1
kind: Service
metadata:
  name: my-service-external
  namespace: my-services
  labels:
    service: AAA
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: metrics
  selector: {}

---
kind: Endpoints
apiVersion: v1
metadata:
  name: my-service-external
  namespace: my-services
subsets:
  - addresses:
      - ip: 10.0.0.0 #ex ip
    ports:
      - port: 3000
       
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-service-monitors
  namespace: my-services
  labels:
    app.kubernetes.io/instance: loki-prometheus-stack
    release: loki-prometheus-stack
spec:                                                                                                                                                                                                                                  
  endpoints:                                                                                                                                                                                                                              
  - interval: 30s                                                                                                                                                                                                                         
    port: metrics                                                                                                                                                                                                                     
  namespaceSelector:                                                                                                                                                                                                                      
    matchNames:                                                                                                                                                                                                                           
    - my-services                                                                                                                                                                                                                       
  selector:                                                                                                                                                                                                                               
    matchLabels:                                                                                                                                                                                                                          
      service: AAA
```

* Prometheus Operator Logs:

```
No logs in operator 

```

**Anything else we need to know?**:

The discovered service somehow appeared in /targets but without any information in targets table (Empty Table), then it's disappeared again!
