### ISSUE TITLE
Configurable startup/liveness/readiness Probe

### ISSUE THREAD

**Issue by ktaborski** [prometheus-operator/prometheus-operator#4730]
**What is missing?**
I would like to have possibility to change startup/liveness/readiness probes parameters in statefulset via `Prometheus` CRD.

**Why do we need it?**
Currently my prometheus stucked in restart loop (due to long WAL-replay) and k8s is killing container before it gets ready. I would like to extend startupProbe.

**Environment**

* Prometheus Operator version:

    `v0.55.0`
    
    

**Anything else we need to know?**:
NA

**Comment by simonpasquier** [comment]
How long does it take for Prometheus to complete the WAL replay in your case? I think that we'd be ok extending the current value.

You can already patch the generated statefulset using the `containers` field:

```
spec:
  containers:
  - name: prometheus
    startupProbe:
      failureThreshold: 120
```

**Comment by dmerrick** [comment]
I support this. The WAL crashloop is unfortunately a very common problem with Prometheus right now:

* https://github.com/prometheus-operator/prometheus-operator/issues/3391
* https://github.com/prometheus/prometheus/issues/6934

**Comment by fpetkovski** [comment]
Instead of directly changing probes, we should consider either baking in a startup probe with a long threshold, or exposing a field like `startupFailureThreshold` in the spec itself.

**Comment by ktaborski** [comment]
> You can already patch the generated statefulset using the containers field

Patching statefulset didn't helped, because prometheus-operator revert changes.

> How long does it take for Prometheus to complete the WAL replay in your case?

I do not really know. I had to remove `wal` directory to make app running again.

**Comment by simonpasquier** [comment]
> Patching statefulset didn't helped, because prometheus-operator revert changes.

Sorry I wasn't clear enough, I meant patching the generated statefulset using [strategic merge patch](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/strategic-merge-patch.md) like this:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: example
spec:
  containers:
  - name: prometheus
    startupProbe:
      failureThreshold: 120
```

**Comment by ktaborski** [comment]
Cool! This was feature I was looking for!

**Comment by AdheipSingh** [comment]
@brancz is this something we can add, would be willing to submit a PR for this

**Comment by tongpu** [comment]
I just want to put there here for anyone else arriving here via a search engine. The `containers` and `init-containers` fields already support the following configuration, because they use a strategic merge patch to merge the default configuration with any values provided via the spec, so

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: example
spec:
  containers:
  - name: prometheus
    startupProbe:
      failureThreshold: 120
```
already works for increasing the `failureThreshold` of the `prometheus` container.

However the documentation created in #3823 seems to be gone.

**Comment by mchiappini** [comment]
What @tongpu suggested worked perfectly. For those using the `kube-prometheus-stack` the way to do it would look like this:
```
prometheus:
  prometheusSpec:
    containers:
      - name: prometheus
        startupProbe:
          failureThreshold: 60
          periodSeconds: 30
```
