### ISSUE TITLE
Servicemonitor: Service Discovery Ok, but 0 target

### ISSUE THREAD

**Issue by osaffer** [prometheus-operator/prometheus-operator#4739]
Hi,

I try to get the metrics in prometheus, but it shows 0 target : Here is my configuration : 

Thanks for your help

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hippo-servicemonitor
  namespace: testdb
  labels:
    name: hippo-servicemonitor
spec:
  endpoints:
    - port: postgres-metrics
      path: /metrics
      honorLabels: true
      interval: 10s
      relabelings:
      - sourceLabels: [ __meta_kubernetes_pod_label_crunchy_postgres_exporter ]
        action: keep
        regex: "true"
      - sourceLabels: [ __meta_kubernetes_pod_container_port_number ]
        action: drop
        regex: "5432"
      - sourceLabels: [ __meta_kubernetes_pod_container_port_number ]
        action: drop
        regex: "10000"
      - sourceLabels: [ __meta_kubernetes_pod_container_port_number ]
        action: drop
        regex: "8009"
      - sourceLabels: [ __meta_kubernetes_pod_container_port_number ]
        action: drop
        regex: "2022"
      - sourceLabels: [ __meta_kubernetes_namespace ]
        action: replace
        targetLabel: kubernetes_namespace
      - sourceLabels: [ __meta_kubernetes_pod_name ]
        targetLabel: pod
      - sourceLabels: [ __meta_kubernetes_namespace,__meta_kubernetes_pod_label_pg_cluster ]
        targetLabel: pg_cluster
        separator: ':'
        replacement: '$1$2'
      - sourceLabels: [ __meta_kubernetes_pod_ip ]
        targetLabel: ip
        replacement: '$1'
      - sourceLabels: [ __meta_kubernetes_pod_label_deployment_name ]
        targetLabel: deployment
        replacement: '$1'
      - sourceLabels: [ __meta_kubernetes_pod_label_role ]
        targetLabel: role
        replacement: '$1'
      - sourceLabels: [ dbname ]
        targetLabel: dbname
        replacement: '$1'
      - sourceLabels: [ relname ]
        targetLabel: relname
        replacement: '$1'
      - sourceLabels: [ schemaname ]
        targetLabel: schemaname
        replacement: '$1'
      - targetLabel: exp_type
        replacement: 'pg'
  namespaceSelector:
    matchNames:
      - testdb 
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/crunchy-postgres-exporter: "true"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    postgres-operator.crunchydata.com/crunchy-postgres-exporter: "true"
  name: hippo-servicemonitor
  namespace: testdb
spec:
  selector:
    postgres-operator.crunchydata.com/crunchy-postgres-exporter: "true"
  ports:
  - name: postgres-metrics
    port: 9187
    protocol: TCP
    targetPort: 9187
  type: ClusterIP
```
