### ISSUE TITLE
http: TLS handshake error from [ip]:[port]: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by lazychanger** [prometheus-operator/prometheus-operator#4741]
**Environment**

* Prometheus Operator version: 

```txt
quay.io/prometheus-operator/prometheus-operator:v0.55.0
```

* Kubernetes version information:

```txt
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T13:00:45Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-aliyunedge.1", GitCommit:"1403255", GitTreeState:"", BuildDate:"2021-12-27T08:07:37Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

```txt
aliyun ack cluster
```

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
level=warn ts=2022-04-21T10:56:36.737029994Z caller=operator.go:316 component=prometheusoperator msg="failed to check if the API supports the endpointslice resources" err="converting (v1.APIGroup) to (v1.APIResourceList): unknown conversion"
level=info ts=2022-04-21T10:56:36.737078655Z caller=operator.go:318 component=prometheusoperator msg="Kubernetes API capabilities" endpointslices=false
level=info ts=2022-04-21T10:56:36.737078655Z caller=operator.go:318 component=prometheusoperator msg="Kubernetes API capabilities" endpointslices=false
level=info ts=2022-04-21T10:56:36.738938505Z caller=main.go:113 msg="Starting secure server on [::]:10250"
level=info ts=2022-04-21T10:56:36.739441769Z caller=operator.go:309 component=thanosoperator msg="connection established" cluster-version=v1.20.11-aliyunedge.1
level=info ts=2022-04-21T10:56:36.739461756Z caller=operator.go:318 component=thanosoperator msg="CRD API endpoints ready"
level=info ts=2022-04-21T10:56:36.740895295Z caller=operator.go:427 component=prometheusoperator msg="connection established" cluster-version=v1.20.11-aliyunedge.1
level=info ts=2022-04-21T10:56:36.74091351Z caller=operator.go:436 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2022-04-21T10:56:36.741778132Z caller=operator.go:448 component=alertmanageroperator msg="connection established" cluster-version=v1.20.11-aliyunedge.1
level=info ts=2022-04-21T10:56:36.741797849Z caller=operator.go:457 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2022-04-21T10:56:36.84005484Z caller=operator.go:261 component=thanosoperator msg="successfully synced all caches"
ts=2022-04-21T10:56:37.033536149Z caller=stdlib.go:105 caller=server.go:3158 msg="http: TLS handshake error from 10.21.4.64:36300: remote error: tls: bad certificate"
ts=2022-04-21T10:56:37.037875351Z caller=stdlib.go:105 caller=server.go:3158 msg="http: TLS handshake error from 10.21.4.64:36302: remote error: tls: bad certificate"
level=info ts=2022-04-21T10:56:37.041822636Z caller=operator.go:357 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2022-04-21T10:56:37.042027891Z caller=operator.go:280 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2022-04-21T10:56:37.042327264Z caller=operator.go:1228 component=prometheusoperator key=monitoring/prometheus-prometheus msg="sync prometheus"
ts=2022-04-21T10:56:37.04406326Z caller=stdlib.go:105 caller=server.go:3158 msg="http: TLS handshake error from 10.21.4.64:36304: remote error: tls: bad certificate"
level=info ts=2022-04-21T10:56:37.045111758Z caller=operator.go:741 component=alertmanageroperator key=monitoring/prometheus-alertmanager msg="sync alertmanager"
level=warn ts=2022-04-21T10:56:37.056107809Z caller=amcfg.go:1486 component=alertmanageroperator alertmanager=prometheus-alertmanager namespace=monitoring receiver="null" msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="unsupported value type" match_re="unsupported value type"
level=info ts=2022-04-21T10:56:37.130040852Z caller=operator.go:741 component=alertmanageroperator key=monitoring/prometheus-alertmanager msg="sync alertmanager"
level=warn ts=2022-04-21T10:56:37.139807396Z caller=amcfg.go:1486 component=alertmanageroperator alertmanager=prometheus-alertmanager namespace=monitoring receiver="null" msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="unsupported value type" match_re="unsupported value type"
level=info ts=2022-04-21T10:56:37.385622375Z caller=operator.go:1228 component=prometheusoperator key=monitoring/prometheus-prometheus msg="sync prometheus"
ts=2022-04-21T10:56:56.850897747Z caller=stdlib.go:105 caller=server.go:3158 msg="http: TLS handshake error from 10.21.4.64:36496: remote error: tls: bad certificate"
ts=2022-04-21T10:56:56.854753992Z caller=stdlib.go:105 caller=server.go:3158 msg="http: TLS handshake error from 10.21.4.64:36498: remote error: tls: bad certificate"
ts=2022-04-21T10:56:56.859322724Z caller=stdlib.go:105 caller=server.go:3158 msg="http: TLS handshake error from 10.21.4.64:36500: remote error: tls: bad certificate"
ts=2022-04-21T10:57:26.851634226Z caller=stdlib.go:105 caller=server.go:3158 msg="http: TLS handshake error from 10.21.4.64:36794: remote error: tls: bad certificate"
ts=2022-04-21T10:57:26.855836971Z caller=stdlib.go:105 caller=server.go:3158 msg="http: TLS handshake error from 10.21.4.64:36796: remote error: tls: bad certificate"
ts=2022-04-21T10:57:26.859689729Z caller=stdlib.go:105 caller=server.go:3158 msg="http: TLS handshake error from 10.21.4.64:36798: remote error: tls: bad certificate"
```

**Anything else we need to know?**:

**Install command**:
```shell
helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring -f ./prometheus-stack-values.yaml
```

**prometheus-stack-values.yaml**:
```yaml
nameOverride: prometheus
defaultRules:
  rules:
    alertmanager: true
    etcd: false
    configReloaders: true
    general: false
    k8s: false
    kubeApiserver: false
    kubeApiserverAvailability: false
    kubeApiserverSlos: false
    kubelet: false
    kubeProxy: false
    kubePrometheusGeneral: false
    kubePrometheusNodeRecording: false
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: false
    kubeScheduler: false
    kubeStateMetrics: false
    network: false
    node: false
    nodeExporterAlerting: false
    nodeExporterRecording: false
    prometheus: true
    prometheusOperator: true
alertmanager:
  enabled: true
grafana:
  enabled: true
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 60
      - type: Resource
        resource:
          name: memory
          targetAverageUtilization: 60
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: false
kube-state-metrics:
  enabled: false
  prometheus:
    monitor:
      enabled: false
nodeExporter:
  enabled: false
prometheus-node-exporter:
  enabled: false
  prometheus:
    monitor:
      enabled: false
prometheusOperator:
  enabled: true
  tls:
    enabled: true
  kubeletService:
    enabled: false
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
prometheus:
  enabled: true
  servicePerReplica:
    enabled: true
  enableAdminAPI: true
  prometheusSpec:
    replicas: 2
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: prometheus-data
          volumeMode: Filesystem
```
