### ISSUE TITLE
How to monitor a static port  to be scrapped by Prometheus from the Node port outside K8s

### ISSUE THREAD

**Issue by satyabratabharati** [prometheus-operator/prometheus-operator#4748]
Hi Team,

I want to monitor a static port form the node. my application is running on the node host and write the metrics to a the local host port in the node itself. example 0.0.0.0:9090.

I want to monitor via the Prometheus operator. For some reason,  I am not able to scape it.

```
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: app
  namespace: monitoring-system
spec:
  jobName: app
  interval: 10s
  prober:
    url: 0.0.0.0:9090
    path: /metrics
  targets:
    staticConfig:
      static:
      - 0.0.0.0
```

Can anyone help me with a probe example? 

 or is  there another  way I can achieve this.

Thank You.
