### ISSUE TITLE
Cannot add the external nodes as targets to prometheus-operator in kubernetes

### ISSUE THREAD

**Issue by bharathpantala** [prometheus-operator/prometheus-operator#4752]
Cannot add the external nodes as targets to prometheus-operator in kubernetes 

My prom release on k8s is : **prometheus-operator**

Followed the same https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/additional-scrape-config.md

Can someone give some doc to add external node-exporter as targets to prometheus-operator in kubernetes.

**Comment by slashpai** [comment]
May be there are better ways but I tested this way in local cluster and it works.  We will create the the service without selector and then define the endpoints separately. And then create servicemonitor. Treat this as example and tweak settings as per your need :)

1. Create service object for external node-exporter with selector

```yaml
kind: Service
apiVersion: v1
metadata:
 name: node-exporter-external
 labels:
    app: node-exporter-external
spec:
 type: ClusterIP
 ports:
 - name: metrics
   port: 9100
   targetPort: 9100
```

2. Create endpoint object separately

```yaml
kind: Endpoints
apiVersion: v1
metadata:
 name: node-exporter-external
subsets:
- addresses:
  - ip: <node external ip>
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
```

3. Create servicemonitor

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: node-exporter-external
  name: node-exporter-external
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: node-exporter-external
```
