### ISSUE TITLE
opsgenie field api_key_file not found in type config.plain

### ISSUE THREAD

**Issue by upstream-dmahlberg** [prometheus-operator/prometheus-operator#4755]
**What happened?**

prometheus-operator is not able to sync alertmanager configuration when setting either receivers.[x].opsgenie_configs.api_key_file or global.opsgenie_api_key_file.

**Environment**

* Prometheus Operator version:
  Image:         quay.io/prometheus-operator/prometheus-operator:v0.56.0

* Helm Chart version:
  - name: kube-prometheus-stack
    version: 35.0.0
    repository: https://prometheus-community.github.io/helm-charts

* Kubernetes version information:
    1.21.6

* Alertmanager version:
  Image:         quay.io/prometheus/alertmanager:v0.24.0 

* Alertmanager config:
```yaml
# setting global results in the same error
# global:
  # opsgenie_api_key_file: '/etc/alertmanager/secrets/opsgenie-api-key/opsgenie-api-key'
  # opsgenie_api_url: 'https://api.eu.opsgenie.com/'
route:
  group_by: ['job']
  group_wait: 1m
  routes:
  - receiver: "opsgenie"
receivers:
- name: "null"
- name: "opsgenie"
  opsgenie_configs: 
    - priority: P1
      api_key_file: '/etc/alertmanager/secrets/opsgenie_api_key/opsgenie_api_key'
      api_url: 'https://api.eu.opsgenie.com/'
```

* Prometheus Operator Logs:
```
level=error ts=2022-04-27T14:37:39.720133122Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"ame/infrastructure-monitoring-alertmanager\" failed: provision alertmanager configuration: failed to initialize from secret: yaml: unmarshal errors:\n  line 8: field api_key_file not found in type config.plain"
```

**Anything else we need to know?**:
This was supposedly [fixed in 0.56.0](https://github.com/prometheus-operator/prometheus-operator/blob/main/CHANGELOG.md#0560--2022-04-20)

PRs as listed in CHANGELOG:
https://github.com/prometheus-operator/prometheus-operator/pull/4666
https://github.com/prometheus-operator/prometheus-operator/pull/4738

Setting opsgenie_api_key_file in the global settings section results in the same error.
