### ISSUE TITLE
podmonitor config  not working

### ISSUE THREAD

**Issue by SABERYJS** [prometheus-operator/prometheus-operator#4778]
there is something strange when i  use  podmonitor  crd，its not working
i write podmonitor yaml:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: demo-pod-monitor
  namespace: prometheus
  labels:
    team: joyours
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
      - ingress-nginx
  podMetricsEndpoints:
    - port: "10254"
```
i want  prometheus  get metrics from nginx ingress pod ,but i see nothing 
prometheus installed in  `prometheus ` namespace:
```
[root@k8snode k8sprometheus]# pods -n  prometheus 
NAME                                                     READY   STATUS    RESTARTS   AGE
alertmanager-k8sprometheus-kube-prometh-alertmanager-0   2/2     Running   0          16h
k8sprometheus-grafana-86b86679b6-mbnsf                   3/3     Running   0          16h
k8sprometheus-kube-prometh-operator-584c77554d-t5qmt     1/1     Running   0          16h
k8sprometheus-kube-state-metrics-867c6487-rrrl2          1/1     Running   0          16h
k8sprometheus-prometheus-node-exporter-2cwkd             1/1     Running   0          16h
prometheus-k8sprometheus-kube-prometh-prometheus-0       2/2     Running   0          16h

```
i can  access  nginx ingress directly,`curl  http://127.0.0.1:10254/metrics`,result:
```
simplethai.hk.petaplay.com",ingress="web",method="POST",namespace="default",path="/",service="web",status="503",le="0.25"} 0
nginx_ingress_controller_response_size_bucket{canary="",controller_class="k8s.io/ingress-nginx",controller_namespace="ingress-nginx",controller_pod="ingress-nginx-controller-tvjcs",host="web.simplethai.hk.petaplay.com",ingress="web",method="POST",namespace="default",path="/",service="web",status="503",le="0.5"} 0
nginx_ingress_controller_response_size_bucket{canary="",controller_class="k8s.io/ingress-nginx",controller_namespace="ingress-nginx",controller_pod="ingress-nginx-controller-tvjcs",host="web.simplethai.hk.petaplay.com",ingress="web",method="POST",namespace="default",path="/",service="web",status="503",le="1"} 0
nginx_ingress_controller_response_size_bucket{canary="",controller_class="k8s.io/ingress-nginx",controller_namespace="ingress-nginx",controller_pod="ingress-nginx-controller-tvjcs",host="web.simplethai.hk.petaplay.com",ingress="web",method="POST",namespace="default",path="/",service="web",status="503",le="2.5"} 0
nginx_ingress_controller_response_size_bucket{canary="",controller_class="k8s.io/ingress-nginx",controller_namespace="ingress-nginx",controller_pod="ingress-nginx-controller-tvjcs",host="web.simplethai.hk.petaplay.com",ingress="web",method="POST",namespace="default",path="/",service="web",status="503",le="5"} 0
nginx_ingress_controller_response_size_bucket{canary="",controller_class="k8s.io/ingress-nginx",controller_namespace="ingress-nginx",controller_pod="ingress-nginx-controller-tvjcs",host="web.simplethai.hk.petaplay.com",ingress="web",method="POST",namespace="default",path="/",service="web",status="503",le="10"} 0
nginx_ingress_controller_response_size_bucket{canary="",controller_class="k8s.io/ingress-nginx",controller_namespace="ingress-nginx",controller_pod="ingress-nginx-controller-tvjcs",host="web.simplethai.hk.petaplay.com",ingress="web",method="POST",namespace="default",path="/",service="web",status="503",le="+Inf"} 5
nginx_ingress_controller_response_size_sum{canary="",controller_class="k8s.io/ingress-nginx",controller_namespace="ingress-nginx",controller_pod="ingress-nginx-controller-tvjcs",host="web.simplethai.hk.petaplay.com",ingress="web",method="POST",namespace="default",path="/",service="web",status="503"} 1719
nginx_ingress_controller_response_size_count{canary="",controller_class="k8s.io/ingress-nginx",controller_namespace="ingress-nginx",controller_pod="ingress-nginx-controller-tvjcs",host="web.simplethai.hk.petaplay.com",ingress="web",method="POST",namespace="default",path="/",service="web",status="503"}
```
when i  browse  grafana metrics related to  nginx,there is nothing
![image](https://user-images.githubusercontent.com/12248909/167541247-f741bccd-0c28-40c8-bc0f-db674de0acfe.png)

nginx pod manfest:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.6
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 1.0.4
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  annotations:
     prometheus.io/scrape: "true"
     prometheus.io/port: "10254"
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/component: controller
  revisionHistoryLimit: 10
  minReadySeconds: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/instance: ingress-nginx
        app.kubernetes.io/component: controller
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: controller
          image: k8s.gcr.io/ingress-nginx/controller:v1.0.4
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /wait-shutdown
          args:
            - /nginx-ingress-controller
            - --publish-service=$(POD_NAMESPACE)/ingress-nginx-controller

```
nginx pod:
```
[root@k8snode deploy-scripts]# pods -n ingress-nginx
NAME                                      READY   STATUS      RESTARTS   AGE
ingress-nginx-controller-tvjcs            1/1     Running     0          19d
```
so i checked  operator log:
```
level=info ts=2022-05-10T05:00:47.868427827Z caller=operator.go:1479 component=prometheusoperator key=prometheus/k8sprometheus-kube-prometh-prometheus msg="update prometheus status"
level=error ts=2022-05-10T05:00:47.876560341Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"prometheus/k8sprometheus-kube-prometh-prometheus\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"k8sprometheus-kube-prometh-prometheus\" not found"
```
```
[root@k8snode config-self]# kubectl get     prometheuses.monitoring.coreos.com  -A
NAMESPACE    NAME                                    VERSION   REPLICAS   AGE
prometheus   k8sprometheus-kube-prometh-prometheus   v2.35.0   1          19h
```
