### ISSUE TITLE
Shards aware TopologySpreadConstraint for Prometheus

### ISSUE THREAD

**Issue by sbeginCoveo** [prometheus-operator/prometheus-operator#4782]
**What is missing?**

The ability to define TopologySpreadConstraint using the label `operator.prometheus.io/shard` when sharding prometheus

**Why do we need it?**

Right now we can only define a single TSC or anti-affinity for _all_ statefulsets. 

* Prometheus Operator version:

`prometheus-operator/prometheus-operator:v0.53.1`

**Anything else we need to know?**:

With some guidance, I could make this happen. We would need to define the implementation details first. For now I think we would need to update all these components:
- the [Operator's statefulset generation](https://github.com/prometheus-operator/prometheus-operator/blob/9456e316035eadd0e8a472df4eee50787798a803/pkg/prometheus/statefulset.go#L1001) 
- the [prometheus crd](https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml#L6578)
- the [helm chart in which its deployed](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L251)

**Comment by sbeginCoveo** [comment]
I'm thinking of something along these lines, to the best of my knowledge:

**User definition**
The user defines a set of "managed TSC" config and custom ones, such as:
```yaml
shardsAwareTSC:
- maxSkew: 2
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: DoNotSchedule
- maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule

additionnalTSC:
- labelSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: ScheduleAnyway
```

**Generation**
And then each STS has its own set ot TSCs generated based on common prometheus labels, plus the additional TSCs are merged in the array. 

We could even keep the `additionnalTSC` named `topologySpreadConstraints` in the prometheus CRD to avoid creating a breaking change

_Shard 1 STS_
```yaml
topologySpreadConstraints:
- labelSelector:
    matchLabels:
      operator.prometheus.io/name: prometheus
      operator.prometheus.io/shard: "1"
  maxSkew: 2
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: DoNotSchedule
- labelSelector:
    matchLabels:
      operator.prometheus.io/name: prometheus
      operator.prometheus.io/shard: "1"
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule
- labelSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: ScheduleAnyway
```

_Shard 2 STS_
```yaml
topologySpreadConstraints:
- labelSelector:
    matchLabels:
      operator.prometheus.io/name: prometheus
      operator.prometheus.io/shard: "2"
  maxSkew: 2
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: DoNotSchedule
- labelSelector:
    matchLabels:
      operator.prometheus.io/name: prometheus
      operator.prometheus.io/shard: "2"
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule
- labelSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: ScheduleAnyway
```

**Comment by simonpasquier** [comment]
Thanks for the request! I'm not very familiar with TopologySpreadConstraints but this seems useful. From what I understand, you would almost want to select pods on either `operator.prometheus.io/name: <prometheus>` + `operator.prometheus.io/shard: <shard>` or `operator.prometheus.io/name: <prometheus>`.

Maybe we could extend the `spec.topologySpreadConstraints` field so you don't have to think too much about the labels?

```yaml
topologySpreadConstraints:
- maxSkew: 2
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: DoNotSchedule
  additionalLabelSelectors:  # can be "Name" or "Shard" but "Shard" would be a no-op for Alertmanager and ThanosRuler
  - Name
  - Shard
- maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule
  additionalLabelSelectors:
  - Name
  - Shard
- maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: ScheduleAnyway
  additionalLabelSelectors:
  - Name
```

The operator would automatically inject the required labels in the generated `topologySpreadConstraints[].labelSelector`. I'm not sure about the naming but this might make the API simpler?
