### ISSUE TITLE
regex (.*) not working in service monitor configuration

### ISSUE THREAD

**Issue by divyak8** [prometheus-operator/prometheus-operator#4795]
```
    metricRelabelings: 
   - sourceLabels:
      -  __meta_kubernetes_namespace
      targetLabel: namespace
    - action: drop
      sourceLabels:
      - __meta_kubernetes_namespace
      regex: (.*)
````
