### ISSUE TITLE
Router monitoring not showing up in Prometheus

### ISSUE THREAD

**Issue by BakermanLP** [prometheus-operator/prometheus-operator#4800]
**What did you do?**
I want to monitor my router with a pod. The pod is a webserver and listening on port 9042

This is my deployment of the pod and a service:

```
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: fritzbox-metrics
  labels:
    app: fritzbox-metrics
spec:
  selector:
    app: fritzboxexporter
  ports:
  - name: fritzweb
    port: 9042
    targetPort: 9042
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: fritzboxexporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "9042"
spec:
  selector:
    matchLabels:
      app: fritzboxexporter
  replicas: 1
  template:
    metadata:
      labels:
        app: fritzboxexporter
    spec:
      containers:
      - name: fritzboxexporter
        image: kehrhardt/fritzbox_exporter
        ports:
        - containerPort: 9042
        env:
        - name: USERNAME
          value: "MYUSERNAME"
        - name: PASSWORD
          value: "MYPASSWORD"
        - name: GATEWAY_URL
          value: "http://192.168.1.1:49000"
```

If I curl the webserver inside my cluster, than I got the correct answer:
```
curl -s http://10.43.105.249:9042/metrics
# HELP fritzbox_exporter_collectErrors Number of collection errors.
# TYPE fritzbox_exporter_collectErrors counter
fritzbox_exporter_collectErrors 0
# HELP fritzbox_exporter_luaCollectErrors Number of lua collection errors.
# TYPE fritzbox_exporter_luaCollectErrors counter
fritzbox_exporter_luaCollectErrors 0
# HELP fritzbox_exporter_results_cached Number of results taken from cache.
# TYPE fritzbox_exporter_results_cached counter
fritzbox_exporter_results_cached{Cache="LUA"} 6
fritzbox_exporter_results_cached{Cache="UPNP"} 136
...
```

But it didn't seem to be recognized by prometheus. I don't see a target or service discovery inside prometheus.

Is there anything wrong with my deployment. Informations found via google haven't helped me.

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:
Image:      carlosedp/prometheus-operator:v0.40.0
Version | 2.19.1
eba3fdcbf0d378b66600281903e3aab515732b39

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"archive", BuildDate:"2022-04-29T06:39:16Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:58Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"}

* Kubernetes cluster kind:

Cluster created via k3s-ansible

* Manifests:

* Prometheus Operator Logs:

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
Did you create any pod or service monitor?

**Comment by BakermanLP** [comment]
OK, here is a working copy. This is solved with a service monitor, a service and a pod.  Sorry for the issue, but this topic is new to me and not easy. But now it is working.

```
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: fritzbox-metrics
  labels:
    app: fritzbox-metrics
spec:
  selector:
    app: fritzboxexporter
  ports:
  - name: metrics
    port: 9100
    targetPort: 9042
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: fritzboxexporter
  name: fritzboxexporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: fritzbox-metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: fritzboxexporter
spec:
  selector:
    matchLabels:
      app: fritzboxexporter
  replicas: 1
  template:
    metadata:
      labels:
        app: fritzboxexporter
    spec:
      containers:
      - name: fritzboxexporter
        image: kehrhardt/fritzbox_exporter
        ports:
        - containerPort: 9042
        env:
        - name: USERNAME
          value: "MySecretUsername"
        - name: PASSWORD
          value: "MySecretPassword"
        - name: GATEWAY_URL
          value: "http://192.168.1.1:49000"
```
