### ISSUE TITLE
Can't Access Prometheus,Grafana UI in NodePort way

### ISSUE THREAD

**Issue by oneslideicywater** [prometheus-operator/prometheus-operator#4801]
## version
download zip lastest of this repo

## description

can't access pods such as `promtheus-k8s-0` in `monitoring` namespace by creating a custom pod in the same namespace, I can't either  expose those service `prometheus-k8s` in NodePort.

```bash
[root@localhost ingress]# kubectl exec -it prometheus-k8s-0 -n monitoring -- /bin/sh
/prometheus $ wget grafana:3000
Connecting to grafana:3000 (10.97.45.181:3000)
saving to 'index.html'
```
but using a custom pod `nginx` can't access grafana pods

```bash
[root@localhost ingress]# kubectl exec -it nginx -n monitoring -- /bin/bash
root@nginx:/# curl http://10.97.45.181:3000
curl: (28) Failed to connect to 10.97.45.181 port 3000: Connection timed out
```

edit the promtheus svc by expose the nodeport, but my brower can't access UI
```yaml
# ref by step 3
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.35.0
  name: prometheus-k8s-nodeport
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    port: 9090
    targetPort: web
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus

```

## how to reproduce 

1. download main branch zip of this repo
2. follow the quick start but not port forward the service
3. add a promtheus svc yaml above
4. access the prometheus UI in the browser
