### ISSUE TITLE
Prometheus jobs generated by PodMonitors do not exclude non-running pods

### ISSUE THREAD

**Issue by jutley** [prometheus-operator/prometheus-operator#4816]
**What happened?**

When using PodMonitors, it appears that the generated Prometheus jobs do not filter out non-running pods.

In some cases, this can have really ugly consequences. In our case, we had a handful of succeeded/failed pods which all had the same pod IP. Since they were completed, the IP was available to assigning, and it happened to get assigned to kube-state-metrics. This meant that we had many non-running pods that Prometheus was trying to scrape, and based on the target IP and port (which happened to match kube-state-metrics), we ended up 5 active scrapes of kube-state-metrics. This caused the Prometheus to crash because kube-state-metrics returned _way_ more data than the intended target.

**Did you expect to see something different?**

I expected to see that non-running pods were intentionally removed in the job relabellings. This can be done by filtering based on the `__meta_kubernetes_pod_phase` label.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a CronJob that runs every minute which does basically nothing. Make sure it keeps around a few succeeded jobs.
2. Create a PodMonitor that targets the CronJob's pods.
3. Check the Prometheus targets page. You'll see that the completed pods are failing to be scraped.

**Environment**

* Prometheus Operator version:

v0.47.1. It's fairly old, but I couldn't find any evidence in the changelog or source code that this behavior has been updated in newer versions.

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12", GitCommit:"696a9fdd2a58340e61e0d815c5769d266fca0802", GitTreeState:"clean", BuildDate:"2022-04-13T19:01:10Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

Our own deployment (not using standard tools) onto AWS.

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    prometheus: apps
  name: commissioner
  namespace: commissioner
spec:
  podMetricsEndpoints:
  - port: commissioner
  selector:
    matchLabels:
      component: worker
```

**Comment by simonpasquier** [comment]
Thanks for the detailed report! The actual behavior is expected because you may want to be alerted when a pod isn't running. 
As you noticed, it can be tweaked with target relabeling:

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    prometheus: apps
  name: commissioner
  namespace: commissioner
spec:
  podMetricsEndpoints:
  - port: commissioner
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_phase]
      action: keep
      regex: Running
  selector:
    matchLabels:
      component: worker
  
```

Modifying the current behavior would be a breaking change so we can't do that. But I agree that it could be less cumbersome. Maybe something like this? 

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    prometheus: apps
  name: commissioner
  namespace: commissioner
spec:
  podMetricsEndpoints:
  - port: commissioner
    # keep only pods which are running
    # if the list is empty or the field undefined, keep all pods.
    phases: [Running]
  selector:
    matchLabels:
      component: worker
```
