### ISSUE TITLE
AlertmanagerConfig fails to unmarshal matchers

### ISSUE THREAD

**Issue by jimethn** [prometheus-operator/prometheus-operator#4822]
**What happened?**

When I use the deprecated matchers syntax 

```
    - matchers:
      - name: foo
        value: bar
      receiver: catch-all
```

it works fine, but the operator gives a warning that I'm using a deprecated syntax:

```
level=warn ts=2022-05-26T19:58:12.569942922Z caller=amcfg.go:1486 component=alertmanageroperator alertmanager=prometheus-operator-alertmanager namespace=prometheus-operator receiver=prometheus-operator/alertmanager-config/catch-all msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="unsupported value type" match_re="unsupported value type"
```

But then when I update to the [current syntax](https://prometheus.io/docs/alerting/latest/configuration/#matcher)

```
    - matchers:
      - foo = bar
      receiver: catch-all
```

then the operator pod crashes with an error

```
panic: route[0]: json: cannot unmarshal string into Go struct field Route.matchers of type v1alpha1.Matcher
```

**Did you expect to see something different?**

I expect the current matchers syntax to work.

**How to reproduce it (as minimally and precisely as possible)**:

Define an AlertmanagerConfig with the current matchers syntax (see full manifest example below).

**Environment**

* Prometheus Operator version:

    `version="(version=0.55.0, branch=refs/tags/v0.55.0, revision=fd0fe0aed99a6a178197f302c06982ad7473a900)"`
    
    

* Kubernetes version information:

    `Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-eks-0d102a7", GitCommit:"eb09fc479c1b2bfcc35c47416efb36f1b9052d58", GitTreeState:"clean", BuildDate:"2022-02-17T16:36:28Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

    EKS 1.21

* Manifests:

    Here is a minimal reproducing config:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    app.kubernetes.io/instance: prometheus-operator
  name: alertmanager-config
  namespace: prometheus-operator
spec:
  receivers:
  - name: catch-all
  route:
    receiver: catch-all
    routes:
    - matchers:
      - foo = bar
      receiver: catch-all
```

* Prometheus Operator Logs:

```
level=info ts=2022-05-26T20:01:00.840040699Z caller=operator.go:280 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2022-05-26T20:01:00.840078789Z caller=operator.go:1228 component=prometheusoperator key=prometheus-operator/prometheus-operator-prometheus msg="sync prometheus"
level=info ts=2022-05-26T20:01:00.840340823Z caller=operator.go:741 component=alertmanageroperator key=prometheus-operator/prometheus-operator-alertmanager msg="sync alertmanager"
level=info ts=2022-05-26T20:01:00.847668247Z caller=operator.go:888 component=alertmanageroperator alertmanager=prometheus-operator-alertmanager namespace=prometheus-operator msg="key not found in base config secret" secret=alertmanager-prometheus-operator-alertmanager key=alertmanager.yaml
panic: route[0]: json: cannot unmarshal string into Go struct field Route.matchers of type v1alpha1.Matcher

goroutine 142 [running]:
github.com/prometheus-operator/prometheus-operator/pkg/alertmanager.(*configGenerator).convertRoute(0xc00412e060, 0xc0038ea160, {{0xc0016da1e0, 0x0}, {0xc0016da198, 0x0}})
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/alertmanager/amcfg.go:364 +0x9d6
github.com/prometheus-operator/prometheus-operator/pkg/alertmanager.(*configGenerator).generateGlobalConfig(0xc00412e568, {0x2138fd0, 0xc000296940}, 0xc001ba3e00)
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/alertmanager/amcfg.go:156 +0xcc
github.com/prometheus-operator/prometheus-operator/pkg/alertmanager.(*Operator).provisionAlertmanagerConfiguration(0xc000818000, {0x2138fd0, 0xc000296940}, 0xc002f5e000, 0xc002f580c0)
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/alertmanager/operator.go:931 +0xa29
github.com/prometheus-operator/prometheus-operator/pkg/alertmanager.(*Operator).sync(0xc000818000, {0x2138fd0, 0xc000296940}, {0xc002f5c000, 0x34})
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/alertmanager/operator.go:745 +0x655
github.com/prometheus-operator/prometheus-operator/pkg/alertmanager.(*Operator).processNextWorkItem(0xc000818000, {0x2138fd0, 0xc000296940})
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/alertmanager/operator.go:539 +0x132
github.com/prometheus-operator/prometheus-operator/pkg/alertmanager.(*Operator).worker(0x8de4aa, {0x2138fd0, 0xc000296940})
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/alertmanager/operator.go:527 +0x39
created by github.com/prometheus-operator/prometheus-operator/pkg/alertmanager.(*Operator).Run
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/alertmanager/operator.go:462 +0x305```

**Anything else we need to know?**:

**Comment by jimethn** [comment]
The problem is on my end, I was looking at the alertmanager docs instead of the alertmanagerConfig CRD spec https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#matcher

**Comment by BeyondEvil** [comment]
> The problem is on my end, I was looking at the alertmanager docs instead of the alertmanagerConfig CRD spec https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#matcher

Might sharing exactly how you solved this @jimethn ?

I have the same issue, but I don't understand how I tie the CRD matchers object to a receiver.

**Comment by jimethn** [comment]
In my case, my problem was I was using the Alertmanager syntax instead of the AlertmanagerConfig syntax. I was trying

```
    routes:
    - matchers:
      - foo = bar
      receiver: catch-all
```

which is the Alertmanager syntax, as opposed to

```
    routes:
    - matchers:
      - name: foo
        value: bar
      receiver: catch-all
```

which is the AlertmanagerConfig syntax required by prometheus-operator.

@BeyondEvil Your problem is different, you aren't using _any_ recognized syntax. 😉 You have

```
    routes:
    - matchType: =
      name: alertname
      value: Watchdog
```

but it should be

```
    routes:
    - matchers:
      - matchType: =
        name: alertname
        value: Watchdog
      receiver: asdf
```

`routes` is a list of maps, and each map needs to define `matchers` and `receiver` keys. `matchers` is also a list of maps, which needs to define `name` and `value` keys. You're putting the map that is supposed to go inside `matchers` directly into `routes` instead. Hope that made sense.

**Comment by BeyondEvil** [comment]
Yes, thank you @jimethn 🙏

**Comment by toan-hf** [comment]
@jimethn  but in the end if you follow the AlertManagerConfig syntax like you explained above, have you still seen that error?
I also used the same syntax like AlertMangerConfig but got that warning like you mentioned as always 

```
msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="unsupported value type" match_re="unsupported value type"
```

```
route:
    groupBy:
    - alertname
    - host
    - cluster
    - service
    groupInterval: 5m
    groupWait: 30s
    receiver: slack-alerts-default
    repeatInterval: 12h
    routes:
    - continue: false
      matchers:
      - name: source_namespace
        value: analytics
      receiver: slack-alerts-analytics
    - continue: true
      matchers:
      - name: slack_channel
        regex: true
        value: ^[@#a-z0-9][a-z0-9._-]*$
      receiver: slack-team-receiver
    - continue: true
      matchers:
      - name: severity
        value: warning
      receiver: slack-alerts-warning
```

**Comment by jimethn** [comment]
@toan-hf that is just a warning, not an error, and it is a red-herring.

> **level=warn** ts=2022-05-26T19:58:12.569942922Z caller=amcfg.go:1486 component=alertmanageroperator alertmanager=prometheus-operator-alertmanager namespace=prometheus-operator receiver=prometheus-operator/alertmanager-config/catch-all msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="unsupported value type" match_re="unsupported value type"

(emphasis mine)

Under the hood, the operator converts the CRD into a valid alertmanager config. The config syntax the operator is outputting to is deprecated, but it's still valid.

![image](https://user-images.githubusercontent.com/89885/198738517-0a824f67-7099-43ab-bcb6-c17c166f1e7f.png)

I'm sure the good folks here at prometheus-operator will update the conversion before it becomes invalid. For now you should not worry about it.

**Comment by PickledChris** [comment]
As it wasn't clear to me from the above, I had correct but old syntax:

```
    routes:
    - matchers:
      - name: foo
        value: bar
      receiver: catch-all

```
And I just needed to specify `matchType`

```
    routes:
    - matchers:
      - name: foo
        value: bar
        matchType: =

      receiver: catch-all

```
I didn't have any parsing errors, so I thought the above was irrelevant, hopefully this is helpful to someone.
