### ISSUE TITLE
failed to update status subresource: prometheuses.monitoring.coreos.com \"instance\" not found"

### ISSUE THREAD

**Issue by ctml91** [prometheus-operator/prometheus-operator#4823]
Status subresource looks like it was updated in some of the logs and status is visible from Prometheus CR, but then after there are recurring messages every ~15 minutes about the Prometheus instance not found despite it being there.

Prometheus-operator: v0.56.2

```
level=info ts=2022-05-26T18:08:32.852268101Z caller=operator.go:1322 component=prometheusoperator key=test/instance msg="sync prometheus"
level=info ts=2022-05-26T18:08:33.331451359Z caller=operator.go:1479 component=prometheusoperator key=test/instance msg="update prometheus status"
level=info ts=2022-05-26T18:08:33.352197297Z caller=operator.go:1322 component=prometheusoperator key=test/instance msg="sync prometheus"
level=info ts=2022-05-26T18:08:33.823138688Z caller=operator.go:1479 component=prometheusoperator key=test/instance msg="update prometheus status"
level=info ts=2022-05-26T18:08:33.827156075Z caller=operator.go:1322 component=prometheusoperator key=test/instance msg="sync prometheus"
level=info ts=2022-05-26T18:08:34.360292939Z caller=operator.go:1479 component=prometheusoperator key=test/instance msg="update prometheus status"
level=info ts=2022-05-26T18:09:05.485425724Z caller=operator.go:1322 component=prometheusoperator key=test/instance msg="sync prometheus"
level=info ts=2022-05-26T18:09:06.074394731Z caller=operator.go:1479 component=prometheusoperator key=test/instance msg="update prometheus status"
level=error ts=2022-05-26T18:09:06.084629488Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"test/instance\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"instance\" not found"
level=info ts=2022-05-26T18:09:06.089909524Z caller=operator.go:1479 component=prometheusoperator key=test/instance msg="update prometheus status"
level=error ts=2022-05-26T18:09:06.099349331Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"test/instance\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"instance\" not found"
level=info ts=2022-05-26T18:09:06.109623377Z caller=operator.go:1479 component=prometheusoperator key=test/instance msg="update prometheus status"
level=error ts=2022-05-26T18:09:06.125298623Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"test/instance\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"instance\" not found"
level=info ts=2022-05-26T18:09:06.145555811Z caller=operator.go:1479 component=prometheusoperator key=test/instance msg="update prometheus status"
level=error ts=2022-05-26T18:09:06.154735087Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"test/instance\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"instance\" not found"
```

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: instance
  namespace: test
spec:
  evaluationInterval: 30s
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
      - key: k8s-app
        operator: Exists
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 256Mi
  alerting:
    alertmanagers:
      - name: alertmanager-operated
        namespace: test
        port: web
  securityContext: {}
  containers:
    - name: config-reloader
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
  scrapeInterval: 30s
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 1Gi
        storageClassName: ocs-storagecluster-ceph-rbd
  replicas: 2
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: prometheus-rulefiles
  retention: 15d
status:
  availableReplicas: 0
  paused: false
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
```
