### ISSUE TITLE
field telegram_configs not found in type alertmanager.receiver

### ISSUE THREAD

**Issue by dalidovichea** [prometheus-operator/prometheus-operator#4826]
hi, got error on 0.56.3 version
failed: provision alertmanager configuration: failed to initialize from secret: yaml: unmarshal errors:\n  line 6: field telegram_configs not found in type alertmanager.receiver

```
global:
  resolve_timeout: 5m
receivers:
- name: "null"
- name: telegram
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: xxxxxxx
    chat_id: xxxxxxx
    parse_mode: ""
    send_resolved: true
route:
  group_by:
  - job
  - alertname
  - cluster
  - service
  group_interval: 5m
  group_wait: 30s
  receiver: "null"
  repeat_interval: 4h
  routes:
  - matchers:
    - alertname =~ "InfoInhibitor|Watchdog"
    receiver: "null"
templates:
- /etc/alertmanager/config/*.tmpl
```

in 0.56.3 version this issue [4703](https://github.com/prometheus-operator/prometheus-operator/issues/4703) is fixed but
got new
Please add telegram_configs in type alertmanager.receiver
