### ISSUE TITLE
How to modify kubelet's rules?

### ISSUE THREAD

**Issue by wajika** [prometheus-operator/prometheus-operator#4841]
```
- job_name: kubelet
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
  scrape_interval: 45s
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    replacement: kubernetes.default.svc:443
  - source_labels:
      - __meta_kubernetes_node_name
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/${1}/proxy/metrics
  - source_labels:
      - __meta_kubernetes_node_name
    action: replace
    target_label: kubernetes_io_hostname >>I need kubernetes_io_hostname label
```

I added additional configuration according to [Additional Scrape Configuration](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/additional-scrape-config.md), but no new label appeared in prometheus, what is the reason? My added rules are overridden by CRD?

[config endpoint information](https://gist.github.com/wajika/21098344fa0c5bde644fdbd59efe682c)
