### ISSUE TITLE
how to deploy prometheus-operator with an existing prometheus ?

### ISSUE THREAD

**Issue by X-Mars** [prometheus-operator/prometheus-operator#4843]
**What did you do?**
how to deploy prometheus-operator with an existing prometheus ?
**Did you expect to see some different?**
no
**Environment**
centos 7.9
* Prometheus Operator version:
0.57
* Kubernetes version information:
kubernete 1.16

* Kubernetes cluster kind:
kubeadm

* Manifests:
no

**Comment by simonpasquier** [comment]
Can you add more details? Do you have an existing statefulset that you want the operator to "adopt"?

**Comment by X-Mars** [comment]
I have a prometheus deploy by yaml and kind is Deployment.
I want to add ServiceMonitor  for it.
How to do can i?
Thank you .

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      serviceAccountName: prometheus
      securityContext:
        runAsUser: 0
      containers:
      - name: prometheus
        image: prom/prometheus:v2.36.0
        imagePullPolicy: IfNotPresent
        command:
          - prometheus
          - --config.file=/etc/prometheus/prometheus.yml
          - --storage.tsdb.path=/prometheus/prometheus-db
          - --storage.tsdb.retention=20d
          - --web.enable-lifecycle
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 6000m
            memory: 20Gi
        volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus-config
          subPath: prometheus.yml
        - mountPath: /prometheus/prometheus-db
          name: volume-prometheus-db
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml
                mode: 0644
        - name: volume-prometheus-db
          persistentVolumeClaim:
            claimName: prometheus-db
```
