### ISSUE TITLE
Prometheus  operator Support AWS ALB to using ingress

### ISSUE THREAD

**Issue by sangram23** [prometheus-operator/prometheus-operator#4845]
I have installed prometheus operator in my AWS EKS Cluster and trying to access using ingress . For Ingress Controller  using  AWS ALB.

1)- I have created Nodeport Service 
apiVersion: v1
kind: Service
metadata:
   name: prometheus-server-nodeport
   labels:
     app: prometheus
     component: server
     release: prometheus
spec:
  type: NodePort
  selector:
     app: prometheus
     component: server
     release: prometheus
  ports:
    - port: 80
      targetPort: 9090

2)- Created ingress resource 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-promethous
  labels:
    app: ingress-promethous
  annotations:
    #kubernetes.io/ingress.class: "alb" #(OLD INGRESS CLASS NOTATION - STILL WORKS BUT RECOMMENDED TO USE IngressClass Resource)
     #Ingress Core Settings
    #alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/scheme: internal
    #Health Check Settings
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /app1/index.html
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
spec:
  ingressClassName: my-aws-ingress-class # Ingress Class
  rules:
   - http:
       paths:
         - path: /app1
           pathType: Prefix
           backend:
             service:
               name: prometheus-server-nodeport
               port:
                 number: 80

Unable to get Promethous UI?

I prometheus support Ingress? or any Specific configuration need to do?

**Comment by simonpasquier** [comment]
It should be possible to expose Prometheus via ingress and I'm not aware of any issue with AWS. Maybe check https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizations/exposing-prometheus-alertmanager-grafana-ingress.md?

**Comment by AlexDaichendt** [comment]
I can confirm, that its possible to use an ALB. 

values.yaml for the helm chart:
```yaml
prometheus:
  enabled: true
  ingress:
    annotations:
      alb.ingress.kubernetes.io/certificate-arn: >-
        arn:aws:acm:eu-central-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      alb.ingress.kubernetes.io/group.name: prod-external
      alb.ingress.kubernetes.io/group.order: '10'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
    enabled: true
    hosts:
      - prometheus.abc.loc
    labels: {}
    paths:
      - /
    tls:
      - hosts:
          - prometheus.abc.loc
        secretName: cert
  service:
    annotations: {}
    clusterIP: ''
    externalIPs: []
    labels: {}
    loadBalancerIP: ''
    loadBalancerSourceRanges: []
    nodePort: 30090
    port: 9090
    sessionAffinity: ''
    targetPort: 8081
    type: NodePort
```
