### ISSUE TITLE
AlertmanagerConfig validation for opsgenie_config.responder.type does not allow template strings

### ISSUE THREAD

**Issue by dembaca** [prometheus-operator/prometheus-operator#4882]
**What happened?**

According to the [Alertmanager documentation](https://prometheus.io/docs/alerting/latest/configuration/#responder) a `<tmpl_string>` should be accepted as value for `opsgenie_config.responder.type`.

Prometheus Operator refuses to accept a template string (see log output below).

**Did you expect to see something different?**

I expect a `tmpl_string`, i.e. a string containing valid go-template code, to be accepted as value for field `responder.type`. 
This `tmpl_string` must evaluate to ^(team|teams|user|escalation|schedule)$ – but only _after_ template evaluation and not to be valid alertmanager configuration.

Currently this prevents to have it evaluated during alert routing and to dynamically assign responders type (just like name, id, username) according to alert label values.

**How to reproduce it (as minimally and precisely as possible)**:

Try to apply alertmanager config with a responder type as in the manifest snippet below (or any other template string).

```
responder:
  - type: '{{ .GroupLabels.opsgenie_responder_type }}'
```

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.56.3`
    
    

* Kubernetes version information:

    `v1.21.5`
    

* Kubernetes cluster kind:

    plain vanilla kubespray cluster

* Manifests:

kube-prometheus-stack helm [values](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml):

```
...
alertmanager:
  config:
    receivers:
      - name: opsgenie-responder-by-name
        opsgenie_configs:
          - responders:
              - type: '{{ .GroupLabels.opsgenie_responder_type }}'
                name: '{{ .GroupLabels.opsgenie_responder_name }}'
      - name: opsgenie-responder-by-id
        opsgenie_configs:
          - responders:
              - type: '{{ .GroupLabels.opsgenie_responder_type }}'
                id: '{{ .GroupLabels.opsgenie_responder_id }}'
...
```

* Prometheus Operator Logs:

```
level=info ts=2022-06-30T13:26:09.590839794Z caller=operator.go:748 component=alertmanageroperator key=managed-prometheus-apps-dev/apps-dev-alertmanager msg="sync alertmanager"
level=error ts=2022-06-30T13:26:09.595331568Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"managed-prometheus-apps-dev/apps-dev-alertmanager\" failed: provision alertmanager configuration: failed to initialize from secret: OpsGenieConfig responder { {{ .GroupLabels.opsgenie_responder_name }}  {{ .grouplabels.opsgenie_responder_type }}} type does not match valid options ^(team|teams|user|escalation|schedule)$"
```

**Anything else we need to know?**:

Problematic validation on string enum was probably introduced here:
https://github.com/prometheus-operator/prometheus-operator/commit/d8454e4e8677d2e67cfa61b266e6cdf583f7f94a
