### ISSUE TITLE
AlertmanagerEndpoints doesn't contain basicAuth field

### ISSUE THREAD

**Issue by zqzzq** [prometheus-operator/prometheus-operator#4892]
how can i config alertmanager's basic_auth in prometheus config like:
```
    alerting:
      alertmanagers:
      - basic_auth:
          username: admin
          password: admin
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - default
        relabel_configs:
        - action: keep
          source_labels:
          - __meta_kubernetes_service_name
          regex: alertmanager
        - action: keep
          source_labels:
          - __meta_kubernetes_endpoint_port_name
          regex: http-metrics
```
the AlertmanagerEndpoints struct in Prometheus CRD only support "bearerTokenFile" and "authorization" field.
