### ISSUE TITLE
prometheus-operator:v0.56.3 loads non-versioned prometheus/prometheus:latest image

### ISSUE THREAD

**Issue by zoxpx** [prometheus-operator/prometheus-operator#4893]
**What happened?**

The `prometheus-operator:v0.56.3` (also `:v0.50.0`) pulls the wrong `prometheus` image:

When using spec with the following arguments:
```
...
    spec:
      containers:
        - args:
            - -namespaces=kube-system
            - --kubelet-service=kube-system/kubelet
            - --prometheus-config-reloader=10.13.1.68/prometheus-operator/prometheus-config-reloader:v0.56.3
            - --prometheus-default-base-image=10.13.1.68/prometheus/prometheus
            - --alertmanager-default-base-image=10.13.1.68/prometheus/alertmanager
            - --thanos-default-base-image=10.13.1.68/thanos/thanos
          image: 10.13.1.68/prometheus-operator/prometheus-operator:v0.56.3
          imagePullPolicy: Always  ...
```
.. the _actual_ images pulled by the `prometheus-operator` are the following:
```
# kubectl get pods -A -o yaml | grep image: | sort -u | grep prom
      image: 10.13.1.68/prometheus/alertmanager:v0.24.0
      image: 10.13.1.68/prometheus-operator/prometheus-config-reloader:v0.56.3
      image: 10.13.1.68/prometheus-operator/prometheus-operator:v0.56.3
      image: 10.13.1.68/prometheus/prometheus
      image: 10.13.1.68/prometheus/prometheus:latest
```

Notes:
* in our test, we used custom registry server 10.13.1.68, but the issue is easily reproducible even without these overrides (i.e. same issue even without `--{prometheus,alertmanager,thanos}-default-base-image` parameters)
* additionally, we also tested `prometheus-operator:v0.50.0`, and it also loads the non-versioned prometheus/prometheus:latest image

**How to reproduce it (as minimally and precisely as possible)**:

Should be easily reproducible on `prometheus-operator:v0.56.3` (also `:v0.50.0`)
* after deployment, check kubernetes runtime configurations for the _actual_ images via:
```
kubectl get pods -A -o yaml | grep image: | sort -u | grep prom
```

**Did you expect to see something different?**

According to https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/operator/defaults.go#L42, the image is supposed to be "calculated" as:

```
	DefaultPrometheusVersion = PrometheusCompatibilityMatrix[len(PrometheusCompatibilityMatrix)-1]
	DefaultPrometheusImage = DefaultPrometheusBaseImage + ":" + DefaultPrometheusVersion
	PrometheusCompatibilityMatrix = []string{
	...
		"v2.35.0",
		"v2.36.0",
	}
```

So, we expected to get the "versioned" `10.13.1.68/prometheus/prometheus:v2.36.0` image, rather than "non-versioned" `10.13.1.68/prometheus/prometheus:latest` image.

**Environment**

* Prometheus Operator version:

`prometheus-operator:v0.56.3` (also `:v0.50.0`)

```
$ kubectl -n kube-system describe deployment prometheus-operator
Name:                   prometheus-operator
Namespace:              kube-system
CreationTimestamp:      Thu, 07 Jul 2022 23:19:38 -0700
Labels:                 k8s-app=prometheus-operator
Annotations:            deployment.kubernetes.io/revision: 1
                        portworx.com/install-source: https://edge-install.portworx.com/?comp=prometheus-operator&kbver=1.24.1&reg=10.13.1.68
Selector:               k8s-app=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           k8s-app=prometheus-operator
  Service Account:  prometheus-operator
  Containers:
   prometheus-operator:
    Image:      10.13.1.68/prometheus-operator/prometheus-operator:v0.56.3
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      -namespaces=kube-system
      --kubelet-service=kube-system/kubelet
      --prometheus-config-reloader=10.13.1.68/prometheus-operator/prometheus-config-reloader:v0.56.3
      --prometheus-default-base-image=10.13.1.68/prometheus/prometheus
      --alertmanager-default-base-image=10.13.1.68/prometheus/alertmanager
      --thanos-default-base-image=10.13.1.68/thanos/thanos
    Limits:
      cpu:     200m
      memory:  100Mi
    Requests:
      cpu:        100m
      memory:     50Mi
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-fd85d77cf (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  59m   deployment-controller  Scaled up replica set prometheus-operator-fd85d77cf to 1
```

* Kubernetes version information:

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    K8s cluster installed via `kubeadm` on a Ubuntu-18.04 LTS VMs, using `containerd` container runtime.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

As a workaround, one can include the full image (including tag/version) as arguments to the prometheus-operator, e.g.

```
    spec:
      containers:
        - args:
            - --prometheus-default-base-image=10.13.1.68/prometheus/prometheus:v2.36.0
...
```
* this will result in prometheus-operator loading the precise image-version (prometheus:v2.36.0)
