### ISSUE TITLE
service monitor default relabel config adds additional labels. 

### ISSUE THREAD

**Issue by vsamidurai** [prometheus-operator/prometheus-operator#4894]
**What happened?**
Service monitor default relabel rules add additional labels in pod-level metrics. 

**Did you expect to see something different?**
expect to see original metrics from exporters without additional container label. ability to disable these rules would probably help. 

**How to reproduce it (as minimally and precisely as possible)**:
check any pod-level metrics from kube-state-metrics service monitor. 

Example
Metrics in prometheus 
```sh
kube_pod_status_ready{condition="false", container="kube-state-metrics", endpoint="http", instance="ip:8080", job="kube-state-metrics", namespace="test", pod="somepod", service="prometheus-stack-kube-state-metrics", uid="4711f8bc-1762-482a-9f62-a0c0874a66a0"}
--
```
metrics from kube-state
```sh
kube_pod_status_ready{namespace="test",pod="somepod",uid="4711f8bc-1762-482a-9f62-a0c0874a66a0",condition="unknown"} 
```
above example, default relabel adds container label with service monitor name. 
 
**Environment**
AWS 

* Prometheus Operator version:

* Kubernetes version information:
kubernetes 1.21.8

* Kubernetes cluster kind:
kops

**Anything else we need to know?**:
this relabel rule introduced in this PR https://github.com/prometheus-operator/prometheus-operator/pull/3315

**Comment by simonpasquier** [comment]
The way to remove the `container` label is to add a relabel config rule:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
spec:
spec:
  endpoints:
  - relabelings:
    - action: labeldrop
      regex: container
```

**Comment by vsamidurai** [comment]
yes, this drops from all the metrics. even metrics with the original container label.

**Comment by simonpasquier** [comment]
It's possible but a bit more involved than my initial answer indeed. I haven't tested but it should something like this:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
spec:
spec:
  endpoints:
  - metricRelabelings:
    # store the container label in a temporary label for all kube_pod_container* metrics
    - sourceLabels: [__name__,container]
      regex: "kube_pod_container.+;(.+)"
      targetLabel: __tmp_container
    # drop the original container label
    - action: labeldrop
      regex: container
    # restore it for kube_pod_container* metrics
    - sourceLabels: __tmp_container
      targetLabel: container
    # drop the temporary label
    - action: labeldrop
      regex: __tmp_container
```
