### ISSUE TITLE
Prometheus is only picking up a metrics deployment in service discovery but not as a target

### ISSUE THREAD

**Issue by PyDataBlog** [prometheus-operator/prometheus-operator#4896]
**What did you do?**
I installed `kube-prometheus-stack` via helm:

```bash
kubectl create namespace monitoring && \
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && \
helm repo update && \
helm install -n monitoring prometheus-stack prometheus-community/kube-prometheus-stack
```
![image](https://user-images.githubusercontent.com/29863388/178033176-2a04e4ab-899d-4ee7-9735-712588058e8f.png)

Then proceeded to deploy a fastapi application which has a metrics endpoint that Prometheus is supposed to scrape. `/metrics` endpoint works fine as seen below:

![image](https://user-images.githubusercontent.com/29863388/178030474-0c3d8b76-9a50-4b36-b414-9012548c7a9e.png)

**Did you expect to see some different?**
I expected both the target and service discovery to work but only service discovery appears to be working

**Environment**

* Prometheus Operator version:

    `2.36.1`
    
    

* Kubernetes version information:

    `Client Version: v1.24.2`
    

* Kubernetes cluster kind:

    `Minikube v1.25.2-1`

* Manifests:

Here are the manifests for the deployed application:

1. Namespace and deployment
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: code-detector-demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-detector
  namespace: code-detector-demo
  labels:
    release: prometheus-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-detector
      release: prometheus-stack
  template:
    metadata:
      labels:
        app: code-detector
        release: prometheus-stack
    spec:
      containers:
      - name: code-detector
        image: <MY-IMAGE:TAG>
        resources:
          limits:
            memory: 512Mi
            cpu: 1000m
        ports:
        - containerPort: 8000
```

2. Service
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    release: prometheus-stack
  name: code-detector-service
  namespace: code-detector-demo
spec:
  selector:
    app: code-detector
    release: prometheus-stack
  ports:
    - name: code-detector-port
      port: 8000
      targetPort: 8000
```

3. ServiceMonitor
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: code-detector-servicemonitor
  # same namespace that Prometheus is running in
  namespace: monitoring
  labels:
    app: code-detector
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: code-detector
      release: prometheus-stack
  endpoints:
    - path: /metrics
      port: code-detector-port
      interval: 15s
  namespaceSelector:
    matchNames:
    - code-detector-demo # namespace where the app is running
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
Here's the labels in service discovery:
![image](https://user-images.githubusercontent.com/29863388/178032152-f8384905-55db-4715-a84b-b53161af1eb7.png)

Targets pane don't show any picked up scraping job:
![image](https://user-images.githubusercontent.com/29863388/178033037-323525cf-b9ab-46ec-a388-9c15dc178192.png)

What could I be doing wrong?
