### ISSUE TITLE
metricRelabelings dropping fields in CR on save

### ISSUE THREAD

**Issue by R0peE** [prometheus-operator/prometheus-operator#4914]
**What did you do?**
I would like to replace the name of metrics scraped with ServiceMonitor, I have set up for that the following configuration:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: slt-monitoring-nodes
  namespace: mcs-monitoring
spec:
  endpoints:
    - metricRelabelings:
        - action: replace
          source_labels: [__name__]
          regex: kube_node_role
          replacement: 'slt_$1'
          target_label: __name__
        - action: replace
          source_labels: [__name__]
          regex: kube_node_status_condition
          replacement: 'slt_$1'
          target_label: __name__
      path: /federate
      interval: 60s
      scheme: https
      params:
        'match[]':
          - 'kube_node_role'
          - 'kube_node_status_condition'
      honorLabels: true
      scrapeTimeout: 50s
      targetPort: 9091
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  jobLabel: mcs-slt-monitoring-nodes
  namespaceSelector:
    matchNames:
      - mcs-monitoring
  selector:
    matchLabels:
      prometheus: k8s-central
```

After saving the CR the `source_labels: [__name__]` and `target_label: __name__` fields are missing, producing an erronous yaml for Prometheus.

What seems to be missing? Is it a syntax issue (as far as i see it should be not) or the `__name__` label is protected for some reason?
Is there any other method to scrape metrics with modified metric name to Prometheus?

**Environment**

* Prometheus Operator version:

v0.53.1

* Kubernetes version information:

Openshift 4.8.42

* Prometheus Operator Logs:

No specific logs

Any help is very much appreciated! :)
