### ISSUE TITLE
remote_write configuration block will be refreshed. 

### ISSUE THREAD

**Issue by CherryJia** [prometheus-operator/prometheus-operator#4918]
Hi Team, 
We are trying to send metrics to my grafana cloud instance. per doc https://grafana.com/docs/grafana-cloud/kubernetes-monitoring/prometheus/remote_write_operator/#step-2--modify-the-prometheus-manifest-configuration
I have appended the following remote_write configuration block to the CR manifest , but it will take effective for only a while , then got refreshed out after very soon. seems the operator reverted it . anyone can guide here how we can get this work ?

```
. . .
  remoteWrite:
  - url: "<Your Metrics instance remote_write endpoint>"
    basicAuth:
      username:
        name: kubepromsecret
        key: username
      password:
        name: kubepromsecret
        key: password
```
