### ISSUE TITLE
How can I autoscale Prometheus shards using HPA?

### ISSUE THREAD

**Issue by SHEELE41** [prometheus-operator/prometheus-operator#4946]
**What did you do?**
I already read #3130, #2590 and saw that Prometheus shards can be autoscaled via the HPA.
> If you need a solution quickly, you can already use additional relabeling rules on your ServiceMonitor via the `hashmod` action, and create multiple ServiceMonitors per "shard". Your use case makes a lot of sense, I'd like to think it through a little bit further, and arrive at a solution, that would allow us to eventually autoscale sharding based on the metric ingestion (I'm thinking a general purpose way, where a Prometheus object would become a `shard` and maybe a `ShardedPrometheus` object that orchestrates these, and can be autoscaled via the HPA). What I'm saying is, maybe the sharding decision should be configured in the Prometheus object ultimately instead of the ServiceMonitor (where it's already possible albeit a little manual today).

I want to increase only 'shards' value, not 'replicas' value, when overall cpu usage of Prometheus shards(pods) is increasing.
(Because I want each Prometheus object to scrape metric from targets mutual exclusively.)

```
kind: Prometheus
...
spec:
  # replicas is fixed
  replicas: 1
  # horizontal scaling by increasing shards
  shards: 3, 4, 5...
```

So, I used [kubernetes-sigs/metrics-server](https://github.com/kubernetes-sigs/metrics-server) for cpu usage based scaling, and wrote a HPA manifest file with 'Prometheus' CRD as the target.

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prometheus-autoscaler
  namespace: monitoring
spec:
  scaleTargetRef:
    apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    name: prometheus
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
```

However, this HPA could not get cpu usage of target, so the target CPU usage remained unknown.
```
$ kubectl get hpa prometheus-autoscaler
... TARGETS ...
... <unknown>/50% ...
```

I realized it stands to reason because 'Promethues' CRD not implements labelselector /scale subresource.
```
$ kubectl describe hpa prometheus-autoscaler
Events:
  Type     Reason                        Age                     From                       Message
  ----     ------                        ----                    ----                       -------
  Warning  FailedComputeMetricsReplicas  5m2s (x12 over 7m52s)   horizontal-pod-autoscaler  selector is required
  Warning  SelectorRequired              2m43s (x21 over 7m52s)  horizontal-pod-autoscaler  selector is required
```

In Prometheus-operator, StatefulSet is created per shard and I checked that each id of the shard is pre-written in each StatefulSet manifest by running kubectl edit.

(In my case... shards=3 & replicas=1)
```
NAME                                          READY   STATUS    RESTARTS   AGE
pod/prometheus-prometheus-0                   2/2     Running   0          3h28m
pod/prometheus-prometheus-shard-1-0           2/2     Running   0          3h28m
pod/prometheus-prometheus-shard-2-0           2/2     Running   0          3h28m

NAME                                             READY   AGE
statefulset.apps/prometheus-prometheus           1/1     3d3h
statefulset.apps/prometheus-prometheus-shard-1   1/1     6h12m
statefulset.apps/prometheus-prometheus-shard-2   1/1     6h12m

NAME                                          VERSION   REPLICAS   AGE
prometheus.monitoring.coreos.com/prometheus   v2.33.5   1          3d3h
```

So even if I write the HPA manifest file to target each StatefulSet, it won't work as I expected.

In conclusion,

1. How can I get entire cpu usage of Prometheus shards by kubernetes-sigs/metrics-server?
2. How can I autoscale Prometheus shards by increasing/decreasing only 'shards' value without touching 'replicas' value using HPA? (like increasing the number of StatefulSet)

FYI, I'm using Prometheus to record external server's metrics, not my kubernetes cluster's metrics. 

**Environment**

* Prometheus Operator version:

    `v0.58.0`

* Kubernetes version information:

    `v1.24`
