### ISSUE TITLE
Sharding - have I missed anything?

### ISSUE THREAD

**Issue by michalschott** [prometheus-operator/prometheus-operator#4958]
**What did you do?**

Trying to use sharding configuration, I have noticed that both shards are scrapping the same targets (which is everything in cluster).

**Did you expect to see some different?**

According to https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/shards-and-replicas.md I should not see the same target list on both shards?

**Environment**

* Prometheus Operator version:

`quay.io/prometheus-operator/prometheus-operator:v0.58.0`

* Kubernetes version information:

EKS 1.22

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 39.2.1
    chart: kube-prometheus-stack-39.2.1
    heritage: Helm
    release: prometheus
  name: prometheus-prometheus
  namespace: prometheus
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: prometheus-alertmanager
      namespace: prometheus
      pathPrefix: /
      port: http-web
  enableAdminAPI: false
  evaluationInterval: 30s
  externalLabels:
    foo: bar
  externalUrl: XXX
  image: quay.io/prometheus/prometheus:v2.37.0
  listenLocal: false
  logFormat: json
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector: {}
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  shards: 2
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: ebs-sc-preserve
  thanos:
    logFormat: json
    objectStorageConfig:
      key: config
      name: thanos-config
  version: v2.37.0
```

**Comment by michalschott** [comment]
Something to add:

```
➜   k -n prometheus get pod,svc,endpoints -o wide
NAME                                                 READY   STATUS    RESTARTS   AGE   IP              NODE                                          NOMINATED NODE   READINESS GATES
pod/prometheus-prometheus-prometheus-0               3/3     Running   0          38m   10.200.60.11    ip-10-200-60-245.eu-west-1.compute.internal   <none>           <none>
pod/prometheus-prometheus-prometheus-shard-1-0       3/3     Running   0          38m   10.200.60.74    ip-10-200-60-171.eu-west-1.compute.internal   <none>           <none>

NAME                                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE   SELECTOR

service/prometheus-prometheus                 ClusterIP   172.20.241.10   <none>        9090/TCP,10901/TCP           38m   app.kubernetes.io/name=prometheus,prometheus=prometheus-prometheus
service/prometheus-prometheus-0               ClusterIP   172.20.79.141   <none>        9090/TCP,10901/TCP           38m   app.kubernetes.io/name=prometheus,prometheus=prometheus-prometheus,statefulset.kubernetes.io/pod-name=prometheus-prometheus-prometheus-0

NAME                                            ENDPOINTS                                                              AGE
endpoints/prometheus-prometheus                 10.200.60.11:9090,10.200.60.74:9090,10.200.60.11:10901 + 1 more...     38m
endpoints/prometheus-prometheus-0               10.200.60.11:9090,10.200.60.11:10901                                   38m
```

Above are created obviously by helm. I'm exposing thanos-sidecars via ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "160"
    nginx.ingress.kubernetes.io/whitelist-source-range: 46.51.166.10/32
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: prometheus
  name: prometheus-kube-prometheus-thanos-gateway
  namespace: prometheus
spec:
  ingressClassName: nginx
  rules:
  - host: XXX
    http:
      paths:
      - backend:
          service:
            name: prometheus-prometheus
            port:
              number: 10901
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - XXX
    secretName: thanos-sidecar-tls
```

Noticed I've got flip-flopping data on graphs:

<img width="1425" alt="Zrzut ekranu 2022-08-8 o 14 16 39" src="https://user-images.githubusercontent.com/6672421/183415914-e50eaba1-38e2-40ce-a429-f5e69f05b0c2.png">
<img width="1432" alt="Zrzut ekranu 2022-08-8 o 14 16 31" src="https://user-images.githubusercontent.com/6672421/183415927-8d76b3cd-00a3-474f-8a2e-873aedf867fd.png">
