### ISSUE TITLE
In alertmanager.yaml secret, does match:{label:keyword} support more flexible usage?

### ISSUE THREAD

**Issue by leo-lao** [prometheus-operator/prometheus-operator#4963]
**What did you do?**
I want to set up global alertmanager configurations in the secret(mentioned in [doc](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/alerting.md#manually-managed-secret))
and alertmanager.yaml in the secret looks like this:
```
global:
  resolve_timeout: 5m
receivers:
- name: "null"
- name: etl-global-alert
  webhook_configs:
  - send_resolved: false
    url: 'https://abc.abc.com/abc/alert/trigger/global_etl/cluster/sjc'    
route:
  group_by:
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: "null"
  repeat_interval: 12h
  routes:  
  - match:
      job: kube-state-metrics
      alertname: “.*Job.*“
    receiver: "etl-global-alert"
    group_interval: 5m
    group_wait: 1m
    repeat_interval: 5m   
    group_by: ['...']
    continue: true        
  - match:
      alertname: Watchdog
    receiver: "null"    
templates:
- /etc/alertmanager/config/*.tmpl
```
I am confused with how to correctly filtrate alerts, I used such matchers:
```
  - match:
      job: kube-state-metrics
      alertname: “.*Job.*“
```
But it did not work, nothing come out of this route.
I seached [alertmanager configuration doc](https://prometheus.io/docs/alerting/0.22/configuration/#matcher), 
and I tried using `~	`, `!` and regex expressions, none of those seems work.

So I want to know, does match here in this ` alertmanager.yaml` only support equal filtrate?

if I want to perform careful filtrations, and make this alertconfig global, what should I do?

**Environment**
My prometheus operator is installed using rancher, 
repo is here https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-monitoring/100.1.2%2Bup19.0.3

image: rancher/mirrored-prometheus-alertmanager:v0.22.2
image: rancher/mirrored-prometheus-operator-prometheus-operator:v0.50.0
image: rancher/mirrored-prometheus-prometheus:v2.28.1
