### ISSUE TITLE
TelegramConfigs not working

### ISSUE THREAD

**Issue by gmendesnip** [prometheus-operator/prometheus-operator#4989]
**What happened?**
Setting up notification channels and policies for Grafana, I was following the documentation from https://prometheus.io/docs/alerting/latest/configuration/#telegram_config and https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md for `receivers`.

However, while applying it for slack and telegram alerts, slack alerts were set up fine while telegram alerts were not. They are provisioned through terraform and the changes are applied, but when I log into Grafana console, it is not shown the Telegram notification channel.

I've set up every attribute exactly as the documentation shows.

**Did you expect to see something different?**

Yes, I expected the notification channel provisioned on the Grafana console.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the alert manager configuration down below

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    alertmanagerConfig: alertmanager-config
spec:
  route:
    receiver: "null"
    groupBy: ['instance', 'alertname']
    groupWait: 45s
    groupInterval: 10m
    repeatInterval: 2h
    routes:
      - receiver: "slack-infra"
        continue: false
        matchers:
          - name: group
            value: infra
      - receiver: "slack-apps"
        continue: false
        matchers:
          - name: group
            value: apps
      - receiver: "slack-sniptech"
        continue: false
        matchers:
          - name: group
            value: sniptech
      - receiver: "telegram-sniptech"
        continue: false
        matchers:
          - name: group
            value: sniptech
  receivers:
    - name: 'null'
    - name: 'slack-infra'
      slackConfigs:
        - channel: '#alerts'
          sendResolved: true
          text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
          apiURL:
            key: 'apiURL'
            name: 'slack-config'
    - name: 'slack-apps'
      slackConfigs:
        - channel: '#alerts-apps'
          sendResolved: true
          text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
          apiURL:
            key: 'apiURL'
            name: 'slack-apps-config'
    - name: 'telegram-sniptech'
      telegramConfigs:
        - botToken:
            key: 'apiToken'
            name: 'telegram-sniptech-config'
          chatID: -794781609
          message: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
          sendResolved: true
    - name: 'slack-sniptech'
      slackConfigs:
        - channel: '#sniptech-alerts'
          sendResolved: true
          text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
          apiURL:
            key: 'apiURL'
            name: 'slack-sniptech-config'
```

**Environment**

* Prometheus Operator version:

Name:                   app-cluster-prometheus-operator
Namespace:              monitoring
CreationTimestamp:      Mon, 22 Aug 2022 16:57:44 +0200
Labels:                 app.kubernetes.io/component=operator
                        app.kubernetes.io/instance=app-cluster-prometheus
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=kube-prometheus
                        helm.sh/chart=kube-prometheus-6.10.3
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: app-cluster-prometheus
                        meta.helm.sh/release-namespace: monitoring
Selector:               app.kubernetes.io/component=operator,app.kubernetes.io/instance=app-cluster-prometheus,app.kubernetes.io/name=kube-prometheus
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/component=operator
                    app.kubernetes.io/instance=app-cluster-prometheus
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=kube-prometheus
                    helm.sh/chart=kube-prometheus-6.10.3
  Service Account:  app-cluster-prometheus-operator
  Containers:
   prometheus-operator:
    Image:      docker.io/bitnami/prometheus-operator:0.56.2-debian-10-r0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/app-cluster-prometheus-kubelet
      --log-format=logfmt
      --log-level=info
      --localhost=127.0.0.1
      --prometheus-config-reloader=$(PROMETHEUS_CONFIG_RELOADER)
    Liveness:   http-get http://:http/metrics delay=120s timeout=5s period=10s #success=1 #failure=6
    Readiness:  http-get http://:http/metrics delay=30s timeout=5s period=10s #success=1 #failure=6
    Environment:
      PROMETHEUS_CONFIG_RELOADER:  <set to the key 'prometheus-config-reloader' of config map 'app-cluster-prometheus-operator'>  Optional: false
    Mounts:                        <none>
  Volumes:                         <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   app-cluster-prometheus-operator-5d46c4bb98 (1/1 replicas created)
Events:          <none>

* Kubernetes version information:
* 
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.21.14-gke.700

* Kubernetes cluster kind:

Using terraform resource helm_release

resource "helm_release" "grafana-operator" {
  name             = "grafana-operator"
  repository       = "https://charts.bitnami.com/bitnami"
  chart            = "grafana-operator"
  namespace        = kubernetes_namespace.monitoring.metadata[0].name
  create_namespace = false
  version          = "2.5.2"

  set {
    name  = "grafana.enabled"
    value = "false"
  }

}

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
