### ISSUE TITLE
log format not set on prometheus main container

### ISSUE THREAD

**Issue by applike-ss** [prometheus-operator/prometheus-operator#4993]
**What happened?**
I was setting the log format for the Prometheus CR to json.
The config reloader container did get the new `--log-format=json` argument, the main container (`prometheus`) did not.

**Did you expect to see something different?**
I would've expected consistent behaviour for the same pod. This means, that the `prometheus` container should've also gotten the `--log-format=json` argument added, just like the `config-reloader` container did.

**How to reproduce it (as minimally and precisely as possible)**:
* Create a Prometheus CR
* Change the logFormat flag to json

**Environment**

* Prometheus Operator version: quay.io/prometheus-operator/prometheus-operator:v0.58.0

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information: 1.22

    `kubectl version`
    

* Kubernetes cluster kind: aws eks

    insert how you created your cluster: kops, bootkube, etc.

* Manifests: -

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs: no errors/warnings

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by applike-ss** [comment]
I just wrote a unit test which should've proven my case, however instead it prove me wrong.

This seems quite strange, because i see the result right in front of me in lens and the config-reloader container hast the --log-format=json arg, while the prometheus container clearly does not.

**Comment by applike-ss** [comment]
I found the cause of the issue, but i am not sure if it is intended behaviour.

My spec looked roughly like this:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
  name: kube-prometheus-stack-prometheus
  namespace: monitoring
spec:
  alerting:
    alertmanagers: []
  containers:
    - args:
        - '--config.file=/etc/prometheus/config_out/prometheus.env.yaml'
        - '--storage.tsdb.min-block-duration=15m'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention.time=10d'
        - '--storage.tsdb.wal-compression'
        - '--web.config.file=/etc/prometheus/web_config/web-config.yaml'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-admin-api'
        - '--web.enable-lifecycle'
        - >-
          --web.external-url=https://my-prom.example.com
        - '--web.route-prefix=/'
      name: prometheus
  enableAdminAPI: false
  evaluationInterval: 30s
  externalUrl: https://my-prom.example.com
  image: quay.io/prometheus/prometheus:v2.37.0
  listenLocal: false
  logFormat: json
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: kube-prometheus-stack
  replicas: 3
  resources:
    limits:
      cpu: '4'
      memory: 32Gi
    requests:
      cpu: '2'
      memory: 16Gi
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector: {}
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: kube-prometheus-stack-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  shards: 1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
  version: v2.37.0
  walCompression: true
```

The root cause here is that i am passing arguments for the prometheus container.

Maybe a dev of this project can tell if this behaviour is desired or not?
