### ISSUE TITLE
Duplicated notifications because of the top-level route enforcement

### ISSUE THREAD

**Issue by duje-begonja-rdx** [prometheus-operator/prometheus-operator#5019]
**What did you do?**
I have created AlertmanagerConfig CRD and set top-level route property "continue: false". CRD was correctly picked up by Alertmanager and placed on top of routes but with property "continue: true".

**Did you expect to see some different?**
I expected that property won't be enforced. That is causing us problem because after notification is sent (route from CRD) it continues to be evaluated and notifcation is sent because of the default route (route from global Alertmanager). All of ours notifications are now duplicated.
How can I have property "continue: false" or the top level route because this brings much noise in our alerting system.

**Environment**

* Prometheus Operator version:

    Image:      quay.io/prometheus-operator/prometheus-operator:v0.48.1
    
    

* Kubernetes version information:

**Client Version:** version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/arm64"}

**Server Version:** version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-18ef993", GitCommit:"ac73613dfd25370c18cbbbc6bfc65449397b35c7", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:50Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by liam-murray-xealth** [comment]
I ran into this as well. I am adding an additional AlertmanagerConfig which gets merged into the global config under the top-level route. It appears the Prometheus Operator does not recognize that the top-level route in the AlertmanagerConfig becomes a child route in the final config.

**Comment by simonpasquier** [comment]
Can you share the Alertmanager & Alertmanager manifests as well as the generated Alertmanager configuration (from the Alertmanager UI status page)?

**Comment by duje-begonja-rdx** [comment]
@simonpasquier here are the alertmanager CRD and resulting global Alertmanager configuration.
So the resulting CRD entry in ALertmanager config is merged successfully but property continue is always true no matter of the definition I put in CRD. Thus alert get fired twice as it doesn't stop.

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: app1-amcfg
  namespace: app1-dev
spec:
  receivers:
    - name: non-prod
      pagerdutyConfigs:
        - client: '{{ template "pagerduty.default.client" . }}'
          clientURL: '{{ template "pagerduty.default.clientURL" . }}'
          description: '{{ template "__subject" . }}'
          details:
            - key: firing
              value: '{{ template "__pd_text" . }}'
            - key: num_firing
              value: '{{ .Alerts.Firing | len }}'
            - key: num_resolved
              value: '{{ .Alerts.Resolved | len }}'
            - key: resolved
              value: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
            - key: Runbook
              value: '{{ (index .Alerts 0).Annotations.runbook_url }}'
            - key: Prometheus Query
              value: '{{ (index .Alerts 0).GeneratorURL }}'
            - key: Dashboard
              value: '{{ (index .Alerts 0).Annotations.dashboard }}'
            - key: Silence
              value: '{{ template "__alert_silence_link" . }}'
          routingKey:
            key: pagerdutyToken
            name: app1-amcfg-integration-keys
          sendResolved: true
          severity: warning
      slackConfigs:
        - actions:
            - text: 'Runbook :green_book:'
              type: button
              url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
            - text: 'Query :prometheus_icon:'
              type: button
              url: '{{ (index .Alerts 0).GeneratorURL }}'
            - text: 'Dashboard :grafana:'
              type: button
              url: '{{ (index .Alerts 0).Annotations.dashboard }}'
            - text: 'Silence :no_bell:'
              type: button
              url: '{{ template "__alert_silence_link" . }}'
          apiURL:
            key: slackWebhookUrl
            name: app1-amcfg-integration-keys
          channel: ***
          color: '{{ template "__slack_color" . }}'
          iconEmoji: ':prometheus_icon:'
          sendResolved: true
          text: '{{ template "__slack_text" . }}'
          title: '{{ template "__slack_title" . }}'
  route:
    continue: false
    receiver: non-prod

---

global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
route:
  receiver: non-prod
  group_by:
  - alertname
  - severity
  - env
  continue: false
  routes:
  - receiver: app1-dev/app1-amcfg/non-prod
    matchers:
    - namespace="app1"
    continue: true
  - receiver: non-prod
    continue: false
  group_wait: 20s
  group_interval: 5m
  repeat_interval: 3h
receivers:
- name: non-prod
  pagerduty_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
    routing_key: <secret>
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{ template "__subject" .}}'
    details:
      firing: '{{ template "__pd_text" . }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
    links:
    - href: '{{ (index .Alerts 0).Annotations.runbook_url }}'
      text: Runbook
    - href: '{{ (index .Alerts 0).GeneratorURL }}'
      text: Prometheus Query
    - href: '{{ (index .Alerts 0).Annotations.dashboard }}'
      text: Dashboard
    - href: '{{ template "__alert_silence_link" . }}'
      text: Silence
    severity: warning
  slack_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
    api_url: <secret>
    channel: non-prod-alerts
    username: '{{ template "slack.default.username" . }}'
    color: '{{ template "__slack_color" . }}'
    title: '{{ template "__slack_title" . }}'
    title_link: '{{ template "slack.default.titlelink" . }}'
    pretext: '{{ template "slack.default.pretext" . }}'
    text: '{{ template "__slack_text" . }}'
    short_fields: false
    footer: '{{ template "slack.default.footer" . }}'
    fallback: '{{ template "slack.default.fallback" . }}'
    callback_id: '{{ template "slack.default.callbackid" . }}'
    icon_emoji: ':prometheus_icon:'
    icon_url: '{{ template "slack.default.iconurl" . }}'
    link_names: false
    actions:
    - type: button
      text: 'Runbook :green_book:'
      url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
    - type: button
      text: 'Query :prometheus_icon:'
      url: '{{ (index .Alerts 0).GeneratorURL }}'
    - type: button
      text: 'Dashboard :grafana:'
      url: '{{ (index .Alerts 0).Annotations.dashboard }}'
    - type: button
      text: 'Silence :no_bell:'
      url: '{{ template "__alert_silence_link" . }}'
- name: app1-dev/app1-amcfg/non-prod
  pagerduty_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
    routing_key: <secret>
    url: https://events.pagerduty.com/v2/enqueue
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{ template "__subject" . }}'
    details:
      Dashboard: '{{ (index .Alerts 0).Annotations.dashboard }}'
      Prometheus Query: '{{ (index .Alerts 0).GeneratorURL }}'
      Runbook: '{{ (index .Alerts 0).Annotations.runbook_url }}'
      Silence: '{{ template "__alert_silence_link" . }}'
      firing: '{{ template "__pd_text" . }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
    severity: warning
  slack_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
    api_url: <secret>
    channel: ***
    username: '{{ template "slack.default.username" . }}'
    color: '{{ template "__slack_color" . }}'
    title: '{{ template "__slack_title" . }}'
    title_link: '{{ template "slack.default.titlelink" . }}'
    pretext: '{{ template "slack.default.pretext" . }}'
    text: '{{ template "__slack_text" . }}'
    short_fields: false
    footer: '{{ template "slack.default.footer" . }}'
    fallback: '{{ template "slack.default.fallback" . }}'
    callback_id: '{{ template "slack.default.callbackid" . }}'
    icon_emoji: ':prometheus_icon:'
    icon_url: '{{ template "slack.default.iconurl" . }}'
    link_names: false
    actions:
    - type: button
      text: 'Runbook :green_book:'
      url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
    - type: button
      text: 'Query :prometheus_icon:'
      url: '{{ (index .Alerts 0).GeneratorURL }}'
    - type: button
      text: 'Dashboard :grafana:'
      url: '{{ (index .Alerts 0).Annotations.dashboard }}'
    - type: button
      text: 'Silence :no_bell:'
      url: '{{ template "__alert_silence_link" . }}'
templates:
- /etc/alertmanager/config/*.tmpl
- /etc/alertmanager/config_out/slack.tmpl
- /etc/alertmanager/config_out/pagerduty.tmpl
```
