### ISSUE TITLE
0.59.0: adding CAP_FOWNER capability breaks prometheus in restricted namespaces

### ISSUE THREAD

**Issue by r0bj** [prometheus-operator/prometheus-operator#5023]
**What happened?**
In https://github.com/prometheus-operator/prometheus-operator/pull/4931 CAP_FOWNER capability was added to the securityContext in the thanos-sidecar container. Unfortunately it breaks prometheus running in restricted namespaces (https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted). In restricted namespaces containers must drop ALL capabilities, and are only permitted to add back the NET_BIND_SERVICE capability. In this case pod cannot be started and error message is generated:
```
create Pod prometheus-k8s-1 in StatefulSet prometheus-k8s failed error: pods "prometheus-k8s-1" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "thanos-sidecar" must not include "FOWNER" in securityContext.capabilities.add)
```

What's interesting this change was introduced to fix https://github.com/prometheus-operator/prometheus-operator/issues/4928 but in my case this issue is not really an issue. In my case prometheus with thanos-sidecar works fine uploading blocks to object storage (prometheus-operator version v0.58.0) without adding any capabilities. So let's execute a reproduction test described by @bingikarthik in https://github.com/prometheus-operator/prometheus-operator/issues/4928.

1. Thanos-sidecar container definition:
```
  - args:
    - sidecar
    - --prometheus.url=http://127.0.0.1:9090/
    - --grpc-address=:10901
    - --http-address=:10902
    - --objstore.config=$(OBJSTORE_CONFIG)
    - --tsdb.path=/prometheus
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /config/sa.json
    - name: OBJSTORE_CONFIG
      valueFrom:
        secretKeyRef:
          key: objstore.yml
          name: thanos-objstore-config
    image: quay.io/thanos/thanos:v0.28.0
    imagePullPolicy: IfNotPresent
    name: thanos-sidecar
    ports:
    - containerPort: 10902
      name: http
      protocol: TCP
    - containerPort: 10901
      name: grpc
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 100Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /config
      name: thanos-sa
    - mountPath: /prometheus
      name: prometheus-k8s-db
      subPath: prometheus-db
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jg2lm
      readOnly: true
```

Note, securityContext is dropping ALL and not adding any capabilities which is compatible with restricted Pod Security Standard.

Let's execute commands to confirm existence of the issue:
```
$ kubectl exec -it prometheus-k8s-0 -c thanos-sidecar -- /bin/sh
/prometheus $ mkdir -p /prometheus/thanos/upload/01GCSR0XCER13FCWZZ7X34QPAW/chunks/000001
/prometheus $ ln /prometheus/01GCSR0XCER13FCWZZ7X34QPAW/chunks/000001 /prometheus/thanos/upload/01GCSR0XCER13FCWZZ7X34QPAW/chunks/000001
/prometheus $ ls -la /prometheus/thanos/upload/01GCSR0XCER13FCWZZ7X34QPAW/chunks/000001/000001
-rw-rw-r--    2 nobody   nobody    91775652 Sep 12 21:00 /prometheus/thanos/upload/01GCSR0XCER13FCWZZ7X34QPAW/chunks/000001/000001
```

All commands executed without issue, link created successfully. No issue here.

So my conclusion is that adding CAP_FOWNER capability is not really necessary in order to thanos-sidecar could upload blocks to object storage.

If, for some reason, CAP_FOWNER capability is needed for some cases maybe it can defined in operator as a optional parameter?

**Environment**

* Prometheus Operator version: 0.59.0

* Kubernetes version information:
```
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.24.3
```

**Comment by simonpasquier** [comment]
Hmm this is interesting. Unfortunately we have no e2e test covering this part but it would have to wait for block uploads which isn't really practical + the test matrix would be huge depending on the object storage solution, PVC or no PVC, default security settings, ...

To confirm, could you add the following snippet to your Prometheus spec and check if 1) the pods can be started and 2) the sidecar uploads the blocks successfully? It should override the capabilities defined by the operator to what you expect.

```
spec:
  ...
  containers:
  - name: thanos-sidecar
    securityContext:
      capabilities:
        add: []
        drop:
        - ALL
```

Could you also share details about the storage? Do you use PVC? Same question for @bingikarthik.
