### ISSUE TITLE
`Probe` config ignored

### ISSUE THREAD

**Issue by euven** [prometheus-operator/prometheus-operator#5036]
**What happened?**
I created a  [`Probe`](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.ProbeSpec) resource, with [`basicAuth`](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.BasicAuth) and [`tlsConfig`](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.ProbeTLSConfig) configured, expecting the prober to use this config when probing the targets.

**Did you expect to see something different?**
I could see the probes happening in the (remote) Blackbox exporter/prober logs, but the TLS and basicAuth config seems to not be used at all and the probes were failing.

I ended up creating a module in the Blackbox exporter config with the corresponding TLS and basic auth config - that worked.

My question is why doesn't the relevant config on the `Probe` resource not work?

**How to reproduce it (as minimally and precisely as possible)**:

Create a `Probe` resource, configured to use a remote prober, with a target that has a self-signed cert and some basic auth.

**Environment**

* Prometheus Operator version: 

    `v0.50.0`
    
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`
    

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
  name: test-probe
spec:
  module: http_2xx
  prober:
    scheme: https
    url: my-remote-blackbox-prober.example.com
  targets:
    staticConfig:
      static:
        - example.com
  tlsConfig:
    insecureSkipVerify: false
  basicAuth:
    username:
      name: secret-name
      key: key-in-secret
    password:
      name: secret-name
      key: key-in-secret
```

* Prometheus Operator Logs:

Nothing much in here:
```
level=info ts=2022-05-09T03:46:37.931143418Z caller=main.go:261 msg="Starting Prometheus Operator" version="(version=0.50.0, branch=master, revision=83fe36566)"
level=info ts=2022-05-09T03:46:37.949856116Z caller=main.go:262 build_context="(go=go1.16, user=paulfantom, date=20210817-15:18:20)"
level=info ts=2022-05-09T03:46:38.569433876Z caller=server.go:54 msg="enabling server side TLS"
level=info ts=2022-05-09T03:46:38.786322803Z caller=main.go:124 msg="Starting secure server on [::]:8443"
level=info ts=2022-05-09T03:46:39.012308728Z caller=operator.go:421 component=prometheusoperator msg="connection established" cluster-version=v1.19.6
level=info ts=2022-05-09T03:46:39.022389054Z caller=operator.go:430 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2022-05-09T03:46:39.060516583Z caller=operator.go:449 component=alertmanageroperator msg="connection established" cluster-version=v1.19.6
level=info ts=2022-05-09T03:46:39.061030898Z caller=operator.go:458 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2022-05-09T03:46:39.012727356Z caller=operator.go:309 component=thanosoperator msg="connection established" cluster-version=v1.19.6
level=info ts=2022-05-09T03:46:39.09026831Z caller=operator.go:318 component=thanosoperator msg="CRD API endpoints ready"
level=info ts=2022-05-09T03:46:41.257443306Z caller=operator.go:261 component=thanosoperator msg="successfully synced all caches"
level=info ts=2022-05-09T03:46:53.552492262Z caller=operator.go:281 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2022-05-09T03:46:54.753826891Z caller=operator.go:351 component=prometheusoperator msg="successfully synced all caches"
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
can you share the generated Prometheus configuration?

**Comment by euven** [comment]
See below for a Probe and its generated Prometheus config @simonpasquier : 

Probe:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: testie-probe4
  namespace: example-namespace
spec:
  module: http_2xx
  prober:
    scheme: https
    url: prober.example.com
  targets:
    staticConfig:
      static:
        - example.com
  tlsConfig:
    ca:
      secret:
        name: rancher-monitoring-tls-auth
        key: ca.crt
    cert:
      secret:
        name: rancher-monitoring-tls-auth
        key: tls.crt
    keySecret:
      name: rancher-monitoring-tls-auth
      key: tls.key
    insecureSkipVerify: true
```

Relevant generated Prometheus config:
```yaml
- job_name: probe/me-test/testie-probe4
  honor_timestamps: true
  metrics_path: /probe
  scheme: https
  params:
    module:
    - http_2xx
  static_configs:
  - targets:
    - example.com
    labels:
      namespace: example-namespace
  relabel_configs:
  - source_labels:
    - job
    target_label: __tmp_prometheus_job_name
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: prober.example.com
  tls_config:
    insecure_skip_verify: true
    ca_file: /etc/prometheus/certs/secret_example-namespace-test_rancher-monitoring-tls-auth_ca.crt
    cert_file: /etc/prometheus/certs/secret_example-namespace_rancher-monitoring-tls-auth_tls.crt
    key_file: /etc/prometheus/certs/secret_example-namespace_rancher-monitoring-tls-auth_tls.key
```

I see the following in the Blackbox exporter logs:
```
                                                                                                                                                                                        
ts=2022-09-21T09:10:33.763Z caller=main.go:211 module=http_2xx target=example.com level=debug msg="Beginning probe" probe=http timeout_seconds=5
ts=2022-09-21T09:10:33.763Z caller=main.go:211 module=http_2xx target=example.com level=debug msg="Resolving target address" target=example.com ip_protocol=ip4
ts=2022-09-21T09:10:33.777Z caller=main.go:211 module=http_2xx target=example.com level=debug msg="Resolved target address" target=example.com ip=[redacted ip]
ts=2022-09-21T09:10:33.777Z caller=main.go:211 module=http_2xx target=example.com level=debug msg="Making HTTP request" url=http://[redacted ip] host=example.com
ts=2022-09-21T09:10:33.807Z caller=main.go:211 module=http_2xx target=example.com level=debug msg="Received redirect" location=https://example.com
ts=2022-09-21T09:10:33.807Z caller=main.go:211 module=http_2xx target=example.com level=debug msg="Making HTTP request" url=https://example.com host=
ts=2022-09-21T09:10:33.807Z caller=main.go:211 module=http_2xx target=example.com level=debug msg="Address does not match first address, not sending TLS ServerName" first=[redacted]         address=example.com
ts=2022-09-21T09:10:33.850Z caller=main.go:211 module=http_2xx target=example.com level=debug msg="Error for HTTP request" err="Get \"https://example.com\": x509: certificate is valid for   ingress.local, not example.com"
ts=2022-09-21T09:10:33.850Z caller=main.go:211 module=http_2xx target=example.com level=debug msg="Response timings for roundtrip" roundtrip=0 start=2022-09-21T09:10:33.777775139Z           dnsDone=2022-09-21T09:10:33.777775139Z connectDone=2022-09-21T09:10:33.790218057Z gotConn=2022-09-21T09:10:33.790311765Z responseStart=2022-09-21T09:10:33.806323056Z tlsStart=0001-01-01T00: 00:00Z tlsDone=0001-01-01T00:00:00Z end=0001-01-01T00:00:00Z
ts=2022-09-21T09:10:33.850Z caller=main.go:211 module=http_2xx target=example.com level=debug msg="Response timings for roundtrip" roundtrip=1 start=2022-09-21T09:10:33.80809699Z            dnsDone=2022-09-21T09:10:33.820626875Z connectDone=2022-09-21T09:10:33.831429737Z gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z tlsStart=2022-09-21T09:10:33.831691637Z     tlsDone=2022-09-21T09:10:33.849945774Z end=0001-01-01T00:00:00Z
ts=2022-09-21T09:10:33.850Z caller=main.go:211 module=http_2xx target=example.com level=debug msg="Probe failed" duration_seconds=0.087501387
```

As you can see above, it's trying to validate the cert, even though `insecureSkipVerify` has been configured.


My Blackbox exporter `http_2xx` module config looks as follows:
```yaml
    modules:
      http_2xx:
        http:
          follow_redirects: true
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
        prober: http
        timeout: 5s
```

Let me know if you need anything else.

Thanks!

**Comment by simonpasquier** [comment]
`insecureSkipVerify` only applies to the TLS connection between Prometheus and the blackbox exporter. If you want to skip verification between the blackbox exporter and the probed host, the right way to go is indeed to tweak the module configuration in the exporter.

**Comment by euven** [comment]
Oh, right - thanks for clarifying @simonpasquier !

In that case, should the references to "targets" in the [documentation](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.ProbeTLSConfig) be removed? I think that's what made me misunderstand this.

> only applies to the TLS connection between Prometheus and the blackbox exporter

I assume this is the case for the the `basicAuth` configuration too?

I wonder if it would be clearer to have the `tlsConfig` and `basicAuth` configuration in the `Probe` resource as part of the `prober` config, instead of being direct children of `spec`?

**Comment by simonpasquier** [comment]
> In that case, should the references to "targets" in the [documentation](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.ProbeTLSConfig) be removed?

It says "targets" because the struct is an embedded version of [SafeTLSConfig](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.SafeTLSConfig). What could be updated at least is the `ProbeTLSConfig` description.

https://github.com/prometheus-operator/prometheus-operator/blob/817797096d8dacc2c6e5b2bac77433b10e013a53/pkg/apis/monitoring/v1/types.go#L2190-L2194

It could be `ProbeTLSConfig specifies TLS configuration parameters for the prober.`

And the description of `SafeTLSConfig` fields could be written in a more generic form maybe?

"Struct containing the CA cert to use for the targets." :arrow_right: "Certificate authority used when verifying server certificates."
"Struct containing the client cert file for the targets. " :arrow_right: "Client certificate to present when doing client-authentication."

https://github.com/prometheus-operator/prometheus-operator/blob/817797096d8dacc2c6e5b2bac77433b10e013a53/pkg/apis/monitoring/v1/types.go#L1612-L1625

> I wonder if it would be clearer to have the tlsConfig and basicAuth configuration in the Probe resource as part of the prober config, instead of being direct children of spec?

It could be but the CRD being v1, we'd have to keep the existing fields and mark them as deprecated. It could be done but not high on the priority list IMHO.

**Comment by michaelniemand** [comment]
I see the basicAuth part of the question was never addressed; 
Just to make sure I undersand: The basicAuth section in the Probe spec is **not** meant for authentication against the endpoint to probe but the connection between BB exporter and Prometheus? 
Additionally I would need to add a module config with hard coded credentials for each endpoint to allow probing basic auth secured endpoints - am I understanding this correctly?

So my BB exporter conf would essentially have to look like this?

```yaml
modules:
  http_basic_auth_server1:
    prober: http
    timeout: 5s
    http:
      method: POST
      headers:
        Host: "server1.example.com"
      basic_auth:
        username: "username"
        password: "mysecret1"
  http_basic_auth_server2:
    prober: http
    timeout: 5s
    http:
      method: POST
      headers:
        Host: "server2.example.com"
      basic_auth:
        username: "username"
        password: "mysecret2"        
  http_basic_auth_server3:
    prober: http
    timeout: 5s
    http:
      method: POST
      headers:
        Host: "server3example.com"
      basic_auth:
        username: "username"
        password: "mysecret3"        
```
