### ISSUE TITLE
how to configure ServiceMonitor scrape metrics other than "/metrics"

### ISSUE THREAD

**Issue by oneslideicywater** [prometheus-operator/prometheus-operator#5046]
I have a service serve metrics under path “/promtheus”, which not the usually used path "/metrics"

how can I configure `ServiceMonitor` Object, like this ?

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-proxy
  labels:
    team: jenkins-proxy
spec:
  selector:
    matchLabels:
      app: jenkins-proxy
  endpoints:
  - port: web
   # path: /prometheus 

```

**Comment by oneslideicywater** [comment]
found it in the CRD description
```yaml
                    path:
                      description: HTTP path to scrape for metrics.
                      type: string
                    port:
                      description: Name of the service port this endpoint refers to. Mutually exclusive with targetPort.
                      type: string
```
