### ISSUE TITLE
 Using bearerTokenSecret doesn't include the Bearer Token in the Authentication Header #3277

### ISSUE THREAD

**Issue by sarce666** [prometheus-operator/prometheus-operator#5054]
hello 

i have the exact same issue 

here is my service monitor :

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    ops.workload.io/component: arangodb
    ops.workload.io/category: infrastructure
  name: arangodb
  namespace: cattle-monitoring-system
spec:
  endpoints:
    - bearerTokenSecret:
        key: token
        name: arango
    - scheme: https
    - port: https
      interval: 30s
      honorLabels: true
      scheme: https
      path: /metrics
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: __address__
          regex: (.*)
          replacement: "xxxxxx.arangodb.cloud:8829"
          action: replace
  selector:
    matchLabels:
      k8s-app: external-dev-prometheus
  namespaceSelector:
    matchNames:
      - cattle-monitoring-system
```

the token:

```
apiVersion: v1
metadata:
  name: arango
  namespace: cattle-monitoring-system
data:
  token: BASE 64 TOKEN
kind: Secret
```

the endpoint definition 
```

kind: Endpoints
apiVersion: v1
metadata:
  name: arangodb
  labels:
    k8s-app: external-dev-prometheus
    workload.stateful: arangodb
subsets:
  - addresses:
      - ip: xxxxx
        nodeName: xxxx.arangodb.cloud
    ports:
      - name: https
        port: 8829
        protocol: TCP
```

and the service 
```

kind: Service
apiVersion: v1
metadata:
  name: arangodb
  labels:
    k8s-app: external-dev-prometheus
    workload.stateful: arangodb
spec:
  type: ExternalName
  externalName: xxxxxx.arangodb.cloud
  ports:
    - name: https
      port: 8829
      targetPort: 443
      protocol: TCP
```

the prometheus is build 2.28.1
install in kubernetes with helm 100.1.3+up19.0.3
the operator version is v0.50.0

_Originally posted by @sarce666 in https://github.com/prometheus-operator/prometheus-operator/issues/3277#issuecomment-1261057579_
