### ISSUE TITLE
How to use Ec2 Service discovery job via prometheus operator crd 

### ISSUE THREAD

**Issue by pratikgajjar** [prometheus-operator/prometheus-operator#5057]
**What did you do?**
I want to use [ec2_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ec2_sd_config) to scrape metrics from ec2 nodes that are not part of k8s cluster

**Did you expect to see some different?**
Couldn't find docs related to this on [OpenShift API spec](https://docs.openshift.com/container-platform/4.10/rest_api/monitoring_apis/servicemonitor-monitoring-coreos-com-v1.html) 

**Environment**
PROD/Stag ? 

* Prometheus Operator version:
```yaml
Name:                   prometheus-operator
Namespace:              monitoring
CreationTimestamp:      Mon, 08 Aug 2022 16:30:41 +0000
Labels:                 app.kubernetes.io/component=controller
                        app.kubernetes.io/name=prometheus-operator
                        app.kubernetes.io/part-of=kube-prometheus
                        app.kubernetes.io/version=0.57.0
```

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.11-eks-18ef993", GitCommit:"b9628d6d3867ffd84c704af0befd31c7451cdc37", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
EKS
