### ISSUE TITLE
spec.tsdb.outOfOrderTimeWindow YAML unmarshal error

### ISSUE THREAD

**Issue by jzelinskie** [prometheus-operator/prometheus-operator#5076]
**What happened?**

Attempted to deploy Prometheus CR with spec.tsdb.outOfOrderTimeWindow set to `30m`.
Pod fails to come up.

**Did you expect to see something different?**

I expected to see the pods come up healthy.

**How to reproduce it (as minimally and precisely as possible)**:

Create a Prometheus CR using the new field and see the pod fail to come up.

**Environment**

* Prometheus Operator version: v0.60.0
* Kubernetes version information: v1.25.2
* Kubernetes cluster kind: kind v1.25.2
* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: test
  namespace: dev
spec:
  ruleSelector:
    matchLabels:
      prometheus: test-prom
  podMetadata:
    labels:
      prometheus: test-prom
  retention: 90d
  serviceAccountName: test-prom
  enableFeatures:
    - remote-write-receiver
    - promql-at-modifier
  externalLabels:
    stack: dev
  tsdb:
    outOfOrderTimeWindow: 30m
  thanos:
    image: quay.io/thanos/thanos:v0.27.0
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  alerting:
    alertmanagers:
      - namespace: dev
        apiVersion: v2
        name: test-alertmanager
        port: web
        pathPrefix: /alertmanager
  externalUrl: https://localhost/prometheus/
  routePrefix: /prometheus
  image: prom/prometheus:v2.39.1
  version: 2.39.1
  replicas: 1
```

* Prometheus Operator Logs:

```
ts=2022-10-07T21:49:53.333Z caller=main.go:455 level=error msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: yaml: unmarshal errors:\n  line 232: field tsdb not found in type config.plain"
```
