### ISSUE TITLE
AlertmanagerConfig does not support apiURLFile for Slack

### ISSUE THREAD

**Issue by ameyp** [prometheus-operator/prometheus-operator#5077]
I'm trying to use `apiFileURL` in a `AlertmanagerConfig` custom resource to read the Slack webhook URL from a file. Here's my YAML:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    release: prometheus-stack
  name: alerts-slack
  namespace: monitoring
spec:
  receivers:
    - name: slack-notifications
      slackConfigs:
        - channel: "#alarms"
          apiURLFile: /my/secrets/slack-webhook-url
          username: AlertManager
  route:
    groupBy:
      - app
    groupInterval: 5m
    groupWait: 30s
    receiver: webhook
    repeatInterval: 12h
```

**What happened?**

`kubectl apply` failed with:

```
error: error validating "/home/amey/tmp/alertmanager.yaml": error validating data: ValidationError(AlertmanagerConfig.spec.receivers[0].slackConfigs[0]): unknown field "apiURLFile" in com.coreos.monitoring.v1alpha1.AlertmanagerConfig.spec.receivers.slackConfigs; if you choose to ignore these errors, turn validation off with --validate=false
```

**Did you expect to see something different?**

I expected it to succeed

**How to reproduce it (as minimally and precisely as possible)**:

Try to apply the YAML above

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.58.0`

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    `k3s`

* Manifests:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    release: prometheus-stack
  name: alerts-slack
  namespace: monitoring
spec:
  receivers:
    - name: slack-notifications
      slackConfigs:
        - channel: "#alarms"
          apiURLFile: /my/secrets/slack-webhook-url
          username: AlertManager
  route:
    groupBy:
      - app
    groupInterval: 5m
    groupWait: 30s
    receiver: webhook
    repeatInterval: 12h
```

* Prometheus Operator Logs:

Not relevant

**Anything else we need to know?**:

I don't see that key in the CRD either: https://github.com/prometheus-operator/prometheus-operator/blob/main/jsonnet/prometheus-operator/alertmanagerconfigs-crd.json

**Comment by simonpasquier** [comment]
The Slack configuration already has a `apiURL` field which is a secret key reference so instead of assuming a file location on disk, the AlertmanagerConfig resource can reference the secret directly:

```
      slackConfigs:
        - channel: "#alarms"
          apiURL:
            name: my-secret
            key: slack-webhook-url
          username: AlertManager
```

Does it work for you?
