### ISSUE TITLE
Adding relabel for every static in staticConfig of Probe

### ISSUE THREAD

**Issue by P9os** [prometheus-operator/prometheus-operator#5105]
**What is missing?**
We use Probe for collect data from SNMP targets, and have only IP address label.
**Why do we need it?**
Ability to add label for every static target in Probe CRD, like us prometheus config yaml

```yaml
- job_name: 'development'
    static_configs:
      - targets: [ '192.168.1.1:9100' ]
        labels:
          service: '1'
      - targets: [ '192.168.1.1:9101' ]
        labels:
          service: '2'
```

**Environment**
K8s v1.22.8
* Prometheus Operator version: quay.io/prometheus-operator/prometheus-operator:v0.58.0

**Anything else we need to know?**:
Suggest model like as:
```yaml
  targets:
    staticConfig:
      static:
        - address: 192.168.0.220
          labels:
            - UPS: 1
        - address: 192.168.0.221
          labels:
            - UPS: 2
        - address: 192.168.12.222
          labels:
           - UPS: 3
```
Thanks

**Comment by simonpasquier** [comment]
This is supported AFAICT, the spec already allows to define labels per target:

```
  targets:
    staticConfig:
      static:
        - address: [192.168.0.220]
          labels:
            UPS: "1"
        - address: [192.168.0.221]
          labels:
            UPS: "2"
        - address: [192.168.12.222]
          labels:
           UPS: "3"
```

**Comment by P9os** [comment]
Now, i check manifests CRD of Probe,
[Probe](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-probes.yaml#L581).
```yaml
static:
  description: The list of hosts to probe.
  items:
    type: string
  type: array
```
And it not contains this model.
