### ISSUE TITLE
Prometheus log reports field partial_response_strategy not found in type rulefmt.RuleGroup when sets this field in PrometheusRule

### ISSUE THREAD

**Issue by slashpai** [prometheus-operator/prometheus-operator#5124]
**What happened?**
Prometheus log reports field partial_response_strategy not found in type rulefmt.RuleGroup when sets this field in PrometheusRule. This was getting logged till removed this field or set it to `""`

```
ts=2022-10-27T11:43:29.048Z caller=manager.go:980 level=error component="rule manager" msg="loading groups failed" err="/etc/prometheus/rules/prometheus-user-workload-rulefiles-0/ns1-example-alert-2f98a05b-dd27-4d1a-87bd-5ef74352cc3a.yaml: yaml: unmarshal errors:\n  line 3: field partial_response_strategy not found in type rulefmt.RuleGroup"
ts=2022-10-27T11:43:29.048Z caller=main.go:1227 level=error msg="Failed to apply configuration" err="error loading rules, previous rule set restored"
ts=2022-10-27T11:43:29.048Z caller=main.go:945 level=error msg="Error reloading config" err="one or more errors occurred while applying the new configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\")"
```

**Did you expect to see something different?**

Since this field is only applicable for Thanos. Operator should reject this field for Prometheus and allow it only for Thanos

**How to reproduce it (as minimally and precisely as possible)**:

Create a PrometheusRule object with `partial_response_strategy` set to a valid accepted value

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-alert
  namespace: ns1
spec:
  groups:
  - name: example
    partial_response_strategy: "abort"
    rules:
    - alert: VersionAlert
      expr: version{job="prometheus-example-app"} == 0
```

**Environment**

All

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

NA

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

NA

* Manifests:

```
insert manifests relevant to the issue
```

NA

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

NA

**Anything else we need to know?**:

As discussed in https://github.com/prometheus-operator/prometheus-operator/pull/4999#issuecomment-1280927196
