### ISSUE TITLE
Pod Monitor Target disappears on Port change or never appears

### ISSUE THREAD

**Issue by brahama** [prometheus-operator/prometheus-operator#5127]
Hi fellows,

I had created a simple pod monitor just to start testing and adding targets, but on my first attempt i am having issues and the target does not appear in the UI.
This was strange as i am seeing quite a few prometheus targets UP and just a couple DOWN due to Connection Refused.

Simple manifest
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: tyk-gw-pod
  labels:
    team: infra
spec:
  selector:
    matchLabels:
      app: gateway-tyk-tyk-headless
  podMetricsEndpoints:
  - interval: 10s
    path: /metrics
    targetPort: 8080
```

This one works (shows as DOWN correctly with an unauthorized message) and shows in the UI pretty fast after apply.
Now if i change the port to 8081 (should give connection Refused) it just disappears from the Target lists and i do not see any error/log in the operator or prometheus pods.

Now the other strange part is when I added another Pod Monitor. This one never appeared and no errors/logs that could help me debug it. i can reach from a POD in the same namespace but it is never shown in the UI.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: tyk-pump-pod
  labels:
    team: infra
spec:
  selector:
    matchLabels:
      app: pump-tyk-tyk-headless
  podMetricsEndpoints:
  - targetPort: 9090
 ```

I know that the targetPort is deprecated but it should work right? (and also the first one does work)

I am testing in my local Kind cluster.

Operator logs
```
level=info ts=2022-10-30T19:09:19.673037218Z caller=operator.go:1390 component=prometheusoperator key=monitoring/prometheus-kube-prometheus-prometheus msg="sync prometheus"
level=warn ts=2022-10-30T19:09:19.680312793Z caller=promcfg.go:860 component=prometheusoperator msg="'targetPort' is deprecated, use 'port' instead." version=v2.39.0
level=warn ts=2022-10-30T19:09:19.680370696Z caller=promcfg.go:860 component=prometheusoperator msg="'targetPort' is deprecated, use 'port' instead." version=v2.39.0
level=warn ts=2022-10-30T19:09:19.68038821Z caller=promcfg.go:860 component=prometheusoperator msg="'targetPort' is deprecated, use 'port' instead." version=v2.39.0
level=info ts=2022-10-30T19:09:19.69064898Z caller=operator.go:754 component=alertmanageroperator key=monitoring/prometheus-kube-prometheus-alertmanager msg="sync alertmanager"
level=info ts=2022-10-30T19:09:19.713058997Z caller=operator.go:1390 component=prometheusoperator key=monitoring/prometheus-kube-prometheus-prometheus msg="sync prometheus"
level=info ts=2022-10-30T19:09:19.713191703Z caller=operator.go:1559 component=prometheusoperator key=monitoring/prometheus-kube-prometheus-prometheus msg="update prometheus status"
level=warn ts=2022-10-30T19:09:19.722654903Z caller=promcfg.go:860 component=prometheusoperator msg="'targetPort' is deprecated, use 'port' instead." version=v2.39.0
level=warn ts=2022-10-30T19:09:19.722714426Z caller=promcfg.go:860 component=prometheusoperator msg="'targetPort' is deprecated, use 'port' instead." version=v2.39.0
level=warn ts=2022-10-30T19:09:19.722732903Z caller=promcfg.go:860 component=prometheusoperator msg="'targetPort' is deprecated, use 'port' instead." version=v2.39.0
level=info ts=2022-10-30T19:09:19.753782803Z caller=operator.go:1559 component=prometheusoperator key=monitoring/prometheus-kube-prometheus-prometheus msg="update prometheus status"
```

Installed from Chart
Using version `# https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.57.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml`

Any help on how to debug is also appreciated. But the appearing and not appearing got me lost.

Thanks!
