### ISSUE TITLE
walCompression not working

### ISSUE THREAD

**Issue by whc9527** [prometheus-operator/prometheus-operator#5162]
helm upgrade --install -n hawkeye-engineer-gz pm-adx prometheus-community/kube-prometheus-stack --version 41.7.4 -f prometheus/xxx.yaml

```
prometheus:
  prometheusSpec:
    containers:
      - name: prometheus
        args:
        - "--web.console.templates=/etc/prometheus/consoles"
        - "--web.console.libraries=/etc/prometheus/console_libraries"
        - "--config.file=/etc/prometheus/config_out/prometheus.env.yaml"
        - "--storage.tsdb.path=/prometheus"
        - "--web.enable-lifecycle"
        - "--storage.tsdb.no-lockfile"
        - "--web.enable-admin-api"
        - "--web.external-url=https://prometheus.fop.bar.com/"
        - "--web.route-prefix=/"
        - "--storage.tsdb.min-block-duration=10m"
        - "--storage.tsdb.max-block-duration=15m"
        - "--storage.tsdb.retention.size=800MB"
        - "--storage.tsdb.retention.time=1h"

    walCompression: false

```

I installed prometehus using the above method, but storage.tsdb.wal-compression is still true. Why?

![image](https://user-images.githubusercontent.com/17898805/201928891-a9832c51-077e-463a-a762-1a48e59b9bbe.png)
