### ISSUE TITLE
Alertmanager not dropping alerts based on "match" rule

### ISSUE THREAD

**Issue by Migueljfs** [prometheus-operator/prometheus-operator#5165]
**What did you do?**
I set up alertmanager using kube-prometheus rules and Prometheus Operator. I added matching routes to drop alerts based on low severity and to send slack alerts on high severity.

Here's an example of what I see in slack:
<img width="713" alt="image" src="https://user-images.githubusercontent.com/25540481/199969900-53888b56-091d-4e51-b8f0-25ce52677389.png">

As you can see, both "critical" and "info" alert were sent to slack

**What did you expect to see?**
I expect alerts with matching severity to be routed to the correct receiver.

**What did you see instead? Under which circumstances?**
Instead, all alerts are being sent to slack, regardless of severity

**Environment**

* System information:
`Linux 5.10.109+ x86_64`

* Operator version:
```
quay.io/prometheus-operator/prometheus-operator:v0.59.2
```

* Alertmanager version:

```
alertmanager, version 0.24.0 (branch: HEAD, revision: f484b17fa3c583ed1b2c8bbcec20ba1db2aa5f11)
  build user:       root@265f14f5c6fc
  build date:       20220325-09:31:33
  go version:       go1.17.8
  platform:         linux/amd64

```

* Prometheus version:

```
prometheus, version 2.39.1 (branch: HEAD, revision: dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)
  build user:       root@273d60c69592
  build date:       20221007-15:57:09
  go version:       go1.19.2
  platform:         linux/amd64
```

* Alertmanager configuration file:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: prometheus-alert-manager-config
  namespace: monitoring
  labels:
    alertmanagerConfig: config
spec:
  route:
    groupBy: ['alertname', 'cluster', 'job', 'env']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'null'
    routes:
      - match:
          severity: 'critical'
        receiver: 'slack-notifications'

      - match:
          severity: 'error'
        receiver: 'slack-notifications'
      
      - match:
          severity: 'warning'
        receiver: 'null'

      - match:
          severity: 'info'
        receiver: 'null'

      - match:
          severity: 'none'
        receiver: 'null'
  receivers:
    - name: 'null'
    - name: slack-notifications
      slackConfigs:
      - apiURL:
          key: apiSecret
          name: alertmanager-slack-config
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Prometheus Event Notification'
        pretext: '{{ .CommonAnnotations.summary }}'
        text: |-
          {{ range .Alerts }}
            {{- if or .Annotations.summary .Annotations.description }}*Alert:* {{ .Annotations.summary }}{{ .Annotations.description }} - `{{ .Labels.severity }}`{{- end }}
            {{ if .Annotations.message }}*Message:* {{ .Annotations.message }}{{ end }}
            {{ if or .Annotations.graph .Annotations.graphUrl }}*Graph:* <{{ .Annotations.graph }}{{ .Annotations.graphUrl }}|:chart_with_upwards_trend:>{{ end }}{{ if or .Annotations.grafana .Annotations.grafanaUrl }}*Grafana:* <{{ .Annotations.grafana }}{{ .Annotations.grafanaUrl }}|:bar_chart:>{{ end }} {{ if or .Annotations.runbook .Annotations.runbook_url }} *Runbook:* <{{ .Annotations.runbook }}{{ .Annotations.runbook_url }}|:spiral_note_pad:>{{ end }}
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
        sendResolved: true
```

* Prometheus configuration file:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.35.0
  name: k8s
  namespace: monitoring
spec:
  replicas: 2
  image: quay.io/prometheus/prometheus:v2.39.1
  thanos:
    baseImage: quay.io/thanos/thanos
    version: v0.28.1
    objectStorageConfig:
      key: thanos.yaml
      name: prometheus-thanos-objstore-config
  additionalScrapeConfigs:
    name: prometheus-additional-scrape-configs
    key: prometheus-additional.yaml
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: alertmanager-main
      namespace: monitoring
      port: web
  enableFeatures: []
  externalLabels:
    cluster: qa-microservices-primary-us-west1
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.35.0
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  resources:
    requests:
      cpu: "2"
      memory: 8Gi
    limits:
      cpu: "4"
      memory: 16Gi
  ruleNamespaceSelector: {}
  ruleSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: 2.38.0
```

* Logs:
No visible logs relevant to the issue

**Comment by simonpasquier** [comment]
could you share the definition of the Alertmanager resource and the resulting Alertmanager configuration (copied from the Alertmanager UI)?

**Comment by Migueljfs** [comment]
Hello,

Alertmanager resource:
```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.24.0
  name: main
  namespace: monitoring
spec:
  replicas: 3
  image: quay.io/prometheus/alertmanager:v0.24.0
  alertmanagerConfigNamespaceSelector: {}
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: config
  externalUrl: "www.my-grafana.com"
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/instance: main
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.24.0
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 4m
      memory: 100Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: 0.24.0
```

In the UI:
```
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
route:
  receiver: Default
  group_by:
  - namespace
  continue: false
  routes:
  - receiver: monitoring/prometheus-alert-manager-config/null
    group_by:
    - alertname
    - cluster
    - job
    - env
    matchers:
    - namespace="monitoring"
    continue: true
    routes:
    - receiver: monitoring/prometheus-alert-manager-config/slack-notifications
      continue: false
    - receiver: monitoring/prometheus-alert-manager-config/slack-notifications
      continue: false
    - receiver: monitoring/prometheus-alert-manager-config/null
      continue: false
    - receiver: monitoring/prometheus-alert-manager-config/null
      continue: false
    - receiver: monitoring/prometheus-alert-manager-config/null
      continue: false
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
  - receiver: Watchdog
    matchers:
    - alertname="Watchdog"
    continue: false
  - receiver: "null"
    matchers:
    - alertname="InfoInhibitor"
    continue: false
  - receiver: Critical
    matchers:
    - severity="critical"
    continue: false
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
inhibit_rules:
- source_matchers:
  - severity="critical"
  target_matchers:
  - severity=~"warning|info"
  equal:
  - namespace
  - alertname
- source_matchers:
  - severity="warning"
  target_matchers:
  - severity="info"
  equal:
  - namespace
  - alertname
- source_matchers:
  - alertname="InfoInhibitor"
  target_matchers:
  - severity="info"
  equal:
  - namespace
receivers:
- name: Default
- name: Watchdog
- name: Critical
- name: "null"
- name: monitoring/prometheus-alert-manager-config/null
- name: monitoring/prometheus-alert-manager-config/slack-notifications
  slack_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
    api_url: <secret>
    username: '{{ template "slack.default.username" . }}'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing
      | len }}{{ end }}] Prometheus Event Notification'
    title_link: '{{ template "slack.default.titlelink" . }}'
    pretext: '{{ .CommonAnnotations.summary }}'
    text: |-
      {{ range .Alerts }}
        {{- if or .Annotations.summary .Annotations.description }}*Alert:* {{ .Annotations.summary }}{{ .Annotations.description }} - `{{ .Labels.severity }}`{{- end }}
        {{ if .Annotations.message }}*Message:* {{ .Annotations.message }}{{ end }}
        {{ if or .Annotations.graph .Annotations.graphUrl }}*Graph:* <{{ .Annotations.graph }}{{ .Annotations.graphUrl }}|:chart_with_upwards_trend:>{{ end }}{{ if or .Annotations.grafana .Annotations.grafanaUrl }}*Grafana:* <{{ .Annotations.grafana }}{{ .Annotations.grafanaUrl }}|:bar_chart:>{{ end }} {{ if or .Annotations.runbook .Annotations.runbook_url }} *Runbook:* <{{ .Annotations.runbook }}{{ .Annotations.runbook_url }}|:spiral_note_pad:>{{ end }}
        *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}
    short_fields: false
    footer: '{{ template "slack.default.footer" . }}'
    fallback: '{{ template "slack.default.fallback" . }}'
    callback_id: '{{ template "slack.default.callbackid" . }}'
    icon_emoji: '{{ template "slack.default.iconemoji" . }}'
    icon_url: '{{ template "slack.default.iconurl" . }}'
    link_names: false
templates: []
```

**Comment by simonpasquier** [comment]
The configuration of matchers is different between the Alertmanager [configuration file](https://prometheus.io/docs/alerting/latest/configuration/) and the AlertmanagerConfig CRD. 
Your AlertmanagerConfig object should rather look like this:

```
    routes:
      - matchers:
        - name: 'severity'
          value: 'critical'
        receiver: 'slack-notifications'

      - matchers:
        - name: 'severity'
          vaue: 'error'
        receiver: 'slack-notifications'
...
```
