### ISSUE TITLE
additionalScrapeConfigs does not work

### ISSUE THREAD

**Issue by gadelkareem** [prometheus-operator/prometheus-operator#5172]
On a federated Prometheus setup, the central Prometheus and Prometheus Operator is in `monitor` namespace while my service is running in `scrapers` namespace. 

I am trying to add `static_config` to Prometheus:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myscraper
  name: myscraper
  namespace: scrapers
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9001
      targetPort: 9001
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: myscraper
  name: myscraper
  namespace: scrapers
subsets:
  - addresses:
      - ip: 10.0.0.1
    ports:
      - name: metrics
        port: 9001
        protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus-operator
    app: myscraper
  name: myscraper
  namespace: scrapers
spec:
  endpoints:
    - interval: 60s
      scrapeTimeout: 60s
      port: metrics
      honorLabels: true
      scheme: http
      path: /metrics
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: instance
          regex: '([^:]+)(:[0-9]+)?'
          replacement: '$1'
  namespaceSelector:
    matchNames:
      - scrapers
  selector:
    matchLabels:
      app: myscraper
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: myscraper
  labels:
    prometheus: prometheus
    release: prometheus-operator
    app: myscraper
  namespace: scrapers
spec:
  replicas: 2
  serviceMonitorSelector:
    matchLabels:
      app: myscraper
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    prometheus: prometheus
    release: prometheus-operator
    app: myscraper
  namespace: scrapers
  name: additional-scrape-configs
stringData:
  prometheus-additional.yaml: |
    - job_name: 'serviceMonitor/scrapers/myscraper/0'
      static_configs:
        - targets: [ "10.0.0.1:9001" ]
          labels:
            server: example.com
            env: dev

```
All config works but not the `additionalScrapeConfigs`
