### ISSUE TITLE
PodMonitor not showing up in Targets GUI - for Springboot

### ISSUE THREAD

**Issue by krishgu** [prometheus-operator/prometheus-operator#5193]
**What did you do?**
We have a setup of multiple microservices instrumented with Springboot actuator metrics, published on a pre-configured port at 8100. So given a pod with "label: my-app" has an IP, 192.168.1.2 -- http://192.168.1.2:8100/actuator/metrics from inside the cluster provides the metrics.

However, when we define a podMonitor for this pod with
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: my-app-pod-monitor
  namespace: prom
  labels:
    release: prom
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: my-app
  namespaceSelector:
    any: true
    matchNames:
    - "myapp-ns"
  podMetricsEndpoints:
  - targetPort: 8100
    path: /actuator/prometheus
```
- there is a new scrape config in the Prometheus config section. But there are no metrics, and it doesn't show in targets. 

```
- job_name: podMonitor/prom/my-app-pod-monitor/0
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /actuator/prometheus
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  ...
  - source_labels: [__meta_kubernetes_pod_label_app, __meta_kubernetes_pod_labelpresent_app]
    separator: ;
    regex: (my-app);true
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_container_port_number]
    separator: ;
    regex: "8100"
    replacement: $1
    action: keep
...
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: "8100"
    action: replace
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: ^prometheus$
    replacement: $1
    action: keep
...
  kubernetes_sd_configs:
  - role: pod
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
```

I have verified that:

1. the label on the podmonitor "release: prom" is accurate, and seeing logs in the prometheus-operator pod
2. the clusterrole from the helm-chart had only "nonResourceURLs" of /metrics. I had updated this for /actuator/metrics, and restarted prometheus. but still no joy
3. a separate service monitor works fine

**Questions**
* is it a clusterrole/crb issue? 
* do we need any type of relabel_configs added?
* does the pod need to expose 8100 in some type of configuration recognizable by prometheus configs?

**Did you expect to see some different?**
expect the pod to be scraped

**Environment**
non-prod

* Prometheus Operator version:
    * prometheus-operator/prometheus-operator:v0.60.1
    * chart=kube-prometheus-stack-42.0.0
    * prom version: prometheus/prometheus:v2.39.1
* Kubernetes version information:

   1.21.14

* Kubernetes cluster kind:

    kubeadm
* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by krishgu** [comment]
this is likely because these conditions aren't matching..  [kubernetes_sd_config doc](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config)

1. the port-number is not defined in the pod definition
2. the container-name is not prometheus

```yaml
  - source_labels: [__meta_kubernetes_pod_container_port_number]
    separator: ;
    regex: "8100"
    replacement: $1
    action: keep
...
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: ^prometheus$
    replacement: $1
    action: keep
```

how to remove the _pod_name filter or specify it in [podMetricsEndpoint](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.PodMetricsEndpoint) spec?

thanks again. much appreciated.
