### ISSUE TITLE
don't work  about web.enable-remote-write-receiver: true

### ISSUE THREAD

**Issue by jingslunt** [prometheus-operator/prometheus-operator#5204]
20221205
I had update prometheus-operator prometheuses crd
```
kubectl apply \
-f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml --force-conflicts=true --server-side
```

but found some error:
```
error: error validating "prometheus-crd-k8s.yaml": 
error validating data: ValidationError(Prometheus.spec.web): unknown field "enable-remote-write-receiver" in com.coreos.monitoring.v1.Prometheus.spec.web; if you choose to ignore these errors, turn validation off with --validate=false
```

some config:

```
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
  generation: 2
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  enableFeatures:
  - remote-write-receiver
  enableRemoteWriteReceiver: true
  web:
    enable-remote-write-receiver: true
...
```

what's wrong

**Comment by jingslunt** [comment]
it does not work too
```
spec:
  enableFeatures:
  - remote-write-receiver
  externalLabels: 
    web.enable-remote-write-receiver: "true"
```

**Comment by simonpasquier** [comment]
This should work:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  enableRemoteWriteReceiver: true
```
