### ISSUE TITLE
Duplicate targets created for pods with multiple containers

### ISSUE THREAD

**Issue by ariep** [prometheus-operator/prometheus-operator#5230]
**What happened?**
When using a PodMonitor with a pod that has two containers, prometheus creates two mostly identical targets for this single pod. The two differ only in the `container` label. This has the effect that the pod is scraped twice as often compared to the specified `interval`.

**Did you expect to see something different?**
Yes, I expected a single pod to result in a single target.

**How to reproduce it (as minimally and precisely as possible)**:
Use any pod with two containers, and a very basic PodMonitor that selects that single pod, targeting a metrics endpoint served by one of the two containers (see manifest below).

**Environment**

* Prometheus Operator version: v0.60.1
* Kubernetes version information:

```
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:12:04Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: kubespray
* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: exim
  namespace: default
spec:
  namespaceSelector:
    matchNames:
    - default
  podMetricsEndpoints:
  - interval: 5m
    metricRelabelings:
    - action: keep
      regex: exim_.*
      sourceLabels:
      - __name__
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: mail-server
      app.kubernetes.io/name: exim
```

* Prometheus Operator Logs: I couldn't find anything relevant in the logs

**Anything else we need to know?**:

This is not a big problem as the effect of a higher scrape frequency is not terrible, but it's still confusing, and also surprising as pods with multiple containers are quite common. Maybe I'm missing a possibility to configure the PodMonitor to select only a single container? Even so, as default this prometheus behaviour is not very useful as both containers in a pod will respond with the same metrics anyway, given that they share a network namespace and prometheus uses the same single port that's specified in the PodMonitor.

**Comment by JoaoBraveCoding** [comment]
Disclaimer: I'm not a maintainer 

> Even so, as default this prometheus behaviour is not very useful as both containers in a pod will respond with the same metrics anyway, given that they share a network namespace and prometheus uses the same single port that's specified in the PodMonitor.

Maybe I misunderstood something, but so here the use case is that you have a pod running two containers that are exactly the same? I got this impression because you said that the metrics reported are the same.
If this is your case couldn't it be averted by just running one container in the pods and scaling that pod to two replicas?

Now if that's not your problem I don't think that there is a feature in PodMonitor to select only a container. And I do agree that if you are getting all the metrics from a Pod and are only interested in a subset that this might be something we could improve on.

**Comment by simonpasquier** [comment]
can you share the definition of the pod/deployment? 

Also `interval: 5m` isn't really recommended. Given that Prometheus has a default staleness value of 5m, you might see gaps in your graphs (if Prometheus scrapes only 1 container).

**Comment by ariep** [comment]
> Maybe I misunderstood something, but so here the use case is that you have a pod running two containers that are exactly the same? [...]

No. It's two different containers: one is exim (mail server) that does the actual work; the other is a "sidecar" container which only exists to expose prometheus metrics based on the exim log files. The reason that "both containers result in the same metrics" is that actually containers in a pod share their network namespace, so rather than prometheus targeting a single container, it targets the pod as a whole and in both cases it's the sidecar container that answers, because that listens on the port specified in the PodMonitor.

> Now if that's not your problem I don't think that there is a feature in PodMonitor to select only a container. And I do agree that if you are getting all the metrics from a Pod and are only interested in a subset that this might be something we could improve on.

Well, given the above it doesn't make a lot of sense to "select a container", but instead prometheus should understand that it's no use scraping two containers in the same pod, and should only scrape each selected pod once.

> can you share the definition of the pod/deployment?

I've pasted a redacted version below. The exim container is a custom one that's not available online so it's not readily runnable as-is anyway, sorry. I don't think it really matters what the deployment looks like exactly as long as it has two containers, though admittedly that's an assumption based on my theory of what's going on.

```
apiVersion: apps/v1
kind: Deployment
  labels:
    app.kubernetes.io/instance: mail-server
    app.kubernetes.io/name: exim
  name: exim
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mail-server
      app.kubernetes.io/name: exim
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mail-server
        app.kubernetes.io/name: exim
    spec:
      containers:
      - env: [...]
        image: [...]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 60
          successThreshold: 1
          tcpSocket:
            port: smtp
          timeoutSeconds: 1
        name: exim
        ports:
        - containerPort: 25
          name: smtp
          protocol: TCP
        - containerPort: 465
          name: ssmtp
          protocol: TCP
        - containerPort: 587
          name: submission
          protocol: TCP
        - containerPort: 9636
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: smtp
          timeoutSeconds: 1
        volumeMounts: [...]
      - args:
        - --log.level=debug
        image: gvengel/exim_exporter:1.4.1
        imagePullPolicy: IfNotPresent
        name: exim-prometheus
        ports:
        - containerPort: 9636
          name: metrics
          protocol: TCP
        volumeMounts: [...]
      securityContext:
        fsGroup: 101
        fsGroupChangePolicy: Always
      shareProcessNamespace: true
      volumes: [...]
```

> Also interval: 5m isn't really recommended. Given that Prometheus has a default staleness value of 5m, you might see gaps in your graphs (if Prometheus scrapes only 1 container).

Oh that's good to know, thanks.

**Comment by simonpasquier** [comment]
The operator and Prometheus do what you asked for. Both containers have a `metrics` port... I suppose that you want to remove the metrics port on the first container?

```
    spec:
      containers:
      - name: exim
        ports:
        - containerPort: 9636
          name: metrics
          protocol: TCP
      - name: exim-prometheus
        ports:
        - containerPort: 9636
          name: metrics
          protocol: TCP
```
