### ISSUE TITLE
Panic processing AlertmanagerConfig values for Pushover

### ISSUE THREAD

**Issue by martafolf** [prometheus-operator/prometheus-operator#5234]
**What happened?**

When modifying values to the `priority` field of a Pushover config in Alertmanager using the AlertmanagerConfig resource, the operator experiences a panic according to the logs and crashes upon attempting to sync the configuration. 

**Did you expect to see something different?**

The configuration to be applied as defined in the resource. 

**How to reproduce it (as minimally and precisely as possible)**:

Apply a sample resource to edit the Alertmanager configuration, to note, the `priority` field is in use and defined: 
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    alertmanagerConfig: config
  name: alertmanager-config
  namespace: monitoring
spec:
  receivers:
    - name: pushover
      pushoverConfigs:
        - token:
            key: token
            name: pushover-config
          userKey:
            key: userkey
            name: pushover-config
        - priority: '2'
  route:
    groupBy:
      - job
    groupInterval: 5m
    groupWait: 30s
    receiver: pushover
    repeatInterval: 24h
```

View the logs of the operator and note the crash during the next attempted sync. 

**Environment**

* Prometheus Operator version:
*
From describe command: `Image:      quay.io/prometheus-operator/prometheus-operator:v0.61.1`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-0
9T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+k3s1", GitCommit:"0dc63334c0db3e7b99244427615e091909fc486e", GitTreeState:"clean", BuildDate:"2022
-11-18T18:17:40Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

Basic k3s dev cluster with three nodes, all masters and schedulable. Very few other notable modifications thus far, more or less exact to the latest official k3s install guide. Longhorn for storage. 

* Manifests:

Used the quick start guide of the prometheus operator, no notable changes. 

* Prometheus Operator Logs:

```
level=info ts=2022-12-20T21:11:27.435969633Z caller=main.go:220 msg="Starting Prometheus Operator" version="(version=0.61.1, branch=refs/tags/v0.61.1, revision=bbd7400711a99eda6c140c31e17f770355617b66)"
level=info ts=2022-12-20T21:11:27.436104811Z caller=main.go:221 build_context="(go=go1.19.3, user=Action-Run-ID-3542121197, date=20221124-16:02:08)"
level=warn ts=2022-12-20T21:11:27.470448137Z caller=operator.go:332 component=prometheusoperator msg="failed to check if the API supports the endpointslice resources" err="converting (v1.APIGroup) to (v1.APIResourceList): unknown conversion"
level=info ts=2022-12-20T21:11:27.47055461Z caller=operator.go:334 component=prometheusoperator msg="Kubernetes API capabilities" endpointslices=false
level=info ts=2022-12-20T21:11:27.47203807Z caller=main.go:103 msg="Starting insecure server on [::]:8080"
level=info ts=2022-12-20T21:11:27.472865544Z caller=operator.go:457 component=alertmanageroperator msg="connection established" cluster-version=v1.25.4+k3s1
level=info ts=2022-12-20T21:11:27.472918826Z caller=operator.go:466 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2022-12-20T21:11:27.472991023Z caller=operator.go:434 component=prometheusoperator msg="connection established" cluster-version=v1.25.4+k3s1
level=info ts=2022-12-20T21:11:27.473024346Z caller=operator.go:443 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2022-12-20T21:11:27.47481379Z caller=operator.go:310 component=thanosoperator msg="connection established" cluster-version=v1.25.4+k3s1
level=info ts=2022-12-20T21:11:27.474888732Z caller=operator.go:319 component=thanosoperator msg="CRD API endpoints ready"
level=info ts=2022-12-20T21:11:27.775019209Z caller=operator.go:373 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2022-12-20T21:11:27.77537185Z caller=operator.go:297 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2022-12-20T21:11:27.776824733Z caller=operator.go:271 component=thanosoperator msg="successfully synced all caches"
level=info ts=2022-12-20T21:11:27.777271333Z caller=operator.go:1326 component=prometheusoperator key=monitoring/k8s msg="update prometheus status"
level=info ts=2022-12-20T21:11:27.777403934Z caller=operator.go:1162 component=prometheusoperator key=monitoring/k8s msg="sync prometheus"
level=info ts=2022-12-20T21:11:27.777630736Z caller=operator.go:638 component=alertmanageroperator key=monitoring/main msg="sync alertmanager"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x188ea43]

goroutine 156 [running]:
github.com/prometheus-operator/prometheus-operator/pkg/alertmanager.(*configBuilder).convertPushoverConfig(0xc00177e978, {0x2389b48, 0xc0000b4840}, {0x0, 0x0, 0x0, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/alertmanager/amcfg.go:982 +0x1a3
github.com/prometheus-operator/prometheus-operator/pkg/alertmanager.(*configBuilder).convertReceiver(0xc0003aa4b0?, {0x2389b48, 0xc0000b4840}, 0xc00177e608, {{0xc000f1c070?, 0x0?}, {0xc000581f08?, 0x2373048?}})
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/alertmanager/amcfg.go:540 +0x152d
github.com/prometheus-operator/prometheus-operator/pkg/alertmanager.(*configBuilder).initializeFromAlertmanagerConfig(0xc00177e978, {0x2389b48, 0xc0000b4840}, 0x0?, 0xc0013c6f20)
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/alertmanager/amcfg.go:235 +0x4b7
github.com/prometheus-operator/prometheus-operator/pkg/alertmanager.(*Operator).provisionAlertmanagerConfiguration(0xc00010f200, {0x2389b48, 0xc0000b4840}, 0xc00077d000, 0xc0006f2d20)
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/alertmanager/operator.go:859 +0x51c
github.com/prometheus-operator/prometheus-operator/pkg/alertmanager.(*Operator).sync(0xc00010f200, {0x2389b48, 0xc0000b4840}, {0xc001163f50, 0xf})
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/alertmanager/operator.go:642 +0x5ea
github.com/prometheus-operator/prometheus-operator/pkg/alertmanager.(*Operator).Sync(0xc00010f200, {0x2389b48?, 0xc0000b4840?}, {0xc001163f50, 0xf})
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/alertmanager/operator.go:606 +0x32
github.com/prometheus-operator/prometheus-operator/pkg/operator.(*ResourceReconciler).processNextReconcileItem(0xc00014b6c0, {0x2389b48, 0xc0000b4840})
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/operator/resource_reconciler.go:391 +0x230
github.com/prometheus-operator/prometheus-operator/pkg/operator.(*ResourceReconciler).Run.func1()
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/operator/resource_reconciler.go:354 +0x45

```

**Anything else we need to know?**:

Happy to aide in any further debug steps.

**Comment by marcoslater** [comment]
I've looked a little further into this with some help, it looks like my YAML was incorrect whereby it defined a new set of pushoverConfigs, rather than appending to the existing one, the fix was to not have the "-" at the start, example: 
```
  receivers:
    - name: pushover
      pushoverConfigs:
        - token:
            key: token
            name: pushover-config
          userKey:
            key: userkey
            name: pushover-config
          priority: '{{ if eq .Status "firing" }}1{{ else }}0{{ end }}'
```

The operator crashing at the prospect of being given a pushover configuration with all empty fields except for priority makes sense. However, that being said, my wrongful YAML should have failed validation, as it would have been a new config with just a priority field, and none of the more essential fields like token and userkey.

In light of that I'd like to change this issue to be a validation bug rather than a crash.
