### ISSUE TITLE
About slack notification method

### ISSUE THREAD

**Issue by jo-jo-1217** [prometheus-operator/prometheus-operator#5246]
**What did you do?**
I want to notify slack using prometheus-operator and alert-manager.

I built prometheus-operator and alert-manager this way.
```
$ helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
$ helm install -f values.yaml prometheus-stack prometheus-community/kube-prometheus-stack -n monitoring
$ kubectl apply -f ingress.yaml
```

values.yaml
```
prometheus:
  service:
    type: NodePort
alertmanager:
  service:
    type: NodePort

  enabled: true

  serviceAccount:
    create: false
    name: ""

  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    maxUnavailable: ""

  config:
    global:
      resolve_timeout: 5m
      slack_api_url: "https://hooks.slack.com/services/~~~"
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      #receiver: 'slack'
      routes:
      - match:
          alertname: DeadMansSwitch
        receiver: 'null'
      - match:
        receiver: 'slack'
        continue: true
    receivers:
    - name: 'null'
    - name: 'slack'
      slack_configs:
      - channel: '#test-slack'
        send_resolved: false
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            *Description:* {{ .Annotations.description }}
            *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
```

Where are the missing settings in values.yaml?
Also, are there any settings to easily detect alerts?

**Environment**

* Prometheus Operator version:

    `42.1.1`
