### ISSUE TITLE
Support Discord Intergration with AlertmanagerConfig CRD

### ISSUE THREAD

**Issue by slashpai** [prometheus-operator/prometheus-operator#5251]
**What is missing?**

Alertmanager version `0.25` is released with [Discord](https://discord.com/) integration. It would be nice to support that in prometheus-operator

https://github.com/prometheus/alertmanager/pull/2948

**Why do we need it?**

Feature Parity

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

NA

**Anything else we need to know?**:

discord integration is not yet documented yet in alertmanager documentation but https://promlabs.com/blog/2022/12/23/sending-prometheus-alerts-to-discord-with-alertmanager-v0-25-0 gives overview on it

**Comment by simonpasquier** [comment]
@guitcastro nope

**Comment by serejke** [comment]
If you're using the community [Helm charts](https://github.com/prometheus-community/helm-charts), a workaround for now is to override [`alertmanager.config`](https://github.com/prometheus-community/helm-charts/blob/78e0e2ab08c5423a743b01bc565fd24ff5eec8b4/charts/kube-prometheus-stack/values.yaml#L177) value. This allows to override raw Alertmanager configuration bypassing the `AlertmanagerConfig` CRD's schema validation.

Create a file `prometheus-stack-values.yaml` with the following content:
```
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
    route:
      group_by: [ 'alertname', 'job' ]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: discord
    receivers:
      - name: discord
        discord_configs:
          - webhook_url: 'https://discord.com/api/webhooks/<WEB_HOOK_TOKEN>'
      - name: 'null'
    templates:
      - '/etc/alertmanager/config/*.tmpl'
```

then in order to install the Helm chart:
```
helm install prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring --values .config/prometheus-stack-values.yaml
```
