### ISSUE TITLE
Improved ServiceMonitor sanity checking

### ISSUE THREAD

**Issue by plaes** [prometheus-operator/prometheus-operator#5258]
Current ServiceMonitor parser does not seem to do much sanity checking of its inputs allowing following messed up `endpoints` configuration:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  ...
spec:
  endpoints:
  - interval: 15s
    port: prom-metrics
  - basicAuth:
      password:
        key: password
        name: appx-metrics-access
      username:
        key: user
        name: appx-metrics-access
  selector:
    matchLabels:
      app: appx
```
**What is missing?**

Sanity check for `/spec/endpoints` children.

**Why do we need it?**

Better error messages :)

* Prometheus Operator version:
prometheus-operator:v0.61.1 + kube-prometheus-stack 43.x
