### ISSUE TITLE
Missing validation for AlertManagerConfigSpec.Route and AlertManagerConfigSpec.Route.Matcher object fields

### ISSUE THREAD

**Issue by plaes** [prometheus-operator/prometheus-operator#5275]
Seems like prometheus operator 0.61.1 happily validates following `AlertManagerConfig` definition:
```
# alertmanager-broken-example.yaml
---
apiVersion: monitoring.coreos.com/v1beta1 # or v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: monitoring
spec:
  route:
    routes:
    - matchers:
      - matchType: =
        xname: alertname                    # unknown field
        xvalue: lockout_threshold_alert     # unknown field
      xreceiver: send_mail                  # unknown field
      repeatIinterval: 24h                  # unknown field
      continue: yes                         # should only accept true/false
```

**Did you expect to see something different?**

Validation failure.

**How to reproduce it (as minimally and precisely as possible)**:

Save provided configuration as `alertmanager-broken-example.yaml` and attempt to validate against the server where AlertManagerConfig CRD is installed:
`kubectl apply --validate=true --dry-run='server' -f alertmanager-broken-example.yaml`

**Environment**

kube-prometheus-stack-43.2.1

* Prometheus Operator version:

prometheus-operator:v0.61.1

* Kubernetes version information:

```
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.24.6
```

* Kubernetes cluster kind:

Azure AKS
