### ISSUE TITLE
PodMonitors are shown multiple times with default path /metrics

### ISSUE THREAD

**Issue by b3n3w** [prometheus-operator/prometheus-operator#5277]
**What did you do?**

Hi there,

i've deployed the following podmonitor where the target path is changed from `/metrics` to `api/v1/metrics/prometheus`. The podmonitors are then correctly set once in the prometheus targets, but also again with the default metrics endpoint /metrics.
Is there any option to disable this behaviour ? 

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fluentbit
  labels:
    name: fluentbit
spec:
  namespaceSelector:
    matchNames:
      - observability
  selector:
    matchLabels:
      k8s-app: fluent-bit-compatible
  podMetricsEndpoints:
  - honorLabels: true
  - targetPort: metrics
  - path: /api/v1/metrics/prometheus
  - interval: 15s
```
Example target:

TARGET                                                                     STATE
http://10.1.152.69:2020/api/v1/metrics/prometheus      UP
http://10.1.152.69:2020/metrics                                  DOWN

**Did you expect to see some different?**

PodMonitors should be only detected for the given path.

**Environment**

* Prometheus Operator version:
    `quay.io/prometheus-operator/prometheus-operator - v0.58.0`

* Kubernetes version information:
    `v1.23`
* Kubernetes cluster kind:
    AWS EKS

**Comment by simonpasquier** [comment]
you've declared 4 endpoints, you probably want
```

  podMetricsEndpoints:
  - honorLabels: true
    targetPort: metrics
    path: /api/v1/metrics/prometheus
    interval: 15s
```

**Comment by b3n3w** [comment]
Thanks for your reply ! Could you please explain where i've declared 4 endpoints ?

**Comment by simonpasquier** [comment]
You have 4 items under podMetricsEndpoints. Compare

```
  podMetricsEndpoints:
  - honorLabels: true
  - targetPort: metrics
  - path: /api/v1/metrics/prometheus
  - interval: 15s
```

with

```
  podMetricsEndpoints:
  - honorLabels: true
    targetPort: metrics
    path: /api/v1/metrics/prometheus
    interval: 15s
```
