### ISSUE TITLE
Help  Service Monitor Token Authentication

### ISSUE THREAD

**Issue by leandromoreirati** [prometheus-operator/prometheus-operator#5315]
**What did you do?**

Hi everyone!

I'm doing labs with prometheus to monitoring jenkins and Ansible AWX.

With Jenkins Its OK becouse o endpoint no need authentication, but AWX need pass a token for authenticate.

I created the a secret with the token generated and in the ServiceMonitor I pass bearerTokensecret, 

```yaml
---
apiVersion: v1
metadata:
  name: awx-api-token
  namespace: monitoring
data:
  token: WHBJT0xqN2dQaDRKRHROTEFxbEJrb3J4ck5UbnhvCg==
kind: Secret
```

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx
    release: prometheus-stack
  name: awx
  namespace: monitoring
spec:
  endpoints:
    - interval: 5s
      path: /api/v2/metrics/
      targetPort: 80
      port: http
      scheme: http
      tlsConfig:
        insecureSkipVerify: true
      bearerTokenSecret:
        key: token
        name: awx-api-token
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/component: awx
      app.kubernetes.io/managed-by: awx-operator
      app.kubernetes.io/name: awx
      release: prometheus-stack
```

On the target page in the prometheus ,I receive erro 401 "invalid header field value for Authorization"

![image](https://user-images.githubusercontent.com/30784301/216203967-975d2b75-1a14-4cf4-a666-650580aecf1b.png)

I already research and test several possibilities to correct this, but nothing it worked.

Anyone can I help me?

**Environment**
```
kind version 0.14.0
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDate:"2022-09-02T00:00:59Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

* Prometheus Operator version:

```
ame:                   prometheus-stack-kube-prom-operator
Namespace:              monitoring
CreationTimestamp:      Mon, 30 Jan 2023 01:14:59 +0000
Labels:                 app=kube-prometheus-stack-operator
                        app.kubernetes.io/instance=prometheus-stack
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/part-of=kube-prometheus-stack
                        app.kubernetes.io/version=44.3.0
                        chart=kube-prometheus-stack-44.3.0
                        heritage=Helm
                        release=prometheus-stack
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: prometheus-stack
                        meta.helm.sh/release-namespace: monitoring
Selector:               app=kube-prometheus-stack-operator,release=prometheus-stack
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=kube-prometheus-stack-operator
                    app.kubernetes.io/instance=prometheus-stack
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/part-of=kube-prometheus-stack
                    app.kubernetes.io/version=44.3.0
                    chart=kube-prometheus-stack-44.3.0
                    heritage=Helm
                    release=prometheus-stack
  Service Account:  prometheus-stack-kube-prom-operator
  Containers:
   kube-prometheus-stack:
    Image:      quay.io/prometheus-operator/prometheus-operator:v0.62.0
    Port:       10250/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/prometheus-stack-kube-prom-kubelet
      --localhost=127.0.0.1
      --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.62.0
      --config-reloader-cpu-request=200m
      --config-reloader-cpu-limit=200m
      --config-reloader-memory-request=50Mi
      --config-reloader-memory-limit=50Mi
      --thanos-default-base-image=quay.io/thanos/thanos:v0.30.1
      --web.enable-tls=true
      --web.cert-file=/cert/cert
      --web.key-file=/cert/key
      --web.listen-address=:10250
      --web.tls-min-version=VersionTLS13
    Environment:  <none>
    Mounts:
      /cert from tls-secret (ro)
  Volumes:
   tls-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-stack-kube-prom-admission
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-stack-kube-prom-operator-7c9974695c (1/1 replicas created)
Events:          <none>
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDate:"2022-09-02T00:00:59Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    My cluster deployed with kind + terraform

* Manifests:

````
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-api-token
  namespace: monitoring
type: Opaque
data:
  token: THJPZ1JmMnNOcTBqOTVicEtyRlBGWm9hT3h2Q0tnCg==
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx
    release: prometheus-stack
    prometheus: "true"
  name: awx-servicemonitor
  namespace: monitoring
spec:
  jobLabel: "kubernetes-service-endpoints"
  endpoints:
    - interval: 5s
      path: /api/v2/metrics/
      port: http
      scheme: http
      tlsConfig:
        insecureSkipVerify: true
      bearerTokenSecret:
        key: token 
        name: awx-api-token
  namespaceSelector:
    matchNames:
      - awx
  selector:
    matchLabels:
      app.kubernetes.io/name: awx
```
```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:
```
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:13.3291576Z caller=operator.go:638 component=alertmanageroperator key=monitoring/prometheus-stack-kube-prom-alertmanager msg="sync alertmanager"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:13.6145962Z caller=operator.go:1330 component=prometheusoperator key=monitoring/prometheus-stack-kube-prom-prometheus msg="update prometheus status"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:13.8458562Z caller=operator.go:638 component=alertmanageroperator key=monitoring/prometheus-stack-kube-prom-alertmanager msg="sync alertmanager"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:13.8669104Z caller=operator.go:1162 component=prometheusoperator key=monitoring/prometheus-stack-kube-prom-prometheus msg="sync prometheus"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:14.190952Z caller=operator.go:1330 component=prometheusoperator key=monitoring/prometheus-stack-kube-prom-prometheus msg="update prometheus status"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:14.4788643Z caller=operator.go:1162 component=prometheusoperator key=monitoring/prometheus-stack-kube-prom-prometheus msg="sync prometheus"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:14.4862156Z caller=operator.go:638 component=alertmanageroperator key=monitoring/prometheus-stack-kube-prom-alertmanager msg="sync alertmanager"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:14.7582385Z caller=operator.go:1330 component=prometheusoperator key=monitoring/prometheus-stack-kube-prom-prometheus msg="update prometheus status"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:15.008632Z caller=operator.go:638 component=alertmanageroperator key=monitoring/prometheus-stack-kube-prom-alertmanager msg="sync alertmanager"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:15.0149425Z caller=operator.go:1162 component=prometheusoperator key=monitoring/prometheus-stack-kube-prom-prometheus msg="sync prometheus"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:15.3412302Z caller=operator.go:1330 component=prometheusoperator key=monitoring/prometheus-stack-kube-prom-prometheus msg="update prometheus status"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:19.0728259Z caller=operator.go:638 component=alertmanageroperator key=monitoring/prometheus-stack-kube-prom-alertmanager msg="sync alertmanager"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:19.072853Z caller=operator.go:1162 component=prometheusoperator key=monitoring/prometheus-stack-kube-prom-prometheus msg="sync prometheus"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:19.3712935Z caller=operator.go:1330 component=prometheusoperator key=monitoring/prometheus-stack-kube-prom-prometheus msg="update prometheus status"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:19.6829897Z caller=operator.go:638 component=alertmanageroperator key=monitoring/prometheus-stack-kube-prom-alertmanager msg="sync alertmanager"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:19.6956805Z caller=operator.go:1162 component=prometheusoperator key=monitoring/prometheus-stack-kube-prom-prometheus msg="sync prometheus"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:19.9649391Z caller=operator.go:1330 component=prometheusoperator key=monitoring/prometheus-stack-kube-prom-prometheus msg="update prometheus status"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:20.1832521Z caller=operator.go:1162 component=prometheusoperator key=monitoring/prometheus-stack-kube-prom-prometheus msg="sync prometheus"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:20.1876592Z caller=operator.go:638 component=alertmanageroperator key=monitoring/prometheus-stack-kube-prom-alertmanager msg="sync alertmanager"
prometheus-stack-kube-prom-operator-7c9974695c-6wss8 kube-prometheus-stack level=info ts=2023-01-30T02:06:20.541789Z caller=operator.go:1330 component=prometheusoperator key=monitoring/prometheus-stack-kube-prom-prometheus msg="update prometheus status"
```
```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
