### ISSUE TITLE
Service Monitor not found - Troubleshooting guide not helping

### ISSUE THREAD

**Issue by rufreakde** [prometheus-operator/prometheus-operator#5332]
**What did you do?**
Deployed Prometheus Operator `kube-prometheus-stack:44.4.1` helm chart with these settings in the values.yaml 
Deployed a simple ServiceMonitor in another namespace:
Followed troubleshooting guide: https://prometheus-operator.dev/docs/operator/troubleshooting/#troubleshooting-servicemonitor-changes 

Checked ClusterRoleBindings seem to be fine.
No Errors in any Prometheus Pod.
Used command to check if Servicemonitor is found from troubleshooting guide:
```
# kubectl -n monitoring get secret prometheus-up-monitoring-kube-prometh-prometheus -ojson | jq -r '.data["prometheus.yaml.gz"]' | base64 -d | gunzip | grep "job_name: serviceMonitor" 
# (sllightly modified comand, also tried with name of servicemonitor it was empty)
>>>
- job_name: serviceMonitor/up-monitoring/up-monitoring-kube-prometh-alertmanager/0
- job_name: serviceMonitor/up-monitoring/up-monitoring-kube-prometh-apiserver/0
- job_name: serviceMonitor/up-monitoring/up-monitoring-kube-prometh-coredns/0
- job_name: serviceMonitor/up-monitoring/up-monitoring-kube-prometh-kube-controller-manager/0
- job_name: serviceMonitor/up-monitoring/up-monitoring-kube-prometh-kube-etcd/0
- job_name: serviceMonitor/up-monitoring/up-monitoring-kube-prometh-kube-proxy/0
- job_name: serviceMonitor/up-monitoring/up-monitoring-kube-prometh-kube-scheduler/0
- job_name: serviceMonitor/up-monitoring/up-monitoring-kube-prometh-kubelet/0
- job_name: serviceMonitor/up-monitoring/up-monitoring-kube-prometh-kubelet/1
- job_name: serviceMonitor/up-monitoring/up-monitoring-kube-prometh-kubelet/2
- job_name: serviceMonitor/up-monitoring/up-monitoring-kube-prometh-operator/0
- job_name: serviceMonitor/up-monitoring/up-monitoring-kube-prometh-prometheus/0
- job_name: serviceMonitor/up-monitoring/up-monitoring-kube-state-metrics/0
- job_name: serviceMonitor/up-monitoring/up-monitoring-prometheus-node-exporter/0

```
**Did you expect to see some different?**
ServiceMonitor from other namespace to be listed.

**Environment**

* Prometheus Operator version:

    `sha256:2038e399c368564b595732c55cbc3982e4e46f3bcd6f5fce64f3899a4488cb6e`
     https://github.com/prometheus-community/helm-charts/commit/68fed06f23d769f10ccc9db9a5dea593285eaa79
     quay.io/prometheus-operator/prometheus-operator:v0.62.0

* Kubernetes version information:

    `Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.22.17`

* Kubernetes cluster kind:

    insert how you created your cluster: AWS

* Manifests:
### values.yaml of helm chart
```yaml
grafana:
  enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}

prometheusOperator:
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false
```
### Servicemonitor
```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-name
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: {{ .Values.service.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  endpoints:
    - honorLabels: true
      interval: 1m
      path: /metrics
      port: http
      scheme: http
      scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  labels:
    app: {{ .Values.service.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.internalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.externalPort }} 
  selector:
    app: {{ .Values.service.name }} 
  type: ClusterIP
```

* Prometheus Operator Logs:

```
level=info ts=2023-02-10T11:08:19.301618004Z caller=main.go:220 msg="Starting Prometheus Operator" version="(version=0.62.0, branch=refs/tags/v0.62.0, revision=21147bd93fa83f01b3fbf1542015d3508962561a)"
level=info ts=2023-02-10T11:08:19.30166125Z caller=main.go:221 build_context="(go=go1.19.4, user=Action-Run-ID-3848028368, date=20230105-15:39:52)"
level=warn ts=2023-02-10T11:08:19.318054673Z caller=operator.go:332 component=prometheusoperator msg="failed to check if the API supports the endpointslice resources" err="converting (v1.APIGroup) to (v1.APIResourceList): unknown conversion"
level=info ts=2023-02-10T11:08:19.318101849Z caller=operator.go:334 component=prometheusoperator msg="Kubernetes API capabilities" endpointslices=false
level=info ts=2023-02-10T11:08:19.319796222Z caller=main.go:103 msg="Starting insecure server on :8080"
level=info ts=2023-02-10T11:08:19.322230897Z caller=operator.go:310 component=thanosoperator msg="connection established" cluster-version=v1.22.17
level=info ts=2023-02-10T11:08:19.322245398Z caller=operator.go:434 component=prometheusoperator msg="connection established" cluster-version=v1.22.17
level=info ts=2023-02-10T11:08:19.32226675Z caller=operator.go:319 component=thanosoperator msg="CRD API endpoints ready"
level=info ts=2023-02-10T11:08:19.32226727Z caller=operator.go:443 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2023-02-10T11:08:19.3225538Z caller=operator.go:457 component=alertmanageroperator msg="connection established" cluster-version=v1.22.17
level=info ts=2023-02-10T11:08:19.322589777Z caller=operator.go:466 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2023-02-10T11:08:19.423901759Z caller=operator.go:297 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2023-02-10T11:08:19.424128496Z caller=operator.go:638 component=alertmanageroperator key=up-monitoring/up-monitoring-kube-prometh-alertmanager msg="sync alertmanager"
level=info ts=2023-02-10T11:08:19.424869113Z caller=operator.go:373 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2023-02-10T11:08:19.42495299Z caller=operator.go:1330 component=prometheusoperator key=up-monitoring/up-monitoring-kube-prometh-prometheus msg="update prometheus status"
level=info ts=2023-02-10T11:08:19.425036657Z caller=operator.go:1162 component=prometheusoperator key=up-monitoring/up-monitoring-kube-prometh-prometheus msg="sync prometheus"
level=info ts=2023-02-10T11:08:19.425040335Z caller=operator.go:1352 component=prometheusoperator key=up-monitoring/up-monitoring-kube-prometh-prometheus statefulset=up-monitoring/prometheus-up-monitoring-kube-prometh-prometheus shard=0 msg="not found"
level=info ts=2023-02-10T11:08:19.49115005Z caller=operator.go:638 component=alertmanageroperator key=up-monitoring/up-monitoring-kube-prometh-alertmanager msg="sync alertmanager"
level=info ts=2023-02-10T11:08:19.52849707Z caller=operator.go:271 component=thanosoperator msg="successfully synced all caches"
level=info ts=2023-02-10T11:08:19.563811394Z caller=operator.go:638 component=alertmanageroperator key=up-monitoring/up-monitoring-kube-prometh-alertmanager msg="sync alertmanager"
level=info ts=2023-02-10T11:08:19.628266212Z caller=operator.go:638 component=alertmanageroperator key=up-monitoring/up-monitoring-kube-prometh-alertmanager msg="sync alertmanager"
level=info ts=2023-02-10T11:08:19.663836173Z caller=operator.go:1162 component=prometheusoperator key=up-monitoring/up-monitoring-kube-prometh-prometheus msg="sync prometheus"
level=info ts=2023-02-10T11:08:19.663901763Z caller=operator.go:1330 component=prometheusoperator key=up-monitoring/up-monitoring-kube-prometh-prometheus msg="update prometheus status"
level=info ts=2023-02-10T11:08:19.66401608Z caller=operator.go:1352 component=prometheusoperator key=up-monitoring/up-monitoring-kube-prometh-prometheus statefulset=up-monitoring/prometheus-up-monitoring-kube-prometh-prometheus shard=0 msg="not found"
level=info ts=2023-02-10T11:08:19.676255652Z caller=operator.go:638 component=alertmanageroperator key=up-monitoring/up-monitoring-kube-prometh-alertmanager msg="sync alertmanager"
Stream closed EOF for up-monitoring/up-monitoring-kube-prometh-operator-66dfd5fd-k4t5v (kube-prometheus-stack)

```

**Anything else we need to know?**:
Before installing the `Operator` Chart we uninstalled a previously running `Prometheus` Chart.

**Comment by rufreakde** [comment]
So I duplicated now another service monitor and deployed it into the `monitoring` namespace - as I thought that maybe it is namespace dependent but even there the new serviceMonitor is not picked up.

All serviceMonitors created are ignored by the Prometheus Operator there are not even logs showing if it "saw" them.

**Comment by rufreakde** [comment]
# Solution:

So the issue is that in version 44.1.7 of the operator chart the `{}`is not used correctly for the `serviceMeshSelector`!

To fix this I just set it explicitly! This is a bug for sure! As it should work as mentioned here: https://github.com/prometheus-operator/prometheus-operator/issues/731#issuecomment-371412289 
```
        prometheus:
          prometheusSpec:
            serviceMonitorNamespaceSelector: {}
            serviceMonitorSelector:
              matchExpressions:
                - {key: app, operator: Exists}

```
