### ISSUE TITLE
How to edit remote_write  to use Victoriametrics?

### ISSUE THREAD

**Issue by giz33** [prometheus-operator/prometheus-operator#5341]
Hi everyone, I just installed the kube prometheus on my environment and now I have Victoria Metrics installed and want to connect my operator on it.
I tried to search for a configmap where I can edit the prometheus.yaml and put the remote_write  section but I didn't find it.
How can I customize my existing and configured kube prometheus operator to point to my victoria metrics without losing my applied custom configs such as rules and etc.

Thanks a lot.

**Comment by JoaoBraveCoding** [comment]
I'm not sure I fully understand the ask, but you can configure RemoteWrite for prometheus using the Prometheus CRD under `spec.remoteWrite` 

https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.RemoteWriteSpec

**Comment by giz33** [comment]
Hi João, thanks for the answer.
Yes, is that I need.
But I already have an installed kube-prometheus, I need to change this parameter without losing all my earlier configs.
Where I can put this parameter and how I can apply it?
I edited the manifest prometheus-prometheus.yaml putting the following lines on it:

version: v2.22.1
  remoteWrite:
  - url: "<Your Metrics instance remote_write endpoint>"
And them I applied with kubectl apply -f prometheus-prometheus.yaml -n monitoring.

After this I check my operator(prometheus) with :
kubectl edit prometheus k8s -n monitoring

And the lines I edited was there, but when I go look inside my PODS of prometheus, there isn't any modifications on prometheus.yml at all.

So, backing to my original question: How can I change this parameter and apply it formally without losing any of my earlier configurations like rules configured, I mean, without need to reconfigure all my prometheus?

For reference I'm trying to execute the following procedure to connect my prometheus to my VictoriaMetrics:
https://grafana.com/docs/grafana-cloud/kubernetes-monitoring/other-methods/prometheus/remote_write_operator/#step-2--modify-the-prometheus-manifest-configuration

I'm trying to use whats on the topic "Modify the Prometheus manifest configuration"
Just ignore the parts where say to use user and password because for VictoriaMetrics its not necessary.

Thank you very much.

**Comment by JoaoBraveCoding** [comment]
>  Where I can put this parameter and how I can apply it?

That depends on how you are managing the deployment of the Prometheus CR, if you are managing it manually then what you did should be enough. If you are using kube-prometheus you have to make sure that when you run `kubectl apply -f manifests/` that your manual changes were not undone.

Regardless, you should also check the logs on the prometheus-operator to see if there are no error messages, same for  prometheus itself. If you are configuring `remoteWrite` and when you do `kubectl get prometheus k8s -n monitoring -o yaml` you are able to see the `remoteWrite` configuration, then it should work.

**Comment by giz33** [comment]
Hi João!
Thanks again for the answer.
I was able to see my remoteWrite configuration applied on my operator after I run `kubectl get prometheus k8s -n monitoring -o yaml`.As you can see on the snippet below:

```
 podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.29.1
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  remoteWrite:
  - url: http://vmsingle-victoria-metrics-single-server.victoriametrics.svc.cluster.local:8428/api/v1/write
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  retention: 48h
  ruleNamespaceSelector: {}
  ruleSelector: {}
```
But on my statefulsets the configuration did not reflected inside the prometheus.yml file configuration.
When I go and look the content of the secret `prometheus-k8s` that is used to create the prometheus.yml config file, the content is not changed to contemplate the new parameter inserted.

I'm suspecting that I need to scale down my statefulsets of prometheus, delete the PVCs of the PODS used by the prometheus statefulset and then apply the configuration on the operator with kubectl apply and then scale up the application to apply the new configuration.

Tks again

**Comment by JoaoBraveCoding** [comment]
> I'm suspecting that I need to scale down my statefulsets of prometheus, delete the PVCs of the PODS used by the prometheus statefulset and then apply the configuration on the operator with kubectl apply and then scale up the application to apply the new configuration.

You shouldn't have to do that, what does the prometheus-operator log show?

**Comment by giz33** [comment]
How can I see the prometheus-operator log?
It is some of this workloads?


```
NAME                                  READY   STATUS    RESTARTS   AGE
alertmanager-main-0                   2/2     Running   0          104d
alertmanager-main-1                   2/2     Running   0          104d
alertmanager-main-2                   2/2     Running   0          104d
blackbox-exporter-6798fb5bb4-b2b8q    3/3     Running   0          35d
grafana-0                             1/1     Running   0          55d
kube-state-metrics-74964b6cd4-hxl5z   3/3     Running   2          77d
node-exporter-47wjf                   2/2     Running   0          134d
node-exporter-5hn49                   2/2     Running   0          134d
node-exporter-64x9w                   0/2     Evicted   0          4m36s
node-exporter-6lxlc                   2/2     Running   0          134d
node-exporter-7wswv                   2/2     Running   0          134d
node-exporter-9jc2z                   2/2     Running   2          134d
node-exporter-bpv42                   2/2     Running   0          134d
node-exporter-lc7h9                   2/2     Running   0          134d
node-exporter-ltgdv                   2/2     Running   2          134d
node-exporter-mgwqv                   2/2     Running   0          134d
node-exporter-mkqzl                   2/2     Running   6          134d
node-exporter-mnv27                   2/2     Running   2          92d
node-exporter-p79k8                   2/2     Running   0          134d
node-exporter-qfgbc                   2/2     Running   0          134d
node-exporter-wxflc                   2/2     Running   0          91d
node-exporter-xmb9k                   2/2     Running   2          134d
node-exporter-xnfmm                   2/2     Running   0          134d
node-exporter-zx7tg                   2/2     Running   0          134d
prometheus-adapter-869cc49999-5bjx5   1/1     Running   0          133d
prometheus-adapter-869cc49999-t27gg   1/1     Running   0          133d
prometheus-k8s-0                      2/2     Running   0          18h
```

**Comment by JoaoBraveCoding** [comment]
Seems like the operator is not running in that namespace... so unless it's running in another namespace you are not able to check its logs.
That also explains why you don't see any changes in your prometheus config.

**Comment by giz33** [comment]
What is the name of the prometheus operator workload?Can I try to run it manually, like kubectl apply -f <operator_manifest>.yaml?

**Comment by giz33** [comment]
João, I solved my problem!
As you pointed earlier, my operator was not running properly.
I applied the following manifest on my environment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.49.0
  name: prometheus-operator
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: prometheus-operator
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 0.49.0
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.49.0
        image: quay.io/prometheus-operator/prometheus-operator:v0.49.0
        imagePullPolicy: IfNotPresent
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --logtostderr
        - --secure-listen-address=:8443
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - --upstream=http://127.0.0.1:8080/
        image: quay.io/brancz/kube-rbac-proxy:v0.11.0
        imagePullPolicy: IfNotPresent
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
        securityContext:
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccount: prometheus-operator
      serviceAccountName: prometheus-operator
      terminationGracePeriodSeconds: 30
```
And after this, all the changes that I made on prometheus k8s using the below command worked and applied succesfully:
kubectl edit prometheus k8s -n monitoring

Thank you very much for all the help.
