### ISSUE TITLE
Root directory of new persistent storage created with wrong permissions

### ISSUE THREAD

**Issue by mnlipp** [prometheus-operator/prometheus-operator#5354]
**What happened?**

Created new Prometheus instance with PVC
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  namespace: monitoring
  name: prometheus
  labels:
    app: prometheus
spec:
  serviceAccountName: prometheus
  # All ServiceMonitors in own namespace
  serviceMonitorSelector: {}
  # All PodMonitors in own namespace
  podMonitorSelector: {}
  # Additional
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  resources:
    requests:
      memory: 400Mi
  # Remove the rest if you don't need long term storage
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: rook-cephfs
        resources:
          requests:
            storage: 40Gi
```

Storage class rook-cephfs is file storage provided by ceph.

The pod prometheus-prometheus-0 fails (crashloop) because the directory `/prometheus` has ownership `root:root` and permissions 755. As Prometheus runs as nobody, it does not have permission to write in this directory.

**Did you expect to see something different?**

Obviously, I expected this to work.

**How to reproduce it (as minimally and precisely as possible)**:

Use file above and a ceph fs.

**Workaround**

Mount the PV in an interactive container, chmod to 777, try again.

* Prometheus Operator version:

0.62.0

* Kubernetes version information:

```
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.25.6+k3s1
```
