### ISSUE TITLE
After configuring the serviceMonitor, it didn't work

### ISSUE THREAD

**Issue by wang-xiaowu** [prometheus-operator/prometheus-operator#5376]
What did you do?
Service/Deployment/ServiceMonitor are in the same namespace.

question:
There were no targets showed in prometheus webUI after apply ServiceMonitor.yaml.
Meanwhile in the Configuration webUI I can see it is updated by servicemonitor configure.
So I wonder what is the main cause and how to fix it.

Basically tested:

Environment

Prometheus Operator version:
Monitoring (100.1.3+up19.0.3)[by rancher]

Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:54:23Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

Kubernetes cluster kind:
k3s + rancher

this is my service
```
apiVersion: v1
kind: Service
metadata:
  name: app-manager
  namespace: sopei-biz
  ports:
  - name: web
    port: 32201
    protocol: TCP
    targetPort: 32201
  namespaceSelector:
    matchNames:
      - sopei-biz
  selector:
    app: app-manager
```

and this is my serviceMonitor
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: app-manager-monitor
  name: app-manager
  namespace: sopei-biz
spec:
  endpoints:
    - path: /metrics
      port: web
      scheme: http
      interval: 10s
      honorLabels: true
  selector:
    matchLabels:
      app: app-manager
```

some pictures

![image](https://user-images.githubusercontent.com/44340137/221818625-3945a131-9b0b-46ce-abe2-d99ff2d40162.png)

![image](https://user-images.githubusercontent.com/44340137/221818740-f7c765be-06b1-46be-a0b7-5bb80881c62f.png)

this is service discover

![image](https://user-images.githubusercontent.com/44340137/221821785-b15a0576-cd1f-4515-9277-47e552b26c68.png)

![image](https://user-images.githubusercontent.com/44340137/221822705-fe0682a3-9a4a-4d15-90bd-7aefef36f6a8.png)
