### ISSUE TITLE
Service discovered but not scraped

### ISSUE THREAD

**Issue by prabhatsharma** [prometheus-operator/prometheus-operator#5386]
**What did you do?**

I instrumented the application. Am able to wget metrics on the service from prometheus pod. Service is getting discovered too.

```shell
[serviceMonitor/monitoring/zincobserve/0 (0 / 34 active targets)](http://localhost:9090/service-discovery?search=#serviceMonitor/monitoring/zincobserve/0)
```

But no metrics are being scraped.

My Service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: zo1-zincobserve-router
  namespace: "ziox-noderole"
  labels:
    helm.sh/chart: zincobserve-0.1.6
    app.kubernetes.io/name: zincobserve
    app.kubernetes.io/instance: zo1
    app.kubernetes.io/version: "v0.1.6"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: zincobserve
    app.kubernetes.io/instance: zo1
    role: router
```

My servicemonitor:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zincobserve
  # Change this to the namespace the Prometheus instance is running in
  namespace: monitoring
  labels:
    app: zincobserve
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zincobserve
  endpoints:
  - port: http
    interval: 15s

```

Generated config

```yaml
- job_name: serviceMonitor/monitoring/zincobserve/0
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: (.*)
    target_label: __tmp_prometheus_job_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name, __meta_kubernetes_service_labelpresent_app_kubernetes_io_name]
    separator: ;
    regex: (zincobserve);true
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: http
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Node;(.*)
    target_label: node
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Pod;(.*)
    target_label: pod
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: (.*)
    target_label: container
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: http
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 1
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: "0"
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - monitoring
```

**Did you expect to see some different?**

Expected to see the metrics being scraped.

**Environment**

Amazon EKS

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
Image:      quay.io/prometheus-operator/prometheus-operator:v0.60.1

* Kubernetes version information:

    `kubectl version`

``` shell
k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.14-eks-ffeb93d", GitCommit:"96e7d52c98a32f2b296ca7f19dc9346cf79915ba", GitTreeState:"clean", BuildDate:"2022-11-29T18:43:31Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

Amazon EKS

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

Sample metrics

```shell
# HELP zincobserve_incoming_requests Incoming Requests
# TYPE zincobserve_incoming_requests counter
zincobserve_incoming_requests{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200"} 43
zincobserve_incoming_requests{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="POST",role="router",status="200"} 30395
zincobserve_incoming_requests{endpoint="/config",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200"} 1
zincobserve_incoming_requests{endpoint="/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200"} 6
zincobserve_incoming_requests{endpoint="/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="304"} 1
zincobserve_incoming_requests{endpoint="/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="404"} 1
# HELP zincobserve_response_code Response Codes
# TYPE zincobserve_response_code counter
zincobserve_response_code{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",statuscode="200",type="200"} 43
zincobserve_response_code{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="POST",role="router",statuscode="200",type="200"} 30395
zincobserve_response_code{endpoint="/config",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",statuscode="200",type="200"} 1
zincobserve_response_code{endpoint="/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",statuscode="200",type="200"} 6
zincobserve_response_code{endpoint="/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",statuscode="304",type="300"} 1
zincobserve_response_code{endpoint="/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",statuscode="404",type="400"} 1
# HELP zincobserve_response_time Response Times
# TYPE zincobserve_response_time histogram
zincobserve_response_time_bucket{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200",le="0.005"} 42
zincobserve_response_time_bucket{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200",le="0.01"} 42
zincobserve_response_time_bucket{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200",le="0.025"} 42
zincobserve_response_time_bucket{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200",le="0.05"} 43
zincobserve_response_time_bucket{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200",le="0.1"} 43
zincobserve_response_time_bucket{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200",le="0.25"} 43
zincobserve_response_time_bucket{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200",le="0.5"} 43
zincobserve_response_time_bucket{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200",le="1"} 43
zincobserve_response_time_bucket{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200",le="2.5"} 43
zincobserve_response_time_bucket{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200",le="5"} 43
zincobserve_response_time_bucket{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200",le="10"} 43
zincobserve_response_time_bucket{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200",le="+Inf"} 43
zincobserve_response_time_sum{endpoint="/api/{path:.*}",hostname="zo1-zincobserve-router-5ffb974c48-qhrvd",method="GET",role="router",status="200"} 0.113799737
```
