### ISSUE TITLE
How to add static labels to the indicators collected by prometheus use prometheus-operator?

### ISSUE THREAD

**Issue by noovertime7** [prometheus-operator/prometheus-operator#5403]
In the  prometheus, add the static label as follows
```
static_configs:
      - targets: ["10.20.110.51:19090"]
        labels:
          app: test   ## add label
```
How to add static labels to the indicators collected by prometheus use prometheus-operator?
