### ISSUE TITLE
Please help, I can't display the target after following the official configuration

### ISSUE THREAD

**Issue by AbelHugh** [prometheus-operator/prometheus-operator#5432]
**Environment**

* Version:
kube-prometheus: 0.12.0
kubernetes version: 1.24.4

* issue description：
I deployed the mysqld exporter using the sidecar mode, and he can get the data correctly, then I try to collect the data according to the official configuration, and, because my mysql exporter is deployed in multiple namespaces, I use it in the ServiceMonitor file 'any: true'

* Prometheus Operator Logs:
```
level=info ts=2023-03-21T08:14:17.7584234Z caller=operator.go:1162 component=prometheusoperator key=monitoring/mysqld-exporter-prom msg="sync prometheus"
level=info ts=2023-03-21T08:14:17.828175629Z caller=operator.go:638 component=alertmanageroperator key=monitoring/main msg="sync alertmanager"
level=info ts=2023-03-21T08:14:17.889618815Z caller=operator.go:1162 component=prometheusoperator key=monitoring/k8s msg="sync prometheus"
level=info ts=2023-03-21T08:14:17.8897355Z caller=operator.go:1330 component=prometheusoperator key=monitoring/mysqld-exporter-prom msg="update prometheus status"
level=info ts=2023-03-21T08:14:17.889824858Z caller=operator.go:1352 component=prometheusoperator key=monitoring/mysqld-exporter-prom statefulset=monitoring/prometheus-mysqld-exporter-prom shard=0 msg="not found"
level=info ts=2023-03-21T08:14:17.979722547Z caller=operator.go:638 component=alertmanageroperator key=monitoring/main msg="sync alertmanager"
level=info ts=2023-03-21T08:14:17.980810772Z caller=operator.go:1330 component=prometheusoperator key=monitoring/mysqld-exporter-prom msg="update prometheus status"
level=info ts=2023-03-21T08:14:18.989048052Z caller=operator.go:638 component=alertmanageroperator key=monitoring/main msg="sync alertmanager"
level=info ts=2023-03-21T08:14:19.079687135Z caller=operator.go:1162 component=prometheusoperator key=monitoring/mysqld-exporter-prom msg="sync prometheus"
level=info ts=2023-03-21T08:14:19.079822673Z caller=operator.go:1330 component=prometheusoperator key=monitoring/k8s msg="update prometheus status"
level=info ts=2023-03-21T08:14:19.201331205Z caller=operator.go:1162 component=prometheusoperator key=monitoring/k8s msg="sync prometheus"
level=info ts=2023-03-21T08:14:19.279412041Z caller=operator.go:1330 component=prometheusoperator key=monitoring/mysqld-exporter-prom msg="update prometheus status"
level=info ts=2023-03-21T08:14:20.393038336Z caller=operator.go:1162 component=prometheusoperator key=monitoring/mysqld-exporter-prom msg="sync prometheus"
level=info ts=2023-03-21T08:14:20.393180153Z caller=operator.go:1330 component=prometheusoperator key=monitoring/k8s msg="update prometheus status"
level=info ts=2023-03-21T08:14:20.481281124Z caller=operator.go:1330 component=prometheusoperator key=monitoring/mysqld-exporter-prom msg="update prometheus status"
level=info ts=2023-03-21T08:14:34.083089478Z caller=operator.go:1330 component=prometheusoperator key=monitoring/mysqld-exporter-prom msg="update prometheus status"
```

* pod prometheus-mysqld-exporter-prom-0's log:
```
ts=2023-03-21T08:14:20.222Z caller=main.go:556 level=info msg="Starting Prometheus Server" mode=server version="(version=2.41.0, branch=HEAD, revision=c0d8a56c69014279464c0e15d8bfb0e153af0dab)"
ts=2023-03-21T08:14:20.222Z caller=main.go:561 level=info build_context="(go=go1.19.4, platform=linux/amd64, user=root@d20a03e77067, date=20221220-10:40:45)"
ts=2023-03-21T08:14:20.222Z caller=main.go:562 level=info host_details="(Linux 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 prometheus-mysqld-exporter-prom-0 (none))"
ts=2023-03-21T08:14:20.222Z caller=main.go:563 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2023-03-21T08:14:20.222Z caller=main.go:564 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2023-03-21T08:14:20.226Z caller=web.go:559 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2023-03-21T08:14:20.227Z caller=main.go:993 level=info msg="Starting TSDB ..."
ts=2023-03-21T08:14:20.230Z caller=tls_config.go:232 level=info component=web msg="Listening on" address=[::]:9090
ts=2023-03-21T08:14:20.230Z caller=tls_config.go:271 level=info component=web msg="TLS is disabled." http2=false address=[::]:9090
ts=2023-03-21T08:14:20.232Z caller=head.go:562 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2023-03-21T08:14:20.232Z caller=head.go:606 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=3.366µs
ts=2023-03-21T08:14:20.232Z caller=head.go:612 level=info component=tsdb msg="Replaying WAL, this may take a while"
ts=2023-03-21T08:14:20.244Z caller=head.go:683 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
ts=2023-03-21T08:14:20.244Z caller=head.go:720 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=58.765µs wal_replay_duration=11.401589ms wbl_replay_duration=184ns total_replay_duration=11.506863ms
ts=2023-03-21T08:14:20.245Z caller=main.go:1014 level=info fs_type=EXT4_SUPER_MAGIC
ts=2023-03-21T08:14:20.246Z caller=main.go:1017 level=info msg="TSDB started"
ts=2023-03-21T08:14:20.246Z caller=main.go:1197 level=info msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
ts=2023-03-21T08:14:20.247Z caller=kubernetes.go:326 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2023-03-21T08:14:20.247Z caller=main.go:1234 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=1.937065ms db_storage=1.933µs remote_storage=2.529µs web_handler=687ns query_engine=1.327µs scrape=432.314µs scrape_sd=661.419µs notify=1.574µs notify_sd=3.526µs rules=2.049µs tracing=5.3µs
ts=2023-03-21T08:14:20.248Z caller=main.go:978 level=info msg="Server is ready to receive web requests."
ts=2023-03-21T08:14:20.248Z caller=manager.go:953 level=info component="rule manager" msg="Starting rule manager..."
ts=2023-03-21T08:14:20.359Z caller=main.go:1197 level=info msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
ts=2023-03-21T08:14:20.360Z caller=kubernetes.go:326 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2023-03-21T08:14:20.360Z caller=main.go:1234 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=1.606943ms db_storage=3.477µs remote_storage=4.252µs web_handler=1.094µs query_engine=2.017µs scrape=99.483µs scrape_sd=590.955µs notify=1.765µs notify_sd=2.655µs rules=1.964µs tracing=7.634µs
```

**Anything else we need to know?**:

```
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql-instance
spec:
  selector:
    app: mysql
  ports:
    - name: db-3306
      port: 3306
      targetPort: 3306
    - name: exporter-9104
      port: 9104
      targetPort: 9104
  type: NodePort
```

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysqld-exporter-sa
  namespace: monitoring
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqld-exporter-cr
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysqld-exporter-cr
subjects:
- kind: ServiceAccount
  name: mysqld-exporter-sa
  namespace: monitoring
```

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysqld-exporter-sm
  namespace: monitoring
  labels:
    team: my-mysqld-exporter
spec:
  selector:
    matchLabels:
      app: mysql-instance
  endpoints:
  - port: exporter-9104
    path: /metrics
    interval: 15s
  namespaceSelector:
    any: true
```

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: mysqld-exporter-prom
  namespace: monitoring
spec:
  serviceAccountName: mysqld-exporter-sa
  serviceMonitorSelector:
    matchLabels:
      team: my-mysqld-exporter
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
```
