### ISSUE TITLE
Add updateStrategy option for StatefulSets

### ISSUE THREAD

**Issue by roth-wine** [prometheus-operator/prometheus-operator#5435]
**What is missing?**
For StatefulSets it would be nice, to specify the updateStrategy. For now the updateStrategy is hard coded to:
```go
UpdateStrategy: appsv1.StatefulSetUpdateStrategy{
	Type: appsv1.RollingUpdateStatefulSetStrategyType,
},
```
**Why do we need it?**
For production environment, it would be great to specify the updateStrategy to OnDelete in order to prevent a roll-out restart of all applied StatefulSet resources, which may cause a short outage of production environments. The updateStrategy will then only apply the changes when the pod gets deleted.  

**Anything else we need to know?**:
For now the the updateStrategy is hard coded to RollingUpdate in three places:
[pkg/thanos/statefulset.go](https://github.com/prometheus-operator/prometheus-operator/blob/6be89b4010d06cbd2561b6650b6399438900a944/pkg/thanos/statefulset.go#L437-L438), [pkg/alertmanager/statefulset.go](https://github.com/prometheus-operator/prometheus-operator/blob/ef5fad77131af9f162b4b13234446e721d74818d/pkg/alertmanager/statefulset.go#L756-L757) and [pkg/prometheus/server/statefulset.go](https://github.com/prometheus-operator/prometheus-operator/blob/e2ce57ad6c383a886a7d5fb518a677e1dd6a6115/pkg/prometheus/server/statefulset.go#L451-L452).

**Comment by JoaoBraveCoding** [comment]
I think this kind of behaviour could also be obtained by leveraging the `spec.paused` flag. However, nowadays we already expose other config parameters of the statefulset so I'm also not against implementing this, I'll defer to @simonpasquier judgement

**Comment by roth-wine** [comment]
Hey @simonpasquier ,
we run several Kubernetes cluster, which are specified to provide Metrics. There are several Prometheus Instances per cluster, which are managed by the Prometheus Operator. For the `Prometheus` resource of the Prometheus Operator you are able to specify the Prometheus version via `spec.version`.  When we update the `spec.version` and deploy those changes, all our Prometheus Instances get deployed with the new version. In our deployment Progress those Prometheus resources are managed via templates and therefore are updated all at once. With the updateStrategy `RollingUpdate` this happen at once and not coordinated and slowly. With the updateStrategy `OnDelete` we could coordinate this step from our side by deleting the pods manually, or rather let the deployment progress process slowly when each pod get's deleted.

**Comment by Jakob3xD** [comment]
> How many replicas per Prometheus object? I'd expect to see no downtime provided that the startup probes work as intended.

Coworker of roth-wine. All Prometheus objects have a replica of 1.
We have an object storage A and object storage B where Prom-1A pushes to A and Prom-1B to B.
AFAIK there is now way of doing it with the Operator/Kubernetes as we would need to modify the object storage config per replica.

**Comment by simonpasquier** [comment]
IIUC you're talking about the Thanos sidecar's object storage config?

**Comment by Jakob3xD** [comment]
Yes, just for clarification I added an example of one Deployment below. There is a second deployment where replica, names etc. is `b` instead of `a` .
<details>
  <summary>Prometheus Deployment</summary>

```
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    thanos: sidecar
    prometheus: domains
  name: sidecar-domains-1a
  namespace: scrape-platform-domains
spec:
  replicas: 1
  version: v2.43.0
  disableCompaction: True
  walCompression: True
  scrapeInterval: 30s
  scrapeTimeout: 15s
  serviceMonitorSelector:
    matchLabels:
      scraped_by: domains
  podMonitorSelector:
    matchLabels:
      scraped_by: domains
  podMetadata:
    labels:
      app: thanos
      thanos: sidecar
      sidecar: domains-1
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsUser: 65534
  prometheusExternalLabelName: ""
  externalLabels:
    region: xyz
    monitor: domains
    prom: prom-domains-1
    replica: a
  additionalScrapeConfigs:
    name: domains-scrape-configs
    key: scrape-config.yaml
  volumes:
    - name: targets
      configMap:
        name: sidecar-domains-target-list-1
    - name: tls
      secret:
        secretName: tls-sidecar
        defaultMode: 0400
    - name: ca
      secret:
        secretName: thanos-ca
        items:
          - key: tls.crt
            mode: 0444
            path: tls.crt
    - name: jaeger
      configMap:
        name: jaeger
  volumeMounts:
    - name: targets
      mountPath: /etc/prometheus/targets.d
    - name: ca
      mountPath: /ca
  query:
    timeout: 180s
    maxConcurrency: 20
  containers:
    - name: thanos-sidecar
      securityContext:
        capabilities:
          add:
          - CAP_FOWNER
          drop:
          - ALL
    - name: config-reloader
      env:
        - name: THANOS_REGION
          value: xyz
  initContainers:
    - name: init-config-reloader
      env:
        - name: THANOS_REGION
          value: xzy
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: Exists
              - key: is-root-server
                operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: sidecar
                operator: In
                values:
                  - domains-1
          topologyKey: "kubernetes.io/hostname"
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: sidecar
                operator: In
                values:
                  - domains-1
          topologyKey: "topology.kubernetes.io/zone"
 storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 15Gi
        storageClassName: default
        accessModes:
          - ReadWriteOnce
  ruleSelector:
    matchLabels:
      domains: "true"
  ruleNamespaceSelector:
    matchLabels:
      rules: prometheus
  resources:
    requests:
      memory: 7000Mi
      cpu: 1500m
    limits:
      memory: 8500Mi
      cpu: 2000m
  imagePullSecrets:
    - name: gitlab
  thanos:
    image: quay.io/thanos/thanos:v0.30.2
    minTime: -6h
    tracingConfigFile: /thanos/jaeger/jaeger.yml
    grpcServerTlsConfig:
      certFile: /tls/tls.crt
      keyFile: /tls/tls.key
      caFile: /ca/tls.crt
    objectStorageConfig:
      name: objectstorage-platform-domains-a
      key: objectstorage
    resources:
      requests:
        memory: 250Mi
        cpu: 200m
    volumeMounts:
      - name: tls
        mountPath: /tls
        readOnly: true
      - name: ca
        mountPath: /ca
        readOnly: true
      - name: jaeger
        mountPath: "/thanos/jaeger"
        readOnly: true
  alerting:
    alertmanagers:
      - name: alertmanager-platform
        namespace: monitoring
        port: 9093
        scheme: http
```

</details>

**Comment by simonpasquier** [comment]
You might be able to inject the pod name as an environment variable in the Thanos sidecar container, mount a secret containing the 2 configurations (one key per pod name) and use the POD_NAME envvar to load a different object storage config for each pod:

```
spec:
  volumes:
  - name: thanos-objectstorage-config
    secret:
      secretName: xxx # secret containing 2 keys: prometheus-<prometheus object name>-0 and prometheus-<prometheus object name>-1 
  thanos:
    objectStorageConfigFile: /etc/thanos/$(POD_NAME)
    volumeMounts:
    - name: thanos-objectstorage-config
      readOnly: true
      mountPath: /etc/thanos
  containers:
  - name: thanos-sidecar
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef: 
          fieldPath: "metadata.name" 
```

**Comment by Jakob3xD** [comment]
> You might be able to inject the pod name as an environment variable in the Thanos sidecar container, mount a secret containing the 2 configurations (one key per pod name) and use the POD_NAME envvar to load a different object storage config for each pod:

Sorry for the late reply. Thank you for your suggestion, I see one issue with this.
We would need to create one secret per prometheus definition. IMO this scales badly as we add unneeded secrets.

We will try to create an init container which will regexp match on the pod name and then create the object storage config depending on the replica.

**Comment by eumel8** [comment]
Slid into that issue. Would be nice if the `updateStrategy` can be extend to current Kubernetes API

```yaml
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
      partition: 0
    type: RollingUpdate
```

ref: https://kubernetes.io/blog/2022/05/27/maxunavailable-for-statefulset/
