### ISSUE TITLE
Non-existing EC2 SD targets causing Config Reloader to loop

### ISSUE THREAD

**Issue by m-zeb** [prometheus-operator/prometheus-operator#5445]
**What happened?**
After deploying kube-prometheus-stack with a config which includes a job that utilises EC2 service disocvery, targetting an instance which was not up at the time, the Config Reloader appears to have gotten stuck in some sort of loop from which it never recovered, with the logs stating (repeatedly):
```
level=error ts=2023-03-23T11:55:07.193683539Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```
Running `time wget --post-data "" http://127.0.0.1:9090/-/reload` would take longer and longer to complete each time, while not actually updating the config.

The only way to fix this was to delete the pods, forcing the init container to rebuild the config. 

After removing the jobs for non-existing targets the reload would execute successfully and take around 20s consistently.

**Did you expect to see something different?**
The expected result would be that the timeout is honoured and the target ignored without causing the config reloader to loop.

**How to reproduce it (as minimally and precisely as possible)**:

Add 4 EC2 service discovery jobs to the config and try reloading. The reloader should produce endless reload request errors. E.g.

```
    - job_name: "dev-metrics-blue"
      scrape_interval: 15s
      ec2_sd_configs:
        - port: 9464
          filters:
            - name: tag:metrics
              values:
                - windows
            - name: tag:server-role
              values:
                - Role
            - name: tag:environment
              values:
                - Dev
      relabel_configs:
        - target_label: 'metrics_type'
          replacement: transient
        - source_labels:
          - '__meta_ec2_tag_Name'
          target_label: 'instance' 
        - source_labels:
          - '__meta_ec2_instance_id'
          target_label: 'instance_id' 
        - source_labels:
          - '__meta_ec2_tag_environment'
          target_label: 'environment'
        - source_labels:
          - '__meta_ec2_tag_environment'
          target_label: 'namespace'
        - source_labels:
          - '__meta_ec2_tag_server_role'
          target_label: 'server_role'
        - source_labels:
          - '__meta_ec2_tag_server_role'
          target_label: 'service'
        - source_labels:
          - '__meta_ec2_instance_type'
          target_label: 'ec2_instance_type'

    - job_name: "dev-metrics-green"
      scrape_interval: 15s
      ec2_sd_configs:
        - port: 9465
          filters:
            - name: tag:metrics
              values:
                - windows
            - name: tag:server-role
              values:
                - Role
            - name: tag:environment
              values:
                - Dev
      relabel_configs:
        - target_label: 'metrics_type'
          replacement: transient
        - source_labels:
          - '__meta_ec2_tag_Name'
          target_label: 'instance' 
        - source_labels:
          - '__meta_ec2_instance_id'
          target_label: 'instance_id' 
        - source_labels:
          - '__meta_ec2_tag_environment'
          target_label: 'environment'
        - source_labels:
          - '__meta_ec2_tag_environment'
          target_label: 'namespace'
        - source_labels:
          - '__meta_ec2_tag_server_role'
          target_label: 'server_role'
        - source_labels:
          - '__meta_ec2_tag_server_role'
          target_label: 'service'
        - source_labels:
          - '__meta_ec2_instance_type'
          target_label: 'ec2_instance_type'

    - job_name: "stg-parkers-metrics-blue"
      scrape_interval: 15s
      ec2_sd_configs:
        - port: 9464
          filters:
            - name: tag:metrics
              values:
                - windows
            - name: tag:server-role
              values:
                - Role
            - name: tag:environment
              values:
                - Staging
      relabel_configs:
        - target_label: 'metrics_type'
          replacement: transient
        - source_labels:
          - '__meta_ec2_tag_Name'
          target_label: 'instance' 
        - source_labels:
          - '__meta_ec2_instance_id'
          target_label: 'instance_id' 
        - source_labels:
          - '__meta_ec2_tag_environment'
          target_label: 'environment'
        - source_labels:
          - '__meta_ec2_tag_environment'
          target_label: 'namespace'
        - source_labels:
          - '__meta_ec2_tag_server_role'
          target_label: 'server_role'
        - source_labels:
          - '__meta_ec2_tag_server_role'
          target_label: 'service'
        - source_labels:
          - '__meta_ec2_instance_type'
          target_label: 'ec2_instance_type'

    - job_name: "stg-parkers-metrics-green"
      scrape_interval: 15s
      ec2_sd_configs:
        - port: 9465
          filters:
            - name: tag:metrics
              values:
                - windows
            - name: tag:server-role
              values:
                - Role
            - name: tag:environment
              values:
                - Staging
      relabel_configs:
        - target_label: 'metrics_type'
          replacement: transient
        - source_labels:
          - '__meta_ec2_tag_Name'
          target_label: 'instance' 
        - source_labels:
          - '__meta_ec2_instance_id'
          target_label: 'instance_id' 
        - source_labels:
          - '__meta_ec2_tag_environment'
          target_label: 'environment'
        - source_labels:
          - '__meta_ec2_tag_environment'
          target_label: 'namespace'
        - source_labels:
          - '__meta_ec2_tag_server_role'
          target_label: 'server_role'
        - source_labels:
          - '__meta_ec2_tag_server_role'
          target_label: 'service'
        - source_labels:
          - '__meta_ec2_instance_type'
          target_label: 'ec2_instance_type'
```

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.61.1`

* Kubernetes version information:

    ```Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:10:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T15:54:23Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}```

* Kubernetes cluster kind:

    `kops`
