### ISSUE TITLE
PrometheusRules CR: Allow empty rule groups

### ISSUE THREAD

**Issue by jkroepke** [prometheus-operator/prometheus-operator#5480]
**What happened?**

By default, The Prometheus Operator does not allow PrometheusRules contains empty rules.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  name: example
spec:
  groups:
  - name: example
    rules:
```

while this is for Prometheus a valid configuration:

```yaml
groups:
  - name: example
    rules:
```

<details>
<summary>Details</summary>

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1560587/230567807-d49fcfd3-80d5-461c-b392-e9a04bbdae06.png">

</details>

But Promethues Operator and the the CRD doesnt allow this configuration:

> % k apply -f rule.yaml
> error: error validating "a.yaml": error validating data: ValidationError(PrometheusRule.spec.groups[0]): missing required field "rules" in com.coreos.monitoring.v1.PrometheusRule.spec.groups; if you choose to ignore these errors, turn validation off with --validate=false

> % k apply --validate=false -f rule.yaml
> The PrometheusRule "example" is invalid: spec.groups[0].rules: Required value

**Did you expect to see something different?**

The PrometheusRule is accepted. A valid reason whould be here that Prometheus does accept this kind of configuration, while the prometheus operator denies this.

**How to reproduce it (as minimally and precisely as possible)**:

Applying the CR from above.

**Environment**

* Prometheus Operator version:

    `45.7.1`
    
    

* Kubernetes version information: 1.24.9

    `kubectl version`
    

* Kubernetes cluster kind: AKS

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  name: example
spec:
  groups:
  - name: example
    rules:
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

# Motivation of this Change:

From the first point to view, this changes feel pointless. The motivation behind this changes is coming from one of our helm charts.

```yaml
# simplifed version
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  name: example
spec:
  groups:
  - name: example
    rules:
{{ if .Values.rules.alert1.enabled }}
    - alert: ExampleAlert1
      expr: vector(1)
{{ end }}
{{ if .Values.rules.alert2.enabled }}
    - alert: ExampleAlert2
      expr: vector(1)
{{ end }}
{{ if .Values.rules.alert2.enabled }}
    - alert: ExampleAlert3
      expr: vector(1)
{{ end }}
```

If all alerts are disabled, I'm hitting the error from above.
