### ISSUE TITLE
Merge multiple scrape pools into one

### ISSUE THREAD

**Issue by dene14** [prometheus-operator/prometheus-operator#5513]
I'm trying to minimize count of scraping pools, in particular scraping pools with just one target looks ugly, yet it causing performance issues to prometheus due to many individual scraping jobs...

I currently have a serviceMonitor spec as follows:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prom
  name: taxi-monitor
spec:
  jobLabel: test
  endpoints:
  - bearerTokenSecret:
      key: ""
    interval: 2m
    path: /metrics
    port: metrics
  - bearerTokenSecret:
      key: ""
    interval: 2m
    path: /metrics
    port: jdb
  - bearerTokenSecret:
      key: ""
    interval: 2m
    path: /metrics
    port: kdb
  - bearerTokenSecret:
      key: ""
    interval: 2m
    path: /metrics
    port: ldb
  namespaceSelector:
    matchNames:
    - 49upompnhn
  selector:
    matchLabels:
      mycorp.com/app: taxi
      mycorp/component: dataaccess
  targetLabels:
  - mycorp.com/app
  - mycorp.com/component
```

which results in 4 separate scrape pool for each endpoint:
- serviceMonitor/monitoring/taxi-monitor/0
- serviceMonitor/monitoring/taxi-monitor/1
- serviceMonitor/monitoring/taxi-monitor/2
- serviceMonitor/monitoring/taxi-monitor/3

questions:
- Is there any way to merge them under the same scrape pool?
- Is it possible to rename scrape pool `serviceMonitor/monitoring/taxi-monitor/0` from ServiceMonitor spec? I've tried `.spec.jobName` but it doesn't change anything.

Thank you!
