### ISSUE TITLE
Default `securityContext` compatible with pss-restricted

### ISSUE THREAD

**Issue by jcpunk** [prometheus-operator/prometheus-operator#5519]
**What is missing?**
`runAsNotRoot`, `seccompType`, and others as the default securityContext for CRDs

**Why do we need it?**
Stronger hardening by default

**Environment**

* Prometheus Operator version:

    `0.63.0`
    
    

**Anything else we need to know?**:
https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted

Currently the defaults are:
```yaml
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
```

Which is nice, but something like this would be stronger:
```yaml
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65536
    runAsGroup: 65536
    fsGroup: 65536
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL
```
