### ISSUE TITLE
PrometheusRule `severity_num` should accept numbers

### ISSUE THREAD

**Issue by jcpunk** [prometheus-operator/prometheus-operator#5525]
**What happened?**
```
  .spec.groups[name="postgres-alert-rules"].rules[0].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
  .spec.groups[name="postgres-alert-rules"].rules[1].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
  .spec.groups[name="postgres-alert-rules"].rules[2].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
  .spec.groups[name="postgres-alert-rules"].rules[3].labels.severity_num: expected string, got &value.valueUnstructured{Value:200}
  .spec.groups[name="postgres-alert-rules"].rules[4].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
  .spec.groups[name="postgres-alert-rules"].rules[5].labels.severity_num: expected string, got &value.valueUnstructured{Value:200}
  .spec.groups[name="postgres-alert-rules"].rules[6].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
  .spec.groups[name="postgres-alert-rules"].rules[7].labels.severity_num: expected string, got &value.valueUnstructured{Value:200}
  .spec.groups[name="postgres-alert-rules"].rules[8].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
  .spec.groups[name="postgres-alert-rules"].rules[9].labels.severity_num: expected string, got &value.valueUnstructured{Value:200}
  .spec.groups[name="postgres-alert-rules"].rules[10].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
  .spec.groups[name="postgres-alert-rules"].rules[11].labels.severity_num: expected string, got &value.valueUnstructured{Value:200}
  .spec.groups[name="postgres-alert-rules"].rules[12].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
  .spec.groups[name="postgres-alert-rules"].rules[13].labels.severity_num: expected string, got &value.valueUnstructured{Value:200}
  .spec.groups[name="postgres-alert-rules"].rules[14].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
  .spec.groups[name="postgres-alert-rules"].rules[15].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
  .spec.groups[name="postgres-alert-rules"].rules[16].labels.severity_num: expected string, got &value.valueUnstructured{Value:200}
  .spec.groups[name="postgres-alert-rules"].rules[17].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
  .spec.groups[name="postgres-alert-rules"].rules[18].labels.severity_num: expected string, got &value.valueUnstructured{Value:200}
  .spec.groups[name="postgres-alert-rules"].rules[19].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
  .spec.groups[name="postgres-alert-rules"].rules[20].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
  .spec.groups[name="postgres-alert-rules"].rules[21].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
  .spec.groups[name="postgres-alert-rules"].rules[22].labels.severity_num: expected string, got &value.valueUnstructured{Value:300}
```

**Did you expect to see something different?**
I'd expected the `severity_num` field to accept a number

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
spec:
    groups:
    - name: postgres-alert-rules
      rules:
      - alert: PGExporterScrapeError
        expr: pg_exporter_last_scrape_error > 0
        for: 60s
        labels:
          service: postgresql
          severity: critical
          severity_num: 300
        annotations:
          summary: 'Postgres Exporter running on {{ $labels.job }} (instance: {{ $labels.instance }}) is encountering scrape errors processing queries. Error count: ( {{ $value }} )'
```

**Environment**
Testing

* Prometheus Operator version:

    `0.63.0`
    
    

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:10:18Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T20:50:51Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
```
    

* Kubernetes cluster kind:

Tested with kubernetes kind

* Manifests:

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
spec:
    groups:
    - name: postgres-alert-rules
      rules:
      - alert: PGExporterScrapeError
        expr: pg_exporter_last_scrape_error > 0
        for: 60s
        labels:
          service: postgresql
          severity: critical
          severity_num: 300
        annotations:
          summary: 'Postgres Exporter running on {{ $labels.job }} (instance: {{ $labels.instance }}) is encountering scrape errors processing queries. Error count: ( {{ $value }} )'
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
All label values need to be string. You need to quote properly

```
        labels:
          service: postgresql
          severity: critical
          severity_num: "300"
````
