### ISSUE TITLE
Documentation: Specify valid values for Endpoints scheme:

### ISSUE THREAD

**Issue by spirilis** [prometheus-operator/prometheus-operator#5526]
**What is missing?**
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.Endpoint - scheme says it's a string, the HTTP scheme, but uppercase values do not work according to my experimentation.

Example:

```yaml
  endpoints:
  - path: /metrics
    port: "prometheus"
    scheme: HTTPS
    tlsConfig:
      ca:
        secret:
          name: ebshell1-ca
          key: ca.crt
      cert:
        secret:
          name: ebshell1
          key: tls.crt
      keySecret:
        name: ebshell1
        key: tls.key
      insecureSkipVerify: true
```

**How can we fix it?**
Can you append something to the documentation like:
`valid values: [http, https]`
