### ISSUE TITLE
Alertmanager TLS certs not being renewed

### ISSUE THREAD

**Issue by cowjen01** [prometheus-operator/prometheus-operator#5527]
**What happened?**
When Alertmanager is configured to enable the web TLS, it is not able to detected updated secret with renewed certificate and apply it. We use cert-manager to keep certificates updated. I checked the secret, and it contains the correct updated certificate, but when I attached to the container the mounted TLS certificate was expired and not replaced by the new one.

I noticed the secret with TLS assets is mounted like this:

```yaml
  - mountPath: /etc/alertmanager/web_config/secret_alertmanager-server-tls_tls.key
    name: web-config-tls-secret-key-alertmanager-server-tls-58c25a53
    readOnly: true
    subPath: tls.key
  - mountPath: /etc/alertmanager/web_config/secret_alertmanager-server-tls_tls.crt
    name: web-config-tls-secret-cert-alertmanager-server-tls-58c25a53
    readOnly: true
    subPath: tls.crt
```

But [Kubernetes docs](https://kubernetes.io/docs/concepts/configuration/secret/) says:

> Note: A container using a Secret as a [subPath](https://kubernetes.io/docs/concepts/storage/volumes#using-subpath) volume mount does not receive automated Secret updates.

When the certificate expires, and the new one is not reloaded Prometheus is no longer able to send the alerts. 

**Did you expect to see some different?**
When the certificate is renewed and specified secret updated, the certificate should also be updated inside the container. Also, Alertmanager and Prometheus should watch for the changes and load the changed certificates.

**How to reproduce it (as minimally and precisely as possible)**:

Kube-prometheus-stack Helm chart values:

```yaml
alertmanager:
  serviceMonitor:
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  alertmanagerSpec:
    replicas: 1
    web:
      tlsConfig:
        clientAuthType: "NoClientCert"
        keySecret:
          name: "alertmanager-server-tls"
          key: "tls.key"
        cert:
          secret:
            name: "alertmanager-server-tls"
            key: "tls.crt"
```

Cert-manager TLS certificate:

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager-server-tls
spec:
  secretName: alertmanager-server-tls
  issuerRef:
    name: vault
    kind: ClusterIssuer
  duration: 1h
  renewBefore: 15m 
  commonName: alertmanager
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - "prometheus-stack-alertmanager"
    - "prometheus-stack-alertmanager.prometheus-stack"
    - "prometheus-stack-alertmanager.prometheus-stack.svc"
    - "prometheus-stack-alertmanager.prometheus-stack.svc.cluster"
    - "prometheus-stack-alertmanager.prometheus-stack.svc.cluster.local"
```

**Environment**

* Prometheus Operator version:

    `v0.63.0`
    

* Kubernetes version information:

    `v1.25.3`
    

* Kubernetes cluster kind:

    Tested both on the Kind cluster and Kubeadm baremetal.

* Prometheus Operator Logs:

```
prometheus-stack-operator-75987f8f8f-8b67k level=info ts=2023-04-25T13:14:01.369962961Z caller=operator.go:1330 component=prometheusoperator key=prometheus-stack/prometheus-stack-pr
ometheus msg="update prometheus status"
prometheus-stack-operator-75987f8f8f-8b67k level=info ts=2023-04-25T13:14:01.783686712Z caller=operator.go:1330 component=prometheusoperator key=prometheus-stack/prometheus-stack-pr
ometheus msg="update prometheus status"
```

* Prometheus Logs:

```
prometheus-prometheus-stack-prometheus-0 prometheus ts=2023-04-25T13:38:32.628Z caller=notifier.go:532 level=error component=notifier alertmanager=https://10.244.3.47:9093/api/v2/al
erts count=1 msg="Error sending alert" err="Post \"https://10.244.3.47:9093/api/v2/alerts\": x509: certificate has expired or is not yet valid: current time 2023-04-25T13:38:32Z is
after 2023-04-25T11:15:10Z"
prometheus-prometheus-stack-prometheus-0 prometheus ts=2023-04-25T13:38:52.855Z caller=notifier.go:532 level=error component=notifier alertmanager=https://10.244.3.47:9093/api/v2/al
erts count=1 msg="Error sending alert" err="Post \"https://10.244.3.47:9093/api/v2/alerts\": x509: certificate has expired or is not yet valid: current time 2023-04-25T13:38:52Z is
after 2023-04-25T11:15:10Z"
```

* Alertmanager Logs:

```
alertmanager-prometheus-stack-alertmanager-0 alertmanager 2023/04/25 13:40:02 http: TLS handshake error from 10.244.3.48:55178: remote error: tls: bad certificate
alertmanager-prometheus-stack-alertmanager-0 alertmanager 2023/04/25 13:40:02 http: TLS handshake error from 10.244.3.48:55184: remote error: tls: bad certificate
```

**Comment by simonpasquier** [comment]
Moving to the prometheus-operator project since it's an operator concern.

**Comment by cowjen01** [comment]
The same issue was also spotted within the Prometheus TLS web config. The TLS assets mounted into the pod from a secret are also not updated.

**Comment by simonpasquier** [comment]
correct, both Alertmanager and Prometheus controllers use the same code.

**Comment by xiu** [comment]
I looked quickly into it, we could add some logic to `prometheus-config-reloader` to watch the directory where the certs are mounted. We could also have it watch the secret but it would mean pulling more dependencies, `prometheus-config-reloader` is fairly simple as it is today.

Another thing is that we might want this behavior to be behind a flag as people might already be using third party reloaders for certificates on the side.

Thoughts?

**Comment by cowjen01** [comment]
Thanks for looking at the issue. Using the reloader to watch for certificate changes is definitely needed to load the renewed assets when they are replaced. I'm only concerned about the subPath issues I pointed out. Based on my examination, the mounted secret was not even updated inside the container when it was changed, as explained in the linked documentation. Leaving out the subPath argument will be necessary to make this work. Am I correct?

**Comment by xiu** [comment]
From what I understand, you are. We'd have to change the way those secrets are mounted in the corresponding containers or restart the containers.

**Comment by cowjen01** [comment]
How about leaving out the subPath argument, mounting the whole secret into a directory, and then passing the secret's key specification from the Helm chart to the web config template?

**Comment by xiu** [comment]
The Operator doesn't seem to require a subPath to be defined, can you try the following, without the `key`:
```yaml
alertmanager:
  serviceMonitor:
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  alertmanagerSpec:
    replicas: 1
    web:
      tlsConfig:
        clientAuthType: "NoClientCert"
        keySecret:
          name: "alertmanager-server-tls"
        cert:
          secret:
            name: "alertmanager-server-tls"
```

The following test is not giving a key and renders a statefulset without a subPath on both secrets: https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/alertmanager/statefulset_test.go#L314

**Comment by xiu** [comment]
Actually, tried the following: 
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: test
spec:
  web:
    tlsConfig:
      keySecret:
        name: test
      cert:
        secret:
          name: test2
```

And got the following:
```
The Alertmanager "test" is invalid:
* spec.web.tlsConfig.keySecret.key: Required value
* spec.web.tlsConfig.cert.secret.key: Required value
```

The test doesn't need them I guess because we're not going through the client.

@simonpasquier any thoughts on how to address this?
