### ISSUE TITLE
Memory persistently high

### ISSUE THREAD

**Issue by envyj020** [prometheus-operator/prometheus-operator#5557]
**What happened?**
Prometheus operator memory consumption is extremely high.

**Did you expect to see something different?**
Prometheus operator is installed in multiple clusters and in all of them but one its memory usage is over the expected baseline. Please see below for more details.

**Environment**
AWS EKS - Kubernetes version 1.23

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.59.1`

* Kubernetes version information:
    **1.23**

* Kubernetes cluster kind:

    EKS managed by Terraform

* Manifests:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 40.3.1
    chart: kube-prometheus-stack-40.3.1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-prometheus-stack-operator
      release: prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-prometheus-stack-operator
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 40.3.1
        chart: kube-prometheus-stack-40.3.1
        heritage: Helm
        release: prometheus
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: category
                operator: In
                values:
                - prometheus
      containers:
      - args:
        - --kubelet-service=kube-system/prometheus-kube-prometheus-kubelet
        - --localhost=127.0.0.1
        - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.60.1
        - --config-reloader-cpu-request=200m
        - --config-reloader-cpu-limit=200m
        - --config-reloader-memory-request=50Mi
        - --config-reloader-memory-limit=50Mi
        - --thanos-default-base-image=quay.io//thanos/thanos:v0.28.0
        image: quay.io/prometheus-operator/prometheus-operator:v0.59.1
        imagePullPolicy: IfNotPresent
        name: kube-prometheus-stack
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccount: prometheus-kube-prometheus-operator
      serviceAccountName: prometheus-kube-prometheus-operator
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: prometheus
```

**Anything else we need to know?**:
The following PromQL query is used to determine prometheus operator container memory usage:

Query: `sum(avg_over_time(container_memory_working_set_bytes{pod=~"prometheus-kube-prometheus-operator.*", container="kube-prometheus-stack"}[6h])) by (container, pod, cluster) / 1024 / 1024`

```

{cluster="gp-qa", container="kube-prometheus-stack", pod="prometheus-kube-prometheus-operator-6bd4ffff89-h6qhs"}
34.65696072048612
{cluster="gp-beta", container="kube-prometheus-stack", pod="prometheus-kube-prometheus-operator-6bd4ffff89-b6scv"}
46.06166449652775
{cluster="gp-dev", container="kube-prometheus-stack", pod="prometheus-kube-prometheus-operator-6bd4ffff89-2tx5s"}
961.0594636292021
{cluster="gp-dispload", container="kube-prometheus-stack", pod="prometheus-kube-prometheus-operator-6bd4ffff89-l4ppq"}
283.95205078124985
{cluster="gp-mgmt", container="kube-prometheus-stack", pod="prometheus-kube-prometheus-operator-6bd4ffff89-46g5l"}
43.37699110243059
{cluster="gp-sandbox", container="kube-prometheus-stack", pod="prometheus-kube-prometheus-operator-6bd4ffff89-8qn9f"}
34.712879774305556
```

Operator managed resources:
Query: `sum(prometheus_operator_managed_resources) by (cluster)`

```
{cluster="gp-qa"}
18
{cluster="gp-beta"}
20
{cluster="gp-dev"}
24
{cluster="gp-dispload"}
20
{cluster="gp-mgmt"}
21
{cluster="gp-sandbox"}
18
```

Then retrieved two memory profiles from the operator, one after 30 minutes aprox of replacing the pod:
```
Showing nodes accounting for 1175.42MB, 99.32% of 1183.44MB total
Dropped 77 nodes (cum <= 5.92MB)
Showing top 10 nodes out of 24
      flat  flat%   sum%        cum   cum%
 1165.38MB 98.47% 98.47%  1165.38MB 98.47%  io.ReadAll
   10.04MB  0.85% 99.32%    10.04MB  0.85%  golang.org/x/net/http2.glob..func3
         0     0% 99.32%    10.04MB  0.85%  golang.org/x/net/http2.(*ClientConn).readLoop
         0     0% 99.32%    10.04MB  0.85%  golang.org/x/net/http2.(*clientConnReadLoop).processData
         0     0% 99.32%    10.04MB  0.85%  golang.org/x/net/http2.(*clientConnReadLoop).run
         0     0% 99.32%    10.04MB  0.85%  golang.org/x/net/http2.(*dataBuffer).Write
         0     0% 99.32%    10.04MB  0.85%  golang.org/x/net/http2.(*dataBuffer).lastChunkOrAlloc
         0     0% 99.32%    10.04MB  0.85%  golang.org/x/net/http2.(*pipe).Write
         0     0% 99.32%    10.04MB  0.85%  golang.org/x/net/http2.getDataBufferChunk
         0     0% 99.32%  1165.38MB 98.47%  io/ioutil.ReadAll
```

Then a second one after a few hours:

```
Showing nodes accounting for 773.75MB, 98.40% of 786.31MB total
Dropped 100 nodes (cum <= 3.93MB)
Showing top 10 nodes out of 38
      flat  flat%   sum%        cum   cum%
  752.77MB 95.73% 95.73%   753.27MB 95.80%  sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).literalStore
    7.28MB  0.93% 96.66%     7.28MB  0.93%  reflect.unsafe_NewArray
    5.50MB   0.7% 97.36%     5.50MB   0.7%  reflect.mapassign_faststr
       4MB  0.51% 97.87%        4MB  0.51%  k8s.io/client-go/tools/cache.MetaNamespaceKeyFunc
    2.70MB  0.34% 98.21%     4.20MB  0.53%  k8s.io/client-go/tools/cache.(*DeltaFIFO).queueActionLocked
       1MB  0.13% 98.34%   769.55MB 97.87%  sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).object
    0.50MB 0.064% 98.40%     4.01MB  0.51%  runtime.main
         0     0% 98.40%    26.15MB  3.33%  k8s.io/apimachinery/pkg/runtime.Decode
         0     0% 98.40%   770.05MB 97.93%  k8s.io/apimachinery/pkg/runtime.WithoutVersionDecoder.Decode
         0     0% 98.40%   770.05MB 97.93%  k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Deco
```
