### ISSUE TITLE
Wrong ProbeSpec.prober default path

### ISSUE THREAD

**Issue by jmuleiro** [prometheus-operator/prometheus-operator#5581]
**What happened?** I created a probe from the standard CRDs. Note that the [documentation](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#proberspec) explicitly says that ProbeSpec.prober.path is defaulted to `/probe`. However, I believe this is not the case, as it seems to default to `/` instead.

**Did you expect to see something different?** I expected the prober path to be defaulted to `/probe`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy the stack and a Blackbox Exporter deployment, manifests below
2. Create the probe itself
3. See results in Prometheus' UI targets (`kubectl port-forward svc/prometheus-operated 9090 -n monitoring`)
![image](https://github.com/prometheus-operator/prometheus-operator/assets/26482875/4b6687f4-020e-4229-8336-ce6a3bbb3c3a)

**Environment**

* Prometheus Operator version:

    `v0.64.1`
    
    

* Kubernetes version information:

    `v1.25.5-gke.2000`
    

* Kubernetes cluster kind:

    GKE

* Manifests:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blackbox-exporter
    spec:
      serviceAccountName: blackbox-exporter
      nodeSelector:
        kubernetes.io/os: linux
      securityContext: {}
      terminationGracePeriodSeconds: 60
      containers:
        - name: main
          image: quay.io/prometheus/blackbox-exporter:v0.23.0
          imagePullPolicy: IfNotPresent
          args: 
            - --config.file=/config/config.yaml
          volumeMounts:
            - name: config
              mountPath: /config
          resources: {}
          ports:
            - name: tcp
              protocol: TCP
              containerPort: 9115
      volumes:
        - name: config
          configMap:
            name: blackbox-exporter-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
data:
  config.yaml: |
    modules:
      http:
        prober: http
        timeout: 15s
        http: 
          valid_http_versions: 
            - "HTTP/1.1"
            - "HTTP/2.0"
          method: GET
          body_size_limit: 1MB
          follow_redirects: true
          fail_if_not_ssl: true
          preferred_ip_protocol: ip4
          ip_protocol_fallback: false
          tls_config:
            insecure_skip_verify: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blackbox-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
spec:
  selector:
    app.kubernetes.io/name: blackbox-exporter
  ports:
  - port: 9115
    targetPort: tcp
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-uptime
spec:
  jobName: blackbox
  prober:
    url: blackbox-exporter:9115
    scheme: http
  module: http
  interval: 15s
  scrapeTimeout: 15s
  targets:
    staticConfig:
      static:
        - "https://google.com"
      labels:
        monitor: test
  metricRelabelings:
    - sourceLabels:
        - "__address__"
      targetLabel: "__param_target"
    - sourceLabels:
        - "__param_target"
      targetLabel: "instance"
    - targetLabel: "__address__"
      replacement: blackbox-exporter:9115
```

* Prometheus Operator Logs:
No relevant logs:
```
level=info ts=2023-05-15T15:51:31.224069264Z caller=operator.go:1126 component=prometheusoperator key=monitoring/main msg="sync prometheus"
level=info ts=2023-05-15T15:51:33.129771404Z caller=operator.go:1126 component=prometheusoperator key=monitoring/main msg="sync prometheus"
level=info ts=2023-05-15T15:51:33.22070508Z caller=operator.go:1313 component=prometheusoperator key=monitoring/main msg="update prometheus status"
level=info ts=2023-05-15T15:51:34.634986184Z caller=operator.go:1313 component=prometheusoperator key=monitoring/main msg="update prometheus status"
```
