### ISSUE TITLE
Thanos sidecar volume name is correct after upgrading from 0.63 to 0.65

### ISSUE THREAD

**Issue by farodin91** [prometheus-operator/prometheus-operator#5595]
**What happened?**
correct name is used in the container template for prometheus but not for thanos.

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

create a Prometheus a with a named volume:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
  name: monitoring-stack-kube-prom-prometheus
  namespace: bla-system
spec:
  storage:
    volumeClaimTemplate:
      metadata:
        name: named-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 12Gi
        storageClassName: class
        volumeMode: Filesystem
  thanos:
    baseImage: quay.io/thanos/thanos
    version: v0.31.0
```

correct name is used in the container template for prometheus but not for thanos.

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
