### ISSUE TITLE
prometheus-agent: walCompression flag

### ISSUE THREAD

**Issue by zetaab** [prometheus-operator/prometheus-operator#5606]
**What happened?** 

I was specifying 

```
  walCompression: true
```

to prometheus-agent crd. However, it seems that its not supported

```
% kubectl logs prom-agent-k8s-agent-0
ts=2023-05-25T09:45:33.769Z caller=main.go:189 level=info msg="Experimental agent mode enabled."
The following flag(s) can not be used in agent mode: ["--storage.tsdb.wal-compression"]% 
```

**Did you expect to see something different?** walCompression should be perhaps removed from crd because it cannot be used with prometheus agent?

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  labels:
    app.kubernetes.io/component: prometheus-agent
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus-agent
    app.kubernetes.io/part-of: kube-prometheus
  name: k8s-agent
  namespace: monitoring
spec:
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus-agent
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus-agent
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  version: 2.44.0
  image: quay.io/prometheus/prometheus:v2.44.0
  replicas: 1
  replicaExternalLabelName: __replica__
  prometheusExternalLabelName: cluster
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 300m
      memory: 500Mi
  nodeSelector:
    kubernetes.io/os: linux
  serviceAccountName: prometheus-k8s
  walCompression: true
```

and check the created statefulset logs

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
