### ISSUE TITLE
Add examples for prometheus-agent and scrapeconfig usage

### ISSUE THREAD

**Issue by slashpai** [prometheus-operator/prometheus-operator#5607]
**What is missing?**

Examples for trying prometheus-agent and scrapeconfig cr is missing

**Why do we need it?**

While the feature is in alpha1 version It would be still helpful for new users to try quickly if we have example documented

**Environment**

NA

* Prometheus Operator version:

NA
    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:

agent mode available from version 0.64 and scrape config from 0.65

**Comment by slashpai** [comment]
cc: @xiu :)

**Comment by xiu** [comment]
Thanks for the ping :) Will push something

**Comment by slashpai** [comment]
I tried something, let me know if this is ok. I can create PR for same

I used in-cluster service as an example because I didnt had any external node to test, but that works same way. (I used kube-prometheus cluster to do quick testing)

```yaml
apiVersion: v1
data:
  targets.yaml: |
    - labels:
        job: alertmanager
      targets:
      - alertmanager-main.monitoring.svc.cluster.local:8080
    - labels:
        job: prometheus
      targets:
      - prometheus-k8s.monitoring.svc.cluster.local:9090
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: scrape-file-sd-targets
  namespace: monitoring
```

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: scrape-config-example
  namespace: default
  labels:
    app.kubernetes.io/name: scrape-config-example
spec:
  fileSDConfigs:
    - files:
      - /etc/prometheus/configmaps/scrape-file-sd-targets/targets.yaml
      refreshInterval: 15s
```

Add configMap in Prometheus CR

``` yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: 2.44.0
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: alertmanager-main
      namespace: monitoring
      port: web
  image: quay.io/prometheus/prometheus:v2.44.0
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/version: 2.44.0
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 2
  ruleNamespaceSelector: {}
  ruleSelector: {}
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector: {}
  version: 2.44.0
  configMaps:
  - scrape-file-sd-targets
```

will include sa, role and role binding in examples folder not added in here

cc: @xiu

**Comment by slashpai** [comment]
Adding static config example as well (Here also I used a in-cluster service url to test). This can be replaced with external node exporter or any other host

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: scrape-config-static-config-example
  namespace: default
  labels:
    app.kubernetes.io/name: scrape-config-static-config-example
spec:
  staticConfigs:
    - labels:
        job: alertmanager
      targets:
      - alertmanager-main.monitoring.svc.cluster.local:8080
    - labels:
        job: prometheus
      targets:
      - prometheus-k8s.monitoring.svc.cluster.local:9090
```

I will create PR based on this.

@xiu If you have better examples let me know :)

**Comment by simonpasquier** [comment]
for static config, maybe an example with federation makes more sense?

**Comment by slashpai** [comment]
@xiu /@simonpasquier I could find a demo node exporter from prometheus so I think we can add this in example. This config is working

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: example-scrapeconfig
spec:
  staticConfigs:
    - targets:
        - node.demo.do.prometheus.io
      labels:
        app: node-demo
  metricsPath: /metrics
```
