### ISSUE TITLE
ScrapeConfig objects don't work properly when Prometheus sharding is used

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#5637]
`generateScrapeConfig` gets the shard number as an input parameter but it doesn't make use of it. As a result, targets from ScrapeConfigs are scraped by all shards while they should be distributed.
 
https://github.com/prometheus-operator/prometheus-operator/blob/d3c37ea81bf3afcd7030819b054f65780e69a237/pkg/prometheus/promcfg.go#L2135-L2140

**Comment by infdahai** [comment]
hi, @simonpasquier I am new here and I want to take this assignment.

**Comment by infdahai** [comment]
The task seems unnecessary from the latest codebase. @simonpasquier

**Comment by ArthurSens** [comment]
Hey @infdahai, I believe this is still an issue, the `shard` argument is not used anywhere in the mentioned function. The correct behavior is that the shard number is used to split targets between all shards

**Comment by infdahai** [comment]
> Hey @infdahai, I believe this is still an issue, the `shard` argument is not used anywhere in the mentioned function. The correct behavior is that the shard number is used to split targets between all shards

Thanks. I'll look into it

**Comment by dipeti** [comment]
I am seeing the same issue with my ScrapedConfig CRDs. Each shard picks up all specified targets, thus every target gets scraped by all prom-agents. 
operator version: v0.65.1

**Comment by chiukapoor** [comment]
@dipeti how may I check if very target gets scraped by all prom-agents?

**Comment by nicolastakashi** [comment]
@chiukapoor if all instances have the same amount of targets, this might be a good indicator of this issue.

**Comment by dipeti** [comment]
ive added the following to sort this: 
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: config
  namespace: prom
spec:
  staticConfigs:
  - targets:
    -  some-service:8080
  metricsPath: /metrics
  {{- if gt .Values.prometheusAgent.shards 1 }}
  {{/* relabeling manually for when sharding is enabled due to this bug: https://github.com/prometheus-operator/prometheus-operator/issues/5637 */}} 
  relabelings:
  - action: hashmod
    modulus: {{ .Values.prometheusAgent.shards }}
    targetLabel: __tmp_hash
  - action: keep
    regex: $(SHARD)
    sourceLabels: [__tmp_hash]
    {{- end }}
{{ end }}

```
