### ISSUE TITLE
Unable to use globally configured receivers in namespaced AlertmanagerConfigs

### ISSUE THREAD

**Issue by llamahunter** [prometheus-operator/prometheus-operator#5653]
**What did you do?**

We have a global route for our Alertmanager that collects any alerts unhandled by child routes and delivers them to an 'orphaned alert' receiver, which sends alerts to a special slack channel and to Big Panda. We also have a separate global receiver configured that also routes events to BigPanda, but is not used globally.
We then use AlertmanagerConfig objects per namespace to route alerts on a team by team basis to different slack channels. However, we would also like all alerts to also go to BigPanda. I tried having each of these namespaced AlertmanagerConfig objects reference the globally configured receiver, but it doesn't seem to work. It's as though the AlertmanagerConfigs can't use the global receivers, even though the operator eventually puts all the routes and receivers into one big configuration file? We cannot have each individual AlertmanagerConfig configure its own route to BigPanda, since there are api_keys and such that the creators of those AlertmanagerConfigs don't have access to.

**Did you expect to see some different?**

I expected the global receivers to be able to be referenced from namespaced AlertmanagerConfigs

**Environment**

* Prometheus Operator version:

quay.io/prometheus-operator/prometheus-operator:v0.63.0

* Kubernetes version information:

Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.25.9-eks-0a21954

* Kubernetes cluster kind:

eks

* Manifests:

Global Alertmanager configuration from secret

```
global:
  resolve_timeout: 5m
  slack_api_url: .... elided .... 
inhibit_rules:
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = critical
  target_matchers:
  - severity =~ warning|info
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = warning
  target_matchers:
  - severity = info
- equal:
  - namespace
  source_matchers:
  - alertname = InfoInhibitor
  target_matchers:
  - severity = info
receivers:
- name: default-route
  slack_configs:
  - channel: '#orphaned-k8s-alerts'
    text: |-
      {{ range .Alerts }}
        *Alert:* {{ if .Annotations.summary }}{{ .Annotations.summary }}{{ else }}{{ .Labels.alertname }}{{ end }} - "{{ .Labels.severity }}"
        *Description:* {{ if .Annotations.description }}{{ .Annotations.description }}{{ else }}{{ .Annotations.message }}{{ end }}
        *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> {{ if .Annotations.runbook_url }}*Runbook:* <{{ .Annotations.runbook_url }}|:spiral_note_pad:>{{ end }}
        *Details:*
        {{ range .Labels.SortedPairs }} - *{{ .Name }}:* "{{ .Value }}"
        {{ end }}
      {{ end }}
    title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing
      | len }}{{ end }}] Monitoring Event Notification'
  webhook_configs:
  - http_config:
      bearer_token: .... elided ....
    send_resolved: true
    url: .... elided ....
- name: big-panda
  webhook_configs:
  - http_config:
      bearer_token: .... elided ....
    send_resolved: true
    url: .... elided ....
- name: watchdog-route
  webhook_configs:
  - url: .... elided ....
- name: "null"
route:
  group_by:
  - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: default-route
  repeat_interval: 12h
  routes:
  - matchers:
    - alertname = InfoInhibitor
    receiver: "null"
  - group_interval: 1m
    group_wait: 30s
    matchers:
    - alertname = Watchdog
    receiver: watchdog-route
    repeat_interval: 1m
templates: []
```

namespaced AlertmanagerConfig custom resource

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  creationTimestamp: "2023-06-07T20:50:18Z"
  generation: 1
  name: echo-rdlee-config
  namespace: echo-rdlee
  resourceVersion: "30789567"
  uid: d3de33ea-2c67-4f8f-817f-eb4c977f4b8d
spec:
  receivers:
  - name: "null"
  - name: echo-rdlee-slack
    slackConfigs:
    - channel: tek1-echo-rdlee-alerts
      sendResolved: true
      text: |-
        {{ range .Alerts }}
          *Alert:* {{ if .Annotations.summary }}{{ .Annotations.summary }}{{ else }}{{ .Labels.alertname }}{{ end }} - "{{ .Labels.severity }}"
          *Description:* {{ if .Annotations.description }}{{ .Annotations.description }}{{ else }}{{ .Annotations.message }}{{ end }}
          *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> {{ if .Annotations.runbook_url }}*Runbook:* <{{ .Annotations.runbook_url }}|:spiral_note_pad:>{{ end }}
          *Details:*
          {{ range .Labels.SortedPairs }} - *{{ .Name }}:* "{{ .Value }}"
          {{ end }}
        {{ end }}
      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing
        | len }}{{ end }}] Monitoring Event Notification'
  route:
    groupBy:
    - job
    groupInterval: 5m
    groupWait: 30s
    receiver: "null"
    repeatInterval: 12h
    routes:
    - continue: true
      matchers:
      - matchType: '!='
        name: alertname
        value: InfoInhibitor
      receiver: echo-rdlee-slack
    - matchers:
      - matchType: '!='
        name: alertname
        value: InfoInhibitor
      receiver: big-panda
```

* Prometheus Operator Logs:

```
level=warn ts=2023-06-07T20:45:49.374929855Z caller=operator.go:1167 component=alertmanageroperator msg="skipping alertmanagerconfig" error="route[1]: receiver \"big-panda\" not found" alertmanagerconfig=echo-rdlee/echo-rdlee-config namespace=monitoring alertmanager=kube-prometheus-stack-alertmanager
```

**Anything else we need to know?**:

**Comment by ANGkeith** [comment]
This is my usecase, 

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    alertmanager: load
  name: foo
  namespace: test
spec:
  receivers:
  - name: pagerduty
    pagerdutyConfigs:
    - routingKey:
        key: application
        name: pagerduty
      severity: 'info'
  # - name: "null"  <--- this is required
  route:
    continue: false
    groupBy:
    - cluster
    - alertname
    matchers:
    - matchType: =
      name: namespace
      value: test
    receiver: pagerduty
    routes:
    - matchers:
      - matchType: =~
        name: alertname
        value: InfoInhibitor|Watchdog
      receiver: "null"                                                            #  Is there any way i can reference the global receiver ? 
```

Is this currently possible ?
