### ISSUE TITLE
MuteTimeInterval - alerts out of time schedule still trigger

### ISSUE THREAD

**Issue by justincilia** [prometheus-operator/prometheus-operator#5665]
**What happened?**
MuteTimeInterval not working as expected 

**Did you expect to see something different?**
Alerts with time interval outside of schedule should be muted

**How to reproduce it (as minimally and precisely as possible)**:
In alertmanager-config.yaml 

```
muteTimeIntervals:
    - name: day
      timeIntervals:
        - times: 
          - endTime   : 14:00
            startTime : 08:00
           
    - name: night
      timeIntervals:
        - times:
          - endTime  : 07:59
            startTime: 00:01
```

```
route:
  receiver: no-alert
  groupWait: 30s
  groupInterval: 1m
  repeatInterval: 30m
  groupBy:
  - alertname

  routes:
  - receiver: slack-notif
    matchers:
      - name: severity
        value: warning
        matchType: = 
    muteTimeIntervals:
      - night   
     
  - receiver: slack-devops-notifications
    matchers:
      - name: severity
        value: warning
        matchType: =  
    muteTimeIntervals:
      - day
```

**Environment**

* Prometheus Operator version:

   v0.63.0
    
    
   

* Kubernetes version information:

v1.26.1
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
