### ISSUE TITLE
alertmanagerConfigMatcherStrategy always adding namespace labels

### ISSUE THREAD

**Issue by rgarcia89** [prometheus-operator/prometheus-operator#5704]
**What happened?**
Setting `alertmanagerConfigMatcherStrategy` type to `None` should normally not add any namespace information to routes that where defined via an AlertmanagerConfig. I also know that this was working properly - however I cannot tell you until when.

**Did you expect to see something different?**
```
  alertmanagerConfigMatcherStrategy:
    type: None
```
should prevent namespace marker 
```
  routes:
  - receiver: ote/alertmanager-self/null
    group_by:
    - cluster
    matchers:
    - namespace="ote"
    continue: true
```

**How to reproduce it (as minimally and precisely as possible)**:
Deploy an alertmanager with above shown config and a alertmanagerconfig.

**Environment**

* Prometheus Operator version: v0.66.0

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information: v1.25.6

    `kubectl version`
    

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
I don't see the same behavior with the [example manifests](https://github.com/prometheus-operator/prometheus-operator/tree/main/example/user-guides/alerting) and v0.66.0. Can you double check?

![image](https://github.com/prometheus-operator/prometheus-operator/assets/2587585/f7c06b8f-2f03-46ea-bbb8-28d3d49d341c)

**Comment by rgarcia89** [comment]
What do you mean with you don't see? Isn't it just there in your screenshot `receiver: default/config-example/webhook`?

**Comment by simonpasquier** [comment]
there's no `matchers` with the namespace of origin.

**Comment by rgarcia89** [comment]
Is `default` not the namespace of origin in your case?
I for me case get the following back - where `ote` is the namespace in which I have deployed the alertmanagerconfig.

```
route:
  receiver: "null"
  continue: false
  routes:
  - receiver: ote/config-example/webhook
    group_by:
```

Wasn't the intention that you described here https://github.com/prometheus-operator/prometheus-operator/issues/3737#issuecomment-1326667523 to get rid of this?
