### ISSUE TITLE
AlertManager Continuous reconcile loop when setting revision history limit

### ISSUE THREAD

**Issue by rouke-broersma** [prometheus-operator/prometheus-operator#5712]
**What happened?**

We use ArgoCD with a fully gitops deployment model. Due to this deployment model we have no need for revisions. In fact we wish to not have them because they clutter the UI for no reason. Many charts and operators do not allow us to set the revision history limit, so we are creating an admission webhook to set the revision history limit for all deployments, daemonsets and statefulsets in our cluster.

However even though prometheus-operator does not provide any way to set the revision history limit (as far as I can find) it does try to enforce the revision history limit for the AlertManager statefulset (possibly other managed resources as well).

This causes a continuous reconciliation and recreation (because revision history limit on sts is immutable) of alertmanager on our environments.

**Did you expect to see something different?**

The operator does not allow setting the revision history limit, so it should not care when it's default gets modified by a custom admission controller. It tries to enforce setting it to 10, and I see no reason for it to do that.

**How to reproduce it (as minimally and precisely as possible)**:

Create admission webhook that modifies the statefulset revision history limit before admission, deploy new AlertManager instance. Observe prometheus-operator continously destroying and recreating the statefulset.

**Environment**

* Prometheus Operator version:

    `prometheus-operator:v0.65.2`
    
    

* Kubernetes version information:

 ```
clientVersion:
    buildDate: "2023-06-14T09:47:38Z"
    compiler: gc
    gitCommit: 25b4e43193bcda6c7328a6d147b1fb73a33f1598
    gitTreeState: clean
    gitVersion: v1.27.3
    goVersion: go1.20.5
    major: "1"
    minor: "27"
    platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
    buildDate: "2023-05-19T00:03:21Z"
    compiler: gc
    gitCommit: b278d3784e784ae3d8e986fe641beb572e08ecc0
    gitTreeState: clean
    gitVersion: v1.26.3
    goVersion: go1.19.7
    major: "1"
    minor: "26"
    platform: linux/amd64
```

* Kubernetes cluster kind:

  `AKS`

* Prometheus Operator Logs:

```
level=info ts=2023-06-21T12:58:47.2969237Z caller=operator.go:736 component=alertmanageroperator key=prometheus/prometheus-stack-kube-prom-alertmanager msg="recreating AlertManager StatefulSet because the update operation wasn't possible" reason="Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden"
```

**Anything else we need to know?**:
