### ISSUE TITLE
basicAuth in PodMonitor or ServiceMonitor generates not working Prometheus configuration

### ISSUE THREAD

**Issue by spimmer** [prometheus-operator/prometheus-operator#5721]
**What happened?**
- configured basicAuth for PodMonitor & ServiceMonitor as follows:
``` yaml
basicAuth:
  password:
    name: basic-auth
    key: password
  username:
    name: basic-auth
    key: username
```
- basicAuth section in Prometheus configuration YAML will be generated as follows:
``` yaml
basic_auth:
  username: |
    demouser
  password: |
    demopassword
```
- target will show up in Prometheus WebUI with message "_server returned HTTP status 401 Unauthorized_"

**Did you expect to see something different?**
I expect Prometheus generated configuration looking like this:
``` yaml
basic_auth:
  username: demouser
  password: demopassword
```

**How to reproduce it (as minimally and precisely as possible)**:
- have a scrape target requiring basic authentication
- create a secret containing the valid credentials for basic authentication
- create a PodMonitor or ServiceMonitor referencing the credentials of the just created secret
- lookup the generated scrape config in the Prometheus configuration YAML
- verify the basicAuth section of the scrape config contains pipes and is not a oneliner

**Environment**

* Prometheus Operator version:

    `v0.66.0`
    
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3+rke2r1", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T22:01:18Z", GoVersion:"go1.20.5 X:boringcrypto", Compiler:"gc", Platform:"linux/arm64"}`
    

* Kubernetes cluster kind:

[RKE2](https://github.com/rancher/rke2) deployed with following command:
`curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL=v1.27 INSTALL_RKE2_METHOD=tar sh -`

* Manifests:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-basic-auth
  namespace: prometheus
  labels:
    release: prometheus
data:
  username: ZGVtb3VzZXIK
  password: ZGVtb3Bhc3N3b3JkCg==
type: Opaque
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: thanos-query
  namespace: prometheus
  labels:
    release: prometheus
spec:
  podMetricsEndpoints:
  - port: http
    basicAuth:
      password:
        name: thanos-basic-auth
        key: password
      username:
        name: thanos-basic-auth
        key: username
  namespaceSelector:
    matchNames:
    - thanos
  selector:
    matchLabels:
        app.kubernetes.io/component: query
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-query
  namespace: prometheus
  labels:
    release: prometheus
spec:
  endpoints:
  - port: http
    basicAuth:
      password:
        name: thanos-basic-auth
        key: password
      username:
        name: thanos-basic-auth
        key: username
  namespaceSelector:
    matchNames:
    - thanos
  selector:
    matchLabels:
      app.kubernetes.io/component: query
```

* Prometheus Operator Logs:

Relevant generated parts of the Prometheus config:
```yaml
- job_name: serviceMonitor/prometheus/thanos-query/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - thanos
  basic_auth:
    username: |
      demouser
    password: |
      demopassword
  relabel_configs:
  - source_labels:
    - job
    target_label: __tmp_prometheus_job_name
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app_kubernetes_io_component
    - __meta_kubernetes_service_labelpresent_app_kubernetes_io_component
    regex: (query);true
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: http
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Node;(.*)
    replacement: ${1}
    target_label: node
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Pod;(.*)
    replacement: ${1}
    target_label: pod
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - action: drop
    source_labels:
    - __meta_kubernetes_pod_phase
    regex: (Failed|Succeeded)
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - target_label: endpoint
    replacement: http
  - source_labels:
    - __address__
    target_label: __tmp_hash
    modulus: 1
    action: hashmod
  - source_labels:
    - __tmp_hash
    regex: 0
    action: keep
  metric_relabel_configs: []
- job_name: podMonitor/prometheus/thanos-query/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - thanos
  basic_auth:
    username: |
      demouser
    password: |
      demopassword
  relabel_configs:
  - source_labels:
    - job
    target_label: __tmp_prometheus_job_name
  - action: drop
    source_labels:
    - __meta_kubernetes_pod_phase
    regex: (Failed|Succeeded)
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_label_app_kubernetes_io_component
    - __meta_kubernetes_pod_labelpresent_app_kubernetes_io_component
    regex: (query);true
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_container_port_name
    regex: http
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - target_label: job
    replacement: prometheus/thanos-query
  - target_label: endpoint
    replacement: http
  - source_labels:
    - __address__
    target_label: __tmp_hash
    modulus: 1
    action: hashmod
  - source_labels:
    - __tmp_hash
    regex: 0
    action: keep
  metric_relabel_configs: []
```

**Anything else we need to know?**:
To verify this is related to a wrong generated configuration by Prometheus Operator I did the following:
- ran Prometheus just as binary
- add a web config with basic authentication for Prometheus
- add a scrape config to scrape itself with the following config (which **will work**):
```yaml
scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
    basic_auth:
      username: demouser
      password: demopassword
```
- change the scrape config to the following config (which **will not work** and return "_server returned HTTP status 401 Unauthorized_"):
```yaml
scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
    basic_auth:
      username: |
        demouser
      password: |
        demopassword
```
