### ISSUE TITLE
ServiceMonitor `bearerTokenSecret` can't specify secret namespace

### ISSUE THREAD

**Issue by Daniel-Vaz** [prometheus-operator/prometheus-operator#5730]
**What is missing?**

When we need to create a ServiceMonitor that needs to specify `spec.endpoints.bearerTokenSecret`, we can only specify `name`, `key`, `optional`. We can't specify the namespace where the secret exists.

By default the Operator tries to search for the secret and the specified key in the same namespace where it is deployed.
For example logs from a Operator deployed inside the namespace `monitoring-system`:

```
level=warn ts=2023-07-07T08:24:09.652363588Z caller=resource_selector.go:174 component=prometheusoperator msg="skipping servicemonitor" error="failed to get bearer token: failed to get token from secret: unable to get secret \"ansible-awx-api-metrics-token\": secrets \"ansible-awx-api-metrics-token\" not found" servicemonitor=ansible-awx/awx-servicemonitor namespace=monitoring-system prometheus=kps-prometheus
```

The Servicemonitor in question was deployed in the `ansible-awx` namespace, with the following definition:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: awx-servicemonitor
spec:
  endpoints:
  - port: http
    path: /api/v2/metrics
    tlsConfig:
      insecureSkipVerify: true 
    bearerTokenSecret:
      name: ansible-awx-api-metrics-token
      key: tokenFile
    relabelings:
    - regex: (container|endpoint|namespace|pod|service)
      action: labeldrop
    - action: labelmap
      regex: __meta_kubernetes_service_label_(.+)
  selector:
    matchLabels:
      app.kubernetes.io/component: "awx"
  namespaceSelector:
    matchNames:
    - ansible-awx
```

**Why do we need it?**

To facilitate the usage of Prometheus Operator in a multi-tenant cluster, where `Secrets` and `ServiceMonitors` are completely managed by the consumer of the Operator on their own namespace on their own.

* Prometheus Operator version:
    * `quay.io/prometheus-operator/prometheus-operator:v0.66.0`
