### ISSUE TITLE
Alertmanager EmailConfig password trailing slash

### ISSUE THREAD

**Issue by agombault** [prometheus-operator/prometheus-operator#5731]
**What happened

Hello, I'm facing an issue with line breaks at the end of the password when retrieving it from secret on AlermanagerConfig > EmailConfigs.

The password is compiled as multiline string, so my SMTP server rejects my authentication due to this `\n`.

Here is the result of the alertmanager.env.yaml generated file:

```bash
k -n monitoring exec --tty --stdin pod/alertmanager-main-0 -- cat /etc/alertmanager/config_out/alertmanager.env.yaml
```

```yaml
route:
  receiver: monitoring/default/default
  group_by:
  - '...'
  routes:
  - receiver: monitoring/production-email/email
    group_by:
    - alertname
    - host
    match:
      severity: critical
    continue: true
  group_interval: 5m
  repeat_interval: 4h
receivers:
- name: monitoring/default/default
- name: monitoring/production-email/email
  email_configs:
  - send_resolved: true
    to: test-receiver@example.com
    from: test@example.com
    smarthost: in-v3.mailjet.com:587
    auth_username: username
    auth_password: |
      password
    html: '{{ template "email.tmpl" . }}'
    require_tls: true
```

**Did you expect to see something different?**

```yaml
route:
  receiver: monitoring/default/default
  group_by:
  - '...'
  routes:
  - receiver: monitoring/production-email/email
    group_by:
    - alertname
    - host
    match:
      severity: critical
    continue: true
  group_interval: 5m
  repeat_interval: 4h
receivers:
- name: monitoring/default/default
- name: monitoring/production-email/email
  email_configs:
  - send_resolved: true
    to: test-receiver@example.com
    from: test@example.com
    smarthost: in-v3.mailjet.com:587
    auth_username: username
    auth_password: password
    html: '{{ template "email.tmpl" . }}'
    require_tls: true
```

I think password string should be sanitized here -> https://github.com/prometheus-operator/prometheus-operator/blob/e21bdb5675e24d94504d530fd19fb89627a631a3/pkg/alertmanager/amcfg.go#L943
Why do you think?

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `v0.66.0`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
```

* Kubernetes cluster kind:

   EKS 1.26

* Manifests:

AlertmanagerConfig manifest
```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: production-email
  labels:
    alertmanagerConfig: main
spec:
  route:
    receiver: email
    groupBy:
      - alertname
      - host
    matchers:
      - name: severity
        value: critical
  receivers:
    - name: email
      emailConfigs:
        - sendResolved: true
          to: "test-receiver@example.com"
          from: test@example.com
          smarthost: in-v3.mailjet.com:587
          authUsername: username
          authPassword:
            name: alertmanager-main
            key: email_password
          requireTLS: true
          html: '{{ template "email.tmpl" . }}'
```

Secret manifest
```yaml
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-main
    namespace: monitoring
type: Opaque
data:
    email_password: cGFzc3dvcmQK
```
