### ISSUE TITLE
CRD scrapeConfigs doesn't honour scheme: https and tlsConfig

### ISSUE THREAD

**Issue by vladimir9876** [prometheus-operator/prometheus-operator#5754]
**What happened?**
I've deployed:

<pre>
  scheme: HTTPS
  tlsConfig:
        insecureSkipVerify: true
</pre>

within my ScrapeConfig CRD but it's not reflected in the prometheus config.
scheme stays http, and tlsConfig is not present.

**Did you expect to see something different?**

Yes.
I expected these directives to be applied to the prometheus config.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

v0.66.0
    
    

* Kubernetes version information:

v1.26.4+k3s1
    

* Kubernetes cluster kind:

k3s (part of rancher desktop)

* Manifests:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: ldap
  namespace: monitoring
  labels:
    test: value
spec:
  scheme: HTTPS
  staticConfigs:
    - targets:
      - myserver.com:9330
  tlsConfig:
    insecureSkipVerify: true
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
