### ISSUE TITLE
service "kube-prometheus-stack-operator" not found

### ISSUE THREAD

**Issue by droslean** [prometheus-operator/prometheus-operator#5779]
Error:

```console
Error from server (InternalError): error when creating "prometheusrule.yaml": Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "https://kube-prometheus-stack-operator.kube-prometheus-stack.svc:443/admission-prometheusrules/validate?timeout=10s": service "kube-prometheus-stack-operator" not found
```

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
  name: prometheus-custom-alerts
  namespace: monitoring
spec:
  groups:
  - name: example
    rules:
    - alert: InstanceNotReporting
      expr: absent(aviation_up{domain="example.com"} == 1) for 5m
      labels:
        severity: critical
      annotations:
        summary: "Instance in domain example.com not reporting"
        description: "Instance in domain example.com has not been reporting for more than 5 minutes."

```

Operator image: `quay.io/prometheus-operator/prometheus-operator:v0.66.0`
Version: `v0.66.0`
