### ISSUE TITLE
help me, why i can’t find my pod in prometheus targets

### ISSUE THREAD

**Issue by fakeache** [prometheus-operator/prometheus-operator#5793]
this is my serviceMonitor.yaml, and my springboot yaml, and the clusterRole.yaml, please help me why i can’t find my pod in prometheus targets 
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zhuque-drug-service
  namespace: monitoring
  labels:
    k8s-app: zhuque-drug-service
spec:
        # namespaceSelector:
        #    matchNames:
        #    - monitoring
  endpoints:
  - interval: 5s
    port: zhuque-drug-service-svc-endpoint
    scheme: http
    path: /actuator/prometheus
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: zhuque-drug-service
      k8s-app: zhuque-drug-service

```
springboot yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zhuque-drug-service-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zhuque-drug-service
  template:
    metadata:
      labels:
        app: zhuque-drug-service
    spec:
      containers:
        - image: 10.101.12.128/zhuque/zhuque-drug-service:0.0.1
          name: zhuque-drug-service
          imagePullPolicy: Always
          ports:
            - containerPort: 9290
          env:
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  name: myconfigmap
                  key: active_profile
          volumeMounts:
            - name: zhuque-oss
              mountPath: /mnt/zhuque_goofys
      imagePullSecrets:
        - name: docker-secret
      volumes:
        - name: zhuque-oss
          hostPath:
            path: /mnt/zhuque_goofys
---

apiVersion: v1
kind: Service
metadata:
  name: zhuque-drug-service
  labels:
    app: zhuque-drug-service
spec:
  selector:
    app: zhuque-drug-service
  type: NodePort
  ports:
    - name: zhuque-drug-service-svc-endpoint
      # port: 9091
      port: 9290
      targetPort: 9290
      protocol: TCP
      nodePort: 30020
```
clusterRole.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.57.0
  name: prometheus-operator
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - alertmanagers/finalizers
  - alertmanagerconfigs
  - prometheuses
  - prometheuses/finalizers
  - prometheuses/status
  - thanosrulers
  - thanosrulers/finalizers
  - servicemonitors
  - podmonitors
  - probes
  - prometheusrules
  - services
  - endpoints
  - pods
  - nodes
  - nodes/proxy
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - nodes/metrics
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  - endpoints
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create

```
