### ISSUE TITLE
AlertmanagerConfig not being merged

### ISSUE THREAD

**Issue by wonderphil** [prometheus-operator/prometheus-operator#5808]
**What did you do?**

Added AlertmanagerConfig CRD and its not being picked up and merged into the config

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    alertmanagerConfig: alertmanager-cfg
    argocd.argoproj.io/instance: control-cluster-config
  name: alertmanager-cfg-platform
  namespace: observability
spec:
  receivers:
    - name: platform-p1-receivers
      slackConfigs:
        - channel: '#rnd_platform_nsp_alerts'
          sendResolved: true
    - name: platform-slack-receivers
      slackConfigs:
        - channel: '#rnd_platform_nsp_alerts'
          sendResolved: true
    - name: platform-pagerduty-receivers
  route:
    receiver: platform-slack-receivers
    routes:
      - matchers:
          - matchType: '=~'
            name: namespace
            value: >-
              argocd|azure-workload-identity-system|cert-manager|core|default|external-secrets|gatekeeper-system|istio-system|kube-node-lease|kube-public|kyverno|observability
        receiver: platform-slack-receivers
        routes:
          - matchers:
              - matchType: '='
                name: severity
                value: p1
            receiver: platform-p1-receivers
```

and the alertmanager has this config:

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: prometheus-alertmanager
  namespace: observability
spec:
  alertmanagerConfigNamespaceSelector:
    matchLabels:
      alertmanagerConfig: alertmanager-cfg
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: alertmanager-cfg
```

**Did you expect to see some different?**

Expected that the AlertmanagerConfig to picked up and merged into the alert manager config

**Environment**

Running kube-prometheus-stack version 48.1.1

* Prometheus Operator version:

    quay.io/prometheus-operator/prometheus-operator:v0.66.0

* Kubernetes version information:

   Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"96681bbd239a00e8a5533bf8aa11afceea7b6d8c", GitTreeState:"clean", BuildDate:"2023-06-12T18:44:47Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

    Azure Kube service

* Prometheus Operator Logs:

```
level=debug ts=2023-08-14T06:31:41.507684141Z caller=operator.go:355 component=alertmanageroperator msg="AlertmanagerConfig updated"
level=info ts=2023-08-14T06:31:41.507787557Z caller=operator.go:655 component=alertmanageroperator key=observability/prometheus-alertmanager msg="sync alertmanager"
level=debug ts=2023-08-14T06:31:41.507851454Z caller=operator.go:1053 component=alertmanageroperator msg="filtering namespaces to select AlertmanagerConfigs from" namespaces= namespace=observability alertmanager=prometheus-alertmanager
level=debug ts=2023-08-14T06:31:41.507869925Z caller=operator.go:1104 component=alertmanageroperator msg="selected AlertmanagerConfigs" alertmanagerconfigs= namespace=observability prometheus=prometheus-alertmanager
level=debug ts=2023-08-14T06:31:41.51374919Z caller=klog.go:84 component=k8s_client_runtime func=Infof msg="GET [https://172.20.0.1:443/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager](https://172.20.0.1/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager) 200 OK in 5 milliseconds"
level=debug ts=2023-08-14T06:31:41.519913114Z caller=klog.go:84 component=k8s_client_runtime func=Infof msg="GET [https://172.20.0.1:443/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager-generated](https://172.20.0.1/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager-generated) 200 OK in 4 milliseconds"
level=debug ts=2023-08-14T06:31:41.529708988Z caller=klog.go:84 component=k8s_client_runtime func=Infof msg="PUT [https://172.20.0.1:443/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager-generated](https://172.20.0.1/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager-generated) 200 OK in 9 milliseconds"
level=debug ts=2023-08-14T06:31:41.535232495Z caller=klog.go:84 component=k8s_client_runtime func=Infof msg="GET [https://172.20.0.1:443/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager-tls-assets-0](https://172.20.0.1/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager-tls-assets-0) 200 OK in 4 milliseconds"
level=debug ts=2023-08-14T06:31:41.545962513Z caller=klog.go:84 component=k8s_client_runtime func=Infof msg="PUT [https://172.20.0.1:443/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager-tls-assets-0](https://172.20.0.1/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager-tls-assets-0) 200 OK in 10 milliseconds"
level=debug ts=2023-08-14T06:31:41.550587516Z caller=klog.go:84 component=k8s_client_runtime func=Infof msg="DELETE [https://172.20.0.1:443/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager-tls-assets-1](https://172.20.0.1/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager-tls-assets-1) 404 Not Found in 4 milliseconds"
level=debug ts=2023-08-14T06:31:41.550800963Z caller=operator.go:1625 component=alertmanageroperator msg="tls-asset secret: stored"
level=debug ts=2023-08-14T06:31:41.555310016Z caller=klog.go:84 component=k8s_client_runtime func=Infof msg="GET [https://172.20.0.1:443/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager-web-config](https://172.20.0.1/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager-web-config) 200 OK in 4 milliseconds"
level=debug ts=2023-08-14T06:31:41.563514967Z caller=klog.go:84 component=k8s_client_runtime func=Infof msg="PUT [https://172.20.0.1:443/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager-web-config](https://172.20.0.1/api/v1/namespaces/observability/secrets/alertmanager-prometheus-alertmanager-web-config) 200 OK in 7 milliseconds"
level=debug ts=2023-08-14T06:31:41.567733237Z caller=klog.go:84 component=k8s_client_runtime func=Infof msg="GET [https://172.20.0.1:443/api/v1/namespaces/observability/services/alertmanager-operated](https://172.20.0.1/api/v1/namespaces/observability/services/alertmanager-operated) 200 OK in 3 milliseconds"
level=debug ts=2023-08-14T06:31:41.588672504Z caller=klog.go:84 component=k8s_client_runtime func=Infof msg="PUT [https://172.20.0.1:443/api/v1/namespaces/observability/services/alertmanager-operated](https://172.20.0.1/api/v1/namespaces/observability/services/alertmanager-operated) 200 OK in 20 milliseconds"
level=debug ts=2023-08-14T06:31:41.589484302Z caller=operator.go:705 component=alertmanageroperator key=observability/prometheus-alertmanager msg="new statefulset generation inputs match current, skipping any actions"
level=debug ts=2023-08-14T06:31:41.606915382Z caller=klog.go:84 component=k8s_client_runtime func=Infof msg="GET [https://172.20.0.1:443/api/v1/namespaces/observability/pods?labelSelector=alertmanager%3Dprometheus-alertmanager%2Capp.kubernetes.io%2Finstance%3Dprometheus-alertmanager%2Capp.kubernetes.io%2Fmanaged-by%3Dprometheus-operator%2Capp.kubernetes.io%2Fname%3Dalertmanager](https://172.20.0.1/api/v1/namespaces/observability/pods?labelSelector=alertmanager%3Dprometheus-alertmanager%2Capp.kubernetes.io%2Finstance%3Dprometheus-alertmanager%2Capp.kubernetes.io%2Fmanaged-by%3Dprometheus-operator%2Capp.kubernetes.io%2Fname%3Dalertmanager) 200 OK in 16 milliseconds"
level=debug ts=2023-08-14T06:31:41.61898Z caller=klog.go:84 component=k8s_client_runtime func=Infof msg="PUT [https://172.20.0.1:443/apis/monitoring.coreos.com/v1/namespaces/observability/alertmanagers/prometheus-alertmanager/status](https://172.20.0.1/apis/monitoring.coreos.com/v1/namespaces/observability/alertmanagers/prometheus-alertmanager/status) 200 OK in 9 milliseconds"
```

**Anything else we need to know?**:

no
