### ISSUE TITLE
Can't set supplementalGroups for Prometheus and Alertmanager StatefulSet

### ISSUE THREAD

**Issue by eumel8** [prometheus-operator/prometheus-operator#5810]
**What happened?**

We have Open Policy Agent running with a constraint to setup [supplementalGroups](https://github.com/caas-team/use-cases/blob/main/gatekeeper/templates/caask8sallowedusers.yaml) in Deployment and StatefulSets. This won't work to deploy Prometheus and Alertmanager: 

```
LAST SEEN   TYPE      REASON         OBJECT                                                     MESSAGE
5m43s       Warning   FailedCreate   statefulset/alertmanager-project-monitoring-alertmanager   create Pod alertmanager-project-monitoring-alertmanager-0 in StatefulSet alertmanager-project-monitoring-alertmanager failed error: admission webhook "validation.gatekeeper.sh" denied the request: [pods-allowed-user-ranges] Container alertmanager is attempting to run without a required securityContext/supplementalGroups. Allowed supplementalGroups: {"ranges": [{"max": 65535, "min": 1}], "rule": "MustRunAs"}...
5m42s       Warning   FailedCreate   statefulset/prometheus-project-monitoring-prometheus       create Pod prometheus-project-monitoring-prometheus-0 in StatefulSet prometheus-project-monitoring-prometheus failed error: admission webhook "validation.gatekeeper.sh" denied the request: [pods-allowed-user-ranges] Container config-reloader is attempting to run without a required securityContext/supplementalGroups. Allowed supplementalGroups: {"ranges": [{"max": 65535, "min": 1}], "rule": "MustRunAs"}...
```

**Did you expect to see something different?**

It seems this settings come into the StatefulSets:

```yaml
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
```

I would expect, this is more configurable but it seems this [isn't](https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/prometheus/agent/statefulset.go#L355C3-L355C3)

**How to reproduce it (as minimally and precisely as possible)**:

Install [kube-prometeus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) with default options

**Environment**

* Prometheus Operator version: v0.67.1

* Kubernetes version information: v1.23.16

* Kubernetes cluster kind: Rancher, RKE1

* Manifests:

* Prometheus Operator Logs:

see above

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
You can use [strategic merge patch](https://prometheus-operator.dev/docs/operator/strategic-merge-patch/) for this use case. We could add another example in the documentation about it though.

**Comment by eumel8** [comment]
@simonpasquier thx, seems workable in a way how can we deal it. Will test it further.

**Comment by eumel8** [comment]
this works:

alertmanager-patch.yaml:
```yaml
spec:
  containers:
  - name: alertmanager
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000
      runAsGroup: 1000
  - name: config-reloader
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000
      runAsGroup: 1000
  initContainers:
  - name: init-config-reloader
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000
      runAsGroup: 1000
  securityContext:
    fsGroup: 1000
    supplementalGroups:
    - 1000
 ```

prometheus-patch.yaml:
```yaml
spec:
  containers:
  - name: config-reloader
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000
      runAsGroup: 1000
  - name: prometheus
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000
      runAsGroup: 1000
  initContainers:
  - name: init-config-reloader
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000
      runAsGroup: 1000
  securityContext:
    fsGroup: 1000
    supplementalGroups:
    - 1000
```

```bash
kubectl patch prometheus project-monitoring-prometheus --patch-file patches/prometheus-patch.yaml --type=merge && kubectl patch alertmanager project-monitoring-alertmanager --patch-file patches/alertmanager-patch.yaml --type=merge && exit 0
```

but it's not very handy

**Comment by eumel8** [comment]
Tested in another cluster. The container object was empty before in `Alertmanager` resource or `Prometheus`.  The patch merge works, but ended in this way:

```yaml
      initContainers:
      - imagePullPolicy: IfNotPresent
        name: init-config-reloader
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups:
        - 1000
  ```

no image present, statefulset won't start
