### ISSUE TITLE
Support EC2 service discovery with ScrapeConfig CRD

### ISSUE THREAD

**Issue by infa-mperiasa** [prometheus-operator/prometheus-operator#5818]
**What happened?**
We are deploying the additionalscrape config using the CRD and ec2sd and kubernetes-sd config is not working.

**Did you expect to see something different?**
Additionalscrape config should be compatible for all the SD configs.

**How to reproduce it (as minimally and precisely as possible)**:
Create a scrapeconfig yaml with ec2 and kubernetes sd config 
**Environment**

* Prometheus Operator version:* 
0.67.1
    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:
1.24.0
    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by slashpai** [comment]
Looked at https://www.robustperception.io/automatically-monitoring-ec2-instances/  to start with we need only following fields in [ec2_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ec2_sd_config)

```yaml
 ec2_sd_configs:
 - region: 
     access_key: 
     secret_key: 
     port:
```

I will try to create PR with this

**Comment by 01cj** [comment]
@slashpai Can we also add support for AWS `role_arn` https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ec2_sd_config

**Comment by slashpai** [comment]
That can be done but I would like to get current change merged first. We should be good to support other fields after that.

**Comment by slashpai** [comment]
> @slashpai Can we also add support for AWS `role_arn` https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ec2_sd_config

I am not familiar how to use role arn with ec2_sd_config, do you have a example what all you need to make this work?

**Comment by slashpai** [comment]
IIUC it also needs profile set to work

**Comment by 01cj** [comment]
@slashpai we use something like this in our kube-prometheus-stack setup.

```
- job_name: test-prometheus-role
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  relabel_configs:
  - ****
  ec2_sd_configs:
  - region: us-east-1
    role_arn: arn:aws:iam::333333333333:role/test-prometheus-role
    refresh_interval: 1m
    port: 8080
    filters:
    - name: tag:service
      values:
      - test-service
```
