### ISSUE TITLE
Get rid of namespace matchers when creating AlertManagerConfig

### ISSUE THREAD

**Issue by bianchi2** [prometheus-operator/prometheus-operator#5860]
I have looked at a couple of PRs but don't see anything in main branch yet. Is it not possible to create just one global AlertManagerConfig or perhaps use regex?

The operator automatically adds namespace matcher to the effective config:

```
  routes:
  - receiver: k8testj-apse2/k8testj-apse2-alertmanager-config/slack-notifications
    matchers:
    - namespace="k8testj-apse2"
```
I wonder if it is possible to change this behabior.

**Comment by simonpasquier** [comment]
You want to look at `.spec.alertmanagerConfigMatcherStrategy.type` in the Alertmanager  CRD. The default is `OnNamespace` but you can set it to `None`.

**Comment by wexire** [comment]
```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
spec:
  alertmanagerConfigMatcherStrategy:
    type: None
```
    
After kubectl apply i get **Error from server (BadRequest): error when creating: Alertmanager in version "v1" cannot be handled as a Alertmanager: strict decoding error: unknown field "spec.alertmanagerConfigMatcherStrategy"**

I'm using the lastest version of [bitnami prometheus operator helm chart](https://artifacthub.io/packages/helm/bitnami/kube-prometheus)
