### ISSUE TITLE
KubernetesSDConfigs not working as expected in ScrapeConfig

### ISSUE THREAD

**Issue by slashpai** [prometheus-operator/prometheus-operator#5870]
We tried to implement the code merged in #5675, by using the latest release (v0.67.1). After applying the following scrapeConfig:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: etcd-scrape-config
  namespace: test
  labels:
    release: kube-prometheus-stack
spec:
  kubernetesSDConfigs:
    - role: "Node"
```

the following config was generated (live from the kube-prometheus-stack container)
```
- job_name: scrapeconfig/test/etcd-scrape-config                                                                                                                                                                                                                                
  kubernetes_sd_configs: null  

```
It seems that the value given in the ScrapeConfig is not transferred to the configuration of Prometheus.

After some additional research we found that the value of Spec.KubernetesSDConfigs are not appended to cfg: https://github.com/prometheus-operator/prometheus-operator/blob/be71cb80b0587d5f8895cfc675e6cc8a6e2d3d3d/pkg/prometheus/promcfg.go#L2350-L2352
If we are not mistaking the following line should be inserted before line 2352: `Value: configs`
Unfortunately we don't have a way of building the GO application and test the potential fix.

_Originally posted by @bsloeserwij in https://github.com/prometheus-operator/prometheus-operator/issues/5711#issuecomment-1699021616_

root cause: https://github.com/prometheus-operator/prometheus-operator/issues/5711#issuecomment-1699053430

We missed unit test for this one but e2e test didn't detect the issue.
