### ISSUE TITLE
Alertmanager pod can't be created when more than 1 template is specified in `.spec.alertmanagerConfiguration.templates`

### ISSUE THREAD

**Issue by dntosas** [prometheus-operator/prometheus-operator#5905]
**What happened?**
AlertManager its trying to mount templates volume twice
```
Warning   FailedCreate       statefulset/alertmanager-prometheus-operator-alertmanager   create Pod alertmanager-prometheus-operator-alertmanager-0 in StatefulSet alertmanager-prometheus-operator-alertmanager failed error: Pod "alertmanager-prometheus-operator-alertmanager-0" is invalid: spec.containers[0].volumeMounts[6].mountPath: Invalid value: "/etc/alertmanager/templates": must be unique
```

When applied this block of config:
```
    configuration:
      name: global
      global:
        resolveTimeout: 5m
        slackApiUrl:
          name: alertmanager-slack-legacy-webhook
          key: webhookUrl
      templates:
        - configMap:
            name: alertmanager-templates
            key: slack-default.tmpl
```
**Did you expect to see something different?**
Same behavior as before.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:
0.68

* Kubernetes version information:
1.26

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by slashpai** [comment]
Was this working correctly in `v0.67`?

If possible can you post operator logs as well?

**Comment by dntosas** [comment]
for some magic reason, deleted and re-created the resource, and everything played as expected 🤷 

re-produced the same behavior in 15 instances

**Comment by simonpasquier** [comment]
I can reproduce the issue with the following spec:

```
spec:
  alertmanagerConfiguration:
    name: config-example
    templates:
    - configMap:
        key: key1
        name: template1
    - configMap:
        key: key1
        name: template2

```

**Comment by simonpasquier** [comment]
Currently the operator generates the following pod template snippet in the statefulset:

```
   volumes:
     ...
      - name: notification-templates
        projected:
          defaultMode: 420
          sources:
          - configMap:
              items:
              - key: key1
                path: key1
              name: template1
          - configMap:
              items:
              - key: key1
                path: key1
              name: template2
```

It triggers a `conflicting duplicate paths` error in the statefulset controller because both keys are projected to the same path.

One way to fix it would be to include the referenced object's name in the path.

```
   volumes:
     ...
      - name: notification-templates
        projected:
          defaultMode: 420
          sources:
          - configMap:
              items:
              - key: key1
                path: template1/key1
              name: template1
          - configMap:
              items:
              - key: key2
                path: template2/key1
              name: template2
```

There's still a problem if someone references a secret and a configmap with the same name but it could be detected by the controller during the reconciliation and rejected.

A related issue is that if someone uses the same reference more than once in the templates list, it also fails the statefulset controller. The easy fix is for the Alertmanager controller to eliminate the duplicate entries.
