### ISSUE TITLE
Not possible to set `cluster` as an External Label

### ISSUE THREAD

**Issue by sherifkayad** [prometheus-operator/prometheus-operator#5908]
**What happened?**
After upgrading to the latest version of the Operator and the CRDs (`0.68.0`), and using my existing good old setup, I am seeing the following error:
`level=warn ts=2023-09-12T12:30:13.674112327Z caller=promcfg.go:418 component=prometheusoperator msg=\"ignoring external label because it is a reserved key\" key=cluster version=v2.45.0`

After that, the started Prometheus metrics don't have the correct `cluster` external label anymore!

**Did you expect to see something different?**
The `cluster` label is respected and treated as an external label as it have always worked in the past.

**How to reproduce it (as minimally and precisely as possible)**:
Start a Prometheus cluster as per the Manifests section!

**Environment**
- EKS 1.27
- Helm3

* Prometheus Operator version:
`0.68.0`

* Kubernetes version information:
`1.27`

* Kubernetes cluster kind:
`EKS`

* Manifests:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kube-prometheus-prometheus
  namespace: monitoring
  annotations:
    meta.helm.sh/release-name: kube-prometheus
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kube-prometheus-prometheus
    app.kubernetes.io/instance: kube-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 51.0.1
    chart: kube-prometheus-stack-51.0.1
    heritage: Helm
    release: kube-prometheus
spec:
  alerting:
    alertmanagers:
      - apiVersion: v2
        name: kube-prometheus-alertmanager
        namespace: monitoring
        pathPrefix: /
        port: http-web
  disableCompaction: true
  enableAdminAPI: false
  enableRemoteWriteReceiver: true
  evaluationInterval: 30s
  externalLabels:
    cluster: my-great-cluster
    region: eu-central-1
  externalUrl: https://prometheus.my-great-cluster.mydomain.com
  hostNetwork: false
  image: quay.io/prometheus/prometheus:v2.45.0
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector: {}
  prometheusExternalLabelName: cluster
  replicaExternalLabelName: replica
  replicas: 2
  resources:
    limits:
      memory: 7Gi
    requests:
      cpu: '1.5'
      memory: 7Gi
  retention: 36h
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector: {}
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector:
    matchLabels:
      release: kube-prometheus
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: kube-prometheus-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  shards: 1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: ebs-sc
  thanos:
    blockSize: 2h
    image: bitnami/thanos:0.32.2-debian-11-r0
    objectStorageConfig:
      key: thanos-object-store.yml
      name: thanos-object-store
  version: v2.45.0
  walCompression: true
```

* Prometheus Operator Logs:
`level=warn ts=2023-09-12T12:30:13.674112327Z caller=promcfg.go:418 component=prometheusoperator msg=\"ignoring external label because it is a reserved key\" key=cluster version=v2.45.0`

**Anything else we need to know?**:
Maybe that problem is related to the MR => https://github.com/prometheus-operator/prometheus-operator/pull/5888 ??!!
