### ISSUE TITLE
Why AlertmanagerConfig not be loaded in Alertmanager

### ISSUE THREAD

**Issue by mrofisr** [prometheus-operator/prometheus-operator#5909]
Hello, I'm setting up Alertmanager and AlertmanagerConfig in Kubernetes using prometheus-operator, but AlertmanagerConfig won't be read in Alertmanager.

this my YAML:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
```
---
```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  image: "quay.io/prometheus/alertmanager:v0.25.0"
  alertmanagerConfigSelector:
    matchLabels:
      app: alertmanager
```

Anyone can help me?

**Comment by slashpai** [comment]
Could you please provide more details

Ref https://github.com/prometheus-operator/prometheus-operator/blob/main/.github/ISSUE_TEMPLATE/support.md

**Comment by slashpai** [comment]
Also look at https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/alerting.md#using-alertmanagerconfig-resources

I don't see config in your `AlertmanagerConfig` object to be loaded

**Comment by mrofisr** [comment]
Thank you @slashpai, I apologize in advance, this turns out to be my fault for not reading the detailed documentation.

To solve this problem, actually there was no error in the config above, but after I tried checking the log from prometheus-operator, it turned out there was an error in AlertmanagerConfig, namely in the apiUrl which I didn't add to the secret, so I created a secret first to store the discord webhook URL then I included the name of the secret and also the key.

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord-config
  namespace: monitoring
  labels:
    app: alertmanager
    app.kubernetes.io/instance: prom
    release: "prom"
spec:
  route:
    receiver: "discord"
    groupBy: ["alertname"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4m
    matchers:
      - name: severity
        matchType: =~
        value: "critical|warning|error"
  receivers:
    - name: "discord"
      discordConfigs:
        - apiURL:
            name: discord-secret
            key: key
     ```
