### ISSUE TITLE
ServiceMonitor not picked up by prom-operator

### ISSUE THREAD

**Issue by tim-hilt** [prometheus-operator/prometheus-operator#5917]
**What did you do?**

1. Tried integrating a simple go-application with prom-operator via a ServiceMonitor (Deployment with one Pod@one replica + one Service)
2. Posted in Prometheus-Slack-Channel (no helpful response though)
3. Found out about prometheus-operator Slack-Channel and posted same question there (no response)
4. Read through Troubleshooting-Guide for ServiceMonitor
5. Found out ServiceMonitor wasn't picked up by Prometheus-Operator (grep didn't list my service-monitor in the list of targets)

**Did you expect to see some different?**

I expected to see the ServiceMonitor being picked up by prom-operator

**Environment**

* Prometheus Operator version:

    `52526e3 (v0.68.0)`
    
    

* Kubernetes version information:

```
    Client Version: v1.24.2
    Kustomize Version: v4.5.4
    Server Version: v1.27.3
```

* Kubernetes cluster kind:

``` bash
    kind create cluster  # Provisioned locally on my MacBook Air M1 using kind (Kubernetes in Docker)
```

* Manifests:

``` yaml
---
# Source: ml-simulation/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: ml-simulation
  labels:
    app: ml-simulation
spec:
  selector:
    app: ml-simulation
  ports:
  - name: web
    port: 8080
---
# Source: ml-simulation/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-simulation
spec:
  selector:
    matchLabels:
      app: ml-simulation
  template:
    metadata:
      labels:
        app: ml-simulation
    spec:
      containers:
      - name: ml-simulation
        image: ml-simulation
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 32M
---
# Source: ml-simulation/templates/service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-simulation
  labels:
    app: ml-simulation
spec:
  selector:
    matchLabels:
      app: ml-simulation
  endpoints:
  - port: web

```

* Prometheus Operator Logs:

```
-
```

**Anything else we need to know?**:

```
-
```
