### ISSUE TITLE
Automated sharding

### ISSUE THREAD

**Issue by ArthurSens** [prometheus-operator/prometheus-operator#5931]
**What is missing?**

When operating hundreds/thousands of Prometheus instances that have very non-standardized loads, it becomes troublesome to fine-tune all of them. While several horizontal auto scalers have shown up in the market, they don't really work with Prometheus because they cause metrics duplication issues.

Prometheus-Operator offers a sharding mechanism to solve this problem. Still, they also fall short when samples ingested per second change alongside the load on the monitored systems.

It would be super helpful if Prometheus-Operator could measure the load on top of managed Prometheuses, e.g. by querying ingested samples per second or using kubernetes metrics API(kubectl top), and automatically bump the number of shards based on a "Max size" configured by the user.

**Why do we need it?**

For teams that manage hundreds/thousands of Prometheus instances, this feature will help them find a good cost-reliability ratio while eliminating manual effort of fine-tuning several Prometheus several times a day.

**Comment by simonpasquier** [comment]
We have a few issues related to sharding and autoscaling.
* https://github.com/prometheus-operator/prometheus-operator/issues/4946
* https://github.com/prometheus-operator/prometheus-operator/issues/4727

There's also the issue of what to do with the shards in excess when scaling down (https://github.com/prometheus-operator/prometheus-operator/issues/4967). Right now the historical data is lost but I suppose that in an agent-based deployment, it's less of an issue.

Do these issues match with what you're looking for?

**Comment by ArthurSens** [comment]
Thanks for pointing those issues, my search was not that good 😓 

I'm closing this one and moving the discussion to the other issues

**Comment by simonpasquier** [comment]
We could keep this umbrella issue though because the 3 issues are related but none of them addresses the complete autoscaling scenario.

**Comment by ArthurSens** [comment]
I've added the topic to the next office hours :)

**Comment by zbialik** [comment]
I was able to handle downscaling scenarios by leveraging Thanos (w/S3) for our use-case.

Since we use S3 w/thanos, we just take a TSDB snapshot before shutting down Prometheus and then upload that snapshot to S3 (after appending some needed metadata). So far this has been working for us, though you might get some redundant data occasionally but nothing deduping hasn't fixed. 

For automation, I just add a sidecar to our Prometheus deploy with a `PreStop` lifecycle hook that performs the HTTP request to take the TSDB snapshot, add the metadata file, and upload to S3. 

Not sure it's the best way to go about things but it's so far been working well.

**Comment by simonpasquier** [comment]
Interesting approach, it might make a good entry for the operator documentation :)

**Comment by ArthurSens** [comment]
Nice solution, I think it's worth adding this approach to the ShardRetentionPolicy API. Very similar to what @nicolastakashi proposed

**Comment by Nashluffy** [comment]
I followed a similar snapshotting approach on shutdown, from my testing it seems fairly reliable but hasn't been in the wild for long.

Partial `Prometheus` spec below which

1. Hits the snapshot endpoint
2. Copies all blocks from the snapshot dir to the root prometheus data dir, where thanos-sidecar & prom expect "normal" blocks to be
3. Clears the WAL to prevent overlapping blocks in case the shutdown is due to normal pod restart
4. thanos-sidecar sleeps for 35 seconds, 5 seconds for the snapshotting to complete + 30 seconds as it's the interval at which thanos-sidecar checks for new blocks.

```
  containers:
    - name: prometheus
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - -c
              - wget --post-data '' localhost:9090/api/v1/admin/tsdb/snapshot &&
                find snapshots -maxdepth 2 -mindepth 2 -type d -exec cp --recursive {} . \; &&
                rm -rf wal
    - name: thanos-sidecar
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - -c
              - sleep 35
```
