### ISSUE TITLE
Issues with ScrapeConfigCRD consulSDConfigs

### ISSUE THREAD

**Issue by heliapb** [prometheus-operator/prometheus-operator#5936]
Hello there, I was trying to test moving away from using additionalScrapeConfigs, to replace with ScrapeConfig instead, but got some errors while trying to create the first one on Prometheus Operator. I use consul for service discovery with additionalScrapeConfigs for context, and creating the ScrapeConfig for the service resulted in errors in prometheus-operator, and no service appeared in Prometheus Targets.

```
github.com/prometheus-operator/prometheus-operator/pkg/prometheus.(*ResourceSelector).validateConsulSDConfigs(0xc000316d20, {0x2604410, 0xc000130190}, 0xc000845b80)
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/resource_selector.go:756 +0x376
github.com/prometheus-operator/prometheus-operator/pkg/prometheus.(*ResourceSelector).SelectScrapeConfigs(0xc000316d20, {0x2604410, 0xc000130190}, 0xc00111b3b8)
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/resource_selector.go:713 +0xc9c
github.com/prometheus-operator/prometheus-operator/pkg/prometheus/server.(*Operator).createOrUpdateConfigurationSecret(0xc000a50000, {0x2604410, 0xc000130190}, 0xc000127100, 0x0?, {0xc0013cc5c0, 0x1, 0x1}, 0xc001300d80)
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/server/operator.go:1531 +0x3a5
github.com/prometheus-operator/prometheus-operator/pkg/prometheus/server.(*Operator).sync(0xc000a50000, {0x2604410, 0xc000130190}, {0xc000b9f980, 0x30})
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/server/operator.go:1201 +0x6be
github.com/prometheus-operator/prometheus-operator/pkg/prometheus/server.(*Operator).Sync(0xc000a50000, {0x2604410?, 0xc000130190?}, {0xc000b9f980, 0x30})
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/server/operator.go:1157 +0x32
github.com/prometheus-operator/prometheus-operator/pkg/operator.(*ResourceReconciler).processNextReconcileItem(0xc000a1d2b0, {0x2604410, 0xc000130190})
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/operator/resource_reconciler.go:397 +0x230
github.com/prometheus-operator/prometheus-operator/pkg/operator.(*ResourceReconciler).Run.func1()
	/home/runner/work/prometheus-operator/prometheus-operator/pkg/operator/resource_reconciler.go:360 +0x45
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5
```
The original additionalScrapeConfigs that I'm currently using and working ok.

```
    additionalScrapeConfigs: |
      - job_name: 'myservice'
        sample_limit: 2000
        scrape_interval: 30s
        scrape_timeout: 10s
        consul_sd_configs:
          - server: https://<consul-dns>:8500
            datacenter: "<DC>"
            services:
              - "myservice"
        relabel_configs:
          # set metrics path from metadata if it's defined
          - source_labels:
              - __meta_consul_service_metadata_metrics_path
            regex: (.+)
            target_label: __metrics_path__
          - source_labels:
              - __meta_consul_service_metadata_metrics_scheme
              - __meta_consul_service_metadata_scheme
            regex: ;?([^;]+);?.*
            target_label: __scheme__
          - source_labels:
              - __meta_consul_service_metadata_metrics_port
              - __meta_consul_service_port
            regex: ;?([^;]+);?.*
            target_label: __tmp_port
          - source_labels: [__meta_consul_address, __tmp_port]
            regex: (.+);(.+)
            replacement: ${1}:${2}
            target_label: __address__
          - source_labels:
              - __meta_consul_node
              - __tmp_port
            regex: ([^.]+).*;(.+)
            replacement: ${1}:${2}
            target_label: instance
```
 
The ScrapeConfig CRD, also added the scrapeConfigSelector on prometheus spec, as per the [documentation](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/scrapeconfig.md#use-scrapeconfig-to-scrape-an-external-target)
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: myservice
  labels:
    prometheus: test
spec:
  consulSDConfigs:
    - server: https://<consul-dns>:8500
      datacenter: "<DC>"
      services:
        - myservice
  relabelings:
    - sourceLabels:
        - __meta_consul_service_metadata_metrics_path
      regex: (.+)
      targetLabel: __metrics_path__
    - sourceLabels:
        - __meta_consul_service_metadata_metrics_scheme
        - __meta_consul_service_metadata_scheme
      regex: ;?([^;]+);?.*
      targetLabel: __scheme__
    - sourceLabels:
        - __meta_consul_service_metadata_metrics_port
        - __meta_consul_service_port
      regex: ;?([^;]+);?.*
      targetLabel: __tmp_port
    - sourceLabels: [__meta_consul_address, __tmp_port]
      regex: (.+);(.+)
      replacement: ${1}:${2}
      targetLabel: __address__
    - sourceLabels:
        - __meta_consul_node
        - __tmp_port
      regex: ([^.]+).*;(.+)
      replacement: ${1}:${2}
      targetLabel: instance
```

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

v0.68.0

* Kubernetes version information:
v1.26.1

* Kubernetes cluster kind:

Local cluster created with Kind v0.17.0 go1.19.2 linux/amd64

Any help with be appreciated. Thanks
