### ISSUE TITLE
Reduce Cardinality 

### ISSUE THREAD

**Issue by rnik12** [prometheus-operator/prometheus-operator#5939]
Should we drop these series to reduce the high cardinality ? A fresh k8s cluster with kube prometheus takes around 2GB of RAM.

```
    - action: drop
      regex: apiserver_request_duration_seconds_bucket.*
      sourceLabels:
      - __name__
    - action: drop
      regex: etcd_request_duration_seconds_bucket.*
      sourceLabels:
      - __name__
    - action: drop
      regex: apiserver_request_sli_duration_seconds_bucket.*
      sourceLabels:
      - __name__
```

<img width="1440" alt="Screenshot 2023-09-23 at 7 39 20 PM" src="https://github.com/prometheus-operator/prometheus-operator/assets/6128508/c52a6d69-90f1-431f-9208-a06472c18eeb">
