### ISSUE TITLE
Support additional relabelings in scrape classes

### ISSUE THREAD

**Issue by SuperQ** [prometheus-operator/prometheus-operator#5947]
**What is missing?**

With the new [scrape classes](https://github.com/prometheus-operator/prometheus-operator/pull/5572) feature, it would be useful to allow additional relabelings that are added after the operator-managed relabelings, but before the relabelings supplied by the scrape target (`ServiceMonitor`, `PodMonitor`, etc)

This is an extension of the request in https://github.com/prometheus-operator/prometheus-operator/issues/3255.

**Why do we need it?**

This is needed in order to allow `Prometheus` admins to extend and enforce relabelings for downstream users of various scrape configs.

Examples:

Always propagate the `deployment` label:
```yaml
kind: Prometheus
spec:
  scrapeClasses:
    - name: deployments
      default: true
      additionalRelabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_deployment]
          targetLabel: deployment
```

Always propagate release information provided by CD tooling:
```yaml
kind: Prometheus
spec:
  scrapeClasses:
    - name: versioning
      default: true
      additionalRelabelings:
        - sourceLabels: [__meta_kubernetes_pod_annotation_example_com_version]
          targetLabel: release_version
```

**Comment by rexagod** [comment]
WIP.

**Comment by nicolastakashi** [comment]
@rexagod Tge ScrapeClasse design is not finished yet.

**Comment by rexagod** [comment]
Ah, I see. I guess I'll wait it out then, thanks for the heads up!

**Comment by sathieu** [comment]
I have a different use-case: We define a tenant as a list of namespaces (or namespace regexps). I want to create a tenant label for each metric.

I need something like:

```yaml
kind: Prometheus
spec:
  scrapeClasses:
    - name: deployments
      default: true
      additionalMetricsRelabelings:
        - sourceLabels: [namespace]
          regex: tenant1-.*
          targetLabel: tenant
          replacement: tenant1
        - sourceLabels: [namespace]
          regex: foo|bar
          targetLabel: tenant
          replacement: foo-bar
```

This metrics relabeling should be enforced **after** scrape target metrics relabeling. Also if the scrape target references an unexisting scrapeClass, the default scrape class should be applied (for security reasons).
