### ISSUE TITLE
Enable `ScrapeConfig` to use (discovery|target) proxies

### ISSUE THREAD

**Issue by DazWilkin** [prometheus-operator/prometheus-operator#5966]
**What is missing?**

IIUC `ScrapeConfig` is the recommended mechanism for reflecting (among other mechanisms) Prometheus [HTTP SD](https://prometheus.io/docs/prometheus/latest/http_sd/).

I have a known-working HTTP SD that I'm unable to translate to `ScrapeConfig`.

```YAML
- job_name: foo
  scheme: http
  proxy_url: http://proxy
  http_sd_configs:
  - refresh_interval: 1m
    url: http://service-discovery
```

In my case, I need to be able to auth discovered targets using ID tokens. The token must have a per-target audience.

None of the static auth mechanisms are appropriate (`basicAuth`, `authroization`, `tlsConfig`).

**Why do we need it?**

1. Non-operated Prometheus provides proxying of both the service discovery endpoint and discovered targets
2. Existing auth mechanisms are insufficient

**Environment**

* Prometheus Operator version:

    `v0.68.0`
    
    

**Anything else we need to know?**:

##### Stack overflow

https://stackoverflow.com/questions/77225018/is-it-possible-to-proxy-scrapeconfig-targets

##### Documentation

I've upgraded to the current version (v0.68.0) but the documentation for `ScrapeConfig` is incorrect and confusing.

[API Reference](https://prometheus-operator.dev/docs/operator/api/) includes [`ScrapeConfig`](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1alpha1.ScrapeConfig) but -- IIUC -- the [`Prometheus`](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.Prometheus) resource must be updated to reflect `scrapeConfigSelector` and `scrapeConfigNamespaceSelector`.

[`Prometheus`](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.Prometheus) describes `scrapeConfigSelector` as deprecated (I think it isn't).

[ScrapeConfig CRD](https://prometheus-operator.dev/docs/user-guides/scrapeconfig/) describes configuring `Prometheus` or `PrometheusAgent`.

A `v0.68.0` deployment includes `Prometheus` but not `PrometheusAgent`.

The document's recommended change appears invalid:

```YAML
spec:
  scrapeConfigSelector:
    prometheus: system-monitoring-prometheus
```
I discovered that I needed:
```YAML
spec:
  scrapeConfigSelector: {}
  scrapeConfigNamespaceSelector: {}
```
And, of course, I could ignore the `ScrapeConfig` annotation `prometheus`.
