### ISSUE TITLE
reloader config limits and requests not being updated

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#5970]
I have set the flags to modify the reloader cpu requests, but they are not applied:

- prometheusOperator version: `0.68.0`
- prometheus version: `v2.47.1`

- Prometheus operator pod description:
```yaml
Containers:
  prometheus-operator:
    Image: quay.io/prometheus-operator/prometheus-operator:v0.68.0
    Args:
      --kubelet-service=kube-system/kubelet
      --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.68.0
      --config-reloader-cpu-request=10m
      --config-reloader-cpu-limit=20m
```

- Prometheus pod description: (i restarted it after applying the operator)
```yaml
 config-reloader:
    Image: quay.io/prometheus-operator/prometheus-config-reloader:v0.68.0
    Command:
      /bin/prometheus-config-reloader
    Args:
      --listen-address=:8080
      --reload-url=http://localhost:9090/prometheus/-/reload
      --config-file=/etc/prometheus/config/prometheus.yaml.gz
      --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
      --watched-dir=/etc/prometheus/rules/prometheus-monitoring-rulefiles-0
    Limits:
      cpu:     10m
      memory:  50Mi
    Requests:
      cpu:     10m
      memory:  50Mi
```

_Originally posted by @ebarped in https://github.com/prometheus-operator/prometheus-operator/issues/5446#issuecomment-1750436288_
