### ISSUE TITLE
ScrapeConfig not supported in prometheus.spec.excludedFromEnforcement

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#5977]
**What happened?**

Operator doesn't support ScrapeConfigs in enforcement exclusion.

**Did you expect to see something different?**

I expect no errors when adding the following to PrometheusSpec:

```
enforcedNamespaceLabel: namespace
excludedFromEnforcement:
  - name: kubelet-slis
    namespace: monitoring
    resource: scraperconfigs
```

**How to reproduce it (as minimally and precisely as possible)**:

Start operator with prometheus CR. Add the following:

**Environment**

* Prometheus Operator version:

`0.68.0`

* Kubernetes version information:

`1.28.2`

* Kubernetes cluster kind:

k3s

* Manifests:

Default kube-prometheus

* Prometheus Operator Logs:

There is no logs as issue is on CRD side.

**Anything else we need to know?**:

For some reason this caused prometheus outage (replicas went down and Prometheus CR was removed) when paired with fluxcd.
