### ISSUE TITLE
AlertmanagerConfig with missing options causes Alertmanager to crash

### ISSUE THREAD

**Issue by slashpai** [prometheus-operator/prometheus-operator#6003]
**What happened?**

If neither a global config value nor at receiver level mandatory field values are not specified it causes alertmanager to crash. For example SMTPSmartHost is a mandatory field if we missout that in global as well as at emailConfig it will cause alertmanager to crash and log following:

```
ts=2023-09-05T12:07:33.449Z caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config_out/alertmanager.env.yaml err="no global SMTP smarthost set"
```

**Did you expect to see something different?**

Validation should be there for these fields which uses global value by default

email: https://github.com/prometheus/alertmanager/blob/5ba9b9c7c34cff1276004e893ed0a4b0998f5256/config/config.go#L367-L378
slack: https://github.com/prometheus/alertmanager/blob/5ba9b9c7c34cff1276004e893ed0a4b0998f5256/config/config.go#L404-L407
pagerduty: https://github.com/prometheus/alertmanager/blob/5ba9b9c7c34cff1276004e893ed0a4b0998f5256/config/config.go#L421-L424
opsgenie: https://github.com/prometheus/alertmanager/blob/5ba9b9c7c34cff1276004e893ed0a4b0998f5256/config/config.go#L432-L435
https://github.com/prometheus/alertmanager/blob/5ba9b9c7c34cff1276004e893ed0a4b0998f5256/config/config.go#L441-L444
wechat:
https://github.com/prometheus/alertmanager/blob/5ba9b9c7c34cff1276004e893ed0a4b0998f5256/config/config.go#L454-L471
victorops:
https://github.com/prometheus/alertmanager/blob/5ba9b9c7c34cff1276004e893ed0a4b0998f5256/config/config.go#L483-L487
https://github.com/prometheus/alertmanager/blob/5ba9b9c7c34cff1276004e893ed0a4b0998f5256/config/config.go#L492-L495
discord:
https://github.com/prometheus/alertmanager/blob/5ba9b9c7c34cff1276004e893ed0a4b0998f5256/config/config.go#L518-L519
webex:
https://github.com/prometheus/alertmanager/blob/5ba9b9c7c34cff1276004e893ed0a4b0998f5256/config/config.go#L526-L529
msteams(not yet in po): https://github.com/prometheus/alertmanager/blob/5ba9b9c7c34cff1276004e893ed0a4b0998f5256/config/config.go#L526-L529

**How to reproduce it (as minimally and precisely as possible)**:

Create alertmanager with mandatory field (smtpsmarthost incase of emailConfig) missing

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: example
  namespace: example-namespace
spec:
  receivers:
    - emailConfigs:
        - to: user@example.com
      name: email
  route:
    matchers:
      - name: alertname
    receiver: email
    repeatInterval: 1m
```

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

All

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
