### ISSUE TITLE
kube-prometheus-stack's alertmanager configs are empty but pod config was populated

### ISSUE THREAD

**Issue by rafaelvanoni** [prometheus-operator/prometheus-operator#6048]
I'm trying to enable alertmanager in my cluster and have a config that passes `amtool config-check` and doesn't generate any errors when applied (nothing in the operator pod's log). The config is in the main kube-prometheus-stack chart:
```
  kube-prometheus-stack:
  [...]
  alertmanager:
    enabled: true
    alertManagerSpec:
      secrets: ['pagerduty']
    config:
      global:
      [...]
```
I exec'ed into the alertmanager pod and see my config got there correctly. But the alertmanager CRDs don't seem to have changed at all:
```
$ kubectl -n mynamespace get alertmanagerconfigs.monitoring.coreos.com -o yaml
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
```
Some things to note:
- both prometheus and alertmanager are in the same namespace
- I haven't created any actual alerts yet
- my root level receiver doesn't do anything, I have child receivers configured tho

Any pointers would be much appreciated.
