### ISSUE TITLE
ThanosRuler broken with thanos >= 0.32.0

### ISSUE THREAD

**Issue by sebhoss** [prometheus-operator/prometheus-operator#6132]
**What happened?**

Upgrading a ThanosRuler instance to version 0.32.0 or greater causes an error crash loop. The log message is:

```
ts=2023-11-29T09:58:55.173115512Z caller=main.go:135 level=error err="lock DB directory: open /thanos/data/lock: permission denied\nopen TSDB\nmain.runRule\n\t/app/cmd/thanos/rule.go:406\nmain.registerRule.func1\n\t/app/cmd/thanos/rule.go:223\nmain.main\n\t/app/cmd/thanos/main
.go:133\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650\npreparing rule command failed\nmain.main\n\t/app/cmd/thanos/main.go:135\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runt
ime/asm_amd64.s:1650"
```

**Did you expect to see something different?**

ThanosRuler should start correctly with version 0.32.0

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `v0.69.1`
    
    

* Kubernetes version information:

    `Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4`
    

* Kubernetes cluster kind:

    kubeadm

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: ThanosRuler
metadata:
  name: thanos-ruler-global
  namespace: prometheus
spec:
  image: quay.io/thanos/thanos:v0.32.5
  storage:
    volumeClaimTemplate:
      metadata:
        name: thanos-ruler-global-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: csi-rbd
```

* Prometheus Operator Logs:

```
level=info ts=2023-11-29T10:08:27.86690159Z caller=operator.go:545 component=thanosoperator key=prometheus/thanos-ruler-global msg="sync thanos-ruler"
```

**Anything else we need to know?**:

I think this is due to https://github.com/thanos-io/thanos/pull/6107 which changed the user in the thanos image. That change was released with version 0.32.0. Reverting to a 0.31.x image fixed this for me. I tried remove the ThanosRuler resource as well as the PVC in order to have prometheus-operator recreate everything from scratch, but this just fails with the same error message.
