### ISSUE TITLE
Add JobName for ScrapeConfig CRD

### ISSUE THREAD

**Issue by janluak** [prometheus-operator/prometheus-operator#6147]
**What happened?**
As far as I can see the CRD of ScrapeConfig is not showing the full support for all scrape configs.
By example: the authorization data source and the job name.

**Did you expect to see something different?**
This is a scrape config how I can set as it is:
```
- job_name: kubernetes-nodes-cadvisor
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  authorization:
    type: Bearer
    credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
```

Looking at the authorization, the crd is only allowing a credentials reading from a secret. Check the current 0.70.0 release:
```
              authorization:
                description: Authorization header to use on every scrape request.
                properties:
                  credentials:
                    description: Selects a key of a Secret in the namespace that contains
                      the credentials for authentication.
                    properties:
                      key:
                        description: The key of the secret to select from.  Must be
                          a valid secret key.
                        type: string
                      name:
                        description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                          TODO: Add other useful fields. apiVersion, kind, uid?'
                        type: string
                      optional:
                        description: Specify whether the Secret or its key must be
                          defined
                        type: boolean
                    required:
                    - key
                    type: object
                    x-kubernetes-map-type: atomic
                  type:
                    description: "Defines the authentication type. The value is case-insensitive.
                      \n \"Basic\" is not a supported value. \n Default: \"Bearer\""
                    type: string
                type: object
```

So a manifest like this is not valid:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kubernetes-nodes-cadvisor
  namespace: default
spec:
  honorTimestamps: true
  authorization:
    type: Bearer
    credentialsFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```

Additionally, there is no option to specify a name for the job / the scrape_job.
This generates the label-value to `scrapeConfig/<namespace>/<metadata.name>` which some applications cannot use (expecting only `<metadata.name>`).

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:
kube-prom-stack: helm 55.0.0 → prometheus 0.70.0
prometheus-operator-crds: helm 8.0.1 → prometheus 0.70.

* Kubernetes version information:

    `kubectl version`
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4+k3s1", GitCommit:"36645e7311e9bdbbf2adb79ecd8bd68556bc86f6", GitTreeState:"clean", BuildDate:"2023-07-28T09:46:05Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/arm64"}

* Kubernetes cluster kind:

    insert how you created your cluster: Rancher & k3s

**Anything else we need to know?**:
I figured the relabelling in the scrapeConfig to a specific value for `scrape_job` isn't working. If you have a different solution this would easy the issue for the moment ;)

```
    - sourceLabels: ['scrape_job']
      regex: 'scrapeConfig\/namespace\/(.*)'
      targetLabel: 'scrape_job'
      replacement: '$1'
      action: 'replace'
```

→ goal is to have the last part of the regex to be the new value. This would be equivalent to the `metadata.name` value which is my desire.

Thanks for the help guys!

**Comment by slashpai** [comment]
ScrapeConfig is alphav1 so not all fields are not supported yet :)
IIRC we didn't want to add support for credential_files since service account's token can be easily grabbed hence only Secret is supported in ScrapeConfig

**Comment by janluak** [comment]
if you give me a little guidance (are there tests for this kind of stuff and is there some code doing the mapping by hand or is the actual scrape-config generated somehow) I can see if I can make the changes myself...

**Comment by ArthurSens** [comment]
Hey @janluak, thanks for your interest in helping out. To add new fields to scrapeConfig CRD.

You'll want to add new fields to the Spec [here](https://github.com/prometheus-operator/prometheus-operator/blob/0d918323945ce87f0094c05c153075c0a6edc8de/pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go#L98C11-L98C11).

The config is generated [here](https://github.com/prometheus-operator/prometheus-operator/blob/0d918323945ce87f0094c05c153075c0a6edc8de/pkg/prometheus/promcfg.go#L2276)

and we do have quite a few tests [here](https://github.com/prometheus-operator/prometheus-operator/blob/0d918323945ce87f0094c05c153075c0a6edc8de/pkg/prometheus/promcfg_test.go#L4949) :)

**Comment by janluak** [comment]
Hey guys,

thanks for the quick heads-up for enabling me to do the changes.
I just created the MR #6153 for the fix. It is only focusing on the `ScrapeConfig`. I guess it will be suitable for `ServiceMonitor` or `PodMonitor` as well. Since I am new to `Go` and not familiar with your coding styles please let me know if there are more sophisticated ways in reaching the goal... Afterwards I can could adapt the changes for the other crds as well ;)

Thanks for the support!
Hope to see the feature go live soon ;)

**Comment by simonpasquier** [comment]
For ServiceMonitor and PodMonitor, the usual way is to use `.spec.jobLabel`.

**Comment by simonpasquier** [comment]
>  should the jobName get changed to jobLabel as well?

we can't change the existing v1 CRDs.

**Comment by janluak** [comment]
> > should the jobName get changed to jobLabel as well?
> 
> we can't change the existing v1 CRDs.

sorry, no I meant for the ScrapeConfig. the spec `jobName` is only added with my MR. If desired we can make I similar to the others and name the flag `jobLabel` instead

**Comment by simonpasquier** [comment]
`jobLabel` has a different meaning because it selects the Kubernetes label from the corresponding Pod (for PodMonitor) or Service (for ServiceMonitor). With ScrapeConfig, there's no "parent" resource to get the label from. Hence I'd keep `jobName` here.

**Comment by kostas-rf** [comment]
For the job label specifically i was able to get around the absence of a dedicated label field by using `relabelings` in the ScrapeConfig CR:

```yaml
spec:
  relabelings:
    - action: replace
      replacement: node-exporter
      targetLabel: job
```

This replaced the job label from `job="scrapeConfig/<namespace>/node-exporter"` to just `job="node-exporter"`.

Hope this helps.
