### ISSUE TITLE
Scrape config is never loaded into Prometheus

### ISSUE THREAD

**Issue by ncrmro** [prometheus-operator/prometheus-operator#6189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Steps to Reproduce

Create Scrape Config

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: example
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - "192.168.1.100:9100"
```

## Expected Result

See scrape config on prometheus targets page

## Actual Result

No scrape config.

### Prometheus Operator Version

```shell
v0.70.0
```

### Kubernetes Version

```yaml
v1.27.7+k3s1 (k3s)
```

### Kubernetes Cluster Type

Other (please comment)

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml
Name:         kube-prometheus-stack-prometheus
Namespace:    monitoring
Labels:       app=kube-prometheus-stack-prometheus
              app.kubernetes.io/instance=kube-prometheus-stack
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/part-of=kube-prometheus-stack
              app.kubernetes.io/version=55.5.0
              chart=kube-prometheus-stack-55.5.0
              heritage=Helm
              release=kube-prometheus-stack
Annotations:  meta.helm.sh/release-name: kube-prometheus-stack
              meta.helm.sh/release-namespace: monitoring
API Version:  monitoring.coreos.com/v1
Kind:         Prometheus
Metadata:
  Creation Timestamp:  2023-10-15T18:09:21Z
  Generation:          10
  Resource Version:    9353650
  UID:                 492ad08a-89fb-4e05-96f4-ed0990efc27a
Spec:
  Alerting:
    Alertmanagers:
      API Version:      v2
      Name:             kube-prometheus-stack-alertmanager
      Namespace:        monitoring
      Path Prefix:      /
      Port:             http-web
  Enable Admin API:     false
  Evaluation Interval:  30s
  External URL:         http://prometheus.test.com/
  Host Network:         false
  Image:                quay.io/prometheus/prometheus:v2.48.1
  Listen Local:         false
  Log Format:           logfmt
  Log Level:            info
  Paused:               false
  Pod Monitor Namespace Selector:
  Pod Monitor Selector:
    Match Labels:
      Release:  kube-prometheus-stack
  Port Name:    http-web
  Probe Namespace Selector:
  Probe Selector:
    Match Labels:
      Release:  kube-prometheus-stack
  Replicas:     1
  Resources:
    Limits:
      Cpu:     1
      Memory:  2Gi
    Requests:
      Cpu:       100m
      Memory:    600Mi
  Retention:     90d
  Route Prefix:  /
  Rule Namespace Selector:
  Rule Selector:
    Match Labels:
      Release:  kube-prometheus-stack
  Scrape Config Namespace Selector:
  Scrape Config Selector:
  Scrape Interval:  30s
  Security Context:
    Fs Group:         2000
    Run As Group:     2000
    Run As Non Root:  true
    Run As User:      1000
    Seccomp Profile:
      Type:              RuntimeDefault
  Service Account Name:  kube-prometheus-stack-prometheus
  Service Monitor Namespace Selector:
  Service Monitor Selector:
    Match Labels:
      Release:  kube-prometheus-stack
  Shards:       1
  Storage:
    Volume Claim Template:
      Spec:
        Access Modes:
          ReadWriteOnce
        Resources:
          Requests:
            Storage:  10Gi
  Tsdb:
    Out Of Order Time Window:  0s
  Version:                     v2.48.1
  Wal Compression:             true
Status:
  Available Replicas:  1
  Conditions:
    Last Transition Time:  2023-12-23T21:44:56Z
    Message:               
    Observed Generation:   10
    Reason:                
    Status:                True
    Type:                  Available
    Last Transition Time:  2023-12-23T21:44:56Z
    Message:               
    Observed Generation:   10
    Reason:                
    Status:                True
    Type:                  Reconciled
  Paused:                  false
  Replicas:                1
  Shard Statuses:
    Available Replicas:    1
    Replicas:              1
    Shard ID:              0
    Unavailable Replicas:  0
    Updated Replicas:      1
  Unavailable Replicas:    0
  Updated Replicas:        1
Events:                    <none>
```

### prometheus-operator log output

```shell
level=info ts=2023-12-23T08:45:21.728287443Z caller=main.go:180 msg="Starting Prometheus Operator" version="(version=0.70.0, branch=refs/tags/v0.70.0, revision=c2c673f7123f3745a2a982b4a2bdc43a11f50fad)"
level=info ts=2023-12-23T08:45:21.728396959Z caller=main.go:181 build_context="(go=go1.21.4, platform=linux/amd64, user=Action-Run-ID-7048794395, date=20231130-15:41:45, tags=unknown)"
level=info ts=2023-12-23T08:45:21.728421135Z caller=main.go:192 msg="namespaces filtering configuration " config="{allow_list=\"\",deny_list=\"\",prometheus_allow_list=\"\",alertmanager_allow_list=\"\",alertmanagerconfig_allow_list=\"\",thanosruler_allow_list=\"\"}"
level=info ts=2023-12-23T08:45:21.734481836Z caller=main.go:221 msg="connection established" cluster-version=v1.27.7+k3s1
level=info ts=2023-12-23T08:45:21.741055286Z caller=operator.go:321 component=prometheusoperator msg="Kubernetes API capabilities" endpointslices=true
level=info ts=2023-12-23T08:45:21.74648157Z caller=operator.go:308 component=prometheusagentoperator msg="Kubernetes API capabilities" endpointslices=true
level=warn ts=2023-12-23T08:45:21.751198385Z caller=server.go:158 msg="server TLS client verification disabled" err="stat /etc/tls/private/tls-ca.crt: no such file or directory" client_ca_file=/etc/tls/private/tls-ca.crt
level=info ts=2023-12-23T08:45:21.752668331Z caller=server.go:259 msg="starting secure server" address=[::]:10250 http2=false
level=info ts=2023-12-23T08:45:21.8524043Z caller=operator.go:417 component=prometheusagentoperator msg="successfully synced all caches"
level=info ts=2023-12-23T08:45:21.852443664Z caller=operator.go:378 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2023-12-23T08:45:21.852448042Z caller=operator.go:309 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2023-12-23T08:45:21.852413096Z caller=operator.go:270 component=thanosoperator msg="successfully synced all caches"
level=info ts=2023-12-23T08:45:21.852795849Z caller=operator.go:641 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2023-12-23T08:45:21.85296089Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:21.880588457Z caller=operator.go:641 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2023-12-23T08:45:21.950444337Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:22.043528628Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:22.130932504Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:22.212721302Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:22.295930511Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:22.384688254Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=error ts=2023-12-23T08:45:22.465409355Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="sync \"monitoring/kube-prometheus-stack-prometheus\" failed: failed to create new ConfigMap 'prometheus-kube-prometheus-stack-prometheus-rulefiles-0': configmaps \"prometheus-kube-prometheus-stack-prometheus-rulefiles-0\" already exists"
level=info ts=2023-12-23T08:45:22.465504986Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:22.559551834Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:22.678054472Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:22.779411561Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:22.863348685Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:22.94340024Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:23.023700638Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:23.104028367Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:23.1826368Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:23.26640373Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:23.352120644Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:23.437634482Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:23.53954154Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:23.620507384Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:23.706080616Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:23.795806466Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:23.878893995Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:23.957128221Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:24.070044724Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:24.231352482Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:24.330981839Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:24.460292472Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:24.590510988Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:24.871807059Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:24.967374175Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:25.048327726Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:25.135414095Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:25.239868952Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:25.370749708Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:25.501222274Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:45:25.631376539Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:51:04.298879255Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:51:04.392819716Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T08:51:04.496060722Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T09:49:39.434304345Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T09:49:39.434293614Z caller=operator.go:641 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2023-12-23T09:49:39.455285532Z caller=operator.go:641 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2023-12-23T09:49:39.523812161Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T10:07:05.244083933Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T10:07:05.354877439Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T20:24:14.446780553Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T20:24:14.529420076Z caller=operator.go:641 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2023-12-23T20:24:14.548050017Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T20:24:14.632096065Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T20:24:18.045440615Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T20:24:18.04543253Z caller=operator.go:641 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2023-12-23T20:27:58.9599674Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T20:27:59.144465315Z caller=operator.go:641 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2023-12-23T20:27:59.170608578Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T20:38:20.140231549Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T20:38:20.140219827Z caller=operator.go:641 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2023-12-23T20:49:28.007962944Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T20:49:28.081430163Z caller=operator.go:641 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2023-12-23T20:49:28.093029619Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T21:00:15.253576752Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T21:00:15.332205076Z caller=operator.go:641 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2023-12-23T21:00:15.351831233Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T21:00:15.443874839Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T21:08:19.327589706Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T21:08:19.40190774Z caller=operator.go:641 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2023-12-23T21:08:19.420513142Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T21:08:19.514961223Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T21:20:46.971832212Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T21:20:47.043833911Z caller=operator.go:641 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2023-12-23T21:20:47.061800763Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T21:20:47.138795172Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T21:25:18.105250415Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T21:25:18.180593177Z caller=operator.go:641 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2023-12-23T21:25:18.19887932Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T21:25:18.280837029Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T21:28:55.100586669Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2023-12-23T21:28:55.288603298Z caller=operator.go:641 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2023-12-23T21:28:55.319544517Z caller=operator.go:975 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
```

### Anything else?

Helm Values

```yaml
prometheus:
  prometheusSpec:
    scrapeConfigSelectorNilUsesHelmValues: false

```
