### ISSUE TITLE
Invalid child routes in AlertmanagerConfig CRD triggers a panic

### ISSUE THREAD

**Issue by siretart** [prometheus-operator/prometheus-operator#6277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

The prometheus operator crashes on a bad CRD

## Steps to Reproduce

Using this:

```yaml
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: global-config
  labels:
    role: alert-rules
    namespace: monitoring
spec:
  route:
    groupBy:
      - namespace
      - alertname
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'matrix'
    # All alerts that do not match the following child routes
    # will remain at the root node and be dispatched to 'matrix'.
    routes:
      - receiver: 'null'
        matchers: [ alertname = "Watchdog" ]
```

## Expected Result

Ideally, the api server would reject the above CRD when trying to apply it to the cluster

## Actual Result

The CRD was expected, because the specification of the CRD is lax:

https://github.com/prometheus-operator/prometheus-operator/blob/372b00558d06a0aa2bc5f544f5c754dff4872527/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml#L5710-L5714

### Prometheus Operator Version

```shell
Name:                   kube-prometheus-stack-operator                                                                                                                                                             
Namespace:              monitoring                                                                                                                                                                                 
CreationTimestamp:      Fri, 20 Jan 2023 14:29:10 -0500                                                                                                                                                            
Labels:                 app=kube-prometheus-stack-operator                                                                                                                                                         
                        app.kubernetes.io/component=prometheus-operator                                                                                                                                            
                        app.kubernetes.io/instance=kube-prometheus-stack                                                                                                                                           
                        app.kubernetes.io/managed-by=Helm                                                                                                                                                          
                        app.kubernetes.io/name=kube-prometheus-stack-prometheus-operator                                                                                                                           
                        app.kubernetes.io/part-of=kube-prometheus-stack                                                                                                                                            
                        app.kubernetes.io/version=56.2.1                                                                                                                                                           
                        chart=kube-prometheus-stack-56.2.1                                                                                                                                                         
                        heritage=Helm                                                                                                                                                                              
                        release=kube-prometheus-stack                                                                                                                                                              
Annotations:            deployment.kubernetes.io/revision: 41
```

### Kubernetes Version

```yaml
kubectl version -o yaml
clientVersion:
  buildDate: "2022-06-15T14:22:29Z"
  compiler: gc
  gitCommit: f66044f4361b9f1f96f0053dd46cb7dce5e990a8
  gitTreeState: clean
  gitVersion: v1.24.2
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2023-12-27T16:01:02Z"
  compiler: gc
  gitCommit: 5b2d1271a6a00a8d71981cc968bc0f822620b9d8
  gitTreeState: clean
  gitVersion: v1.28.5+k3s1
  goVersion: go1.20.12
  major: "1"
  minor: "28"
  platform: linux/amd64
```

### Kubernetes Cluster Type

Rancher

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

Version: 0.71.2

### prometheus-operator log output

```shell
panic: route[0]: json: cannot unmarshal string into Go struct field Route.matchers of type v1alpha1.Matcher
```
