### ISSUE TITLE
Enable kubernetes node labels

### ISSUE THREAD

**Issue by HenryGuo1019** [prometheus-operator/prometheus-operator#6281]
### What is missing? Please describe.

Can i use kubernetes node labes as a target label ? I try to create a service-monitor witch use source_label "__meta_kubernetes_node_label_beta_kubernetes_io_arch" but i can't see it in the prometheus dashboard .

servicemonitor.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xcloud-vm-node-exporter
  namespace: monitoring # prometheus所在ns
    #  labels:
    #    vm.kubevirt.io/name: gyh-test01 # 与redis-srv service yaml中配置一样
      #    release: qph # prometheus的release
spec:
  namespaceSelector:
    any: true
    # matchNames:
    #- xcloud-iaas # 被监控service所在的ns
  selector:
    matchLabels:
      vm.kubevirt.io/prometheus: node-exporter
  endpoints:
  - port: node-exporter # port名称
    interval: 10s
    path: /metrics #路径，默认为/metrics
    relabelings:
    - action: replace
      sourceLabels:  [__meta_kubernetes_node_label_beta_kubernetes_io_arch]
      targetLabel: arch
```

prometheus-dashboard . Sorry i can't use upload screenshot. I can't get the label ”arch“ i added above.
```
<html>
<body>
<!--StartFragment-->



http://10.57.131.164:9100/metrics | UP | endpoint="node-exporter"instance="10.57.131.164:9100"job="gyh-test02-node-exporter"namespace="xcloud-iaas"pod="virt-launcher-gyh-test02-6zgbw"service="gyh-test02-node-exporter" | 9.482s ago | 70.932ms |  
http://10.57.131.166:9100/metrics | UP | endpoint="node-exporter"instance="10.57.131.166:9100"job="gyh-test01-node-exporter"namespace="xcloud-iaas"pod="virt-launcher-gyh-test01-sw75l"service="gyh-test01-node-exporter" | 7.236s ago | 161.451ms

<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```

## Environment
**Kubernetes Version:** 
v1.22.6+rke2r1
**Prometheus-Operator Version:**  
prometheus:v2.41.0
prometheus-operator:v0.62.0
