### ISSUE TITLE
0.71.x breaks Vertical Pod Autoscaler for individual shards with the implementation of the Prometheus CRDs scale subresource

### ISSUE THREAD

**Issue by mattiasnensen** [prometheus-operator/prometheus-operator#6291]
### Component(s)

Prometheus

### What is missing? Please describe.

Core problem: If a StatefulSet is owned by a controller (Prometheus object) with a scale subresource, then you cannot apply autoscaling on that StateFulset.

I would like the ability to choose whether or not to utilize/configure the Prometheus scale subresource that was added in 0.71.x.

The reason is that I used Vertical Pod Autoscaler until now for each shard, making it so we scale each shards resources individually. This saved me about $30,000 per year in memory costs in my environment. I assume that the cumulative monetary value of doing this for all Promethues instances everywhere is in the millions.

The scale subresource makes it so we can scale Prometheus with HPA, or with VPA of course, but we still then end up with the same requests and limits per shard, and this makes it so we waste a lot of resources on the ones not scraping kube-state-metrics or particular ingress gateways with high metric cardinality.

There are methods to make the distribution of metrics more even on shards, but it's still not as good as just using VPA for each individual shard in my honest opinion.

I ask you to reconsider the scale resource for Prometheus, as I don't believe it's as good as Vertical Pod Autoscaler for each StatefulSet. At least give us a separate CRD for Prometheus which we can choose to install if we don't want the scale subresource.

Best regards,
Mattias 

## Environment
Kubernetes Version: 1.25
Prometheus-Operator Version: 0.71.3

**Comment by ArthurSens** [comment]
Interesting problem!

When you used VPA on statefulsets, the Prometheus-Operator did not override the changes made by the VPA?

**Comment by ArthurSens** [comment]
A quick work around is to remove the scale subresource from the CRD before installing it, the operator should work even without those fields

**Comment by ArthurSens** [comment]
> No, the way VPA works is that it doesn't change the StatefulSet, it changes the pod when it's being scheduled, and then the pod gets an annotation which tells the StatefulSet controller not to mess with it.
> 
> The way it works now with 0.71.x is that VPA completely ignores anything controlled by the StatefulSet since VPA is made not to mess with children of objects with scale subresources. Therefore no recommendation is made and nothing happens.

Got it!

Could you try https://github.com/prometheus-operator/prometheus-operator/issues/6291#issuecomment-1931987803 and let us know how it goes?

**Comment by viennaa** [comment]
We ran into the same problem. Last working version with autoscaler is v0.70.0, everything above breaks.

The autoscaler responds with:
```status:
  conditions:
  - lastTransitionTime: "2024-02-07T10:03:42Z"
    message: 'Error checking if target is a topmost well-known or scalable controller:
      Unhandled targetRef monitoring.coreos.com/v1 / Prometheus / prometheus-whatever-name,
      last error Internal error occurred: the spec replicas field ".spec.shards" does
      not exist'
    status: "True"
    type: ConfigUnsupported
```

> Could you try [#6291 (comment)](https://github.com/prometheus-operator/prometheus-operator/issues/6291#issuecomment-1931987803) and let us know how it goes?

Confirmed working, with `v0.71.3` and this removed from `prometheuses.monitoring.coreos.com`

```
      subresources:
        scale:
          labelSelectorPath: .status.selector
          specReplicasPath: .spec.shards
          statusReplicasPath: .status.shards
```

Sticking with `v0.70.0` for now.

**Comment by simonpasquier** [comment]
Thanks for the report. Can you share more details on the VPA workflow?
I'm afraid that none of us is familiar enough with it.

**Comment by viennaa** [comment]
I have digged into this issue trying to understand, how this works. 

[This comment](https://github.com/kubernetes/autoscaler/issues/5925#issuecomment-1621330207) is was a good starting point along this [FAQ](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md#how-can-i-apply-vpa-to-my-custom-resource).

First I thought, it might be an implementation issue, most of other CRD implementations are going with `.spec.replicas` instead of `.spec.shard` like our operator here does. However I looked through the originating PR of this change and it was quite a long runner and reasonable to get this.

The problem is twofold.

**Problem 1**
The prometheus CRD needed to have `.spec.shards` specced. Since I don't want to use them, I just went with `1`.
```
spec:
  shards: 1
```
This then resolved the error and shows the next problem.


**Problem 2**
After step one, this error appears:
```
status:
  conditions:
  - lastTransitionTime: "2024-02-09T13:09:59Z"
    message: The targetRef controller has a parent but it should point to a topmost
      well-known or scalable controller
``` 

The (automatically generated) VPA for the statefulset has the following `targetRef`
```
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: prometheus-whatever-name
```

This needs to be switched to the topmost resource, which is Prometheus here.
```
  targetRef:
    apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    name: whatever-name
```

And it works again
```
conditions:
  - lastTransitionTime: "2024-02-09T13:52:43Z"
    status: "True"
    type: RecommendationProvided
```
