### ISSUE TITLE
config-reloader takes several minutes to reload successfully after an invalid additionalScrapeConfigs is fixed

### ISSUE THREAD

**Issue by FloMedja** [prometheus-operator/prometheus-operator#6310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

when a user specify a `additionalScrapeConfigs` in the prometheus configuration, If the initial configuration is invalid the `config-reloader` didn't reload when after the configuration is fixed. the config-reloader get stucked.

## Steps to Reproduce

-  create a secret that contains an invalid scrape config. The configuration need to be properly formatted `yaml` but not loadable by prometheus. This is an exemple of an invalid scrape config:

```yaml
- job_name: opencost
  honor_labels: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  dns_sd_configs:
    - names:
        - opencost-cost-analyzer
  type: A     # <----------------  we have a  bad indentation here
  port: 9003 # <---------------  we have a  bad indentation here
```
-  create a prometheus configuration with an `additionalScrapeConfigs` spec pointing to the previously created secret
-  the logs of the `config-reloader` shows that the configuration is invalid and can't be applied
-  fix the invalid scrape config. This is the fix of the previous exemple of scrape config:
```yaml
- job_name: opencost
  honor_labels: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  dns_sd_configs:
    - names:
        - opencost-cost-analyzer
      type: A     # <---------------- indentation fixed
      port: 9003 # <---------------   indentation fixed
```
-  the logs of the `config-reloader` are still showing that the configuration is invalid and can't be applied
- 
## Expected Result

The `config-reloader` load the valid scrape configs after a invalid scrape configs is initially pushed

## Actual Result

the `config-reloader` is stucked after a invalid scrape config is initially pushed, even after this invalid scrape configs is fixed

### Prometheus Operator Version

```shell
v0.70.0
```

### Kubernetes Version

```yaml
v1.26.8
```

### Kubernetes Cluster Type

minikube

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### prometheus-operator log output

```shell
the prometheus-operator didn't log any particular nessage related to the issue.
```

### Anything else?

Manually trigger the reloading refresh the `config-reloader`  and the scrape config is updated

`kubectl exec <peometheus-pod-name> -c config-reloader -- /bin/prometheus-config-reloader --listen-address=:8090 --reload-url=http://127.0.0.1:9090/-/reload`

Noticed that the port of the `--listen-address` should be different from the one already in use
