### ISSUE TITLE
Thanos Sidecar - Put Data in AWS S3 Bucket

### ISSUE THREAD

**Issue by PaintedShepherd** [prometheus-operator/prometheus-operator#6324]
### What happened?

I have activated the thanos sidecar on my prometheus and after 2h i see the following error in the logs of thanos container:
`level=info ts=2024-02-23T10:28:16.972042857Z caller=shipper.go:338 msg="upload new block" id=01HQAPN803SE2HE0N75DJK6NHS
level=warn ts=2024-02-23T10:28:17.041433057Z caller=sidecar.go:339 err="upload 01HQAPN803SE2HE0N75DJK6NHS: upload debug meta file: upload s3 object: The header 'x-amz-server-side-encryption-context' shall be Base64-encoded UTF-8 string holding JSON which represents a string-string map" uploaded=0`

This is my configuration-file used for thanos sidecar:

<pre> type: s3
config:
    bucket: "MyBucket"
    endpoint: "s3-eu-central-1.amazonaws.com"
    region: "eu-central-1"
    insecure: true
    signature_version2: false
    http_config:
        insecure_skip_verify: true
    sse_config:
        type: "SSE-KMS"
        kms_key_id: "XXX"</pre>

The documentation says, that the **kms_enryption_context** parameter is optional:
`If type is set to SSE-KMS you must set kms_key_id. The kms_encryption_context is optional, as [AWS provides a default encryption context](https://docs.aws.amazon.com/kms/latest/developerguide/services-s3.html#s3-encryption-context)`.

Any advise how to enable my thanos side to push to aws s3 with kms encryption?

### Prometheus Operator Version

```shell
0.69.1
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2023-10-18T11:33:16Z"
  compiler: gc
  gitCommit: a8a1abc25cad87333840cd7d54be2efaf31a3177
  gitTreeState: clean
  gitVersion: v1.28.3
  goVersion: go1.20.10
  major: "1"
  minor: "28"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-01-02T20:34:50Z"
  compiler: gc
  gitCommit: 95c835ee1111774fe5e8b327187034d8136720a0
  gitTreeState: clean
  gitVersion: v1.26.12-eks-5e0fdde
  goVersion: go1.20.12
  major: "1"
  minor: 26+
  platform: linux/amd64
```

### Kubernetes Cluster Type

EKS

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml
{
                apiVersion: "monitoring.coreos.com/v1",
                kind: "Prometheus",
                metadata:
                {
                    labels:
                    {
                        "app.kubernetes.io/component": "prometheus",
                        "app.kubernetes.io/instance": "k8s",
                        "app.kubernetes.io/name": "prometheus",
                        "app.kubernetes.io/part-of": "kube-prometheus",
                        "app.kubernetes.io/version": "2.49.1",
                    },
                    name: "k8s",
                    namespace: this.prometheusShardNamespace.name
                },
                spec:
                {
                    thanos:
                    {
                        image: `IMAGE_REPO/thanos/thanos:v0.24.0`,
                        objectStorageConfig:
                        {
                            key: "thanos.yaml", //needs to match the name of the secret-key
                            name: PrometheusShardStack.THANOS_SECRET_NAME
                        }
                    },
                    alerting:
                    {
                        alertmanagers:
                            [
                                {
                                    apiVersion: "v2",
                                    name: "alertmanager-main",
                                    namespace: this.prometheusShardNamespace.name,
                                    port: "web"
                                }
                            ]
                    },
                    enableFeatures: [],
                    externalLabels: {},
                    image: "IMAGE_REPO/prometheus/prometheus:v2.49.1",
                    nodeSelector:
                    {
                        "kubernetes.io/os": "linux"
                    },
                    podMetadata:
                    {
                        labels:
                        {
                            "app.kubernetes.io/component": "prometheus",
                            "app.kubernetes.io/instance": "k8s",
                            "app.kubernetes.io/name": "prometheus",
                            "app.kubernetes.io/part-of": "kube-prometheus",
                            "app.kubernetes.io/version": "2.49.1"
                        }
                    },
                    podMonitorNamespaceSelector: {},
                    podMonitorSelector: {},
                    probeNamespaceSelector: {},
                    probeSelector: {},
                    replicas: 2,
                    resources:
                    {
                        requests:
                        {
                            memory: "400Mi"
                        }
                    },
                    ruleNamespaceSelector: {},
                    ruleSelector: {},
                    scrapeConfigNamespaceSelector:
                    {
                        matchExpressions:
                            [
                                {
                                    key: "kubernetes.io/metadata.name",
                                    operator: "In",
                                    values: [this.prometheusShardNamespace.name]
                                }
                            ]
                    },
                    scrapeConfigSelector:
                    {
                        matchExpressions:
                            [{
                                key: "federated-prometheus-configs",
                                operator: "In",
                                values:
                                    [this.prometheusShardNamespace.name]
                            }]
                    },
                    securityContext:
                    {
                        fsGroup: 2000,
                        runAsNonRoot: true,
                        runAsUser: 1000
                    },
                    serviceAccountName: PrometheusShardStack.SERVICE_ACCONT_NAME,
                    serviceMonitorNamespaceSelector:
                    {
                        matchExpressions:
                            [{
                                key: "kubernetes.io/metadata.name",
                                operator: "In",
                                values: [this.prometheusShardNamespace.name]
                            }]
                    },
                    version: "2.49.1"
                }
            }
```

### prometheus-operator log output

```shell
level=info ts=2024-02-23T07:02:09.644780249Z caller=main.go:256 msg="Starting Prometheus Operator" version="(version=0.69.1, branch=refs/tags/v0.69.1, revision=941b9e98d4ae5faa952af250e23c31c56cc1190c)"
level=info ts=2024-02-23T07:02:09.644828619Z caller=main.go:257 build_context="(go=go1.21.4, platform=linux/amd64, user=Action-Run-ID-6812497076, date=20231109-15:18:17, tags=unknown)"
level=info ts=2024-02-23T07:02:09.653415112Z caller=main.go:322 msg="connection established" cluster-version=v1.26.12-eks-5e0fdde
level=info ts=2024-02-23T07:02:09.664840547Z caller=operator.go:360 component=prometheusoperator msg="Kubernetes API capabilities" endpointslices=true
level=info ts=2024-02-23T07:02:09.674970702Z caller=operator.go:308 component=prometheusagentoperator msg="Kubernetes API capabilities" endpointslices=true
level=info ts=2024-02-23T07:02:09.68803787Z caller=main.go:147 msg="Starting secure server on [::]:10250" http2=false
level=info ts=2024-02-23T07:02:09.78618645Z caller=operator.go:323 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2024-02-23T07:02:09.786258691Z caller=operator.go:417 component=prometheusagentoperator msg="successfully synced all caches"
level=info ts=2024-02-23T07:02:09.786407962Z caller=operator.go:655 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=info ts=2024-02-23T07:02:09.787915474Z caller=operator.go:283 component=thanosoperator msg="successfully synced all caches"
level=info ts=2024-02-23T07:02:09.788129677Z caller=operator.go:417 component=prometheusoperator msg="successfully synced all caches"
level=warn ts=2024-02-23T07:02:09.791489946Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-iat msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match=map[netcool_iat:true] match_re=map[]
level=warn ts=2024-02-23T07:02:09.791520186Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-iat msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HEARTBEAT-Check netcool_iat:true]" match_re=map[]
level=warn ts=2024-02-23T07:02:09.791530806Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-iat msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HeartbeatMonitoring netcool_iat:true]" match_re=map[]
level=warn ts=2024-02-23T07:02:09.791539546Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-prd msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match=map[netcool_prd:true] match_re=map[]
level=warn ts=2024-02-23T07:02:09.791550156Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-prd msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HEARTBEAT-Check netcool_prd:true]" match_re=map[]
level=warn ts=2024-02-23T07:02:09.791561086Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-prd msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HeartbeatMonitoring netcool_prd:true]" match_re=map[]
level=info ts=2024-02-23T07:02:09.794978426Z caller=operator.go:1181 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2024-02-23T07:02:09.871116749Z caller=operator.go:655 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=warn ts=2024-02-23T07:02:09.87809302Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-iat msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match=map[netcool_iat:true] match_re=map[]
level=warn ts=2024-02-23T07:02:09.87813986Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-iat msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HEARTBEAT-Check netcool_iat:true]" match_re=map[]
level=warn ts=2024-02-23T07:02:09.87815549Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-iat msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HeartbeatMonitoring netcool_iat:true]" match_re=map[]
level=warn ts=2024-02-23T07:02:09.87816787Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-prd msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match=map[netcool_prd:true] match_re=map[]
level=warn ts=2024-02-23T07:02:09.878180561Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-prd msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HEARTBEAT-Check netcool_prd:true]" match_re=map[]
level=warn ts=2024-02-23T07:02:09.878192841Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-prd msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HeartbeatMonitoring netcool_prd:true]" match_re=map[]
level=info ts=2024-02-23T07:02:09.977126941Z caller=operator.go:1181 component=prometheusoperator key=ris-ripl/k8s msg="sync prometheus"
level=info ts=2024-02-23T07:02:10.189512892Z caller=operator.go:1181 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2024-02-23T10:30:48.044535131Z caller=operator.go:1181 component=prometheusoperator key=ris-ripl/k8s msg="sync prometheus"
level=info ts=2024-02-23T10:30:48.243730864Z caller=operator.go:1181 component=prometheusoperator key=ris-ripl/k8s msg="sync prometheus"
level=info ts=2024-02-23T10:30:48.440957953Z caller=operator.go:1181 component=prometheusoperator key=ris-ripl/k8s msg="sync prometheus"
level=info ts=2024-02-23T10:30:48.455255743Z caller=operator.go:655 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=warn ts=2024-02-23T10:30:48.462776171Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-iat msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match=map[netcool_iat:true] match_re=map[]
level=warn ts=2024-02-23T10:30:48.462823972Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-iat msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HEARTBEAT-Check netcool_iat:true]" match_re=map[]
level=warn ts=2024-02-23T10:30:48.462835102Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-iat msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HeartbeatMonitoring netcool_iat:true]" match_re=map[]
level=warn ts=2024-02-23T10:30:48.462843682Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-prd msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match=map[netcool_prd:true] match_re=map[]
level=warn ts=2024-02-23T10:30:48.462852222Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-prd msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HEARTBEAT-Check netcool_prd:true]" match_re=map[]
level=warn ts=2024-02-23T10:30:48.462860783Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-prd msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HeartbeatMonitoring netcool_prd:true]" match_re=map[]
level=info ts=2024-02-23T10:30:48.522877706Z caller=operator.go:655 component=alertmanageroperator key=monitoring/kube-prometheus-stack-alertmanager msg="sync alertmanager"
level=warn ts=2024-02-23T10:30:48.527088123Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-iat msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match=map[netcool_iat:true] match_re=map[]
level=warn ts=2024-02-23T10:30:48.527142724Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-iat msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HEARTBEAT-Check netcool_iat:true]" match_re=map[]
level=warn ts=2024-02-23T10:30:48.527160716Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-iat msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HeartbeatMonitoring netcool_iat:true]" match_re=map[]
level=warn ts=2024-02-23T10:30:48.527174446Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-prd msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match=map[netcool_prd:true] match_re=map[]
level=warn ts=2024-02-23T10:30:48.527188406Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-prd msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HEARTBEAT-Check netcool_prd:true]" match_re=map[]
level=warn ts=2024-02-23T10:30:48.527202256Z caller=amcfg.go:2207 component=alertmanageroperator alertmanager=kube-prometheus-stack-alertmanager namespace=monitoring receiver=netcool-prd msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="map[alarm_group:HeartbeatMonitoring netcool_prd:true]" match_re=map[]
To bottom
```
