### ISSUE TITLE
Incomplete method of prometheus-operator validation rule?

### ISSUE THREAD

**Issue by magiceses** [prometheus-operator/prometheus-operator#6336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
I noticed that the method used by prometheus-operator to verify the spec of prometheusRule is github.com/prometheus/prometheus@v0.46.0/model/rulefmt/rulefmt.go:testTemplateParsing.

However, this method can only verify the $value, $labels, $externalLabels, and $externalURL variables, not variables that start with dots, such as. Value,. Labels,. ExternalLabels, and. ExternalURL.

If I use {{.External}} when defining a rule, the prometheus-operator will not report an error and will load the rule normally, but the alarm message triggered by the rule will fail to parse and output something like:
'< Error expanding template: error executing template __alert_ node CPU usage greater than 10%: template: __alert_ node CPU usage greater than 10%!: (string = External) 1:118: executing "__alert_ node CPU usage greater than 10%" at <. External >: can't evaluate field struct {Labels map [string] string; ExternalLabels map [string] string; ExternalURL string; Value float64} in type%! s (MISSING) >'

## Steps to Reproduce
When referring to a variable in the annotations field, add {{.External}}

## Expected Result
prometheus-operator raise error, report the rule is invalid.

## Actual Result
normal render

### Prometheus Operator Version

```shell
v0.61.1
```

### Kubernetes Version

```yaml
1.27
```

### Kubernetes Cluster Type

kubeadm

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### prometheus-operator log output

```shell
None
```

**Comment by slashpai** [comment]
We had improvements in latest versions to reject invalid rules, can you try latest version?

**Comment by magiceses** [comment]
Sorry, i do not see any change here. Can you tell me where you improving?
```go
// ValidateRule takes PrometheusRuleSpec and validates it using the upstream prometheus rule validator.
func ValidateRule(promRuleSpec monitoringv1.PrometheusRuleSpec) []error {
	for i := range promRuleSpec.Groups {
		// The upstream Prometheus rule validator doesn't support the
		// partial_response_strategy field.
		promRuleSpec.Groups[i].PartialResponseStrategy = ""

		// Empty durations need to be translated to nil to be omitted from the
		// YAML ouptut otherwise the generated configuration will not be valid.
		if promRuleSpec.Groups[i].Interval != nil && *promRuleSpec.Groups[i].Interval == "" {
			promRuleSpec.Groups[i].Interval = nil
		}

		for j := range promRuleSpec.Groups[i].Rules {
			if promRuleSpec.Groups[i].Rules[j].For != nil && *promRuleSpec.Groups[i].Rules[j].For == "" {
				promRuleSpec.Groups[i].Rules[j].For = nil
			}
		}
	}

	content, err := yaml.Marshal(promRuleSpec)
	if err != nil {
		return []error{errors.Wrap(err, "failed to marshal content")}
	}
	_, errs := rulefmt.Parse(content)
	return errs
}
```
This is still checked with the prometheus rulefmt library.

**Comment by slashpai** [comment]
[Select method](https://github.com/prometheus-operator/prometheus-operator/blob/c5098f5d050544850ffee285fb8dee9c8d4050c3/pkg/operator/rules.go#L165-L222) is introduced to reject invalid rules and added more [validations at CRD level](https://github.com/prometheus-operator/prometheus-operator/blob/c5098f5d050544850ffee285fb8dee9c8d4050c3/pkg/apis/monitoring/v1/prometheusrule_types.go
)

It still uses upstream rule validator to validate rules. 

Could you please provide a example PrometheusRule manifest where you see the issue

**Comment by magiceses** [comment]
If i set rule :
```yaml
  groups:
  - name: 3f541c787ebd4054896a1cb9ad9965d2
    rules:
    - alert: xxxxxxx
      annotations:
        summary: |2-

          xx {{ .External }}

          {{ range query "up" }}
            {{ .Labels.instance }} {{ .Value }}
          {{ end }}
        summary_en: |2-

          xx {{ .External }}
          {{ range query "up" }}
            {{ .Labels.instance }} {{ .Value }}
          {{ end }}
      expr: xxxxxxxx
      for: 0m
      labels:
        alert_id: "10032"
```
The rule will be created successfully, but the {{ .External }} is not correct for prometheus. So prometheus will send error message to alertmanager, just like : '< Error expanding template: error executing template _alert node CPU usage greater than 10%: template: _alert node CPU usage greater than 10%!: (string = External) 1:118: executing "_alert node CPU usage greater than 10%" at <. External >: can't evaluate field struct {Labels map [string] string; ExternalLabels map [string] string; ExternalURL string; Value float64} in type%! s (MISSING) >'.

The above error is because there are no External variables.
