### ISSUE TITLE
Setting enableCompression to false in scrapeConfig is not taken into account by prometheus

### ISSUE THREAD

**Issue by JerbiAhmed** [prometheus-operator/prometheus-operator#6354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
Setting `enableCompression: false` under `ScrapeConfig.spec` will not have any effect as in scrape_config we will always get default value for `enable_compression: true`

## Steps to Reproduce

- Create a ScrapeConfig with enableCompression set to false

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: "{{ .Values.label }"
  namespace: "{{ .Values.namespace }}"
  labels:
    prometheus: system-monitoring-prometheus
spec:
  staticConfigs:
    - labels:
        job: "monitoring/demo"
      targets:
        - hostname1:9000
        - hostname2:9000
  scrapeInterval: "1m"
  enableCompression: false
``` 

- Create prometheus ressource with scrapeConfigSelector that matchs all labels (setting a specific label will not allow prometheus to discover the scrapConfig but this is another issue)

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
  labels:
    app: prometheus
spec:
  image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
  logLevel: "info" 
  replicas: {{ .Values.replicas }}
  resources:
    requests:
      memory: 400Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  version: {{ .Values.image.tag }}
  scrapeConfigSelector: {}
{{- if .Values.storage.enabled }}
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: {{ .Values.storage.className }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
{{- end}}
``` 

## Expected Result

Get enable_compression: false in job monitoring/demo scrape_configs

## Actual Result
ScrapConfig is loaded by prometheus without the enable_compression value, thus default true value is set.

```
- - job_name: scrapeConfig/monitoring/demo
  scrape_interval: 1m                      
  static_configs:
  - targets:      
        - hostname1:9000
        - hostname2:9000
    labels:              
      job: monitoring/demo
  relabel_configs:
  - source_labels:                        
    - job                 
    target_label: __tmp_prometheus_job_name
``` 
    

- Using `kubectl describe scrapeconfigs.monitoring.coreos.com` we are able to see that Enable Compression is set to false.

```
Spec:
  Enable Compression:  false
  Scrape Interval:     1m
  Static Configs:
    Labels:
      Job:  monitoring/demo
    Targets:
        - hostname1:9000
        - hostname2:9000
Events:  <none>

``` 

### Prometheus Operator Version

```shell
v0.71.2
```

### Kubernetes Version

```yaml
v1.27.5
```

### Kubernetes Cluster Type

GKE

### How did you deploy Prometheus-Operator?

yaml manifests

### prometheus-operator log output

```shell
Nothing relevent
```
