### ISSUE TITLE
Label drop not working in service discovery

### ISSUE THREAD

**Issue by r-aju** [prometheus-operator/prometheus-operator#6355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
I have a service monitor through which prometheus scrapes metrics as CRD. I'm currently trying to drop some labels in my service monitor configs, and when I make the change in the service monitor with the label drop configs, The labels are not getting dropped. below is my service monitor configuration file.

`
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: segmentation-service
    release: prometheus-operator
  name: segmentation-service
  namespace: segmentation-service
spec:
  endpoints:
  - interval: 30s
    path: /prometheus
    port: http-8080
  - metricRelabelings:
    - action: labeldrop
      regex: instance
    - action: labeldrop
      regex: pod  
  namespaceSelector:
    matchNames:
    - segmentation-service
  selector:
    matchLabels:
      app.kubernetes.io/name: segmentation-service
      service-type: metrics
      
```

And in the prometheus UI this is how the scrape target configs looks like
```
`- job_name: serviceMonitor/segmentation-service/segmentation-service/0
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /prometheus
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: (.*)
    target_label: __tmp_prometheus_job_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name, __meta_kubernetes_service_labelpresent_app_kubernetes_io_name]
    separator: ;
    regex: (segmentation-service);true
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_service_label_service_type, __meta_kubernetes_service_labelpresent_service_type]
    separator: ;
    regex: (metrics);true
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: http-8080
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Node;(.*)
    target_label: node
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Pod;(.*)
    target_label: pod
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: (.*)
    target_label: container
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_phase]
    separator: ;
    regex: (Failed|Succeeded)
    replacement: $1
    action: drop
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: http-8080
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 1
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: "0"
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - segmentation-service
```

Not sure on why does it have scrape with the name `serviceMonitor/segmentation-service/segmentation-service/1` and `serviceMonitor/segmentation-service/segmentation-service/0` .
## Expected Result
The labels `pod` and `instances` from the prometheus scrape metric should be dropped which it is not ideally happening.
## Actual Result
<img width="433" alt="labeldropp" src="https://github.com/prometheus-operator/prometheus-operator/assets/43216503/a0d1f74d-0ff7-4099-8aad-be69ca7ed305">

### Prometheus Operator Version

```shell
Name:                   prometheus-operator-kube-p-operator
Namespace:              monitoring
CreationTimestamp:      Mon, 10 Jul 2023 12:59:29 +0530
Labels:                 app=kube-prometheus-stack-operator
                        app.kubernetes.io/instance=prometheus-operator
                        app.kubernetes.io/managed-by=spinnaker
                        app.kubernetes.io/name=cluster-setup
                        app.kubernetes.io/part-of=kube-prometheus-stack
                        app.kubernetes.io/version=46.8.0
                        chart=kube-prometheus-stack-46.8.0
                        heritage=Helm
                        release=prometheus-operator
Annotations:            artifact.spinnaker.io/location: monitoring
                        artifact.spinnaker.io/name: prometheus-operator-kube-p-operator
                        artifact.spinnaker.io/type: kubernetes/deployment
                        artifact.spinnaker.io/version:
                        deployment.kubernetes.io/revision: 2
                        moniker.spinnaker.io/application: cluster-setup
                        moniker.spinnaker.io/cluster: deployment prometheus-operator-kube-p-operator
Selector:               app=kube-prometheus-stack-operator,release=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=kube-prometheus-stack-operator
                    app.kubernetes.io/instance=prometheus-operator
                    app.kubernetes.io/managed-by=spinnaker
                    app.kubernetes.io/name=cluster-setup
                    app.kubernetes.io/part-of=kube-prometheus-stack
                    app.kubernetes.io/version=46.8.0
                    chart=kube-prometheus-stack-46.8.0
                    heritage=Helm
                    release=prometheus-operator
  Annotations:      artifact.spinnaker.io/location: monitoring
                    artifact.spinnaker.io/name: prometheus-operator-kube-p-operator
                    artifact.spinnaker.io/type: kubernetes/deployment
                    artifact.spinnaker.io/version:
                    moniker.spinnaker.io/application: cluster-setup
                    moniker.spinnaker.io/cluster: deployment prometheus-operator-kube-p-operator
  Service Account:  prometheus-operator-kube-p-operator
  Containers:
   kube-prometheus-stack:
    Image:      quay.io/prometheus-operator/prometheus-operator:v0.65.2
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/prometheus-operator-kube-p-kubelet
      --localhost=127.0.0.1
      --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.65.2
      --config-reloader-cpu-request=200m
      --config-reloader-cpu-limit=200m
      --config-reloader-memory-request=50Mi
      --config-reloader-memory-limit=50Mi
      --thanos-default-base-image=quay.io/thanos/thanos:v0.31.0
      --secret-field-selector=type!=kubernetes.io/dockercfg,type!=kubernetes.io/service-account-token,type!=helm.sh/release.v1
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  prometheus-operator-kube-p-operator-6cd8c6696b (0/0 replicas created)
NewReplicaSet:   prometheus-operator-kube-p-operator-68cb9858c7 (1/1 replicas created)
Events:          <none>
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-01-17T15:41:11Z"
  compiler: gc
  gitCommit: bc401b91f2782410b3fb3f9acf43a995c4de90d2
  gitTreeState: clean
  gitVersion: v1.29.1
  goVersion: go1.21.6
  major: "1"
  minor: "29"
  platform: darwin/arm64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-01-02T20:34:50Z"
  compiler: gc
  gitCommit: 95c835ee1111774fe5e8b327187034d8136720a0
  gitTreeState: clean
  gitVersion: v1.26.12-eks-5e0fdde
  goVersion: go1.20.12
  major: "1"
  minor: 26+
  platform: linux/amd64

WARNING: version difference between client (1.29) and server (1.26) exceeds the supported minor version skew of +/-1
```

### Kubernetes Cluster Type

EKS

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml
the official one
```

### prometheus-operator log output

```shell
the official one
```

### Anything else?

the official one
