### ISSUE TITLE
ScrapeConfig not applied when deployed via CRD

### ISSUE THREAD

**Issue by EugenMayer** [prometheus-operator/prometheus-operator#6363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

deploying a scrape config via a crd in the stack deployed via the `kube-prometheus-stack` chart

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: opnsense
  namespace: kube-prometheus-stack
spec:
  staticConfigs:
    - targets:
        - 10.10.10.2:9100
```

While having the typical configs for the operator .

```yaml
prometheus:
  prometheusSpec:
    scrapeConfigNamespaceSelector: {}
    scrapeConfigSelector: {}
    scrapeConfigSelectorNilUsesHelmValues: false
    retain: '10d'
    retentionSize: ''

prometheusOperator:
  logLevel: debug
```

The scrape config does never show in in prometheus under `/targets`

Reading the similar #6189 i deployed the operator with debug logs and in fact i can see that the ScrapeConfig CRD is picked up
```
level=debug ts=2024-03-03T15:44:58.818656387Z caller=resource_selector.go:768 component=prometheus-controller msg="selected ScrapeConfigs" scrapeConfig=kube-prometheus-stack/opnsense namespace=kube-prometheus-stack prometheus=kube-prometheus-stack-prometheus
```

## Expected Result

The target/scrape config should be added to prom and show up under targets

## Actual Result

Scrape config never shows up

### Prometheus Operator Version

```shell
kubectl -n kube-prometheus-stack describe deployment/kube-prometheus-stack-operator
```

```
Name:                   kube-prometheus-stack-operator
Namespace:              kube-prometheus-stack
CreationTimestamp:      Sun, 03 Mar 2024 12:30:35 +0100
Labels:                 app=kube-prometheus-stack-operator
                        app.kubernetes.io/component=prometheus-operator
                        app.kubernetes.io/instance=kube-prometheus-stack
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=kube-prometheus-stack-prometheus-operator
                        app.kubernetes.io/part-of=kube-prometheus-stack
                        app.kubernetes.io/version=56.19.0
                        chart=kube-prometheus-stack-56.19.0
                        heritage=Helm
                        release=kube-prometheus-stack
Annotations:            deployment.kubernetes.io/revision: 2
                        meta.helm.sh/release-name: kube-prometheus-stack
                        meta.helm.sh/release-namespace: kube-prometheus-stack
Selector:               app=kube-prometheus-stack-operator,release=kube-prometheus-stack
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=kube-prometheus-stack-operator
                    app.kubernetes.io/component=prometheus-operator
                    app.kubernetes.io/instance=kube-prometheus-stack
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=kube-prometheus-stack-prometheus-operator
                    app.kubernetes.io/part-of=kube-prometheus-stack
                    app.kubernetes.io/version=56.19.0
                    chart=kube-prometheus-stack-56.19.0
                    heritage=Helm
                    release=kube-prometheus-stack
  Service Account:  kube-prometheus-stack-operator
  Containers:
   kube-prometheus-stack:
    Image:      quay.io/prometheus-operator/prometheus-operator:v0.71.2
```

### Kubernetes Version

```
1.29.0
```

### Kubernetes Cluster Type

`k3s`

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml
prometheus:
  prometheusSpec:
    scrapeConfigNamespaceSelector: {}
    scrapeConfigSelector: {}
    scrapeConfigSelectorNilUsesHelmValues: false
    retain: '10d'
    retentionSize: ''

prometheusOperator:
  logLevel: debug
```

### prometheus-operator log output

```shell
level=debug ts=2024-03-03T15:44:58.818656387Z caller=resource_selector.go:768 component=prometheus-controller msg="selected ScrapeConfigs" scrapeConfig=kube-prometheus-stack/opnsense namespace=kube-prometheus-stack prometheus=kube-prometheus-stack-prometheus
```
