### ISSUE TITLE
example/user-guides/getting-started does not work

### ISSUE THREAD

**Issue by kaihendry** [prometheus-operator/prometheus-operator#6370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Steps to Reproduce

https://s.natalian.org/2024-03-06/prom-operator.mp4

1. helm install weds prometheus-community/kube-prometheus-stack
2. Use https://github.com/prometheus-operator/prometheus-operator/tree/main/example/user-guides/getting-started and modify to use hendry/slo:latest instead of quay because of my m1 macbook

## Expected Result

Auto discovered and scraped example service

## Actual Result

No example service targets

### Prometheus Operator Version

```shell
https://gist.github.com/kaihendry/58142f6b8498fe3ab73a0f20179b6eba
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "1980-01-01T00:00:00Z"
  compiler: gc
  gitCommit: 4b8e819355d791d96b7e9d9efe4cbafae2311c88
  gitTreeState: archive
  gitVersion: v1.29.2
  goVersion: go1.21.7
  major: "1"
  minor: "29"
  platform: darwin/arm64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2023-10-18T11:33:18Z"
  compiler: gc
  gitCommit: a8a1abc25cad87333840cd7d54be2efaf31a3177
  gitTreeState: clean
  gitVersion: v1.28.3
  goVersion: go1.20.10
  major: "1"
  minor: "28"
  platform: linux/arm64
```

### Kubernetes Cluster Type

kind

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### prometheus-operator log output

```shell
How do do this?
```
