### ISSUE TITLE
Support all pagerduty_config options in AlertmanagerConfig crd

### ISSUE THREAD

**Issue by Aaron-ML** [prometheus-operator/prometheus-operator#6387]
### Component(s)

AlertManagerConfig

### What is missing? Please describe.

Currently walking through going from a static alertmanager config to a more dynamic approach using alertmanagerconfig crds. Immediately noticed that there are a few fields missing in the crd for the pagerduty_config options. I had assumed they weren't mapped 1:1 but they appear to be. 

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: pagerduty-non-critical
  labels:
    alertconfig: monitoring
spec:
  receivers:
    - name: pagerduty_non_critical
      pagerdutyConfigs: # this crd maps without an underscore here
      - class: '{{ .GroupLabels.alertname }}'
        group: '{{ .GroupLabels.cluster }}'
        routing_key: <redacted>
        severity: |
          {{- if or (eq .GroupLabels.severity "info") (eq .GroupLabels.severity "warning") (eq .GroupLabels.severity "error") (eq .GroupLabels.severity "critical") -}}
          {{- .GroupLabels.severity -}}
          {{ else }}critical{{- end -}}
        source: '[Cluster: {{ .CommonLabels.cluster }}] [Namespace: {{ .CommonLabels.namespace
          }}] [Pod: {{ range .Alerts }}{{ .Labels.pod }}]{{ end }} [Container: {{ range
          .Alerts }}{{ .Labels.container }}]{{ end }}'
        url: https://events.pagerduty.com/v2/enqueue
```
```
Error from server (BadRequest): error when creating "alertmanagerconfig.yaml": AlertmanagerConfig in version "v1alpha1" cannot be handled as a AlertmanagerConfig: strict decoding error: unknown field "spec.receivers[0].pagerdutyConfigs[0].routing_key", unknown field "spec.receivers[0].pagerdutyConfigs[0].source"
```

Using alertmanager config directly I can use source and other fields without issue, going through the alertmanagerconfig CRD is an issue since not all fields are exposed at that level.

https://prometheus.io/docs/alerting/latest/configuration/#pagerduty_config
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#pagerdutyconfig

### Describe alternatives you've considered.

N/A

## Environment
Kubernetes Version: 1.26
Prometheus-Operator Version: 72.0
