### ISSUE TITLE
Add a new servicemonitor to cluster but prometheus-operator sync failed

### ISSUE THREAD

**Issue by yehaifeng** [prometheus-operator/prometheus-operator#6397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
I installed prometheus using the chart of kube-prometheus-stack, which version is `v57.0.1` . 
I wanted to monitor my rook-ceph cluster in kubernetes,  but prometheus sync failed to update new config.

## Expected Result
Prometheus can scrape the metrics of rook-ceph.

## Actual Result
No data in prometheus.

### Prometheus Operator Version

```shell
prometheus-operator: v0.72.0
```

### Kubernetes Version

```yaml
v1.28.2
```

### Kubernetes Cluster Type

kubeadm

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-mgr
  namespace: monitoring
spec:
  endpoints:
  - interval: 9s
    path: /metrics
    port: http-metrics
  jobLabel: rook-ceph-mgr
  namespaceSelector:
    matchNames:
    - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: rook-ceph
```

### prometheus-operator log output

```shell
level=info ts=2024-03-15T05:40:18.070005221Z caller=operator.go:984 component=prometheus-controller key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2024-03-15T05:40:18.305359649Z caller=operator.go:1182 component=prometheus-controller msg="failed to apply prometheus status subresource, trying again without scale fields" err="failed to create typed patch object (monitoring/kube-prometheus-stack-prometheus; monitoring.coreos.com/v1, Kind=Prometheus): .status.selector: field not declared in schema"
```
