### ISSUE TITLE
Add a servimonitor to scrape metrics but no targets in prometheus

### ISSUE THREAD

**Issue by yehaifeng** [prometheus-operator/prometheus-operator#6398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
I wanted to scrape metrcs for my service using a servicemonitor, but no data in prometheus and no targets in configuration of it.

### Prometheus Operator Version

```shell
v0.72.0
```

### Kubernetes Version

```yaml
v1.28.2
```

### Kubernetes Cluster Type

kind

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### Manifests

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-ovn-cni
  namespace: monitoring
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 16s
      port: metrics
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: kube-ovn-cni
```

### prometheus-operator log output

```shell
level=info ts=2024-03-15T08:12:40.166451149Z caller=operator.go:984 component=prometheus-controller key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2024-03-15T08:20:42.864116987Z caller=operator.go:984 component=prometheus-controller key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
level=info ts=2024-03-15T08:22:07.29634103Z caller=operator.go:984 component=prometheus-controller key=monitoring/kube-prometheus-stack-prometheus msg="sync prometheus"
```
