### ISSUE TITLE
Allow users to use OTEL Kubernetes semantic conventions

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#6432]
### Component(s)

Prometheus, PrometheusAgent, ServiceMonitor, PodMonitor, Probe

### What is missing? Please describe.

Right now the operator hardcodes the target labels in the scrape configurations:
* "pod"
* "namespace"
* "service"
* "container"
* ...

OpenTelemetry uses different conventions for Kubernetes resource attributes (https://opentelemetry.io/docs/specs/semconv/attributes-registry/k8s/) which aren't possible to apply right now but once Prometheus supports UTF-8 characters for metric and label names, the operator should offer a way to opt-in for the OTEL conventions.

## Environment
N/A

**Comment by haanhvu** [comment]
So we need to wait for https://github.com/prometheus/prometheus/issues/13095 to finish right?

**Comment by simonpasquier** [comment]
@haanhvu yes

**Comment by jmichalek132** [comment]
Hi, would it make sense to implement support in the mean time for the naming of the resource attributes with dots being replaced with underscores? If so I would be willing work on that.

**Comment by simonpasquier** [comment]
@jmichalek132 yes it sounds like a good approach to me.

@ArthurSens @nicolastakashi @slashpai more thoughts on this?

**Comment by ArthurSens** [comment]
Changing behavior after we implement the API (using dots once Prometheus supports it) doesn't sound like a good approach, so I would say yes if we put this behind a feature flag. 

From my understanding, it is still unclear within the Prometheus team itself how UTF-8 will be supported. It wouldn't make sense for us to commit to a stable feature until Prometheus does it.

**Comment by haanhvu** [comment]
> Hi, would it make sense to implement support in the mean time for the naming of the resource attributes with dots being replaced with underscores? If so I would be willing work on that.

Seems like this is not finalized yet? It's one of the things being asked in user survey: https://x.com/opentelemetry/status/1785657674861809910

**Comment by simonpasquier** [comment]
> I would say yes if we put this behind a feature flag.

Agreed, I would definitely marketed it as experimental/subject to change.

**Comment by simonpasquier** [comment]
Thinking more about it, we can also allow users to fully customize the target labels in which case OTEL conventions become a special case.

Completely made-up API:

````
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  ...
spec:
  targetMetadataMapping:
    pod: "k8s_pod_name" # it can be changed to "k8s.pod.name" once/if supported by Prometheus
    namespace: "k8s_namespace_name"
    container: "" # use the default "container" label
````
