### ISSUE TITLE
Allow a custom label for sharding.

### ISSUE THREAD

**Issue by arnecls** [prometheus-operator/prometheus-operator#6437]
### Component(s)

Prometheus

### What is missing? Please describe.

Currently the recording rule assigning endpoint to shards is hardcoded to `__address__`.

https://github.com/prometheus-operator/prometheus-operator/blob/d87710bd7201425d078374eef1312cb985bd9c08/pkg/prometheus/promcfg.go#L1613

We would like to be able to change the label and/or the method to, for example, allow zone aware sharding.
If all endpoints expose a certain label, let's say `zone`, either directly or through a rewrite rules, one could use this label instead of `__address__`. This would allow more control over how endpoints are distributed amongst the available shards.

In addition to this it would be nice to switch from hash based sharding to "value based sharding" where each shard is reacting to a specific value. This could be used to, for example, assign a specific shard to a specific zone, removing the need to find out which shard is scraping which zone after hashing.

### Describe alternatives you've considered.

We're not aware of any alternative method to inject a "per-shard" rewrite rule to all metrics handled by a specific shard.

## Environment
Kubernetes Version: -
Prometheus-Operator Version: 0.72.0

**Comment by simonpasquier** [comment]
I thought we already had an issue about this but I can't find it but definitely :+1: for the idea of zone sharding.
Can you elaborate a bit more how this could work? My understanding is that to shard on zones, Prometheus needs to attach node's metadata to the targets.
Also do you foresee other target labels which would be good candidates for sharding?

**Comment by arnecls** [comment]
> Can you elaborate a bit more how this could work? My understanding is that to shard on zones, Prometheus needs to attach node's metadata to the targets.

The main issue here is that zones are cloud provider specific and not all scraping configs support the same set of labels.

My idea (for our case) is that we have re-labeling rules for different cases which generate a unified label. That would only work though if dropping happens _after_ these rules have been evaluated.

For pod based metrics the idea was to use Kyverno (or some other suitable controller) to add a label on each pod containing the zone. A rule for this case could look like this:

```yaml
  - source_labels: [__meta_kubernetes_pod_label_zone] # generated by us, same for all shards
    separator: ;
    regex: (.+)
    target_label: zone
    replacement: ${1}
    action: replace
  - source_labels: [zone] # generated by operator per shard
    separator: ;
    regex: (.*)
    modulus: 1
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: "0"
    replacement: $1
    action: keep
```

That would still be a bit fiddly, as the shards need to be placed in the correct zone based on the output of the hash.

If we have an "equality" match for the zone label, this would make the placement simpler.
However, we either need to assign a zone value to a shard (which is doable via helm, but a bit tricky) or we need to convert the zone to a number when generating the label.
Assuming we did the latter, e.g. by using kyverno, the following would work.

```yaml
  - source_labels: [__meta_kubernetes_pod_label_zone]  # generated by us, same for all shards
    separator: ;
    regex: (.+)
    target_label: zone
    replacement: ${1}
    action: replace
  - source_labels: [zone] # generated by operator per shard
    separator: ;
    regex: "0"
    replacement: $1
    action: keep
```

From the Prometheus/Prometheus agent CRD I'd expect to set the following

```yaml
shardingOn: "zone"
shardingByHash: false
```

Now for the "helm could totally generate the equality check", you could add something like this

```yaml
shardValues:
- europe-west4-a
- europe-west4-b
- europe-west4-c
```

When generating the per-shard rewrite rule, you could do something like `regex: "(shardValues[ shardNumber % len(shardValues)])"`.

**Comment by nicolastakashi** [comment]
My two cents!
I do think by default we should shard on the target, but users should be free to shard for any other label.
This will bring more flexibility to users, and they can play with what label will provide a better target distribution for their needs.

**Comment by mviswanathsai** [comment]
We would need to add this new field `ShardingOn` to the Prometheus and PrometheusAgent resources and then subsequently add this value to the store and pass that value to the 
```
 return generateAddressShardingRelabelingRulesWithSourceLabel(relabelings, shards, store.ShardingOn) 
``` 
Does that sound right?

**Comment by mviswanathsai** [comment]
I think we would need to create the new field, get a hold of it in each of the config generating functions (for ServiceMonitor, PodMonitors) and pass the custom ShardingOn value in place of `__address__`. With this, we would add corresponding validation too for the field.

What do you think? @simonpasquier

**Comment by ArthurSens** [comment]
> Open questions
> 
> * Investigate sharding implementation for additionalScrapeConfigs.

I believe we want to deprecate `additionalScrapeConfigs` after ScrapeConfig CRD became a thing, couldn't we just ignore or document that?

**Comment by mviswanathsai** [comment]
> Probes use the __param_target label. Do we need something special when sharding by a custom label?
I am not sure I follow what you are trying to say. __param_target label is used to pass the targets as parameters, and so we would not want the user to write something to that label. Are you referring to that? How is sharding on this label a problem, it would be, if we are writing to this label but that is not the case here IIUC.

**Comment by simonpasquier** [comment]
@mviswanathsai 

Probe targets are sharded differently from "regular" targets. How will it work in case of custom sharding?

https://github.com/prometheus-operator/prometheus-operator/blob/db27c619f6409460aa01886e33b08bd83edcceb2/pkg/prometheus/promcfg.go#L1628-L1630

https://github.com/prometheus-operator/prometheus-operator/blob/db27c619f6409460aa01886e33b08bd83edcceb2/pkg/prometheus/promcfg.go#L1280-L1281

**Comment by arnecls** [comment]
> If we focus on sharding by zone, there would be no guarantee that Prometheus pods scrape targets from the same zone IIUC. Is it a problem?

That's actually a good point.
We cannot set [nodeSelector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) config per shard yet.

This could be solved via something like this (based on the previous suggestion)

```yaml
spec:
  shardingStrategy:
    perShardNodeAffinity:
      label: 'topology.kubernetes.io/zone'
      values:
        - europe-west4-a
        - europe-west4-b
  # ...
```

The value of the given label could then be calucluated via 

```go
affinityValues := spec.shardingStrategy.perShardNodeAffinity.values
labelValue := affinityValues[shardNumber % len(affinityValues)]
```

**Comment by simonpasquier** [comment]
We've discussed this feature request during today's office hours and the general consensus was that we'd need a design proposal to move forward (https://prometheus-operator.dev/docs/prologue/contributing/#proposal-process).

**Comment by arnecls** [comment]
@simonpasquier if I understand that link (and the repository structure) correctly, a proposal requires a PR with a single file in `Documentation/proposals`, structured as described in the link. Correct?

As I initiated this issue, shall I write this doc? How do we collaborate on this? Is there a deadline/timeframe?

**Comment by Jakob3xD** [comment]
Hey, was there any proposal written to this issue?
I am currently running in a similar issue but only need to change the label the hash is created on.

The sharding does not work for blackbox exporter jobs as the `__address__` label is set to the blackbox exporter URL causing all targets to be on one node. With following relable_config we would need to has on the `instance` label.
```
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: ^(.+)(:?.*)$
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 3
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: "2"
    replacement: $1
    action: keep
```

**Comment by simonpasquier** [comment]
@Jakob3xD as far as I know, there hasn't been any effort on this issue. Regarding probes, the hashmod is applied to the `__param_target` label, not `__address__`. Which version of the operator are you using?

**Comment by Jakob3xD** [comment]
We are using v0.75.2. The config is copied from the pod it self. The operator added the hashmod for the `__address__` label. Due to the current limitation we build our own image where we replace the `__address__` with `__param_targets` in following line:
https://github.com/prometheus-operator/prometheus-operator/blob/35b0f457d8f705f1ac8282b4e22caa68a19c6c43/pkg/prometheus/promcfg.go#L1658

With this change it its possible to use the sharing in combination with the blackbox exporter.
Maybe PR https://github.com/prometheus-operator/prometheus-operator/pull/6446 can be re-opended?

**Comment by simonpasquier** [comment]
hmm there's something off here because Probe objects use `__param_targets` instead of `__address__`

https://github.com/prometheus-operator/prometheus-operator/blob/35b0f457d8f705f1ac8282b4e22caa68a19c6c43/pkg/prometheus/promcfg.go#L1310

You need to provide more details about your setup. Are you using ServiceMonitor or PodMonitor instead of Probe?

**Comment by Jakob3xD** [comment]
> You need to provide more details about your setup. Are you using ServiceMonitor or PodMonitor instead of Probe?

None of them. We are using additionalScrapeConfigs as we are using httpsd to get our targets. Probe does not support httpSD. The open issue for probe to add more SD looks dead to me. https://github.com/prometheus-operator/prometheus-operator/issues/6462

The scrape configs we give to the Prometheus looks like this:
```
- job_name: icmp_v4
  scrape_timeout: 15s
  scrape_interval: 30s
  metrics_path: /probe
  params:
    module: [icmp_v4]
  http_sd_configs:
    - url: 'http://httpsd.blackbox:8080/targets?job=icmp_v4'
      refresh_interval: 10s
  relabel_configs:
   - source_labels: [__address__]
     target_label: __param_target
     regex: ^(.+)(:?.*)$
     replacement: $1
   - source_labels: [__param_target]
     target_label: instance
   - target_label: __address__
     replacement: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
```
The output looks something like this:
```
- job_name: icmp_v4
  scrape_timeout: 15s
  scrape_interval: 30s
  metrics_path: /probe
  params:
    module: [icmp_v4]
  http_sd_configs:
    - url: 'http://httpsd.blackbox:8080/targets?job=icmp_v4'
      refresh_interval: 10s
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: ^(.+)(:?.*)$
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 3
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: "2"
    replacement: $1
    action: keep
```
So the hasmod won't work because the `__address__` is always the same.

**Comment by Jakob3xD** [comment]
@simonpasquier replaced the additionalScrapeConfig with the scrape config CR and the results are similar.
Input:
```
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  labels:
    scrapeconfig.selector.monitoring.example.com/blackbox: enabled
  name: http2xx
  namespace: blackbox
spec:
  jobName: http_2xx
  scrapeTimeout: 15s
  scrapeInterval: 30s
  metricsPath: /probe
  params:
    module: [http_2xx]
  httpSDConfigs:
    - url: 'http://httpsd.blackbox:8080/targets?job=http_2xx'
      refreshInterval: 10s
  relabelings:
    - sourceLabels:
        - __address__
      targetLabel: __param_target
      regex: ^(.+)(:?.*)$
      replacement: $1
    - sourceLabels: 
        - __param_target
      targetLabel: instance
    - targetLabel: __address__
      replacement: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115

```
Output:
```
- job_name: scrapeConfig/blackbox/http2xx
  honor_timestamps: true
  track_timestamps_staleness: false
  params:
    module:
    - http_2xx
  scrape_interval: 30s
  scrape_timeout: 15s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /probe
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  http_headers: null
  relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: (.*)
    target_label: __tmp_prometheus_job_name
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: job
    replacement: http_2xx
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: ^(.+)(:?.*)$
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 3
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: "0"
    replacement: $1
    action: keep
  http_sd_configs:
  - follow_redirects: true
    enable_http2: true
    http_headers: null
    refresh_interval: 10s
    url: http://httpsd.blackbox:8080/targets?job=http_2xx
```

**Comment by simonpasquier** [comment]
If you add your own hasmod rule to the ScrapeConfig relabeling, the operator should detect it and not inject its own.

**Comment by simonpasquier** [comment]
Ah I didn't think about autoscaling indeed...
In this case, I suppose that your use case might overlap with this "custom label for sharding" feature request.

**Comment by arnecls** [comment]
Sorry that this took so long.
I finally got around writing a proposal for this change.

**Comment by simonpasquier** [comment]
I've created https://github.com/prometheus-operator/prometheus-operator/milestone/13 to group all issues related to the feature. Contributions welcome!

**Comment by mviswanathsai** [comment]
I'm planning to work on this. If anyone else also wants to, great! I'm open to discussion, let's try to work together and get this done.

**Comment by PrayagS** [comment]
> If you add your own hasmod rule to the ScrapeConfig relabeling, the operator should detect it and not inject its own.

@simonpasquier Does this actually work as expected? I applied the following `ScrapeConfig` object,

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: <redacted>
  namespace: monitoring
  labels:
    prometheus: <redacted>
spec:
  kubernetesSDConfigs:
    - role: Pod
      selectors:
        - role: Pod
          label: <redacted>
      namespaces:
        names: <redacted>
  relabelings:
    - sourceLabels: [<redacted>]
      separator: ';'
      action: hashmod
      modulus: 4
      targetLabel: __tmp_hash
  scrapeInterval: 15s

```

When I see the rendered config inside one of the shard's pods, I only see the `hashmod` action. There's no corresponding `keep` action which checks the value of `__tmp_hash`.
