### ISSUE TITLE
Empty replacement is not possible when Action is Replace

### ISSUE THREAD

**Issue by tdminh** [prometheus-operator/prometheus-operator#6443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
Prometheus allows empty replacements to drop label.

It is valid to use an empty replacement in order to drop label for an existing metric.

FYI. https://stackoverflow.com/questions/73716815/conditionally-drop-labels

## Steps to Reproduce
Here is an example PodMonitor
```
- name: test
   podMetricsEndpoints:
    - interval: 5s
      scrapeTimeout: 2s
      path: /metrics
      port: monitor
      metricRelabelings:
      - sourceLabels: [__name__]
        regex: '(test)'
        targetLabel: testlabel
        replacement: ""
```

Generated PodMonitor is correct
```
podMetricsEndpoints:
  - interval: 5s
    metricRelabelings:
    - action: replace
      regex: (test)
      replacement: ""
      sourceLabels:
      - __name__
      targetLabel: testlabel
    path: /metrics
    port: monitor
    scrapeTimeout: 2s
```

## Expected Result
Generated prometheus.yaml.gz should be
```
metric_relabel_configs:
  - source_labels:
    - __name__
    target_label: testlabel
    regex: (test)
    replacement: ''
    action: replace
```

## Actual Result
Generated prometheus.yaml.gz is not correct
```
metric_relabel_configs:
  - source_labels:
    - __name__
    target_label: testlabel
    regex: (test)
    action: replace
```

### Prometheus Operator Version

```shell
Name:                   kube-prometheus-stack-operator
Namespace:              monitoring
CreationTimestamp:      Sun, 20 Mar 2022 13:27:26 +0700
Labels:                 app=kube-prometheus-stack-operator
                        app.kubernetes.io/instance=kube-prometheus-stack
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/part-of=kube-prometheus-stack
                        app.kubernetes.io/version=55.11.0
                        chart=kube-prometheus-stack-55.11.0
                        heritage=Helm
                        release=kube-prometheus-stack
Annotations:            deployment.kubernetes.io/revision: 48
                        meta.helm.sh/release-name: kube-prometheus-stack
                        meta.helm.sh/release-namespace: monitoring
Selector:               app=kube-prometheus-stack-operator,release=kube-prometheus-stack
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=kube-prometheus-stack-operator
                    app.kubernetes.io/instance=kube-prometheus-stack
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/part-of=kube-prometheus-stack
                    app.kubernetes.io/version=55.11.0
                    chart=kube-prometheus-stack-55.11.0
                    heritage=Helm
                    release=kube-prometheus-stack
  Annotations:      kubectl.kubernetes.io/restartedAt: 2024-03-18T11:20:38+07:00
  Service Account:  kube-prometheus-stack-operator
  Containers:
   kube-prometheus-stack:
    Image:      quay.io/prometheus-operator/prometheus-operator:v0.70.0
    Port:       10250/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kube-prometheus-stack-kubelet
      --localhost=127.0.0.1
      --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.70.0
      --config-reloader-cpu-request=0
      --config-reloader-cpu-limit=0
      --config-reloader-memory-request=0
      --config-reloader-memory-limit=0
      --thanos-default-base-image=quay.io/thanos/thanos:v0.33.0
      --secret-field-selector=type!=kubernetes.io/dockercfg,type!=kubernetes.io/service-account-token,type!=helm.sh/release.v1
      --web.enable-tls=true
      --web.cert-file=/cert/cert
      --web.key-file=/cert/key
      --web.listen-address=:10250
      --web.tls-min-version=VersionTLS13
    Environment:
      GOGC:  30
    Mounts:
      /cert from tls-secret (ro)
  Volumes:
   tls-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-prometheus-stack-admission
    Optional:    false
```
```


### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2023-01-18T15:58:16Z"
  compiler: gc
  gitCommit: 8f94681cd294aa8cfd3407b8191f6c70214973a4
  gitTreeState: clean
  gitVersion: v1.26.1
  goVersion: go1.19.5
  major: "1"
  minor: "26"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2023-11-03T12:18:23Z"
  compiler: gc
  gitCommit: 55a7e688f9220adca1c99b7903953911dd38b771
  gitTreeState: clean
  gitVersion: v1.27.7
  goVersion: go1.20.10
  major: "1"
  minor: "27"
  platform: linux/amd64
```

### Kubernetes Cluster Type

AKS

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### prometheus-operator log output

```shell
N/A (no error)
```
