### ISSUE TITLE
Probe CRD Add all SD variants

### ISSUE THREAD

**Issue by chipzzz** [prometheus-operator/prometheus-operator#6462]
### Component(s)

**Probe CRD**

### What is missing? Please describe.

Probe CRD is missing all regular SD variants that are available in the regular scrape configuration. Users that utilize blackbox exporter and probe targets using `http_sd_config` or `consul_sd_config` and others cannot use probe CRD in lieu of the scrape_config.

It was mentioned here that this would be covered by scrapeConfig CRD, however, I believe that still only works for external kubernetes clusters and not external endpoints.

https://github.com/prometheus-operator/prometheus-operator/issues/5269

### Describe alternatives you've considered.

Custom SD that provides list to configmap - defeats the purpose.

## Environment
Kubernetes Version: latest
Prometheus-Operator Version:
latest

**Comment by slashpai** [comment]
ScrapeConfig should work for the scenario, have you tried it?

**Comment by slashpai** [comment]
ok I understand now. AFAIK we didn't have any plans to add more SD's too probe as we are developing more on ScrapeConfig.

May be @simonpasquier will have more context why other sd's were not supported in Probe.

**Comment by simonpasquier** [comment]
Now that we have the ScrapeConfig CRD, I don't think that we need/want to add more service discoveries to Probes.

**Comment by simonpasquier** [comment]
My point is that you can use the ScrapeConfig CRD to scrape targets such as blackbox exporter.

**Comment by simonpasquier** [comment]
The point we're trying to make is that It should be possible to use the ScrapeConfig CRD to collect metrics from blackbox_exporter (as well as other probers like snmp_exporter).

**Comment by Jakob3xD** [comment]
Example for blackbox icmp.
```
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  labels:
    scrapeconfig.selector.monitoring.example.com/blackbox: enabled
  name: icmpv4
  namespace: blackbox
spec:
  jobName: icmp_v4
  scrapeTimeout: 15s
  scrapeInterval: 30s
  metricsPath: /probe
  params:
    module: [icmp_v4]
  httpSDConfigs:
    - url: 'http://httpsd.blackbox:8080/targets?job=icmp_v4'
      refreshInterval: 10s
  relabelings:
    - sourceLabels:
        - __address__
      targetLabel: __param_target
      regex: ^(.+)(:?.*)$
      replacement: $1
    - sourceLabels: 
        - __param_target
      targetLabel: instance
    - targetLabel: __address__
      replacement: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115

```
