### ISSUE TITLE
Own Service Monitor isn't working

### ISSUE THREAD

**Issue by LukasMenninger** [prometheus-operator/prometheus-operator#6511]
## Description
I Have created a serviceMonitor to scrape metrics from my own service. I can find it in the configuration and service discovery of prometheus but there are no targets for my servicemonitor

## Expected Result
Scraping my own metrics from my service

## Actual Result
No targets discovered, TargetLabels for servicemonitor are dropped

### Prometheus Operator Version

```shell
Name:                   kube-prometheus-stack-operator
Namespace:              monitoring
CreationTimestamp:      Mon, 15 Apr 2024 08:55:50 +0200
Labels:                 app=kube-prometheus-stack-operator
                        app.kubernetes.io/component=prometheus-operator
                        app.kubernetes.io/instance=kube-prometheus-stack
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=kube-prometheus-stack-prometheus-operator
                        app.kubernetes.io/part-of=kube-prometheus-stack
                        app.kubernetes.io/version=58.1.1
                        chart=kube-prometheus-stack-58.1.1
                        heritage=Helm
                        release=kube-prometheus-stack
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: kube-prometheus-stack
                        meta.helm.sh/release-namespace: monitoring
Selector:               app=kube-prometheus-stack-operator,release=kube-prometheus-stack
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=kube-prometheus-stack-operator
                    app.kubernetes.io/component=prometheus-operator
                    app.kubernetes.io/instance=kube-prometheus-stack
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=kube-prometheus-stack-prometheus-operator
                    app.kubernetes.io/part-of=kube-prometheus-stack
                    app.kubernetes.io/version=58.1.1
                    chart=kube-prometheus-stack-58.1.1
                    heritage=Helm
                    release=kube-prometheus-stack
  Service Account:  kube-prometheus-stack-operator
  Containers:
   kube-prometheus-stack:
    Image:      quay.io/prometheus-operator/prometheus-operator:v0.73.1
    Port:       10250/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kube-prometheus-stack-kubelet
      --localhost=127.0.0.1
      --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.73.1
      --config-reloader-cpu-request=0
      --config-reloader-cpu-limit=0
      --config-reloader-memory-request=0
      --config-reloader-memory-limit=0
      --thanos-default-base-image=quay.io/thanos/thanos:v0.34.1
      --secret-field-selector=type!=kubernetes.io/dockercfg,type!=kubernetes.io/service-account-token,type!=helm.sh/release.v1
      --web.enable-tls=true
      --web.cert-file=/cert/cert
      --web.key-file=/cert/key
      --web.listen-address=:10250
      --web.tls-min-version=VersionTLS13
    Environment:
      GOGC:  30
    Mounts:
      /cert from tls-secret (ro)
  Volumes:
   tls-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-prometheus-stack-admission
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   kube-prometheus-stack-operator-85f86ff6f6 (1/1 replicas created)
Events:          <none>
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-02-14T10:40:49Z"
  compiler: gc
  gitCommit: 4b8e819355d791d96b7e9d9efe4cbafae2311c88
  gitTreeState: clean
  gitVersion: v1.29.2
  goVersion: go1.21.7
  major: "1"
  minor: "29"
  platform: windows/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2023-10-18T11:33:18Z"
  compiler: gc
  gitCommit: a8a1abc25cad87333840cd7d54be2efaf31a3177
  gitTreeState: clean
  gitVersion: v1.28.3
  goVersion: go1.20.10
  major: "1"
  minor: "28"
  platform: linux/amd64
```

### Kubernetes Cluster Type

minikube

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-server
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-server
      #release: kube-prometheus-stack 
  template:
    metadata:
      name: Flask-Pod
      namespace: monitoring
      labels:
        app: flask-server
        release: kube-prometheus-stack 
    spec:
      containers:
        - name: flask-container
          image: lukasm2604/my_repo:kub_flask_server
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: flask-server
  namespace: monitoring
  labels:
    app: flask-server
    release: kube-prometheus-stack
  annotations:
    prometheus.io/scrape: "true"    
    prometheus.io/path: /metrics
    prometheus.io/port: "5000"
spec:
  selector:
    app: flask-server
    release: kube-prometheus-stack
    namespace: monitoring
  ports:
    - protocol: TCP
      name: metricport
      port: 5000
      targetPort: 5000



---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-server-monitor
  namespace: monitoring
  labels:
    app: flask-server
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: flask-server
      release: kube-prometheus-stack

  endpoints:
  - port: metricport
    path: /metrics
    interval: 16s
  namespaceSelector: 
    any: true
```

### prometheus-operator log output

```shell
ts=2024-04-15T07:54:27.194Z caller=main.go:617 level=info msg="Starting Prometheus Server" mode=server version="(version=2.51.1, branch=HEAD, revision=855b5ac4b80956874eb1790a04c92327f2f99e38)"
ts=2024-04-15T07:54:27.194Z caller=main.go:622 level=info build_context="(go=go1.22.1, platform=linux/amd64, user=root@d3785d7783f2, date=20240328-09:27:30, tags=netgo,builtinassets,stringlabels)"
ts=2024-04-15T07:54:27.194Z caller=main.go:623 level=info host_details="(Linux 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 prometheus-kube-prometheus-stack-prometheus-0 )"        
ts=2024-04-15T07:54:27.194Z caller=main.go:624 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2024-04-15T07:54:27.194Z caller=main.go:625 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2024-04-15T07:54:27.199Z caller=web.go:568 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2024-04-15T07:54:27.199Z caller=main.go:1129 level=info msg="Starting TSDB ..."
ts=2024-04-15T07:54:27.206Z caller=tls_config.go:313 level=info component=web msg="Listening on" address=[::]:9090
ts=2024-04-15T07:54:27.206Z caller=tls_config.go:352 level=info component=web msg="TLS is disabled." http2=false address=[::]:9090
ts=2024-04-15T07:54:27.210Z caller=head.go:616 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2024-04-15T07:54:27.210Z caller=head.go:698 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=2.4µs
ts=2024-04-15T07:54:27.210Z caller=head.go:706 level=info component=tsdb msg="Replaying WAL, this may take a while"
ts=2024-04-15T07:54:27.210Z caller=head.go:778 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
ts=2024-04-15T07:54:27.210Z caller=head.go:815 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=31.703µs wal_replay_duration=330.431µs wbl_replay_duration=100ns total_replay_duration=384.436µs
ts=2024-04-15T07:54:27.216Z caller=main.go:1150 level=info fs_type=EXT4_SUPER_MAGIC
ts=2024-04-15T07:54:27.216Z caller=main.go:1153 level=info msg="TSDB started"
ts=2024-04-15T07:54:27.216Z caller=main.go:1335 level=info msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
ts=2024-04-15T07:54:27.225Z caller=kubernetes.go:331 level=info component="discovery manager scrape" discovery=kubernetes config=serviceMonitor/monitoring/kube-prometheus-stack-coredns/0 msg="Using pod service account via in-cluster config"
ts=2024-04-15T07:54:27.226Z caller=kubernetes.go:331 level=info component="discovery manager scrape" discovery=kubernetes config=serviceMonitor/monitoring/kube-prometheus-stack-prometheus/1 msg="Using pod service account via in-cluster config"
ts=2024-04-15T07:54:27.226Z caller=kubernetes.go:331 level=info component="discovery manager scrape" discovery=kubernetes config=serviceMonitor/monitoring/flask-server-monitor/0 msg="Using pod service account via in-cluster config"
ts=2024-04-15T07:54:27.227Z caller=kubernetes.go:331 level=info component="discovery manager scrape" discovery=kubernetes config=serviceMonitor/monitoring/kube-prometheus-stack-apiserver/0 msg="Using pod service account via in-cluster config"
ts=2024-04-15T07:54:27.227Z caller=kubernetes.go:331 level=info component="discovery manager notify" discovery=kubernetes config=config-0 msg="Using pod service account via in-cluster config"
ts=2024-04-15T07:54:27.953Z caller=main.go:1372 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=736.967919ms db_storage=1.9µs remote_storage=1.6µs web_handler=300ns query_engine=1.6µs scrape=278.326µs scrape_sd=1.735762ms notify=27.502µs notify_sd=190.018µs rules=725.711471ms tracing=68.907µs
ts=2024-04-15T07:54:27.953Z caller=main.go:1114 level=info msg="Server is ready to receive web requests."
ts=2024-04-15T07:54:27.953Z caller=manager.go:163 level=info component="rule manager" msg="Starting rule manager..."
ts=2024-04-15T07:54:28.014Z caller=main.go:1335 level=info msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
ts=2024-04-15T07:54:28.020Z caller=kubernetes.go:331 level=info component="discovery manager scrape" discovery=kubernetes config=serviceMonitor/monitoring/flask-server/0 msg="Using pod service account via in-cluster config"
ts=2024-04-15T07:54:28.020Z caller=kubernetes.go:331 level=info component="discovery manager scrape" discovery=kubernetes config=serviceMonitor/monitoring/kube-prometheus-stack-apiserver/0 msg="Using pod service account via in-cluster config"
ts=2024-04-15T07:54:28.020Z caller=kubernetes.go:331 level=info component="discovery manager scrape" discovery=kubernetes config=serviceMonitor/monitoring/kube-prometheus-stack-kube-controller-manager/0 msg="Using pod service account via in-cluster config"
ts=2024-04-15T07:54:28.022Z caller=kubernetes.go:331 level=info component="discovery manager scrape" discovery=kubernetes config=serviceMonitor/monitoring/flask-server-monitor/0 msg="Using pod service account via in-cluster config"
ts=2024-04-15T07:54:28.022Z caller=kubernetes.go:331 level=info component="discovery manager notify" discovery=kubernetes config=config-0 msg="Using pod service account via in-cluster config"
ts=2024-04-15T07:54:28.163Z caller=main.go:1372 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=149.052278ms db_storage=2.3µs remote_storage=2.201µs web_handler=500ns query_engine=1.3µs scrape=129.812µs scrape_sd=2.742255ms notify=13.502µs notify_sd=824.276µs rules=139.659104ms tracing=7.201µs
ts=2024-04-15T07:58:38.072Z caller=group.go:555 level=warn name=node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile index=0 component="rule manager" file=/etc/prometheus/rules/prometheus-kube-prometheus-stack-prometheus-rulefiles-0/monitoring-kube-prometheus-stack-kubelet.rules-ac5b364d-e2da-43a4-b44e-a7ecee0aea6f.yaml group=kubelet.rules msg="Error on ingesting results from rule evaluation with different value but same timestamp" numDropped=1
ts=2024-04-15T07:58:38.276Z caller=group.go:555 level=warn name=node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile index=1 component="rule manager" file=/etc/prometheus/rules/prometheus-kube-prometheus-stack-prometheus-rulefiles-0/monitoring-kube-prometheus-stack-kubelet.rules-ac5b364d-e2da-43a4-b44e-a7ecee0aea6f.yaml group=kubelet.rules msg="Error on ingesting results from rule evaluation with different value but same timestamp" numDropped=1
ts=2024-04-15T07:58:38.282Z caller=group.go:555 level=warn name=node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile index=2 component="rule manager" file=/etc/prometheus/rules/prometheus-kube-prometheus-stack-prometheus-rulefiles-0/monitoring-kube-prometheus-stack-kubelet.rules-ac5b364d-e2da-43a4-b44e-a7ecee0aea6f.yaml group=kubelet.rules msg="Error on ingesting results from rule evaluation with different value but same timestamp" numDropped=1
```

### Anything else?
![image](https://github.com/prometheus-operator/prometheus-operator/assets/118532611/30708053-38cf-4a92-926b-84f21a73e17b)

### Prometheus Configuration-File
scrape_configs:
    - job_name: serviceMonitor/monitoring/flask-server-monitor/0
      honor_timestamps: true
      track_timestamps_staleness: false
      scrape_interval: 16s
      scrape_timeout: 10s
      scrape_protocols:
      - OpenMetricsText1.0.0
      - OpenMetricsText0.0.1
      - PrometheusText0.0.4
      metrics_path: /metrics
      scheme: http
      enable_compression: true
      follow_redirects: true
      enable_http2: true
      relabel_configs:
      - source_labels: [job]
        separator: ;
        regex: (.*)
        target_label: __tmp_prometheus_job_name
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_label_app, __meta_kubernetes_service_labelpresent_app]
        separator: ;
        regex: (flask-server);true
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_service_label_release, __meta_kubernetes_service_labelpresent_release]
        separator: ;
        regex: (kube-prometheus-stack);true
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        separator: ;
        regex: metricport
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
        separator: ;
        regex: Node;(.*)
        target_label: node
        replacement: ${1}
        action: replace
      - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
        separator: ;
        regex: Pod;(.*)
        target_label: pod
        replacement: ${1}
        action: replace
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_container_name]
        separator: ;
        regex: (.*)
        target_label: container
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_phase]
        separator: ;
        regex: (Failed|Succeeded)
        replacement: $1
        action: drop
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: job
        replacement: ${1}
        action: replace
      - separator: ;
        regex: (.*)
        target_label: endpoint
        replacement: metricport
        action: replace
      - source_labels: [__address__]
        separator: ;
        regex: (.*)
        modulus: 1
        target_label: __tmp_hash
        replacement: $1
        action: hashmod
      - source_labels: [__tmp_hash]
        separator: ;
        regex: "0"
        replacement: $1
        action: keep
      kubernetes_sd_configs:
      - role: endpoints
        kubeconfig_file: ""
        follow_redirects: true
        enable_http2: true
    _No response_
