### ISSUE TITLE
Support scraping kubelet metrics

### ISSUE THREAD

**Issue by dploeger** [prometheus-operator/prometheus-operator#6590]
### Component(s)

Prometheus

### What is missing? Please describe.

We tried to implement kubelet scraping to get metrics for volumes. These metrics are requested using this scrape config:

```yaml
      - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        job_name: kubernetes-nodes
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - replacement: kubernetes.default.svc:443
          target_label: __address__
        - regex: (.+)
          replacement: /api/v1/nodes/$1/proxy/metrics
          source_labels:
          - __meta_kubernetes_node_name
          target_label: __metrics_path__
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
```

This requires the prometheus service account to have these additional rights:

```
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  verbs:
  - get
```

### Describe alternatives you've considered.

We implemented the ClusterRole, ClusterRoleBinding and the additional scrape config using the addtionalScrapeConfig parameter, but this is something so vital, it should be directly supported by the operator (maybe toggable with a switch)

## Environment
Kubernetes Version: Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.11+vmware.1-fips.1", GitCommit:"5ee2bbaec1d784e90139d89e8795921629453218", GitTreeState:"clean", BuildDate:"2024-02-19T20:56:33Z", GoVersion:"go1.21.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
Prometheus-Operator Version: 0.73.2
