### ISSUE TITLE
Invalid AlertmanagerConfig passes validation and results in 'group_interval cannot be zero' errors

### ISSUE THREAD

**Issue by leonardo-zorzi** [prometheus-operator/prometheus-operator#6594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
AlertmanagerConfig CR with group_interval set to 0 passes validation and results in errors on the alertmanager instances itself.
`ts=2024-05-15T12:04:48.725Z caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config_out/alertmanager.env.yaml err="group_interval cannot be zero"`

## Steps to Reproduce
```yaml
spec:
  route:
      groupBy: [ "..." ]
      groupWait: 0s
      groupInterval: 0s
      repeatInterval: 24h
      receiver: "a_receiver"
      routes:
        - matchers:
            - name: "alertname"
              value: "InfoInhibitor"
          receiver: "null"
```
I run the Operator on v0.67.1 (unfortunately the [latest kube-prometheus](https://github.com/prometheus-operator/kube-prometheus/blob/v0.13.0/jsonnet/kube-prometheus/jsonnetfile.json#L39)) but the current master CRD seems to references still the same [regex](https://github.com/prometheus-operator/prometheus-operator/blob/48e98584b57b72a4a10951414b1c0b3acf043426/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml#L5786).

## Expected Result
CR fails validation.

## Actual Result
CR passed validation and gets added to the final config file.

### Prometheus Operator Version

```shell
v0.67.1
```

### Kubernetes Version

```yaml
1.27
```

### Kubernetes Cluster Type

GKE

### How did you deploy Prometheus-Operator?

Other (please comment)

### Manifests

```yaml
kube-prometheus jsonnet
```

### prometheus-operator log output

```shell
`ts=2024-05-15T12:04:48.725Z caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config_out/alertmanager.env.yaml err="group_interval cannot be zero"`
```
