### ISSUE TITLE
Add `scale` subresource to `Alertmanger` CRD to support VPA

### ISSUE THREAD

**Issue by fullykubed** [prometheus-operator/prometheus-operator#6609]
### Component(s)

AlertManager

### What is missing? Please describe.

I'd like to use the vertical pod autoscaler (VPA) to scale the Alertmanager pods.

While this works with Prometheus CRs, the Alertmanager CRs are missing the scale subresource which is [required for the VPA](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md#how-can-i-apply-vpa-to-my-custom-resource).

On Prometheus:

```yaml
  Subresources:
    Scale:
      Label Selector Path:   .status.selector
      Spec Replicas Path:    .spec.shards
      Status Replicas Path:  .status.shards
    Status:
```

On Alertmanager:

```yaml
  Subresources:
    Status:
```

### Describe alternatives you've considered.

None

### Environment Information.

Deployed with the prometheus stack Helm chart: `58.5.3`
