### ISSUE TITLE
bearerTokenFile deprecated - unclear what the replacement is

### ISSUE THREAD

**Issue by sebhoss** [prometheus-operator/prometheus-operator#6719]
## Description

We are currently using a ServiceMonitor to scrape metrics from kubelet and use `bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token` in its configuration. `bearerTokenFile` is now marked as deprecated but I'm unsure how to use a non-deprecated version of a ServiceMonitor to scrape kubelet. 

## Steps to Reproduce

Create ServiceMonitor that looks similar to this:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet
  namespace: kube-system
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: https-metrics
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
      app.kubernetes.io/managed-by: prometheus-operator
```

Get your favorite analysis tool/IDE to tell you that `bearerTokenFile` is deprecated.

## Expected Result

Be able to define a ServiceMonitor using non-deprecated fields.

## Actual Result

Documentation is unclear to me. https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#authorization lists a field called `credentialsFile` which sounded promising but that is actually not part of the CRD (anymore?).

https://github.com/prometheus-operator/prometheus-operator/issues/6493#issuecomment-2046701958 mentions that we should use the new `scrapeClasses` feature but those are marked as experimental in https://prometheus-operator.dev/docs/operator/api/ and I still could not find an example on how to use them. The charts at https://github.com/prometheus-community/helm-charts seem to be relying on `bearerTokenFile` as well for now.

### Prometheus Operator Version

```shell
0.75.0
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-06-11T20:29:44Z"
  compiler: gc
  gitCommit: 39683505b630ff2121012f3c5b16215a1449d5ed
  gitTreeState: clean
  gitVersion: v1.30.2
  goVersion: go1.22.4
  major: "1"
  minor: "30"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-04-16T15:00:26Z"
  compiler: gc
  gitCommit: 55019c83b0fd51ef4ced8c29eec2c4847f896e74
  gitTreeState: clean
  gitVersion: v1.29.4
  goVersion: go1.21.9
  major: "1"
  minor: "29"
  platform: linux/amd64
```

### Kubernetes Cluster Type

kubeadm

### How did you deploy Prometheus-Operator?

yaml manifests

### prometheus-operator log output

```shell
no logs are relevant for this issue
```
