### ISSUE TITLE
Lack of debugging playbook for multi-cluster federation

### ISSUE THREAD

**Issue by ensonic** [prometheus-operator/prometheus-operator#6724]
## Description
I have 2 GKE clusters (main, worker) in a GCP projects. Both run the same version of the prometheus operator (prometheus 2.49.1). On main I also have grafana dashboards enabled. I would like to federate selected worker metrics into the main cluster for dashboarding.

## Steps to Reproduce

on worker GKE cluster
```yaml
apiVersion: v1
kind: Service
metadata:
  namespace: app-prometheus
  name: kube-prometheus-exported
  annotations:
    # Only expose this to the GCP project
    networking.gke.io/load-balancer-type: "Internal"
spec:
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: kube-prometheus
  type: LoadBalancer
```
on main GKE cluster
```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: app-worker-cluster
  labels:
    app: worker-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: worker-cluster-metrics
  namespace: app-worker-cluster
  labels:
    app: worker-cluster
    cluster: worker
spec:
  type: ExternalName
  # needs to be replaced with an actual ip address
  externalName: KUBE_PROMETHEUS_EXPORTED_IP
  ports:
    - name: http-metrics
      port: 9090
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: worker-cluster
  namespace: app-worker-cluster
  labels:
    app: worker-cluster
    cluster: worker
subsets:
- addresses:
  # needs to be replaced with an actual ip address
  - ip: KUBE_PROMETHEUS_EXPORTED_IP
  ports:
  - name: http-metrics
    port: 9090
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-cluster-metrics
  namespace: app-worker-cluster
  labels:
    prometheus: kube-prometheus
spec:
  endpoints:
    - port: http-metrics
      path: /federate
      interval: 30s
      params:
        'match[]':
        # Identified via Prometheus query: topk(10, count by (__name__)({__name__=~".+"}))
        - '{__name__=~".+", __name__!~"apiserver_request_duration_seconds_bucket|apiserver_request_slo_duration_seconds_bucket|etcd_request_duration_seconds_bucket|apiserver_response_sizes_bucket"}'
      honorLabels: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: instance  # These are the labels below on the federation service
  targetLabels:
    - cluster
  selector:
    matchLabels:
      app: worker-cluster
```

Verify worker:
```bash
> kubectl --context=gke_WORKER run curl --rm -it --image=alpine/curl -- -fsSL -G --data-urlencode 'match[]={__name__=~".+"}' worker-cluster-metrics.app-worker-cluster.svc.cluster.local:9090/federate | grep pod_cpu_usage
# TYPE pod_cpu_usage untyped
pod_cpu_usage{endpoint="http-metrics",...}
```

## Expected Result
See metric also on main:
```bash
kubectl --context=gke_MAIN -n app-prometheus port-forward svc/kube-prometheus 9753:9090
```
```bash
curl -s -G --data-urlencode 'match[]={__name__=~"pod_cpu_usage"}' http://localhost:9753/federate
```

## Actual Result
No output. If I run:
```
curl -s -G --data-urlencode 'match[]={__name__=~".+"}' http://localhost:9753/federate
```

In the prometheus webui on WORKER the metrics can be queries and plotted.
In the prometheus webui on MAIN, I see the service-monitor, but no target below. I can see the config on (/config). I've been reading the docs (e.g.  https://prometheus.io/docs/prometheus/latest/federation/#configuring-federation, https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/troubleshooting.md#troubleshooting-servicemonitor-changes). I cheked the logs of my deployments. Sadly I am stuck here.

### Prometheus Operator Version

```shell
app.kubernetes.io/version: 56.6.2
chart: kube-prometheus-stack-56.6.2
```

### Kubernetes Version

```yaml
1.27.13-gke.1070000
```

### Kubernetes Cluster Type

GKE

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### prometheus-operator log output

```shell
<too much, provided as a followup depending on what it needed>
```
