### ISSUE TITLE
Support envfrom in alertmanager CRD

### ISSUE THREAD

**Issue by davhdavh** [prometheus-operator/prometheus-operator#6805]
### Component(s)

AlertManager, AlertManagerConfig

### What is missing? Please describe.

Problem:

Using secrets in alertmanager config is extremely restricted.

For example, lets say you used terraform to provision a new email account, and stored that in a secret. That secret now contains the FROM, the HOST, the USERNAME and the PASSWORD.

Yet, Alertmanager config only supports fetching the password from a file or a secret.

Another default way to handle secrets is to inject them as environment variables, and indeed Alertmanager already pipes the config through `prometheus-config-reloader` which does env variable substitutions.

However, there is no way to actually provide the list of secrets that the `prometheus-config-reloader` uses.

Solution:

Add `configEnvFrom` which gets mapped to `envFrom` in the  `prometheus-config-reloader` pod.
https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables

existing env for `prometheus-config-reloader` pod is set here:

https://github.com/prometheus-operator/prometheus-operator/blob/377b4876ad5f883e7243e9aebc42c3b959b35cbb/pkg/operator/config_reloader.go#L299

### Environment Information.

NA

**Comment by simonpasquier** [comment]
It should already be possible using [strategic merge patch](https://prometheus-operator.dev/docs/platform/strategic-merge-patch/). If you make it work, it could be a nice example to be added to the docs :)

**Comment by davhdavh** [comment]
actually, yes that works (almost) perfectly...

```yaml
kube-prometheus-stack:
  alertmanager:
    config:
      global:
        smtp_from: grafana@grafana-dev.somewhere.com
        smtp_smarthost: $(AWS_SMTP_SERVER):587
        smtp_auth_username: $(AWS_ACCESS_KEY_ID)
        smtp_auth_password: $(AWS_SECRET_ACCESS_KEY)
        smtp_require_tls: true
    alertmanagerSpec:
      containers:
      - name: config-reloader
        envFrom:
        - secretRef:
            name: aws-mail
      initContainers:
      - name: init-config-reloader
        envFrom:
        - secretRef:
            name: aws-mail
```

Notice the :587 in the host is required, otherwise you get this:

```
level=error ts=2024-08-07T09:11:45.377238347Z caller=klog.go:126 component=k8s_client_runtime func=ErrorDepth msg="sync \"monitoring/kube-prometheus-stack-alertmanager\" failed: provision alertmanager configuration: failed to initialize from secret: address $(AWS_SMTP_SERVER): missing port in address"
```

IE, there is some validation running BEFORE the env-subst takes place.
