### ISSUE TITLE
Usage of a dash (-) in a label-name of the LabelSelector in a ServiceMonitor causes services not to be found

### ISSUE THREAD

**Issue by unknownbanana** [prometheus-operator/prometheus-operator#6816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

In the Getting Started documentation there is [an example](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md#deploying-a-sample-application) of a ServiceMonitor.

Adjusting the label-name of this example to one that contains a dash, leads to services not being found without any kind of exception/error. Eventough the usage of a label-name with a dash is [legal syntax](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set).

## Steps to Reproduce

- Follow the getting started guide, but use `my-app` as the label-name

## Expected Result

I would expect the services matching that label to be found and metrics to be made available.

## Actual Result

No services are found and no metrics are made available.

### Prometheus Operator Version

```shell
Cannot currently provide this, Prometheus Operator is wrapped by the https://github.com/openshift/cluster-monitoring-operator and I do not have access to the version number. Assuming that it is at least present in the latest version of the Operator, will post the actual version number once I've heard back from our Platform team.
```

### Kubernetes Version

```yaml
v1.27.15
```

### Kubernetes Cluster Type

OpenShift

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### Manifests

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      my-app: example-app
  endpoints:
  - port: web
```

### prometheus-operator log output

```shell
Not available to me.
```

**Comment by simonpasquier** [comment]
I'd be surprised that we have a bug here. You'd need to share the definition of the service and ideally the generated Prometheus configuration.

**Comment by unknownbanana** [comment]
@simonpasquier I was surprised as well when this occurred. I cannot share the "actual" Service and Prometheus configuration. Because the actual Service contains markers pointing to the client I work for, which I prefer not to disclose, and I do not have the Prometheus configuration available to me.

However, I can provide you with a similar minimal reproduction of the ServiceMonitor + Service. The Service LabelSelector selects a Quarkus deployment with the micrometer extention installed. Hence the ServiceMonitor points to `/q/metrics`.

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
spec:
  endpoints:
    - interval: 30s
      targetPort: tcp-8080
      path: /q/metrics
      scheme: http
  selector:
    matchLabels:
      my-metrics: 'enabled'

kind: Service
apiVersion: v1
metadata:
  name: service-name
  labels:
    app: service-name
    my-metrics: 'enabled'
spec:
  ports:
    - name: tcp-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: service-name
```

**Comment by simonpasquier** [comment]
You have a typo

````
  endpoints:
    - interval: 30s
      port: tcp-8080
      path: /q/metrics
      scheme: http
````
