### ISSUE TITLE
Changing severity of default rules via additionalAlertRelabelConfigs does not seem to work

### ISSUE THREAD

**Issue by sebschlue** [prometheus-operator/prometheus-operator#6857]
## Description

I have tried to change severity of a default rule via the following helm chart values:

```
prometheus:
  prometheusSpec:
    additionalAlertRelabelConfigs:
    - source_labels: [__name__]
      regex: 'KubePodCrashLooping'
      action: replace
      target_label: severity
      replacement: critical
```

As far as helm chart is concerned, this seems to work because in Prometheus-Pod I can now see

```
alerting:
  alert_relabel_configs:
  - action: labeldrop
    regex: prometheus_replica
  - action: replace
    regex: KubePodCrashLooping
    replacement: critical
    source_labels:
    - __name__
    target_label: severity
```
in /etc/prometheus/config_out/prometheus.env.yaml

But it does not seem t actually change the severity of the rule from warning to critical.

## Steps to Reproduce

See description. I have added section with additionalAlertRelabelConfigs to helm chart values.

## Expected Result

The severity of the specified rule should change.

## Actual Result

The severity of the specified rule does not change.

### Prometheus Operator Version

```shell
quay.io/prometheus/prometheus:v2.48.0
```

### Kubernetes Version

```yaml
EKS 1.28.8
```

### Kubernetes Cluster Type

EKS

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml
Please see description. I have added prometheus.prometheusSpec.additionalAlertRelabelConfigs to helm chart values. Apart from that, config does not contain anything special.
```

### prometheus-operator log output

```shell
Not errors or warnings.


level=info ts=2024-08-20T08:02:52.344281337Z caller=reloader.go:376 msg="Reload triggered" cfg_in=/etc/prometheus/config/prometheus.yaml.gz cfg_out=/etc/prometheus/config_out/prometheus.env.yaml watched_dirs=/etc/prometheus/rules/prometheus-kube-prometheus-kube-prome-prometheus-rulefiles-0
```
```


### Anything else?

_No response_
