### ISSUE TITLE
AlertmanagerConfig: Matching on `namespace` OR `exported_namespace`?

### ISSUE THREAD

**Issue by m3adow** [prometheus-operator/prometheus-operator#6870]
## Description

I'm currently working on bringing our Google Managed Prometheus (GMP) alerts into our alertmanager instance which is deployed with Prometheus Operator. GMP uses the `exported_namespace` label for the identification of the correct namespace to alert for. At the same time, we have other metrics which still use the `namespace` label for that.

Therefore, I need to find a way to match either of those labels in each `AlertmanagerConfig` our teams deploy in their namespaces. Preferrably with only one `AlertmanagerConfig` CRD.  
If I understood correctly, it's not possible to OR the `spec.route.matchers`. Additionally, a `namespace` matcher is automatically added to each `AlertmanagerConfig` as long as  the Alertmanager instance is configured with `alertmanagerConfigMatcherStrategy.type: OnNamespace` which is the default as well. All my efforts until now either didn't work or had some very annoying side effects.

My best approach right now is to:

* Change `alertmanagerConfigMatcherStrategy.type` to `None`
* Configure each `AlertmanagerConfig` CRD to use `namespace != ""` as `spec.route.matchers` item to prevent Watchdog alerts from matching
* Configure two child routes:
  * `namespace = "mynamespace"`
  * `exported_namespace = "mynamespace"`
*  Each of those child routes has the real receiver configured

The problem is, that the `.spec.route.receiver` is triggered for every alert matching, which is a lot of course. Although the CRD description makes it sound like `.spec.route.receiver` could be omitted, it's not possible. Therefore, I have to configure a "null" receiver for each `AlertmanagerConfig` CRD which is still shown in the Alertmanager UI cluttering the Overview with useless information

Is there any good way to achive what I want?

### Prometheus Operator Version

```shell
v0.76.0
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-07-16T23:54:40Z"
  compiler: gc
  gitCommit: 6fc0a69044f1ac4c13841ec4391224a2df241460
  gitTreeState: clean
  gitVersion: v1.30.3
  goVersion: go1.22.5
  major: "1"
  minor: "30"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-07-19T09:16:41Z"
  compiler: gc
  gitCommit: 0858698e672612745ea0150984b899843b9f0bba
  gitTreeState: clean
  gitVersion: v1.30.3-gke.1225000
  goVersion: go1.22.5 X:boringcrypto
  major: "1"
  minor: "30"
  platform: linux/amd64
```

### Kubernetes Cluster Type

GKE

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml
# My current approach
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: my-test
  namespace: my-test
spec:
  receivers:
  - name: my-test
  - name: "null"
  route:
    receiver: "null"
    matchers:
      - name: namespace
        matchType: "!="
        value: ""
    routes:
      - matchers:
        - name: exported_namespace
          matchType: "="
          value: my-test
        receiver: my-test
      - matchers:
        - name: namespace
          matchType: "="
          value: my-test
        receiver: my-test
```
