### ISSUE TITLE
Unable to add console templates with prometheus-operator

### ISSUE THREAD

**Issue by k8s-1** [prometheus-operator/prometheus-operator#6880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

I am unable to add console templates with prometheus-operator instance following advice from @simonpasquier in #2699 that using a configMap and additionalArgs should not be a problem. It looks like console-templates is already defined by the operator and this results in an apply conflict.

Suggestions to resolve (mutually exclusive):
A. allow users to configure the console-template directory flag --web.console.templates without conflict
B. allow users to add console templates as configMaps into the default console-templates path /etc/prometheus/consoles 

## Steps to Reproduce
Create a prometheus instance e.g. https://github.com/k8s-1/prometheus-simple/blob/main/prometheus-instance.yaml with console template.

## Expected Result
Prometheus instance starts and I can see a console template in <endpoint>/consoles/

## Actual Result
Prometheus instance fails to apply

### Prometheus Operator Version

```shell
app.kubernetes.io/version=0.76.0
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-07-24T07:05:46Z"
  compiler: gc
  gitCommit: 6fc0a69044f1ac4c13841ec4391224a2df241460
  gitTreeState: archive
  gitVersion: v1.30.3
  goVersion: go1.22.5
  major: "1"
  minor: "30"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-08-13T22:44:37Z"
  compiler: gc
  gitCommit: 9edcffcde5595e8a5b1a35f88c421764e575afce
  gitTreeState: clean
  gitVersion: v1.31.0
  goVersion: go1.22.5
  major: "1"
  minor: "31"
  platform: linux/amd64
```

### Kubernetes Cluster Type

kind

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### Manifests

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
---
apiVersion: v1
data:
  test.html: |
    {{ template "head" . }}

    {{ template "prom_right_table_head" }}
    {{ template "prom_right_table_tail" }}

    {{ template "prom_content_head" . }}
    <h1>TEST CONSOLE</h1>
    <p>These are example consoles for Prometheus.</p>

    <p>These consoles expect exporters to have the following job labels:</p>
    <table class="table table-sm table-striped table-bordered" style="width: 0%">
    <tr>
      <th>Exporter</th>
      <th>Job label</th>
    </tr>
    <tr>
      <td>Node Exporter</td>
      <td><code>node</code></td>
    </tr>
    <tr>
      <td>Prometheus</td>
      <td><code>prometheus</code></td>
    </tr>
    </table>

    {{ template "prom_content_tail" . }}

    {{ template "tail" }}
kind: ConfigMap
metadata:
  name: consoles
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus
  type: NodePort
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  additionalArgs:
  - name: web.console.templates
    value: /etc/prometheus/configmaps/consoles/
  configMaps:
  - consoles
  enableAdminAPI: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  serviceAccountName: prometheus
```

### prometheus-operator log output

```shell
ts=2024-08-27T20:58:48.773938407Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/server/operator.go:808 msg="sync prometheus" component=prometheus-controller key=default/prometheus
level=error ts=2024-08-27T20:58:48.788872832Z caller=klog.go:126 component=k8s_client_runtime func=ErrorDepth msg="sync \"default/prometheus\" failed: making statefulset failed: make StatefulSet spec: can't set arguments which are already managed by the operator: web.console.templates"
```

### Anything else?

in bundle.yaml:
In case of an argument conflict (e.g. an argument which is already set by the operator itself) or when providing an invalid argument, the reconciliation will fail and an error will be logged.

**Comment by k8s-1** [comment]
The problem is that there's no way to mount this config other than with configMaps: , which ends up in /etc/prometheus/configmaps/<cm-name>/example-console-template.html

Setting the additionalArgs flag to reroute the default console-template directory path results in an argument conflict.

**Comment by simonpasquier** [comment]
Sorry for the wrong hint @k8s-1!

> The problem is that there's no way to mount this config other than with configMaps: , which ends up in /etc/prometheus/configmaps/configmap-name/example-console-template.html

You may be able to pass the configmap via `.spec.volumes` and then mount it in the prometheus container using [strategic merge patch](https://prometheus-operator.dev/docs/platform/strategic-merge-patch/). I haven't tested it though 

I'm not inclined to have first-class support for console templates which isn't a widely used feature AFAICT.

**Comment by k8s-1** [comment]
Thanks, tried the strategic merge to change the volumePath and it ended up mounting the configMap a second time, but this time to the correct path, console templates are reachable!

http://nodeport:31924/consoles/test.html

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
container.
    - consoles
  containers: # strategic merge patch the destination of the configMap mountPath to the default console template path
  - name: prometheus
    volumeMounts:
    - mountPath: /etc/prometheus/consoles
      name: configmap-consoles
```
