### ISSUE TITLE
API validation not working for `map[v1.LabelName]string` type structures

### ISSUE THREAD

**Issue by mviswanathsai** [prometheus-operator/prometheus-operator#6889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
Issue was discovered while refactoring the `StaticConfig` struct. API validations are not adhered to for the LabelName type when it is part of the map structure. 

## Steps to Reproduce
1. Run the operator (I did it in a local cluster, with the current version code of the operator)
2. Create the manifest.
3. run `kubectl apply -f <filename.yaml>`

## Expected Result
The resource should be rejected because the `LabelName` does not follow the API validation rules.
 
## Actual Result
The resource gets created.

### Prometheus Operator Version

```shell
v0.76.0
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-08-15T02:13:19Z"
  compiler: gc
  gitCommit: a51b3b711150f57ffc1f526a640ec058514ed596
  gitTreeState: clean
  gitVersion: v1.30.4
  goVersion: go1.22.6
  major: "1"
  minor: "30"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2023-06-15T00:36:28Z"
  compiler: gc
  gitCommit: 25b4e43193bcda6c7328a6d147b1fb73a33f1598
  gitTreeState: clean
  gitVersion: v1.27.3
  goVersion: go1.20.5
  major: "1"
  minor: "27"
  platform: linux/amd64
```
```


### Kubernetes Cluster Type

kind

### How did you deploy Prometheus-Operator?

Other (please comment)

### Manifests

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: static-config
  namespace: default
  labels:
    prometheus: system-monitoring-prometheus
    app.kubernetes.io/name: scrape-config-example
spec:
  staticConfigs:
    - labels:
        -"1owner": "prometheus"
```

### prometheus-operator log output

```shell
mviswanathsai@pop-os:~$ kubectl create -f static_config.yaml 
scrapeconfig.monitoring.coreos.com/static-config created
```

### Anything else?

I ran a local deployment using `./scripts/runvexternal.sh -c` with the latest code version at the time of writing this issue.
