### ISSUE TITLE
Scrape with Prometheus operator result in random 503

### ISSUE THREAD

**Issue by CJsPod** [prometheus-operator/prometheus-operator#6929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
We are using kube-prometheus-stack and have ServiceMonitor defined for various services. 

```yaml
Name:         pg-grafana-pg-metrics
Namespace:    user-grafana
Labels:       app.kubernetes.io/component=metrics
              app.kubernetes.io/name=pg-grafana-pg-metrics
Annotations:  argocd.argoproj.io/sync-wave: 15
              argocd.argoproj.io/tracking-id: user-grafana:monitoring.coreos.com/ServiceMonitor:user-grafana/pg-grafana-pg-metrics
API Version:  monitoring.coreos.com/v1
Kind:         ServiceMonitor
Spec:
  Endpoints:
    Path:    /metrics
    Port:    http-patroni
    Scheme:  http
  Selector:
    Match Labels:
      App:  pg-grafana-pg-metrics
---
Name:         pg-keycloak-db-pg-metrics
Namespace:    security
API Version:  monitoring.coreos.com/v1
Kind:         ServiceMonitor
Spec:
  Endpoints:
    Path:    /metrics
    Port:    http
    Scheme:  https
    Tls Config:
      Ca File:               /etc/prometheus/istio-certs/root-cert.pem
      Cert File:             /etc/prometheus/istio-certs/cert-chain.pem
      Insecure Skip Verify:  true
      Key File:              /etc/prometheus/istio-certs/key.pem
    enableHttp2:             false
    Path:                    /metrics
    Port:                    http-patroni
    Scheme:                  https
    Tls Config:
      Ca File:               /etc/prometheus/istio-certs/root-cert.pem
      Cert File:             /etc/prometheus/istio-certs/cert-chain.pem
      Insecure Skip Verify:  true
      Key File:              /etc/prometheus/istio-certs/key.pem
  Selector:
    Match Labels:
      App:  pg-keycloak-db-pg-metrics
```
## Expected Result

Every time when we roll new nodes or when postgres pods are recreated, prometheus should be able to scrape the targets.

## Actual Result

Every time when we roll new nodes or when Postgres pods are recreated, we see 503 Error in Prometheus Target status for random Postgres pods. upon restart of Prometheus pods it gets fixed and we see healthy target status Postgres pods. Verified that all the targets details are correct, and services are working.
Also, On doing curl to Postgres pod scrape endpoint from Prometheus pod I can see the metric, but the Prometheus target status still shows 503 until we restart Prometheus.

### Prometheus Operator Version

```shell
Prometheus Operator - v0.76.0
prometheus, version 2.54.1
kube-prometheus-stack - 62.3.1
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-06-11T20:29:44Z"
  compiler: gc
  gitCommit: 39683505b630ff2121012f3c5b16215a1449d5ed
  gitTreeState: clean
  gitVersion: v1.30.2
  goVersion: go1.22.4
  major: "1"
  minor: "30"
  platform: windows/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-04-16T15:00:26Z"
  compiler: gc
  gitCommit: 55019c83b0fd51ef4ced8c29eec2c4847f896e74
  gitTreeState: clean
  gitVersion: v1.29.4
  goVersion: go1.21.9
  major: "1"
  minor: "29"
  platform: linux/amd64
```

### Kubernetes Cluster Type

Other (please comment)

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### prometheus-operator log output

```shell
Nothing specific in logs
```

**Comment by slashpai** [comment]
Did you check the Prometheus pod logs when issue is occurring?

**Comment by dongjiang1989** [comment]
Does the postgres pod set readiness and liveness to ensure that the pod IP can serve external parties? What is the specific pg yaml?

**Comment by CJsPod** [comment]
We are using Zalando postgresql, and currently we do not have readiness and liveness set on pg pods. 

```yaml

apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: pg-grafana
spec:
  additionalVolumes:
    - mountPath: /home/
      name: pg-exporter-queries
      targetContainers:
        - postgres-exporter
      volumeSource:
        configMap:
          name: pg-exporter-queries
          optional: true
  initContainers:
    - command:
        - sh
        - '-c'
        - >-
          mkdir -p /home/postgres/pgdata/pgroot/data && ls -lah 
          /home/postgres/pgdata/pgroot && chmod 0700
          /home/postgres/pgdata/pgroot/data && ls -lah 
          /home/postgres/pgdata/pgroot
      image: alpine:3.18.0
      imagePullPolicy: IfNotPresent
      name: pgdata-permissions-fix
      volumeMounts:
        - mountPath: /home/postgres/pgdata
          name: pgdata
  numberOfInstances: 3
  patroni:
    pg_hba:
      - local     all             all                             trust
      - hostssl   all             +zalandos    127.0.0.1/32       pam
      - host      all             all          127.0.0.1/32       md5
      - hostssl   all             +zalandos    ::1/128            pam
      - host      all             all          ::1/128            md5
      - local     replication     standby                         trust
      - hostssl   replication     standby      all                md5
      - hostnossl all             all          all                md5
      - hostssl   all             +zalandos    all                pam
      - hostssl   all             all          all                md5
  postgresql:
    parameters:
      max_wal_size: 256MB
      min_wal_size: 64MB
    version: '12'
  preparedDatabases:
    grafana:
      defaultUsers: true
      schemas:
        public:
          defaultUsers: true
  sidecars:
    - image: patroniselfheal:0.0.2
      name: patroni-selfheal
  teamId: pg
  users:
    admin:
      - superuser
      - createdb
```
