### ISSUE TITLE
Review e2e/unit tests for verifying Prometheus 3 support

### ISSUE THREAD

**Issue by slashpai** [prometheus-operator/prometheus-operator#6942]
### Component(s)

Other (please comment)

### What is missing? Please describe.

Review e2e/unit tests for verifying Prometheus 3 support. This is to find issues if any for Prometheus 3 and any updates needed for operator code

Related Issues:

- https://github.com/prometheus-operator/prometheus-operator/issues/6939
- https://github.com/prometheus-operator/prometheus-operator/pull/6940

## Environment
Kubernetes Version: NA
Prometheus-Operator Version: NA

**Comment by slashpai** [comment]
Documenting what we discussed during office hours today

### Possible actions

* Make e2e test pipeline compatible with podman (but the kind setup might be a problem)
* Improve failure messages so we know exactly what happened (e.g. collect pod logs -via framework.GetLogs()-, namespace object, …)
* set fail-fast: false for the periodic workflow https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#handling-failures

Existing prom3 test were failing on operatorUpgrade

```
status:
  availableReplicas: 0
  conditions:
  - lastTransitionTime: "2024-09-23T11:59:35Z"
    message: 'shard 0: statefulset operatorupgrade-operatorupgrade-sk9l48-0-c4775453/prometheus-operator-upgrade
      not found'
    observedGeneration: 1
    reason: StatefulSetNotFound
    status: "False"
    type: Available
  - lastTransitionTime: "2024-09-23T11:59:35Z"
    message: 'unsupported Prometheus major version 3.0.0-beta.0: %!w(<nil>)'
    observedGeneration: 1
    reason: ReconciliationFailed
    status: "False"
    type: Reconciled
  paused: false
  replicas: 0
```
