### ISSUE TITLE
Add credentialsFile support in scrape class

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#6986]
### Component(s)

Prometheus, PrometheusAgent, ServiceMonitor, PodMonitor, Probe, ScrapeConfig

### What is missing? Please describe.

Currently it's possible to use scrape classes to provide default TLS cert/key files to ServiceMonitor, PodMonitor, Probe and ScrapeConfig objects (in fact it was the primary use case for scrape classes as described in https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/proposals/202305-scrapeclasses.md).

It would be useful to add the same kind of support for (bearer) token files:

````yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: example
spec:
  scrapeClasses:
  - name: sa-token-file
    default: true
    authorization:
      credentialsFile: /var/run/secrets/kubernetes.io/serviceaccount/token
...
````

### Describe alternatives you've considered.

N/A

## Environment
Kubernetes Version: N/A
Prometheus-Operator Version: N/A
