### ISSUE TITLE
Documentation: advertised OTLPConfig in Prometheus CRD not available yet

### ISSUE THREAD

**Issue by r-asiebert** [prometheus-operator/prometheus-operator#7002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Attempted to use `….otlp.promoteResourceAttributes` feature exposed in Prometheus CRD, which doesn't exist yet in Prometheus.

### Prometheus Operator Version

```shell
0.77.1
```

### Kubernetes Version

```yaml
N/A
```

### Kubernetes Cluster Type

Other (please comment)

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml
# Helm values
prometheus:
  prometheusSpec:
    additionalConfig:
      otlp:
        # https://github.com/prometheus-operator/prometheus-operator/blob/3993785/Documentation/api.md#monitoring.coreos.com/v1.OTLPConfig
        promoteResourceAttributes:
          # https://prometheus.io/docs/guides/opentelemetry/
          - service.instance.id
          - service.name
          - service.namespace
          - cloud.region
          - container.name
          - deployment.environment
          - k8s.cluster.name
          - k8s.namespace.name
          - k8s.pod.name
```

### prometheus-operator log output

```shell
N/A - Operator correctly writes /etc/prometheus/config_out/prometheus.env.yaml and triggers Prom conf reload
```

## Doc location

https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.CommonPrometheusFields advertises this field in the `Prometheus` CRD spec:
> `otlp`   [OTLPConfig](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.OTLPConfig) 
> (Optional) Settings related to the OTLP receiver feature. It requires Prometheus >= v2.54.0.

([current source](https://github.com/prometheus-operator/prometheus-operator/blob/880f847f6a553019d968ba65e5eb19ade7170b59/Documentation/api.md#L11528-L11542))

This `otlp` block contains the `promoteResourceAttributes` configuration.

## Issue

After upgrading to the latest Helm Chart (kube-prometheus-stack 65.1.1) finally including the 0.77.1 Operator with this CRD field, I found out Prometheus doesn't support it yet. Prometheus 2.54.1 rejects the resulting config file with `field otlp not found in type config.plain`.

Looking at the Prometheus repo, this feature was introduced in https://github.com/prometheus/prometheus/pull/14200 **and is not released yet**. The merge is only in releases `v3.0.0-beta.0 v2.55.0-rc.0 v0.300.0-beta.0`, and the current changelog has it slated for 2.55 currently in RC:
https://github.com/prometheus/prometheus/blob/d9a54284f5bcf5d82b2552a00fc476669c3634d5/CHANGELOG.md#L35

Therefore, "_It requires Prometheus >= v2.54.0_" in the CRD documentation is incorrect and misleading.
