### ISSUE TITLE
Accessing volumes from prometheus pod requires root privileges

### ISSUE THREAD

**Issue by yp969803** [prometheus-operator/prometheus-operator#7009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
For using a volume mount in prometheus pod, i have to give it root privileges
## Steps to Reproduce
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    release: prometheus
spec:
  retention: 5d
  serviceAccountName: prometheus

  serviceMonitorSelector:
    matchLabels:
      release: prometheus
  podMonitorSelector:
    matchLabels:
      release: prometheus
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 1Gi
```

Log output of prometheus-pod
```
ts=2024-10-13T05:46:53.875Z caller=query_logger.go:114 level=error component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log
```
## Expected Result
To solve this i have to give root privileges to the pod
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    release: prometheus
spec:
  retention: 5d
  serviceAccountName: prometheus

  serviceMonitorSelector:
    matchLabels:
      release: prometheus
  podMonitorSelector:
    matchLabels:
      release: prometheus
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 1Gi
  securityContext:
    fsGroup: 0
    runAsUser: 0           
    runAsGroup: 0        
 
```
This creates a vulnerability to the cluster

## Solution
Init container with root privileges should change the permission of '/prometheus' directory of the volume
chown -R 65534:65534 /prometheus

### Prometheus Operator Version

```shell
latest
```

### Kubernetes Version

```yaml
1.30
```

### Kubernetes Cluster Type

EKS

### How did you deploy Prometheus-Operator?

yaml manifests

### prometheus-operator log output

```shell
No error by operator
```

**Comment by simonpasquier** [comment]
You shouldn't have to run as root. The following setting should work:

```
  securityContext:
    fsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
````
