### ISSUE TITLE
EKS kubelet metrics

### ISSUE THREAD

**Issue by markretallack** [prometheus-operator/prometheus-operator#7025]
## Description

In EKS, kubelet is managed by AWS and so the (as far as I can see) the ServiceMonitor for KubeLet needs to be disabled. The metrics for volume are still available, for example, the following works:
`
kubectl get --raw /api/v1/nodes/ip-10-0-1-199.eu-west-2.compute.internal/proxy/metrics | grep kubelet_volume_stats_used_bytes
`
What is the recommended method for getting these metrics from EKS?

## Expected Result

The Metrics available

### Prometheus Operator Version

```shell
quay.io/prometheus-operator/prometheus-operator:v0.77.1
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2020-06-22T12:00:00Z"
  compiler: gc
  gitCommit: c96aede7b5205121079932896c4ad89bb93260af
  gitTreeState: clean
  gitVersion: v1.18.4
  goVersion: go1.19.9
  major: "1"
  minor: "18"
  platform: linux/amd64
serverVersion:
  buildDate: "2024-09-21T09:31:42Z"
  compiler: gc
  gitCommit: 194b08f0b9db51e750f3a3dcc2ffe5dda0103c0d
  gitTreeState: clean
  gitVersion: v1.30.5-eks-ce1d5eb
  goVersion: go1.22.6
  major: "1"
  minor: 30+
  platform: linux/amd64
```

### Kubernetes Cluster Type

EKS

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### prometheus-operator log output

```shell
NA
```
