### ISSUE TITLE
podMonitor: namespace any: true does not work anymore

### ISSUE THREAD

**Issue by tcoupin** [prometheus-operator/prometheus-operator#7075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

I use a podMonitor with `any: true` as namespaceSelector. The matching pods in anothers namespaces are not discovered by prometheus. It was working before upgrade from 0.59.1 (chart rancher-monitoring 102.0.2+up40.1.2) to 0.72.0 (chart rancher-monitoring 104.1.2+up57.0.3).

I use podmonitor for my postgresql database and setup posmonitor as described there : https://shivering-isles.com/2022/04/postgres-operator-with-monitoring

## Steps to Reproduce

- Create a pod with label `app: myapp` in namespace `myapp`
- Create a podmonitor in namespace `monitor` with spec
```
namespaceSelector:
  any: true
podMetricsEndpoints:
  - interval: 15s
    scrapeTimeout: 10s
    targetPort: 8080 #fake
  selector:
    matchLabels:
      app: myapp
```

## Expected Result

Prometheus must discover the pod.

## Actual Result

No pod are discovered.
The kubernetes sd config limits to podmonitor namespace: 
```
  kubernetes_sd_configs:
  - role: pod
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - monitor
```

### Prometheus Operator Version

```shell
0.72.0 provided by chart rancher-monitoring 104.1.2+up57.0.3 (https://github.com/rancher/charts/tree/release-v2.9/charts/rancher-monitoring/104.1.2%2Bup57.0.3)
```

### Kubernetes Version

```yaml
serverVersion:
  buildDate: "2024-09-12T15:50:42Z"
  compiler: gc
  gitCommit: 74e84a90c725047b1328ff3d589fedb1cb7a120e
  gitTreeState: clean
  gitVersion: v1.30.5+rke2r1
  goVersion: go1.22.6 X:boringcrypto
  major: "1"
  minor: "30"
  platform: linux/amd64
```

### Kubernetes Cluster Type

Rancher

### How did you deploy Prometheus-Operator?

Other (please comment)

### Manifests

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: rancher-monitoring-operator
    app.kubernetes.io/component: prometheus-operator
    app.kubernetes.io/instance: rancher-monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rancher-monitoring-prometheus-operator
    app.kubernetes.io/part-of: rancher-monitoring
    app.kubernetes.io/version: 104.1.2_up57.0.3
    chart: rancher-monitoring-104.1.2_up57.0.3
    heritage: Helm
    pod-template-hash: 6f5c765464
    release: rancher-monitoring
  name: rancher-monitoring-operator-6f5c765464-bf6pv
  namespace: cattle-monitoring-system
spec:
  automountServiceAccountToken: true
  containers:
  - args:
    - --kubelet-service=kube-system/rancher-monitoring-kubelet
    - --localhost=127.0.0.1
    - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.72.0
    - --config-reloader-cpu-request=0
    - --config-reloader-cpu-limit=0
    - --config-reloader-memory-request=0
    - --config-reloader-memory-limit=0
    - --thanos-default-base-image=docker.io/rancher/mirrored-thanos-thanos:v0.34.1
    - --secret-field-selector=type!=kubernetes.io/dockercfg,type!=kubernetes.io/service-account-token,type!=helm.sh/release.v1
    - --web.enable-tls=true
    - --web.cert-file=/cert/cert
    - --web.key-file=/cert/key
    - --web.listen-address=:8443
    - --web.tls-min-version=VersionTLS13
    env:
    - name: GOGC
      value: "30"
    image: quay.io/prometheus-operator/prometheus-operator:v0.73.0
    name: rancher-monitoring
    ports:
    - containerPort: 8443
      name: https
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    volumeMounts:
    - mountPath: /cert
      name: tls-secret
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-6bppt
      readOnly: true
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 200
  priorityClassName: default-priority
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: rancher-monitoring-operator
  tolerations:
  - effect: NoSchedule
    key: cattle.io/os
    operator: Equal
    value: linux
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: tls-secret
    secret:
      secretName: rancher-monitoring-admission
  - name: kube-api-access-6bppt
    projected:
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.namespace
            path: namespace
```

### prometheus-operator log output

```shell
gresql
level=info ts=2024-11-05T17:22:54.572012481Z caller=operator.go:766 component=prometheus-controller key=cattle-monitoring-system/rancher-monitoring-prometheus msg="sync prometheus"
level=warn ts=2024-11-05T17:22:59.482340408Z caller=promcfg.go:1374 component=prometheus-controller msg="'bearerTokenFile' is deprecated, use 'authorization' instead." version=v2.50.1 service_monitor=default/rancher-monitoring-apiserver
level=warn ts=2024-11-05T17:22:59.482947472Z caller=promcfg.go:1374 component=prometheus-controller msg="'bearerTokenFile' is deprecated, use 'authorization' instead." version=v2.50.1 service_monitor=kube-system/rancher-monitoring-coredns
level=warn ts=2024-11-05T17:22:59.483178557Z caller=promcfg.go:1374 component=prometheus-controller msg="'bearerTokenFile' is deprecated, use 'authorization' instead." version=v2.50.1 service_monitor=kube-system/rancher-monitoring-kubelet
level=warn ts=2024-11-05T17:22:59.483421868Z caller=promcfg.go:1374 component=prometheus-controller msg="'bearerTokenFile' is deprecated, use 'authorization' instead." version=v2.50.1 service_monitor=kube-system/rancher-monitoring-kubelet
level=warn ts=2024-11-05T17:22:59.483680857Z caller=promcfg.go:1374 component=prometheus-controller msg="'bearerTokenFile' is deprecated, use 'authorization' instead." version=v2.50.1 service_monitor=kube-system/rancher-monitoring-kubelet
level=warn ts=2024-11-05T17:22:59.484374372Z caller=promcfg.go:956 component=prometheus-controller msg="'targetPort' is deprecated, use 'port' instead." version=v2.50.1 pod_monitor=postgresql-operator/postgresql
```

### Anything else?

I tried 0.73.0 because of https://github.com/prometheus-operator/prometheus-operator/pull/6390 but it was not better..
