### ISSUE TITLE
prometheus-operator v0.78.1 still uses v1alpha1 and ignores `spec.timeIntervals` throwing "mute time interval not found"

### ISSUE THREAD

**Issue by meysam81** [prometheus-operator/prometheus-operator#7087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

I am using the latest stable version of the prometheus-operator (as of writing, v0.78.1) and I see the following two error lines popping up in my logs:

```
ts=2024-11-08T07:30:24.259036574Z level=warn caller=/workspace/pkg/alertmanager/operator.go:997 msg="skipping alertmanagerconfig" component=alertmanager-controller error="route[1]: mute time interval \"weekend\" not found" alertmanagerconfig=monitoring/alertmanager namespace=monitoring alertmanager=kube-prometheus-stack-alertmanager
ts=2024-11-08T07:30:24.259142152Z level=info caller=/go/pkg/mod/k8s.io/client-go@v0.31.2/tools/record/event.go:389 msg="Event occurred" object.name=alertmanager object.namespace=monitoring fieldPath="" kind=AlertmanagerConfig apiVersion=monitoring.coreos.com/v1alpha1 type=Warning reason=InvalidConfiguration message="AlertmanagerConfig alertmanager was rejected due to invalid configuration: route[1]: mute time interval \"weekend\" not found"
```

This is the minimal configuration to get to the same outcome as I did:

```yaml
---
apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  receivers:
    - name: blackhole
    - name: slack
  route:
    continue: true
    groupBy:
      - alertname
      - app
      - env
      - severity
    matchers:
      - matchType: "=~"
        name: severity
        value: critical|error|info
    muteTimeIntervals:
      - weekend
    receiver: blackhole
    routes:
      - matchers:
          - matchType: "=~"
            name: severity
            value: critical|error
        receiver: slack
  timeIntervals:
    - name: weekend
      timeIntervals:
        - weekdays:
            - saturday
            - sunday
```

If you notice, you will see that the second log line has `apiVersion=monitoring.coreos.com/v1alpha1`, however, my manifest is using `v1beta1` apiVersion.

This is where the logs are coming from (again, notice the v1alpha1 in the filepath):

https://github.com/prometheus-operator/prometheus-operator/blob/7b8010bea23c8e1d282bac64cf8cc02d46f4267f/pkg/alertmanager/validation/v1alpha1/validation.go#L380:L384

I have converted the above manifest into a `alertmanager.yml` config file as below, and the alertmanager `0.27.0` runs this with no hiccups.

```yaml
receivers:
  - name: blackhole
  - name: slack
route:
  receiver: blackhole
  group_by:
    - alertname
    - app
    - env
    - severity
  routes:
    - continue: false
      matchers:
        - severity =~ critical|error
      receiver: slack
    - matchers:
        - severity =~ info
      receiver: slack
      mute_time_intervals:
        - weekend
time_intervals:
  - name: weekend
    time_intervals:
      - weekdays:
          - saturday
          - sunday
```

I believe the prometheus-operator is lagging behind its currently provided API version v1beta1 and is only considering the use of v1alpha1 and that is why I keep seeing those errors.

Effectively, with the kube-prometheus-stack (65.8.1 as of today), we can't have `timeIntervals` in the AlertmanagerConfig CRD because it is still using the old v1alpha1 version.

I also manually upgraded the prometheus-operator to the later version than the currently default of v0.77.0 but even that didn't do!

### Prometheus Operator Version

```shell
quay.io/prometheus-operator/prometheus-operator:v0.78.1
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-07-16T23:54:40Z"
  compiler: gc
  gitCommit: 6fc0a69044f1ac4c13841ec4391224a2df241460
  gitTreeState: clean
  gitVersion: v1.30.3
  goVersion: go1.22.5
  major: "1"
  minor: "30"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-10-26T04:07:15Z"
  compiler: gc
  gitCommit: 6da204241bfd40220cb1af4cde35609e0c58df72
  gitTreeState: clean
  gitVersion: v1.31.2+k3s1
  goVersion: go1.22.8
  major: "1"
  minor: "31"
  platform: linux/amd64
```

### Kubernetes Cluster Type

Rancher

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### prometheus-operator log output

```shell
It is provided above, I try not to repeat myself.
```
