### ISSUE TITLE
Add support of promql-experimental-functions in PrometheusRule

### ISSUE THREAD

**Issue by pavelstyra** [prometheus-operator/prometheus-operator#7099]
### Component(s)

PrometheusRule

### What is missing? Please describe.

`sort_by_label`, `sort_by_label_desc` functions and `limitk()`, `limit_ratio()` operators are getting rejected by `ValidatingWebhookConfiguration/prometheus-kube-prometheus-admission`

Which means I cannot create a PrometheusRule using these functions and operators in expression:
```
kubectl apply -f - <<EOF
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: check-limitk
  namespace: monitoring
  labels:
    app: check-limitk
    release: prometheus
spec:
  groups:
    - name: check-limitk
      rules:
        - alert: check-limitk
          annotations:
            message: check-limitk
          expr: limitk(1, kube_pod_info) > 0
EOF

The  "prometheusrules" is invalid: : 7:11: group "check-limitk", rule 1, "check-limitk": could not parse expression: 1:1: parse error: unknown function with name "limitk"
```

They are implemented in Prometheus and must be enabled with `--enable-feature=promql-experimental-functions`:
https://github.com/prometheus/prometheus/pull/11299
https://github.com/prometheus/prometheus/pull/12503

## Environment
Kubernetes Version: v1.30.5
Prometheus-Operator Version: 0.78.1

**Comment by natdol** [comment]
We're experiencing similar issue with double_exponential_smoothing function, which is enabled in Prometheus.
After upgrading to from v2 to v3 and changing holt_winters function to double_exponential_smoothing it is not possible to use it in PrometheusRule.

**Comment by davidbrusius** [comment]
I am trying to use the new `anchored` and `smoothed` [Extended Range Selectors](https://prometheus.io/docs/prometheus/latest/feature_flags/#extended-range-selectors) on a few recording rules and facing the same limitation. Any updates on this one?

**Comment by simonpasquier** [comment]
we need some changes to https://github.com/prometheus-community/prom-label-proxy first but once they are in, I'll submit a PR.

**Comment by simonpasquier** [comment]
we also need first https://github.com/prometheus-operator/prometheus-operator/pull/8493.

**Comment by davidbrusius** [comment]
Much appreciated @simonpasquier!

For anyone using this through the `kube-prometheus-stack` chart, I've pushed a change upstream to support the new `--promql-options` CLI arg in the admission-webhook deployment https://github.com/prometheus-community/helm-charts/pull/6945 and upgraded `prometheus-operator` to the required version v0.91.0 at https://github.com/prometheus-community/helm-charts/pull/6947. Changes are available starting at `kube-prometheus-stack` version `86.0.0` - please note that this does require you to run the admission hooks on its own separate deployment by enabling it. Example:


```yaml
kube-prometheus-stack:
  prometheusOperator:
    admissionWebhooks:
      deployment:
        enabled: true
        promqlOptions: ["extended-range-selectors"]
```
