### ISSUE TITLE
alertmanagerconfig - proxyURL auto-removing on operator upgrade

### ISSUE THREAD

**Issue by kozharskyad** [prometheus-operator/prometheus-operator#7114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
There is destructive operation occurs on operator upgrade. After upgrading from version 0.68.0 to 0.77.2, operator removing proxyURL field from all receivers. Also proxyURL renamed to proxyUrl in CRD, using the proxyURL field causes OpenAPI validation error.

Field naming before upgrade:
```
spec.name.schema.openAPIV3Schema.properties.spec.properties.receivers.items.properties.discordConfigs.items.properties.httpConfig.properties.oauth2.properties.proxyURL
```

Field naming after upgrade:
```
spec.name.schema.openAPIV3Schema.properties.spec.properties.receivers.items.properties.discordConfigs.items.properties.httpConfig.properties.oauth2.properties.proxyUrl
```

## Steps to Reproduce
1. Install prometheus-operator 0.68.0
2. Create and deploy following CR:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: test-alertmanagerconfig
  labels:
    alertmanagerconfig: here
spec:
  route:
    groupBy:
      - job
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: test-receiver
  receivers:
    - discordConfigs:
        - apiURL:
            key: test-api-url-key
            name: test-alertmanagerconfig-secret
            optional: true
          httpConfig:
            proxyUrl: http://127.0.0.1:8123
      name: test-receiver
      opsgenieConfigs:
        - httpConfig:
            proxyUrl: http://127.0.0.1:8123
          responders:
            - type: team
              name: test-responder-name
      pagerdutyConfigs:
        - httpConfig:
            proxyUrl: http://127.0.0.1:8123
          serviceKey:
            key: test-service-key
            name: test-alertmanagerconfig-secret
            optional: true
      pushoverConfigs:
        - httpConfig:
            proxyUrl: http://127.0.0.1:8123
          userKey:
            key: test-user-key
            name: test-alertmanagerconfig-secret
            optional: true
          token:
            key: test-token-key
            name: test-alertmanagerconfig-secret
            optional: true
      slackConfigs:
        - httpConfig:
            proxyUrl: http://127.0.0.1:8123
      snsConfigs:
        - httpConfig:
            proxyUrl: http://127.0.0.1:8123
          topicARN: some-test-arn
      webhookConfigs:
        - httpConfig:
            proxyUrl: http://127.0.0.1:8123
          url: http://127.0.0.1:8123
      wechatConfigs:
        - httpConfig:
            proxyUrl: http://127.0.0.1:8123
```
3. Upgrade prometheus-operator to 0.77.2 version
4. Check previously deployed CR:
```
kubectl get alertmanagerconfig/test-alertmanagerconfig
```

## Expected Result
Cluster object is the same (conversion must working) OR automatic remapping applied to CR.

## Actual Result
proxyURL fields automatically removed, there is no replace proxyUrl performed, proxy functionality is absent without hand editing.

### Prometheus Operator Version

```shell
Name:                   prometheus-operator
Namespace:              d8-operator-prometheus
CreationTimestamp:      Wed, 18 Oct 2023 22:48:58 +0300
Labels:                 app.kubernetes.io/managed-by=Helm
                        heritage=deckhouse
                        module=operator-prometheus
Annotations:            deployment.kubernetes.io/revision: 32
                        meta.helm.sh/release-name: operator-prometheus
                        meta.helm.sh/release-namespace: d8-system
Selector:               app=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=prometheus-operator
  Annotations:      kubectl.kubernetes.io/restartedAt: 2024-11-06T12:52:24+03:00
  Service Account:  operator-prometheus
  Containers:
   prometheus-operator:
    Image:      dev-registry.deckhouse.io/sys/deckhouse-oss@sha256:f138e3e1f607a30739775396fe59d3b169d355a2398998edc0177c6dd4116005
    Port:       <none>
    Host Port:  <none>
    Args:
      --kubelet-service=d8-monitoring/kubelet
      --config-reloader-cpu-request=0
      --config-reloader-cpu-limit=0
      --config-reloader-memory-request=0
      --config-reloader-memory-limit=0
      --prometheus-config-reloader=dev-registry.deckhouse.io/sys/deckhouse-oss@sha256:8abfb07f41a17dfaa3bcfd6210fa1c27f6a9a1361426d83704d2a84f6b76dc90
      --alertmanager-instance-namespaces=d8-monitoring
      --prometheus-instance-namespaces=d8-monitoring
      --thanos-ruler-instance-namespaces=d8-monitoring
      --secret-field-selector=type!=kubernetes.io/dockercfg,type!=kubernetes.io/service-account-token,type!=helm.sh/release.v1
      --web.listen-address=127.0.0.1:8080
    Requests:
      ephemeral-storage:  50Mi
    Environment:          <none>
    Mounts:               <none>
   kube-rbac-proxy:
    Image:      dev-registry.deckhouse.io/sys/deckhouse-oss@sha256:6cfcc749556651fb851ed7819ad7f3dc51964538586f44126c0dc923cbbaecf8
    Port:       8443/TCP
    Host Port:  0/TCP
    Args:
      --secure-listen-address=$(KUBE_RBAC_PROXY_LISTEN_ADDRESS):8443
      --v=2
      --logtostderr=true
      --stale-cache-interval=1h30m
    Requests:
      ephemeral-storage:  50Mi
    Environment:
      KUBE_RBAC_PROXY_LISTEN_ADDRESS:   (v1:status.podIP)
      KUBE_RBAC_PROXY_CONFIG:          upstreams:
                                       - upstream: http://127.0.0.1:8080/
                                         path: /
                                         authorization:
                                           resourceAttributes:
                                             namespace: d8-operator-prometheus
                                             apiGroup: apps
                                             apiVersion: v1
                                             resource: daemonsets
                                             subresource: prometheus-metrics
                                             name: prometheus-operator

    Mounts:                            <none>
  Volumes:                             <none>
  Priority Class Name:                 cluster-low
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  prometheus-operator-64955b76d6 (0/0 replicas created), prometheus-operator-856b74f6f9 (0/0 replicas created)
NewReplicaSet:   prometheus-operator-6b6577b977 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  31m   deployment-controller  Scaled up replica set prometheus-operator-6b6577b977 to 1
  Normal  ScalingReplicaSet  31m   deployment-controller  Scaled down replica set prometheus-operator-856b74f6f9 to 0 from 1
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-11-07T16:28:39Z"
  compiler: gc
  gitCommit: "0000000000000000000000000000000000000000"
  gitTreeState: archive
  gitVersion: v1.28.15
  goVersion: go1.20.5
  major: "1"
  minor: "28"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-11-07T16:25:57Z"
  compiler: gc
  gitCommit: "0000000000000000000000000000000000000000"
  gitTreeState: archive
  gitVersion: v1.28.15
  goVersion: go1.20.5
  major: "1"
  minor: "28"
  platform: linux/amd64
```

### Kubernetes Cluster Type

Other (please comment)

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### prometheus-operator log output

```shell
level=info ts=2024-11-14T08:58:04.574016654Z caller=main.go:224 msg="Starting Prometheus Operator" version="(version=0.68.0, branch=, revision=unknown)"
level=info ts=2024-11-14T08:58:04.574072282Z caller=main.go:225 build_context="(go=go1.20.5, platform=linux/amd64, user=deckhouse, date=, tags=unknown)"
level=info ts=2024-11-14T08:58:04.668028401Z caller=operator.go:356 component=prometheusoperator msg="Kubernetes API capabilities" endpointslices=true
level=info ts=2024-11-14T08:58:04.69846682Z caller=operator.go:295 component=prometheusagentoperator msg="Kubernetes API capabilities" endpointslices=true
level=info ts=2024-11-14T08:58:04.70287772Z caller=main.go:113 msg="Starting insecure server on 127.0.0.1:8080"
level=info ts=2024-11-14T08:58:04.705947899Z caller=operator.go:481 component=prometheusoperator msg="connection established" cluster-version=v1.28.15
level=info ts=2024-11-14T08:58:04.707223091Z caller=operator.go:490 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2024-11-14T08:58:04.706960939Z caller=operator.go:476 component=alertmanageroperator msg="connection established" cluster-version=v1.28.15
level=info ts=2024-11-14T08:58:04.707408865Z caller=operator.go:485 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2024-11-14T08:58:04.707052936Z caller=operator.go:313 component=thanosoperator msg="connection established" cluster-version=v1.28.15
level=info ts=2024-11-14T08:58:04.707554091Z caller=operator.go:322 component=thanosoperator msg="CRD API endpoints ready"
level=info ts=2024-11-14T08:58:04.707201472Z caller=operator.go:320 component=prometheusagentoperator msg="connection established" cluster-version=v1.28.15
level=info ts=2024-11-14T08:58:04.71132079Z caller=operator.go:329 component=prometheusagentoperator msg="CRD API endpoints ready"
level=info ts=2024-11-14T08:58:04.807894131Z caller=operator.go:413 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2024-11-14T08:58:04.808008868Z caller=operator.go:307 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2024-11-14T08:58:04.808090645Z caller=operator.go:274 component=thanosoperator msg="successfully synced all caches"
level=info ts=2024-11-14T08:58:04.809888682Z caller=operator.go:1189 component=prometheusoperator key=d8-monitoring/longterm msg="sync prometheus"
```

### Anything else?

We use Deckhouse Kubernetes Platform.
