### ISSUE TITLE
Enable setting ThreadId for Telegram notifications

### ISSUE THREAD

**Issue by cybercoder** [prometheus-operator/prometheus-operator#7122]
### Component(s)

AlertManagerConfig

### What is missing? Please describe.

This pull request has been merged:
https://github.com/prometheus/alertmanager/pull/3638

but the
alertmanagerconfigs.monitoring.coreos.com has not updated with the telegram threadId.

**Comment by slashpai** [comment]
This is already done in https://github.com/prometheus-operator/prometheus-operator/pull/6999 and available in main branch. This will be part of next release `v0.79`  which is on  `2024-12-11` :)

**Comment by AlexxxxxxD** [comment]
@slashpai hi! 

I encountered the same issue: https://github.com/prometheus/alertmanager/issues/3332#issuecomment-2500980613

Tested with the following versions of the [kube-prometheus-stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack/67.3.0) chart:  
- 67.3.0 - v0.79.1  
- 67.2.1 - v0.79.1  
- 67.2.0 - v0.79.0  

When setting up a Telegram bot with the following configuration:
```yaml
receivers:
  - name: "telegram-alert"
    telegram_configs:
      - send_resolved: true
        bot_token: "token"
        chat_id: -100*****
        message_thread_id: 4
        parse_mode: HTML
        message: |
          {{ template "alert.template" . }}
        disable_notifications: false
```

In the logs of kube-prometheus-stack-operator, I get the following error:

```log
ts=2024-12-18T15:54:13.738714959Z level=info caller=/workspace/pkg/alertmanager/operator.go:544 msg="sync alertmanager" component=alertmanager-controller key=logging/kube-prometheus-stack-alertmanager
ts=2024-12-18T15:54:13.745184972Z level=error caller=/workspace/pkg/operator/resource_reconciler.go:557 msg="Unhandled Error" logger=UnhandledError err="sync \"logging/kube-prometheus-stack-alertmanager\" failed: provision alertmanager configuration: failed to initialize from secret: yaml: unmarshal errors:\n  line 35: field message_thread_id not found in type config.plain"
```

Alertmanager version:  
```yaml
alertmanager:
  alertmanagerSpec:
    image:
      tag: v0.28.0-rc.0
```

Without `message_thread_id: 4`, the alert works as expected.

I also found that a similar issue has been reported by others.

Could you please help me understand if this is a bug or if there is a workaround for enabling the `message_thread_id` field?

https://prometheus.io/docs/alerting/0.28/configuration/#telegram_config
