### ISSUE TITLE
PodMonitor support of port number in addition of port name

### ISSUE THREAD

**Issue by jerem0808** [prometheus-operator/prometheus-operator#7129]
## Description
We are working with some helm charts that only exposes the port number exposing the metrics but not actually write it inside the deployment/statefulset. 
For example ingress-nginx exposes only the prometheus.io/port=10254
but inside the deployment.yaml the port is not exposed with a name[
deployment.yaml](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml)

## Steps to Reproduce
I'm using this podmonitor
```
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ingress-nginx-monitor
  namespace: prometheus-operator
spec:
  podMetricsEndpoints:
    - targetPort: "10254"
  namespaceSelector:
    matchNames:
      - ingress-nginx
  selector:
    matchLabels:
      app: ingress-nginx
```
I have the following deployment 
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: ingress-nginx
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ingress-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-11-12T15:27:35+01:00"
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: ingress-nginx
    spec:
[...]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nginx-ingress-controller
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
[...]
```

The configuration is applied
```
prom-agent-kube-prometheus-stack-prometheus-2 prometheus ts=2024-11-19T15:56:34.477Z
caller=kubernetes.go:331 level=info component="discovery manager scrape" discovery=kubernetes config=podMonitor/prometheus-operator/ingress-nginx-monitor/0 msg="Using pod service account via in-cluster config" 
```

But the actual config is as follow:
```
- job_name: podMonitor/prometheus-operator/ingress-nginx-monitor/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - ingress-nginx
  relabel_configs:
  - source_labels:
    - job
    target_label: __tmp_prometheus_job_name
  - action: drop
    source_labels:
    - __meta_kubernetes_pod_phase
    regex: (Failed|Succeeded)
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_label_app
    - __meta_kubernetes_pod_labelpresent_app
    regex: (ingress-nginx);true
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_container_port_name
    regex: "10254"
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - target_label: job
    replacement: prometheus-operator/ingress-nginx-monitor
  - target_label: endpoint
    replacement: "10254"
  - source_labels:
    - __address__
    target_label: __tmp_hash
    modulus: 1
    action: hashmod
  - source_labels:
    - __tmp_hash
    regex: 0
    action: keep
```
For me this part 
```
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_container_port_name
    regex: "10254"
```
is wrong and should be port_number instead of port_name
according to the [prometheus configuration documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#pod)

## Expected Result
__meta_kubernetes_pod_container_port_number is used when port is a number

## Actual Result
__meta_kubernetes_pod_container_port_name is used and i don't see my metrics in our Cortex

### Prometheus Operator Version

```shell
$ kubectl describe deploy kube-prometheus-stack-operator -n prometheus-operator
Name:                   kube-prometheus-stack-operator
Namespace:              prometheus-operator
CreationTimestamp:      Tue, 19 Nov 2024 10:51:56 +0100
Labels:                 app=kube-prometheus-stack-operator
                        app.kubernetes.io/component=prometheus-operator
                        app.kubernetes.io/instance=kube-prometheus-stack
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=kube-prometheus-stack-prometheus-operator
                        app.kubernetes.io/part-of=kube-prometheus-stack
                        app.kubernetes.io/version=65.1.1
                        chart=kube-prometheus-stack-65.1.1
                        helm.toolkit.fluxcd.io/name=kube-prometheus-stack
                        helm.toolkit.fluxcd.io/namespace=prometheus-operator
                        heritage=Helm
                        release=kube-prometheus-stack
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: kube-prometheus-stack
                        meta.helm.sh/release-namespace: prometheus-operator
Selector:               app=kube-prometheus-stack-operator,release=kube-prometheus-stack
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=kube-prometheus-stack-operator
                    app.kubernetes.io/component=prometheus-operator
                    app.kubernetes.io/instance=kube-prometheus-stack
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=kube-prometheus-stack-prometheus-operator
                    app.kubernetes.io/part-of=kube-prometheus-stack
                    app.kubernetes.io/version=65.1.1
                    chart=kube-prometheus-stack-65.1.1
                    heritage=Helm
                    release=kube-prometheus-stack
  Service Account:  kube-prometheus-stack-operator
  Containers:
   kube-prometheus-stack:
    Image:      quay-remote.artifactory.swisscom.com/prometheus-operator/prometheus-operator:v0.77.1
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --localhost=127.0.0.1
      --prometheus-config-reloader=quay-remote.artifactory.swisscom.com/prometheus-operator/prometheus-config-reloader:v0.77.1
      --config-reloader-cpu-request=0
      --config-reloader-cpu-limit=0
      --config-reloader-memory-request=0
      --config-reloader-memory-limit=0
      --thanos-default-base-image=quay.io/thanos/thanos:v0.36.1
      --secret-field-selector=type!=kubernetes.io/dockercfg,type!=kubernetes.io/service-account-token,type!=helm.sh/release.v1
    Liveness:   http-get http://:http/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      GOGC:  30
    Mounts:  <none>
  Volumes:   <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   kube-prometheus-stack-operator-7bc79f49d9 (1/1 replicas created)
Events:          <none>
```

### Kubernetes Version

```yaml
$ kubectl version -o yaml
clientVersion:
  buildDate: "2024-02-14T10:40:49Z"
  compiler: gc
  gitCommit: 4b8e819355d791d96b7e9d9efe4cbafae2311c88
  gitTreeState: clean
  gitVersion: v1.29.2
  goVersion: go1.21.7
  major: "1"
  minor: "29"
  platform: windows/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-01-23T07:45:55Z"
  compiler: gc
  gitCommit: 858f08ca84457e1a267aca691e6bbb49779524d5
  gitTreeState: clean
  gitVersion: v1.29.1
  goVersion: go1.21.6
  major: "1"
  minor: "29"
  platform: linux/amd64
```

### Kubernetes Cluster Type

Other (please comment)

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### prometheus-operator log output

```shell
ts=2024-11-19T16:08:59.285244053Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:09:41.067273217Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:09:41.102132905Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:09:44.053886436Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:09:44.086215882Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:09:51.050048224Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:09:51.085929899Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:10:27.052285042Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:10:27.095561397Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:10:32.086958467Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:10:32.12350795Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:10:36.058310555Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:10:36.096839872Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:10:37.151019239Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:10:37.19159587Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:10:42.051165812Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:10:42.137214469Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:10:42.172170197Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:10:42.214533433Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:10:45.04058632Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:10:45.080779123Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:01.061148325Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:01.102291075Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:06.085030785Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:06.117843009Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:11.055742601Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:11.087584817Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:14.063832985Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:14.097867435Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:15.131657782Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:15.164122497Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:15.201991635Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:23.053528428Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:23.087784358Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:32.035850344Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:32.070642602Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
ts=2024-11-19T16:11:43.848792744Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/agent/operator.go:688 msg="sync prometheus" component=prometheusagent-controller key=prometheus-operator/kube-prometheus-stack-prometheus
```

**Comment by jerem0808** [comment]
Hi
I tried as well but same outcome
```
spec:
  namespaceSelector:
    matchNames:
    - ingress-nginx
  podMetricsEndpoints:
  - targetPort: "10254"
  selector:
    matchLabels:
      app: ingress-nginx
```

```
   regex: (ingress-nginx);true
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_container_port_name
    regex: "10254"
  - source_labels:
```

**Comment by simonpasquier** [comment]
`targetPort: "10254"` should be `targetPort: 10254` (without the double quotes).

**Comment by jerem0808** [comment]
thanks it works. But then the question would be what will be the future for the port key? Because it's support only port name and targetPort is deprecated

**Comment by simonpasquier** [comment]
I realize that the topic was already discussed (https://github.com/prometheus-operator/prometheus-operator/issues/3071#issuecomment-1167264566=) and I advocated for keeping the deprecation on `targetPort` and adding a `portNumber` field (integer) which would fit your use case (scrape metrics from a container port which isn't explicitly exposed) and offer a less cumbersone API (e.g. no more guessing on whether the field value is a string or a number).

````
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: example-app
spec:
  selector:
    matchLabels:
      app: example-app
  podMetricsEndpoints:
  - portNumber: 8080
````
