### ISSUE TITLE
AlertManagerConfig - PushoverConfig Expire and Retry Settings Units Missing

### ISSUE THREAD

**Issue by jlrgraham** [prometheus-operator/prometheus-operator#7245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

After upgrading Prometheus Operator via the `kube-prometheus-stack` Helm chart `67.5.0` my AlertManager configurations that specify either the `expire` or `retry` parameters to the [pushover_config](https://prometheus.io/docs/alerting/latest/configuration/#pushover_config) result in invalid AlertManager configurations.

The logs complain of a missing unit on the rendered [duration](https://prometheus.io/docs/alerting/latest/configuration/#duration) in the configuration.
```
alertmanager ts=2024-12-28T23:11:33.821Z caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config_out/alertmanager.env.yaml err="time: missing unit in duration \"300000000000\""
```
## Steps to Reproduce

Apply an AlertManager configuration that references the `retry` or `expire` parameters, see the included `AlertManagerConfig` resource in the sample manifests.

Observe either failed launches of the `alertmanager` pods, or errors on loading the configuration for running instances.

Inspecting the generated secret from the operator shows the value of `300000000000` in `retry` without any units specified.

```
kubectl -n prometheus get secrets alertmanager-kube-prometheus-stack-alertmanager-generated -o json | jq -r '.data["alertmanager.yaml.gz"]' | base64 -d | gzip -d
```

```
route:
  receiver: prometheus/alertmanager/pushover-receiver
  group_by:
  - alertname
  - datacenter
  - service
  routes:
  - receiver: prometheus/alertmanager/pushover-receiver
    continue: true
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
receivers:
- name: prometheus/alertmanager/pushover-receiver
  pushover_configs:
  - user_key: <secret>
    token: <secret>
    priority: "1"
    retry: 300000000000
templates: []
```

## Expected Result

The configuration should render the `retry` and `expire` [fields as AlertManager expects](https://prometheus.io/docs/alerting/latest/configuration/#duration), including the units and as a string.

## Actual Result

The `retry` and `expire` parameters appear to be rendered as nanoseconds without a unit, and result in failed starts of the service.

### Prometheus Operator Version

```shell
Name:                   kube-prometheus-stack-operator
Namespace:              prometheus
CreationTimestamp:      Sat, 29 Jul 2023 14:12:57 -0500
Labels:                 app=kube-prometheus-stack-operator
                        app.kubernetes.io/component=prometheus-operator
                        app.kubernetes.io/instance=kube-prometheus-stack
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=kube-prometheus-stack-prometheus-operator
                        app.kubernetes.io/part-of=kube-prometheus-stack
                        app.kubernetes.io/version=67.5.0
                        chart=kube-prometheus-stack-67.5.0
                        helm.toolkit.fluxcd.io/name=kube-prometheus-stack
                        helm.toolkit.fluxcd.io/namespace=prometheus
                        heritage=Helm
                        release=kube-prometheus-stack
Annotations:            deployment.kubernetes.io/revision: 17
                        meta.helm.sh/release-name: kube-prometheus-stack
                        meta.helm.sh/release-namespace: prometheus
Selector:               app=kube-prometheus-stack-operator,release=kube-prometheus-stack
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=kube-prometheus-stack-operator
                    app.kubernetes.io/component=prometheus-operator
                    app.kubernetes.io/instance=kube-prometheus-stack
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=kube-prometheus-stack-prometheus-operator
                    app.kubernetes.io/part-of=kube-prometheus-stack
                    app.kubernetes.io/version=67.5.0
                    chart=kube-prometheus-stack-67.5.0
                    heritage=Helm
                    release=kube-prometheus-stack
  Annotations:      kubectl.kubernetes.io/restartedAt: 2024-10-02T19:53:21-05:00
  Service Account:  kube-prometheus-stack-operator
  Containers:
   kube-prometheus-stack:
    Image:      quay.io/prometheus-operator/prometheus-operator:v0.79.2
    Port:       10250/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kube-prometheus-stack-kubelet
      --kubelet-endpoints=true
      --kubelet-endpointslice=false
      --localhost=127.0.0.1
      --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.79.2
      --config-reloader-cpu-request=0
      --config-reloader-cpu-limit=0
      --config-reloader-memory-request=0
      --config-reloader-memory-limit=0
      --thanos-default-base-image=quay.io/thanos/thanos:v0.37.2
      --secret-field-selector=type!=kubernetes.io/dockercfg,type!=kubernetes.io/service-account-token,type!=helm.sh/release.v1
      --web.enable-tls=true
      --web.cert-file=/cert/cert
      --web.key-file=/cert/key
      --web.listen-address=:10250
      --web.tls-min-version=VersionTLS13
    Liveness:   http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      GOGC:  30
    Mounts:
      /cert from tls-secret (ro)
  Volumes:
   tls-secret:
    Type:          Secret (a volume populated by a Secret)
    SecretName:    kube-prometheus-stack-admission
    Optional:      false
  Node-Selectors:  <none>
  Tolerations:     <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  kube-prometheus-stack-operator-d8787b99b (0/0 replicas created), kube-prometheus-stack-operator-76bf64f57d (0/0 replicas created), kube-prometheus-stack-operator-86bfc9c754 (0/0 replicas created), kube-prometheus-stack-operator-7d5857db64 (0/0 replicas created), kube-prometheus-stack-operator-7f5b4b745f (0/0 replicas created), kube-prometheus-stack-operator-7f5bd7d77 (0/0 replicas created), kube-prometheus-stack-operator-77bb57589 (0/0 replicas created), kube-prometheus-stack-operator-7dfd4ffd9c (0/0 replicas created), kube-prometheus-stack-operator-79bfb57995 (0/0 replicas created), kube-prometheus-stack-operator-7b9fd876c7 (0/0 replicas created)
NewReplicaSet:   kube-prometheus-stack-operator-5cc4fbfc87 (1/1 replicas created)
Events:
  Type    Reason             Age                   From                   Message
  ----    ------             ----                  ----                   -------
  Normal  ScalingReplicaSet  10m                   deployment-controller  Scaled up replica set kube-prometheus-stack-operator-79bfb57995 to 1 from 0
  Normal  ScalingReplicaSet  10m                   deployment-controller  Scaled down replica set kube-prometheus-stack-operator-7b9fd876c7 to 0 from 1
  Normal  ScalingReplicaSet  6m47s (x2 over 113m)  deployment-controller  Scaled up replica set kube-prometheus-stack-operator-5cc4fbfc87 to 1 from 0
  Normal  ScalingReplicaSet  6m44s (x2 over 113m)  deployment-controller  Scaled down replica set kube-prometheus-stack-operator-79bfb57995 to 0 from 1
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-12-11T17:59:15Z"
  compiler: gc
  gitCommit: 70d3cc986aa8221cd1dfb1121852688902d3bf53
  gitTreeState: clean
  gitVersion: v1.32.0
  goVersion: go1.23.4
  major: "1"
  minor: "32"
  platform: darwin/arm64
kustomizeVersion: v5.5.0
serverVersion:
  buildDate: "2024-08-14T18:57:35Z"
  compiler: gc
  gitCommit: a51b3b711150f57ffc1f526a640ec058514ed596
  gitTreeState: clean
  gitVersion: v1.30.4
  goVersion: go1.22.5
  major: "1"
  minor: "30"
  platform: linux/amd64
```

### Kubernetes Cluster Type

Other (please comment)

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: my-alertmanager
spec:
  receivers:
    - name: pushover-receiver
      pushoverConfigs:
        - userKey:
            name: prometheus-alertmanager-secrets
            key: pushover_user_key
          token:
            name: prometheus-alertmanager-secrets
            key: pushover_token
          retry: "5m"
          priority: "1"

  route:
    receiver: pushover-receiver

    groupBy: [alertname, datacenter, service]
    groupInterval: 5m
    groupWait: 30s

    repeatInterval: 3h

    routes:
      - receiver: pushover-receiver
        continue: true
```

### prometheus-operator log output

```shell
ts=2024-12-28T23:21:19.015266684Z level=info caller=/workspace/pkg/prometheus/server/operator.go:766 msg="sync prometheus" component=prometheus-controller key=prometheus/kube-prometheus-stack-prometheus
ts=2024-12-28T23:21:19.042093211Z level=info caller=/workspace/pkg/alertmanager/operator.go:544 msg="sync alertmanager" component=alertmanager-controller key=prometheus/kube-prometheus-stack-alertmanager
```

### Anything else?

Deployment type is KubeSpray.

The operator itself has no interesting output, just the usual syncing resources messages.

Using the `prometheus-operator-crds` and `kube-prometheus-stack` charts:

```
 helm -n prometheus list                                                                                                                                                                       !819
NAME                    	NAMESPACE 	REVISION	UPDATED                                	STATUS  	CHART                          	APP VERSION
kube-prometheus-stack   	prometheus	47      	2024-12-28 23:15:09.710720856 +0000 UTC	deployed	kube-prometheus-stack-67.5.0   	v0.79.2
prometheus-operator-crds	prometheus	5       	2024-12-28 21:16:54.364614762 +0000 UTC	deployed	prometheus-operator-crds-17.0.2	v0.79.2
```
