### ISSUE TITLE
AlertmanagerConfig's msteams optional webhookurl secret is not respected

### ISSUE THREAD

**Issue by Fresa** [prometheus-operator/prometheus-operator#7264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
The MS teams receiver includes a [field for referring the webhook url](https://github.com/prometheus-community/helm-charts/blob/d2556fe19b34948e17d5b21c46bf22ea859858a5/charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml#L1958) from a Kubernetes secret which includes an [optional](https://github.com/prometheus-community/helm-charts/blob/d2556fe19b34948e17d5b21c46bf22ea859858a5/charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml#L1974) field which is described as _Specify whether the Secret or its key must be defined_. When setting this field to true I'm under the impression that the operator should ignore trying to read it if it cannot find it, but instead it produces an error log and doesn't create the alertmanager instance.

`2025-01-08 14:23:09.205 | ts=2025-01-08T13:23:09.205375835Z level=error caller=/workspace/pkg/operator/resource_reconciler.go:557 msg="Unhandled Error" logger=UnhandledError err="sync \"monitoring/kube-prometheus-stack-alertmanager\" failed: provision alertmanager configuration: failed to initialize from global AlertmangerConfig: MSTeamsConfig[0]: unable to get secret \"alertmanager-msteams-webhook\": secrets \"alertmanager-msteams-webhook\" not found"
`

We're using a secret store CSI driver to mount the webhook url and sync it to the described secret. But this doesn't happen until the [pod starts](https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret), which doesn't happen due to the secret not existing.

We are eagerly waiting for the support of using a [file reference](https://github.com/prometheus-operator/prometheus-operator/pull/6346) instead, but until then we're stuck with the secret.

## Steps to Reproduce
Define an AlertmanagerConfig with a msteams receiver:
```
  receivers:
  - name: Teams
    msteamsConfigs:
    - webhookUrl: 
        key: url
        # Read from secret
        name: alertmanager-msteams-webhook
        optional: true
      title: Foo
      text: Bar
```
Use the kube-prometheus-stack helm chart with 
```
alertmanager:
  alertmanagerSpec:
    alertmanagerConfiguration:
      name: <alertmangerconfig name>
```

Tested with kube-prometheus-stack 65.3.2 (using prometheus-operator v0.77.1). I've also tested referring the latest prometheus-operator image (v0.79.2).

## Expected Result
The alertmanager instance is created even though the secret is missing as it's declared optional.

## Actual Result
The alertmanager instance is not created and the operator produces the above error log continuously.

### Prometheus Operator Version

```shell
Tested with v0.77.1 and v0.79.2
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-03-15T00:08:19Z"
  compiler: gc
  gitCommit: 6813625b7cd706db5bc7388921be03071e1a492d
  gitTreeState: clean
  gitVersion: v1.29.3
  goVersion: go1.21.8
  major: "1"
  minor: "29"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-10-23T15:29:14Z"
  compiler: gc
  gitCommit: 00f20d443ba0cbc485d6ce36a7d3f9a9c4e8ed7a
  gitTreeState: clean
  gitVersion: v1.30.6
  goVersion: go1.22.8
  major: "1"
  minor: "30"
  platform: linux/amd64
```

### Kubernetes Cluster Type

AKS

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### prometheus-operator log output

```shell
2025-01-08 14:23:09.205 | ts=2025-01-08T13:23:09.205375835Z level=error caller=/workspace/pkg/operator/resource_reconciler.go:557 msg="Unhandled Error" logger=UnhandledError err="sync \"monitoring/kube-prometheus-stack-alertmanager\" failed: provision alertmanager configuration: failed to initialize from global AlertmangerConfig: MSTeamsConfig[0]: unable to get secret \"alertmanager-msteams-webhook\": secrets \"alertmanager-msteams-webhook\" not found"
```
