### ISSUE TITLE
Enable shared volume mount feature on ThanosRuler kind

### ISSUE THREAD

**Issue by prasadrajesh** [prometheus-operator/prometheus-operator#7266]
### Component(s)

ThanosRuler

### What is missing? Please describe.

**What is working :**
I wanted to run thanos-ruler pods in active-standby mode. This feature doesn't supported by Thanos-ruler. So, I made a script which basically run on startup of pod and works fine as I expected. (This is not my issue)

**Why do I want to do:**
Two active pods of thanos-ruler are causing high CPU usage on Thanos-query and Thanos-Receiver. So, I want to keep running one pod of thanos-ruler as active mode and other pod should be keep run in standby mode.

**Problem statement:**
The above solution is working. 
As I said before from two pods pod-1 is working as active mode. when restart happen the standby pod (pod-2) may become active pod and in this condition I will missed two hours of WAL data due to it was stored on pod-1 and active is pod-2. 
So, I want to use shared volume like Azure fileshare to mount same pvc on both pods (pod-1 and pod-2)   

## Environment
Kubernetes Version: v1.30.3
Prometheus-Operator Version: v0.79.0

**Comment by nicolastakashi** [comment]
Interesting use case, I have mixed feeling but It seems like a legitimate reason to me, wdyt @simonpasquier ?

**Comment by simonpasquier** [comment]
How does it work in practice today (ideally share the ThanosRuler definition)? What are exactly the missing API to accomplish this?

It's not something that I would run personally and I'd rather look at optimizing the rules and the query performances.

**Comment by prasadrajesh** [comment]
Hi @simonpasquier ,

**Without any hack**
```
spec:
  additionalArgs:
  - name: enable-auto-gomemlimit
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - thanos-ruler
          - key: thanos-ruler
            operator: In
            values:
            - prometheus-operator-thanos-ruler
        topologyKey: kubernetes.io/hostname
  alertDropLabels:
  - thanos_ruler_replica
  alertQueryUrl: https://xxxxxxx.xxx.com
  alertmanagersUrl:
  - http://alertmanager-prometheus-operator-alertmanager-0.alertmanager-operated.monitoring-system.svc.cluster.local:9093
  - http://alertmanager-prometheus-operator-alertmanager-1.alertmanager-operated.monitoring-system.svc.cluster.local:9093
  - http://alertmanager-prometheus-operator-alertmanager-2.alertmanager-operated.monitoring-system.svc.cluster.local:9093
  evaluationInterval: 30s
  externalPrefix: http://prometheus-operator-thanos-ruler.monitoring-system:10902
  image: artifactory.prod.cre.az-eastus2.hosting.nuautoco.com/thirdparty-docker-remote/thanos/thanos:v0.37.2
  imagePullSecrets:
  - name: cks-image-pull-secret-bbkbg5gh49
  labels:
    cluster: xxxxxx
    region: na
    thanos_ruler: monitoring-system/thanos-ruler
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  objectStorageConfig:
    key: thanos.yaml
    name: thanos-objectstorage-5mth9fh42c
  paused: false
  portName: web
  queryEndpoints:
  - https://xxxxxxx
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 500Mi
  retention: 4h
  routePrefix: /
  ruleNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: prometheus-operator-thanos-ruler
  storage:
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: disk-ssd
```
The above one will create two disks as below
```
data-thanos-ruler-prometheus-operator-thanos-ruler-0
data-thanos-ruler-prometheus-operator-thanos-ruler-1
```

**The Problem start when I am going to use fileshare which allow to me to mount same volume on both pod.** 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanosruler
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100G
  storageClassName: fileshare-standard
  volumeMode: Filesystem
```
The volumes attribute of the Thanosruler CRD is not allowing me to mount my shared volume at "/thanos/data" as by default Operator is creating emptyDir volume for "/thanos/data" if I will use volumes.

<img width="815" alt="image" src="https://github.com/user-attachments/assets/84740c58-ec62-4bd2-8209-ff37ea1f0051" />

I believe ideally the volume/volumeMount section should allow me to override the default behavior (where If I will not use below section then I should have option to mount custom pvc at "/thanos/data") 
```
storage:
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: disk-ssd
```

**Comment by simonpasquier** [comment]
Ok so If I'm following correctly, the issue is that the operator will always mount the `thanos-ruler-<thanos ruler name>-data` volume into the Thanos container. One way to allow your use case would be to add a field to the storage spec saying "don't mount the storage volume".

**Comment by prasadrajesh** [comment]
@simonpasquier , Yes correct The operator will always mount the thanos-ruler-<thanos ruler name>-data volume into the Thanos container.

Sorry, I am not following "One way to allow your use case would be to add a field to the storage spec saying don't mount the storage volume". 

How can I mount fileshare based PVC to both pods at same time with this operator?

**Comment by simonpasquier** [comment]
> How can I mount fileshare based PVC to both pods at same time with this operator?

I'm suggesting that we extend the CRD so you can do something like

````
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteMany
---
apiVersion: monitoring.coreos.com/v1
kind: ThanosRuler
metadata:
  name: example
spec:
  storage:
    persistentVolumeClaimName: myclaim # the operator would add a volume to the PVC and mount it at "/thanos/data"
````

would this work for you? As I wrote before, I'm not an expert in storage configuration.
