### ISSUE TITLE
Unable to add a new service to be monitored with kube-prometheus

### ISSUE THREAD

**Issue by shadycuz** [prometheus-operator/prometheus-operator#731]
**What did you do?**
Created a new servicemonitor

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sanguine-butterfly-traefik-dashboard
  labels:
    app: sanguine-butterfly-traefik
spec:
  selector:
    matchLabels:
      app: sanguine-butterfly-traefik
  endpoints:
  - port: 8080
    interval: 10s
```
**What did you expect to see?**
I expected to see it appear in the prometheus dashboard under targets
**What did you see instead? Under which circumstances?**
Nothing changed
**Environment**

* Kubernetes version information:
1.8.1

* Kubernetes cluster kind: 
kubespray

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
E1106 21:21:42.632764       1 reflector.go:201] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:278: Failed to list *v1.ServiceMonitor: json: cannot unmarshal number into Go struct field Endpoint.port of type string
```

after seeing the operator logs I changed port to `-port: "8080"` . Then the error went away but I still did not see my target show up.

New logs
```
Go struct field Endpoint.port of type string
E1106 21:21:42.632764       1 reflector.go:201] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:278: Failed to list *v1.ServiceMonitor: json: cannot unmarshal number into Go struct field Endpoint.port of type string
ts=2017-11-06T21:21:43Z caller=operator.go:670 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-11-06T21:21:43Z caller=operator.go:979 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-11-06T21:21:43Z caller=operator.go:670 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-11-06T21:21:44Z caller=operator.go:979 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-11-06T21:21:53Z caller=operator.go:321 component=alertmanageroperator msg="Alertmanager updated" key=monitoring/main
ts=2017-11-06T21:21:53Z caller=operator.go:377 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
ts=2017-11-06T21:23:20Z caller=operator.go:326 component=prometheusoperator msg="Prometheus updated" key=monitoring/k8s
ts=2017-11-06T21:23:20Z caller=operator.go:670 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-11-06T21:23:21Z caller=operator.go:979 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-11-06T21:23:23Z caller=operator.go:670 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-11-06T21:23:23Z caller=operator.go:979 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-11-06T21:23:23Z caller=operator.go:670 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-11-06T21:23:23Z caller=operator.go:979 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-11-06T21:23:36Z caller=operator.go:321 component=alertmanageroperator msg="Alertmanager updated" key=monitoring/main
ts=2017-11-06T21:23:36Z caller=operator.go:377 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
```

**Comment by shadycuz** [comment]
Okay... so I found this https://coreos.com/blog/the-prometheus-operator.html which says I need to tell the operator what servicemonitors I want to be embedded into my config. It has...
```
serviceMonitors:
  - selector:
      matchLabels:
        tier: frontend
```

then when I check the kube-prometheus files the default prometheus has...

```
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
```

So how do I include my new servicemonitor? I was going to try 
```
- {key: app, value: sanguine-butterfly-traefik}
```

but idk if thats right, cant find any documentation for it.

**Comment by shadycuz** [comment]
Hmm that failed
```
serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
    - {key: app, value: sanguine-butterfly-traefik}
```
```
E1106 22:17:59.409073       1 operator.go:577] Sync "monitoring/k8s" failed: creating config failed: selecting ServiceMonitors failed: "" is not a valid pod selector operator
```

**Comment by shadycuz** [comment]
So this caused a bunch of updates in prometheus-operator but now I have 0 targets

```
serviceMonitorSelector:
    matchLabels:
      app: sanguine-butterfly-traefik
    matchExpressions:
    - {key: k8s-app, operator: Exists}
```

**Comment by shadycuz** [comment]
Tried this 
```
serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
    - {key: app, operator: In, values: [sanguine-butterfly-traefik]}
```

still not targets, does serviceMonitorSelector take a list or something?

**Comment by shadycuz** [comment]
Finally gave in and labeled my servicemonitor as k8s-app that didn't work either, but at least it's in the config now... 

```
- job_name: monitoring/sanguine-butterfly-traefik-dashboard/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - monitoring
  scrape_interval: 10s
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app
    regex: sanguine-butterfly-traefik
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: "8080"
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - target_label: endpoint
    replacement: "8080"
```

I noticed the namespace says `  - monitoring` so I changed my servicemonitor to ...

```
namespaceSelector:
    any: true
```
as per the docs.... and that doesn't work either. 
```
- job_name: monitoring/sanguine-butterfly-traefik-dashboard/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names: []
```
