### ISSUE TITLE
Wrong web.console.* settings for prometheus >= 3.0.0

### ISSUE THREAD

**Issue by TheMeier** [prometheus-operator/prometheus-operator#7319]
### Is there an existing issue for this?

- [x] I have searched the existing issues

## Description

Values for `web.console.templates` and `web.console.libraries` command line arguments are set to /etc/prometheus/consoles and /etc/prometheus/consoles_libraries. These locations where symlinks in the official prometheus container images until version 3.x With versions >= 3.0.0 these symlinks no longer exist.

### Prometheus Operator Version

```shell
Image:         quay.io/prometheus-operator/prometheus-operator:v0.78.2
    Image ID:      quay.io/prometheus-operator/prometheus-operator@sha256:ec69d3f89a28b16b2f43877eef0cbeeaea124f6b20fe641dc03ff1755bd374bd
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-07-17T00:06:19Z"
  compiler: gc
  gitCommit: 4e4a18878ce330fefda1dc46acca88ba355e9ce7
  gitTreeState: clean
  gitVersion: v1.29.7
  goVersion: go1.22.5
  major: "1"
  minor: "29"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-10-22T20:26:48Z"
  compiler: gc
  gitCommit: 00f20d443ba0cbc485d6ce36a7d3f9a9c4e8ed7a
  gitTreeState: clean
  gitVersion: v1.30.6
  goVersion: go1.22.8
  major: "1"
  minor: "30"
  platform: linux/amd64
```

### Kubernetes Cluster Type

Other (please comment)

### How did you deploy Prometheus-Operator?

yaml manifests

### Manifests

```yaml

```

### prometheus-operator log output

```shell
Not relevant
```
