### ISSUE TITLE
Prometheus Operator CRD issue

### ISSUE THREAD

**Issue by kallaics** [prometheus-operator/prometheus-operator#7344]
### Is there an existing issue for this?

- [x] I have searched the existing issues

## Description

I try to use the AlertmanagerConfig CRD and it looks like it has some mapping issue. It works, when I configure it directly in the values yaml. When I convert the configuration to the AlertmanagerConfig CRD and I deploy it, then the configuration wil not the same. The issue affected most of the configuration parameter under the `route` section.  

I assume the issue somewhere the AlermanagerConfig CRD mapping to the configuration. The configuration merged one level deeper than needed. Please see the next section with an example configuration, it will present the issue.

## Steps to Reproduce

1. Create Alertmanager CRD (configuration is default, nothing special)
2. Create AlertmanagerConfig CRD with route configuration (routes receivers, groupby options etc)
3. Deploy the Prometheus Operator
4. Deploy CRDS and see the Alertmanager configuration secret (the "route" level will be on wrong level (indentation), so it will be ignored) 

AlertmanagerConfig CRD version

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.1
    operator.prometheus.io/version: 0.80.0
  labels:
    helm.toolkit.fluxcd.io/name: prometheus
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: alertmanagerconfigs.monitoring.coreos.com
spec:
  conversion:
    strategy: None
  group: monitoring.coreos.com
  names:
    categories:
    - prometheus-operator
    kind: AlertmanagerConfig
    listKind: AlertmanagerConfigList
    plural: alertmanagerconfigs
    shortNames:
    - amcfg
    singular: alertmanagerconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
  ...
```

## Actual Result
Example configuration:

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config
  namespace: monitoring
spec:
  route:
    receiver: "null"
    groupBy:
      - alertname
      - env
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 5m
    routes:
      - matchers:
          - name: alertname
            matchType: "="
            value: Watchdog
        receiver: "null"
        continue: false
  receivers:
    - name: "null"
```

Current result /etc/alertmanager/config_out/alertmanager.env.yaml

```yaml
global:
  resolve_timeout: 5m
route:
  receiver: "null"
  group_by:
  - namespace
  routes:
   # It is wrong mapping and create routes, but it is not a route, just the groupBy configuration
  - receiver: monitoring/config/null
    group_by:
    - alertname
    - env
    matchers:
    - namespace="monitoring"
    # Until this point
    continue: true                                    #  implemented probably wrong level and not override the config
    routes:                                           #  implemented probably wrong level and not override the config
    - receiver: monitoring/config/null
      matchers:
      - alertname="Watchdog"
    #  implemented probably wrong level of next item
    group_wait: 30s                                #  implemented probably wrong level and not override the config
    group_interval: 5m                             #  implemented probably wrong level and not override the config
    repeat_interval: 5m                            #  implemented probably wrong level and not override the config
  - receiver: "null"
    matchers:
    - alertname = "Watchdog"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
```
## Expected Result

Expected result in /etc/alertmanager/config_out/alertmanager.env.yaml

```yaml
global:
  resolve_timeout: 5m
route:
  receiver: "null"
  group_by:
  - alertname
  - env
  continue: true
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  routes:
  - receiver: monitoring/config/null
    matchers:
    - alertname="Watchdog"
  - receiver: "null"
    matchers:
    - alertname = "Watchdog"
```

### How to reproduce it?

1. Configure any of the parameters inside the `route` section as AlermanagerConfig CRDS like:

- groupWait
- groupInterval
- repeatInterval
- groupBy
- continue
- routes

2. Deploy a CRDS with AlertmanagerConfiguration CRD.
3. Deploy the kube-prometheus-stack Helm chart.
4. Check the /etc/alertmanager/config_out/alertmanager.env.yaml file the alertmanager container.

### Enter the changed values of values.yaml?

No changes in values yaml. 
Created CRDs for the configuration

### Enter the command that you execute and failing/misfunctioning.

Create a default configuration

```bash
cat << EOF > alertmanagerconfig.yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config
spec:
  route:
    receiver: "null"
    groupBy:
      - alertname
      - env
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 5m
    routes:
      - matchers:
          - name: alertname
            matchType: "="
            value: Watchdog
        receiver: "null"
        continue: false
  receivers:
    - name: "null"
EOF
```

Deploy the prometheus-operator

```bash
kubectl apply -f alermanagerconfig.yaml -n monitoring
helm install prometheus prometheus-community/prometheus-operator --namespace monitoring --values values.yaml
```

### Prometheus Operator Version

```shell
v0.80.0
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2025-01-15T14:31:54Z"
  compiler: gc
  gitCommit: e9c9be4007d1664e68796af02b8978640d2c1b26
  gitTreeState: clean
  gitVersion: v1.32.1
  goVersion: go1.23.4
  major: "1"
  minor: "32"
  platform: darwin/arm64
kustomizeVersion: v5.5.0
serverVersion:
  buildDate: "2024-12-02T23:17:46Z"
  compiler: gc
  gitCommit: 0c76c645d5a665cfeb736719b1cc47354193dc9a
  gitTreeState: clean
  gitVersion: v1.30.7
  goVersion: go1.22.8
  major: "1"
  minor: "30"
  platform: linux/amd64
```

### Kubernetes Cluster Type

AKS

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### Manifests

```yaml
alertmanagerconfigs.monitoring.coreos.com/v1alpha1
```

### prometheus-operator log output

```shell
Not report any issue. Just maps the CRD configuration to the Alertmanager configuration on wrong level, so it will be ignored by Alertmanager.
```

**Comment by simonpasquier** [comment]
I suppose that it's more a question for the Helm chart. From what I can tell, your `config` AlertmanagerConfig resource is used in this [scenario](https://prometheus-operator.dev/docs/developer/alerting/#using-alertmanagerconfig-resources) while you expected https://prometheus-operator.dev/docs/developer/alerting/#using-alertmanagerconfig-for-global-configuration

**Comment by kallaics** [comment]
I am using Alertmanager resource for Alertmanager deployment configs (as expected) and I am using the AlertmanagerConfig for configuration of Alertmanager.  No mixed configuration here. The configuration items allowed in CRDS, so I don't mean it is is a configuration issue.

The issue is simple. Looks like the merge happens on wrong level and that cause the invalid configuration for Alertmanager application. 

For example without exact configuration:

```yaml
mydict:
  config:
    config1: value1 
    config2: value2
    route:
      key: value
      list1:
        - item1
        - item2
```

Expected result as (valid configuration):

```yaml
mydict:
  config:
    config1: value1 
    config2: value2
    route:
      key: value
      list1:
        - item1
        - item2
```

Real result:

```yaml
mydict:
  config:
    route:
      config1: value1 
      config2: value2
      key: value
      list1:
        - item1
        - item2
```

So it looks like the supported configuration merged to the wrong level.
