### ISSUE TITLE
While "kubectl apply -f bundle.yaml" getting "Too long: must have at most 262144 bytes"

### ISSUE THREAD

**Issue by dashimanshu** [prometheus-operator/prometheus-operator#7363]
## Description
Seems like the size of the bundle yaml is too big to install. 

## Steps to Reproduce

1. download https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.80.1/bundle.yaml
2.  Run "kubectl apply -f bundle.yaml"
## Expected Result
Should get installed without error 
## Actual Result
[cicd@dev1 ~]$ kubectl apply -f bundle.yaml
customresourcedefinition.apiextensions.k8s.io/podmonitors.monitoring.coreos.com unchanged
customresourcedefinition.apiextensions.k8s.io/probes.monitoring.coreos.com unchanged
customresourcedefinition.apiextensions.k8s.io/prometheusrules.monitoring.coreos.com unchanged
customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com unchanged
clusterrolebinding.rbac.authorization.k8s.io/prometheus-operator unchanged
clusterrole.rbac.authorization.k8s.io/prometheus-operator unchanged
deployment.apps/prometheus-operator unchanged
serviceaccount/prometheus-operator unchanged
service/prometheus-operator unchanged
Error from server (Invalid): error when creating "bundle.yaml": CustomResourceDefinition.apiextensions.k8s.io "alertmanagerconfigs.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
Error from server (Invalid): error when creating "bundle.yaml": CustomResourceDefinition.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
Error from server (Invalid): error when creating "bundle.yaml": CustomResourceDefinition.apiextensions.k8s.io "prometheusagents.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
Error from server (Invalid): error when creating "bundle.yaml": CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
Error from server (Invalid): error when creating "bundle.yaml": CustomResourceDefinition.apiextensions.k8s.io "scrapeconfigs.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
Error from server (Invalid): error when creating "bundle.yaml": CustomResourceDefinition.apiextensions.k8s.io "thanosrulers.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
[cicd@dev1 ~]$

### Prometheus Operator Version

```shell
v0.80.1
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-10-22T20:34:56Z"
  compiler: gc
  gitCommit: 841856557ef0f6a399096c42635d114d6f2cf7f4
  gitTreeState: clean
  gitVersion: v1.28.15
  goVersion: go1.22.8
  major: "1"
  minor: "28"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2024-10-22T20:26:27Z"
  compiler: gc
  gitCommit: 841856557ef0f6a399096c42635d114d6f2cf7f4
  gitTreeState: clean
  gitVersion: v1.28.15
  goVersion: go1.22.8
  major: "1"
  minor: "28"
  platform: linux/amd64
```

### Kubernetes Cluster Type

kubeadm

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### Manifests

```yaml

```

### prometheus-operator log output

```shell
NIL
```
