### ISSUE TITLE
Feat: auto-gomemlimit.ratio Cannot Be Set

### ISSUE THREAD

**Issue by aydosman** [prometheus-operator/prometheus-operator#7378]
### Component(s)

AlertManager

### What is missing? Please describe.

ref: https://github.com/prometheus/alertmanager/pull/3895

When using enableFeatures in alertmanager.alertmanagerSpec the `auto-gomemlimit` feature flag successfully enables the feature. Attempting to set the `--auto-gomemlimit.ratio` flag requires modifying args in containers, which completely replaces the default arguments set by the Prometheus Operator.

For example enabling the feature works:

```
alertmanager:
  alertmanagerSpec:
    enableFeatures:
      - auto-gomemlimit
```

Setting the ratio:

```
alertmanager:
  alertmanagerSpec:
    enableFeatures:
      - auto-gomemlimit
    containers:
      - name: alertmanager
        args:
          - --auto-gomemlimit.ratio=0.9

```

removes all default args, causing Alertmanager to break.

Maybe an additionalArgs field (similar to additionalConfig) that appends extra CLI flags without removing the default ones.

### Describe alternatives you've considered.

Tried a number of work arounds, with no avail. 

## Environment
Kubernetes Version: 1.29-1.32
Prometheus-Operator Version: [0.80.0 / 2025-02-04](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.80.0)
