### ISSUE TITLE
Probe CRD configuration gets ignored

### ISSUE THREAD

**Issue by OneOfTheJohns** [prometheus-operator/prometheus-operator#7403]
## Description
I have applied "Probe" CRD manifest against my cluster where prometheus-operator is being hosted.
But i cannot see any updates on the "targets" page of prometheus.
Strangely enough, while i was doing some troubleshooting, i was changing the `release` value multiple times, and at some point, for some time, i was able to see the "Probe" in targets for prometheus, but was not able to find again what was the fix...

## Steps to Reproduce
Apply the same configuration

## Expected Result
New monitoring targets should appear on "targets" page of prometheus UI.

## Actual Result
Configuration gets applied to the cluster but no new targets appear on UI.

### Prometheus Operator Version

```shell
app.kubernetes.io/version=62.3.1-e-v3.9.2
chart=kube-prometheus-stack-62.3.1-e-v3.9.2
```

### Kubernetes Version

```yaml
v1.30.9-eks-8cce635
```

### Kubernetes Cluster Type

EKS

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
    release: prometheus # https://github.com/prometheus-community/helm-charts/issues/408#issuecomment-751848253
  name: blackbox-exporter-probe
  namespace: monitoring
spec: 
  ### required
  jobName: http-get
  interval: 60s
  module: http_2xx
  prober: 
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115
    scheme: http
    path: /probe
  targets: 
    staticConfig:
      static:
        - https://test.com/
        - https://www.google.com/
```

### prometheus-operator log output

```shell
ts=2025-03-11T13:47:43.767676429Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/server/operator.go:808 msg="sync prometheus" component=prometheus-controller key=monitoring/kube-prometheus-stack-prometheus
ts=2025-03-11T13:47:44.009748314Z level=info caller=/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/server/operator.go:808 msg="sync prometheus" component=prometheus-controller key=monitoring/kube-prometheus-stack-prometheus
```
