### ISSUE TITLE
Alerts are not sent to telegram

### ISSUE THREAD

**Issue by dmitriy-shleht** [prometheus-operator/prometheus-operator#7447]
## Description
I can't figure out what my problem is, whether it's a bug or a configuration issue. On the previous version (0.74.0), the same configuration worked correctly. The problem is that alerts are not sent to Telegram, but are sent to null and Grafana somehow strangely creates a policy.

![Image](https://github.com/user-attachments/assets/1eb4d40c-15f0-4229-87e6-1723b50fed08)

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alert-config-telegram
  namespace: monitoring
  labels:
    release: prometheus-stack
    alertmanagerConfig: alertmanager-telegram
spec:
  route:
    groupBy: ["alertname","job","namespace"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 30m
    receiver: "telegram"
  receivers:
    - name: telegram
      telegramConfigs:
        - botToken:
            name: telegram-bot-token
            key: token
          chatID: ***
          sendResolved: true
```

### Prometheus Operator Version

```shell
0.81.0
```

### Kubernetes Version

```yaml
RKE2 v1.27.12
```

### Kubernetes Cluster Type

Rancher

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml

```

### prometheus-operator log output

```shell
# There are no errors in the log
2025-04-08T16:53:41.081+03:00[alertmanager]time=2025-04-08T13:53:41.079Z level=INFO source=coordinator.go:112 msg="Loading configuration file" component=configuration file=/etc/alertmanager/config_out/alertmanager.env.yaml
2025-04-08T16:53:41.081+03:00[alertmanager]time=2025-04-08T13:53:41.081Z level=INFO source=coordinator.go:125 msg="Completed loading of configuration file" component=configuration file=/etc/alertmanager/config_out/alertmanager.env.yaml
2025-04-08T17:08:58.072+03:00[alertmanager]time=2025-04-08T14:08:58.071Z level=INFO source=coordinator.go:112 msg="Loading configuration file" component=configuration file=/etc/alertmanager/config_out/alertmanager.env.yaml
2025-04-08T17:08:58.074+03:00[alertmanager]time=2025-04-08T14:08:58.073Z level=INFO source=coordinator.go:125 msg="Completed loading of configuration file" component=configuration file=/etc/alertmanager/config_out/alertmanager.env.yaml
```

**Comment by dmitriy-shleht** [comment]
By experimenting, I determined that alerts are not included because `namespace = 'monitoring`. How do I override it?

**Comment by cdivitotawela** [comment]
Looks like I have the same issue. Installed in kind cluster using Helm chart kube-prometheus-stack-70.7.0

I create this PrometheusRule where you can see only one label teams=ops. 
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: observability
    prometheus-operator-validated: "true"
  labels:
    app: kube-prometheus-stack
    release: prometheus-stack
  name: container-cpu-usage-seconds-tot
  namespace: observability
spec:
  groups:
  - name: container_memory_usage
    rules:
    - alert: container memory usage high
      expr: sum(container_memory_rss{container="alertmanager",pod="alertmanager-prometheus-stack-kube-prom-alertmanager-0"}) > 10000000
      for: 10s
      annotations:
        summary: '[blockchain] high memory usage container - alertmanager'
      labels:
        team: ops
```

On the AlertmanagerConfig, my route only has the matcher `team=ops`
```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: opsgenie
  labels:
    alertmanagerConfig: opsgenie
spec:
  route:
    receiver: 'opsgenie'
    groupBy: ['alertname']
    groupWait: 10s
    groupInterval: 1m
    repeatInterval: 2m
    matchers:
    - name: team
      value: ops
      matchType: =
  receivers:
  - name: 'opsgenie'
    opsgenieConfigs:
      - message: "This is summary"
        description: This is the description
        sendResolved: true
        apiKey:
          name: opsgenie-api-key
          key: api-key
        apiURL: 'http://mitmproxy:8080'
```

However the generated Alertmanager config at /etc/alertmanager/config_out/alertmanager.env.yaml has following where it has added additional matchers `namespace=observability`.  Given default receiver is null, it looks like all alerts sent to null receiver as matcher include the namespace as well. So far I haven't been able to figure out why the namespace is automatically added to the matchers.

```yaml
global:
  resolve_timeout: 5m
route:
  receiver: "null"
  group_by:
  - namespace
  routes:
  - receiver: observability/opsgenie/opsgenie
    group_by:
    - alertname
    matchers:
    - team="ops"
    - namespace="observability"
    continue: true
    group_wait: 10s
    group_interval: 1m
    repeat_interval: 2m
  - receiver: "null"
    matchers:
    - alertname = "Watchdog"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
...
receivers:
- name: "null"
- name: observability/opsgenie/opsgenie
  opsgenie_configs:
  - send_resolved: true
    api_key: xxxxxxxxxx
    api_url: http://mitmproxy:8080
    message: This is summary
    description: This is the description
```
