### ISSUE TITLE
prometheus-operator  running with error "failed to apply prometheus status subresource..."

### ISSUE THREAD

**Issue by suuuy** [prometheus-operator/prometheus-operator#7450]
## Description

The prometheus-community/kube-prometheus-stack package installed by helm is version 70.4.2, and the prometheus-operator image version is v0.81.0. The prometheus-operator can start normally, but the log reports an error. No suitable solution was found on Google and AI tools through the log error information. I would like to ask what the possible cause of this error is?

## Expected Result

service runing without error

## Actual Result

with error info "failed: failed to apply prometheus status subresource: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json"

### Prometheus Operator Version

```shell
Name:                   coding-prometheus-operator
Namespace:              coding-observable
CreationTimestamp:      Thu, 10 Apr 2025 18:13:43 +0800
Labels:                 app=coding-prometheus-operator
                        app.kubernetes.io/component=prometheus-operator
                        app.kubernetes.io/instance=kube-prometheus-stack
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=coding-prometheus-prometheus-operator
                        app.kubernetes.io/part-of=coding-prometheus
                        app.kubernetes.io/version=70.4.2
                        chart=kube-prometheus-stack-70.4.2
                        heritage=Helm
                        release=kube-prometheus-stack
Annotations:            deployment.kubernetes.io/revision: 2
                        meta.helm.sh/release-name: kube-prometheus-stack
                        meta.helm.sh/release-namespace: coding-observable
Selector:               app=coding-prometheus-operator,release=kube-prometheus-stack
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=coding-prometheus-operator
                    app.kubernetes.io/component=prometheus-operator
                    app.kubernetes.io/instance=kube-prometheus-stack
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=coding-prometheus-prometheus-operator
                    app.kubernetes.io/part-of=coding-prometheus
                    app.kubernetes.io/version=70.4.2
                    chart=kube-prometheus-stack-70.4.2
                    heritage=Helm
                    release=kube-prometheus-stack
  Service Account:  coding-prometheus-operator
  Containers:
   coding-prometheus:
    Image:      quay.io/prometheus-operator/prometheus-operator:v0.79.2
    Port:       10250/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/coding-prometheus-kubelet
      --kubelet-endpoints=true
      --kubelet-endpointslice=false
      --localhost=127.0.0.1
      --prometheus-config-reloader=registry.tcs.io/image/prometheus-config-reloader:v0.81.0
      --config-reloader-cpu-request=0
      --config-reloader-cpu-limit=0
      --config-reloader-memory-request=0
      --config-reloader-memory-limit=0
      --thanos-default-base-image=registry.tcs.io/image/thanos:v0.37.2
      --secret-field-selector=type!=kubernetes.io/dockercfg,type!=kubernetes.io/service-account-token,type!=helm.sh/release.v1
      --web.enable-tls=true
      --web.cert-file=/cert/cert
      --web.key-file=/cert/key
      --web.listen-address=:10250
      --web.tls-min-version=VersionTLS13
    Liveness:   http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get https://:https/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      GOGC:  30
    Mounts:
      /cert from tls-secret (ro)
  Volumes:
   tls-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coding-prometheus-admission
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   coding-prometheus-operator-6d7c84bdd9 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  34m   deployment-controller  Scaled up replica set coding-prometheus-operator-66c959b7f5 to 1
  Normal  ScalingReplicaSet  31m   deployment-controller  Scaled up replica set coding-prometheus-operator-6d7c84bdd9 to 1
  Normal  ScalingReplicaSet  30m   deployment-controller  Scaled down replica set coding-prometheus-operator-66c959b7f5 to 0
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2024-06-26T06:51:34Z"
  compiler: gc
  gitCommit: 7d2563cd4ff8906413bd39fb54db58d402b70d66
  gitVersion: v1.22.5-7d2563cd
  goVersion: go1.21.5
  major: "1"
  minor: 22+
  platform: linux/amd64
serverVersion:
  buildDate: "2024-06-26T06:52:21Z"
  compiler: gc
  gitCommit: 7d2563cd4ff8906413bd39fb54db58d402b70d66
  gitVersion: v1.22.5-7d2563cd
  goVersion: go1.21.5
  major: "1"
  minor: 22+
  platform: linux/amd64
```

### Kubernetes Cluster Type

kind

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### Manifests

```yaml
prometheusOperator:
  nameOverride: coding-prometheus-operator
  fullnameOverride: coding-prometheus-operator
  replicas: 1
  image:
    registry: registry.tcs.io
    repository: image/prometheus-operator
  prometheusConfigReloader:
    image:
      registry: registry.tcs.io
      repository: image/prometheus-config-reloader
  admissionWebhooks:
    deployment:
      image:
        registry: registry.tcs.io
        repository: image/admission-webhook
    patch:
      image:
        registry: registry.tcs.io
        repository: image/kube-webhook-certgen
  thanosImage:
    registry: registry.tcs.io
    repository: image/thanos
  nodeSelector: *nodeSelector     # 节点选择器
  affinity: *affinity             # 节点亲和性
  tolerations: *tolerations       # 污点容忍
```

### prometheus-operator log output

```shell
ts=2025-04-10T10:38:08.223128405Z level=info caller=/workspace/pkg/alertmanager/operator.go:544 msg="sync alertmanager" component=alertmanager-controller key=coding-observable/coding-prometheus
ts=2025-04-10T10:38:08.229868976Z level=info caller=/workspace/pkg/prometheus/server/operator.go:766 msg="sync prometheus" component=prometheus-controller key=coding-observable/coding-prometheus
ts=2025-04-10T10:38:08.364305588Z level=info caller=/workspace/pkg/alertmanager/operator.go:712 msg="failed to apply alertmanager status subresource, trying again without scale fields" component=alertmanager-controller err="the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json"
ts=2025-04-10T10:38:08.366563399Z level=error caller=/workspace/pkg/operator/resource_reconciler.go:579 msg="Unhandled Error" logger=UnhandledError err="status \"coding-observable/coding-prometheus\" failed: failed to apply alertmanager status subresource: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json"
ts=2025-04-10T10:38:08.37308521Z level=info caller=/workspace/pkg/prometheus/server/operator.go:974 msg="failed to apply prometheus status subresource, trying again without scale fields" component=prometheus-controller err="the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json"
ts=2025-04-10T10:38:08.375444812Z level=error caller=/workspace/pkg/operator/resource_reconciler.go:579 msg="Unhandled Error" logger=UnhandledError err="status \"coding-observable/coding-prometheus\" failed: failed to apply prometheus status subresource: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json"
ts=2025-04-10T10:38:08.462785039Z level=info caller=/workspace/pkg/alertmanager/operator.go:544 msg="sync alertmanager" component=alertmanager-controller key=coding-observable/coding-prometheus
ts=2025-04-10T10:38:08.467709298Z level=info caller=/workspace/pkg/prometheus/server/operator.go:766 msg="sync prometheus" component=prometheus-controller key=coding-observable/coding-prometheus
ts=2025-04-10T10:38:08.545768874Z level=info caller=/workspace/pkg/alertmanager/operator.go:712 msg="failed to apply alertmanager status subresource, trying again without scale fields" component=alertmanager-controller err="the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json"
ts=2025-04-10T10:38:08.547935784Z level=error caller=/workspace/pkg/operator/resource_reconciler.go:579 msg="Unhandled Error" logger=UnhandledError err="status \"coding-observable/coding-prometheus\" failed: failed to apply alertmanager status subresource: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json"
ts=2025-04-10T10:38:08.572027556Z level=info caller=/workspace/pkg/prometheus/server/operator.go:974 msg="failed to apply prometheus status subresource, trying again without scale fields" component=prometheus-controller err="the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json"
ts=2025-04-10T10:38:08.57512771Z level=error caller=/workspace/pkg/operator/resource_reconciler.go:579 msg="Unhandled Error" logger=UnhandledError err="status \"coding-observable/coding-prometheus\" failed: failed to apply prometheus status subresource: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json"
```
