### ISSUE TITLE
Prometheus instance does not load scrape jobs from generated config on EKS 1.30

### ISSUE THREAD

**Issue by rohin-delhivery** [prometheus-operator/prometheus-operator#7634]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

**Description**
After a successful deployment of the kube-prometheus-stack Helm chart, a specific ServiceMonitor in a different namespace (lora) is not being discovered by Prometheus.

We have exhaustively verified every step of the process:

The ServiceMonitor, Service, and application pod are all correctly configured.
The necessary Custom Resource Definitions (CRDs) have been manually applied and are up to date.
RBAC permissions for the Prometheus Operator have been verified and corrected via helm upgrade to allow cluster-wide discovery.

We have proven by inspecting the Secret containing the prometheus.yaml.gz that the Prometheus Operator is successfully generating the correct scrape configuration for the target.

Despite this, and even after a full pod restart and a complete recreation of the StatefulSet and its data volume (PVC), the target never appears in the Prometheus /api/v1/targets endpoint.
The failure appears to be that the running Prometheus process is not loading or activating the valid scrape job from its configuration file.

**Steps to Reproduce**

Deploy kube-prometheus-stack on an EKS 1.30 cluster.
Deploy a custom application and a corresponding ServiceMonitor in a separate namespace (lora).
Observe that the target for the ServiceMonitor does not appear in the Prometheus UI or API, even though all RBAC, CRDs, and configurations appear correct.

Inspect the Prometheus configuration secret (prometheus-kube-prometheus-stack-prometheus) and confirm the scrape job for the ServiceMonitor is present.
Query the running Prometheus instance's /api/v1/targets endpoint and confirm the scrape job is absent.

**Expected Result**

The Prometheus instance should load the configuration generated by the operator, and the target for serviceMonitor/lora/vllm-triton-monitor/0 should appear in the /api/v1/targets API endpoint with a status of "up" or "down".

**Actual Result**
The target for serviceMonitor/lora/vllm-triton-monitor/0 is completely absent from the /api/v1/targets endpoint, as if it doesn't exist in the configuration, even though we have proven it does.

### Prometheus Operator Version

```shell
0.83.0
```

### Kubernetes Version

```yaml
clientVersion:
  buildDate: "2025-06-25T00:00:00Z"
  compiler: gc
  gitCommit: ""
  gitTreeState: clean
  gitVersion: v1.30.0
  goVersion: go1.24.3
  major: "1"
  minor: "30"
  platform: linux/amd64
serverVersion:
  buildDate: "2025-06-18T00:00:00Z"
  compiler: gc
  gitCommit: 5d4a308
  gitTreeState: clean
  gitVersion: v1.30.13-eks-5d4a308
  goVersion: go1.24.3
  major: "1"
  minor: "30"
  platform: linux/amd64
```

### Kubernetes Cluster Type

EKS

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml
- job_name: serviceMonitor/lora/vllm-triton-monitor/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - lora
  scrape_interval: 15s
  metrics_path: /metrics
  relabel_configs:
  - action: keep
    regex: nvidia-triton-server-triton-inference-server-lora-adaptor
    source_labels:
    - __meta_kubernetes_service_name
...



service monitor:

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-triton-monitor
  namespace: lora
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nvidia-triton-server-triton-inference-server-lora-adaptor
      app.kubernetes.io/instance: nvidia-triton-server
  endpoints:
  - port: http-lora-server
    interval: 15s
    path: /metrics


Service Manifest:

apiVersion: v1
kind: Service
metadata:
  name: nvidia-triton-server-triton-inference-server-lora-adaptor
  namespace: lora
  labels:
    helm.sh/chart: triton-inference-server-1.0.0
    app.kubernetes.io/name: nvidia-triton-server-triton-inference-server-lora-adaptor
    app.kubernetes.io/instance: nvidia-triton-server
spec:
  type: ClusterIP
  ports:
  - name: http-lora-server
    port: 8000
    targetPort: http
  selector:
    app.kubernetes.io/name: triton-inference-server-lora-adaptor
    app.kubernetes.io/instance: nvidia-triton-server
```

### prometheus-operator log output

```shell
The operator logs show no errors related to discovering the ServiceMonitor in the lora namespace after the RBAC and CRDs were fixed. It successfully connects to the Kubernetes API and syncs its caches. The logs are clean.


ts=2025-06-25T05:17:37.998501133Z level=info caller=/workspace/cmd/operator/main.go:214 msg="Starting Prometheus Operator" version="(version=0.83.0, branch=, revision=5cf2f5d)"
ts=2025-06-25T05:17:37.999006124Z level=info caller=/workspace/cmd/operator/main.go:227 msg="namespaces filtering configuration " config="{allow_list=\"\",deny_list=\"\"...}"
ts=2025-06-25T05:17:38.0124871Z level=info caller=/workspace/cmd/operator/main.go:268 msg="connection established" kubernetes_version=1.30.13-eks-5d4a308
ts=2025-06-25T05:17:38.271017535Z level=info caller=/workspace/pkg/prometheus/server/operator.go:421 msg="successfully synced all caches" component=prometheus-controller
ts=2025-06-25T05:17:38.742989374Z level=info caller=/workspace/pkg/prometheus/server/operator.go:770 msg="sync prometheus" component=prometheus-controller key=monitoring/kube-prometheus-stack-prometheus
```

### Anything else?

The issue has persisted through multiple restarts of the Prometheus Operator and the Prometheus StatefulSet. We have even gone as far as deleting the Persistent Volume Claim (PVC) for the Prometheus pod to force it to start with a completely fresh, non-corrupted data state, and the issue remains. This suggests the problem is not related to a corrupted on-disk state. Every component appears to be configured correctly, but the running Prometheus process is not reflecting the configuration it is being given.
